### ISSUE TITLE
Admin import preview for fields with default values shows a misleading diff.

### ISSUE THREAD

**Issue by andybak** [django-import-export/django-import-export#100]
I have a field CharField called 'type' with a default set to 'untracked;. 

Say the import for that row sets the value of type to 'tracked' then the preview shows this as a change and displays the diff as being a deletion of the characters 'un'.

I would suggest that for 'new' rows - existing values should be ignored when calculating the diff.

**Comment by domenkozar** [comment]
This is now fixed: https://github.com/django-import-export/django-import-export/pull/345
