### ISSUE TITLE
Remove empty rows automatically from import data sheet

### ISSUE THREAD

**Issue by dxp168** [django-import-export/django-import-export#1005]
Often time in a spreadsheet, empty rows are not noticeable and viewable in MS Excel.  These empty rows cause a problem during the IMPORT from the admin web form.

At current, these empty rows are not filtered out in the dataset, then `dry_run` to the database will cause the database validation error, such as `no null` violation, etc. While after database rejection, the problem should be stopped, instead of continuing to repeat the dry run, finally `timed out`.

Suggestions to fix this problem:
- truncate empty rows of dataset in the `resource.import_data`
- validate against the Model in the `ImportMixin.import_action` before start `resource.import_data`

**Comment by lcmartinezdev** [comment]
I have the same problem. Since the file has too many cells, it causes a lot of memory usage.

As a workaround: 
I'm filtering out the cells after the first empty row in the dataset, but it would be nice if the file could be cleaned up in a better way.
