### ISSUE TITLE
Fix errors in integrity tests

### ISSUE THREAD

**Issue by beruic** [django-import-export/django-import-export#1011]
First of all, I'm not sure this is even caused by this project, but after fixing #1010 it seemed from the error logs that CI should start working again. However, judging from #1007 and #1008 there is an issue with Python 3.3 on the `1.x` branch and Python 3.8-dev on `master`.

The problem with Python 3.8-dev on `master` may be a non-issue since the URL that seems to cause it definitely works now, so could someone please re-run the CI for #1007?

For Python 3.3 on the `1.x` branch, it seems to be caused by [Python 3.3 end of life](https://www.python.org/dev/peps/pep-0398/#x-end-of-life) that in turn causes the binary package to be removed, and the fix seems to be just 

I was considering making this two issues, but since the effort for fixing them seems very small, I could not bring myself to justify it. Right now this issue is mostly for ensuring that this get fixed, and that it is fixed the right way.

**Comment by beruic** [comment]
**Update**

I have verified that the failing for #1007 is periodical, so I will close and reopen the PR to re-run it, since I found out that it is possible to re-run this way. We still need to fix 1.x however.

Proposals for solution:
- Declare 1.x dead and release 2.0 soon.
- Remove support for Python 3.3
- Upgrade travis distribution to `bionic` (Newest LTS so there might be a Python 3.3 package for it in place of the missing one for `xenial`)

Any thoughts?

**Comment by andrewgy8** [comment]
> Proposals for solution:
> 
>     - Declare 1.x dead and release 2.0 soon.
>     - Remove support for Python 3.3
>     - Upgrade travis distribution to bionic (Newest LTS so there might be a Python 3.3 package for it in place of the missing one for xenial)
> 
> Any thoughts?

All of the above!

**Comment by beruic** [comment]
I don't have time for undertaking this. Nor do I have the need anymore, but I'd be sorry to see this staling into oblivion.

Please also take into consideration that `bionic` is soon not the newest LTS, and upgrading to using newer packages should be considered.

**Comment by matthewhegarty** [comment]
Closing since we have since moved CI to Github actions.
