### ISSUE TITLE
0.4.2 no longer supports Python2.7

### ISSUE THREAD

**Issue by m3talstorm** [django-import-export/django-import-export#1012]
django-import-export 0.4.2 

https://github.com/django-import-export/django-import-export/blob/0.4.2/requirements/base.txt

- Requires the latest `tablib` 

https://github.com/jazzband/tablib/blob/master/requirements.txt

- Requires `openpyxl>=2.4.0` 

Which grabs the latest version of openpyxl which is now `3.0.0` (released 25th sept 2019 - https://pypi.org/project/openpyxl/#history) which no longer supports Python 2.7

So 0.4.2 no longer supports Python 2.7 as per the README (https://github.com/django-import-export/django-import-export/blob/0.4.2/README.rst)

**Comment by andrewgy8** [comment]
Hi @m3talstorm ! We dropped Python 2.x support in the previous version if Im not mistaken. And I believe we are no longer maintaining support for it.

**Comment by m3talstorm** [comment]
@andrewgy8 I understand not supporting Python2.7 in later/new releases, but `0.4.2` is a release that did/states that it does support Python2.7.

I would suggest pinning your dependencies so things like this don't happen in the future.

**Comment by andrewgy8** [comment]
Please see https://github.com/django-import-export/django-import-export/issues/923
