### ISSUE TITLE
ValueError encountered while trying to read file: ... - no debugging help

### ISSUE THREAD

**Issue by jbothma** [django-import-export/django-import-export#1018]
When https://github.com/django-import-export/django-import-export/blob/4589d4c40bd5b8ecb1b34e69e5f5e6632217de2c/import_export/admin.py#L299 catches an unexpected exception, it just outputs an error message to the browser, with no information for debugging the cause.

I hacked the library to raise an exception so I can explore it using werkzeug, and it turned out to be bad data.

I think this should output the stacktrace to the django log using something like `logger.exception()` so that devs can debug the issues users are experiencing.

If you're happy with the suggestion I'll send a pull request.

Here's the underlying issue https://github.com/django-import-export/django-import-export/issues/1019

**Comment by andrewgy8** [comment]
Hey @jbothma !
You maybe able to do something like 

```
except Exception as e:
	return HttpResponse(_(u"<h1>%s encountered while trying to read file: %s</h1>" % (type(e).__name__, import_file.name))) from e
```

If that doesnt work, then I think logging an exception is perfectly reasonable. 👍
