### ISSUE TITLE
Prevent new items. Update only.

### ISSUE THREAD

**Issue by jangeador** [django-import-export/django-import-export#1020]
Is there any setting that will allow me to ignore any new items. I would only want to import to update. But let's say that there is a new ID that does not currently exists in the database, I would want to ignore that.

**Comment by max-block** [comment]
I'm interested in the opposite settings. I'd like to import only new items and to prevent updates.

**Comment by jangeador** [comment]
I was able to find a solution using the method `skip_row`

To only update existing items while ignoring any new item I use:
```py3
# Do not import any new items. Only update records
def skip_row(self, instance, original):
	if original.id:
		return False
	return super(BookResource, self).skip_row(instance, original)
```

To import only new items while preventing updates you can use:

```py3
# Only import new items. Do not update any record
def skip_row(self, instance, original):
	if not original.id:
		return False
	return True
```

This assumes your `import_id_fields = ('id',)` and your resource is called `BookResource`
