### ISSUE TITLE
Float and Decimal widgets should use LANGUAGE_CODE

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#1025]
Hi!

When exporting a FloatField, DecimalField, etc. the result uses the `.` as decimal separator. I was just wondering if instead, it should use the decimal separator for `LANGUAGE_CODE` defined in `settings.py`.

https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L58

What do you think?

**Comment by zbynekdrlik** [comment]
+1

**Comment by andrewgy8** [comment]
Yes, I do not see why not. That would make sense to me, and should be quite an easy fix!

**Comment by matthewhegarty** [comment]
This was added in #1501
