### ISSUE TITLE
How can we import a csv file with ANSI encoding

### ISSUE THREAD

**Issue by farhankn** [django-import-export/django-import-export#1026]
I'm trying to import a file that has ANSI encoding, Accented characters like "ç" etc. 

The import shows an error as mentioned below.

> Imported file has a wrong encoding: 'utf-8' codec can't decode byte 0xf3 in position 18710: invalid continuation byte

Changing it to utf-8 breaks the characters into "Blockers"

**Comment by farhankn** [comment]
Team: Any updates

**Comment by andrewgy8** [comment]
Moving the conversation of encoding issues here #1141
