### ISSUE TITLE
Export don't work for queryset with values() method

### ISSUE THREAD

**Issue by CrazySky2121** [django-import-export/django-import-export#1027]
Hello! Exporting fields don't work when queryset used with values() method. This is because when we iterate over queryset we have dict rather than model instance.

I think code in resources.py must be like this:

```python
def export_field(self, field, obj):
        if isinstance(obj, dict):
            return obj.get(field.attribute)
        field_name = self.get_field_name(field)
        method = getattr(self, 'dehydrate_%s' % field_name, None)
        if method is not None:
            return method(obj)
        return field.export(obj)
```

We can't using queryset without values() because this using for GROUP BY. So I think import_export must support it

**Comment by mohammadhasanzadeh** [comment]
Does this issue need to a Pull Request for done resolution?

**Comment by deviirmr** [comment]
Alternatively, instead of defining the value in the query, declare it in the resource class, as it has already been documented [here](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#declare-import-fields).
