### ISSUE TITLE
Bulk insert Log Entries instead of inserting them one by one

### ISSUE THREAD

**Issue by nishanthvijayan** [django-import-export/django-import-export#1032]
Post import, django admin log entries are inserted. However, at the moment, they are inserted one by one. This could be optimized by using Django ORM's bulk_create.

**Comment by matthewhegarty** [comment]
Hi, there's some related discussion [here](#939) if you haven't already seen it.

**Comment by matthewhegarty** [comment]
This behaviour is going to be the default in Django 6.

**Comment by matthewhegarty** [comment]
#1674
