### ISSUE TITLE
Django3.0 compatibility issue

### ISSUE THREAD

**Issue by ShaheedHaque** [django-import-export/django-import-export#1046]
django-import-export 1.2.0 does not work with Django 3.0 because [it dropped its internal version of six](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis).

The following files are affected:

* widgets.py
* admin.py
* resources.py
* base_formats.py

**Comment by andrewgy8** [comment]
Yep, we will need a release for this to be fixed as it was merged to master a while ago. @bmihelac I think its about time for a release. What do you think?

**Comment by bmihelac** [comment]
I agree.

**Comment by andrewgy8** [comment]
2.0 was Released yesterday
