### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by MuslimBeibytuly** [django-import-export/django-import-export#1053]

**Comment by MuslimBeibytuly** [comment]
/usr/local/lib/python3.8/site-packages/import_export/resources.py:687: in get_export_headers
    headers = [
/usr/local/lib/python3.8/site-packages/import_export/resources.py:688: in <listcomp>
    force_text(field.column_name) for field in self.get_export_fields()]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = 'id', encoding = 'utf-8', strings_only = False, errors = 'strict'

    def force_text(s, encoding='utf-8', strings_only=False, errors='strict'):
>       warnings.warn(
            'force_text() is deprecated in favor of force_str().',
            RemovedInDjango40Warning, stacklevel=2,
        )
E       django.utils.deprecation.RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().

/usr/local/lib/python3.8/site-packages/django/utils/encoding.py:111: RemovedInDjango40Warning

**Comment by matthewhegarty** [comment]
Thanks.  The full list of warnings for Django 3 is below. ([deprecation info](https://docs.djangoproject.com/en/3.0/releases/3.0/#django-utils-encoding-force-text-and-smart-text)).

@andrewgy8 I can fix these unless you have any other comments?  Are there any other issues with supporting Django 3.0?

```
$ python -Wd ./manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
./../import_export/resources.py:688: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  force_text(field.column_name) for field in self.get_export_fields()]
./../import_export/widgets.py:41: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  return force_text(value)
...../../import_export/admin.py:295: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  data = force_text(data, self.from_encoding)
./../import_export/resources.py:531: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  row_result.object_repr = force_text(instance)
./../import_export/resources.py:180: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  diff = dmp.diff_main(force_text(v1), force_text(v2))
./../import_export/admin.py:146: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  data = force_text(data, self.from_encoding)
............./home/matthew/Projects/django-import-export/tests/core/tests/test_base_formats.py:68: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  data = force_text(in_stream.read())
../home/matthew/Projects/django-import-export/tests/core/tests/test_base_formats.py:96: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  data = force_text(in_stream.read())
.........................../../import_export/widgets.py:419: RemovedInDjango40Warning: smart_text() is deprecated in favor of smart_str().
  ids = [smart_text(getattr(obj, self.field)) for obj in value.all()]
.....................s........../../import_export/widgets.py:97: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  return force_text(value)
./../import_export/resources.py:385: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  force_text(e), code="invalid")
............................................................................/home/matthew/Projects/django-import-export/tests/core/tests/test_resources.py:924: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
  self.assertEqual(strip_tags(categories_diff), force_text(cat1.pk))
...ss
----------------------------------------------------------------------
Ran 157 tests in 5.193s

OK (skipped=3)
Destroying test database for alias 'default'...
```

**Comment by andrewgy8** [comment]
Nope. None. Go for it!

**Comment by MuslimBeibytuly** [comment]
Tried to fix it in https://github.com/django-import-export/django-import-export/pull/1054
@andrewgy8 @matthewhegarty please can you check it and tell me how to do it better?

**Comment by MuslimBeibytuly** [comment]
Closing this issue as pr is at master branch, waiting for new release
