### ISSUE TITLE
Tablib released at 2020.01.13 and broke requirements

### ISSUE THREAD

**Issue by HiveTraum** [django-import-export/django-import-export#1064]
Need to fix version of tablib in setup.py

**Comment by andrewgy8** [comment]
Which version of import-export?

**Comment by ahmedeltaweel** [comment]
It happened to me also, version `1.2.0`

**Comment by ahmedeltaweel** [comment]
I managed to solve the issue by locking `tablib` to version `0.14.0`

**Comment by HiveTraum** [comment]
i have version 2.0

**Comment by HiveTraum** [comment]
> I managed to solve the issue by locking `tablib` to version `0.14.0`

same solution

**Comment by uunbound** [comment]
`tablib` dependencies have become optional in the latest release. install them all using `pip install tablib[all]`.

**Comment by tamers** [comment]
> `tablib` dependencies have become optional in the latest release. install them all using `pip install tablib[all]`.

Actually while this indeed installs all required dependencies, the dropdown "format" list in django admin is no longer populated correctly. It seems it was dynamically fetched and this no longer works with Tablib 1.0 (latest as of today)

**Comment by uunbound** [comment]
> > `tablib` dependencies have become optional in the latest release. install them all using `pip install tablib[all]`.
> 
> Actually while this indeed installs all required dependencies, the dropdown "format" list in django admin is no longer populated correctly. It seems it was dynamically fetched and this no longer works with Tablib 1.0 (latest as of today)

You are right, I noticed it just now. I locked tablib to version `0.14.0` for now.

**Comment by martigan** [comment]
@andrewgy8 last version of django-import-export

**Comment by LuRsT** [comment]
> Actually while this indeed installs all required dependencies, the dropdown "format" list in django admin is no longer populated correctly. It seems it was dynamically fetched and this no longer works with Tablib 1.0 (latest as of today)

@tamers, I wonder what is making that behaviour work, if it's not due to a dependency, it could be a change in `tablib`. If you figure it out, please raise an issue with https://github.com/jazzband/tablib/

**Comment by lucaspolo** [comment]
I made [this PR](https://github.com/django-import-export/django-import-export/pull/1063) to not use major version, I believe this is not the definitive solution, but can help a little. [This PR](https://github.com/django-import-export/django-import-export/pull/1061) is more appropriate for definitive solution.

**Comment by manelclos** [comment]
This is now fixed in master branch: https://github.com/django-import-export/django-import-export/commit/7878169c7244b5c8c12b08a9d41217056e8eae6d

**Comment by martigan** [comment]
any release happening soon?

**Comment by manelclos** [comment]
@martigan this is now released: https://github.com/django-import-export/django-import-export/blob/master/docs/changelog.rst#201-2020-01-15

Thank you all!
