### ISSUE TITLE
Allow skipping importing a row basing on row information

### ISSUE THREAD

**Issue by n1k0** [django-import-export/django-import-export#1068]
I'm dealing with importing 3rd-party generated CSV files using django-import-export, and I'd like to ignore malformed CSV rows (and not import them). I'm already doing some checks and data preprocessing using `before_import_row`, which conveniently pass the `row` dict so I can update it as needed.

And sometimes I'd just want to skip importing a row entirely, basing on the row data. I've seen the `skip_row` function but it only receives a model instance and the original instance when it exists... No obvious access to the `row` dict to check if the row should be skipped or not! The name is slighly misleading here (hint: there's no obvious reason the Model should map 1:1 the row data imho).

Maybe I'm missing something obvious in the docs, or an alternative way to achieve that?

An alternative way to implement the feature, rather than adding a new arg, would be to allow skipping importing a row right from `before_import_row` and friends, eg. by raising a specific exception. Thoughts?

Note: a similar issue has been filed already in #968 but has been closed automatically by a bot, while I really think this should be addressed - or at least answered.

Thanks!

**Comment by MinchinWeb** [comment]
Is overriding `skip_row(instance, origina)` in your Resource class ([link](https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.resources.Resource.skip_row)) what you want?

(I haven't tried it, I'm just reading through the documentation and code and it looks promising.)

**Comment by manelclos** [comment]
@n1k0 you can try validating or adding any flag you need in `import_obj` so that your `skip_row` function can decide on that.

**Comment by n1k0** [comment]
@manelclos that's what I finally did, so yeah that probably means it's the right way to do it. It's unfortunate we can't simply discard a row based on itself, but we can probably live with it. Closing.
