### ISSUE TITLE
Failing while starting django server on tablib deps (djnango-import-export 1.2.0)

### ISSUE THREAD

**Issue by lerdem** [django-import-export/django-import-export#1075]
I am using 
- django 1.11 
- djnango-import-export 1.2.0

When I am installing deps, have no errors. But when I ran server occur error like
ModuleNotFoundError: ... xlrd

I am suggesting to create a patch for version 1.2.1 (last witch supports django 1.11).
in setup.py (https://github.com/lerdem/django-import-export/blob/1.2.0/setup.py#L29)
```python
install_requires = [
    'diff-match-patch',
    'django>=1.8',
    'tablib[all]',
]
```

tarlib doc installation
https://tablib.readthedocs.io/en/stable/install/#installing-tablib

**Comment by claudep** [comment]
I think the solution for you is to pin tablib to an older version in your project (until you upgrade to a more recent Django version).

**Comment by claudep** [comment]
Just reopen if the tablib pinning explained above didn't fix your issue.
