### ISSUE TITLE
admin not working with utf-8 import of csv file

### ISSUE THREAD

**Issue by bilkusg** [django-import-export/django-import-export#1082]
When trying to import a file containing names with foreign characters in utf-8 format using the admin mixin, import-export either fails or mangles the characters.

This seems to be because when storing the uploaded data in a file in the temp directory prior to processing the data it uses text mode, which then complains on certain unicode combinations. If I change get_read_mode in formats to 'rb', everything then works properly.

Is this a bug, or am I not setting something up correctly.
I'm using django 3.1 and python 3.8

Thanks,

**Comment by claudep** [comment]
Are you on Windows? Could you try to apply that patch to see if it makes a difference?

```
diff --git a/import_export/admin.py b/import_export/admin.py
index acd51fe..3ae90a1 100644
--- a/import_export/admin.py
+++ b/import_export/admin.py
@@ -255,7 +255,7 @@ class ImportMixin(ImportExportMixinBase):
         for chunk in import_file.chunks():
             data += chunk
 
-        tmp_storage.save(data, input_format.get_read_mode())
+        tmp_storage.save(data, mode='wb')
         return tmp_storage
 
     def import_action(self, request, *args, **kwargs):
```

**Comment by spamandeggs** [comment]
hi, claudep, I have the same issue than bilkugs. I tried the patch above and it doesn't solve the import encoding problem for utf8 csv (with bom or not) on windows 10 cpython 3.8.1. everything is fine in ANSI.

**Comment by claudep** [comment]
I have no windows system to test with, so I'm afraid someone else should try to debug what's happening, where exactly the problem lies.

**Comment by andrewgy8** [comment]
Im going to close this in deference to #1141
