### ISSUE TITLE
choices field how to import

### ISSUE THREAD

**Issue by wolong1997** [django-import-export/django-import-export#1087]
class MyModel(models.Model):
       ATTR = (
        (1, 'attr1'),
        (2, 'attr2'),
    )
       attr = models.IntegerField(verbose_name="attr", choices=ATTR, default=1)

when import excel value  is attr1 , how translate to 1 save in database

**Comment by sunilkothiyal** [comment]
@wolong1997  did you get the answer?

**Comment by kongyuanhao** [comment]
@wolong1997 did you get the answer?
