### ISSUE TITLE
from_encoding does not work

### ISSUE THREAD

**Issue by HoshiYamazaki** [django-import-export/django-import-export#1090]
I get - ```Imported file has a wrong encoding: 'utf-8' codec can't decode byte 0xb9 in position 254: invalid start byte```.

Despite using `from_encoding` set to `iso-8859-2`, `iso-8859-1`, `iso-8859`.

**Comment by GabrieleCalarota** [comment]
I get:
```
Imported file has a wrong encoding: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
```
Even though I only get this problem in deploy and not in development.
From_encoding is set to utf-8 and I have installed:
django-import-export==2.1.0
tablib==2.0.0

**Comment by andrewgy8** [comment]
Duplicate of #1141
