### ISSUE TITLE
Empty cells on Excel import are imported as None for CharFields with blank=True

### ISSUE THREAD

**Issue by MicBoucinha** [django-import-export/django-import-export#1091]
**A description of the problem/suggestion.**
Not 100% sure if this is a bug or a problem from my end.
As the title mentions, I have an Excel file with the columns that my model requires. One thing I have noticed is that when I have CharFields defined with blank=True, and in the Excel file the cell is empty, I get None instead of an empty string as I would expect (that's the way the CSV importing works for me in the same conditions).

I tried loading the file using:
```python
with open( filepath, "rb") as f:
    dataset = tablib.import_set(f, format="xlsx")
```

and also:
```python
with open( filepath, "rb") as f:
    dataset = Dataset().load(f.read())
```
I am using:
    Python interpreter: **3.7.5**
    Django: **2.2.11**
    tablib version: **1.1.0**
    django-import-export: **2.0.2**

Did anyone encounter this before? Am I doing something wrong on loading the XLSX file? Is there any way that I can define some loading defaults for empty Excel cells?

Thanks!

**Comment by fordguo** [comment]
any suggest?

**Comment by matthewhegarty** [comment]
Please refer to [this issue](https://github.com/django-import-export/django-import-export/issues/1410#issuecomment-1088934294)
