### ISSUE TITLE
please update your documentation about IMPORT_EXPORT_USE_TRANSACTIONS

### ISSUE THREAD

**Issue by spamandeggs** [django-import-export/django-import-export#1100]
IMPORT_EXPORT_USE_TRANSACTIONS default is True and not False as documented in latest
https://django-import-export.readthedocs.io/en/stable/installation.html

IMPORT_EXPORT_USE_TRANSACTIONS = False in settings is **mandatory** if one want to actually import something in a mysql db (at least)

without it :

result = somemodel_resource.import_data(datanew, dry_run=True)

will fail with "ImproperlyConfigured" and no explanation.

spend 3 hours to tweak my csv and test just about this before to look at import_export\resources.py, and its a pity because the project is really cool.

**Comment by matthewhegarty** [comment]
The [documentation](https://django-import-export.readthedocs.io/en/stable/installation.html#import-export-use-transactions) now states that `IMPORT_EXPORT_USE_TRANSACTIONS` default is True
