### ISSUE TITLE
export action not showing on model admin with custom action

### ISSUE THREAD

**Issue by DanSantoDomingo** [django-import-export/django-import-export#1102]
Its working fine with other models without custom action

**Comment by DanSantoDomingo** [comment]
im using `ImportExportActionModelAdmin`

**Comment by DanSantoDomingo** [comment]
found a fix

`actions = ImportExportActionModelAdmin.actions + [my_action]
`

**Comment by xojisi** [comment]
Thank you for helping me to solve the problem.
^.^

**Comment by zbynekdrlik** [comment]
+1 please add it to documentation

**Comment by lggwettmann** [comment]
Thanks, is there a DRYer way to handle this? Would be great if the package would handle this itself.
