### ISSUE TITLE
import feature is not working in django

### ISSUE THREAD

**Issue by Panchalkishan** [django-import-export/django-import-export#1106]
HI Team,

i use this py package for import export my contacts refer my snapshots as series of steps.
initial i have setup using pip
> pip install django-import-export

than i have added 
> 'import_export', in settings.py 

next imported this in modal file
![image](https://user-images.githubusercontent.com/38061833/79348659-e8eb4500-7f52-11ea-9f33-7c31a9ee594f.png)

all contact has been successfully exportad in csv file but it does not import all contacts from that same file and store into database. it shows me below message for each and every recored
![image](https://user-images.githubusercontent.com/38061833/79349663-1c7a9f00-7f54-11ea-844d-45b4b09e369e.png)
 

can anyone please suggest... what actually causing this issue withing this only import feature package. earlier it was working fine..i dont know version number. so kindly check and confirm.

**Comment by matthewhegarty** [comment]
Looks like you have enabled [USE_TZ](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-USE_TZ) in your settings file but are sending non-timezone aware datetimes in your csv file.  Either update the csv values or disable USE_TZ?

https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L196

**Comment by andrewgy8** [comment]
Did this solve your issue @Panchalkishan ?

**Comment by Panchalkishan** [comment]
thanks it works @matthewhegarty 

> Looks like you have enabled [USE_TZ](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-USE_TZ) in your settings file but are sending non-timezone aware datetimes in your csv file. Either update the csv values or disable USE_TZ?
> 
> https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L196
