### ISSUE TITLE
Django Import Exports fails for MongoDB

### ISSUE THREAD

**Issue by sv8083** [django-import-export/django-import-export#1120]
import-export is working for Mysql but fails for MongoDb.

Does this package supports Mongo?
or is there any additional requirement?

The error is same as in issue:
https://github.com/django-import-export/django-import-export/issues/811

**Comment by matthewhegarty** [comment]
It's not supported - only Mysql, Postgres and sqlite are covered in the tests.
You could search the past issues (if not already) to see if anyone has been successful in integrating with other dbs.  Maybe [this](https://django-mongodb-engine.readthedocs.io/en/latest/) a good starting point?

**Comment by sv8083** [comment]
Thank You @matthewhegarty . I will sure check it.
