### ISSUE TITLE
cant import xls with error OSError: File contains no valid workbook part

### ISSUE THREAD

**Issue by WWY507** [django-import-export/django-import-export#1124]
django-import-export==2.1.0
python3.6.8

when i upload xls, with  error OSError: File contains no valid workbook part
anyone help with solve it, thank you

django views.py
> 
def import_xls(request):
    if request.method == 'POST':
        user_resource = UserResource()
        dataset = Dataset()
        new_users = request.FILES['myfile']
        imported_data = dataset.load(new_users.read())
        result = user_resource.import_data(dataset, dry_run=True)
        if not result.has_errors():
            user_resource.import_data(dataset, dry_run=False)
    return render(request,'user/index.html')
> 

html

> 

```
<form method="POST" enctype="multipart/form-data" action="{% url 'user:import_xls' %}">
 {% csrf_token %}
<input type="file" name="myfile">
<button type="submit">Upload</button>
</form>
```

>

**Comment by matthewhegarty** [comment]
My guess is that this is an issue with your file, and not with this library.
The error originates from [openpyxl reader](https://bitbucket.org/openpyxl/openpyxl/src/8953233f5af287d9cdf3dae34e437e76bea5bd59/openpyxl/reader/excel.py#lines-113)

You could try to integrate your upload form with the Admin console, as there are existing examples for how to do this.  ([docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#admin-integration))

**Comment by WWY507** [comment]
> My guess is that this is an issue with your file, and not with this library.
> The error originates from [openpyxl reader](https://bitbucket.org/openpyxl/openpyxl/src/8953233f5af287d9cdf3dae34e437e76bea5bd59/openpyxl/reader/excel.py#lines-113)
> 
> You could try to integrate your upload form with the Admin console, as there are existing examples for how to do this. ([docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#admin-integration))

thanks for  your reply,solve it! 
![Uploading image.png…]()
