### ISSUE TITLE
Repeated ID in imported file does not cause error

### ISSUE THREAD

**Issue by zehawki** [django-import-export/django-import-export#1130]
Just to experiment, I created an XL with a repeated ID to see whether the import process would throw an error. My DB table already contains **IDs upto 4211**, and the table I created for import contained many rows with IDs as follows:

id
____
4210
4209
4210
4211
4212
4213
4214
...

When running the import, the preview shows that the first row with ID 4210 is an UPDATE, then 4209 is an UPDATE (this is fine), then the _next_ 4210 is also UPDATE and then 4211 is an UPDATE (this is fine) and 4212 onwards is NEW (this is fine).

I would expect that since each is an atomic operation, at the end of the import, the DB record with ID 4210 will have contents of the 2nd 4210 in the XL sheet. Right?

Now, why is this not flagged off as an import error?

PS: I hope I've been able to explain the above clearly!

**Comment by matthewhegarty** [comment]
> I would expect that since each is an atomic operation, at the end of the import, the DB record with ID 4210 will have contents of the 2nd 4210 in the XL sheet. Right?

Correct - it will be updated with the values that you saw in the preview.

> Now, why is this not flagged off as an import error?

It wouldn't be an import error.  It has correctly identified that your import contains a row to be updated.

I may not have understood what your question is.  Perhaps you can clarify with an example file / code.  If you could reproduce using the example app that would be easier to understand.

**Comment by zehawki** [comment]
> It wouldn't be an import error. It has correctly identified that your import contains a row to be updated.

Yes, but its a repeated row (same ID) in the Excel sheet I'm importing. That's what I tried to show in the example above. **ID 4210 occurs twice with different values to be imported.** Obviously the person who is importing has made an inadvertent error, hence shouldn't a case like this be flagged as an error, rather than silently importing?

**Comment by andrewgy8** [comment]
I would argue no, as its not import-exports role to judge what should or should not be imported. IMHO import-export's role is simply to take what you have in xls or csv and convert it to a DB instance via django. It would be the users responsibility to check that their xls or csv is correct. This isnt to say you couldnt add your own custom logic to guard against this, but this would be something that youd configure on a per app basis.

**Comment by zehawki** [comment]
OK, thanks. Just wanted to know what you as the devs thought about this. Thanks Matt and Andrew for the quick responses.
