### ISSUE TITLE
NullBooleanField handling...

### ISSUE THREAD

**Issue by jedie** [django-import-export/django-import-export#1135]
I quote https://github.com/django-import-export/django-import-export/issues/357#issuecomment-334475772 :

> Currently for `NullBooleanField' exported data are:
> 
> ```
> true -> "1"
> false -> "0"
> null -> ""
> ```
> 
> But, what i expected:
> 
> ```
> true -> true
> false -> false
> null -> null
> ```

Has that ever been considered?

**Comment by MinchinWeb** [comment]
#1071 will do half of this. It doesn't change the exported values, but will allow you to import data that represent `True` as "true" or "TRUE" or 1 (or a few other things).

**Comment by matthewhegarty** [comment]
You could implement this by extending `BooleanWidget`.  We would review a PR if available.  I will close for now due to inactivity.
