### ISSUE TITLE
 How change the coloumn names in the export file django import export

### ISSUE THREAD

**Issue by yarnakaroesay** [django-import-export/django-import-export#1140]
I want to remove the spaces between the headers and to change the coloumn name altogether in the export file. Like,
 'First Name' to 'firstname'
'Surname' to 'lastname'

**Comment by andrewgy8** [comment]
What have you tried?

**Comment by yarnakaroesay** [comment]
I don't know where to begin from just came accross this package yesterday and i have read almost every issue on github. But nothing im getting no leads.

**Comment by matthewhegarty** [comment]
@yarnakaroesay I added a comment to the [SO post](https://stackoverflow.com/questions/61876484/django-import-export-imports-not-showing?noredirect=1#comment109477628_61876484).  It would be best to continue to ask questions on SO, and only post here if you find issues with the package.

**Comment by andrewgy8** [comment]
Have you read the docs?

**Comment by andrewgy8** [comment]
Closing as its duplicated on SO
