### ISSUE TITLE
Missing Portuguese localizations

### ISSUE THREAD

**Issue by ExarchD** [django-import-export/django-import-export#1143]
I noticed that a few of the portuguese translations weren't happening. Here's one example:
"Some rows failed to validate"

These entries are absent from the PO files. I'm happy to add them, but I've never done any work with Lokalize, etc. I could manually do it in VIM and submit a pull request if that's alright. I'm also not sure where to find a comprehensive list of missing translations.

**Comment by andrewgy8** [comment]
You are absolutely right @ExarchD I added the translations in https://github.com/django-import-export/django-import-export/pull/1144/files Once that goes to master, you should be able to translate the test quite easily.

**Comment by ExarchD** [comment]
That's perfect, thank you!

**Comment by andrewgy8** [comment]
@ExarchD The new translations have been merged, so please feel free to translate as much as you can. Cheers!

**Comment by ExarchD** [comment]
#1145 has the new pt_BR translations
