### ISSUE TITLE
I'm getting Line number: 1 - 'id' Error when i import

### ISSUE THREAD

**Issue by yarnakaroesay** [django-import-export/django-import-export#1148]
This is my code

class Finance(models.Model):
invoiceNumber = models.IntegerField(blank=False, null=False, 
primary_key=True)
student = models.CharField(max_length=50, blank=False, null=False)
rollGroup = models.CharField(max_length=50, blank=False, null=False)
invoiceTo = models.CharField(max_length=50, blank=False, null=False)
dob = models.CharField(max_length=50, null=True)
gender = models.CharField(max_length=50, blank=False, null=False)
status = models.CharField(max_length=50, blank=False, null=False)
schedule = models.CharField(max_length=50,blank=False, null=False)
totalValue = models.CharField(max_length=50, blank=False, null=False)
issueDate = models.CharField(max_length=50, null=True)
dueDate = models.CharField(max_length=50, null=True)
datePaid = models.CharField(max_length=50, null=True)
amountPaid = models.CharField(max_length=50, null=True)

def __str__(self):
    return self.invoiceNumber
This is my resource model

class FinanceResource(resources.ModelResource):

    invoiceNumber = Field(attribute='invoiceNumber', column_name='Invoice 
    Number')
    student = Field(attribute='student', column_name='Student')
    rollGroup = Field(attribute='rollGroup', column_name='Roll Group')
    invoiceTo = Field(attribute='invoiceTo', column_name='Invoice To')
    dob = Field(attribute='dob', column_name='DOB')
    gender = Field(attribute='gender', column_name='Gender')
    status = Field(attribute='status', column_name='Status')
    schedule = Field(attribute='schedule', column_name='Schedule')
    totalValue = Field(attribute='totalValue', column_name='Total             
    Value(PKR 
    ₨)')
    issueDate = Field(attribute='issueDate', column_name='Issue Date')
    dueDate = Field(attribute='dueDate', column_name='Due Date')
    datePaid = Field(attribute='datePaid', column_name='Date Paid')
    amountPaid = Field(attribute='amountPaid', column_name='Amount Paid     
    (PKR 
    ₨)')

class Meta:
    model = Finance

import_id_fields = ('id',)
export_order = ('id', 'invoiceNumber', 'student', 'rollGroup', 
'invoiceTo', 'dob', 'gender', 'status', 'schedule',
                'totalValue', 'issueDate', 'dueDate', 'datePaid', 
'amountPaid')

skip_unchanged = True
report_skipped = True

And this is the error

Line number: 1 - 'id'
2, styles, harry, Spring 2020, Family, , M, Pending, First Installment, 57000, , 10/06/2020, , 0
Traceback (most recent call last):
File "C:\Users\long play computers\PycharmProjects\DotsPrototype\venv\lib\site-packages\import_export\resources.py", line 522, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Users\long play computers\PycharmProjects\DotsPrototype\venv\lib\site-packages\import_export\resources.py", line 292, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "C:\Users\long play computers\PycharmProjects\DotsPrototype\venv\lib\site-packages\import_export\resources.py", line 281, in get_instance
self.fields[f] for f in self.get_import_id_fields()
File "C:\Users\long play computers\PycharmProjects\DotsPrototype\venv\lib\site-packages\import_export\resources.py", line 281, in <listcomp>
self.fields[f] for f in self.get_import_id_fields()
KeyError: 'id'

**Comment by matthewhegarty** [comment]
Hi - I tend to monitor this issue list and stackoverflow, so if you send questions to SO I'll respond to them there.  I would suggest only post here if you think you've found an issue in the library.

thanks

**Comment by yarnakaroesay** [comment]
Oh my bad i will remove it.
https://stackoverflow.com/questions/62262667/django-import-export-error-in-import-xlsx
