### ISSUE TITLE
Django import export: it's not importing all column's data from csv.

### ISSUE THREAD

**Issue by AirnFire** [django-import-export/django-import-export#1150]
i'm using django import export and it's importing first 3 columns and leaving rest of the columns blank.

from import_export import resources
#from import_export import instance_loaders
from import_export.admin import ImportExportModelAdmin
from .userB import User_Acadamic_Details_B
from import_export.fields import Field

class UserResourceB(resources.ModelResource):   #User_Acadamic_Details_A_Resource

    def get_export_headers(self):
        headers = super().get_export_headers()
        for i, h in enumerate(headers):
            if h == 'Course ID':
                headers[i] = "Course_ID"
            if h == 'Rollno':
                headers[i] = "Student_ID"
            if h == 'Name':
                headers[i] = 'Name'
            if h == 'Gender':
                headers[i] = 'Gender'
            if h == 'Dedication':
                headers[i] = 'Dedication'
            if h == 'Quiz 1 (Quiz 01(A))':
                headers[i] = 'Quiz1'
            if h == 'Quiz 2 (Quiz 02(A))':
                headers[i] = 'Quiz2'
            if h == 'Assignment 1 (Assignment no 1(A))':
                headers[i] = 'Assignment1'
            if h == 'Assignment 2 (Assignment no 2(A))':
                headers[i] = 'Assignment2'
            if h == 'Mid Exam (MID TERM EXAM(A))':
                headers[i] = 'Mid_Exam'
        return headers

    Course_ID = Field(attribute='Course_ID', column_name='Course ID' )
    Student_ID = Field(attribute='Student_ID', column_name='Rollno')
    Name = Field(attribute='Name', column_name='Name')
    Gender = Field(attribute='Gender', column_name='Gender')
    Dedication = Field(attribute='Dedication', column_name='Dedication')
    Quiz1 = Field(attribute='Quiz1', column_name='Quiz 1 (Quiz 01(A))')
    Quiz2 = Field(attribute='Quiz2', column_name='Quiz 2 (Quiz 02(A))')
    Assignment1 = Field(attribute='Assignment1', column_name='Assignment 1 (Assignment no 1(A))')
    Assignment2 = Field(attribute='Assignment2', column_name='Assignment 2 (Assignment no 2(A))')
    Mid_Exam = Field(attribute='Mid_Exam', column_name='Mid Exam (MID TERM EXAM(A))')
    #Attendance = Field(attribute='Attendance', column_name='Password')

    class Meta:
        model = User_Acadamic_Details_B
        import_id_fields = ('Course_ID',)
        export_order = ('Course_ID', 'Student_ID', 'Name', 'Gender', 'Dedication', 'Quiz1', 'Quiz2', 'Assignment1', 'Assignment2', 'Mid_Exam', 'Mid_Exam')
        skip_unchanged = True
        report_skipped = True

class UserBAdmin(ImportExportModelAdmin):
    resource_class = UserResourceB

**Comment by matthewhegarty** [comment]
Presumably you have checked if the columns in the import file match those you've declared in your Resource?
Can you post an example of the import file?

**Comment by AirnFire** [comment]
Course ID | Rollno | Name | Gender | Dedication | Quiz 1 (Quiz 01(A)) | Quiz 2 (Quiz 02(A)) | Assignment 2 (Assignment no 2(A)) | Assignment 1 (Assignment no 1(A)) | Mid Exam (MID   TERM EXAM(A))
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
MGT502 | 1 | muhammad ibrahim | Male | 0 | No attempts have been made on this lesson. | No attempts have been made on this lesson. | Grade: - | Grade: - | Grade: - |   |   |  
MTH603 | 2 | Lahore Garrision | Female | 1 hour 39 mins | Grade: 100.00 / 100.00 Friday, 5 June 2020, 12:05 AM | No attempts have been made on this lesson. | Grade: - | Grade: 90.00 / 100.00 Thursday, 4 June 2020, 10:58 PM | Grade: - |   |   |  
MGT502 | 3 | Lahore Garrision | Female | 1 hour 39 mins | Grade: 100.00 / 100.00 Friday, 5 June 2020, 12:05 AM | No attempts have been made on this lesson. | Grade: - | Grade: 90.00 / 100.00 Thursday, 4 June 2020, 10:58 PM | Grade: - |   |   |  
MGT610 | 4 | Lahore Garrision | Female | 1 hour 39 mins | Grade: 100.00 / 100.00 Friday, 5 June 2020, 12:05 AM | No attempts have been made on this lesson. | Grade: - | Grade: 90.00 / 100.00 Thursday, 4 June 2020, 10:58 PM | Grade: - |   |   |  
MGT502 | 5 | huma asgar | Female | 0 | No attempts have been made on this lesson. | No attempts have been made on this lesson. | Grade: - | Grade: - | Grade: - |   |   |  
MGT502 | 7 | bushra asgar | Female | 0 | No attempts have been made on this lesson. | No attempts have been made on this lesson. | Grade: - | Grade: - | Grade: - |   |   |  
MGT502 | 8 | yazdan haider | Male | 0 | No attempts have been made on this lesson. | No attempts have been made on this lesson. | Grade: - | Grade: - | Grade: - |   |   |  


this is the csv i'm trying to import

**Comment by matthewhegarty** [comment]
Try to declare `fields` in the meta class:

```python
fields = ('Course_ID', 'Rollno', 'Name', 'Gender', 'Dedication', 'Quiz 1 (Quiz 01(A))', 'Quiz 2 (Quiz 02(A))', 'Assignment 2 (Assignment no 2(A))', 'Assignment 1 (Assignment no 1(A))', 'Mid Exam (MID TERM EXAM(A))')
```

**Comment by matthewhegarty** [comment]
@AirnFire Have you got anything you would like to add to this thread? If not, I will close it.
thanks
