### ISSUE TITLE
How to append rows in django import export

### ISSUE THREAD

**Issue by humna-s** [django-import-export/django-import-export#1151]
This is the preview of csv file
Course | Principles of Marketing |   |   |  
-- | -- | -- | -- | --
Group | All participants |   |   |  
  |   |   |   |  
Student ID | Username | ID number | Institution | Department
132 | web_service_user |   |   |  
131 | a.i |   |   |  

I am importing this csv file using django import-export but the file appears empty rather than showing data. I want to skip first two rows and start from Student_ID. 

this is how it appears: 
  | STUDENT ID | USERNAME | ID NUMBER | INSTITUTION | DEPARTMENT | SURNAME | FIRST NAME | GROUPS | P | L | E | A | TAKEN SESSIONS | POINTS | PERCENTAGE
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Skipped |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Skipped |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
Skipped

this is my code:
     class courseAttendanceResource(resources.ModelResource):
     Student_ID = Field(attribute='Student_ID', column_name='Student ID')
    Username = Field(attribute='Username', column_name='Username')
    ID_number = Field(attribute='ID_number', column_name='ID number')
    Institution = Field(attribute='Institution', column_name='Institution')
    Department = Field(attribute='Department', column_name='Department')
    Surname = Field(attribute='Surname', column_name='Surname')
    First_name = Field(attribute='First_name', column_name='First name')
    Groups = Field(attribute='Groups', column_name='Groups')
    P = Field(attribute='P', column_name='P')
    L = Field(attribute='L', column_name='L')
    E = Field(attribute='E', column_name='E')
    A = Field(attribute='A', column_name='A')
    Taken_sessions = Field(attribute='Taken_sessions', column_name='Taken sessions')
    Points = Field(attribute='Points', column_name='Points')
    Percentage = Field(attribute='Percentage', column_name='Percentage')

    def get_export_headers(self):
        headers = super().get_export_headers()
        for i, h in enumerate(headers):
            if h == 'Student ID':
                headers[i] = 'Student_ID'
            if h == 'Username':
                headers[i] = 'Username'
            if h == 'ID number':
                headers[i] = 'ID_number'
            if h == 'Institution':
                headers[i] = 'Institution'
            if h == 'Department':
                headers[i] = 'Department'
            if h == 'Surname':
                headers[i] = 'Surname'
            if h == 'First name':
                headers[i] = 'First_name'
            if h == 'Groups':
                headers[i] = 'Groups'
            if h == 'P':
                headers[i] = 'P'
            if h == 'L':
                headers[i] = 'L'
            if h == 'E':
                headers[i] = 'E'
            if h == 'A':
                headers[i] = 'A'
            if h == 'Taken sessions':
                headers[i] = 'Taken_sessions'
            if h == 'Points':
                headers[i] = 'Points'
            if h == 'Percentage':
                headers[i] = 'Percentage'
        return headers

    class Meta:
        model = courseAttendance
        import_id_fields = ('Student_ID',)
        exclude = ('Course', 'Group',)
        fields = ('Student_ID', 'Username', 'ID_number', 'Institution', 'Department', 'Surname', 'First_name', 'Groups', 'P', 'L', 'E', 'A', 'Taken_sessions', 'Points', 'Percentage' )
        #export_order = ('Student_ID', 'Username', 'ID_number', 'Institution', 'Department', 'Surname','First_name', 'Groups', 'P', 'L', 'E', 'A','Taken_sessions', 'Points', 'Percentage')
        skip_unchanged = True
        report_skipped = True

class courseAttendanceAdmin(ImportExportModelAdmin):
    resource_class =courseAttendanceResource

**Comment by matthewhegarty** [comment]
The easiest way would be to either manually or programatically strip the first 3 rows from the csv before you pass it into django-import-export.  The library is assuming that you have a clean dataset before it starts processing records.
