### ISSUE TITLE
 How to update model before export

### ISSUE THREAD

**Issue by yarnakaroesay** [django-import-export/django-import-export#1152]
I'm trying to calculate the pending amount from by getting the data from the django model. Now i want to update the model before exporting as the AmountPending field is empty during import. But i'm just hardstuck on this problem. Here's my resource class

class FinancePendingResource(resources.ModelResource):

    invoiceNumber = Field(attribute='invoiceNumber', column_name='Invoice Number')
    student = Field(attribute='student', column_name='Student')
    Schedule = Field(attribute='Schedule', column_name='Schedule')
    issueDate = Field(attribute='issueDate', column_name='Issue Date')
    dueDate = Field(attribute='dueDate', column_name='Due Date')
    amountPaid = Field(attribute='amountPaid', column_name='Amount Paid (PKR ₨)')

    class Meta:
        model = FinancePending
        import_id_fields = ('invoiceNumber',)
        fields = ('invoiceNumber', 'student', 'amountPaid', 'issueDate', 'dueDate', 'Schedule', 'AmountPending',)
        exclude = ('id',)
        skip_unchanged = True
        report_skipped = True

    def before_export(self, queryset, *args, **kwargs):
        amount_paid = FinancePending.objects.values_list('amountPaid', flat=True)
        amount_paid = list(amount_paid)
        total_amount = FinancePending.objects.values_list('TotalAmount', flat=True)
        total_amount = list(total_amount)

        # total - paid
        TotalFee = [float(s.replace(',', '')) for s in total_amount]
        AmountPaid = [float(s.replace(',', '')) for s in amount_paid]

        def Diff(li1, li2):
            return (list(set(li1) - set(li2)))

        amount_pending = Diff(TotalFee, AmountPaid)

        finance_pending = FinancePending()
        i=1
        while i<=len(amount_pending):
            FinancePending.objects.filter(invoiceNumber=i).update(AmountPending=str(amount_pending[i]))
            i = i + 1
Edited (uploaded an older version earlier accidently)

**Comment by andrewgy8** [comment]
What if you do a queryset.refresh_from_db()?

**Comment by yarnakaroesay** [comment]
How do i do that?

**Comment by yarnakaroesay** [comment]
Still getting an empty coloumn

**Comment by matthewhegarty** [comment]
https://stackoverflow.com/a/62332748/39296
