### ISSUE TITLE
Exporting a lot of data (more than 500 records) will causes the browser reset connection

### ISSUE THREAD

**Issue by kennir** [django-import-export/django-import-export#1153]
**Describe the bug**

Exporting a lot of data (more than 500 records) will cause the browser to reset the connection

**To Reproduce**

Select many records, then export to Xls format, wait for about 30 seconds before a reset connection error occurs

**Versions (please complete the following information):**
 - Django Import Export: 2.1.0
 - Python 3.7.0
 - Django 2.2.12

**Expected behavior**
The browser reset the connection, The server side gets 499 code.

**Screenshots**

**Additional context**

**Comment by matthewhegarty** [comment]
Hi - can you reproduce the issue using the [example application](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?  I just tried with 500 Book records (attached if you want to import them), and it exported fine with no latency.

If it works ok for you, we'll need to know some more details.  What server are you running?  What is the nature of your data?  How many records are you exporting?

[Book-2020-06-15.zip](https://github.com/django-import-export/django-import-export/files/4782537/Book-2020-06-15.zip)

**Comment by kennir** [comment]
Hi @matthewhegarty  

I can not reproduce the problem after I rebooted the server, please give me a few days to see if it will come back

**Comment by andrewgy8** [comment]
I will close this as it seems solved. Please feel free to reopen if the problem persists.
