### ISSUE TITLE
How to raise message when import file # format file action import?

### ISSUE THREAD

**Issue by thangbuingoc** [django-import-export/django-import-export#1155]

**Comment by andrewgy8** [comment]
What have you tried? What went wrong? What do you expect? What versions are you using? etc, etc... Please provide context to your question.

**Comment by thangbuingoc** [comment]
I used django-import-export verssion 2.2.0. I want to check the import file and import format. If the format is wrong, give an error message right on the django admin interface. The library is currently catching an exception. I want that exception to be a message. Thank master!

**Comment by thangbuingoc** [comment]
`# then read the file, using the proper format-specific mode
            # warning, big files may exceed memory
            try:
                data = tmp_storage.read(input_format.get_read_mode())
                if not input_format.is_binary() and self.from_encoding:
                    data = force_str(data, self.from_encoding)
                dataset = input_format.create_dataset(data)
            except UnicodeDecodeError as e:
                return HttpResponse(_(u"<h1>Imported file has a wrong encoding: %s</h1>" % e))
            except Exception as e:
                return HttpResponse(_(u"<h1>%s encountered while trying to read file: %s</h1>" % (type(e).__name__, import_file.name)))`

**Comment by thangbuingoc** [comment]
# then read the file, using the proper format-specific mode
            # warning, big files may exceed memory
            try:
                data = tmp_storage.read(input_format.get_read_mode())
                if not input_format.is_binary() and self.from_encoding:
                    data = force_str(data, self.from_encoding)
                dataset = input_format.create_dataset(data)
            except UnicodeDecodeError as e:
                return HttpResponse(_(u"<h1>Imported file has a wrong encoding: %s</h1>" % e))
            except Exception as e:
                return HttpResponse(_(u"<h1>%s encountered while trying to read file: %s</h1>" % (type(e).__name__, import_file.name)))
Maybe override exception raise error message?

**Comment by matthewhegarty** [comment]
> The library is currently catching an exception. I want that exception to be a message.

This is now addressed in #1281.
