### ISSUE TITLE
Django Import-export: Import CSV files errors

### ISSUE THREAD

**Issue by NhaTrang** [django-import-export/django-import-export#1156]
I`ve spent a few hours trying to debug this issue. I am trying to import a catalog of product into my app. I am using Django Import-export to import a csv file. I have tried to import it via the admin site and via a simple upload file. In both case, I am encountering some errors. Would you have an idea how to resolve them?

**1st Method: Import the csv file via the admin site**

Error encountered: Imported file has a wrong encoding: 'charmap' codec can't decode byte 0x9d in position 13365: character maps to

It looks like this method cannot accept some character(""). How can I change my code to accept any character? I`ve already removed the following characters: £, - and try to encode it in UTF-8. I have also done a search to remove every non ASCII characters(128-255)

**2eme Method: Import the csv file via the website**

Error encountered: 'MultiValueDict' object is not callable

**views.py**

```
def simple_upload(request):
    if request.method == 'POST':
        file_format = request.POST.get('file-format')
        product_resource = ProductResource()
        dataset = Dataset()
        new_products = request.FILES['Price_List']

        if file_format == 'CSV':
            imported_data = dataset.load(new_products.read().decode('utf-8'),format='csv')
            result = product_resource.import_data(dataset, dry_run=True)                                                                 
        elif file_format == 'JSON':
            imported_data = dataset.load(new_products.read().decode('utf-8'),format='json')
            # Testing data import
            result = product_resource.import_data(dataset, dry_run=True) 

        if not result.has_errors():
            # Import now
            product_resource.import_data(dataset, dry_run=False)

    return render(request, 'catalog/simple_upload.html')
```
**models.py**

```
from import_export import resources
from .models import Product

class ProductResource(resources.ModelResource):
    class Meta:
        model = Product
        skip_unchanged = True
        report_skipped = False
```
**simple_upload.html**

```
{% extends 'base.html' %}

{% block body %}
<h3>Import Data</h3>
<p>importing to database</p>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="importData">
    <p>Please select format of file.</p>
    <select name="file-format" class="form-control my-3">
        <option selected>Choose format...</option>
        <option>CSV</option>
        <option>JSON</option>
      </select>
    <button class="btn btn-primary" type="submit">Import</button>
  </form>

{% endblock %}
```
Many Thanks,

**Comment by matthewhegarty** [comment]
Can you run the import process locally so that we can remove the server from the picture.  You can use a variant of this script:

```python
import django
from tablib import dataset
django.setup()

from .models import Product

class ProductResource(resources.ModelResource):
    class Meta:
        model = Product
        skip_unchanged = True
        report_skipped = False


resource = ProductResource()
with open("data.csv", "r") as fh:
    imported_data = dataset.load(fh.read().decode('utf-8'),format='csv')

result = resource.import_data(imported_data, raise_errors=True)
print(result)
```

**Comment by NhaTrang** [comment]
Sorry, it`s a beginner question, where this data.csv file should be stored?

**Comment by matthewhegarty** [comment]
Anywhere where you can read it on your filesystem (e.g. `/tmp` or `c:\temp`)

I'm in the [SO chat room](https://chat.stackoverflow.com/rooms/216196/django-import-export) if you want to join

**Comment by matthewhegarty** [comment]
@NhaTrang Have you got anything you would like to add to this thread?  If not, I will close it.  Thanks
