### ISSUE TITLE
Examples of importing nested data?

### ISSUE THREAD

**Issue by charleshan** [django-import-export/django-import-export#1157]
Here's a simple use case.

```
class Address(models.Model):
    city = models.CharField(blank=True, max_length=255)
    place = models.CharField(blank=True, max_length=255)
    state = models.CharField(blank=True, max_length=255)
    county = models.CharField(blank=True, max_length=255)
    country = models.CharField(blank=True, max_length=255)
    country_code = models.CharField(blank=True, max_length=3)

class Person(models.Model):
    name = models.CharField(blank=True, max_length=255)
    address = models.OneToOneField(Address, related_name='+', blank=True, null=True, on_delete=models.SET_NULL)
    ...
```

`django-import-export` makes it really straight forward if the `Address` fields are inside the `Person` model but the documentation doesn't show any examples of importing nested structures like this.
 
How do we make the import create two objects and and create a relationship?

---
Related: https://github.com/django-import-export/django-import-export/issues/571, https://github.com/django-import-export/django-import-export/issues/318

**Comment by matthewhegarty** [comment]
I haven't tried this but it should be possible to set fields in related objects.

The [docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-resource-options) give a brief example of this:

```python
    class Meta:
        model = Book
        fields = ('author__name',)
```

So if you are importing a `Person` it should be possible to set related `Address` fields, using a similar pattern.  

If you are finding this doesn't work or are hitting problems (or if I have misunderstood your issue) please reply with more details.

**Comment by charleshan** [comment]
@matthewhegarty That is only for exporting related objects.

I figure it out but I really had to dig through other issues and the source code. We should add how to add this to the documentation.

```
from import_export import fields, resources, widgets

class AddressWidget(widgets.ForeignKeyWidget):
    def clean(self, value, row=None, *args, **kwargs):
        if not value:
            return None
        else:
            obj, _ = Address.objects.update_or_create(
                pk=value,
                defaults={
                    'city': row.get('city'),
                    'state': row.get('state'),
                    'county': row.get('county'),
                    'country': row.get('country'),
                    'country_code': row.get('country_code'),
                }
            )
        return obj

class PersonResource(resources.ModelResource):
    address = fields.Field(
        column_name='place_id',
        attribute='address',
        widget=AddressWidget(Address, 'place_id')
    )

```

**Comment by andrewgy8** [comment]
Closing as its not an issue. But please feel free to add some more documentation!
