### ISSUE TITLE
Translation conflicts 

### ISSUE THREAD

**Issue by z268** [django-import-export/django-import-export#1158]
I get some translation conflicts with Django when I use `LANGUAGE_CODE = 'ru-ru'`. 

Translation from `django==3.0`:
```
msgid "Delete"
msgstr "Удалить"
```

Translation from `django-import-export`:
```
#: templates/admin/import_export/import.html:101
msgid "Delete"
msgstr "Удалено"
```

`django-import-import` overrides django translations. It's confusing.
if I understand correctly in `templates/admin/import_export/import.html` should be used verbs in past tense: `Added`, `Deleted`, `Updated` instead of `New`, `Delete`, `Update`. 
Also it needs  to be renamed in `.po` files for saving previous translations.

**Comment by andrewgy8** [comment]
Interesting. I wouldnt know as I dont speak Russian, but would you be able to submit a fix for this?

**Comment by andrewgy8** [comment]
Closing as keeping it open is not going to solve anything. But if someone wants to fix this translation, feel free.
