### ISSUE TITLE
zh_Hans translation file has a problem

### ISSUE THREAD

**Issue by SnarkBoojum** [django-import-export/django-import-export#1159]
I package django-import-export for Debian, and the Debian checkers found an issue with the zh_Hans translation ([report](https://i18n.debian.org/l10n-pkg-status/p/python-django-import-export.html)):
```gettext: import_export/locale/zh_Hans/LC_MESSAGES/django.po: can't guess language```

**Comment by SnarkBoojum** [comment]
I can give more information:
```
$ msgfmt -c -o /dev/null import_export/locale/zh_Hans/LC_MESSAGES/django.po 
msgfmt: import_export/locale/zh_Hans/LC_MESSAGES/django.po: warning: PO file header fuzzy
                                                            warning: older versions of msgfmt will give an error on this
import_export/locale/zh_Hans/LC_MESSAGES/django.po:8: warning: header field 'Project-Id-Version' still has the initial default value
import_export/locale/zh_Hans/LC_MESSAGES/django.po:8: warning: header field 'PO-Revision-Date' still has the initial default value
import_export/locale/zh_Hans/LC_MESSAGES/django.po:8: warning: header field 'Last-Translator' still has the initial default value
import_export/locale/zh_Hans/LC_MESSAGES/django.po:8: warning: header field 'Language-Team' still has the initial default value
import_export/locale/zh_Hans/LC_MESSAGES/django.po:8: warning: header field 'Language' still has the initial default value
```

**Comment by SnarkBoojum** [comment]
I have several django.po for zh_Hans on my system, and there are names of people who made them : perhaps it's possible to get in touch with them directly (rather than through transifex.com) ?

**Comment by andrewgy8** [comment]
It seems like its just an issue with the meta data included in the .po files. Maybe any easy fix for this would be to submit a PR with this info? If you do that, Ill create a release.

**Comment by andrewgy8** [comment]
Im going to close this, as I dont think keeping it open will get it solved any quicker. Please submit a PR with the fixes, if you get a chance.

**Comment by SnarkBoojum** [comment]
I can't provide the information, since I don't know who provided the translations...

**Comment by andrewgy8** [comment]
Id recommend that you can put `django-import-export contributors` as a generic person.

**Comment by SnarkBoojum** [comment]
[Here](https://github.com/django-import-export/django-import-export/files/4924133/zh_CN.txt) is a patch fixing the header ; but notice that the translations are still marked as fuzzy : you should really get in touch with a translating team to get translations right.

**Comment by andrewgy8** [comment]
OK dude
