### ISSUE TITLE
How do you deal with server timeouts?

### ISSUE THREAD

**Issue by charleshan** [django-import-export/django-import-export#1160]
I found an issue that was created a few years back but the answer is not valid anymore: https://github.com/django-import-export/django-import-export/issues/301

I believe this is a common problem if you're importing a large dataset. We should document how to get around server timeouts.

**Comment by matthewhegarty** [comment]
If this is a problem you're experiencing at the moment, I have an [open PR](https://github.com/django-import-export/django-import-export/pull/1149) for bulk imports.  Obviously this won't solve the issue of timeouts, but might help if it is a pressing problem for you now.

My current project involves the import of large data sets, and my solution is not to perform the import in the server process.  There is a synchronous upload of data files, which then kicks off an async server process to perform the import, and then returns.  Users can poll a URL to check on the status of the import.

**Comment by andrewgy8** [comment]
Closing as it can perhaps be solved with bulk imports! If it doesnt solve it, please feel free to reopen.
