### ISSUE TITLE
Locale and imported numbers

### ISSUE THREAD

**Issue by ExarchD** [django-import-export/django-import-export#1162]
I'm not sure if this is handled already, but I'm having some issues importing numbers following different number conventions. For example if my data looks like this:

> 23,7; 33,5; 1.000,4;
> 22,4; 32,1; 1.213,5;
> ....

I have LANGUAGE configured in settings.py but it doesn't seem to help parse correctly. I end up with an error like this:

> could not convert string to float: '4,12'

Any ideas?

**Comment by matthewhegarty** [comment]
The best solution to this would be to extend `NumberWidget` to handle parsing of the custom format.
