### ISSUE TITLE
Transform DEFAULT_FORMATS to dict

### ISSUE THREAD

**Issue by CleitonDeLima** [django-import-export/django-import-export#1167]
Currently DEFAULT_FORMATS is a `list`. Perhaps it would not be better if it were a `dict`?
I want to change the human-readable name of the format choices but I don't find a simple solution.

I think handling forms would be simpler.

```python
class ExportForm(forms.Form):
    file_format = forms.ChoiceField(
        label=_('Format'),
        choices=(),
    )

    def __init__(self, formats, *args, **kwargs):
        super().__init__(*args, **kwargs)
        choices = []
        for f, label in formats.items():
            title = f().get_title()
            choices.append((title, label or title))
        if len(formats) > 1:
            choices.insert(0, ('', '---'))

        self.fields['file_format'].choices = choices

# in custom view or admin 

class ExportMixin:
    formats = {
        base_formats.XLSX: "Excel (xlsx)"
    }
    ...
```

**Comment by matthewhegarty** [comment]
If this is still relevant and you would like to submit a PR, please review the guidance on [contributing](https://github.com/django-import-export/django-import-export/blob/main/CONTRIBUTING.md), and we would consider for future inclusion.
