### ISSUE TITLE
Is this able to handle gigabytes of csv file import without overwhelming memory?

### ISSUE THREAD

**Issue by shadrachbaldon** [django-import-export/django-import-export#1170]

**Comment by andrewgy8** [comment]
Thanks @shadrachbaldon for opening an issue. However this is a common issue that has been addressed previously #1160 #327  #206

If you are imporing csvs of multiple GBs, I think youll find django-import-export lacking in performance as it was not built to handle that size of file. I think you would be hard pressed to find any out of the box solution to import GB's of data. You might be able to use django-import-export as a base, but then youll probably have to expand and create a custom solution for that type of job. Good luck!
