### ISSUE TITLE
Import name instead of ID in a foreign key field

### ISSUE THREAD

**Issue by cesardft** [django-import-export/django-import-export#1172]
Hi!

I have this model: 

models.py
```
`class User(models.Model):
    user_name = models.CharField(max_length=50, blank=False, verbose_name='Nome')
    user_login = models.CharField(max_length=50, blank=True, verbose_name='Login de Rede')
    user_position = models.ForeignKey('UserPositionDatabase', on_delete=models.PROTECT, max_length=50, blank=True, verbose_name='Posição', default="") 
    user_departament = models.ForeignKey('Departament', on_delete=models.PROTECT, null=False, blank=True, verbose_name='Departamento')
    user_manager = models.CharField(max_length=20, verbose_name='Gestor Imediato', default="")
    user_locality = models.ForeignKey('Locality', on_delete=models.PROTECT, blank=True, null=False, verbose_name='Localidade')`
```

when I export the department which is a foreign key, the result is the id instead of the departament name. How do I change?

**Comment by matthewhegarty** [comment]
[This section](https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-resource-options) of the docs may help:

> When defining ModelResource fields it is possible to follow model relationships:

```python
class BookResource(resources.ModelResource):

    class Meta:
        model = Book
        fields = ('author__name',)
```

So likely in your case the `fields` definition would be:

```
fields = (user_departament__name, ...)
```

**Comment by andrewgy8** [comment]
Thanks @matthewhegarty ! 

@cesardft if you feel that this doesnt solve your issue, please let us know. Im closing this in the meantime.

**Comment by cesardft** [comment]
Hi @matthewhegarty 
Thanks for the reply. Apparently this is a good solution, but it doesn't seem to have worked for me. I will share my code with you. Did I do it right? I'm a little beginner in programming.

My field `Departament` is:

```
class Departament(models.Model):
    departament_name = models.CharField(max_length=50, blank=False, verbose_name='Departamento')
```

And `User` is:

```
class User(models.Model):
        user_departament = models.ForeignKey('Departament', on_delete=models.PROTECT, null=False, blank=True, verbose_name='Departamento')
```

So i need to put this in the 'field' var?

`field = ('user_departament__departament_name', ...)` ?

**Comment by matthewhegarty** [comment]
That is almost correct.  It must be `fields` not `field`.  And don't include the `...` bit (replace that with any other field names that you want to export).

If you are a beginner (and you don't already do this) then may I suggest:
- read the documentation carefully
- use an IDE like PyCharm and use the debugger.  

This will save you many hours in trying to fix issues.

**Comment by cesardft** [comment]
It works! Thank you very much and sorry for the inconvenience.

**Comment by deki90to** [comment]
Why this does not work for me? Is anything changed untill now?

**Comment by samatharkar** [comment]
When I tried this, 

It said `django.core.exceptions.FieldDoesNotExist: Vendor.added_by_user.name: User has no field named 'name'`

My code is : 

`    added_by_user = models.ForeignKey(User, on_delete=models.PROTECT, related_name= "vendors", verbose_name="Added By User")
`

**Comment by naveedur** [comment]
Hi experts, I need help on above issue. I am importing data to database with foreign key also. 
`class MemberResource(resources.ModelResource):
    class Meta:
        model = model
        fields=('id','title','Model_code','Chipset','chipset_description','image','Brand__title','Cat')`
In above code  **Brand** is using as a foreignkey and I get his title by **Brand__title** I word perfectly for exporting but when importing with brand title it through an error given below.
`Line number: 1 - null value in column "Brand_id" of relation "firmApp_model" violates not-null constraint DETAIL: Failing row contains (6, f16, sd, images/sample_3pahsfV.jfif, gf, kjkj, null).
None, f16, sd, images/sample_3pahsfV.jfif, gf, 1, kjkj, oppo`

any solution please!!

**Comment by Satyamkhadka** [comment]
@naveedur My guess is: your import file's failing row has a null value for firmApp_model field. As firmApp_model is set to not-null it is raising constraint violation error. 
Also, check if your import for corruption. Following row doesn't seem to be in format. 
Read the error description carefully.
