### ISSUE TITLE
CHUNK_SIZE defaults to 1, so unless explicitly set, prefetching won't work

### ISSUE THREAD

**Issue by jdewells** [django-import-export/django-import-export#1174]
**Describe the bug**
Not setting `CHUNK_SIZE` in your resource will cause it to default to being set to 1. Since we need to paginate the queryset to enable prefetching, this means we iterate over the queryset row by row, which prevents prefetching from working.

Setting the `CHUNK_SIZE` explicitly against the resource fixes the issue and lets the prefetch work, but there's no signal that this problem could be happening to the user, which can be very confusing if you're new to prefetch and can't see why it's not working (not that I know anyone who fits that description, ahem)

**To Reproduce**
1. Remove the `CHUNK_SIZE` setting from your resource
2. Make a resource for a Django model that has a valid prefetch option, e.g. a `m2m_thing = ManyToManyField(…)`
3. Export the resource using `MyResource().export(queryset.prefetch_related('m2m_thing')`
4. See in the query log that one query for `m2m_thing` is run for each row of the model

**Versions:**
 - Django Import Export: 2.3.0
 - Python: 3.6.9
 - Django: 3.0.8 

**Expected behavior**
* Setting the `CHUNK_SIZE` default value to something higher, e.g. 5000?
* Possibly a warning output if `CHUNK_SIZE` isn't set but prefetches are being used on the queryset?
* A note added to the docs against `CHUNK_SIZE`?

**Comment by andrewgy8** [comment]
I assume this is similar to what was reported here? https://github.com/django-import-export/django-import-export/pull/1050#issuecomment-664473338

**Comment by jdewells** [comment]
> I assume this is similar to what was reported here? [#1050 (comment)](https://github.com/django-import-export/django-import-export/pull/1050#issuecomment-664473338)

It absolutely is - describes it perfectly. 

Happy to close this issue as a duplicate, but since #1050 is about the fundamental fix for `prefetch_related`, I think it makes sense to keep this issue open to track the simple "the default value doesn't work as expected" angle that @pawelzar points out?

**Comment by pawelzar** [comment]
I think it makes sense to keep this one as it's a new issue (regression). I should've created one, but I figured I'll just post a comment in the original issue, where the `CHUNK_SIZE` was added and wait for some feedback.

@jdewells I'd only change the title, because theoretically the `prefetching` works, but since queryset is evaluated for each item due to `CHUNK_SIZE = 1` it just doesn't make much sense.

I agree that the solution should be to set the default value much higher as it shouldn't harm anyone. There is no point in trying to keep "the old behavior" when the performance could just be improved for everyone.

**Comment by jdewells** [comment]
> @jdewells I'd only change the title, because theoretically the `prefetching` works, but since queryset is evaluated for each item due to `CHUNK_SIZE = 1` it just doesn't make much sense.

Any suggestions? "CHUNK_SIZE defaults to 1, forcing queryset to evaluate for each row & preventing optimisation"?

**Comment by pawelzar** [comment]
Works for me @jdewells :+1:

**Comment by adamchainz** [comment]
I've gone for a default of 100 in my PR #1196.
