### ISSUE TITLE
How I can pass “allow_unicode=True” to yaml encoder

### ISSUE THREAD

**Issue by cprog** [django-import-export/django-import-export#1180]
Hello,

For my project I use version 0.4.5
I would like to ask you how I can pass "allow_unicode = True" to yaml encoder ?
```

def export(self, queryset=None, *args, **kwargs):
        kwargs.update({'allow_unicode' : True})
        return super(BranchResource, self).export(queryset, *args, **kwargs)
```

but this raises an error for unknown parameter

I want to pass this parameter because I believe that this way I can fix encoding in a resulted YAML file.
At the moment all Cyrillic characters in the file are displayed as an escape characters  .

Best regards

**Comment by pokken-magic** [comment]
It looks to me like we depend on Tablib for exporting to various formats, but with version 3.0.0 of Tablib unicode characters probably are supported in Yaml from Tablib. I'd suggest retrying this with tablib 3.0.0+. If this is still an issue let us know.

reference: https://github.com/jazzband/tablib/blob/master/src/tablib/formats/_yaml.py

See that Tablib now passes allow_unicode=True to the YAML decoder.
