### ISSUE TITLE
Import/Export for single field

### ISSUE THREAD

**Issue by sover02** [django-import-export/django-import-export#1181]
Hi There - is it possible to import/export a single field value? 

I have a JSONField that stores config items that I'd like to enable users to download and update, but don't necessarily want them to have to track the rest of the fields in the file they download/upload.

I'd like to also be able to update the single JSONField via the admin interface at an item level.

I gave the documentation a run-through but didn't quite find the answer I was looking for.

**Comment by miguelfg** [comment]
Have you tried to:
1 export it first, 
2 drop all fields except id and your JSONField, 
3 modify your JSONField
4 import this json file

Hmm, you might want to do steps 1,2 and 3 as csv, and then convert the csv to json. With pandas the right way for me to generate the json file that is correclty imported is as:

`df.to_json("YOUR FILE PATH.json", orient='records')`

**Comment by ekarmazin** [comment]
Same question here, how to export a single item only? The 'exclude' option is great, but I have hundreds items and I just need only particular one by id.

export 100+ rows and drop fields is not an option at all.

**Comment by matthewhegarty** [comment]
We added a filter_queryset() function in #1579
