### ISSUE TITLE
Django import-export updates the database even if you do not confirm your import

### ISSUE THREAD

**Issue by jpdpueyo** [django-import-export/django-import-export#1182]
I am creating a django app using the import-export module. I am using the import feature to upload an excel/csv and my app will send an email if there are changes detected in the excel/csv file.

My issue is when I upload an excel/csv file with changes in it, clicking the SUBMIT button will already trigger the 'send mail' function even if I am still on the CONFIRM IMPORT PAGE on the django admin page.

Can you guys assist on how can I trigger my 'send mail' function only after I confirm the import?

Below is my models.py
`class Tracking2(models.Model):

MODE_CHOICES = (
    ('Air Freight', 'Air Freight'),
    ('Sea Freight', 'Sea Freight'),
)

name = models.CharField(max_length=255)
contact_number = models.CharField(max_length=255)
mode = models.CharField(max_length=255, choices=MODE_CHOICES)
tracking_number = models.CharField(max_length=255)
cargo_received_date = models.DateField(null=True, blank=True)
cargo_received_details = models.CharField(null=True, max_length=255,blank=True)
out_for_delivery_date = models.DateField(null=True, blank=True)
out_for_delivery_details = models.CharField(null=True, max_length=255,blank=True)
arrived_at_region_date = models.DateField(null=True, blank=True)
arrived_at_region_details = models.CharField(null=True, max_length=255,blank=True)
departed_shipping_facility_date = models.DateField(null=True, blank=True)
departed_shipping_facility_details = models.CharField(null=True, max_length=255,blank=True)
cargo_delivered_date = models.DateField(null=True, blank=True)
cargo_delivered_details = models.CharField(null=True, max_length=255,blank=True)

class Meta:
       verbose_name_plural = "Italy"

def save(self, *args, **kwargs):
    return super(Tracking2, self).save(*args, **kwargs)
@receiver(pre_save, sender=Tracking2)
def on_change(sender, instance: Tracking2, **kwargs):
    if instance.id is None:
        email_host = settings.EMAIL_HOST_USER
        email_subject = 'New entry created'
        recipient_list = ['test@email.com']
        body =  'New entry created ' + instance.name
        send_mail(email_subject, body, email_host, recipient_list )
    else:
        previous = Tracking2.objects.get(id=instance.id)
        if previous.name != instance.name:
            email_host = settings.EMAIL_HOST_USER
            email_subject = 'There is an update on your order'
            recipient_list = ['test@email.com']
            body =  'Cargo Tracking Update for ' + instance.name + '\n' + 'Tracking Number: ' + instance.tracking_number
            send_mail(email_subject, body, email_host, recipient_list )`

Below is my admin.py

`from django.contrib import admin
from .models import Tracking, Tracking2
from import_export import resources
from import_export.admin import ImportExportModelAdmin
from rangefilter.filter import DateRangeFilter, DateTimeRangeFilter

class Tracking2Resources(resources.ModelResource):
    class Meta:
        model = Tracking2

class Tracking2Admin(ImportExportModelAdmin):
    resource_class= Tracking2Resources
    search_fields = ('name', 'contact_number', 'tracking_number','out_for_delivery_details' )
    list_display = ("name","contact_number","mode","tracking_number", "cargo_received_date","cargo_received_details",
        "out_for_delivery_date","out_for_delivery_details","arrived_at_region_date",
        "arrived_at_region_details","departed_shipping_facility_date",
        "departed_shipping_facility_details","cargo_delivered_date",
        "cargo_delivered_details")
    list_filter = (
        ("cargo_received_date", DateRangeFilter),
        'mode'
    )`

**Comment by andrewgy8** [comment]
This is a known issue reported https://github.com/django-import-export/django-import-export/issues/1078
Im going to close it since it is a duplicate
