### ISSUE TITLE
Incorrect example in BooleanWidget docstring

### ISSUE THREAD

**Issue by washeck** [django-import-export/django-import-export#1186]
The docstring in BooleanWidget in

https://github.com/django-import-export/django-import-export/blob/e855fcf8ed43af4dd681435f516e9f50ee19613d/import_export/widgets.py#L119

shows example usage with missing brackets (the `widget` kwarg must be instance not a class)

**Comment by andrewgy8** [comment]
Thanks for the catch. Feel like submitting a fix?

**Comment by washeck** [comment]
@andrewgy8 I can try to submit a PR though I don't know when. But I'd prefer not to close the issue until it's fixed.

**Comment by andrewgy8** [comment]
Ok thanks @washeck. I closed the issue as I dont think that keeping it open will resolve it any further. If you wish to have it open then I will reopen it.

**Comment by matthewhegarty** [comment]
This was fixed in #1193
