### ISSUE TITLE
Django Import_export MultipleObjectsReturned

### ISSUE THREAD

**Issue by oppongntiamoah** [django-import-export/django-import-export#1188]
I am trying to import an excel file
When I try to import it, I receive the following error:

> Line number: 1 - get() returned more than one Info -- it returned 6!
5, Yaw Berko, West Caton, RHL Concord, 2010-09-22, Overland, Amasaman, Ghana, 123456, 1254, , Cash Against Document, ZENITH, Accra, olol, Oppong, Wawa, Lumber (Kiln Dried), Odum, 21.00, 1.0000, , m3, 457.00, USD, 9597.000, 1.0200, 9788.94
Traceback (most recent call last):
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\import_export\resources.py", line 662, in import_row
self.import_obj(instance, row, dry_run)
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\import_export\resources.py", line 516, in import_obj
self.import_field(field, obj, data)
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\import_export\resources.py", line 499, in import_field
field.save(obj, data, is_m2m)
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\import_export\fields.py", line 110, in save
cleaned = self.clean(data)
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\import_export\fields.py", line 66, in clean
value = self.widget.clean(value, row=data)
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\import_export\widgets.py", line 396, in clean
return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
File "C:\Users\Pages\.virtualenvs\tidd-fGwTEFFg\lib\site-packages\django\db\models\query.py", line 433, in get
raise self.model.MultipleObjectsReturned(
permit.models.Info.MultipleObjectsReturned: get() returned more than one Info -- it returned 6!

models.py
`
class Info(models.Model):

    O_PORT = [
        ('Overland', 'Overland'),
        ('Ghana', 'Ghana'),
        ('By Air', 'By Air'),
        ('Takoradi', 'Takoradi'),
        ('Tema', 'Tema'),
    ]

    PAYMENT_TYPE = [
        ('Cash Against Document', 'Cash Against Document'),
        ('Bank Draft', 'Bank Draft'),
        ('Cash Against Document', 'Cash Against Document'),
        ('Letter of Credit', 'Letter of Credit'),
        ('Wire Transfer', 'Wire Transfer'),
        ('PrePaid', 'PrePaid'),
    ]

    exporter = models.CharField(max_length=150)
    buyer = models.CharField(max_length=150)
    vessel = models.CharField(max_length=150)
    date_of_transaction = models.DateField(default=timezone.now, verbose_name="Transaction Date")
    originating_port = models.CharField(choices=O_PORT, max_length=8)
    city_destination = models.CharField(max_length=150, verbose_name="City of Destination")
    country_destination = models.CharField(max_length=150, verbose_name="Country of Destination")
    contract_number = models.CharField(max_length=150, verbose_name="Contract Number")
    a2_form = models.CharField(max_length=50, blank=True, null=True)
    payment_type = models.CharField(choices=PAYMENT_TYPE, max_length=50)
    negotiating_bank = models.ForeignKey(Bank, on_delete=models.CASCADE)
    container_or_vehicle = models.CharField(max_length=50)
    driver_name = models.CharField(max_length=150, blank=True)

    # records on user
    added_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, editable=False, verbose_name="Employee")
    date_added = models.DateTimeField(auto_now_add=True)

    permit_NUM = models.CharField(max_length=30, unique=True, verbose_name="Permit Number")

    class Meta:
        verbose_name = "Capture Permit Info"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.exporter

# ________________ Permit ________________
class Permit(models.Model):

    CONVERSION = [
        ('1.0000', '1.0000'),
        ('0.0006', '0.0006'),
        ('0.0007', '0.0007'),
        ('0.0010', '0.0010'),
        ('0.0015', '0.0015'),
    ]

    UNITS = [

        ('m2', 'm2'),
        ('m3', 'm3'),

    ]

    CURRENCY = [
        ('USD', 'USD'),
        ('GHS', 'GHS'),
        ('CFA', 'CFA'),
        ('Euro', 'Euro'),

    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specie = models.ForeignKey(Specie, on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)
    info = models.ForeignKey(Info, on_delete=models.CASCADE)

    # volume
    volume = models.DecimalField(max_digits=19, decimal_places=2)
    conversion_factor = models.CharField(choices=CONVERSION, max_length=8)
    units = models.CharField(choices=UNITS, max_length=5)
    unit_price = models.DecimalField(max_digits=19, decimal_places=2)
    currency = models.CharField(choices=CURRENCY, max_length=5)
    ex_rate = models.DecimalField(
        max_digits=19, decimal_places=4, verbose_name='Exchange Rate')

    # Calculations
    value = models.DecimalField(max_digits=19, decimal_places=3, default=0)
    derived_volume = models.DecimalField(
        max_digits=19, decimal_places=3, default=0)
    euro_value = models.DecimalField(
        max_digits=19, decimal_places=2, default=0)

    def __str__(self):
        return self.info.exporter

`

**resources.py**
`class PermitResource(resources.ModelResource):
    info__exporter = Field(column_name='Exporter',attribute='info',widget=ForeignKeyWidget(Info, 'exporter'))
    
    product__name = Field(column_name='Product',attribute='product',widget=ForeignKeyWidget(Product, 'name'))
    specie__name = Field(column_name='Specie',attribute='specie',widget=ForeignKeyWidget(Specie, 'name'))
    grade__name = Field(column_name='Grade',attribute='grade',widget=ForeignKeyWidget(Grade, 'name'))

    info__buyer = Field(column_name='Buyer',attribute='info',widget=ForeignKeyWidget(Info, 'buyer'))
    info__vessel = Field(column_name='Vessel',attribute='info',widget=ForeignKeyWidget(Info, 'vessel'))
    info__date_of_transaction = Field(column_name='Transaction_Date',attribute='info',widget=ForeignKeyWidget(Info, 'date_of_transaction'))
    info__originating_port = Field(column_name='O_Port',attribute='info',widget=ForeignKeyWidget(Info, 'originating_port'))
    info__city_destination = Field(column_name='D_City',attribute='info',widget=ForeignKeyWidget(Info, 'city_destination'))
    info__contract_number = Field(column_name='ContractNo',attribute='info',widget=ForeignKeyWidget(Info, 'contract_number'))
    info__a2_form = Field(column_name='A2 Form',attribute='info',widget=ForeignKeyWidget(Info, 'a2_form'))
    info__payment_type = Field(column_name='Payment Type',attribute='info',widget=ForeignKeyWidget(Info, 'payment_type'))

    info__negotiating_bank__name = Field(column_name='Bank',attribute='info__negotiating_bank',widget=ForeignKeyWidget(Bank, 'name'))

    info__container_or_vehicle = Field(column_name='Container',attribute='info',widget=ForeignKeyWidget(Info, 'container_or_vehicle'))
    info__driver_name = Field(column_name='Driver',attribute='info',widget=ForeignKeyWidget(Info, 'driver_name'))
    info__permit_NUM = Field(column_name='PermitNo',attribute='info',widget=ForeignKeyWidget(Info, 'permit_NUM'))
    info__country_destination = Field(column_name='D_Country',attribute='info',widget=ForeignKeyWidget(Info, 'country_destination'))
    
    derived_volume = Field(column_name='Derived Volume')
    

    class Meta:
        model = Permit
        skip_unchanged = False
        report_skipped = False
        
        fields = (
            'info__exporter', 'info__buyer', 'info__vessel', 'info__date_of_transaction',
            'info__originating_port', 'info__city_destination', 'info__country_destination',
            'info__contract_number', 'info__permit_NUM', 'info__a2_form',
            'info__payment_type', 'info__negotiating_bank__name', 'info__container_or_vehicle',
            'info__driver_name', 'specie__name', 'product__name',  'grade__name',
            'volume', 'conversion_factor', 'derived_volume', 'id',
            'units', 'unit_price', 'currency', 'value', 'ex_rate', 'euro_value',

        )
        export_order = (
            'id', 'info__exporter', 'info__buyer', 'info__vessel', 'info__date_of_transaction',
            'info__originating_port', 'info__city_destination', 'info__country_destination',
            'info__contract_number', 'info__permit_NUM', 'info__a2_form',
            'info__payment_type', 'info__negotiating_bank__name', 'info__container_or_vehicle',
            'info__driver_name', 'specie__name', 'product__name',  'grade__name',
            'volume', 'conversion_factor', 'derived_volume',
            'units', 'unit_price', 'currency', 'value', 'ex_rate', 'euro_value',

        )
`

**Comment by matthewhegarty** [comment]
What is happening is that the import logic is attempting to see if any existing rows exists so that it can perform an update rather than an insert.  It will be attempting to match using the fields you have provided, and is returning multiple matching rows.

Best practice would be to provide a unique id for each import (this can be combined from multiple fields).  These can be declared in `import_id_fields`.

Please review the documentation on [import workflow](https://django-import-export.readthedocs.io/en/latest/import_workflow.html) for more information.
