### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by adamchainz** [django-import-export/django-import-export#1189]
Hi,

Is it possible to get a new release? I'd like to have the fixes for Django 3.1 deprecation warnings from #1173 available on PyPI.

Thanks for a really useful library,

Adam

**Comment by andrewgy8** [comment]
Of course! Ill try to get to it today.

**Comment by adamchainz** [comment]
Thank you 👏

**Comment by andrewgy8** [comment]
Django Import Export 2.4.0 is out! https://pypi.org/project/django-import-export/ 

Enjoy!

**Comment by adamchainz** [comment]
Great 😁
