### ISSUE TITLE
empty rows before csv header trigger exception while importing

### ISSUE THREAD

**Issue by amonaldo** [django-import-export/django-import-export#1192]
I just realized that empty rows before the header trigger this exception : 

`list indices must be integers or slices, not str`

Here is an example : 

```

first_name,last_name,email,password,role
Noak,Larrett,nlarrett0@ezinearticles.com,8sh15apPjI,Student
Duffie,Milesap,dmilesap1@wikipedia.org,bKNIlIWVfNw,Student
```

It only works if the first row is the header. Empty rows after the header are ignored

```
first_name,last_name,email,password,role
Noak,Larrett,nlarrett0@ezinearticles.com,8sh15apPjI,Student
Duffie,Milesap,dmilesap1@wikipedia.org,bKNIlIWVfNw,Student

...

```

Is there a way to fix this ?

**UPDATE** : I tried overwriting `before_import` to remove any blank row

```
def before_import(self, dataset, using_transactions, dry_run, **kwargs):
	indexes = []
	for i in range(0, len(dataset)):
		row = ''.join(dataset[i])
		if row.strip() == '':
			indexes.append(i)
	for index in sorted(indexes, reverse=True):
		del dataset[index]			
	return dataset
```

This works for all the rows, except for the first one that must be the header and if not then the error is thrown.

**Comment by matthewhegarty** [comment]
I added a [PR](#1281) for this which handles any leading empty rows gracefully.  Obviously this only applies to the Admin site, if you are running imports programmatically (i.e. not using the Admin site), then you will have to check for empty leading rows in your own file handling code.

**Comment by manelclos** [comment]
@amonaldo if you are importing from the admin, @matthewhegarty PR will solve this problem. You could also try to automatically fix the file in `write_to_tmp_storage`, but I think warning the user is better.

If you are not using the admin, maybe subclass the format you are using and override `create_dataset` to generate the correct data, skipping the blank line in the file, this would work for the admin too.

**Comment by amonaldo** [comment]
@matthewhegarty Yes I was able to solve it by overwriting create_dataset in import_export/formats/base_formats.py

``
def create_dataset(self, in_stream, **kwargs):
    in_stream = os.linesep.join([s for s in in_stream.splitlines() if s.strip()])
    try:
        return tablib.import_set(in_stream, format=self.get_title())
    except:
        return tablib.import_set('', format=self.get_title())
``
