### ISSUE TITLE
Customizeable MediaStorage

### ISSUE THREAD

**Issue by duck-nukem** [django-import-export/django-import-export#1210]
Hey,

At $dayjob we've encountered an issue where using the temporary storage can fail, since we have multiple instances serving requests. When trying to retrieve the file, it might not be in that instance's file system.

We've found that `MediaStorage` would be great, except we don't want to upload our files to the public media storage, but to a private S3 bucket.

I've implemented that by subclassing `BaseStorage` and almost exactly copy & pasting `MediaStorage`'s internals, except that instead of `default_storage` I'm using our own internal `PROTECTED_STORAGE`.

After this lengthy introduction, I'd like to ask if you'd be interested in a Pull Request where there's a `ConfigurableStorage` class, that accepts an instance of storage. `MediaStorage` would be a subclass of `ConfigurableStorage` using `default_storage`. `ConfigurableStorage` would also be public to allow defining custom storage classes.

If you're interested, let me know, and I'll prepare a PR ✌️

**Comment by matthewhegarty** [comment]
The storage classes have had some modest refactoring in recent releases.  I'm now planning release 4.  If there is still any interest in this PR, then aiming for v4 would be great.

**Comment by Dsujan** [comment]
Hi @duck-nukem will you be contributing to this? We are encountering this exact issue when we scale to multiple instances.

**Comment by duck-nukem** [comment]
@Dsujan hey, sorry I don't think I'll have capacity anytime soon to contribute :(

**Comment by Dsujan** [comment]
Hi @matthewhegarty, I can see you have tagged this issue for the v4 release. Is this one planned for the fix or somebody has already fixed it ?

**Comment by matthewhegarty** [comment]
No, it's not planned and no-one is working on it.  I don't know if it will go into v4.  Happy to consider any PRs.

**Comment by duck-nukem** [comment]
It's been some time so not sure I remember all the details, but we basically wanted to have what `MediaStorage` offers, except we didn't want to store our files in `MEDIA_ROOT`, but in a custom storage - it happened to be a private S3 bucket.

So we copied the implementation of `MediaStorage` and customised it like:

```diff
+from .storages import PROTECTED_STORAGE  # S3Storage instance

-class MediaStorage(BaseStorage):
+class PrivateStorage(BaseStorage):
-   MEDIA_FOLDER = "django-import-export"

    def __init__(self, **kwargs):
-       # issue 1589 - Ensure that for MediaStorage, we read in binary mode
-       kwargs.update({"read_mode": "rb"})
        super().__init__(**kwargs)

    def save(self, data):
        if not self.name:
            self.name = uuid4().hex
-       default_storage.save(self.get_full_path(), ContentFile(data))
+       PROTECTED_STORAGE.save(self.get_full_path(), ContentFile(data))

    def read(self):
-       with default_storage.open(self.get_full_path(), mode=self.read_mode) as f:
+       with PROTECTED_STORAGE.open(self.get_full_path(), mode=self.read_mode) as f:
            return f.read()

    def remove(self):
-       default_storage.delete(self.get_full_path())
+       PROTECTED_STORAGE.delete(self.get_full_path())

    def get_full_path(self):
-       return os.path.join(self.MEDIA_FOLDER, self.name)
+       return PROTECTED_STORAGE.path(self.name)
```

once again I'd like to emphasise that this is mostly just pseudo-code as it's been years since I opened this issue and I only vaguely remember the details.

Does this help @matthewhegarty ?

**Comment by matthewhegarty** [comment]
This will be released in the next beta release of v4.
