### ISSUE TITLE
'NoneType' object has no attribute 'has_header' !

### ISSUE THREAD

**Issue by pulse-mind** [django-import-export/django-import-export#1211]
Hello,

Thank you for your job. 
At the end of the process of import, when I click on Confirm I get this error : 
```
Request URL: | http://localhost:8002/app/xxx/xxxxproduct/process_import/
-- | --
2.2.17
AttributeError
'NoneType' object has no attribute 'has_header'
D:\Perso\VirtualEnv\xxx\lib\site-packages\django\utils\cache.py in patch_response_headers, line 243
```

I've done more tests and a very simple project and it happens when I add the method
```def get_form_kwargs(self, request=None ,*args, obj=None, form=None, import_form=None, **kwargs):```
On my main project, this method was used to update kwargs

Do you have any ideas of the source of the problem ?

**Comment by pulse-mind** [comment]
Ok, I was doing this : 
```if form and isinstance(form, ImportForm):
            kwargs.pop('import_file_name', None)
            kwargs.pop('input_format', None)
            kwargs.pop('original_file_name', None)
```
Because I had some errors before...
My mistake, ow I do 
```
       if request and inspect.isclass(request) and issubclass(request, ImportForm):
            kwargs.pop('xxxx', None)
            kwargs.pop('xxxx', None)
        elif form and isinstance(form, ImportForm):
            pass
...
```

**Comment by MarceloPiske** [comment]
Bem tive esse mesmo problema e a resolução foi simple, eu estava dando um retorno vazio em uma função, quando na verdade deveria retornar o que o FrontEnd estava esperando, foi uma simples falta de atenção.
