### ISSUE TITLE
Unecessary

### ISSUE THREAD

**Issue by sesostris** [django-import-export/django-import-export#1212]
https://github.com/django-import-export/django-import-export/blob/b367e106794ef3a029f933702644b4f81453a0be/import_export/admin.py#L415-L446

The purpose of this code snippet is just to get the queryset with the same filters and ordering of the django admin changelist.

However, in the django's ModelAdmin class has a method that returns a ChangeList instance: ModelAdmin.get_changelist_instance (self, request).

This entire code snippet could be replaced by:

`return self.get_changelist_instance (request) .get_queryset (request)`

With the advantage of avoiding copy-and-paste

**Comment by andrewgy8** [comment]
Hi @sesostris! Is this a question, comment, request for changes?

**Comment by sesostris** [comment]
This is a request for change. If approved I can submit a pull request.

**Comment by andrewgy8** [comment]
Can you change the title? Its still unclear to me what the change requested is.
