### ISSUE TITLE
CSV Break Line

### ISSUE THREAD

**Issue by guigro1987** [django-import-export/django-import-export#1213]
Hello,

I need help to break line in CSV export. One line per object.

Thank you.

**Comment by matthewhegarty** [comment]
Hi - I recommend to post your question to [Stackoverflow](https://stackoverflow.com/questions/tagged/django-import-export) (tag it with django-import-export).  Include as much information as you can to help people understand your issue.  There are guidelines [here](https://stackoverflow.com/help/how-to-ask)
