### ISSUE TITLE
TypeError: import_obj() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by sam-thecoder** [django-import-export/django-import-export#1214]
I did an update to the latest version and with django to 3.1.2 and the import page throws this error

    Line number: 1 - import_obj() takes 3 positional arguments but 4 were given
    DAVAN, LEMETEI, M, 37291003, , 4827, , KAMPI YA KANZI, , , , , , , , , 7/9/2020, N/A, N/A, N/A, , N/A, N/A, N/A, N/A, N/A, N/A, N/A, , N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A, N/A,
    Traceback (most recent call last):
    File "/home/sammy/webapps/envs/kpsga/lib/python3.8/site-packages/import_export/resources.py", line 662, in import_row
    self.import_obj(instance, row, dry_run)
    TypeError: import_obj() takes 3 positional arguments but 4 were given

I've attached image below for how it looks

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/2c9QV.png

**Comment by matthewhegarty** [comment]
I replied on [SO](https://stackoverflow.com/questions/64952855/django-import-export-error-line-number-1-import-obj-takes-3-positional-arg) with a request for more information.  Please continue there if you need further help.
