### ISSUE TITLE
Translate to Korean

### ISSUE THREAD

**Issue by jinmay** [django-import-export/django-import-export#1217]
Hi. I have just started using django-import-export for my project.
This is awesome and helpful for me. But I thought that it sometimes quite feels hard to understand because of everthing in English. So I think that translation to Korean would be needed for Korean users.

So I want to ask you that i can translate to Korean.
Thank you for your answer in advanced.

**Comment by andrewgy8** [comment]
Yes! Translations are always welcome!

**Comment by andrewgy8** [comment]
Fixed in #1218
