### ISSUE TITLE
how to change model.datefield format to dd-mm-YY

### ISSUE THREAD

**Issue by ashwinisd25** [django-import-export/django-import-export#1224]
I'am importing the csv file from admin area and uploading it to database through model.
the date format in CSV is in dd-mm-YY but the django default date format is YY-mm-dd 
please suggest the solution

**Comment by matthewhegarty** [comment]
[This SO post](https://stackoverflow.com/a/61318918/39296) should answer the question.  If not, feel free to post a new question on SO and I'll take a look.
