### ISSUE TITLE
Transaction rollback after file submit without hitting confirm import increases the MySQL auto increment counter by row numbers

### ISSUE THREAD

**Issue by bahaspieler** [django-import-export/django-import-export#1227]
Whenever I submit file in the import page.  The Preview looks like the below table with the allocated IDs.

..... | ID | NAME | FEATURES
-- | -- | -- | --
New | 121 | gold | ABC
New | 122 | classic | DEF
New | 123 | platinum | GHI

But after confirming, the data are saved with IDs 124,125,126. 

![image](https://user-images.githubusercontent.com/37025618/102690644-09ca0f80-4231-11eb-9d5e-bea475372bef.png)

So the more the row of data to be inserted, the more ids are getting skipped. Even if I don't confirm the import, just after hitting the submit button the IDs are getting allocated due to transaction rollback. May be because AUTO_INCREMENT field doesn't rollbacks if a transaction rollbacks in MySQL. Is there any way that any kind of rollbacks will be executed after hitting the Confirm Import button so that no IDs get skipped without importing. Or am I doing anything wrong??

My admin.py :- 

```
from django.contrib import admin
from .models import Product
from import_export import resources
from import_export.admin import ImportExportModelAdmin
from django.db import transaction


class ProductResource(resources.ModelResource):
    save_points = []

    def before_save_instance(self, instance, using_transactions, dry_run):
       
        if using_transactions and dry_run:

            con = transaction.get_connection()

            self.save_points.extend(con.savepoint_ids)

    def after_import(self, dataset, result, using_transactions, dry_run, **kwargs):
       
        if using_transactions and dry_run:

            con = transaction.get_connection()
            for sid in self.save_points:
                con.run_on_commit = [
                    (sids, func) for (sids, func) in con.run_on_commit if sid not in sids
                ]
        super().after_import(dataset, result, using_transactions, dry_run, **kwargs)

    class Meta:
        model = Product



class ProductAdmin(ImportExportModelAdmin):
    resource_class = ProductResource


admin.site.register(Product, ProductAdmin)
```

In settings.py :-
`IMPORT_EXPORT_USE_TRANSACTIONS = True`

**Comment by llostris** [comment]
We've noticed the same thing – it looks like it's a known issue:
https://github.com/django-import-export/django-import-export/issues/1182
https://github.com/django-import-export/django-import-export/issues/1183

**Comment by andrewgy8** [comment]
Unfortunately, this is not something in Django Import Exports scope. It seems that it is a database specific behaviour. https://stackoverflow.com/a/14758690/5779280

**Comment by maqsoodhakro** [comment]
I have same issue, how to solve this ? kindly help.
