### ISSUE TITLE
InvalidDimensions encountered while trying to read file: [Extended from issues 796]

### ISSUE THREAD

**Issue by VanessaMachi** [django-import-export/django-import-export#1235]
having the same problem statement from the below issues, 

Django==3.1.1
django-import-export==2.5.0

https://github.com/django-import-export/django-import-export/issues/796

I had an excel file that has this issue suspect also is the Apple number problem, I had fixed this issue by copy all the data from that excel file to a new excel file, and the problem fixed. But in user experience wise is not user friendly.

Looking for an ideal solution.

**Comment by andrewgy8** [comment]
Hi there! This doesnt seem to be a Django Import/Export issue. Perhaps its a tablib issue with the way excel files are read and parsed. You might want to check there.
