### ISSUE TITLE
ForeignKeyWidget Custom User Model

### ISSUE THREAD

**Issue by albixhafa** [django-import-export/django-import-export#1237]
I am no longer able to upload a csv file after creating a custom user model. I deleted the db file and re-ran migrations still the issue persists. I am not sure if the ForeignKeyWidget even accepts it.

username = fields.Field(
        column_name='username',
        attribute = 'username',
        widget=ForeignKeyWidget(settings.AUTH_USER_MODEL, 'username')
)

**Comment by matthewhegarty** [comment]
If this is still an issue you would like an answer for, please can you raise a new question on [StackOverflow](https://stackoverflow.com/questions/tagged/django-import-export)
