### ISSUE TITLE
KeyError 'a' when importing (import page doesn't load)

### ISSUE THREAD

**Issue by dgurovich** [django-import-export/django-import-export#1239]
I have a model with 5 Charfields and 1 AutoField, so it's quite simple.  I've created a resource that defines the model in the metaclass and then added it to the "general" admin class.  Exporting seems to work fine, but importing throws an error on page, from \import_export\resources.py, line 292

KeyError: 'a'

This seems like a very simple model/resource for import export, yet the page doesn't load and the above error shows.  I'm kinda lost....

The resource looks like:

```
class CXSystemsResource(resources.ModelResource):
    class Meta:
        model = CxSystems
        export_order = ('acronym')
```

The Admin code is:

`class CxSystemsAdmin(ImportExportModelAdmin, admin.ModelAdmin):
    resource_class = CXSystemsResource
    search_fields = ['id', 'owning_it_org', 'acronym', 'application_name']

    def get_search_results(self, request, queryset, search_term):
        queryset, use_distinct = super(CxSystemsAdmin, self).get_search_results(request, queryset, search_term)
        queryset = queryset.order_by('id', 'acronym')
        return queryset, use_distinct
`

The model is:
`class CxSystems(models.Model):
    """
    A System usually, but not always associated in the ASMS System registry (sites.gm.com).
    This is an enterprise architecture viewpoint and is mapped to
    Systems in the GM enterprise ecosystem.  They are mapped to CX Business Capabilities via
    a relationship in the Business Capability/System Catalog (CXBusinessSystemMembers)

    @CXBusinessSystemMembers
    """
    id = models.AutoField(primary_key=True)
    asms_id = models.BigIntegerField(blank=True, null=True)
    owning_it_org = models.CharField(max_length=255, blank=True, null=True)
    acronym = models.CharField(unique=False, max_length=255)
    application_name = models.CharField(unique=True, max_length=255)
    description = models.CharField(max_length=255, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=12)
    ordering = [acronym]

    def __str__(self):
        return f"{self.acronym} --> {self.application_name}, ({self.owning_it_org})"

    class Meta:
        managed = True
        db_table = 'cx_systems'
        verbose_name = 'CX System'
        verbose_name_plural = 'CX Systems'`

**Comment by andrewgy8** [comment]
I think you are missing a comma in the export order tuple. Try this:

```
class CXSystemsResource(resources.ModelResource):
    class Meta:
        model = CxSystems
        export_order = ('acronym', )
```
