### ISSUE TITLE
Is it possible to export selected rows?

### ISSUE THREAD

**Issue by j-kong** [django-import-export/django-import-export#124]
First of all, thanks for the great plugin!

I'm wondering if it's possible to export selected rows in the admin interface, rather than the entire model. For example, I can perform a search `model/?q=test` and click Export, then only the searched fields would be exported. However, if I select say, 3 rows, by checking them, the plugin doesn't export just those 3 rows, but rather the entire model.

![export](https://cloud.githubusercontent.com/assets/1407485/3801103/343ba2be-1c00-11e4-96aa-f825a1212939.jpg)

Does the plugin support what I'm looking for? 

Once again, thanks!

**Comment by manelclos** [comment]
@miceno is right, documented here: https://django-import-export.readthedocs.org/en/latest/getting_started.html#admin-integration

Closing.

**Comment by huxaiphaer** [comment]
@manelclos , I suggest we be explicit, Is it available in the documentation or not ?

Thanks

**Comment by manelclos** [comment]
@huxaiphaer yes it is, see how to use actions here: https://django-import-export.readthedocs.io/en/latest/getting_started.html#exporting-via-admin-action
