### ISSUE TITLE
how to restrict the no of records to be uploaded at .xlsx file processing level

### ISSUE THREAD

**Issue by shaileshyadav7771** [django-import-export/django-import-export#1240]
Hi, I am having **model A** which is having 1000 records and with the help of the .xlsx file, I am updating the user's shift timing.
Now  I want to limit the records to be updated to one day.

How I am thinking to Implement?
-If I can Count the records at the **resource.py** file-level by using before_import (don't know how to write the logic for this)
so once the count will be more than 500 that data will not process. Now the problem here what if a user has updated 100 records the first time and 500 next time so need something which can count the data and the next day that counted data should reset to 0.

Anyone Can help me with how I can implement this functionality at the file processing level.

My **resource.py** file is as follows.

class CTAResource(resources.ModelResource):
 class meta: Model=CTA

My **views.py** logic to upload data
def CTA_upload(request):
    try:
        if request.method == 'POST':
            movie_resource = CTAResource()
    ##we will get data in movie_resources####
    dataset = Dataset()
    new_movie = request.FILES['file']
    if not new_movie.name.endswith('xls'):
        messages.info(request, 'Sorry Wrong File Format.Please Upload valid format')
    return render(request, 'apple/uploadinfosys.html')
    messages.info(request, 'Uploading Data Line by Line...')
    imported_data = dataset.load(new_movie.read(), format='xls')
    count = 1
    for data in imported_data:
        value = CTA(
            data[0],
            data[1],
            data[2],
            data[3],
            data[4],
            data[5],
            data[6],
            data[7],
            data[8],
        )
    count = count + 1
    value.save()
    # messages.info(request, count)
    # time.sleep(1)
    messages.info(request, 'File Uploaded Successfully...')

    except:
    messages.info(request,
                  'Same Email ID has been observed more than once. Except that other records has been added../nPlease Make sure Email field should be unique.')

    return render(request, 'app/cta.html')

**Comment by andrewgy8** [comment]
Im going to close this as it seems to be outside the scope of django-import-export and is not a code base issue. However, feel free to continue discussing either here or on SO.
