### ISSUE TITLE
Unable to import from csv file unless saved in TextEdit first. 

### ISSUE THREAD

**Issue by bkbirr** [django-import-export/django-import-export#1243]
I am using django-import-export to upload a csv file. I cannot get it to read a certain column on upload in the admin or in my view unless I save it in Mac's TextEdit app. The rows are straight forward with no unusual characters.

An example row is:
`ASIN,Title,P-index,Category,Brand,Fulfillment,"Size Tier","Number of Images","Variation Count",Weight,BSR,Price,"Monthly Sales","Net Price","Monthly Revenue","Review Count","Reviews Rating",Sellers,"Last Year Sales","Sales Year Over Year","Sales Trend (90 days)","Price Trend (90 days)","Best Sales Period","Sales to Reviews" B00167YCSM,"HERSHEY'S Milk Chocolate Bulk Holiday Candy, 4.4 Ounce, Extra Large Bars, 12 Count",,"Grocery & Gourmet Food",HERSHEY'S,Amazon,"Large Standard-Size",6,4,3.9903669422,747,17.76,17055,8.92,294710.4,2861,4.8,6,,,2471,-31,"Dec, 2020",6.23
`

It is the ASIN column with B00167YCSM as the value (or any other similar ASIN value). Mac users are able to upload (with ASIN row showing) only if they open the csv in TextEdit and save it, but Windows users are not able to upload csv files no matter what they use to save the file with.

Any ideas on what could be causing this?

**Versions (please complete the following information):**
 - Django Import Export: [2.5.0]
 - Python  [3.7]
 - Django [3.0.11]

**Comment by matthewhegarty** [comment]
The data you have posted includes the header and a single data row, however they are rendered on a single line.  Hence it would not be a valid csv format which could be imported.  As long as the data is structure on multiple rows in your csv, then it will import.

```
ASIN,Title,P-index,Category,Brand,Fulfillment,"Size Tier","Number of Images","Variation Count",Weight,BSR,Price,"Monthly Sales","Net Price","Monthly Revenue","Review Count","Reviews Rating",Sellers,"Last Year Sales","Sales Year Over Year","Sales Trend (90 days)","Price Trend (90 days)","Best Sales Period","Sales to Reviews"
B00167YCSM,"HERSHEY'S Milk Chocolate Bulk Holiday Candy, 4.4 Ounce, Extra Large Bars, 12 Count",,"Grocery & Gourmet Food",HERSHEY'S,Amazon,"Large Standard-Size",6,4,3.9903669422,747,17.76,17055,8.92,294710.4,2861,4.8,6,,,2471,-31,"Dec, 2020",6.23
```

Sorry if this is something that you are already aware of.  I don't think it is a django-import-export bug - and I don't know why it only shows up for Windows users, but it likely comes down to the csv not being valid.

Note django-import-export uses [tablib](https://tablib.readthedocs.io/en/stable/formats/#csv) to parse csv.
