### ISSUE TITLE
multiple exports with different resource file for same model

### ISSUE THREAD

**Issue by JyothiVutukuri** [django-import-export/django-import-export#1245]
Want multiple types of export for the same model
Eg. We have investors model
We want exports like

- Investors data for issuing shares for project owner.
- Investors data for compliance data with different fields
- Founders to see investors with invested project.

**Comment by JyothiVutukuri** [comment]
This issue has solution in `pr`
https://github.com/django-import-export/django-import-export/pull/1223

**Comment by andrewgy8** [comment]
Dup of https://github.com/django-import-export/django-import-export/issues/765
