### ISSUE TITLE
Modify model instance with post_import signal

### ISSUE THREAD

**Issue by philmcnamara** [django-import-export/django-import-export#1250]
Hi all,

I would like to make some modifications to imported data using the _post_import signal. 

My code looks like this:

```
class OligoImportResource(resources.ModelResource):

    created_by = fields.Field(
        column_name='created_by',
        attribute='created_by',
        widget=ForeignKeyWidget(User, field='username')
    )

    class Meta:
        model = Oligo
```

```
@receiver(post_import, dispatch_uid="modify_import")
def _post_import(model, **kwargs):
    model.comment= "extra comment"
    model.save()
```

Based on the documentation the ```model``` argument should be giving me an instance of my model, but when I try to confirm import I get the following error:

```
save() missing 1 required positional argument: 'self'
```

I would also like to access ```request``` to get the user id during import which someone else here mentioned was possible using ```kwargs``` but I can't get that to work either. Any help is appreciated.

**Comment by tochimclaren** [comment]
My proble is that _post_import signal is not being called.

`@receiver(post_import, dispatch_uid='balabala...')
def _post_import(model, **kwargs):
    # model is the actual model instance which after import
    print(model)`

after succesful import.

**Comment by matthewhegarty** [comment]
Hi - it's a few years old now, but if this is still an issue, please upgrade to v4 and advise if it is still an issue.
Otherwise I will close.
thanks

**Comment by tochimclaren** [comment]
It's no longer an issue I made a work around for the issue.
