### ISSUE TITLE
Export ImageField url.

### ISSUE THREAD

**Issue by victor-trindade** [django-import-export/django-import-export#1253]
is there any way to export the absolute path of the images ?
![image](https://user-images.githubusercontent.com/41354910/111099710-d68fd780-8524-11eb-8fdf-7eb756c642ba.png)

**Comment by SuperMasterBlasterLaser** [comment]
You can use field dehydration. Something like this:

    class MyResource(resources.ModelResource):
        class Meta:
            model = MyModel
            fields = ('photo',)
    
    def dehydrate_photo(self, obj):
        return obj.photo.url
