### ISSUE TITLE
Deployed version doesn't show import/export.

### ISSUE THREAD

**Issue by dgurovich** [django-import-export/django-import-export#1264]
I looked around the issue tracker and didn't see an answer, so I wanted to ask here -- I'm sure it's between my seat and the keyboard -- I have import_export working beautifully with the production DB and my dev server on my box, but when deployed to Apache/WSGI,  the import/export buttons have dissappeared on the admin pages where I have configured them (obviously same code).  Is there something I've missed?

It was something I missed.  Working fine.

**Comment by manelclos** [comment]
@dgurovich would be great to document here what the problem was before closing the issue.

**Comment by matthewhegarty** [comment]
Closing due to lack of updates
