### ISSUE TITLE
Csv files should be opened with universal new line mode

### ISSUE THREAD

**Issue by gone** [django-import-export/django-import-export#127]
When attempting to open a file saved on a windows computer import-export throw an error:

Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?

It looks like U needs to be added to the open call - see http://stackoverflow.com/questions/17315635/csv-new-line-character-seen-in-unquoted-field-error

**Comment by litchfield** [comment]
Yes there should be an option to support universal (and frankly, I'd have thought that should've been the default option)

**Comment by bmihelac** [comment]
@litchfield thanks for contribution.

I am thinking of treating CSV as text and not binary python2. I am not sure why it is opened as binary and cannot find any documentation regarding this.

Also I do not think there is needed additional setting as this should be a bugfix.

This would be achieved by removing following lines:

https://github.com/django-import-export/django-import-export/blob/master/import_export/formats/base_formats.py#L128-L133

I just need to make csv with office on windows to make sure it does not break anything.

**Comment by litchfield** [comment]
Cool, yes a fix would be even better @bmihelac

**Comment by jdotjdot** [comment]
When will this get released to PyPI?
