### ISSUE TITLE
Import data without id (autogenerate them)

### ISSUE THREAD

**Issue by apelliciari** [django-import-export/django-import-export#128]
Hi,

it's possible to import data from csv without setting the ids in the file? They will be generated on save

Example csv (columns: id, name, league_id):

```
;Atalanta;1
;Cagliari;1
;Cesena;1
;Chievo;1
;Empoli;1
;Fiorentina;1
;Genoa;1
;Inter;1
;Juventus;1
;Lazio;1
;Milan;1
;Napoli;1
;Palermo;1
;Parma;1
;Roma;1
;Sampdoria;1
;Sassuolo;1
;Torino;1
;Udinese;1
;Verona;1
```

Trying to import this with the admin interfarce reports this error:

```
Line number: 1 - u'id'
Traceback (most recent call last):
  File "C:\Home\web\django-fantacalcio-app\.venv\lib\site-packages\import_export\resources.py", line 317, in import_data
    instance, new = self.get_or_init_instance(instance_loader, row)
  File "C:\Home\web\django-fantacalcio-app\.venv\lib\site-packages\import_export\resources.py", line 149, in get_or_init_instance
    instance = self.get_instance(instance_loader, row)
KeyError: u'id'
```

Thanks

**Comment by unifiedsaad** [comment]
i have figure out the solution to import without ID column 
Here is code , Take a Look

        if request.method == 'POST':
        queryset = Client.objects.filter(company=company)
        company = Company.objects.get(id=company)
        person_resource = ClientResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']
        imported_data = dataset.load(new_persons.read().decode('utf-8'), format='csv')
        try:
            for row in dataset:
                client = Client()
                client.company = company
                client.title = row[0]
                client.first_name = row[1]
                client.last_name = row[2]
                client.email = row[3]
                client.position = row[4]
                client.company_name = row[5]
                client.vat_number = row[6]
                client.website = row[7]
                client.address = row[8]
                client.city = row[9]
                client.state = row[10]
                client.zip = row[11]
                client.country = row[12]
                client.phone = row[13]
                client.fax = row[14]
                client.notes = row[15]
                client.save()

        except Client.DoesNotExist:
            raise Http404("There is a Problem with The CSV")

    return render(request, 'import.html')

And my Resource Looks Like this

    class ClientResource(resources.ModelResource):
    company = fields.Field(
        column_name='company',
        attribute='company',
        widget=ForeignKeyWidget(Company, 'name'))

    class Meta:
        model = Client
        skip_unchanged = True
        report_skipped = True
        exclude = ('id', 'company', 'status', 'modified', 'created')
        import_id_fields = ['email']
