### ISSUE TITLE
Exporting json field values into multiple rows of Excel table

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [django-import-export/django-import-export#1291]
Hello.

I have a JsonField  `data` that contains values like this:

    [
        {"id": 1, "name": "Name A", "value": "Value A"},
        {"id": 2, "name": "Name B", "value": "Value B"},
        {"id": 3, "name": "Name C", "value": "Value C"},
    ]

When I try to export my models with this field as an Excel file, it just places them into one cell as text. Is it possible to distribute them into different rows and cels?

**Comment by matthewhegarty** [comment]
You could look at [`after_export()`](https://django-import-export.readthedocs.io/en/stable/api_resources.html?highlight=after_export#import_export.resources.Resource.after_export) to manipulate the data prior to export.

**Comment by matthewhegarty** [comment]
Check out the [tablib documentation](https://tablib.readthedocs.io/en/stable/tutorial/#adding-columns)
