### ISSUE TITLE
Null values rendered as empty strings in JSON exports

### ISSUE THREAD

**Issue by monsieurTut** [django-import-export/django-import-export#1292]
**Describe the bug**
Null values are rendered as empty strings (`""`) in JSON exports, when using `ModelResource`.

**To Reproduce**
Create a model instance with a null field and export it as JSON.

**Versions (please complete the following information):**
 - Django Import Export: 2.5.0
 - Python 3.8
 - Django 3.1.7

**Expected behavior**
When the value of a field is `None`, I would expect it to be rendered as `null` in JSON rather than `""`.

**Additional context**
I believe the problematic piece of code is in [fields.py line 117](https://github.com/django-import-export/django-import-export/blob/main/import_export/fields.py#L117):

```python
    def export(self, obj):
        """
        Returns value from the provided object converted to export
        representation.
        """
        value = self.get_value(obj)
        if value is None:
            return ""
        return self.widget.render(value, obj)
```

**Comment by andyzickler** [comment]
To expand on this, I think the widget itself should be responsible for rendering a None value. I have a project that requires Nones to be exported as `-` and currently i have to use a bunch of dehydrate methods to do it. 

I think fixing this might be pretty straightforward as most of the widgets already check for Nones in their render method.

**Comment by matthewhegarty** [comment]
The best way to achieve this would be to override CharWidget and create a custom render method
