### ISSUE TITLE
Are you considering adding the possibility of dynamically selecting which fields to export

### ISSUE THREAD

**Issue by mehr-licht** [django-import-export/django-import-export#1293]
Hi.

I began using django-import-export today.
Congratulations. It's very simple and easy to use.
I just have a new feature request:  possibility of dynamically selecting which fields to export

**Comment by matthewhegarty** [comment]
Hi Luis

Thanks for the feedback.  If you were to submit a PR with a clean way of adding the option to select fields, then this would be reviewed, and considered for inclusion in the codebase.  I would suggest that this be optional and is disabled by default.

For anyone who reads this in future, here is the [SO thread](https://stackoverflow.com/questions/67651313/select-which-fields-to-export-in-django-import-export) on how to do this by overriding existing methods.

This did highlight an issue in that it is not easy to add a custom ExportForm (in the same way we do for ImportForm).  I'll look into fixing this if I can.
