### ISSUE TITLE
exclude doesn't works with custom Field

### ISSUE THREAD

**Issue by ayushbisht2001** [django-import-export/django-import-export#1294]
```python
   is_vaccinated = fields.Field(
        column_name = 'Is Vaccinated',
        attribute='patient_vaccine_status',
        widget = ForeignKeyWidget(PatientVaccinationStatus, 'is_vaccinated'
        )
    )

class Meta:
        model = PatientProfile
        fields = ('name', 'patient_id', 'contact_number', 'created_on',  'address', 'patient_status', 'bed_id', \
            'is_tested','test_type',  'vaccine_status','patient_migrate_to', 'patient_migrate_on', \
                  'patient_migration_reason' )
        # export_order = ('name', 'patient_id','created_on',  'contact_number', 'address', 'patient_status', 'bed_id','is_tested','test_type', 'is_vaccinated', 'vaccine_status')

        exclude =['is_vaccinated']

```
how can I exclude the is_vaccinated field . 
Actually I am trying to download only selected data based on the filter..  for example, bed_id should not display for expired patients. for that.. I have updated the static exclude variable in  custom filter class , but.. it doesn't works for custom fields (such as is_vaccinated). Is there any way to exclude them, without actually deleting that field (I mean , I don't have to remove the is_vaccinated  field for that)

or if there is any work around then please suggest me, your help and response will be highly appreciated.
Thanks.

**Comment by frba** [comment]
Hi @ayushbisht2001, did you find a solution to your problem? I'm having the same problem. I want to export some fields but not use them to import.

**Comment by furkandemireleng** [comment]
Me too. Can anyone know the solution ? Please help us 🙏

**Comment by matthewhegarty** [comment]
If you want to control which fields appear in the export, you can override `get_export_order()` to return an iterable containing just the fields you need, for example, this will export only the 'id' field.

```python
class BookResource(resources.ModelResource):
    name = Field(attribute="name", column_name="Book Name")

    def get_export_order(self):
        return ("id",)

    class Meta:
        model = Book
        fields = ('id', 'name', 'author_email')
```

If you want to control which fields are exported, perhaps based on a check against the instance to be exported, then there are some hooks in the code which you can use to modify the data before it is exported:

- `before_export(queryset, *args, **kwargs)`
- `after_export(queryset, data, *args, **kwargs)`

You can override these methods in your `Resource` class.  Alternatively you can override the `export()` method completely to have complete control over the export.

**Comment by OttoAndrey** [comment]
@matthewhegarty Looks odd for me but thank you for solution!
