### ISSUE TITLE
Timeout retrieving big file

### ISSUE THREAD

**Issue by DoMaT** [django-import-export/django-import-export#1296]
When retrieving the data with ImportExportActionModelAdmin, I get the time-out related failure - see logs:

Wed Jun  2 10:23:43 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /admin/daj_wlos/targetowanieraport/?kontakt_z_fundacja__exact=1 (ip 127.0.0.1) !!!
Wed Jun  2 10:23:43 2021 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 341] during POST /admin/daj_wlos/targetowanieraport/?kontakt_z_fundacja__exact=1 (127.0.0.1)
OSError: write error

It's raised after 60 seconds when e.g. xlsx export option is picked. Is there any chance to configure the timeout in this plugin? https://stackoverflow.com/questions/2719017/how-to-set-timeout-on-pythons-socket-recv-method might be related

**Comment by matthewhegarty** [comment]
The timeout will be a webserver setting - it's not controlled by this library
