### ISSUE TITLE
using customized changelist template

### ISSUE THREAD

**Issue by saeedhmt** [django-import-export/django-import-export#1300]
Hi.
I have a customized changelist template for a model. is there a way to use that with the package?

**Comment by ffuentese** [comment]
I have the same question. I wanna customize the import form (just add a link, nothing else) and I wanna overwrite it. I can overwrite the whole thing for the entire admin app but not for a specific model app. Is this possible?

**Comment by saeedhmt** [comment]
> I have the same question. I wanna customize the import form (just add a link, nothing else) and I wanna overwrite it. I can overwrite the whole thing for the entire admin app but not for a specific model app. Is this possible?

if you check the source code of package, in 'admin.py' file and  in 'ImportMixin' class there is a variable named 'import_template_name'. I think you can overwrite it for a modelAdmin and set it to the address of customized import template like this:

class SnmpModelAdmin(ImportExportActionModelAdmin):
    import_template_name = 'address of customized import template'

**Comment by ffuentese** [comment]
> > I have the same question. I wanna customize the import form (just add a link, nothing else) and I wanna overwrite it. I can overwrite the whole thing for the entire admin app but not for a specific model app. Is this possible?
> 
> if you check the source code of package, in `admin.py` file and in `ImportMixin` class there is a variable named `import_template_name`. I think you can overwrite it for a modelAdmin and set it to the path of customized import template like this:
> 
> ```python
> class SnmpModelAdmin(ImportExportActionModelAdmin):
>     import_template_name = 'path of customized import template'
> ```

Thanks! This worked and I saw it in the documentation as well. Now I wonder if it can be detected automatically which is what's suggested for django admin's templates or if templates just can be overwritten with an explicit indication like this.

**Comment by matthewhegarty** [comment]
#1483 was added to 3.0.0 and included options for customization of template.  Closing issue.
