### ISSUE TITLE
Get empty row after importing a dataset

### ISSUE THREAD

**Issue by oussama-he** [django-import-export/django-import-export#1304]
I am importing a file with django import-export and I want to take the values of each row.

```python
def get_import_data(file):
    hr_dataset = Dataset()
    return hr_dataset.load(file.read(), format='xlsx', headers=True)


def upload_hr_file(request):
    if request.method == 'POST':
        hr_file = request.FILES['hr-file']
        data = get_import_data(hr_file)
        hr_resource = HREmployeeResource()
        result = hr_resource.import_data(data, dry_run=True, raise_errors=True)
        if not result.has_errors():
            result = hr_resource.import_data(data, dry_run=False, raise_errors=True)
            for row in result.rows:
                print(row.raw_values)

    return render(request, 'core/upload-hr-file.html', {})

```
I iterate through the rows of the Result with `result.rows` and each row seems to have a raw_values property but it returns an empty dict.

Please, how can access the values of each row?

Thank you in advance.

**Comment by matthewhegarty** [comment]
> each row seems to have a raw_values property but it returns an empty dict.

I can confirm that the `raw_values` attribute was added in #852, but it is not used.  It may have been added as a placeholder, and it could be used by subclasses.  

There is currently no way to access the row values from the result by default, but you can override `after_import_row()` to achieve this:

```python
def after_import_row(self, row, row_result, row_number=None, **kwargs):
    row_result.raw_values = row
```
