### ISSUE TITLE
Import files in app with two or more containers provisioned

### ISSUE THREAD

**Issue by flaviosilva-iteris** [django-import-export/django-import-export#1320]
**Describe the bug**
Currently, when we want to import a file, in the first screen django-import-export send that file to save it in the server's temp directory and return a form where there is the file's data to user confirm if they want to import it. After the user's confirmation, the library uses the file saved on the temp directory and import its data.

When an app has two or more containers provisioned, that approach doesn't work because it's impossible to ensure the same container where the file has been created will be the same container that will receive the request to import that file.

**To Reproduce**

1. Install django-import-export in some Django app
2. Configure some Admin menu to use the import function
2. Run that app with two or more containers provisioned
3. Import file through Admin menu
4. It'll show an error 

**Versions (please complete the following information):**
 - Django Import Export: 2.5.0
 - Python: 3.7
 - Django: 2.2.24

**Expected behavior**
The file should be imported regardless of how many containers are running

**Screenshots**
![image](https://user-images.githubusercontent.com/85254106/130852224-1638ba90-7c91-4b1e-827b-978e8f10d52c.png)

**Additional context**
I've created [this pull request](https://github.com/django-import-export/django-import-export/pull/1319) with the solution to solve that problem.

**Comment by TraderSamwise** [comment]
I know this is ridiculous but yea this fixed my exact same problem. I was only on 2.4.0 so not nearly as behind but all good now. Thanks for this library and for keeping up with all the issues!

**Comment by matthewhegarty** [comment]
There are two ways to address this:

1.  [Disable the confirmation page](https://github.com/django-import-export/django-import-export/blob/main/docs/installation.rst#import_export_skip_admin_confirm)

2. [Store confirmation data](https://github.com/django-import-export/django-import-export/blob/main/docs/advanced_usage.rst#import-confirmation) in a cache other than the filesystem, which may not work in a container setting.
