### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by daviddavis** [django-import-export/django-import-export#1321]
It looks like the latest release of django-import-export (2.5.0) was back in December 2020. Any chance we could get a new release? We could really use some of the bug fixes like https://github.com/django-import-export/django-import-export/commit/f348ef3782e60d44a2cedd0062179f0b9c798510.

Thank you.

**Comment by matthewhegarty** [comment]
Release 2.6.0 now available on [pypi.org](https://pypi.org/project/django-import-export/)

**Comment by daviddavis** [comment]
Thank you!
