### ISSUE TITLE
Documentation of properties required for row_result

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1322]
**Describe the bug**

The `row_result` object which is generated by each row import has undocumented properties.  This was raised [here](https://stackoverflow.com/a/68954762/39296).

** Solution **

I guess attributes should be documented [here](https://django-import-export.readthedocs.io/en/latest/api_results.html#import_export.results.Result)

**To Reproduce**

**Versions (please complete the following information):**
 - Django Import Export: 2.5.0
 - Python (all)
 - Django (all

**Comment by prakhar1144** [comment]
Hi, @matthewhegarty 
I would like to work on this issue.
Please assign this to me.

**Comment by matthewhegarty** [comment]
Done - thanks

**Comment by matthewhegarty** [comment]
Addressed in #1584
