### ISSUE TITLE
yaml export crashes for objects with decimal values

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1324]
**Describe the bug**

Export is broken when one tries to export an object containing a `DecimalField` (e.g. Book).

The error is:

```
RepresenterError at /admin/core/book/export/
('cannot represent an object', Decimal('1.00'))
```

**To Reproduce**
1. Login to the Admin site
2. Create a book with a 'price' value
3. Export books (select 'yaml' format)
4. The crash should occur.

**Versions (please complete the following information):**
 - Django Import Export: 2.5.0
 - Python 3.9
 - Django 3.2

**Expected behavior**

Yaml export should work correctly.  Other exports work correctly.

**Stack trace**

```
Exception Type:	RepresenterError
Exception Value:	
('cannot represent an object', Decimal('1.00'))
Exception Location:	/home/matthew/.virtualenvs/django-import-export/lib/python3.9/site-packages/yaml/representer.py, line 231, in represent_undefined
```

**Comment by matthewhegarty** [comment]
Also #341

**Comment by Actionb** [comment]
pyyaml has an open issue on this: https://github.com/yaml/pyyaml/issues/255
There even is a PR up to fix, but no move has been made on this issue for 2+ years.

As a quick fix, `DecimalWidget.render` could just return a string version of the decimal value.

**Comment by 1gni5** [comment]
> pyyaml has an open issue on this: [yaml/pyyaml#255](https://github.com/yaml/pyyaml/issues/255) There even is a PR up to fix, but no move has been made on this issue for 2+ years.
> 
> As a quick fix, `DecimalWidget.render` could just return a string version of the decimal value.

That has been done in #1501 and it seems to fix the problem.

**Comment by matthewhegarty** [comment]
Still an issue using `release-4` branch

**Comment by bmihelac** [comment]
By default `NumberWidget` coerces to string.

It looks that [pyyaml](https://github.com/yaml/pyyaml/issues/255) does not work not only with `Decimal` , but also with `SafeString` types.
To reproduce:

```python
from django.utils.safestring import SafeString
import yaml
yaml.safe_dump(SafeString("1"))
```
