### ISSUE TITLE
Missed wheel for 2.6.0 release

### ISSUE THREAD

**Issue by Mogost** [django-import-export/django-import-export#1327]
2.6.0
![image](https://user-images.githubusercontent.com/721963/133750989-2df0b780-e6bc-4b4a-ad85-7efe602787c8.png)

2.5.0
![image](https://user-images.githubusercontent.com/721963/133750954-534a2573-4528-4de0-85f6-0632797250b4.png)

**Comment by matthewhegarty** [comment]
thanks for raising, we will take a look

**Comment by Mogost** [comment]
@matthewhegarty In fact, I would suggest that you automate the release of new versions via GitHub Actions. This will firstly make the release of new versions easier, and secondly, it will guarantee repeatability.

**Comment by matthewhegarty** [comment]
The 2.6.0 wheel is [now available](https://pypi.org/project/django-import-export/2.6.0/#files).
