### ISSUE TITLE
Dark mode styles makes our page unreadable

### ISSUE THREAD

**Issue by jedie** [django-import-export/django-import-export#1330]
The "dark mode styles" was added with: https://github.com/django-import-export/django-import-export/commit/7fc06627e2f12d719c03a6528cb63f05da256ca1 for: https://github.com/django-import-export/django-import-export/issues/1318

Our page doesn't support dark mode yet. So these styles makes the diff unreadable.

A work-a-round, that we currently use is to add these styles in our css file:
```
@media (prefers-color-scheme: dark) {
  /*
  Work-a-round for https://github.com/django-import-export/django-import-export/pull/1323
  */
  html table.import-preview tr.skip {
    background-color: #d2d2d2;
  }

  html table.import-preview tr.new {
    background-color: #bdd8b2;
  }

  html table.import-preview tr.delete {
    background-color: #f9bebf;
  }

  html table.import-preview tr.update {
    background-color: #fdfdcf;
  }

  html .validation-error-container {
    background-color: #ffc1c1;
  }

  /*
  these declarations are necessary to forcibly override the
  formatting applied by the diff-match-patch python library
   */
  html table.import-preview td ins {
    background-color: #bdd8b2 !important;
  }

  html table.import-preview td del {
    background-color: #f9bebf !important;
  }
}
```
That will "reset" the dark colors to "normal" ones...

**Comment by matthewhegarty** [comment]
Thanks for raising this.  Can you give me some more information as to what the issue is...  How do you reproduce it?  Can you add some screenshots?  What browser is this etc.

**Comment by jedie** [comment]
Sorry, i can't create a screenshot... (They will display internal information)

We still use Django 2.2... Don't know if the admin has "dark"-Styles ?!? I don't think so. So it can't work with 2.2?!?

**Comment by matthewhegarty** [comment]
I tested using the example app on django 2.2.  It renders ok for imports, but I notice that if you switch to dark mode in the browser then there is an issue where the text is not legible (below).  Is this what you are seeing?.  Can you confirm if you are browsing in "dark mode"?  If, so, what happens if you switch to 'light mode'?

![dm1](https://user-images.githubusercontent.com/6249838/135441264-8cf5c032-7e92-4a46-b653-5f6d5697640a.png)

**Comment by jedie** [comment]
That is exactly how this "bug" looks like here:

![grafik](https://user-images.githubusercontent.com/71315/135448815-f8bbdd41-79ac-4a4d-9a8c-91b1ad6042af.png)
