### ISSUE TITLE
Update only certain fields when importing?

### ISSUE THREAD

**Issue by fcoppey** [django-import-export/django-import-export#1333]
I am trying to import an xlsx file with only one column from the Django model that want to update instances. The import module asks for fields in my xlsx that are mandatory in the Django model (like created field that has auto_now_add=True and therefore does not need to be updated during the import). is this package made specially to import instances completely with all the fields or one can use it as bulk update package for specific fields?

Thanks

**Comment by matthewhegarty** [comment]
> is this package made specially to import instances completely with all the fields or one can use it as bulk update package for specific fields?

You can just update specific fields - see the [docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-resource-options) on using the `fields` meta attribute to whitelist fields to import.

**Comment by fcoppey** [comment]
Thank you but it seems more complicated than that, as I keep getting errors like field “created_at” cannot be null. Although I do not want to import this field and it is not in my fields meta attribute list.
This field was auto_add_now at creation, now I don’t want to touch it anymore.

On 4 Oct 2021, at 13:12, Matt Hegarty ***@***.******@***.***>> wrote:



is this package made specially to import instances completely with all the fields or one can use it as bulk update package for specific fields?

You can just update specific fields - see the docs<https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-resource-options> on using the fields meta attribute to whitelist fields to import.

**Comment by matthewhegarty** [comment]
If you are doing a standard import (i.e non-bulk), then `instance.save()` gets called, so you can test in the django shell whether this will persist your object correctly with any defaults set.

However, if using bulk mode, then [`save()` does not get called](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-update).  In which case, you'll have to set any defaults on your instance by overriding the `before_save_instance()` method.
