### ISSUE TITLE
fa language not work

### ISSUE THREAD

**Issue by hamedyosefian** [django-import-export/django-import-export#1337]
FA language not work because not have  .mo file 

**Versions (please complete the following information):**
 - Django Import Export: [e.g. 1.2, 2.0]
 - Python [e.g. 3.6, 3.7]
 - Django [e.g. 1.2, 2.0]

**Comment by matthewhegarty** [comment]
Are you able to supply this translation?

**Comment by matthewhegarty** [comment]
Fixed in #1299
