### ISSUE TITLE
Import into Multiple Model from single Dataset 

### ISSUE THREAD

**Issue by VaZark** [django-import-export/django-import-export#1340]
Is there a way to define a resource on admin so that data from a single dataset can be used to populate multiple ModelResource? If not, would you be amenable to accept a patch for the same?

Something along the lines of,

```python
class ParentModelResource(resource.ModelResource):

   class Meta:
       model = ParentModel
       related_models = [
           'RelatedResource'
       ]

class RelatedModelResource(resource.ModelResource):
    parent = fields.field(attribute='parent',column_name='common_id',
        widget=ForeignKeyWidget(ParentModel, 'common_id')
        )

   class Meta:
       model = RelatedModel
```

**Comment by matthewhegarty** [comment]
My view is that you could achieve this quite easily using existing hooks in the code base, for example:

```python
def after_save_instance(self, instance, using_transactions, dry_run):
  related_instance = RelatedModel()
  # copy fields from instance into related_instance
  related_instance.save()
```

The downside of this is that it would not be atomic, so if that is an issue you could override `save_instance()` itself and save both the instance and the related instance in a transaction.

**Comment by VaZark** [comment]
While I’ve not tested this yet, the problem with approach is possibly the fact that this might not be extensible to bulk operations . 

I could create the child list and trigger the create/update after the import with `after_import`. 

Having said that, i think having an explicit function for that or documentation on how to do it would be super helpful to people new to the library or those use it one in a blue moon.
