### ISSUE TITLE
Should openpyxl and xlrd be listed in configuration files?

### ISSUE THREAD

**Issue by yuluc123** [django-import-export/django-import-export#1349]
Hi,
I notice that **openpyxl  and xlrd** are used as  direct dependencies in import_export/formats/base_formats.py. So should openpyxl  and xlrd be listed in configuration files?

**Comment by matthewhegarty** [comment]
by 'configuration files', do you mean requirements files?

**Comment by yuluc123** [comment]
Hi, I mean that if the dependency is directly used in code files, it should be declared. "Configuration files" here， for example requirements-*.txt

**Comment by matthewhegarty** [comment]
Thanks for raising this - I'll look into updating requirements.

**Comment by matthewhegarty** [comment]
I looked into this and I think we are OK with the dependencies as they are.  In our `base.txt`, we have:

```
tablib[html,ods,xls,xlsx,yaml]>=3.0.0
```
(also in `setup.py`)

hence `openpyxl` and `xlrd` are provided by [tablib](https://github.com/jazzband/tablib/blob/91beb35a77e3a7e290e42ccad35b6fee5059e3f7/setup.py#L43) as [optional dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies).  Therefore we can be sure that the dependencies will be installed, and that we will have the versions that are known to work with tablib.  I think if we define the specific versions for openpyxl and xlrd we run the risk of introducing subtle bugs where these dependencies get out of sync with tablib.

Therefore I propose to take no further action.  Let me know if you disagree with the above.
