### ISSUE TITLE
Export only list_display colums with verbose_name's ?

### ISSUE THREAD

**Issue by furkandemireleng** [django-import-export/django-import-export#1350]
Hello I am newbie for django so I have basic question.
In my admin class I added ExportMixin and  I want to save excel file with my list_display colums and verbose names.
Not id colum or lets say I have status it says keep going or not doing but I show 0 -1 under the status.

I am still looking for the answer please help me :)

mycode :

```
@admin.register(Ico)
class IcoAdmin(ExportMixin, BaseAdmin):
    list_display = (
        'account', 'pair', 'amount', 'ico_situation', 'expire_date', 'price',
        'token_amount', 'reference_user', 'get_reference_user_income')
    list_filter = ('account', 'account__is_bot')
    search_fields = ('account_id', 'wallet_id', 'ico_situation')

    raw_id_fields = ('account', 'pair', 'wallet', 'reference_user')
```
My Excel table :

id | account | wallet | pair | amount | token_amount | final_token_amount | expire_date | status | ico_situation | price | reference_code | reference_user
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
152 | 111 | 789 | 12 | 100 | 400 | 0 | 2022-03-17 | 1 | 1 | 0,25 |   |  
151 | 111 | 789 | 12 | 100 | 200 | 0 | 2021-11-17 | 1 | 0 | 0,5 |   |  
150 | 111 | 789 | 12 | 100 | 200 | 0 | 2021-11-17 | 1 | 0 | 0,5 |   | 2
149 | 111 | 789 | 12 | 100 | 200 | 0 | 2021-11-17 | 1 | 0 | 0,5 |   |  
148 | 111 | 789 | 12 | 100 | 200 | 0 | 2021-11-17 | 1 | 0 | 0,5 |   | 2
147 | 111 | 789 | 12 | 100 | 200 | 0 | 2021-11-17 | 1 | 0 | 0,5 |   |  
146 | 111 | 789 | 12 | 100 | 200 | 0 | 2021-11-17 | 1 | 0 | 0,5 |   | 2

Table I want:
(https://ibb.co/8YpQ0S1)

**Comment by matthewhegarty** [comment]
Hi - I left a comment on the [SO](https://stackoverflow.com/q/70017379/39296) post.  Please update your question there if you need more help.

**Comment by furkandemireleng** [comment]
> Hi - I left a comment on the [SO](https://stackoverflow.com/q/70017379/39296) post. Please update your question there if you need more help.

Thanks I am looking for now

**Comment by furkandemireleng** [comment]
Yes I try example app but it is not what I need.
example app's exel form contains all Book model fields but I want only list_display fields with model's verbose name.
Is it possible ? Can you help me please ? Thanks

**Comment by furkandemireleng** [comment]
> > Hi - I left a comment on the [SO](https://stackoverflow.com/q/70017379/39296) post. Please update your question there if you need more help.
> 
> Thanks I am looking for now

Yes I check and do

**Comment by furkandemireleng** [comment]
Guys I found my solution.
 
 codes here:
 --the example app's admin page

```
 class BookResource(ModelResource):
    published = Field(attribute='published', column_name='Basim Tarihi')
    yazaradi = Field(attribute='author__name', column_name='Yazar Adi')
    # ico_situation = Field(attribute='ico_situation', column_name='Ico Durumu')
    imported = Field(attribute='imported', column_name='Onemli MI')
    ico_situation = Field(attribute='ico_situation')

    class Meta:
        model = Book
        widgets = {
            'published': {'format': '%d.%m.%Y'},
        }

        fields = ('yazaradi', 'price', 'author_email', 'categories', 'published', 'imported', 'ico_situation')
        export_order = ('yazaradi', 'price', 'author_email', 'categories', 'published', 'imported', 'ico_situation')

    def for_delete(self, row, instance):
        return self.fields['name'].clean(row) == ''


class BookAdmin(ImportExportMixin, admin.ModelAdmin):
    list_display = ('name', 'author', 'added')
    list_filter = ['categories', 'author']
    resource_class = BookResource
```

you can rename excel colums under the ModelResource class
