### ISSUE TITLE
could export and import png file?

### ISSUE THREAD

**Issue by Tina0330** [django-import-export/django-import-export#1354]

**Comment by matthewhegarty** [comment]
From what I know of the library I don't think this is going to be possible.  `django-import-export` uses [xlrd](https://xlrd.readthedocs.io/) to handle xlsx imports (via [tablib](https://tablib.readthedocs.io/en/stable/)) and exports via [xlwt](https://pypi.org/project/xlwt/).  I had a quick google to see if xlrd supports png in spreadsheets, maybe it's [possible](https://stackoverflow.com/a/19306015/39296) to do something here.

If your own research reveals anything feel free to post back here.
