### ISSUE TITLE
Can't use example

### ISSUE THREAD

**Issue by Samoht1** [django-import-export/django-import-export#1355]
**Describe the bug**
Cannot use manage.py in example app.

**To Reproduce**
1. Clone repo (_pip install -e git+https://github.com/django-import-export/django-import-export.git#egg=django-import-export_)
2. `cd tests`
3. `python manage.py makemigrations`
4. Error:  `ModuleNotFoundError: No module named 'django_extensions'`

**Versions (please complete the following information):**
 - Django Import Export: 2.7.1
 - Python 3.9
 - Django 4.0

**Expected behavior**
Run makemigrations in example app

**Comment by matthewhegarty** [comment]
In your virtual environment, try:

```
pip install -r requirements/test.txt
```

**Comment by Samoht1** [comment]
Yea that did the trick, thanks!
