### ISSUE TITLE
Model is imported with empty pk value

### ISSUE THREAD

**Issue by ratondeau** [django-import-export/django-import-export#1360]
**Describe the bug**
I try to import a csv file via django admin with only one column which is also the primary key field for that model. The csv consist of 3 columns but only the first one is of any interest here. The import seems to work as I get a success message but if I look at the list view in django admin there is only one more entry with an empty key field. 

**To Reproduce**
Prerequisite is the following model:
```
class Token(models.Model):
    key = models.CharField(db_index=True,unique=True,primary_key=True,    )
    state = models.PositiveSmallIntegerField(default=State.VALID, choices=State.choices)
```

then
```
class TokenResource(resources.ModelResource):
    class Meta:
        model = Token
        report_skipped = True
        import_id_fields = ("key",)
        fields = ("key",)
```

the django Admin entry:
```
class TokenAdmin(ImportMixin, admin.ModelAdmin):
    resource_class = TokenResource
```

and some csv:
key;type;number
ABCDEFG;Publication;101549
GFEDCBA;Publication;101549

then go to this model in django admin list view and click import. Choose file with sample data, csv and click import.
On the preview you get table with 
![import token](https://user-images.githubusercontent.com/41551756/146958980-4436aa23-f649-4b42-95fc-de7a39a8fb7b.png)

After clicking import you get the success message:
![token import success](https://user-images.githubusercontent.com/41551756/146959283-1426d6c7-ddf9-4120-b303-c9cff8818c1a.png)

**Versions (please complete the following information):**
 - Django Import Export: 2.7.0
 - Python 3.9
 - Django 3.2

**Expected behavior**
A list with the imported Tokens should appear within the list view, with a filled key value

**Details**
 import_export.resources.ModelResource.init_instance --> return self._meta.model()
 returns an instance without a key although the key value has been passed with the row

**Comment by matthewhegarty** [comment]
Can you create a branch that reproduces this issue?

**Comment by ratondeau** [comment]
Yes sure, I have created a minimal project under: git@github.com:ratondeau/django-import-export.git wit a sample file and the import model. Pipenv is used for setting up the environment. PG database is used but could be easily switched to sqlite

**Comment by matthewhegarty** [comment]
I can take a look but you'll have to give me as much as you can to reproduce the issue - I don't have time to work it out for myself.

I will need:

- Simple instructions to setup the environment
- Step-by-step instructions on reproducing the issue

**Comment by ratondeau** [comment]
Hi 

Python version 3.9.9 is configured within the Pipfile, that could be adapted to your needs.
If you have pipenv installed it is as easy as just type in `pipenv install` otherwise it should be installed before.
Set PYTHONPATH to python binary within the created venv and DJANGO_SETTING_MODULE environment variable to settings  

1. copy .env.sample to .env and adapt db settings in .env 
2. `pipenv shell` to activate the environment
3. create superuser for django admin
4. make migrations and migrate for the model
5. run the server
6. Login with your account
7. Go to the Token-Model (ListView)
8. Click import on the top right
9. Choose import-sample.csv provided within the repository
10. see the previev and click confirm import

**Comment by matthewhegarty** [comment]
OK thanks - your issue is a simple one - you are using ';' as the delimiter in your csv.  If you change this to ',' it will work:

![2021-12-22_10-34](https://user-images.githubusercontent.com/6249838/147079300-7b931c7e-1ef7-42fb-be3d-e0af53827467.png)

If you need to use semi-colon as the delimiter, there are instructions [here](https://github.com/django-import-export/django-import-export/issues/181#issuecomment-391579943).

**Comment by ratondeau** [comment]
Ok thanks, must have overlooked that. I cannot change this somewhere in the settings, right? So I will adapt the file.
