### ISSUE TITLE
Resource._meta doesn't get params from parent's parent's Meta

### ISSUE THREAD

**Issue by ramazanFarrahov** [django-import-export/django-import-export#1363]
**Describe the bug**
`Resource._meta` does get params from own `Meta` and from parent's `Meta`. But it doesn't get params from `Meta` of parent's parent's `Meta`

**To Reproduce**
Execute the following code:
```
from import_export.resources import Resource

class MyBaseResource(Resource):
    class Meta:
        # random parameter to show error
        batch_size = 123456789


class MyResource(MyBaseResource):
    class Meta:
        pass


class MyChildResource(MyResource):
    class Meta:
        pass

print(f'MyResource: {MyResource()._meta.batch_size}')
print(f'MyChildResource: {MyChildResource()._meta.batch_size}')
```
Output:
```
MyResource: 123456789 # right
MyChildResource: 1000 # wrong, default value of `ResourceOptions.batch_size`
```

**Versions (please complete the following information):**
 - Django Import Export: 2.7.0
 - Python 3.9
 - Django 4.0 

**Expected behavior**
`MyChildResource` should get params from `MyBaseResource`

**Possible Solution**
`import_export.resources.DeclarativeMetaclass` should copy params from parent's `_meta` instead of `Meta`.

**Comment by matthewhegarty** [comment]
thanks - I have seen this before and we will look into when we can.
