### ISSUE TITLE
Allow default format selections on import, export, and action screens

### ISSUE THREAD

**Issue by pokken-magic** [django-import-export/django-import-export#1373]
It would be useful to allow specifying a default format on the import and export screens as well as the actions. On some of the screens it will auto-select if you only have one option, but the Actions do not work that way. If you're always using a specific format (or usually even) it gets to be a lot of clicking going back to Yaml or Json or what have you from the menu.

**Comment by shimakaze-git** [comment]
Hi.
I want to work for this issue, can I try that? :)

**Comment by radiophysicist** [comment]
Is it implemented?

**Comment by matthewhegarty** [comment]
Yes it should be, please see #1389.  I recommend upgrading to [v4 rc][1] if you can.

[1]: https://pypi.org/project/django-import-export/4.0.0rc3/
