### ISSUE TITLE
Export from a specific model view page in Django Admin

### ISSUE THREAD

**Issue by pokken-magic** [django-import-export/django-import-export#1374]
Does anyone have any ideas on the best way to add an export button on a model instance's page in Django Admin? The thought being that if you browse to a resource, it would be fairly natural workflow-wise to want to be able to click Export on that page and export that model instance.

I imagine that it is fairly easy to custom code this but it might be a cool feature as a mixin for the model admin, or as an additional feature for the ExportActionMixin.

**Comment by pokken-magic** [comment]
I think on this that it should be coupled to the export action. If you have the export action enabled you should be able to export a model from its page (and trigger the export workflow etc just like when you select models and do the drop down).  I’ll wish I was better at the django admin code so maybe this would be a decent learning opportunity for me.

**Comment by matthewhegarty** [comment]
Export from actions are being refactored in #1671.  Perhaps we could look into this also.
