### ISSUE TITLE
Exporting Decimal Values

### ISSUE THREAD

**Issue by gorkemye** [django-import-export/django-import-export#1377]
When i export my data, instead of 0 i get 0E-8 How can i fix this ?
![image](https://user-images.githubusercontent.com/73352935/148574654-ad6c0fb8-7e81-4648-872f-70847c6cea6f.png)

**Comment by matthewhegarty** [comment]
I wonder if it is an excel formatting issue - does [this help](https://youtu.be/2hBdYlgz0pQ)?  If not, can you reproduce with the example app (it has a Book object with a 'price' decimal field).
