### ISSUE TITLE
Documentation for customizing admin forms is out-of-date / unclear

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1396]
The documentation describes how to [customize the import forms](https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-admin-import-forms).  The example shows how you can add an `author` field, but it doesn't make it clear what the purpose of this is, and that you have to provide any filtering capabilities yourself.  This has led to some [confusion](https://stackoverflow.com/q/71161607/39296).

I propose to update this section so that it is clearer why you would want to customize the import forms, and to give an example of how to filter using a dropdown.

**Comment by eldavo** [comment]
Thanks Matthew for the help on StackOverflow.  I expect the issue I encountered as a new user of django-import-export is not uncommon and it would be great to make the docs around this more specific.  https://stackoverflow.com/questions/77085694/django-import-export-customize-admin-missing-field-error

**Comment by matthewhegarty** [comment]
Hi Dave, yes I agree that the docs could be improved.  If you felt like sharing your experiences and submitting a PR, I'd be happy to review.

**Comment by Murgowt** [comment]
Hello @matthewhegarty, Could you please assign this issue to me, I would love the opportunity to work on this issue.

**Comment by matthewhegarty** [comment]
Hi - thanks for the offer of help.  Please use the `release-4` branch as this has the most recent changes.  I strongly recommend posting your proposal for changes here before starting on any work, just so we can be sure it fits.

Please read [this comment](https://github.com/django-import-export/django-import-export/issues/1740#issuecomment-1900465490).  It is an improvement to the documentation which demonstrates how the selected 'author' field can be saved to the db.

Another area that might be of interest is to post tutorials on dev.to demonstrating how to use and customise the example app.  If these are useful, we can link from the github README page.

**Comment by matthewhegarty** [comment]
Closing - documentation was updated in v4
