### ISSUE TITLE
Import fails when CacheStorage enabled and file contains LF char

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1397]
**Describe the bug**

If using `CacheStorage`, the process crashes if attempting to import a file with the `/r` feed char (which was the default on mac os).

I believe this is a [bug in `tablib`](https://github.com/jazzband/tablib/issues/517).

**To Reproduce**

- Set `tmp_storage_class` to `CacheStorage` in `admin.py`
- Use the UI to import the file `tests/core/exports/books-mac.csv`
- The import will fail with 'Error encountered while trying to read file: books-mac.csv'
- The underlying exception is 'new-line character seen in unquoted field - do you need to open the file in universal-newline mode?'
 
**Versions (please complete the following information):**
 - Django Import Export: 2.7.2
 - Python 3.9.10
 - Django 4.0

**Expected behavior**

The file should import without issue.

**Additional context**

I found this whilst testing #1306 so wanted to record it here so that it is a known issue.

**Comment by matthewhegarty** [comment]
This is fixed in an upstream change in [tablib](https://github.com/jazzband/tablib/pull/518).

**Comment by hugovk** [comment]
> This is fixed in an upstream change in [tablib](https://github.com/jazzband/tablib/pull/518).

Released in Tablib 3.2.1 :rocket:

https://github.com/jazzband/tablib/releases/tag/v3.2.1

**Comment by matthewhegarty** [comment]
Fixed in release 3
