### ISSUE TITLE
Deleting xlsx row causes the import dataset to become huge

### ISSUE THREAD

**Issue by abithyzis** [django-import-export/django-import-export#1399]
**Describe the bug**
I have the following resource I use to import users

```
class CustomUserResource(resources.ModelResource):
    store = fields.Field(
        column_name='store_id',
        attribute='store',
        widget=ForeignKeyWidget(Store, 'store_id'))

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email', 'store')
        unique_id_fields = ('email',)
        import_id_fields = ('email',)
        export_order = ('first_name', 'last_name', 'email', 'store')
```

I am using this [users.xlsx](https://github.com/django-import-export/django-import-export/files/8125598/users.xlsx) file and everything works fine.
If I select a row and delete it then when I attempt to import the new [users_broken.xlsx](https://github.com/django-import-export/django-import-export/files/8125599/users_broken.xlsx) the size of the dataset [here](https://github.com/django-import-export/django-import-export/blob/125c1cff2958a43f9824843ee90c27f5dc0280d5/import_export/resources.py#L812) is
![image](https://user-images.githubusercontent.com/795664/155353867-01b8fdbd-3c30-4b32-b6a4-a8b339a86117.png) even though the file contains only one record

**To Reproduce**
1. Delete row in users.xlsx
2. Attempt to import users.xlsx (in this case users_broken.xlsx)
3. Wait

**Versions (please complete the following information):**
 - Django Import Export: [2.7.1]
 - Python [3.7]
 - Django [3.2.8]

**Expected behavior**
Expect either the correct number of rows to be imported or an error

**Comment by matthewhegarty** [comment]
Please can you confirm which version of django-import-export you are using?

**Comment by matthewhegarty** [comment]
I wonder if there are [hidden rows](https://support.microsoft.com/en-us/office/hide-or-show-rows-or-columns-659c2cad-802e-44ee-a614-dde8443579f8) in the Excel file you are importing.  You could save the excel as csv and try to import it that way.

**Comment by matthewhegarty** [comment]
> deleting any row causes this issue.

The only thing I can think of is that there are a lot of hidden rows for some reason.  If you could export the problem file to csv it might answer that question.  It looks like the number of rows you are seeing is related to [Excel](https://www.google.com/search?q=1048575+excel&oq=1048575+excel&aqs=chrome..69i57.4502j0j7&sourceid=chrome&ie=UTF-8), so I don't think this is a django-import-export bug.

**Comment by abithyzis** [comment]
Exporting the users_broken.xlsx file I linked to csv produces a 3 line csv file (header, user, empty)
