### ISSUE TITLE
可以导出表格内为图片吗？

### ISSUE THREAD

**Issue by wuqiang-001** [django-import-export/django-import-export#1403]
想把用户头像导出，希望是图片，而不是url

**Comment by matthewhegarty** [comment]
Sorry - very unlikely we can help unless you can post in English.

**Comment by pokken-magic** [comment]
> 想把用户头像导出，希望是图片，而不是url

If this translation service is right,

> I want to export the user's avatar, I hope it is a picture, not a url

We do not support exporting base64 encoded images or files today, but it's a pretty good idea and one I have thought about writing a few times. The approach I would probably take is to make a custom widget that Renders a tuple of ("path/to/file", "base64encoded data") and returns that as a string, then on the way back hydrates that in its Clean method into a ContentFile or similar Django field.

If you build it I think it could be something good to add to the repo. If get around to building it I'll let you know as well.
