### ISSUE TITLE
Add property method to fields

### ISSUE THREAD

**Issue by israelabraham** [django-import-export/django-import-export#1404]
Hello, everyone!

I want to know if it's possible to pass a property method to fields. Example:

```
class PaymentResources(resources.ModelResource):
    """This class is used to import data from the Payment model to a CSV file"""
    
    class Meta:
        model = Payment
        fields = ("id", "user__name", "amount", "transaction",\
            "product", "payment_type", "verified", "email", "date_created", )

    @property
    def user__name(self, obj):
        """
        Return the fullname of the user
        
        :param obj: The object that is being rendered
        :return: The fullname of the user.
        """
        return obj.user.fullname()
```

Where `user__name` is a custom method. I want to export the user fullname, not id. I get the following error when I try the above code:

`django.core.exceptions.FieldDoesNotExist: Payment.user.name: User has no field named 'name'`

I'll appreciate a blog guide or anything at all. Thank you so much!

**Comment by matthewhegarty** [comment]
Take a look at the [`dehydrate`](https://django-import-export.readthedocs.io/en/latest/getting_started.html#advanced-data-manipulation-on-export) method.  This can modify data during export.

**Comment by israelabraham** [comment]
Hey, man! It works, I really appreciate it. Thank you.
