### ISSUE TITLE
Error - "Enter a valid date/time"

### ISSUE THREAD

**Issue by AlaiY95** [django-import-export/django-import-export#1420]
I'm using the import=export to upload a csv file, i've uploaded 2 of my other models great but now i'm uploading the csv below into a model that has a DateTimeField with the format %Y-%m-%d %H:%M:%S.

The csv uploads well into the django admin and I can see the date/time in the rows perfectly! But, each row in the preview in admin has a red error saying "enter a valid date/time". I've included ```format="%Y-%m-%d %H:%M:%S"``` into the settings.py file as suggested in the django docs. Any idea what's wrong?

**Demand in models.py:**
```
class Demand(models.Model):
    order_id = models.CharField(primary_key=True, max_length=100)
    customer_id = models.ForeignKey(Customer, null=True, on_delete= models.SET_NULL)
    placed = models.DateTimeField(null=True, blank=True)
```

**CSV File:**

```
order_id,customer_id,placed
O00001,C02842,2022/02/17 19:46:59
O00002,C01150,2022/08/26 11:27:14
```

**resources.py:**

```
from import_export import resources
from .models import *

class PropertyAdminResource(resources.ModelResource):
    class Meta:
        model = Demand
        import_id_fields = ('order_id',)
        fields = ('order_id', 'customer_id','placed',)
```

**admin.py file:**

```
class DataImportExportAdmin(ImportExportModelAdmin):
    resource_class = PropertyAdminResource
  
admin.site.register(Demand, DataImportExportAdmin)
```

**Comment by matthewhegarty** [comment]
> i'm uploading the csv below into a model that has a DateTimeField with the format %Y-%m-%d %H:%M:%S.

I notice that the date format in the upload file is '2022/02/17 19:46:59', hence the error because this does not match the defined format of '%Y-%m-%d %H:%M:%S'.

To fix, either correct the dates in your source file to be formatted as 2022-02-17 19:46:59', or you can configure `django-import-export` to handle the custom format in one of two ways:

1.  Define your field widget to use the correct format:

```python
placed = fields.Field(column_name="placed", attribute="placed", widget=widgets.DateTimeWidget(format="%Y/%m/%d %H:%M:%S"))
```

2. Extend `DATETIME_INPUT_FORMATS` ([ref](https://stackoverflow.com/a/27216175/39296))

**Comment by AlaiY95** [comment]
BOOM! worked perfectly! I just changed the custom format in excel then uploaded. Thanks

**Comment by TEJESWARARAOPAIDI** [comment]
import time
from dropbox.files import WriteMode
import struct
import minimalmodbus
import serial
import datetime
from datetime import date

def unpack_meter_data(x, y):
    a = struct.pack('HH', x, y)
    return struct.unpack('f', a)[0]

meters = [1]
instrument = []

# Initialization of meters
for x in range(len(meters)):
    # The specific meter
    instrument.append(minimalmodbus.Instrument('/dev/ttyUSB0', meters[x]))
    # Selecting the meter communication parameters
    instrument[x].serial.baudrate = 9600
    instrument[x].serial.bytesize = 8
    instrument[x].serial.parity = serial.PARITY_EVEN
    instrument[x].serial.stopbits = 1
    instrument[x].serial.timeout = 1
    instrument[x].mode = minimalmodbus.MODE_RTU

try:
    date_now = date.today()
    file_path = "/home/pi/CEMS/GN/"
    filename = f"GN_{date_now}.txt"
    file_path += filename

    with open(file_path, 'w') as file:
        for x in range(len(meters)):
            time_now = datetime.datetime.now()
            test_reg = instrument[x].read_registers(100, 118, 3)

            P_total = round(unpack_meter_data(int(test_reg[0]), int(test_reg[1])) / 1000, 3)
            P_restr = round(unpack_meter_data(int(test_reg[2]), int(test_reg[3])) / 1000, 3)
            P_y = round(unpack_meter_data(int(test_reg[4]), int(test_reg[5])) / 1000, 3)
            P_bostr = round(unpack_meter_data(int(test_reg[6]), int(test_reg[7])) / 1000, 3)

            # Write data to the file
            file.write(f"Meter {x + 1} - P_total: {P_total}, P_restr: {P_restr}, P_y: {P_y}, P_bostr: {P_bostr}\n")

            # Calculate time elapsed
            elapsed_time = datetime.datetime.now() - time_now
            print(f"Time taken to read meters: {elapsed_time}")

except Exception as e:
    print(f"An error occurred: {e}")

**Comment by edkohler** [comment]
This was helpful for a project I'm working on. For those who might still be stuck, I [wrote up a walk-through](https://medium.com/@edkohler/solving-datetime-import-headaches-with-django-import-export-widgets-e948e750e5c5) of how to resolve this issue with the DateTimeWidget here that provides a bit more detail into what to update in admin.py and resources.py.
