### ISSUE TITLE
All fields as import_id_fields

### ISSUE THREAD

**Issue by Yodale1000** [django-import-export/django-import-export#1422]
Hey,

is there an option to declare all fields as import_id_fields instead of defining them all one by one in a list ?

**Comment by matthewhegarty** [comment]
Yes, you can override `get_import_id_fields()`:

```python
class BookResource(resources.ModelResource):
    def get_import_id_fields(self):
        return self._meta.fields

    class Meta:
        model = Book
        fields = ('id', 'name')
```

**Comment by Yodale1000** [comment]
I get this error:
`import_id_fields = [
TypeError: 'NoneType' object is not iterable`

**Comment by Yodale1000** [comment]
Or maybe you i misspelled my question. I want all of the fields i declared above `class Meta:` to be used as import_id_fields.

**Comment by Yodale1000** [comment]
Apparently i miss understood the purpose or function of the `import_if_fields`.
