### ISSUE TITLE
[3.0] Beta3 breaks on import page

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#1432]
Beta 2 works ok. Updating to beta 3 produces error when loading import page:

`__init__()` got multiple values for argument 'data'

I cannot find the commit or tag for beta 2.

**Comment by manelclos** [comment]
The problem is in this commit: https://github.com/django-import-export/django-import-export/commit/cd0ab61955998ab27840d2ee2b6898d9d892a695

**Comment by matthewhegarty** [comment]
Can you reproduce in the example app?

**Comment by manelclos** [comment]
Hi Matthew, didn't try. I'm debugging the changes on the commit to see where the problem is. Will get to it if I fail to find original problem.
