### ISSUE TITLE
error during installation 

### ISSUE THREAD

**Issue by teshomem** [django-import-export/django-import-export#144]
python 3.4.1

pip install django-import-export

Downloading/unpacking django-import-export
  Downloading django-import-export-0.2.4.zip
  Running setup.py (path:/work/users/pip_build_root/django-import-export/setup.py) egg_info for package django-import-export

Downloading/unpacking tablib (from django-import-export)
  Downloading tablib-0.10.0-py2.py3-none-any.whl (864kB): 864kB downloaded
Downloading/unpacking diff-match-patch (from django-import-export)
  Downloading diff-match-patch-20121119.tar.gz (54kB): 54kB downloaded
  Running setup.py (path:/work/users/pip_build_root/diff-match-patch/setup.py) egg_info for package diff-match-patch

Installing collected packages: django-import-export, tablib, diff-match-patch
  Running setup.py install for django-import-export

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/markup.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/markup.py", line 186
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/odf/attrconverters.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/odf/attrconverters.py", line 51
    raise ValueError, "'%s' not allowed" % str(arg)
                    ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/odf/draw.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/odf/draw.py", line 33
    raise ValueError, "Style's family must be either 'graphic' or 'presentation'"
                    ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/odf/element.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/odf/element.py", line 119
    raise IllegalChild, "%s cannot be child of %s" % (newChild.tagName, self.tagName)
                      ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/odf/load.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/odf/load.py", line 77
    except AttributeError, v:
                         ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/odf/odfmanifest.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/odf/odfmanifest.py", line 114
    print "%-40s %-40s" % (file['media-type'], file['full-path'])
                      ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/odf/opendocument.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/odf/opendocument.py", line 37
    UNIXPERMS = 0100644 << 16L  # -rw-r--r--
                      ^
SyntaxError: invalid token

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/**init**.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/**init**.py", line 1187
    print "EXTERNSHEET(b7-):"
                            ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/compdoc.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/compdoc.py", line 61
    print "DID=%d name=%r etype=%d DIDs(left=%d right=%d root=%d parent=%d kids=%r) first_SID=%d tot_size=%d" \
                                                                                                            ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/formatting.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/formatting.py", line 168
    print "nearest_colour_index for %r is %r -> %r; best_metric is %d" \
                                                                     ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/formula.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/formula.py", line 410
    print "!!! get_externsheet_local_range: refx=%d, not in range(%d)" \
                                                                     ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/sheet.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/sheet.py", line 840
    print "GCW:", showgcw
               ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/timemachine.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/timemachine.py", line 28
    False = 0
       ^
SyntaxError: can't assign to keyword

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlrd/xldate.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlrd/xldate.py", line 116
    def xldate_from_date_tuple((year, month, day), datemode):
                               ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/BIFFRecords.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/BIFFRecords.py", line 193
    file_hist_flags = 0x00L
                          ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/CompoundDoc.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/CompoundDoc.py", line 25
    print 'NOTE: header says that must be', self.total_ssat_sectors, 'short sectors'
                                         ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/ExcelFormula.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/ExcelFormula.py", line 20
    except ANTLRException, e:
                         ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/ExcelFormulaLexer.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/ExcelFormulaLexer.py", line 126
    print t
          ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/ExcelFormulaParser.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/ExcelFormulaParser.py", line 525
    raise Exception, "%d parameters for function: %s" % (arg_count, func_tok.text)
                   ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/Style.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/Style.py", line 581
    if debug: print "+++ %s.%s = %r # %s; was %r" % (section, k, value, v, orig)
                                                ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/Workbook.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/Workbook.py", line 528
    0x00L, sheet.visibility, sheet.name, self.encoding
        ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/xlwt/antlr.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/xlwt/antlr.py", line 87
    print "error: ", fmt % tuple(args)
                  ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/yaml/constructor.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/yaml/constructor.py", line 135
    except TypeError, exc:
                    ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/yaml/reader.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/yaml/reader.py", line 193
    except UnicodeDecodeError, exc:
                             ^
SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/yaml/resolver.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/yaml/resolver.py", line 171
    re.compile(ur'''^(?:yes|Yes|YES|no|No|NO
                    |true|True|TRUE|false|False|FALSE
                    |on|On|ON|off|Off|OFF)$''', re.X),

```
                                         ^
```

SyntaxError: invalid syntax

**\* Error compiling '/work/users/pip_build_root/tablib/tablib/packages/yaml/scanner.py'...
  File "/work/users/pip_build_root/tablib/tablib/packages/yaml/scanner.py", line 1427
    except UnicodeDecodeError, exc:
                             ^
SyntaxError: invalid syntax

  Running setup.py install for diff-match-patch

Successfully installed django-import-export tablib diff-match-patch
Cleaning up...

**Comment by NicacioSilva** [comment]
pip install django-import-export

To me it takes about 1min to start installation processes but, in the end it worked fine. I've got a successfully installed!

So, be patient and it should work.
