### ISSUE TITLE
[3.0] Export Action should support multiple resources too

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#1440]
When using import-export 3.0, the export action in the changelist does not allow resource selection.

I think we should add the support to complete the multi resource feature.

https://github.com/django-import-export/django-import-export/blob/033f803c5994ceba9da8b610819ee5b52a630bf7/import_export/admin.py#L489

@matthewhegarty @PetrDlouhy what do you think?

**Comment by matthewhegarty** [comment]
Will take a look when I get chance
