### ISSUE TITLE
Import finished, with 0 new and 0 updated

### ISSUE THREAD

**Issue by senorpinatta** [django-import-export/django-import-export#1442]
**Bug Description**
Django-Import-Export had been working fine for months until a user reported that importing was not consistently working. Importing would report successful but no new records would actually be added/updated.

**Reproduction Steps**
1. Click Import
2. Select File to Import
3. (After successful validation checks) Click Confirm import
4. Import finishes reporting "Import finished, with 0 new and 0 updated" (no records are actually added or updated)

**Versions (please complete the following information):**
 - Django Import Export: Latest (2.8.0 I think)
 - Python [Latest]
 - Django [3.0.10]

**Expected Behavior**
"Import finished, with X new and Y updated"

**Screenshots**
<img width="203" alt="image" src="https://user-images.githubusercontent.com/8880195/170922236-c2bd5fb7-6483-46b1-acf7-83bd4cbc7642.png">

**Additional Context**
No problems found in local testing.

Strangely, testing revealed that import would complete successfully (Import finishing with the correct number of new/updated entries) about 12% of the time. The rest of the time, the import would fail as described above.

Therefore, I don't think this is necessarily a problem with Django-Import-Export, but perhaps with the staging environment that this error is occurring in.

Any suggestions as to what may be causing this will be greatly appreciated.

Edit 1:
Please feel free to change the label to question if that is more appropriate.

**Comment by matthewhegarty** [comment]
Are you using any containers or multi-server environment in staging?  (if so, read [this](https://github.com/django-import-export/django-import-export/blob/release-3-x/docs/getting_started.rst#import-confirmation) (from the release-3 branch)).

I agree it doesn't sound like a bug if it is not happening in staging.

**Comment by matthewhegarty** [comment]
Do you have any update on this please?  Was this the source of your problem?

**Comment by senorpinatta** [comment]
Hi,
Sorry for not getting back to you sooner. The multi-server environment point was spot on, and switching to [database backed storage](https://docs.djangoproject.com/en/dev/topics/cache/#database-caching) resolved the issue.

Thanks very much for the help.

**Comment by MohitSinha1** [comment]
Hi,
I don't want to cache other api endpoints, How to cache only django-import-export feature? 
Using database caching all the endpoints are cached which I don't want for now.

**Comment by matthewhegarty** [comment]
I think you will have to make some additions and add custom logic to perform the caching you want.  However I can't comment further without knowing the nature of your problem.  If you want to create a new issue, and include as much relevant information as possible, we may be able to help further.
