### ISSUE TITLE
how to ONLY export what I want?

### ISSUE THREAD

**Issue by monalisir** [django-import-export/django-import-export#1452]
Thanks for this app. 
I'm using it to export data from django admin.
But I face a problem, how to ONLY export the data after filtering.
Just like there are 30000 records in the DB table, after filtering, I get 200 records. How to ONLY export these 200 records?
I do not want to export them all. 

Thank you.

**Comment by pokken-magic** [comment]
Iirc export can accept a queryset.

**Comment by merwok** [comment]
Isn’t that what ExportActionModelAdmin (and subclasses) are for?  They let you use admin filters, date filters, search and manual check/uncheck of rows to select, then choose the export action from bulk actions menu and export the selection.

**Comment by Yodale1000** [comment]
> Isn’t that what ExportActionModelAdmin (and subclasses) are for? They let you use admin filters, date filters, search and manual check/uncheck of rows to select, then choose the export action from bulk actions menu and export the selection.

How do i implement it that way ?

**Comment by merwok** [comment]
See https://django-import-export.readthedocs.io/en/stable/getting_started.html#exporting-via-admin-action

**Comment by matthewhegarty** [comment]
#1477 related question
