### ISSUE TITLE
did any one tested it with django 4.06 python 3.10

### ISSUE THREAD

**Issue by engrimran7** [django-import-export/django-import-export#1457]
Hi all did any one tested it with django 4.06 python 3.10

actually i want to import and export to postgresql where my django app uses many to many fields and also the foreign keys i tried with django-import-export which prints ID only of foreign key and many to many but not the name. did anyone resolved this issue

**Comment by matthewhegarty** [comment]
Hi

Yes it gets tested on build using [tox](https://github.com/django-import-export/django-import-export/blob/main/tox.ini) with latest django version and on python 3.10.

Import of many to many fields is supported.  I suggest use the [3.0 beta](https://pypi.org/project/django-import-export/3.0.0b4/).  The [tests](https://github.com/django-import-export/django-import-export/blob/a11bbd4b425f5ca84eb091d8cde8990827cb4c56/tests/core/tests/test_resources.py#L907) and [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app) may help you solve your issue.

**Comment by engrimran7** [comment]
Thanx a lot for guiding this much after hours of struggle i came to know that we can retrieve the Name of FK instead of id by def.dehydrate
and then i fall into an issue that the fields i whitelisted to export are were not taken into account by django import export it was exporting the default fields data. i was trying to extract only few of the fields.
issue is by below code only the field which is dehydrated is getting exported all others are skipped/not exported
```
class MemberResource(resources.ModelResource):
    Brand=Field()
    class meta:
        model = model
        fields=('title','Brand')
    def dehydrate_Brand(self, obj):
        return str(obj.Brand.title)
```
```
class modelAdmin(ImportExportModelAdmin):
    resource_class = MemberResource
    list_display=['title','Model_code','Chipset','chipset_description','Brand','categories']
    search_fields = ['title','Model_code','Chipset',]
    fields=('title','Model_code','Chipset','chipset_description','image','Brand','Cat')
admin.site.register(model,modelAdmin)

```

any one here can point out the mistake

**Comment by engrimran7** [comment]
All above mentioned issues were resolved can close the question 

now i am facing issues with importing data to database which contains many to many and foreign keys

**Comment by pokken-magic** [comment]
Awesome, glad to hear it!
