### ISSUE TITLE
django importing error

### ISSUE THREAD

**Issue by naveedur** [django-import-export/django-import-export#1461]
I am using django-import-export. I am getting error in importing data to database with foreignkey value.
`class MemberResource(resources.ModelResource):

    class Meta:

        model = model

        fields=('id','title','Model_code','Chipset','chipset_description','image','Brand__title','Cat')`

Here **Brand** is use as foreignkey and I get title by using **Brand__title** . It work perfectly for exporting but when importing it through an error for foreignkey is null.
`Line number: 1 - null value in column "Brand_id" of relation "firmApp_model" violates not-null constraint DETAIL: Failing row contains (6, f16, sd, images/sample_3pahsfV.jfif, gf, kjkj, null).
None, f16, sd, images/sample_3pahsfV.jfif, gf, 1, kjkj, 1`

any solution please!

**Comment by matthewhegarty** [comment]
closing. answered [on SO](https://stackoverflow.com/questions/73018281/django-import-error-in-django-import-export)
