### ISSUE TITLE
Missing documentation: widgets and fields

### ISSUE THREAD

**Issue by vanschelven** [django-import-export/django-import-export#1464]
The architecture and usage of widgets and fields is not clear (to me) from the documentation. Questions in particular are:

* How do fields / widgets map to their counterparts in Django / Django Forms. What distinguishes them from those?
* What is the interface of `widget.clean()`? In particular: what type of Exception is expected to be raised by that method if something is does not validate (assuming that validation is part of the job for that method)
* How to configure the usage of a particular field/widget? (This might be deduced from examples throughout the docs, but I could not find a central location in the docs that describes how this can/should be done). See e.g. https://docs.djangoproject.com/en/4.0/topics/forms/#the-form-class for how Django itself does it.
* What is the division of responsibilities between Resource/Field/Widget?

**Comment by matthewhegarty** [comment]
Documentation is updated in v4
