### ISSUE TITLE
ValidationErrors are lumped together whereas ValueErrors are not

### ISSUE THREAD

**Issue by vanschelven** [django-import-export/django-import-export#1465]
**Describe the bug**

When a `ValidationError` is raised during the cleaning of a particular field, it ends up in the "non specific errors", even when it is specific to a field. This makes it harder to fix the problem, and unnecessarily so, because that information was available in the first place.

For ValueErrors a much more sophisticated flow exists, which keeps the error tied to the particular field.

**Versions (please complete the following information):**
 - Django Import Export: [2.8.0]

**Comment by matthewhegarty** [comment]
Closing as 'wontfix'.  I checked the interface for Fields and Widgets, and ValidationErrors are not thrown from Widgets or Fields.  I have clarified the documentation to record that ValueErrors should be raised from Widgets, and therefore they will be recorded as field-specific errors.
