### ISSUE TITLE
Horizontal scrolling broken when used with django-admin-interface

### ISSUE THREAD

**Issue by yatahaze** [django-import-export/django-import-export#1476]
I have an issue open over at [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface/issues/165) because I'm not sure which side to report this to.

When django-import-export is paired with django-admin-interface, the ability to scroll horizontally on the before/after preview screen doesn't work.

**Comment by matthewhegarty** [comment]
Can you retry with [v3](https://pypi.org/project/django-import-export/).  There were some fixes to help with integration with other packages.  That may help.

**Comment by matthewhegarty** [comment]
https://stackoverflow.com/questions/67432186/how-to-enable-horizontal-scrolling-in-django-admin-list-view

**Comment by yatahaze** [comment]
> https://stackoverflow.com/questions/67432186/how-to-enable-horizontal-scrolling-in-django-admin-list-view

we updated to 3.2 and our team is still reporting the same issue.

**Comment by matthewhegarty** [comment]
Closing - seems like this was fixed in [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface/issues/165#issuecomment-1271333642)
