### ISSUE TITLE
Alternative method for export data.

### ISSUE THREAD

**Issue by vb64** [django-import-export/django-import-export#1477]
Is [this way](https://medium.com/@vb64/exporting-user-filtered-data-from-a-django-admin-without-django-import-export-library-23d79009c183) (ChangeList class instead Admin Action) can be used for further library development?

**Comment by merwok** [comment]
I think you need to give more motivation!

Using an admin action is the django admin way.  I don’t think requiring a few clicks to be explicit about what you want to export is a big problem.
