### ISSUE TITLE
Admin Import broken if primary key is not "id"

### ISSUE THREAD

**Issue by joefessenden** [django-import-export/django-import-export#1480]
**Describe the bug**
If a OneToOneField (I have not fully tested with other foreign key types) uses the foreign key as the primary_key and names it something other than "id," import does not work. If I create a garbage field in the model and call it "id" the decorator works, but the mixin still does not work at all. I validated this by adding a simple model to the test application. 

**To Reproduce**
(Starting with test application)
1. Add model using a `OneToOneField` with `primary_key=True` (example below) named anything BUT 'id' (Do not include a field called 'id' in model).
2. Add import to admin.py (example of each approach below)
3. Run server
4. Go to admin > new model > import
5. Attempt import with csv content below.
6. See error (note errors differ slightly):

#### Error with Mixin Approach
```
Line number: 1 - 'reader'
11, Bob Smith
Traceback (most recent call last):
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 661, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 353, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 340, in get_instance
import_id_fields = [
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 341, in <listcomp>
self.fields[f] for f in self.get_import_id_fields()
KeyError: 'reader'
```
#### Error with Decorator Approach
```
Line number: 1 - 'id'
11, Bob Smith
Traceback (most recent call last):
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 661, in import_row instance, new = self.get_or_init_instance(instance_loader, row)
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 353, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 340, in get_instance
import_id_fields = [
File "c:\Users\...\test-django-import-export\temp-venv\lib\site-packages\import_export\resources.py", line 341, in <listcomp>
self.fields[f] for f in self.get_import_id_fields()
KeyError: 'id'
```

##### Workaround:
Note: I don't think this is a reasonable long-term solution, but, in case someone runs into this bug, it gets you moving again
  1. Add "id" field as blank IntegerField to model (just never expose it - the existence of the field with that name allows partial functionality).
  2. Add import to admin.py using decorator
Mixin approach is still broken

**Versions (please complete the following information):**
 - Django Import Export: 2.8.0 (tested with pre-release with similar results)
 - Python 3.10.4
 - Django 4.1

**Expected behavior**
Expect import to function fully when I set primary_key to be a field other than "id" and when I do not include a field with that name in my model.

##Code used for testing:

### models.py
```
class Reader(models.Model):
    reader = models.OneToOneField(Book, on_delete=models.CASCADE, primary_key=True,)
    reader_name = models.CharField('Reader Name',max_length=100,blank=True, null=True)
    #id = models.IntegerField(blank=True, null=True)
```

#### Decorator Approach
```
class ReaderImportExport(ImportExportModelAdmin):
    resource_class: ReaderResource

@admin.register(Reader)
class ReservationAdmin(ReaderImportExport):
    fields = ["reader","reader_name",]
```
#### Mixin Appproach
```
class ReaderAdmin(ImportExportMixin, admin.ModelAdmin):
    resource_class = ReaderResource

admin.site.register(Reader, ReaderAdmin)
```
### full contents of import csv for test
```
reader,reader_name
11, Bob Smith
```

**Comment by matthewhegarty** [comment]
Hi Joe - thanks for reporting this.  Is it possible you can create a branch containing the issue as described above?

**Comment by joefessenden** [comment]
Will do (or tell you if I am too dumb to figure it out).

**Comment by matthewhegarty** [comment]
Thanks - in case it was not obvious I meant to reproduce it in the django-import-export example application.

**Comment by joefessenden** [comment]
I got it (but clarification is fine - I'm still new. I MIGHT try to figure out a fix, but I reached the end of my understanding - meta classes are not something I've actually set up. I just use them when a package has them. )

**Comment by joefessenden** [comment]
@matthewhegarty I don't have permission to publish a branch (new at this - what do I need to do?)

**Comment by joefessenden** [comment]
https://github.com/joefessenden/django-import-export/tree/Admin-Import-broken-if-model-does-not-have-field-named-id-%231480

Is this what you need, or do I need to do something else?

**Comment by matthewhegarty** [comment]
Hi Joe - There is a typo in your `ReaderResource` declaration in your branch (missing comma).  I don't have permission to push, but you just need to add the comma [here](https://github.com/joefessenden/django-import-export/blob/d5886d333b9450be8601435998aff48cec311ee7/tests/core/admin.py#L67).  It looks like it works ok when using "mixin approach".  I was able to import your csv.  Can you try and see if it works for you?

I couldn't get "Decorator Approach" to work, but I have never come across that and it is possible django-import-export doesn't support that.  I will need to do some more testing to find out.

**Comment by joefessenden** [comment]
Matt - Thanks for that! It at least gets me moving again. 
I could swear I pulled the "Decorator Approach" (tell me if there's a better way to refer to it - just not sure) is straight from the docs on django-import-export - but now I can't find it, so maybe I've been imagining it.

**Comment by matthewhegarty** [comment]
I searched the docs for `register` and nothing there, so it's not something that's documented at present (and it doesn't look like it works anyway).

**Comment by joefessenden** [comment]
Matt - Finally found what I did wrong (now I'm embarrassed). I kept using `resource_class: ReservationResource` instead of `resource_class = ReservationResource` Now, that decorator approach works.

**Comment by matthewhegarty** [comment]
Glad you found the issue in the end.  Don't be embarrassed, we got there in the end, and it looks like you have uncovered a bug with the register decorator (I'll raise it separately).

**Comment by matthewhegarty** [comment]
I just tried register decorator with your updated syntax and it worked ok, so looks to be ok anyway.  If you're happy it's resolved feel free to close the issue.

**Comment by joefessenden** [comment]
Closing it, here. There was an issue in my code, so not broken.
