### ISSUE TITLE
Is it possible to set column_name based on value from request.user data in data export?

### ISSUE THREAD

**Issue by redwitchproject** [django-import-export/django-import-export#1489]
Is it possible to set `column_name` based on value from `request.user` data, for example, `request.user.company.name`?

```
class UserProfileResource(resources.ModelResource):
    custom_field = fields.Field(attribute="custom_field", column_name="...")
```

**Comment by matthewhegarty** [comment]
Yes you can do this if you dynamically create a Resource, for example:

```python
class YourResource(ModelResource):
    def __init__(self, company_name):
        super().__init__()
        self.fields["custom_field"] = fields.Field(
            attribute="custom_field", column_name=company_name, widget=widgets.CharWidget()
        )
```

The slightly tricky part is injecting the company name when instantiating the Resource.  Are you exporting via the Admin interface?

**Comment by redwitchproject** [comment]
_Are you exporting via the Admin interface?_

Thank you @matthewhegarty . I export in Celery task so there is not a problem.
