### ISSUE TITLE
``self.list_select_related`` could use``self.get_list_select_related`` in admin.ExportMixin

### ISSUE THREAD

**Issue by mpasternak** [django-import-export/django-import-export#1493]
Hey, 

``self.list_select_related`` could be``self.get_list_select_related(request)`` in admin.ExportMixin:

https://github.com/django-import-export/django-import-export/blob/main/import_export/admin.py#L371

That line. 

Django has a function for it now:

https://github.com/django/django/blob/main/django/contrib/admin/options.py#L1090

Perhaps it would be useful to use it, to play even more nicely withe rest of the ecosystem. 

I think I'm going to provide a PR for this some time later.

**Comment by matthewhegarty** [comment]
Thanks for raising - PR is welcome - check out the [contributing guidelines](https://github.com/django-import-export/django-import-export/blob/main/CONTRIBUTING.md)

**Comment by mpasternak** [comment]
Done! Thank you! https://github.com/django-import-export/django-import-export/pull/1511

**Comment by matthewhegarty** [comment]
merged - thanks
