### ISSUE TITLE
Export then Import ArrayField(INT)

### ISSUE THREAD

**Issue by zN3utr4l** [django-import-export/django-import-export#1495]
**Describe the bug**
I have this field which is an array of ints, when I export it transforms it into a string with separator character ',' but when I import that field becomes a list of strings even if the field needs a list of ints and goes into error.

`trigger_day = ArrayField(models.PositiveSmallIntegerField(choices=Days.choices), help_text='days at which the maintenance will be triggered', size=7)`

`"trigger_day": "1,4,5"`

![image](https://user-images.githubusercontent.com/73225008/194305101-9ec569e8-ad57-415b-95a6-a7bfbf2d44b8.png)

**How do I get it to be turned into int?**

**Versions (please complete the following information):**
 - Django Import Export: 2.9.0
 - Python 3.8.13
 - Django 3.2.15

**Comment by matthewhegarty** [comment]
I tested this as part of `release-4` and couldn't reproduce.  

I imported a file:

```
id,name,chapter_numbers
1,Some book2,"1,2,3,4"
```

This imported OK:

![image](https://github.com/django-import-export/django-import-export/assets/6249838/b3133015-808a-4f1a-9285-40e3d3b411fe)

I added the following to the test app to test:

```
# models.py

class BookWithChapterNumbers(models.Model):
    name = models.CharField("Book name", max_length=100)
    chapter_numbers = ArrayField(models.PositiveSmallIntegerField(), default=list)


# admin.py

class BookWithChapterNumbersResource(ModelResource):
    class Meta:
        model = BookWithChapterNumbers

class BookWithChapterNumbersAdmin(ImportExportModelAdmin):
    resource_classes = [BookWithChapterNumbersResource]

class BookWithChapterNumbersAdmin(ImportExportModelAdmin):
    pass

admin.site.register(BookWithChapterNumbers, BookWithChapterNumbersAdmin)
```
