### ISSUE TITLE
Import skips incremental ids in db

### ISSUE THREAD

**Issue by franhace** [django-import-export/django-import-export#1496]
**Describe the bug**
Inserted objects in database have a different id from what is shown in the preview.

**To Reproduce**
Import xlsx file.

**Versions:**
 - Django Import Export: 2.9.1
 - Python 3.8
 - Django 4.1
 - Mysql 5.7.38.

**Expected behavior**
I would except that objects get uploaded with the same id shown in the preview.

In the example shown below the expected id would be 647, but instead it gets inserted in the database as 648, skipping 647-

**Screenshots**
![image](https://user-images.githubusercontent.com/13649860/195721373-2f25d64f-35f4-49c8-bda7-23bea2c1f488.png)
![image](https://user-images.githubusercontent.com/13649860/195721445-28e2d303-16c6-4dd5-b943-dd184710dec7.png)

**Additional context**
I checked the version and the issue started with 2.6.0
In 2.5.0 you get duplicated inserted objects.

Probably related to https://github.com/shivanshs9/django-import-export/pull/1

**Comment by matthewhegarty** [comment]
Similar to #560 and #846

**Comment by matthewhegarty** [comment]
https://django-import-export.readthedocs.io/en/latest/faq.html#ids-incremented-twice-during-import
