### ISSUE TITLE
import nested json data

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1507]
### Discussed in https://github.com/django-import-export/django-import-export/discussions/1506

<div type='discussions-op-text'>

<sup>Originally posted by **biscotty666** October 24, 2022</sup>
Hi,
I need to import some data from json. The data contains nested objects and I’m unclear how to reference through to that data when writing the resource. I only see documentation about how to access fields at the “root” level of the data structure, not the nested levels. There is a bunch of info on exporting nested structures to json but I haven’t found anything on importing.
```
[{
    "somekeys": somevalues,
    "roster": [
      {
        "id": "P2021130273",
        "name": "Benja",
        "level": 85,
      },
      { more records },
    ]
}]
```
My goal is to map to the ids in the “roster” list. Where could I look for this information?

Thanks</div>

**Comment by matthewhegarty** [comment]
@biscotty666 One way you could maybe do it is to override `before_import()` and add a new column(s) to the dataset which flattens the data.  This modifies the dataset in places to add columns you can work with.

Here is an example using `BookResource` from the example application.  You can play around with this idea to see if it works for you.

```python
class BookResource(ModelResource):

    class Meta:
        model = Book

    def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        import tablib
        ids = [i["roster"][0]["id"] for i in dataset.dict]
        dataset.append_col(ids, header="id")
        print(dataset)
```

**Comment by biscotty666** [comment]
Thanks. I will try this out tonight.

**Comment by matthewhegarty** [comment]
You normally wouldn't make a dependency a separate app.  I guess if you apply a lot of customisations to it (i.e. creating your own resources, and overriding methods) then you might want it to be a separate app, but in most cases it would be overkill to create a separate app.

**Comment by matthewhegarty** [comment]
Closing - discussion continues in #445
