### ISSUE TITLE
ManyToMany relation with intermediate model breaks import

### ISSUE THREAD

**Issue by amarandon** [django-import-export/django-import-export#151]
Let's say I need to modify the example app to add a field on the relation table between a book and a category:

``` py
# models.py
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):                            
        return self.name


@python_2_unicode_compatible
class Book(models.Model):
    name = models.CharField('Book name', max_length=100)
    author = models.ForeignKey(Author, blank=True, null=True)
    author_email = models.EmailField('Author email', max_length=75, blank=True)
    imported = models.BooleanField(default=False)
    published = models.DateField('Published', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True,
                                blank=True)
    categories = models.ManyToManyField(Category, blank=True,
                                        through="IntermediateRelation")

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class IntermediateRelation(models.Model):
    relation_field = models.CharField(max_length=100)
    category = models.ForeignKey(Category)
    book = models.ForeignKey(Book)

    def __str__(self):
        return self.relation_field
```

Then I update `admin.py` so that I can assign a category to a book in the admin:

``` py
class IntermediateRelationInline(admin.TabularInline):
    model = IntermediateRelation
    extra = 1

class BookAdmin(ImportExportMixin, admin.ModelAdmin):
    list_filter = ['categories', 'author']
    inlines = (IntermediateRelationInline, )
```

I can export my books, but when I try to import them back, here is what I get:

``` pytb
Traceback:
File "/home/synext/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/synext/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/utils/decorators.py" in _wrapped_view
  105.                     response = view_func(request, *args, **kwargs)
File "/home/synext/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/views/decorators/cache.py" in _wrapped_view_func
  52.         response = view_func(request, *args, **kwargs)
File "/home/synext/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/contrib/admin/sites.py" in inner
  204.             return view(request, *args, **kwargs)
File "../import_export/admin.py" in process_import
  130.                                  raise_errors=True)
File "../import_export/resources.py" in import_data
  355.                     six.reraise(*sys.exc_info())
File "../import_export/resources.py" in import_data
  342.                         self.save_m2m(instance, row, real_dry_run)
File "../import_export/resources.py" in save_m2m
  216.                 self.import_field(field, obj, data)
File "../import_export/resources.py" in import_field
  195.             field.save(obj, data)
File "../import_export/fields.py" in save
  94.             setattr(obj, self.attribute, self.clean(data))
File "/home/synext/lib/python2.7/site-packages/Django-1.7-py2.7.egg/django/db/models/fields/related.py" in __set__
  1170.             raise AttributeError("Cannot set values on a ManyToManyField which specifies an intermediary model.  Use %s.%s's Manager instead." % (opts.app_label, opts.object_name))

Exception Type: AttributeError at /admin/core/book/process_import/
Exception Value: Cannot set values on a ManyToManyField which specifies an intermediary model.  Use core.IntermediateRelation's Manager instead.
```

**Comment by maltem-za** [comment]
@amarandon Thank you, that was extremely helpful.

Just a note on your **is_m2m_with_intermediate_object** and **get_intermediate_model** functions:
**_meta.get_field_by_name** has been [deprecated and will be removed soon](https://docs.djangoproject.com/en/1.8/ref/models/meta/#migrating-from-the-old-api).

You can use **_meta.get_field** instead. Eg:

`
def is_m2m_with_intermediate_object(self, obj):
    field = obj._meta.get_field(self.attribute)
    return field.many_to_many and not field.rel.through._meta.auto_created

def get_intermediate_model(self, obj):
    field = obj._meta.get_field(self.attribute)
    IntermediateModel = field.rel.through
    from_field_name = field.m2m_field_name()
    to_field_name = field.rel.to.__name__.lower()
    return IntermediateModel, from_field_name, to_field_name
`

**Comment by mc8ain1** [comment]
@amarandon and @maltem-za thank you very much!
I needed to extend it a bit, to get the correct field name of the ForeignKey in the IntermediateModel (if the field is not named == _lowercase model name_), I used this function:
```python
def get_fk_field_name(fk_field):
    for f in fk_field.rel.through._meta.fields:
        if f.related_model and f.related_model.__name__.lower() == fk_field.rel.to._meta.model_name.lower():
            return str(f.name)
```
here:
```python
def related_object_representation(self, obj, related_obj):
    ...
    related_field_name = get_fk_field_name(self)
    ...
```
and here:
```python
def def get_intermediate_model(self, obj):
    ...
    to_field_name = get_fk_field_name(field)
    ...
```

This works as long as you don't have multiple ForeignKeys to the same Model.

**Comment by alonappleboim** [comment]
I needed a simple text import-export for fields with intermediate models (which I refer to as association objects), perhaps this code can help someone (django 2.1.7). This solution can easily be improved...

To test I'm using a minimal site with a "library" app , and the following models:
`
# app/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=75, blank=True)

    def __str__(self): return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self): return self.name


class BookType(models.Model):
    name = models.CharField(max_length=16)
    date = models.DateField()

    def __str__(self):
        return '%s/%s' % (self.name, str(self.date))


class Book(models.Model):
    name = models.CharField('Book name', max_length=100)
    imported = models.BooleanField(default=False)
    published = models.DateField('Published', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    type = models.ForeignKey(BookType, on_delete=models.CASCADE)
    authors = models.ManyToManyField(Author, related_name='books')
    categories = models.ManyToManyField(Category, through='BookCategory', related_name='books')

    def __str__(self): return self.name


class BookCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='bcs')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='bcs')
    number = models.IntegerField()

    def __str__(self): return str(self.number)
`

In library/resources.py:
`
from import_export import resources, widgets, fields
from django.db.models.fields.related import ForeignKey


class AssocManyToManyWidget(widgets.ManyToManyWidget):
    """
            nomenclature throughout class:
                model - or "m", target model of this relationship
                assoc - or "a", model through which relationship is implemented
                src - or "s" the model this field belongs to
    """
    SEP_DICT = dict(inst=',', main=':', val='=', asn='|')

    def __init__(self, relation, sep=None, assoc_fields=None, model_fields=None, *args, **kwargs):
        """
        :param relation: the ManyToManyRelation
        :param sep: a dict of separators to render/parse the field

        example output string:
        model_field1=z1|model_field2=w1:assoc_field1=x1,model_field1=z2|model_field2=w2:assoc_field1=x2,...
        """
        super(AssocManyToManyWidget, self).__init__(*args, **kwargs)

        a_fields = assoc_fields or [f.name for f in relation.through._meta.fields
                                    if not f.auto_created and not isinstance(f, ForeignKey)]

        self.with_assoc = len(a_fields) > 0
        if not self.with_assoc: return # if there are no association objects, default to regular ManyToManyWidget
        if sep is None: sep = AssocManyToManyWidget.SEP_DICT
        self.sep = sep

        self.assoc = relation.through
        self.source = relation.related_model
        # collect all fields that will be exported
        self.m_fields = model_fields or ['pk']
        self.a_fields = a_fields

        # collect names of reference fields
        fk_field = lambda src, dst: next(f for f in src._meta.fields
                                         if isinstance(f, ForeignKey) and f.related_model == dst)
        a2s_field = fk_field(self.assoc, self.source)
        self.a2s, self.s2a = a2s_field.name, a2s_field.remote_field.name
        a2m_field = fk_field(self.assoc, self.model)
        self.a2m, self.m2a = a2m_field.name, a2m_field.remote_field.name

    def render(self, value, obj=None):
        f = self._render if self.with_assoc else super().render
        return f(value, obj)

    def clean(self, value, row=None, *args, **kwargs):
        f = self._clean if self.with_assoc else super().clean
        return f(value, row, *args, **kwargs)

    def format_fv(self, field, instance):
        return '%s%s%s' % (field, self.sep['val'], str(getattr(instance, field)))

    def _render(self, value, obj=None):
        s = []
        for assoc in getattr(obj, self.s2a).all():
            afields = self.sep['asn'].join(self.format_fv(f, assoc) for f in self.a_fields)
            model = getattr(assoc, self.a2m)
            mfields = self.sep['asn'].join(self.format_fv(f, model) for f in self.m_fields)
            s.append(self.sep['main'].join([mfields, afields]))
        return self.sep['inst'].join(s)

    def fieldvalues_dict(self, fvs):  # does not maintain order?
        return dict(fv.split(self.sep['val']) for fv in fvs.split(self.sep['asn']))

    def _clean(self, value, row=None, *args, **kwargs):
        assoc_attrs = []
        for instance_str in value.split(self.sep['inst']):
            mfields, attr = [self.fieldvalues_dict(x) for x in instance_str.split(self.sep['main'])]
            attr.update({self.a2m: self.model.objects.get(**mfields)})
            assoc_attrs.append(attr)
        return assoc_attrs


class FKWidget(widgets.ForeignKeyWidget):
    """
            nomenclature throughout class:
                model - or "m", target model of this relationship
                assoc - or "a", model through which relationship is implemented
                src - or "s" the model this field belongs to
    """
    SEP_DICT = dict(val='=', field=',')

    def __init__(self, sep=None, model_fields=None, *args, **kwargs):
        """
        :param relation: the ManyToManyRelation
        :param sep: a dict of separators to render/parse the field

        example output string:
        model_field1=z1|model_field2=w1:assoc_field1=x1,model_field1=z2|model_field2=w2:assoc_field1=x2,...
        """
        super(FKWidget, self).__init__(*args, **kwargs)
        if sep is None: sep = FKWidget.SEP_DICT
        self.sep = sep
        self.m_fields = model_fields or ['pk']

    def render(self, value, obj=None):
        return self.sep['field'].join([self.format_fv(x, value) for x in self.m_fields])

    def clean(self, value, row=None, *args, **kwargs):
        return self.model.objects.get(**self.fieldvalues_dict(value))

    def format_fv(self, field, instance):
        return '%s%s%s' % (field, self.sep['val'], str(getattr(instance, field)))

    def fieldvalues_dict(self, fvs):  # does not maintain order?
        return dict(fv.split(self.sep['val']) for fv in fvs.split(self.sep['field']))


class AssocField(fields.Field):

    def save(self, obj, data, is_m2m):
        """
        Cleans this field value and assign it to provided object.
        """
        if not self.readonly:
            if self.widget.with_assoc:
                self.widget.assoc.objects.filter(**{self.widget.a2s: obj}).delete()  # delete old associations of this object
                for assoc_dict in self.clean(data):
                    assoc_dict[self.widget.a2s] = obj
                    self.widget.assoc.objects.create(**assoc_dict)
            else:
                getattr(obj, self.attribute).set(self.clean(data))

    def export(self, obj):
        """
        Returns value from the provided object converted to export
        representation.
        """
        value = self.get_value(obj)
        return "" if value is None else self.widget.render(value, obj)


class ModelResource(resources.ModelResource):
    @classmethod
    def field_from_django_field(cls, field_name, django_field, readonly):
        """
        Returns a Resource Field instance for the given Django model field.

        In case of a m2m field return the AssocField with an AssocManyToManyWidget instead of regular defaults
        """
        if django_field.get_internal_type() in ('ManyToManyField',):
            Field = AssocField
            FieldWidget = AssocManyToManyWidget
            widget_kwargs = dict(model=django_field.remote_field.model,
                                 relation=django_field.remote_field)
        elif django_field.get_internal_type() in ('ForeignKey',):
            Field = fields.Field
            FieldWidget = FKWidget
            widget_kwargs = dict(model=django_field.remote_field.model)
        else:
            Field = cls.DEFAULT_RESOURCE_FIELD
            FieldWidget = cls.widget_from_django_field(django_field)
            widget_kwargs = cls.widget_kwargs_for_field(field_name)

        return Field(attribute=field_name,
                     column_name=field_name,
                     widget=FieldWidget(**widget_kwargs),
                     readonly=readonly,
                     default=django_field.default)


from .models import *


class BookResource(ModelResource):
    # authors = fields.Field(column_name='authors', attribute='authors',
    #                        widget=ManyToManyWidget(Author, field='name'))

    categories = AssocField(column_name='categories', attribute='categories',
                            widget=AssocManyToManyWidget(model=Category,
                                                         relation=Book._meta.get_field('categories').remote_field, #todo get this implicitly from related object
                                                         model_fields=['name']))

    type = fields.Field(column_name='type', attribute='type',
                            widget=FKWidget(model=BookType, model_fields=['name']))

    class Meta:
        model = Book
        fields = ('id', 'name', 'imported', 'published', 'type', 'price', 'authors', 'categories')
        # export_order = ('id','name','imported','published','price','type__name','authors', 'bcs')
`

and in admin.py
`
from django.contrib import admin
from import_export.admin import ImportExportModelAdmin
from .models import *

from .resources import BookResource
# Register your models here.


class CategoryInLine(admin.TabularInline):
    model = Book.categories.through
    list_display = ('number',)


class AuthorInLine(admin.TabularInline):
    model = Book.authors.through
    list_display = ('name', 'email')


@admin.register(BookType)
class BookAdmin(ImportExportModelAdmin):
    pass


@admin.register(Book)
class BookAdmin(ImportExportModelAdmin):
    resource_class = BookResource
    inlines = (CategoryInLine, )
    filter_horizontal = ('authors',)


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    pass


@admin.register(Author)
class AuthorAdmin(admin.ModelAdmin):
    pass
`
