### ISSUE TITLE
Cache django-import-export feature

### ISSUE THREAD

**Issue by MohitSinha1** [django-import-export/django-import-export#1512]
Question Description
I want to use per-view caching instead of per-site caching for django-import-export. How to implement per-view caching in it?

Additional Context
Django-Import-Export is working fine on staging environment (multiple server) after using Database caching(per-site) as recommended in [here](https://github.com/django-import-export/django-import-export/issues/1442).  Due to this per-site caching it is caching data for some other api endpoint which I don't want that's why I want to use per-view caching.

Code setup for django-import-export

```
class XyzResource(resources.ModelResource):
    
    class Meta:
        model = Xyz
    
   
    def __init__(self):


    def import_data(self, dataset, dry_run=False, raise_errors=False, use_transactions=None, collect_failed_rows=False, rollback_on_validation_errors=False, **kwargs):
    

    def skip_row(self, instance, original):

    def after_save_instance(self, instance, using_transactions, dry_run):

    def after_import(self, dataset, result, using_transactions, dry_run, **kwargs):


class XyzAdmin(ImportExportModelAdmin):
    resource_class = XyzResource
    tmp_storage_class = CacheStorage
```

Django Import Export: Latest (2.8.0 )
Python [Latest]
Django [3.0.10]

Any suggestions will be greatly appreciated.

**Comment by matthewhegarty** [comment]
I can't really help based on what you've posted.  This isn't something we've seen before AFAIK.  Upgrade to django-import-export 3.0.1 if you haven't already.

You could help further by posting

- More information on what is not working
- What have you tried?
- What is caching / what do you want to exclude
- Screenshots may help

The module which handles cache storage is [tmp_storages.py](https://github.com/django-import-export/django-import-export/blob/905839290016850327658bbee790314d4854f8a6/import_export/tmp_storages.py).  I feel you may have to parameterize or extend this module to get what you want (but you haven't provided much detail so hard to say).

If you have any further insights with this (or a working solution) please post back.
