### ISSUE TITLE
Template not found, skipped to avoid recursion issue

### ISSUE THREAD

**Issue by martinlehoux** [django-import-export/django-import-export#1514]
**Describe the bug**
My custom template for an admin list won't render du to a `Skipped to avoid recursion issue`

**To Reproduce**

```py
class MyAdmin(ImportExportMixin, models.Amin):
	change_list_template = "admin/my_app/folder/change_list.html"
```

I suppose recursion is: 
```
admin/my_app/folder/change_list
	admin/import_export/change_list_import_export
		admin/import_export/change_list
			admin/my_app/folder/change_list
```

**Versions (please complete the following information):**
 - Django Import Export: 3.0.1
 - Python: 3.11
 - Django: 4.1

**Expected behavior**
The list to render correctly as before

**Additional context**
It might be related to the recent update in `ImportExportMixin.__init__` (https://github.com/django-import-export/django-import-export/blob/905839290016850327658bbee790314d4854f8a6/import_export/admin.py#L36)

**Comment by mirzadelic** [comment]
Having the same issue, @martinlehoux any solution for this?

**Comment by martinlehoux** [comment]
@mirzadelic yeah, I moved my custom template to another name (not used by this repo) (not sure of the usefulness, but couldn't hurt), and made this change
```py
    -change_list_template = "admin/cms/static_search_page/change_list.html"
    +import_export_change_list_template = "admin/cms/change_static_search_page_list.html"
```

**Comment by mirzadelic** [comment]
@martinlehoux it works, thanks.

**Comment by matthewhegarty** [comment]
@nikhaldi I haven't looked in detail but this could be related to #1483.  I would appreciate if you could take a look if you have time 🙏
