### ISSUE TITLE
How to use ImportExportModelAdmin together with SortableAdminMixin from admin-sortable2

### ISSUE THREAD

**Issue by micudaj** [django-import-export/django-import-export#1531]
I tried to use ImportExportModelAdmin together with SortableAdminMixin from admin-sortable2, but I get the following error. Any idea how and if. these can work together?

```
join() argument must be str, bytes, or os.PathLike object, not 'list'
Request Method:	GET
Request URL:	http://xxxxx.de/admin/tenant_only/frage/
Django Version:	4.1.5
Exception Type:	TypeError
Exception Value:	
join() argument must be str, bytes, or os.PathLike object, not 'list'
Exception Location:	/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py, line 152, in _check_arg_types
Raised during:	adminsortable2.admin.changelist_view
```

Thanks you in advance!

**Comment by matthewhegarty** [comment]
At first glance it looks like an error in adminsortable2, but can you post the full stack trace (along with the versions you are using)

**Comment by matthewhegarty** [comment]
Did you solve this?  Can we close?

**Comment by micudaj** [comment]
sorry for not answering. In the stacktracke the error appears in a class of adminsortable2, so I opened an issue there. So I guess we can close here for now, unless you have an idea?

**Comment by matthewhegarty** [comment]
[Link}(https://github.com/jrief/django-admin-sortable2/issues/345)

Will close for now and will re-open if it looks like an import-export issue.

**Comment by PetrDlouhy** [comment]
I think this is `django-import-export` issue.
I was able to make the sorting work together with import/export buttons by following code:
```python
class MyAdmin(ImportExportMixin, SortableAdminMixin, admin.ModelAdmin):                                                                                                        
     change_list_template = "admin/import_export/change_list.html"
```

The substantial part is the `change_list_template` which I think should be set explicitly in `django-import-export` and shouldn't be needed in the users code.

For the reverse order of the mixins (`(SortableAdminMixin, ImportExportMixin, admin.ModelAdmin)`) which should in theory also work I think is at fault the `django-adminsortable2` which defines list as `change_list_template`.

**Comment by matthewhegarty** [comment]
We decided to [document these clashes](https://django-import-export.readthedocs.io/en/3.3.1/advanced_usage.html#interoperability-with-3rd-party-libraries) rather than try to fix:

**Comment by micudaj** [comment]
> I think this is `django-import-export` issue. I was able to make the sorting work together with import/export buttons by following code:
> 
> ```python
> class MyAdmin(ImportExportMixin, SortableAdminMixin, admin.ModelAdmin):                                                                                                        
>      change_list_template = "admin/import_export/change_list.html"
> ```
> 
> The substantial part is the `change_list_template` which I think should be set explicitly in `django-import-export` and shouldn't be needed in the users code.
> 
> For the reverse order of the mixins (`(SortableAdminMixin, ImportExportMixin, admin.ModelAdmin)`) which should in theory also work I think is at fault the `django-adminsortable2` which defines list as `change_list_template`.

I changed my code to this. I can now see the drag handler, but cannot use them as they don't work. Am I anything missing. Works when I only use the SortableAdminMixin.

**Comment by matthewhegarty** [comment]
You could try @PetrDlouhy [patch](https://github.com/django-import-export/django-import-export/pull/1607/files) and see if that works for you.  I decided not to merge into the main codebase, instead documented the workaround [here](https://github.com/django-import-export/django-import-export/blob/main/docs/advanced_usage.rst#interoperability-with-3rd-party-libraries).

**Comment by micudaj** [comment]
Unfortunately this also didn't work. Still drag & drop is not working in combination with import/export mixin

**Comment by matthewhegarty** [comment]
Sorry to say I can't help further.  It looks like various 3rd party libraries don't work well together.  If you get it working or find a workaround, please post back here.

**Comment by PetrDlouhy** [comment]
@matthewhegarty I think that ideal state of this issue is, that cooperation with `admin-sortable2` works out of the box without any workarounds (maybe even independently on order of the mixins).
Although it would be difficult to determine which library is at fault or if there are changes need to be implemented in Django itself to make sorting out template overriding easier with mixins.

I would like to contribute to solve this issue somehow.

@micudaj I have identified another issue which causes that `admin_sortable2_config` is not set and the drag&drop doesn't work. The cause is clash of variable of the same name in both libraries: #1633 
There is still needed to apply workaround after this change. The sorting drag&drop should work with following code:

```python
class MyAdmin(ImportExportMixin, SortableAdminMixin, admin.ModelAdmin):
    change_list_template = "adminsortable2/change_list.html"
```

**Comment by PetrDlouhy** [comment]
It also might be good to add `super` to the `change_list.html` template in case that some other library would override the `object-tools` block too:

```htmldjango
{% block object-tools %}
  <ul class="object-tools">
    {% block object-tools-items %}
      {% if has_add_permission %}
        {{ block.super }}
      {% endif %}
    {% endblock %}
  </ul>
  {{ block.super }}
{% endblock %}
```

**Comment by micudaj** [comment]
> @matthewhegarty I think that ideal state of this issue is, that cooperation with `admin-sortable2` works out of the box without any workarounds (maybe even independently on order of the mixins). Although it would be difficult to determine which library is at fault or if there are changes need to be implemented in Django itself to make sorting out template overriding easier with mixins.
> 
> I would like to contribute to solve this issue somehow.
> 
> @micudaj I have identified another issue which causes that `admin_sortable2_config` is not set and the drag&drop doesn't work. The cause is clash of variable of the same name in both libraries: #1633 There is still needed to apply workaround after this change. The sorting drag&drop should work with following code:
> 
> ```python
> class MyAdmin(ImportExportMixin, SortableAdminMixin, admin.ModelAdmin):
>     change_list_template = "adminsortable2/change_list.html"
> ```

Hey PetrDlouhy,

With your fixes drag & drop works. Thank you! But now I have the import export buttons in the top right twice. It is more of a cosmetic topic, but maybe this can easily be avoided.

**Comment by micudaj** [comment]
Never mind. Was an issue on my side with a change I tried before.
