### ISSUE TITLE
prefer-media-dark colors from django-import-export do not contrast well with the default theme.

### ISSUE THREAD

**Issue by Osc100** [django-import-export/django-import-export#1561]
**Describe the bug**
If you're using dark mode in your browser and then try to import data, the css prefer-media-dark from django-import-export triggers and overrides the light theme colors.

**To Reproduce**
1. Turn on dark mode in your browser.
2. Import a file in the admin site.

**Versions:**
 - Django Import Export: [3.1.0]
 - Python [3.11]
 - Django [4.1.7]
 - Jazzmin [2.6.0]
 - Firefox [110.0]

**Expected behavior**
To still use the light mode colors or bootstrap colors.

**Screenshots**
Dark Mode: 
![image](https://user-images.githubusercontent.com/60488755/224897149-0b1ddc4a-cd5d-47bb-856a-083039fcd8be.png)
Light Mode:
![image](https://user-images.githubusercontent.com/60488755/224897347-4c09c521-e221-443e-a790-412ef9b4de94.png)

**Comment by Osc100** [comment]
this was fixed by: https://github.com/django-import-export/django-import-export/pull/1370
sorry for opening the issue.

**Comment by houtadono** [comment]
-  use custom css JAZZMIN_SETTINGS in setting.py:

```
JAZZMIN_SETTINGS = {
    "custom_css": "css/custom_admin.css",
}
```

-  file css/custom_admin.css in folder static:

```
html {
    table.import-preview tr.new {
        background-color: white !important;
    }
    table.import-preview td ins {
        background-color: transparent !important;
        text-decoration: none  !important;
    }
} 
```
