### ISSUE TITLE
Request separate export_order and import_order Meta opts (or have export_order not affect import order)

### ISSUE THREAD

**Issue by halfmetaljacket** [django-import-export/django-import-export#1574]
I have run into a situation where I have some models with multiple FK fields, and in at least one case, resolving one custom FK field requires first resolving another FK field due to how I am using nested attributes. For this reason, I have to have the fields arranged in a certain order upon import else I get `NoneType does not have <attribute>`-type errors. This can easily be controlled for by defining the fields in a certain order in the Resource definition. However, I want the fields to be arranged in a different order that follows a more logical hierarchy (for the user and my application) when _exporting_. Unfortunately, setting `export_order` affects import order as well, meaning I can't have the order of export columns and the import processing order different.

Is it possible to either: remove `export_order` from affecting import processing, or alternatively adding a new Meta option e.g. `import_order` to separately control the two?

**Comment by matthewhegarty** [comment]
Hi, thanks for raising.

> Is it possible to either: remove export_order from affecting import processing, or alternatively adding a new Meta option e.g. import_order to separately control the two?

It seems reasonable.  I would probably opt for the latter.  We would consider a PR if you want to have a go, please refer to the [contribution guidelines](https://django-import-export.readthedocs.io/en/latest/contributing.html).

Otherwise we can take a look, but I cannot say when that would be, since we are a very small team with limited resources.

**Comment by matthewhegarty** [comment]
> Is it possible to either: remove export_order from affecting import processing

#1576 addresses this.  Since a breaking change, it will be released in v4.

**Comment by matthewhegarty** [comment]
> or alternatively adding a new Meta option e.g. import_order to separately control the two?

This will also be added in #1626

**Comment by matthewhegarty** [comment]
This was released in [4.0.0a3](https://pypi.org/project/django-import-export/4.0.0a3/)
