### ISSUE TITLE
Reference the model in the Resource meta via string

### ISSUE THREAD

**Issue by carlosdorneles-mb** [django-import-export/django-import-export#1581]
Guys, it is possible to reference the model in the Resource meta class via string without having to import the model specifically?

- How is today
```py
from core.books import Book

class BookResource(ModelResource):
    class Meta:
        model = Book
```

- How I wish
```py
class BookResource(ModelResource):
    class Meta:
        model = "books.Book"
```

I know that the way I said it doesn't work, but I wanted to know if there is any other way. This is useful to prevent imports from looping.

**Comment by carlosdorneles-mb** [comment]
As an alternative, I made a copy paste of the `import_from_str` function that exists in the package [model_bakery](https://github.com/model-bakers/model_bakery/blob/75735ff68341e2a030d1381b25907e3a4377a76f/model_bakery/utils.py#L16) and it is working as follows form:

```python
from core.utils import import_from_str

class BookResource(ModelResource):
    class Meta:
        model = import_from_str("books.Book")
```

It would be interesting if this already exists as a default in the project.

**Comment by matthewhegarty** [comment]
Hi Carlos - thanks for the update.  I'll leave this open as a potential enhancement though it might be a while before we look at it (we are a small team).  If you wanted to submit a PR to support this, you would be very welcome to do so.

**Comment by EricOuma** [comment]
@matthewhegarty Assign me this

**Comment by matthewhegarty** [comment]
Thanks @EricOuma - please can you take a branch from `release-4`

**Comment by carlosdorneles-mb** [comment]
@EricOuma, Django has a function that does this, in this case you could even use it...

```
from django.apps import apps

User = apps.get_model('auth', 'User')
User = apps.get_model('auth.User')
```
