### ISSUE TITLE
read filters from admin

### ISSUE THREAD

**Issue by hamidrabedi** [django-import-export/django-import-export#1582]
make it that reads filters from `list_filter` in admin, and be able to customize it and override it.

**Comment by matthewhegarty** [comment]
Hi, thanks for submitting this but there's not enough information here for us to be able to proceed.  Could you add more detail as to what you are looking for, or even better [submit a PR](https://github.com/django-import-export/django-import-export/blob/main/docs/contributing.rst) for review?

**Comment by hamidrabedi** [comment]
hello there, thanks for responding, I could not come up with a working answer but this is the overall idea:

```
class ImportExportModelAdminWithAdminFilters(ImportExportModelAdmin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for filter in self.list_filter:
        #     qs = self.my_queryset(filter)
        #     self.export_form_class.base_fields.update({
        #         filter: forms.ModelChoiceField(queryset=qs)
        #     })
    def get_paginator(
        self, request, queryset, per_page, orphans=0, allow_empty_first_page=True
    ):
        for filter in self.list_filter:
            qs = self.my_queryset(filter, request)
            self.export_form_class.base_fields.update({
                filter: forms.ModelChoiceField(queryset=qs)
            })
        return super().get_paginator(request, queryset, per_page, orphans=0, allow_empty_first_page=True)

    def my_queryset(self, filter_name, request):
        if filter_name in self.list_filter:
            filter_parts = filter_name.split('__')
            field_name = filter_parts.pop()
            queryset = self.get_queryset(request)
            for part in filter_parts:
                field = queryset.model._meta.get_field(part)
                queryset = queryset.filter(**{part: field.rel.to.objects.all()})
            queryset = queryset.values_list(field_name, flat=True).distinct()
            queryset = self.get_field_queryset(field_name, queryset, request)
            return queryset
        return None


@admin.register(Company)
class CompanyAdmin(ImportExportModelAdminWithAdminFilters):
    resource_class = CompanyResource
    list_filter = (
        "field_of_activity",
        "booth_type",
    )
```

I need to update the export form in the __init__ but i could not access the request there and not sure how to do it. i just copied this to show what is the general idea of getting the fields dynamically from admin `list_filter`. the correct option that you are offering is to override the `export_form_class` which is ok, but this one is what I needed in one of my projects.
Thanks.

**Comment by matthewhegarty** [comment]
I still do not understand what the issue is.  Can you explain the issue more clearly?  Can you give us steps to reproduce?  The code block doesn't help me understand the problem.
