### ISSUE TITLE
Issue submitted by mistake

### ISSUE THREAD

**Issue by yassinsameh** [django-import-export/django-import-export#1590]
**Describe the bug**

**To Reproduce**

**Versions (please complete the following information):**
 - Django Import Export: [e.g. 1.2, 2.0]
 - Python [e.g. 3.6, 3.7]
 - Django [e.g. 1.2, 2.0]

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by matthewhegarty** [comment]
Do you have any more information?

**Comment by yassinsameh** [comment]
Apologies @matthewhegarty , was a question and just published it, somehow submitted this issue by mistake, sorry about that.
