### ISSUE TITLE
ValueError when making an xls export of more than 65535 records

### ISSUE THREAD

**Issue by EricOuma** [django-import-export/django-import-export#1592]
**Describe the bug**
A ValueError when making an xls export of more than 65535 records.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select more than 65535 records
2. Export to xls format

**Versions:**
 - Django Import Export: 3.0.2
 - Python 3.10
 - Django 3.2.3

**Expected behavior**
Given that the xls format is limited to [65535 rows](https://stackoverflow.com/a/45741831/9564152), I export a warning that the data I am trying to export to xls format is more than the supported rows.

**Additional context**
Here is the stack trace.
```
TypeError: argument of type 'int' is not iterable
  File "tablib/formats/_xls.py", line 144, in dset_sheet
    if '\n' in col:
ValueError: row index was 65536, not allowed by .xls format
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "import_export/admin.py", line 707, in export_action
    export_data = self.get_export_data(
  File "import_export/admin.py", line 656, in get_export_data
    export_data = file_format.export_data(data)
  File "import_export/formats/base_formats.py", line 86, in export_data
    return dataset.export(self.get_title(), **kwargs)
  File "tablib/core.py", line 427, in export
    return fmt.export_set(self, **kwargs)
  File "tablib/formats/_xls.py", line 47, in export_set
    cls.dset_sheet(dataset, ws)
  File "tablib/formats/_xls.py", line 149, in dset_sheet
    ws.write(i, j, col)
  File "xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "xlwt/Worksheet.py", line 1142, in row
    self.__rows[indx] = self.Row(indx, self)
  File "xlwt/Row.py", line 37, in __init__
    raise ValueError("row index was %r, not allowed by .xls format" % rowx)
```

I can make a PR for this but I need some guidance on where it would be best suited to show an error to the user. I will need access to the `file_format` and `queryset` so `ExportViewFormMixin` or `ExportViewMixin` seem like suitable locations for displaying the error

**Comment by matthewhegarty** [comment]
This is a limitation of the library used to export to xls (which is [now unsupported](https://groups.google.com/g/python-excel/c/P6TjJgFVjMI/m/g8d0eWxTBQAJ?pli=1)).  You could try exporting to xlsx which uses openpyxl and supports more rows.

If you are exporting via the Admin interface, there are ways you can [format the exception](https://django-import-export.readthedocs.io/en/latest/faq.html#how-to-hide-stack-trace-in-ui-error-messages) to appear clearer.

**Comment by EricOuma** [comment]
@matthewhegarty Thanks for the response. I understand the limitation. 
'You could try exporting to xlsx', I know this and that's why my main interest is to provide a message to the users informing them to use an alternative export format and why. 

I am seeking advice on where it would be best suited to insert the sample code below:

```
if queryset.count() >= XLS_LIMIT and format == 'xls':
    messages.add(request, messages.ERROR, 'XLS is limited to ... rows. Please use another format')
```

**Comment by matthewhegarty** [comment]
Hi Eric - thanks for the suggestion, but personally I don't approve of adding this check to the main code base.  My view is that it will add bloat the code, and the call to `count()` may have performance implications.

I agree that it is better usability if users were warned about this issue.  In fact a warning about the use of xls in general might be useful.

Can you find a way to display this message without changing the core library?  Can you add [exception formatting](https://github.com/django-import-export/django-import-export/issues/1592#issuecomment-1579155643) or find another hook for customisation. 

If there was a generic way of displaying warnings to the users we might be interested in that, i.e. a hook that lets implementations override behaviour to display a custom message.  What might be ideal is that a warning is shown as soon as the user selects 'xls' from the drop down - i.e. 'use of xls is now deprecated' or similar.  But there should be a way for the user to customise the message text and it should handle internationalization.  I expect you'd have to generate this message when the page is loaded and then place it in a hidden div, to be shown when 'xls' is selected.  The display of warnings should fit in with any existing protocol within Django Admin.

**Comment by EricOuma** [comment]
Hi @matthewhegarty 

Thanks for the update. Am thinking given user-known issues mapped to their formats defined in the settings. e.g

IMPORT_EXPORT_WARNINGS = {
base_formats.XLS: ['XLS export is limited to 65535']
}

I can handle internalization in the template or Python code. I think this would be a generic way as the user can update this map easily. 
On page load, I create hidden divs for each of the formats the user has provided warnings for and id them like this 'xls_warnings'. These can then be displayed with jquery

$('select').on('change', function() {
  $(`${this.value}_warnings`).show();
  //Make sure the unselected remain hidden
});

'The display of warnings should fit in with any existing protocol within Django Admin' Not sure I understand this fully. To use the messages framework I would need to show the warning(s) after the user has submitted which nullifies the objective.

**Comment by matthewhegarty** [comment]
I think this sounds ok.  Personally I wouldn't make it 'generic', and would instead only display the 'xls' is a deprecated format message.  It's not clear to me how you would manage the internationalization.

> 'The display of warnings should fit in with any existing protocol within Django Admin'

My only point here was that it should fit in with any existing best practice for messages, but if this is not possible then no problem.

**Comment by ciskeboekelo** [comment]
Hi, I would also like to see this formats option come to life. @matthewhegarty @EricOuma let me know if I can help with anything.

**Comment by EricOuma** [comment]
Fixed here https://github.com/django-import-export/django-import-export/pull/1606
