### ISSUE TITLE
Export URL field as clickable URL to XLS file

### ISSUE THREAD

**Issue by ddoyaguez** [django-import-export/django-import-export#1593]
Hello.

I am trying to export a model that has an URLField. The problem is that it doesn't appear as a clickable URL (it appears as a normal string, so the user of the resulting Excel has to copy and paste the whole URL to open it instead of being able to open it with one click).

Could you please give me some advice on how to implement this on a widget level? I will try to implement it in my project and will open a PR with the solution if it works.

Thank you very much.

**Comment by matthewhegarty** [comment]
I would suggest check the docs for the upstream dependencies [tablib](https://github.com/jazzband/tablib) and [openpyxl](https://openpyxl.readthedocs.io/en/stable/) (assuming you are exporting to xlsx).  There might be a way of preserving links by passing an option.

**Comment by ddoyaguez** [comment]
Thank you very much.

Tablib was the way to go. It didn't have many docs, but I have checked the code and traced it all down to xlwt library, the library that gives tablib xls support.

So xlwt library has support for hyperlinks as stated in this example: https://github.com/python-excel/xlwt/blob/master/examples/hyperlinks.py

Tablib does not, BUT :), in xlwt docs, in Worksheet.py, write function, it says:
`An :class:`xlwt.Formula` instance causes an Excel formula to be written.`

So I think that if I manage to pass it a xlwt.Formula object as stated in the example, it will do the trick. The only thing is that I have to pass it from above (django-import-export) all the way through tablib.

The idea I have is to create an URLWidget or HyperlinkWidget (what do you think that sounds better?) that inherits from NumberWidget and in its clean() method it performs the transformation shown in the example, that is surrounding the hyperlink text with parenthesis and appending 'HYPERLINK' to it. With that, creating a xlwt.Formula object, and returning it so hopefully it gets to the xlwt write method as it is.

I will try this tomorrow and let you know what happens!

**Comment by ddoyaguez** [comment]
I tested this and it works, but there is a catch.
It only works when the selected export option is set to xls. Is there any way to know from a Widget what is the output file format, so I can change the data return by the clean method?

**Comment by matthewhegarty** [comment]
I suggest that you wouldn't want to pass file format into widget, because widgets shouldn't need to know about file format.  Instead, you could look at the `base_formats.py` module which is where format specific logic can go.  I don't have time to look into this at present, but you could look into how the recent [formula escaping logic](https://github.com/django-import-export/django-import-export/pull/1568) was added to maybe give some ideas.  That PR has the notion of a flag being passed to control how the format appears in export.

**Comment by ddoyaguez** [comment]
I understand, thank you very much for the idea. I have thought of two methods based on what I have seen in base_formats.py:
1. To create a class that inherits from the XLS class from `base_formats.py` in my app and to modify the DEFAULT_FORMATS list in my admin.py so that is the subclass the one that makes the transform if the text starts with http:// or https://. I don't think that the import_export library could benefit from implementing this mechanism for such a corner case.
2. This is very funny and if it works the one that I think I will stick with: In my app I create a class that inherits from xlwt.Formula and override its __str__ method so it returns the original string. The only thing that I should check is what happens when it is saved as xlsx. If it breaks, I will modify DEFAULT_FORMATS again to make xlsx unavailable and problem solved (if users don't ask for xlsx :rofl:  ).
