### ISSUE TITLE
On version > 2.9.0 got Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable

### ISSUE THREAD

**Issue by belonesox** [django-import-export/django-import-export#1595]
Since version > 2.9.0 got on my admin site error «Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable»
See attached complete django debug info.

[import-export-django-report.zip](https://github.com/django-import-export/django-import-export/files/11707430/import-export-django-report.zip)

**Comment by matthewhegarty** [comment]
Thanks for raising.  It's going to be very difficult to get to the cause of this without more information.

- Have you got any other packages which might conflict?
- Have you made any template customisations yourself which may be causing the issue?
- Can you provide a reproducible instance (maybe in the example application)
- There is a similar thread [here](https://github.com/kmmbvnr/django-material/issues/244) - does this provide any clues?
- Similar [SO post](https://stackoverflow.com/questions/46641057/extending-templates-from-project-root-django)

Probably there are other resources out there for this error - do any of those help?

**Comment by belonesox** [comment]
> Can you provide a reproducible instance (maybe in the example application)
Not easy, will try to solve it without generating VMs, etc.

> Have you got any other packages which might conflict?
It is Django, anything possible.

In all packages from my 
[requirements.txt](https://github.com/django-import-export/django-import-export/files/11708466/requirements.txt)
I cannot find «base_change_list_template» (I locked on «Django==3.2.5»). 

There it should be in your setup?

**Comment by matthewhegarty** [comment]
I would suggest:

1.  Identify which of your dependencies have Admin integration
2. Start with a clean installation which renders ok and then add those dependencies one-by-one until you reproduce the issue.

[This](https://www.imdb.com/news/ni63912908/) is the only other issue we've had so far with templates in recent releases.
