### ISSUE TITLE
how to use  choices for the field.widgets

### ISSUE THREAD

**Issue by doneite** [django-import-export/django-import-export#1596]
when import xls file, the choices field is None,but xls exist data and the import preview page in the Admin UI exist data.

**Comment by matthewhegarty** [comment]
hi I can't understand what the issue is here.  Can you repost with as much information as possible (how to reproduce, screenshots if necessary).

**Comment by doneite** [comment]
thanks,
**in models.py:**
education = models.CharField(_("文化程度"), max_length=20, choices=Education.choices)
class Education(TextChoices):
    A = '1', '小学'
    B = '2', '初级中学'
    C = '3', '普通高中'
    D = '4', '技工学校'
    E = '5', '大学专科'
    F = '6', '大学本科'
    G = '7', '硕士研究生'
    H = '8', '博士'
    I = '99', '不限'
**in resources.py:**
education = Field(column_name='文化程度', attribute='get_education_display')
Export is working.
when Import this field. the value in database is None;
1、A screenshot of the excel  file:
<img width="145" alt="error" src="https://github.com/django-import-export/django-import-export/assets/51977397/a37f0d1f-8986-4dce-b6a6-510516101127">

2、A screenshot of the confirm import view.:
<img width="825" alt="err1" src="https://github.com/django-import-export/django-import-export/assets/51977397/d78a3a2c-03b6-4549-8618-b3cdcffced19">

3、A screenshot in database:
<img width="348" alt="error2" src="https://github.com/django-import-export/django-import-export/assets/51977397/74748673-dc5c-40dc-80b5-f4c98ae610e4">

**Comment by matthewhegarty** [comment]
Sorry - I cannot understand the issue - can you reproduce in the example application?
