### ISSUE TITLE
Exporting to XLS gives: Unexpected data type <class 'django.utils.functional.lazy.<locals>.__proxy__'>

### ISSUE THREAD

**Issue by ciskeboekelo** [django-import-export/django-import-export#1601]
**Describe the bug**
When I export to XLS I get this error: Unexpected data type <class 'django.utils.functional.lazy.<locals>.__proxy__'>
I don't get this error when choosing the XSLX file type.

**To Reproduce**
1. Go to Export
2. Select xls
3. Hit the submit button

**Versions (please complete the following information):**
 - Django Import Export: 3.2.0
 - Python 3.8.10
 - Django 4.2.3

Note that this has been an issue for us many several years.

**Expected behavior**
No error.

Let me know if you need more information on the models.

**Comment by matthewhegarty** [comment]
Hi
Thanks for raising this.  There's not much we can do with the information you have supplied.  If you could provide a reproducible issue in the example application, or a stack trace, or steps to reproduce, we could maybe look into it.

It sounds like this is an xls issue.  XLS support is taken from tablib, which in turn takes its support from xlrd / xlwt, both of which are now unsupported, so I don't think it is likely you will get a resolution to this issue, and you should try to move to using xlsx.

**Comment by ciskeboekelo** [comment]
Thanks for your quick response.

In that case, can we have a setting to hide the XLS option? I'm fine with
having only XLSX.

Our users keep using the XLS format on occasion, so it's confusing to have
it there when it doesn't work.

Perhaps an EXPORT_FORMATS  setting would be best, where we could specify
which format we'd like to have available for export (or a SUPPORTED_FORMATS
setting if we're including imports for the setting).

And if I can dream: If we choose to set EXPORT_FORMATS to one format only:
['xslx'], then we could have the export button immediately export without
having to go to the intermediary page where you select the file format.

Thanks for listening

Op wo 19 jul 2023 om 11:18 schreef Matt Hegarty ***@***.***>:

**Comment by matthewhegarty** [comment]
Thanks for the suggestions, we had a similar request [here](https://github.com/django-import-export/django-import-export/issues/1592#issuecomment-1602731853).

**Comment by matthewhegarty** [comment]
Thanks to Eric's [PR](#1606) you can now specify export formats in settings
