### ISSUE TITLE
Error in application configuration

### ISSUE THREAD

**Issue by danilodcn** [django-import-export/django-import-export#1613]
**Describe the bug**
after update package I got the error

**To Reproduce**
1. Configure a django application with django import export and django import export celery
2. call `python manage.py check` in terminal 

**Versions:**
 - Django Import Export: [2.9.0]
 - Python [3.10.9]
 - Django [4.2.5]

**Screenshots**
![image](https://github.com/django-import-export/django-import-export/assets/31135098/934a6056-b20a-49fd-bd0d-7d265a00c391)

**Comment by matthewhegarty** [comment]
This error is coming from a [different library](https://github.com/auto-mat/django-import-export-celery/commit/e7bc39c03f524b12f965163f87eb9226b3c1939e) 'django-import-export-celery'.  Please raise this issue there.
