### ISSUE TITLE
Can I import a csv file containt the list of `pk` and then export with new csv contain list of emails ?

### ISSUE THREAD

**Issue by kev26** [django-import-export/django-import-export#1619]
I want to import a CSV file containing a list of primary keys (pk). I will then retrieve member emails based on those primary keys and export them to a new CSV file. However, I have a problem. Currently, in my admin dashboard, I have implemented a feature using ExportMixin to export all member fields. Now, I want to implement another feature that imports member primary keys and exports member emails. How can I achieve this while ensuring that both features continue to work together in the same MemberAdmin table? Thank you so much.

**Comment by matthewhegarty** [comment]
> Now, I want to implement another feature that imports member primary keys and exports member emails. 

It sounds like you want to export using two different configurations.  To do this, you can define two resources, and then choose the one you want on the export screen.  You can see this in the example app:

![image](https://github.com/django-import-export/django-import-export/assets/6249838/75795a0d-f818-41f9-9931-ab22e32ec6c8)

There's more information in the [docs](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#using-multiple-resources).

**Comment by kev26** [comment]
Thank you so much, but with the way import csv file with list ID and I will do some ORM to get emails and export to new csv ? Can we do it by django-import-export ? Thank you :D

**Comment by matthewhegarty** [comment]
Yes it should be possible.
