### ISSUE TITLE
Refactor large test modules

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1636]
Some test modules (e.g. `test_admin_integration.py`) have become large and are hard to edit.
They should be broken up into smaller modules.

v3.3.1

**Comment by bvedang** [comment]
Is this issue currently worked on, I see some commits related to this in branch **release - 4** and i see we can also refactor test_resources.py file.

**Comment by matthewhegarty** [comment]
Hi - so `test_admin_integration.py` has been refactored.  `test_resources.py` needs to be done.

@PrashansaChaudhary - are you working on `test_resources.py` or can Vedang take it on?

**Comment by PrashansaChaudhary** [comment]
Hi @matthewhegarty, currently I am not working on test_resources.py, I will work on another issue if @bvedang is working on  test_resources.py .

**Comment by matthewhegarty** [comment]
Thanks @PrashansaChaudhary.  @bvedang feel free to pick up refactoring `test_resources`, please refer to [contributor guide](https://github.com/django-import-export/django-import-export/blob/main/docs/contributing.rst#development) if you are new to the project.
