### ISSUE TITLE
Is there any conflict between skip_diff and skip_unchanged?

### ISSUE THREAD

**Issue by dralley** [django-import-export/django-import-export#1653]
skip_unchanged requires a comparison between the imported and persisted rows, skip_diff purports to skip that comparison.  Does that yield any conflict, or are they perfectly OK to use together?

If so, perhaps it makes sense to adjust the documentation to make this more clear.

Separately, skip_unchanged isn't called out anywhere as a potential performance optimization, but it seems like it would be one, if indeed it skips saving objects which it will not have not changed?

**Comment by matthewhegarty** [comment]
Thanks for raising.  I have updated the documentation in #1655 to make this clearer.

**Comment by dralley** [comment]
Thanks!
