### ISSUE TITLE
Django compress causes issues

### ISSUE THREAD

**Issue by RumitAP** [django-import-export/django-import-export#1659]
**Describe the bug**
When I try to compress my project down, the static files within the django-import-export causes errors from the templates.

**To Reproduce**
1. Go to the root of external project in terminal
2. python manage.py collectstatic
3. python manage.py compress --force

```
Compressing... Error parsing template /home/rap/.local/lib/python3.8/site-packages/import_export/templates/admin/import_export/change_list_import.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template /home/rap/.local/lib/python3.8/site-packages/import_export/templates/admin/import_export/change_list_import_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template /home/rap/.local/lib/python3.8/site-packages/import_export/templates/admin/import_export/change_list_export.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
Error parsing template /home/rap/.local/lib/python3.8/site-packages/import_export/templates/admin/import_export/change_list.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_change_list_template' variable.
```

**Versions (please complete the following information):**
 - Django Import Export: 3.2.0 but tried with latest stable release
 - Python: 3.8, 3.9
 - Django: 3.2.15

**Expected behavior**
It should be able to compress these files down.

**Comment by matthewhegarty** [comment]
Please can you test this with the release-4 branch and let us know if it fixes the issue?

See also #1605

**Comment by matthewhegarty** [comment]
Closing due to lack of detail.
