### ISSUE TITLE
Declaring a Resource Field changes the export order

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1663]
**Describe the bug**

If declaring a Field in a Resource, this causes the export order to change:

Without declaration:

![Screenshot 2023-10-22 at 19 10 35](https://github.com/django-import-export/django-import-export/assets/6249838/d6331ec4-0b52-445c-821b-e4a5580eb9b5)

With declaration:

![Screenshot 2023-10-22 at 19 10 17](https://github.com/django-import-export/django-import-export/assets/6249838/1cc53441-8216-4fa5-847a-42a3b361aa03)

**To Reproduce**

Declare a Field in Resource:

```
class BookResource(ModelResource):
    published = Field(attribute='published', column_name='published_date',
        widget=DateWidget(format='%d.%m.%Y'))

    class Meta:
        model = Book
```

Export the book.

Note this doesn't occur (i.e. order is preserved) if you use the widgets dict:

```
class BookResource(resources.ModelResource):

    class Meta:
        model = Book
        widgets = {
            'published': {'format': '%d.%m.%Y'},
        }
```

**Versions (please complete the following information):**
 - Django Import Export: 3.3.1
 - Python 3.11
 - Django 4.2

**Expected behavior**

Declaring Field should not affect the export order.

**Comment by cocorocho** [comment]
Hello,

I looked into the issue and it seems to be caused by `DeclarativeMetaclass`. Since `ModelDeclarativeMetaclass`  inherits `DeclarativeMetaclass` and declared fields are defined first by the parent model, `ModelDeclarativeMetaclass` appends model fields into the fields defined by `DeclarativeMetaclass` so the ordering is like:

Declared Fields + Model Fields.

My suggested solution is re construct new `OrderedDict` for `resource.fields` after extracting fields from model.

### Current behavior
```py
# Resource class already has declared fields so model fields are appended
new_class.fields.update(OrderedDict(field_list))
```

### Suggested change
```py
# Model fields are first then declared fields
new_class.fields = OrderedDict([
    *field_list,
    *new_class.fields.items()
])
```

### Example
```py
class BookResource(ModelResource):
    publish_date = fields.Field(
        attribute="publish_date",
        column_name="publish_date",
        widget=widgets.DateWidget("%d.%M.%Y")
    )

    class Meta:
        model = Book
        fields = ["id", "name", "publish_date"]
```

![Screenshot 2023-11-22 101124](https://github.com/django-import-export/django-import-export/assets/53194641/21a35a3e-47d9-498a-80cd-e2aae1d2a27a)

**Comment by cocorocho** [comment]
I was going to create a PR but should this be the intended behavior?

Basically, declared fields are going to be in the end. This is not going to preserve the actual model field order.

#### Example

```py
class Book(Model):
    name = CharField()
    published = DateField()
    author = CharField()
    author_email = EmailField()


class BookResrouce(ModelResource):
    published = fields.Field(
        attribute="published",
        column_name="published_date",
        widgets.DateWidget("%d.%M.%Y")
    )

    class Meta:
        model = Book

# My solution's outcome
# id, name, author, author_email, published

# Or should it be
# id, name, published, author, author_email
```

**Comment by matthewhegarty** [comment]
> This is not going to preserve the actual model field order.

Do you know if it would be possible to do this, because that would be the best outcome.
