### ISSUE TITLE
Admin UI does not show message for deleted objects

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1675]
**Describe the bug**

If you delete an object via the interface, there is no message to indicate if objects were deleted.

![image](https://github.com/django-import-export/django-import-export/assets/6249838/ec5e3176-2e77-4145-8e5c-a6ae82a6abec)

**To Reproduce**

- Login to Admin interface
- Import books.csv (tests/core/exports/)
- Import books-for-delete.csv
- You will not see any message for delete

**Versions (please complete the following information):**
 - Django Import Export: 3.3.1
 - Python 3.11
 - Django 4.2

**Expected behavior**

A message indicating that delete was successful

**Comment by RobTilton** [comment]
I'd like to attempt to assist with this, I have some Django related exp, as depicted in my repos. I am new to open source, and this seems like a simple issue. Maybe a missing line in a delete method. Is there any other information you can provide, that might help me locate this faster? @matthewhegarty

**Comment by matthewhegarty** [comment]
Hi Rob

Thanks for the offer of help, much appreciated. 

- First check out the contributing guidelines in the docs
- Next, get the example app running and reproduce the issue as above.
- You'll likely need to modify [this method](https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/import_export/admin.py#L248) to check for deletes and to write an appropriate method
- Add tests ([this](https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/tests/core/tests/test_admin_integration.py#L117) is an example you can copy and adapt)
- Test manually and make sure it is working
- Run the test suite with `make test`
- Once you have a working version, create a PR and push to your fork (loads of tutorials online for this if you are new to it).

Let me know if you get stuck or need a hand.

Matt

**Comment by RobTilton** [comment]
@matthewhegarty 
good evening, Matt, just a little update.
I have reproduced the bug.
and I believe I have tracked the issue back from line 248 add_success_message()
through precess_result()
Here we have Two methods that return process_result()
import_action() and process_import(). 
In process_import() I found the form validation for imports.
in admin.py line 159 there is an if confirm_form.is_valid(): 
and below on line 166 there is a tmp_storage variable.
in this variable we find name=confirm_form.clean_data['import_file_name']

Throughout the rest of this I couldn't find a place where the name of the file was being used. But I see that the name of the csv file is directly related to deleting the books, unless I am mistaken. But we delete the temp file and do not return anything that would tell us it was -for-delete. 

searching the files the only place for-delete comes up is in a test case, in test_admin_intergration.py. 

My thoughts are we have to pass a bool down to add_success_message(), something along the lines of is_for_deletion.
the message that is returned by add_success_message() can be determined with an if statement. 

Hopefully this isn't to much information, but I like to be clear. 

Is there a way you decide to delete through import that I missed in the files?

**Comment by matthewhegarty** [comment]
Hi Rob

You are on the right lines, but hopefully the solution to this is fairly straightforward.

Firstly, there is no default logic for deleting items.  The user has to implement that for themselves.  In the example app, that is already implemented [here][1].

The check for deleting objects is performed [here][2].

However, all you will need to do is to modify the `add_success_message()` method.  Note that this is passed a `Result` object (which is defined [here][3]).  The `Result` object contains N [`RowResult`][4] instances, each one of which (if valid) is 'new', 'update', 'delete' or 'skip'.  You can see how this is implemented in `add_success_message()`.

So all you will have to do is to read the number of deleted rows in the Result object (i.e. how many RowResults are delete), and add that to the message.  Ideally you could add helper methods to `Result` to report on the number of objects (e.g. `num_delete()`, `num_new()`, `num_update()`, `num_skip()`).

To do this properly, we should also report on the number of skipped rows.  This will also change the message to users, therefore I propose to make this change in the forthcoming v4 release.  This means you will have to take a branch from `release-4` and makes the changes there.

Hopefully this all makes sense, happy to clarify further if required.

[1]: https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/tests/core/admin.py#L22

[2]: https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/import_export/resources.py#L786

[3]: https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/import_export/results.py#L113

[4]: https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/import_export/results.py#L15

**Comment by RobTilton** [comment]
@matthewhegarty 
Good evening Matt, Update:
![image](https://github.com/django-import-export/django-import-export/assets/105300415/b7742e0f-3dfb-4ef3-be02-8168f5f7a5a8)
Is there a specific way you would like this to read?

**Comment by matthewhegarty** [comment]
Looks great.  I would suggest keep it simple:

```
Import finished: 1 new, 0 updated, 0 deleted and 0 skipped books.
```

What do you think?

**Comment by RobTilton** [comment]
Alright, I have the Test, test_import_for_deletion, done, name added to Authors.txt, and aligned the message with your suggestion.
pushed to the Fork, and as soon as I make sure I haven't missed anything, and determine if I need to right a patch, or is that a term for an update, I believe its done.

The Fork should be on my page if you needed to look over it, And Id appreciate it if you did. This is my first attempt ever at working on code that wasn't mine. I have no other experience, and I am a little apprehensive to say it's complete.
 
Have a good night.

**Comment by matthewhegarty** [comment]
Sounds great, thanks so much for taking the time to do this, much appreciated.  What you should do now is to submit a [Pull Request][2].  If you have pushed to a branch in your fork, then you should see a prompt for this when you go to [this page][1].

Once you create the PR, the automated tests will run.

When you have submitted the PR, I will be able to review, and add any comments and request any changes if necessary.  It's very common for the maintainers to request changes, but sometimes it's not necessary.

This all happens in your branch, and when the change is approved, it will be merged into the main codebase, and you will have submitted your very first PR.

[1]: https://github.com/django-import-export/django-import-export/pulls

[2]: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by RobTilton** [comment]
I am working on fixing all the test I broke with the changes. a lot of:
str_in_response="Import finished, with 1 new and 0 updated books."
That I wasnt aware of. Should be a simple fix of just changing the line over to what is expected.
After that I'll complete the Pull Request.
atm 20 failures, 7 skipped.
