### ISSUE TITLE
Running tests with `reverse` flag causes test failures

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1677]
**Describe the bug**

Tests should be able to run in [any order](https://docs.djangoproject.com/en/4.2/topics/testing/overview/#order-in-which-tests-are-executed) to minimise dependencies between tests.

However, running tests with the reverse flag causes test failures.

**To Reproduce**

```python
./manage.py test --reverse
```

**Versions (please complete the following information):**
 - Django Import Export: 3.3.1
 - Python 3.11
 - Django 4.2

**Expected behavior**

Tests should pass with no issues

**This should be done on the `release-4` branch due to test refactorings**

**Comment by RobTilton** [comment]
Do you want this to be on the release-4 build?
and to make sure I understand this, each test IS NOT isolated, and that is what we are aiming for. Correct?

**Comment by matthewhegarty** [comment]
Yes this should be on `release-4` please.  Refer to the contributing.rst page for guidance on how to configure environment for tests.

We are aiming that the test suite runs successfully no matter what order the tests are run (also see the `shuffle` param) (see [docs][1]).  This is best practice for tests.  Likely there are dependencies between tests, probably due to state being retained prior to test runs.

I would say get comfortable with how tests are run by reading the [django docs][2] first (apologies if you already know all this).  You can run each test module on its own with `reverse` and `shuffle` and you should be able to track down the problem tests fairly quick.

For example you can run a single module with:

```
cd tests
./manage.py test core.tests.test_mixins
```

If you get stuck give me a shout.

[1]: https://docs.djangoproject.com/en/4.2/ref/django-admin/#cmdoption-test-shuffle
[2]: https://docs.djangoproject.com/en/4.2/topics/testing/

**Comment by RobTilton** [comment]
Understood, Code is up and running on my local machine. I have reproduced the issue, with 1 Failure, 9 Errors, 7 Skips.  With the majority of the errors being: 
sqlite3.OperationalError: no such table: core_bookwithobjectrepr
If I run into any walls that I can't find my way over or around, I'll be sure to contact you.
