### ISSUE TITLE
Cannot create export selection when defining multiple resource classes

### ISSUE THREAD

**Issue by stefanvi** [django-import-export/django-import-export#1679]
**Describe the bug**
Hi, I'm trying to create a Model with multiple resources. This works well, but now it seems that I lose the ability to use the `ExportActionMixin`, as the export options do not show up in the admin actions. I can use the regular `ExportMixin`, but with this one I can't select which items I would like to export; it simply exports all items. This is a big nuisance, because the site I'm working on frequently needs to export a selection of data, but not everything. Filtering would need to be done manually.

Is there a way to either:
- Have multiple Model exports show up in the admin actions?
- Or, exporting only a selection, when using the standalone export page?

Thanks

**Comment by matthewhegarty** [comment]
Funnily enough I am working on adding this at the moment - see #1671.

It is still in draft, but you could check out the [branch](https://github.com/matthewhegarty/django-import-export/tree/issue-1440-export-multiple-resources) and try it out.  It is basically functional, I still need to add tests and documentation.  It will be released in the next v4 beta release.

**Comment by stefanvi** [comment]
That's great to hear, thank you!

**Comment by matthewhegarty** [comment]
For info, this has been [released][1].

[1]: https://pypi.org/project/django-import-export/4.0.0b0/
