### ISSUE TITLE
Running tests using runtests.sh

### ISSUE THREAD

**Issue by cocorocho** [django-import-export/django-import-export#1686]
I can't seem to find where `runtest.sh` is used but the file still uses `docker-compose` instead of `docker compose` which is the [old V1 syntax](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose).

https://github.com/django-import-export/django-import-export/blob/ebf58e0fe6b27285bb1c9bdfcfff0792bd7ad116/runtests.sh#L17

Is this test runner still to be used? If so maybe I could create a PR for using the valid `docker[-]compose` syntax based on whichever is available

**Comment by matthewhegarty** [comment]
Hi
The purpose of `runtests.sh` is for those that want to run a full test suite locally ([docs][1]).  You'd be welcome to submit a PR to update to latest syntax.

[1]: https://github.com/django-import-export/django-import-export/blob/main/docs/testing.rst
