### ISSUE TITLE
Declared fields are still imported/exported even if they are not defined in Meta.fields 

### ISSUE THREAD

**Issue by cocorocho** [django-import-export/django-import-export#1693]
**Describe the bug**
Declared field in `ModelResource` will still be imported/exported whether they are in `Meta.fields` or not

**To Reproduce**
```py
class BookResource(ModelResource):
    author_name = fields.Field(attribute="author__name", column_name="author_name")

    class Meta:
        model = Book
        fields = ("id", "price",)

# `author_name` will still be exported even though it's not in `Meta.fields`
```

**Versions (please complete the following information):**
 - Django Import Export: 3.3.3
 - Python 3.10.12
 - Django 4.2.7

**Expected behavior**
if `fields` is defined in `Meta` only those fields should be imported/exported

**Comment by matthewhegarty** [comment]
Thanks for raising - are you able to supply a fix for this?
