### ISSUE TITLE
Import Columns wich dont dont exist in the Model fields (read only not working correctly ?)

### ISSUE THREAD

**Issue by Yodale1000** [django-import-export/django-import-export#1697]
i got this Resource:

```
class ProductionResource(resources.ModelResource):
    article = fields.Field(column_name="GMC", attribute="article", widget=ForeignKeyWidget(Article, "gmc"))
    amount = fields.Field(column_name="Menge", attribute="amount")
    number = fields.Field(column_name="Lagerplatz", attribute="number")
    sheet = fields.Field(column_name="Bogen", readonly=True)
    use = fields.Field(column_name="Nutzen", readonly=True)
    version = fields.Field(column_name="Version", readonly=True, widget=CharWidget())
    comment = fields.Field(column_name="Bemerkung", readonly=True)

    def before_import_row(self, row, row_number=None, **kwargs):
        row["Lagerplatz"] = f"PRODUKTION ({row['GMC']})"

    def after_import_row(self, row, row_result, row_number=None, **kwargs):
        Movement.objects.create(
            article_number=row["GMC"],
            storage_place_barcode=row["Lagerplatz"],
            amount_moved=row["Menge"],
            operation=1,
            purpose=5,
            user=kwargs['user'],
            comment=f"({row['Bogen']}/{row['Nutzen']}) {row['Version']} {row['Bemerkung']}"
        )

    class Meta:
        model = StoragePlace
        use_bulk = True
        use_transactions = True
        skip_unchanged = False
        report_skipped = True
        import_id_fields = ["article", "number"]
        exclude = ["id", "blocked", "can_store_multiple_articles"]
```

The fields sheet, use, version and comment don't exist and this is the reason why i get key errors. I thought the read only attribute would solve my problem but apparently it dose not.

**Comment by matthewhegarty** [comment]
Thanks for raising.  The `readonly` field seems to control whether the field is saved or not, not that it is ignored during import, so I might need to clarify the documentation.

Would setting [fields / exclude][1] help?

If you still think this is a bug, could you reproduce in the example app, or provide a failing test case?

[1]: https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#declare-import-fields

**Comment by matthewhegarty** [comment]
I added a test to attempt to reproduce this issue [here](https://github.com/matthewhegarty/django-import-export/blob/397f3ca21777bd980d773e000a411fd92f6427fa/tests/core/tests/test_resources/test_resources.py#L1465), however I can't reproduce it.  Please can you confirm this is the issue you are facing?
