### ISSUE TITLE
`test_resources.py` is too large and can be broken up

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1700]
The `test_resources.py` module is too large (~1.8k lines).  It could be broken up into its own package, with sub-modules.

Additionally `ModelResourceTest` test case is too large and should be broken up.

For example:

```
test_resources/
  test_modelresource/
    test_export.py
    test_import.py
 ...
```

**Comment by abastola0** [comment]
@matthewhegarty can you assign me this issue?

**Comment by matthewhegarty** [comment]
Thanks - all yours

**Comment by bvedang** [comment]
Hi @matthewhegarty  I'm currently exploring the issue of refactoring ModelResourceTest from test_resources.py into multiple smaller, more focused test classes.
I'm interested in gathering insights or suggestions on the following:
- **Replicating vs. Customizing setUp Methods**: In cases where a large test class with a comprehensive setUp method is being split into smaller classes, what are the best practices for handling the setUp method in each new class? Should the setUp method be replicated across all new classes, or should it be customized to fit the specific needs of each class?

- **Identifying Common vs. Unique Setup Needs**: How can one effectively identify which parts of the existing setUp method are universally applicable to all new classes, and which parts should be modified or omitted based on the unique requirements of each test class?

**Comment by matthewhegarty** [comment]
I would suggest not to worry too much about complicated refactoring.  We don't mind duplication of logic in test classes, and it is perhaps something we can address later.  The main goal is to break up large test modules so that they are easier to manage.
