### ISSUE TITLE
IllegalCharacterError is not handled

### ISSUE THREAD

**Issue by ralfzen** [django-import-export/django-import-export#1712]
**Describe the bug**
When there are ASCII control characters > 32 in the values for the export, the export to `.xlsx` will fail, because `openpyxl` can't handle it.

**To Reproduce**
1. In a CharField add '\x0b' to the value.
2. Click on 'export' in the ModelAdmin Changelist Browser window.
3. Chose 'xlsx' and submit.

**Versions (please complete the following information):**
 - Django Import Export: [3.3.4]
 - Python [3.11]
 - Django [4.2.7]

**Expected behavior**
Just have these characters escaped or replaced and continue with the export. In best case have a message to the user about the replacement of some characters.

**Screenshots**
![Bildschirmfoto 2023-12-12 um 18 07 50](https://github.com/django-import-export/django-import-export/assets/639859/eaf3f3e3-3585-4798-9bb5-0d0fee4572cd)

**Additional context**
In my case the problem occurred with the "vertical tab", which is in `string.whitespace`.
```python
>>> '\v'
'\x0b'
>>> import string
>>> string.whitespace
' \t\n\r\x0b\x0c'
```
But I assume there are more characters as described in: http://www.havnemark.dk/?p=185

**Comment by matthewhegarty** [comment]
Hi 
Thanks for raising.  We could not reproduce this in the example app with the steps suggested.  Is it possible you can reproduce in the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app), and provide updated instructions?
