### ISSUE TITLE
Issue with preferred color scheme when manually using the other scheme

### ISSUE THREAD

**Issue by ZibingZhang** [django-import-export/django-import-export#1718]
**Describe the bug**
When the preferred color scheme is set to dark, but the color scheme being used is manually selected as light (or vice versa), the CSS doesn't support the manual override.

**To Reproduce**
1. Have preferred color scheme be dark
2. Manually select light in the admin panel
3. Import a file

**Versions (please complete the following information):**
 - Django Import Export: 3.3.4
 - Python: 3.11.1
 - Django: 5.0

**Expected behavior**

I would expect this library to respect the manually selected color scheme.

**Screenshots**
<img width="1465" alt="image" src="https://github.com/django-import-export/django-import-export/assets/44979059/d5e450d5-31a2-4082-a1c0-75afeb91ea11">

**Additional context**
The admin page handles this override with a `html[data-theme="light"]`. This library doesn't check for the manually selected theme, which could be different than the preferred color scheme, and so the CSS doesn't line up.

**Comment by matthewhegarty** [comment]
Thanks for reporting.  Would you be able to supply a fix for this?

**Comment by ZibingZhang** [comment]
If this could get added to 3.3.5, that would be appreciated.

**Comment by matthewhegarty** [comment]
Released in 3.3.5 👍
