### ISSUE TITLE
Getting column name causing import error

### ISSUE THREAD

**Issue by msanders70** [django-import-export/django-import-export#1719]
Hi,

I try to import CSV data from a file into a Django DB. I've a column called "price" containing a floating point value. But this value has the "," as decimal separator which leads of course into an "<class 'decimal.ConversionSyntax'>" error. That's fine.

But I try to get the column name "price" causing this conversion error, but can't find it in the result of the "import_data()" function. I call "import_data()" like this:

```
        result = resource.import_data(
            dataset=dataset,
            dry_run=False,
            raise_errors=False,
            use_transactions=True,
            collect_failed_rows=True,
            rollback_on_validation_errors=True,
        )

```

Any idea how to get the column name?

Thank you!

**Comment by matthewhegarty** [comment]
The column name price will be in the [dataset](https://tablib.readthedocs.io/en/stable/tutorial.html#selecting-rows-columns). e.g.

```python
price = dataset["price"]
```

Does this help answer the question?

**Comment by msanders70** [comment]
No no. What I mean: How can I get the column name causing the import error? The column name "price" was just an example, it could also be "foo" or anything else... The import failes because one column causes this problem. But which column?

Thank you!

**Comment by matthewhegarty** [comment]
You could inspect the [`Result`](https://github.com/django-import-export/django-import-export/blob/bf18044f3d9102371400316570800b0181412f2e/import_export/results.py#L113) object which is returned from the `import_data()` call.  Some more info [here](https://django-import-export.readthedocs.io/en/4.0.0-beta.2/advanced_usage.html#validation-during-import) (although this documentation relates to the v4 beta release, the interface for v3 should be the same).

**Comment by msanders70** [comment]
Well, of course I evaluate the result of "import_data()" according to the documentation and I can see the "ConversionSyntax" error. But where can I find the corresponding column name?

![grafik](https://github.com/django-import-export/django-import-export/assets/16937349/b91afdf3-ac94-41ac-8512-27758c62299c)

**Comment by matthewhegarty** [comment]
My best suggestion would be to set a breakpoint [here](https://github.com/django-import-export/django-import-export/blob/bf18044f3d9102371400316570800b0181412f2e/import_export/resources.py#L594) and see which field throws the error.

We have an [open issue](https://github.com/django-import-export/django-import-export/issues/1359) to improve the error reporting.

**Comment by msanders70** [comment]
Yes, I already found this line of code. But that's not the issue. I want to know it at runtime when the customer imports a CSV file. No debugger possible at this time... :-) The issue you mentioned goes exactly towards this problem.

Thanks a lot for your support!

**Comment by matthewhegarty** [comment]
If you are able to submit a PR for #1359 that would be appreciated.  We are planning our v4 release for the new year, so it could well go into that.

Or, if this is for a commercial venture, you could consider sponsoring development of the feature.

**Comment by matthewhegarty** [comment]
We added better support for identifying the underlying error [here](https://github.com/django-import-export/django-import-export/pull/1729)

**Comment by msanders70** [comment]
Thank you very much! This seems to be very helpful!

Unfortunately the new "result.invalid_rows" element is empty, although there is an import error (wrong decimal separator; "," instead of "."). Therefore, there's also no "row.error.error_dict" containing the invalid field/column.

![grafik](https://github.com/django-import-export/django-import-export/assets/16937349/543b0afe-d1d2-428b-a668-a854343aac3a)

**Comment by matthewhegarty** [comment]
I'll take a look - are you are testing with the `release-4` branch?

**Comment by msanders70** [comment]
Oh, shit! I though it would be integrated in "https://pypi.org/project/django-import-export/3.3.6/".
My mistake, sorry for that! I'll re-test.

**Comment by msanders70** [comment]
Ok, re-tested. And now I see...

In my case the "decimal.ConversionSyntax" error (because of the "," instead of the "." decimal separator; a frequently occuring user mistake) is saved in "row_result.errors" (ressources.py#932ff):

            if row_result.errors:
                result.append_error_row(i, row, row_result.errors)

And not in "row_result.validation_error" (ressources.py#940ff):

            elif row_result.validation_error:
                result.append_invalid_row(i, row, row_result.validation_error)

Therefore, in my case there's no benefit of the "invalid_rows" member with the interesting "error_dict" member where the field/column name causing the import error is located:

for row in result.invalid_rows:
        print(f"--- row {row.number} ---")
        for field, error in row.error.error_dict.items():
            print(f"{field}: {error} ({row.values})

My bad luck. :-(

**Comment by matthewhegarty** [comment]
You could look at a custom widget to detect this error and raise [`ValueError`](https://django-import-export.readthedocs.io/en/4.0.0-beta.2/advanced_usage.html#field-level-validation), this should give you the column information because it would know which field caused the error.

You could try to pass the [`collect_failed_rows`](https://github.com/django-import-export/django-import-export/blob/e42209ef9670d68aca3758cc862d7753057fa442/import_export/resources.py#L796) param.  This creates a new Dataset in the result, with the failed row and the errors appended.  However, I don't think this will give you any more information.

Let me know if this helps.

**Comment by msanders70** [comment]
I already set "collect_failed_rows=True", which unfortunately doesn't help.
I wasn't aware of the "clean_modal_instance" feature, I'll give it a try.
Finally, the custom widget should help.

Thank you, I'll keep you informed.

**Comment by msanders70** [comment]
Wow! The custom widget did the trick. Thank you!

![grafik](https://github.com/django-import-export/django-import-export/assets/16937349/62a0b838-5392-481d-972b-6a48b4cb56b3)
