### ISSUE TITLE
How to disable import?

### ISSUE THREAD

**Issue by lsmith77** [django-import-export/django-import-export#1725]
I only want to support import. Can export be disabled somehow?

**Comment by lsmith77** [comment]
Err the obvious way to do it is via permissions: https://django-import-export.readthedocs.io/en/latest/installation.html#import-export-import-permission-code

**Comment by matthewhegarty** [comment]
Yes, you can use permissions to control which users have access, or to remove the functionality completely, you can modify which mixins you link to the model.

e.g.

```python
# Export only
class BookAdmin(ExportMixin, admin.ModelAdmin):
    pass

# import only
class BookAdmin(ImportMixin, admin.ModelAdmin):
    pass
```

e.g. import only:

![image](https://github.com/django-import-export/django-import-export/assets/6249838/c038b7cb-8fff-455a-b699-7018b8c3ecbd)

[Docs](https://django-import-export.readthedocs.io/en/4.0.0-beta.2/advanced_usage.html#importing)
