### ISSUE TITLE
Grappelli Dashboard causes UI issue

### ISSUE THREAD

**Issue by lsmith77** [django-import-export/django-import-export#1726]
**Describe the bug**
After enabling [Grappelli Dashboard](https://django-grappelli.readthedocs.io/en/latest/dashboard_setup.html?highlight=dashboard#custom-dashboard), the top action button styling is broken

Before it looks like this:
<img width="331" alt="image" src="https://github.com/django-import-export/django-import-export/assets/300279/ad68420a-c0b3-4463-b0bf-a2dae24f1bf0">

Now it looks like this:
<img width="102" alt="image" src="https://github.com/django-import-export/django-import-export/assets/300279/013576db-82b2-4f38-af28-03b9cc3d157f">

Maybe related to https://github.com/django-import-export/django-import-export/issues/901 ?

Note all admin's where I am not using `django-import-export` still look fine.

**To Reproduce**
1. Install Grappeli
2. Activate [Grappelli Dashboard](https://django-grappelli.readthedocs.io/en/latest/dashboard_setup.html?highlight=dashboard#custom-dashboard)
3. Go to admin list view with import/export enabled

**Versions (please complete the following information):**
 - Django Import Export: 3.3.5
 - Python 3.11
 - Django 4.2

**Additional context:**

It appears that the issue is due to `class="grp-object-tools"` becoming `class="object-tools"`, which I think would be fixed via the change proposed in https://github.com/django-import-export/django-import-export/issues/901 (I am not sure why the ticket was closed).

**Comment by lsmith77** [comment]
Possible fix would be
```
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
{% if has_add_permission %}
{{ block.super }}
{% endif %}
{% endblock %}
```

**Comment by matthewhegarty** [comment]
Have you tried with [v4 beta](https://pypi.org/project/django-import-export/4.0.0b2/)?  I haven't tested but there have been some changes which might help.

**Comment by lsmith77** [comment]
I have not but I suspect it should have the same issue as the relevant template remains unchanged:
https://github.com/django-import-export/django-import-export/blob/release-4/import_export/templates/admin/import_export/change_list.html

Note I can fix it by overriding the template with the above suggested code.

**Comment by matthewhegarty** [comment]
Is it possible you can supply me with steps to reproduce using the [example app](https://github.com/django-import-export/django-import-export/blob/main/docs/installation.rst#example-app)?  I tried but couldn't get Grappelli working.  If you can help me reproduce the issue I will take a look.

**Comment by lsmith77** [comment]
thank you for reaching out. I am currently not persuing the topic anymore. Note I just checked my commit when I added grappelli to my project and I don't see anything fancy I needed to do.

As for the example app. I am still a bit new to python but the setup is not clear to me at all.

**Comment by matthewhegarty** [comment]
Closing - no further progress.
