### ISSUE TITLE
Overriding before_import to make changes to csv

### ISSUE THREAD

**Issue by kaelaspark** [django-import-export/django-import-export#174]
It would be great if on an import django-import-export checked the file for an 'id' column and if it did not exist it automatically added it.

In the mean time, how do I override the before_import function to add the 'id' column along with some other changes (remove spaces and uppercase letters from the header and remove thousands separators from the integers) so that the users don't have to before they import. 

I am not sure how to access the dataset of the csv to make the changes. Am I able to use csvwriter? This is what I have so far:

``` python
class DonationResource(resources.ModelResource):

        class Meta:
            model = Donation 

        def before_import(self, *args, **kwargs):
            # make changes to csv
            super(DonationResource, self).before_import(*args, **kwargs)
```

I am pretty green so any help would be appreciated. Thank you.

**Comment by ahmedjawed01** [comment]
you can override it as

# to create a new instance
def get_instance(self, instance_loader, row):
        return False

# your custom save
    def save_instance(self, instance, real_dry_run):
        if not real_dry_run:
                try:
                    obj = YourModel.objects.get(some_val=instance.some_val)
                    # extra logic if object already exist
                except NFCTag.DoesNotExist:
                    # create new object
                    obj = YourModel(some_val=instance.some_val)
                    obj.save()

    def before_import(self, dataset, dry_run):

        if dataset.headers:
            dataset.headers = [str(header).lower().strip() for header in dataset.headers]

# if id column not in headers in your file
        if 'id' not in dataset.headers:
            dataset.headers.append('id')

**Comment by bitterjug** [comment]
I'm trying the same trick and my `before_import` is not being called at all. The class of the resource at run time appears to be 

```
  >>> type(self)
<class 'import_export.resources.QuestionResource'>
```

which has the same _name_ as my resource class but belongs to the `import_export.resources` module. What am I doing wrong?

**Comment by gz1992** [comment]
hey, if you want, you can use pandas as a dataset writer:

```
import pandas as pd

def before_import(self, dataset, using_transactions, dry_run, **kwargs):
        df = pd.DataFrame(dataset.dict)
        df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
        dataset.dict = df.to_dict('records')
        super().before_import(dataset, using_transactions, dry_run, **kwargs)
```
