### ISSUE TITLE
selected value of custom importForm is not being saved 

### ISSUE THREAD

**Issue by wesselcram** [django-import-export/django-import-export#1740]
The customized importForm in the test application does not seem to be working when used for default values on the imported rows. For example when i use the dropdown in the test application to select an author. The selected author is not being saved. 

To reproduce
- Clone django-import-export repository
- I started the test application
- I tested the CSV import as below (i removed author)
- i selected one of the authors in the dropdown (Ian Flemming)
- the chosen author form the dropdown was not inserted in the database

Versions:
Python 3.12.1
Django 5.0.1
tablip: 3.5.0
django-import-export: "3.3.7.dev0"

Expected
I expect the import csv to save the id of the selected author of the custom import form. 

CSV:
id,name,author,author_email,imported,published,published_time,price,added,categories
15,Triangles,,geo@met.ry,,2020-01-12,,12,,1

<img width="1407" alt="image" src="https://github.com/django-import-export/django-import-export/assets/43724700/0a62f81a-792d-4a3e-a38d-01e9f253c01c">

**Comment by AegAtt** [comment]
It does not work for me, when I try to debug the `after_import_instance` method, the `instance` parameter is NULL at that stage

**Comment by AegAtt** [comment]
It works just fine after the update, thanks
