### ISSUE TITLE
`get_resource_kwargs` should return kwargs passed

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1741]
**Describe the bug**

```
    def get_resource_kwargs(self, request, *args, **kwargs):
        return {}
```

This block will remove any values currently present in `kwargs`, which means data is lost and it is not easy to override.
[source](https://github.com/django-import-export/django-import-export/blob/eabba74bbfe0128411612c064b8e65900ab377ee/import_export/mixins.py#L65)

The correct implementation should be:

```
    def get_resource_kwargs(self, request, *args, **kwargs):
        return kwargs
```

There should be tests to prove this fix

**Versions (please complete the following information):**
 - Django Import Export: 3.3.6

**Comment by RobTilton** [comment]
@matthewhegarty Modify the return value of get_resource_kwargs and write a test for it? If that's what you want, I'll get on that asap.

**Comment by matthewhegarty** [comment]
Hi Rob - yes that is all that is needed (along with changelog update).  I would suggest this fix goes into the `main` branch and then we can port to `release-4`.

**Comment by RobTilton** [comment]
in case it matters I am sitting down to tackle this at this very moment, if you needed to assign anyone for records or anything along those lines.
@matthewhegarty

**Comment by matthewhegarty** [comment]
Thanks - feel free to assign it to yourself :+1:
