### ISSUE TITLE
Wrong indent in `skip_row` code block breaks intersphinx build

### ISSUE THREAD

**Issue by ulliholtgrave** [django-import-export/django-import-export#1742]
**Describe the bug**
We recently added your library to our django project, but our documentation build keeps failing with the following error:
`:docstring of import_export.resources.Resource.skip_row:22: ERROR: Unexpected indentation.`
This is related to our [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) setup which isn't able to parse the docstring of this `django-import-export`.

**To Reproduce**
Have a project with an intersphinx setup and use the `resources.ModelResource` in your code.

**Versions:**
 - Django Import Export: 3.3.6
 - Python 3.11
 - Django 3.2

**Expected behavior**
The docstring of `skip_row` should be successfully parsed and linked.

**Additional context**
This seems to be a problem of the missing line before the code block.

**Comment by matthewhegarty** [comment]
Thanks for reporting and submitting.  May I recommend using [v4 beta](https://github.com/django-import-export/django-import-export/releases/tag/4.0.0-beta.2) for new developments, as this has a lot of new features and fixes, and will be the main supported version from 2024.
