### ISSUE TITLE
Test needed to cover `collect_failed_row` option

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1752]
**Describe the bug**

We have a line of code which is not covered by tests:

https://coveralls.io/builds/65434344/source?filename=import_export%2Fresources.py#L945

**Versions (please complete the following information):**
 - Django Import Export: v4 beta
 - Django [e.g. 1.2, 2.0]

**Expected behavior**

We should get back up to 100% coverage.

**Comment by bvedang** [comment]
Hi @matthewhegarty 

So, we need to write a test case to trigger `collect_failed_row` . Am i thinking correctly?

**Comment by matthewhegarty** [comment]
Yes, that is correct.  We need coverage in the v4 branch for that single line.  You can set breakpoints and run the existing tests to find examples of tests which already cover that section of code.

Do you want to take it on?

**Comment by matthewhegarty** [comment]
It was easy to add a test,  PR [here](https://github.com/django-import-export/django-import-export/pull/1753).  Do you want to review?

**Comment by bvedang** [comment]
Hi @matthewhegarty,

I reviewed the PR and the test case you added looks great - it properly covers the `collect_failed_rows` path and hits the line we were missing. Validating the length of `failed_rows` and appending a row is a simple and effective approach.

Going through the test code and your comments explaining the approach also helped further my understanding of how to trigger and assert against error condition handling in the import process.

The hands-on learning for me to review the code and execution flow is super valuable.Thanks again for driving this one to completion and sharing the knowledge along the way.
