### ISSUE TITLE
'list' object is not callable

### ISSUE THREAD

**Issue by elcolie** [django-import-export/django-import-export#1754]
**Describe the bug**
It does not support list as said in the doc
<img width="1068" alt="image" src="https://github.com/django-import-export/django-import-export/assets/18206728/0d73fbff-27a4-44d1-81a5-74f84734a7f4">

**To Reproduce**
Follow the online document

**Versions (please complete the following information):**
django-import-export==3.3.7
python 3.12
django==4.2.9

**Expected behavior**
It should work normally

**Screenshots**
![image](https://github.com/django-import-export/django-import-export/assets/18206728/14f5c9f4-ac52-4f8c-a42c-692588af3382)

**Solution**
Remove bracket.

**Comment by matthewhegarty** [comment]
I can only reproduce this using the example application with the following declaration:

```python
class BookAdmin(ImportExportModelAdmin):
    # Incorrect - note the double bracket
    resource_classes = [[BookResource]]
```

It should be declared as:

```python
class BookAdmin(ImportExportModelAdmin):
    resource_classes = [BookResource]
```

Does this solve the issue?  If not, is it possible you can provide steps to reproduce using the example application, or create a failing test case?

**Comment by matthewhegarty** [comment]
Closed due to no response.
