### ISSUE TITLE
ImproperlyConfigured at /admin/..

### ISSUE THREAD

**Issue by nurlanek** [django-import-export/django-import-export#1758]
I keep encountering this error whenever I try to import data in any format. It consistently gives the same error for all tables. I've tried reinstalling import_export, but it didn't work.

**Comment by matthewhegarty** [comment]
Hi
You're going to have to give us more information to help you with this, please refer to the [guidelines](https://github.com/django-import-export/django-import-export/blob/main/docs/contributing.rst#questions).

Some things to add:

- What version are you using? (python, django, import_export)
- What are the steps to reproduce?
- Any stack trace or error message 
- Screenshots can help
- Can you reproduce with the example app?
- What have you tried already.

**Comment by matthewhegarty** [comment]
Closing due to lack of detail.
