### ISSUE TITLE
Validation when using ModelResource

### ISSUE THREAD

**Issue by sergei-maertens** [django-import-export/django-import-export#176]
Is anybody working on validation for resources generated by the modelresource_factory?

For instance, a Django CharField that has choices as keyword argument should be validated when importing. The value in the import file should match one of the possible values.

Another example is again with CharFields: make sure that max_length is respected and if the provided value is too long, trim it with django.utils.text.Truncator.

If this sounds reasonable, I'm definitely willing to put some time in it to add those validation rules and make a pull request. Right now for a project I'm overriding quite a bit of stuff to make this possible.

**Comment by ses4j** [comment]
Did anything ever come of this?

**Comment by sergei-maertens** [comment]
No, not yet

**Comment by dz0** [comment]
maybe just call  `instance.full_clean()`   in `before_save_instance(..)`

**Comment by ababic** [comment]
Hi @bmihelac.

I've got a version of this working locally, which I think is 'pretty okay'. However, I'm sure you'll have your own ideas about a few things (as will always be the case with changes of this size). Is this something you'd rather solve yourself, or would you be happy for me to submit a PR, and we can bash things into shape together?

**Comment by bmihelac** [comment]
Fixed with bd5ce92.
