### ISSUE TITLE
Export the excel as password protected file

### ISSUE THREAD

**Issue by RakeshAMD** [django-import-export/django-import-export#1766]
We would like to download the report with password protected file, because some may contains sensitive data in it.

How to do that with this package?

**Comment by matthewhegarty** [comment]
It's not possible to do this directly with the package, but you could perhaps extend existing functionality to achieve this.

I assume that you are exporting to XLSX format?  If so, it may be possible to use openpyxl to modify the output to be [password protected](https://openpyxl.readthedocs.io/en/stable/protection.html).  I haven't tried this so I cannot verify that it will work.

To embed this in django-import-export, you will likely have to create a custom format to override the `export_data()` method from [`XLSX`](https://github.com/django-import-export/django-import-export/blob/3cd5bba63279b5043ba22b805412f85da9c42e36/import_export/formats/base_formats.py#L182) format.  You might be able to create a password protected object with directly calls to change the xlsx object.

You'll need to update the [settings](https://django-import-export.readthedocs.io/en/4.0.0-rc.0/installation.html#import-export-formats) to provide your new XLSX format with password protection.

Make sure you use the v4 rc as this has the latest updates.

Feel free to post back if you get a working solution.

**Comment by matthewhegarty** [comment]
I suggest to read the openpyxl documentation to see if this is possible, and if so, then you can try to implement using the techniques I proposed in my earlier message.
