### ISSUE TITLE
Issue in line no 227 of widget.py file

### ISSUE THREAD

**Issue by am1ty9d9v** [django-import-export/django-import-export#177]
AttributeError: 'float' object has no attribute 'split' if only one value is passed in m2m field, hence we get a float value from excel sheet.

To fix this I converted float to str.

Here is the changes in fork version.
https://github.com/am1ty9d9v/django-import-export/commit/c2e7b5531308e56e941f0abf9c0cefd7e637ff49?diff=split

**Comment by citmusa** [comment]
https://github.com/citmusa/django-import-export/commit/24e3f406a5a8e280c8a9815a901ba496fbedf60e

**Comment by fabian** [comment]
Can confirm this is still a problem in version 0.4.2.

A workaround is to add a comma at the end of the single value in the Excel file.

Any chance to get #180 merged?

**Comment by bmihelac** [comment]
Merged in ccff5ed15b6b51e17e138d0874fbf68caba52e46

Thanks!

**Comment by TheDeadOne** [comment]
The problem still remains in the version 0.4.5.
