### ISSUE TITLE
how to skip error for confirm: '"Field 'id' expected a number but got '1-variant'. "

### ISSUE THREAD

**Issue by ikhasanmusaev** [django-import-export/django-import-export#1773]
![image](https://github.com/django-import-export/django-import-export/assets/48137379/9bfc2e15-6674-4a2f-bc4d-be830513afb6)

I get this error every time. I can’t just get by without just an id. Why should I enter the id at all, when the model itself should set the required value?

**Comment by matthewhegarty** [comment]
Can you give us some more information?  It's hard to understand the nature of the issue.

- Please post the code for your Resource
- What version of import-export?

**Comment by matthewhegarty** [comment]
Close due to lack of activity
