### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by Viicos** [django-import-export/django-import-export#1783]
Would you open to have type hints in the library? If so, I can come up with a PR. A couple things to note:
- Type hinting a Django related library can be difficult. We can consider having types defined as separate stubs (e.g. in typeshed). Having type stubs will also simplify the writing of such types, so this option is totally fine by me. It's just a matter of if you prefer to have types in the source code to ease development.
- If we choose to define separate stubs, I'll probably make use of generics, so `__class_getitem__` would have to be added in the library itself (which doesn't affect runtime at all).

**Comment by andrewgy8** [comment]
Thanks @Viicos for opening this issue. Do you know of any other large Django projects that have embraced type hints? And what has the reaction been like from the community after they added them? 

In a declarative library like django-import-export, Im struggling to see the benefits of adding them.

**Comment by Viicos** [comment]
I recently [did it](https://github.com/deschler/django-modeltranslation/pull/716/) in `django-modeltranslation` (but it isn't merged yet). My personal experience with it is that:
- whenever a library is dealing with Django internals, it gets tricky (sometimes Django stubs are incorrect, and dynamic stuff is hard to support). But it did help understand what `django-modeltranslation` was doing in some cases.
- The benefit for declarative libraries is limited (from an end user perspective), however I can see the benefit for some public methods called by such end users (`resource.export()`, `modelresource_factory` for instance).

So I think type hints would still be a nice addition (as stubs or in the library), although I do agree it isn't a strong requirement as most of the library is declarative

**Comment by matthewhegarty** [comment]
Hi - thanks for the offer of help.  I would agree with the view that it would be nice to have, but probably not required for a project like this.  Therefore I would conclude that we don't need type hints at this time.

If any other users have a view on this, they can add to this thread, and we can keep it in mind for later versions such as v5.
