### ISSUE TITLE
A way to make a header column required

### ISSUE THREAD

**Issue by Alex-Sichkar** [django-import-export/django-import-export#1792]
Hello everyone,

I have two questions:

1. Is there a way to make a header column required?
2. What is the proper approach for validating each row with a custom form?

Thanks!

**Comment by matthewhegarty** [comment]
> Is there a way to make a header column required?

Do you mean 'how to make a column required'? - i.e. show an error if a column is missing?  Are you using the Admin interface?

> What is the proper approach for validating each row with a custom form?

I don't know what you mean here.  You can set validation rules using widgets for each field, but I don't know how you would use a form.  Can you give more information as to what the use case is?

**Comment by matthewhegarty** [comment]
You can do it like this using the [v4 rc3][1] release:

```python
class BookResource(ModelResource):
    class Meta:
        model = Book

    def before_import_row(self, row, **kwargs):
        if "some_column" not in row:
            raise ValidationError("missing column")
```

![image](https://github.com/django-import-export/django-import-export/assets/6249838/2ecd3bbd-a84c-4826-abfa-bd35752c29b1)

[1]: https://pypi.org/project/django-import-export/4.0.0rc3/
