### ISSUE TITLE
Admin Export fails for models with a primary key which is not "id"

### ISSUE THREAD

**Issue by martynwatson-tdi** [django-import-export/django-import-export#1800]
**Issue**
I have a simple Django model as follows:
```python
class Category(models.Model):
    name = models.CharField(primary_key=True, max_length=30)
```

Clicking on the "Export" button in the `ImportExportModelAdmin` for this Model, I get the following, for line 736 in `import_export/admin.py`:
```
AttributeError at /admin/products/category/export/
'Category' object has no attribute 'id'
```

**Versions**
 - Django Import Export: 4.0
 - Python: 3.12
 - Django: 5.0.4

**Comment by matthewhegarty** [comment]
Thanks for raising.  This is a valid bug.  I can reproduce in the example app by adding 

```python
class UUIDCategoryAdmin(ExportActionModelAdmin):
    pass
...
admin.site.register(UUIDCategory, UUIDCategoryAdmin)
```
Then adding a `UUIDCategory` and then exporting.
