### ISSUE TITLE
Admin Export does not honour the "IMPORT_EXPORT_SKIP_ADMIN_ACTION_EXPORT_UI" setting

### ISSUE THREAD

**Issue by martynwatson-tdi** [django-import-export/django-import-export#1801]
**Issue**
Setting `IMPORT_EXPORT_SKIP_ADMIN_ACTION_EXPORT_UI = True` in `settings.py` does not skip the screen to choose a resource, fields or format from the Export button in an `ImportExportModelAdmin`

**Versions:**
 - Django Import Export: 4.0
 - Python: 3.12
 - Django: 5.0.4

**Comment by matthewhegarty** [comment]
Thanks for raising.  The reason for this is that the setting is only for cases when export is triggered via the 'action' menu.

![image](https://github.com/django-import-export/django-import-export/assets/6249838/9f35c781-8e72-4833-9ad3-a482ce52749a)

Skipping the confirmation screen using this setting is not supported at present.
