### ISSUE TITLE
Admin export confirm page runs a query for the entire table

### ISSUE THREAD

**Issue by bluetech** [django-import-export/django-import-export#1806]
When the export page is loaded, the code runs a query for the entire table of the model (i.e. the equivalent of `SELECT * FROM table`):

https://github.com/django-import-export/django-import-export/blob/9839a28089575baef1ecab686ab81682751ed761/import_export/admin.py#L736

When trying to export even a moderately sized table, which I think is a common scenario for django-import-export, such a query is very problematic, especially because it ignores any filtering on the queryset.

I'm not sure if this query is really intentional, but if it is, would it possible to add a way to turn it off?

**Comment by matthewhegarty** [comment]
Thanks for raising - you make a valid point.  I will take a look.

**Comment by matthewhegarty** [comment]
I have improved this in #1827

**Comment by bluetech** [comment]
Thank you @matthewhegarty, I can confirm that this no longer happens with 4.0.2.

**Comment by matthewhegarty** [comment]
Thanks for raising and confirming fix
