### ISSUE TITLE
attribute and column_name mixed up for export and Meta.fields

### ISSUE THREAD

**Issue by BeePerNet** [django-import-export/django-import-export#1808]
**Describe the bug**
Unable to export columns when the column_name is not the same as attribute when fields using attribute.

**To Reproduce**
1- Create a field and put his attribute name in the Meta.fields list and use another name for column_name
2- execute export

**Versions (please complete the following information):**
Last, last last, surfing on the last.

**Expected behavior**
Columns appears on export with the good translation of the column_name header

**Screenshots**
Useless

**Additional context**
Use less

** Fix **
Replace column_name by attribute when applicable. resource.py line 1034
```python
    def export_resource(self, instance, fields=None):
        export_fields = self.get_export_fields()

        if isinstance(fields, list) and fields:
            return [
                self.export_field(field, instance)
                for field in export_fields
                if field.attribute in fields
            ]

        return [self.export_field(field, instance) for field in export_fields]

    def get_export_headers(self, fields=None):
        if isinstance(fields, list) and fields:
            return [force_str(field.column_name) for field in self.get_export_fields() if field.attribute in fields]
        return [force_str(field.column_name) for field in self.get_export_fields()]
```

Thanks

**Comment by tobhv** [comment]
also seeing this. thanks for reporting it.

**Comment by tobhv** [comment]
the feature used to work in the v3 series. desired behavior is also documented here: https://django-import-export.readthedocs.io/en/stable/advanced_usage.html#explicit-field-declaration

**Comment by matthewhegarty** [comment]
Thanks for reporting.  I confirm this is a bug in v4.  I tested in v3 with the following in the example app:

```python
class BookResource(ModelResource):
    published = Field(attribute='published', column_name='published_date')

    class Meta:
        model = Book
        fields = ('id', 'name', 'price', 'published')
```

In v3, this will export to a column with header 'published_date'.  In v4, it doesn't export the column.  If you remove the custom declaration, then it exports ok as 'published'.
