### ISSUE TITLE
ImportForm does not support widgets with associated CSS and JS media

### ISSUE THREAD

**Issue by jhthompson** [django-import-export/django-import-export#1809]
**Describe the bug**
Any widget within a Field within an `ImportForm` that has its own associated CSS and/or JS does not get that CSS/JS included on the rendered form page.

**To Reproduce**
I first noticed this while trying to use [django-autocomplete-light](https://pypi.org/project/django-autocomplete-light/) on an `ImportForm`.

To demonstrate, I created an example [commit](https://github.com/jhthompson/django-import-export/commit/5ce12968f61e438101c28f02140342bf3f531417) where I install django-autocomplete-light and change the "author" selection on the EBook admin import form to use a `autocomplete.ModelSelect2` widget instead of the default.

```diff
 class AuthorFormMixin(forms.Form):
     author = forms.ModelChoiceField(
         queryset=Author.objects.all(),
         required=True,
+        widget=autocomplete.ModelSelect2(url="author-autocomplete"),
     )
```

None of the required JS or CSS load on the page, so it renders in a broken state like this:

![Screenshot 2024-05-02 at 12 03 12 PM](https://github.com/django-import-export/django-import-export/assets/23730407/e879409c-04ee-4600-817b-b06b6d5771e6)

**Versions**
_From what I can tell, this affects all versions._
 - Django Import Export: all
 - Python: all
 - Django: all

**Expected behavior**
The autocomplete field should work, since it will have all of its required CSS and JS:
![Screenshot 2024-05-02 at 12 05 36 PM](https://github.com/django-import-export/django-import-export/assets/23730407/7ea1ec3b-7ba2-476b-b838-b872936247a5)

**Comment by bmihelac** [comment]
Fix in https://github.com/django-import-export/django-import-export/commit/af13bde8e4470440a94769bd9fa35748b4fd9b02
