### ISSUE TITLE
'import_id_fields = []' can't handle programmaticaly created columns in 4.0

### ISSUE THREAD

**Issue by AlmerCarbonEquity** [django-import-export/django-import-export#1811]
**Describe the bug**

We use the import functionality for a model that has a foreign key `deal` that we can only uniquely identify using 2 fields: `account_name` and `product_name`. We fixed this by making a new column programaticaly in `before_import_row` but since 4.0 we get an error that we need to have all fields we set in  'import_id_fields' in the header of our file. How are we expected to handle this? A workaround is to just have an empty column in our import file that has 'deal' as the header, but this seems hacky.

The following exception is thrown:

`import_export.exceptions.ImportError: The following fields are declared in 'import_id_fields' but are not present in the file headers: deal`

**To Reproduce**

Here is an example model for which the import will break without 'deal' in the import file columns.

```
class AssetResource(resources.ModelResource):
    account_name = fields.Field(
        attribute="account_name",
        column_name="Account",
        widget=widgets.CharWidget(),
    )
    product_name = fields.Field(
        attribute="product_name",
        column_name="Product",
        widget=widgets.CharWidget(),
    )
    date = fields.Field(
        attribute="date",
        column_name="Date",
        widget=widgets.DateWidget(format="%d-%b-%y"),
    )

    class Meta:
        model = NetAssetValue
        fields = [
            "date",
            "deal",
        ]
        import_id_fields = ["date", "deal"]

    def before_import_row(self, row, row_number=None, **kwargs):
        row["deal"] = Deal.objects.get(
            account__name=row["Account"],
            product__name=row["Product"],
        ).id
```

**Versions (please complete the following information):**
 - Django Import Export: 4.0
 - Python 3.12
 - Django 5.0.3

**Expected behavior**

Don't raise: 

`import_export.exceptions.ImportError: The following fields are declared in 'import_id_fields' but are not present in the file headers: deal`

**Comment by matthewhegarty** [comment]
Thanks for raising - i will take a look.  One workaround might be to declare (not tested):

```
    def before_import(self, dataset, **kwargs):
        dataset.headers += "deal"
```

**Comment by AlmerCarbonEquity** [comment]
@matthewhegarty Thanks for the quick response. Using your workaround seems to trigger some kind of safety mechanism and raises:

`tablib.exceptions.InvalidDimensions`

**Comment by matthewhegarty** [comment]
Apologies, I'm guessing at the workaround... you could try:

```python
   def before_import(self, dataset, **kwargs):
       dataset.append_col([], header='deal')
```

**Comment by AlmerCarbonEquity** [comment]
@matthewhegarty Sorry, I wasn't really paying attention much. This workaround works:

```
    def before_import(self, dataset, **kwargs):
        dataset.headers.append("deal")
        super().before_import(dataset, **kwargs)
```

**Comment by matthewhegarty** [comment]
Closing as this is an edge case which can be solved using the workaround.
