### ISSUE TITLE
Default field set differs during import in v4

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1820]
**Describe the bug**

in v3, all model fields are presented during import:

![image](https://github.com/django-import-export/django-import-export/assets/6249838/79ed7332-adf2-44dd-ad99-a6a0d8ca1cd8)

In v4, only certain model fields are presented, even when no `fields` attribute is defined.

![image](https://github.com/django-import-export/django-import-export/assets/6249838/f21f04b3-7853-443f-a393-520b43c06e5b)

**To Reproduce**

Import the books.csv file using the Admin console.

**Versions (please complete the following information):**
 - Django Import Export: 4.0.1
 - Python 3.11
 - Django 5.0.2

**Expected behavior**

For consistency with v3, we should see all default fields presented.

**Comment by bmihelac** [comment]
@matthewhegarty I could not reproduce this.  You mention importing books.csv but screenshot looks like E-books import (it has author field). Without digging deeper, it seems fields that are presented are defined with Resource class and not import file headers.

**Comment by matthewhegarty** [comment]
Ah good point - thanks for checking.  I'll check again later and close if I cannot reproduce.

**Comment by matthewhegarty** [comment]
Yes, it looks ok when importing a file to Book 

![image](https://github.com/django-import-export/django-import-export/assets/6249838/a2f490a4-96ed-49a5-86ea-06ca8374fea7)
