### ISSUE TITLE
During import, existing keys not being ignored

### ISSUE THREAD

**Issue by pandye** [django-import-export/django-import-export#183]
Hi, 

I am using django-import-export. Is this possible django-import-export ignore the existing key values, because i have large csv file. when i import it, I am getting an error :

duplicate key value violates unique constraint "spm_author_name_key" DETAIL: Key (name)=(Arthur Rachkam) already exists.

**Comment by ibnbay99** [comment]
how and where to implement it? please write the example please.... :)
