### ISSUE TITLE
Fixed Arabic translate for  'Import' word

### ISSUE THREAD

**Issue by EngFarisAlsmawi** [django-import-export/django-import-export#1832]
https://github.com/django-import-export/django-import-export/blob/745039381cc7c9f61281f4dc76df9f3b48e35df7/import_export/locale/ar/LC_MESSAGES/django.po#L41

Fixed Patch:
` msgstr "إستيراد" `

**Comment by matthewhegarty** [comment]
Thank you - would you be able to create a PR?

**Comment by matthewhegarty** [comment]
Thanks for raising - this has been merged.
