### ISSUE TITLE
Breaking change due to _check_import_id_fields

### ISSUE THREAD

**Issue by jameslao** [django-import-export/django-import-export#1834]
**Describe the bug**
This is a breaking change in 4.0 vs 3.x. 

In my resource, I've declared a `before_import_row()` to add another column 'Object' to the row, which is used as an identifier. 

```
object = resources.Field(column_name="Object", attribute="object")

def before_import_row(self, row, **kwargs):
....
        row["Object"] = hashlib.sha256((row.get("Object 1 Name") or "").encode()).hexdigest()
...

    class Meta:
...
        import_id_fields = ["time", "object"]
```

However, after upgrading to 4.0.2, the import throws an error

```
File "***/python3.12/site-packages/import_export/resources.py", line 1186, in _check_import_id_fields
raise exceptions.FieldError(
import_export.exceptions.FieldError: The following fields are declared in 'import_id_fields' but are not present in the file headers: Object
```

This check on headers seems not taking into accounts that the rows can change.

**Versions (please complete the following information):**
 - Django Import Export: 4.0.2
 - Python 3.12
 - Django 5.0.6

**Comment by matthewhegarty** [comment]
Can you see if this solves your issue:

```python
    def before_import(self, dataset, **kwargs):
        dataset.headers.append("Object")
        super().before_import(dataset, **kwargs)
```

**Comment by jameslao** [comment]
Thanks I ended up using the `before_import` to modify the whole dataset instead, but seems this behavior should be documented.
