### ISSUE TITLE
`TypeError: Widget.__init__() got an unexpected keyword argument 'allow_blank'`

### ISSUE THREAD

**Issue by OttoAndrey** [django-import-export/django-import-export#1841]
Hi! I'm trying upgrade import-export from 3rd to 4th version and getting error:
`TypeError: Widget.__init__() got an unexpected keyword argument 'allow_blank'`

It happens in this case (simplified):

```python
class UserAdminResource(resources.ModelResource):
    class Meta:
        model = models.User
        fields = (
            "first_name",
            "email",
        )
```

```python
class User(
    AbstractBaseUser,
    PermissionsMixin,
):
    first_name = models.CharField(
        verbose_name=_("First name"),
        max_length=80,
        blank=True,  # <--- I think problem is here
    )
    email = models.CharField(
        verbose_name=_("Email Address"),
        max_length=80,
        blank=False,
        unique=True,
        db_index=True,
        validators=[validators.validate_email],
    )
```

If I comment `first_name` inside `UserAdminResource` problem is gone (actually it will appear in other import resources but anyway).

I see similar problem in already solved [issue](https://github.com/django-import-export/django-import-export/issues/1817). Thats why I tried commenting fields inside resource.

**Comment by matthewhegarty** [comment]
Are you using v4.0.3? Are you using any third party plugins?

**Comment by matthewhegarty** [comment]
I couldn't reproduce this in the example app by declaring the following on the Book model:

```
    name = models.CharField(
        verbose_name=_("Name"),
        max_length=80,
        blank=True,  # <--- I think problem is here
    )
```

When we have seen this before it is because there is a custom field type (i.e. from a third party app) which is being identified as a `CharField` or subclass, but then is not being created with the correct Widget type.

If you could reproduce in the example app, or provide a failing test case, that would be ideal.

The other thing to check is that you are declaring resources correctly in the Admin file:

```
# this is correct
resource_classes = [YourResource]

# this is not correct
resource_class = YourResource
```

In the latter case, we have seen that this can cause issues.

**Comment by OttoAndrey** [comment]
@matthewhegarty Sorry for late answer.

> When we have seen this before it is because there is a custom field type (i.e. from a third party app) which is being identified as a CharField or subclass, but then is not being created with the correct Widget type.

You are right. Before v4 we added own `CharWidget` where replace `None` by empty strings.

Our solution:
```python
class CharWidget(Widget):
    """Widget for converting text fields."""

    def clean(
        self,
        value: str | None,
        row: None = None,
        *args,
        **kwargs,
    ) -> str:
        """Return empty string for values which is None.

        Since CharField can only be blank, when importing, it needs to be
        convert none to an empty string.

        """
        value = super().clean(value, row, *args, **kwargs)

        return "" if value is None else value
```

But now as I can see it works out of the box: [docstring](https://github.com/django-import-export/django-import-export/blame/33da17a908b337e4b4ab8de4717b6431b9894815/import_export/widgets.py#L169) and [code](https://github.com/django-import-export/django-import-export/blame/33da17a908b337e4b4ab8de4717b6431b9894815/import_export/widgets.py#L181)

So I think we can just remove this part of code. Thank you for help!

**Comment by matthewhegarty** [comment]
Great - thanks for confirming.
