### ISSUE TITLE
How to  explicitly disable and enable bulk import?

### ISSUE THREAD

**Issue by shimachao** [django-import-export/django-import-export#1847]
Because I hooked model.save method in my project, I want to explicitly disable bulk import

**Comment by matthewhegarty** [comment]
Hi
bulk import is enabled using [this flag](https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.options.ResourceOptions.use_bulk).  It is disabled by default, so unless you explicitly set this flag, there will be no bulk import.
HTH
