### ISSUE TITLE
Error in import FloatField

### ISSUE THREAD

**Issue by pandye** [django-import-export/django-import-export#185]
Hi, 
I am using a FloatField in my model :
               purchase_price = models.FloatField(null=True, blank=True)

When I import csv file with blank value, it throws an error : 
             ValueError: could not convert string to float:

**Comment by manelclos** [comment]
Hi @pandye, I know this is an old issue. There have been recent changes recently to float importing. Can you please check latest version in github?

**Comment by Braintelligence** [comment]
This is strange, it doesn't work with JSONs that I export from django-import-export but the JSONs that I exported from phpmyadmin did work.

The only difference I could find was that the id value wasn't escaped by these "".
phpmyadmin escaped all values.

**Comment by Braintelligence** [comment]
Hah! Changing the way django-import-export handles the output of the export made the import work again.
You have to enforce parentheses for ALL values, this is especially true for ids and foreignkey ids.

I did it like this:
    id = fields.Field(attribute='id')

**Comment by Braintelligence** [comment]
Using this #284 (the FloatWidget solution) worked!
