### ISSUE TITLE
Setting a string value to None stopped preserving existing data in v4

### ISSUE THREAD

**Issue by adamchainz** [django-import-export/django-import-export#1855]
**Describe the bug**

On django-import-export v3, modifying the incoming dataset to use `None` for values would prevent those values from overwriting existing data. This changed in v4.

**To Reproduce**

Take this model:

```python
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200)
```

And this resource:

```python
from import_export.resources import ModelResource


class BookResource(ModelResource):
    class Meta:
        model = Book
        fields = ("title", "subtitle")
        import_id_fields = ("title",)

    def before_import_row(self, row, *args, **kwargs):
        if not row['subtitle'].strip():
            row['subtitle'] = None
```

Do this setup:

```python
Book.objects.all().delete()
book = Book.objects.create(title="Frankenstein", subtitle="The Modern Prometheus")
```

Then import some data:

```python
dataset = Dataset(
    ("Frankenstein", ""),
    headers=("title", "subtitle"),
)

BookResource().import_data(dataset)
```

Load the data from the database and check `subtitle`:

```python
book.refresh_from_db()
print(book.subtitle)
```

On django-import-export v3, you’ll see `The Modern Prometheus` was preserved. On v4, it’s erased and replaced with the empty string.

**Versions (please complete the following information):**

- Django Import Export: 4.0.5, but exact commit bisected, see below
- Python 3.12
- Django 5.0

I wrapped the above in a test script and ran `git bisect` and found the commit that introduced this change was #1657, “Standardize widget `render()`”.

<details>

<summary><strong>Bisect details</strong></summary>

Test Python script:

```python
from tablib import Dataset
from import_export.resources import ModelResource

from example.models import Book


Book.objects.all().delete()
book = Book.objects.create(title="Frankenstein", subtitle="The Modern Prometheus")


class BookResource(ModelResource):
    class Meta:
        model = Book
        fields = ("title", "subtitle")
        import_id_fields = ("title",)

    def before_import_row(self, row, *args, **kwargs):
        if not row['subtitle'].strip():
            row['subtitle'] = None


dataset = Dataset(
    ("Frankenstein", ""),
    headers=("title", "subtitle"),
)

BookResource().import_data(dataset)

book.refresh_from_db()
if book.subtitle == "The Modern Prometheus":
    print("👍 preserved")
    raise SystemExit(0)
else:
    print("👎 overwritten")
    raise SystemExit(1)
```

Wrapper shell script:

```sh
#!/bin/sh
cd ~/tmp/import-export-bug || exit
.venv/bin/python manage.py shell -c 'import test'
```

Git bisect session:

```console
$ git bisect start
status: waiting for both good and bad commits

$ git bisect old d51d1bf
status: waiting for bad commit, 1 good commit known

$ git bisect new release-4
Bisecting: 106 revisions left to test after this (roughly 7 steps)
[e3e9fea9159b2725977224ee3d5d8b5d77a644d1] added deprecation catch

$ git bisect run ./test.sh
running './test.sh'
👎 overwritten
Bisecting: 53 revisions left to test after this (roughly 6 steps)
[dc354ef660ec67b1a4260c25d2697170dec2bd77] Document best practice for concurrent writes (#1668)
running './test.sh'
👎 overwritten
Bisecting: 26 revisions left to test after this (roughly 5 steps)
[421d3b406422d3ae42be7f6baa64f997febf95ba] Refactor to standardise method args (#1641)
running './test.sh'
👍 preserved
Bisecting: 13 revisions left to test after this (roughly 4 steps)
[edd53085f355145d7a94146e0e544695a5885ff7] Updated the list of authors (#1661)
running './test.sh'
👍 preserved
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[98a0529d1d1df989af9a7827f62eaec715ec7c87] refactored test_admin_integration.py (#1662)
running './test.sh'
👎 overwritten
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[bc14f5c1c7f08d9f3f4917fea21e53fce2890141] Improve validation documentation (#1665)
running './test.sh'
👎 overwritten
Bisecting: 0 revisions left to test after this (roughly 1 step)
[3f41d37bf640b84cb86d61877e9a714a65e70300] Standardize widget `render()` (#1657)
running './test.sh'
👎 overwritten
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[9c8684e278ab48ec1480adaf053f22931eb98aee] Add logging for missing fields & attributes (#1664)
running './test.sh'
👍 preserved
3f41d37bf640b84cb86d61877e9a714a65e70300 is the first new commit
commit 3f41d37bf640b84cb86d61877e9a714a65e70300
Author: Matt Hegarty <matthewhegarty@users.noreply.github.com>
Date:   Tue Oct 24 21:11:03 2023 +0100

    Standardize widget `render()` (#1657)
...
bisect found first bad commit
```

</details>

**Expected behavior**

Using this `None` replacement strategy should continue to work on v4. It’s not a clear implication of the widget change, and afaict there’s no clear alternative.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by adamchainz** [comment]
I’ve figured out the cause is the changed default of `CharWidget.allow_blank`: https://github.com/django-import-export/django-import-export/pull/1657/files#diff-aa9ae935765c98769d83f48338b922e200b52973464339783022fff958eb2abaR131 .

Replacing the default widget with one that allows blank fixes the issue:

```diff
 class BookResource(ModelResource):
+    subtitle = Field(widget=CharWidget(allow_blank=False))
  
     class Meta:
```

The changelog note and release note don’t cover this change, or its implications. Perhaps it wasn’t really done so deliberately?

**Comment by adamchainz** [comment]
Scratch that, the above comment was mistaken - it didn’t save anything because the defined `subtitle` field had no attribute. Setting the attribute reproduces the issue:

```python
 class BookResource(ModelResource):
+    subtitle = Field(attribute="subtitle", widget=CharWidget(allow_blank=False))

     class Meta:
```

It looks like actually I made a whole mistake simplifying this bug from production code. I forgot to include `raise_errors=True` to `import_data()` to check for exceptions. When I add that:

```diff
-BookResource().import_data(dataset)
+BookResource().import_data(dataset, raise_errors=True)
```

...the import **crashes** on v3:

```console
$ ./test.sh
Traceback (most recent call last):
  ...
django.db.utils.IntegrityError: NOT NULL constraint failed: example_book.subtitle
```

But it still overwrites on v4, because `''` is returned instead, which is a valid value.

(I need to dig into the client project to figure out if/how the “replace with `None`” behaviour was preserving existing data. I didn’t see `Field.saves_null_values` being set, but that seems to be the switch.)

**Comment by matthewhegarty** [comment]
Thanks for taking the time to raise this and investigate.  I'll take a look soon and see what I can uncover.

**Comment by adamchainz** [comment]
I had a further look, and it seems like `None` was never actually preserving existing data. So my report really boils down to: “`CharWidget` returns ``''`` when `None` is explicitly set in the dataset”. I am not sure that’s something you want to change, and I can certainly work with it on my side.

**Comment by matthewhegarty** [comment]
Hi Adam
Thanks for looking into this, I appreciate your time and input. 

It sounds like it was an issue which used to come up now and then, and is mentioned in the [FAQ](https://django-import-export.readthedocs.io/en/latest/faq.html#not-null-constraint-fails-when-importing-blank-charfield).  

There is a thread [here](https://github.com/django-import-export/django-import-export/issues/1485) which discusses the issue in detail.  In v4 we added some logic to try to set the widget params based on the definition of the `CharField`, which likely accounts for the changes you are seeing.

The [release notes](https://django-import-export.readthedocs.io/en/latest/release_notes.html#charwidget) do mention this, but I admit that it is vague and doesn't describe the implications in detail.

Just thinking, if you want to prevent a column from being updated, you could remove it from the row in one of the `before_import*` methods, though I haven't tried it.

**Comment by adamchainz** [comment]
> The [release notes](https://django-import-export.readthedocs.io/en/latest/release_notes.html#charwidget) do mention this, but I admit that it is vague and doesn't describe the implications in detail.

Yeah, maybe the best action is only to expand that description a bit.

> Just thinking, if you want to prevent a column from being updated, you could remove it from the row in one of the `before_import*` methods, though I haven't tried it.

Yeah, that is checked for at this step:

https://github.com/django-import-export/django-import-export/blob/891a87889c434a5f651706b611ab1728ef40d883/import_export/resources.py#L425-L430
