### ISSUE TITLE
Import field (source) x field (target) selectively

### ISSUE THREAD

**Issue by sunjoomoon** [django-import-export/django-import-export#186]
Any way to match source field to target field selectively when importing? and only those matched fields are imported.

**Comment by sunjoomoon** [comment]
Thanks for the note. For below case, using admin integration method, currently there is any way to do selective column matching ? If above 'api_fields.html' method is the one, can I have a real example using below case? 

source json with  "id, name, email, note" fields
target model with  "name, home_email, office_phone, memo"

**Comment by manelclos** [comment]
Hi @sunjoomoon, see example here:
https://django-import-export.readthedocs.org/en/latest/getting_started.html#declaring-fields

**Comment by manelclos** [comment]
Hi @sunjoomoon, the admin selective column matching is not currently possible. In the future it may be possible to use you own form for preview/import. About the fields matching, the answer should be already answered. Please reopen if necessary.
