### ISSUE TITLE
One Click Export

### ISSUE THREAD

**Issue by mscout1** [django-import-export/django-import-export#1866]
Hello, 

Our needs include "one click" export. For this particular model, all of the field and format specification will be the same every time.  
The users will not want to click through an extra form to get their file. 

Is there a good way to make the export button just download the file, no choices? 

If not consider this feature request.

**Comment by matthewhegarty** [comment]
> Is there a good way to make the export button just download the file, no choices?

Not at present.  There is a workaround but it is a bit clunky.  If you set [`IMPORT_EXPORT_SKIP_ADMIN_ACTION_EXPORT_UI `](https://django-import-export.readthedocs.io/en/latest/installation.html#import-export-skip-admin-action-export-ui), then it will do a one-click export but only if you export from the [action menu](https://django-import-export.readthedocs.io/en/latest/admin_integration.html#exporting-via-admin-action):

![image](https://github.com/django-import-export/django-import-export/assets/6249838/cf0c2b31-111a-4af7-9d8b-048913b8aea2)

Other users have requested this feature, so we will look to add it as soon as we can (PRs [welcome](https://django-import-export.readthedocs.io/en/latest/contributing.html#guidelines-for-contributing-code)).  lmk if you want to submit a PR so we can discuss the approach and ensure we don't duplicate effort.

**Comment by matthewhegarty** [comment]
This should be fairly straightforward, leave it with me.

**Comment by mscout1** [comment]
Thank you for the swift response. 

It looks like this will meet my needs. 

However as a side note, I will say that I first looked for this feature as a flag on the resource or admin. And I would anticipate that people might want it be be different for different models. (For example I am using this for 2 too 3 different models, for different reasons and for different audiences. In my case, I can tell the developers how it's gonna be, if I make the marketers happy, so a global switch works acceptably.) 

 It would be nice if it was configurable as an admin attr some day.
