### ISSUE TITLE
Overriding `formats`, `export_formats`, `import_formats` not documented. 

### ISSUE THREAD

**Issue by mscout1** [django-import-export/django-import-export#1868]
I wanted to restrict valid formats differently for different models.

By examining the code I discovered that I could set `formats`, `export_formats`, or `import_formats` as attrs on the admin to control the allowed formats. 

This is not documented. 

I am not sure if this was an intended feature, but it is useful enough that I recommend it be promoted to such, and documented.

**Comment by matthewhegarty** [comment]
Thanks for raising this.  There is some documentation on this [here][1] but it looks like we missed documentation for setting values directly on the admin.  I'll get that added in.

[1]: https://django-import-export.readthedocs.io/en/latest/installation.html#import-export-formats
