### ISSUE TITLE
unexpected keyword argument 'search_help_text'

### ISSUE THREAD

**Issue by jgrewal1991** [django-import-export/django-import-export#1871]
**Describe the bug**
When I try to export from django admin, I get error:
`__init__() got an unexpected keyword argument 'search_help_text'`

**To Reproduce**
1. Go to model admin list view
2. Click on click on export.
3. Scroll down to select format and select CSV format
4. Click on Submit and try to generate report.

**Versions (please complete the following information):**
 - Django Import Export: 4.0.7
 - Python : 3.8.10
 - Django : 3.2.18

**Expected behavior**
Report should be downloaded

**Screenshots**

<img width="1596" alt="Screenshot 2024-06-11 at 10 09 33 AM" src="https://github.com/django-import-export/django-import-export/assets/64787963/8e504e4b-8f7b-4790-92f7-07d36420be8e">

**Additional context**

**Comment by matthewhegarty** [comment]
Thanks for reporting.  Django 3.2 has passed [end of life](https://endoflife.date/django) and is no longer supported.  The next supported version is 4.2.  Can you upgrade and see if you can reproduce the issue?
