### ISSUE TITLE
Export contains "None" instead of ""

### ISSUE THREAD

**Issue by CharString** [django-import-export/django-import-export#1872]
**Describe the bug**

The default Field using the default Widget exports `"None"` instead of `""`
https://django-import-export.readthedocs.io/en/4.0.8/api_widgets.html#import_export.widgets.Widget

**To Reproduce**

This test fails:

```diff
diff --git a/tests/core/tests/test_fields.py b/tests/core/tests/test_fields.py
index 4a1f31d..f56159b 100644
--- a/tests/core/tests/test_fields.py
+++ b/tests/core/tests/test_fields.py
@@ -35,6 +35,10 @@ class FieldTest(TestCase):
     def test_export(self):
         self.assertEqual(self.field.export(self.obj), self.row["name"])
 
+    def test_export_none(self):
+        instance = Obj(name=None)
+        self.assertEqual(self.field.export(instance), "")
+
     def test_save(self):
         self.row["name"] = "foo"
         self.field.save(self.obj, self.row)
```

**Versions (please complete the following information):**
 - Django Import Export: 4.0.8
 - Python 3.12
 - Django 4.2

**Additional context**
The bug was introduced here:
https://github.com/django-import-export/django-import-export/commit/6db364bf1943309ce90228b92fea2d0efd22522b#diff-b3aa0a5a7d01d69048e8dc4f5aefd05151be3b01508e00335f3f0d45334bfd26R143

Either `Widget.render` should be changed accordingly, or `Field.export` should return `""` again.

**Comment by matthewhegarty** [comment]
Thanks for raising this.  I'll take a look.
