### ISSUE TITLE
Display checkbox before field label in export form for alignment

### ISSUE THREAD

**Issue by RenDelaCruz** [django-import-export/django-import-export#1873]
Is it possible to render the `BooleanField` checkbox before the field labels in the export form? This way, the checkboxes would always be aligned no matter the length of the field name, which is more expected for multi-select forms.

Would be happy to submit a PR if this enhancement is accepted.

| Current | New |
| --- | --- |
| ![Screenshot 2024-06-17 at 9 52 44 PM](https://github.com/django-import-export/django-import-export/assets/55041697/8c01f036-344a-455c-8bc4-94453a498c02)  | ![Screenshot 2024-06-17 at 9 50 12 PM](https://github.com/django-import-export/django-import-export/assets/55041697/baf8d41a-5127-4605-88ca-0c3ae8278c26) |

**Comment by matthewhegarty** [comment]
Hi - thanks for suggesting this - if you could submit a PR that would be appreciated.
