### ISSUE TITLE
Change to Resource.import_field broke my resources

### ISSUE THREAD

**Issue by adamchainz** [django-import-export/django-import-export#1874]
**Describe the bug**

PR #1861 dropped this block:

https://github.com/django-import-export/django-import-export/blob/5faa0115ad05ebe32cc46441d929213771438a99/import_export/resources.py#L422-L424

The project I’m working on had some resources with fields based on reading model properties. The django-import-export fields for those properties deliberately didn't set `attribute`, so that the import process wouldn't try to set them, but they could still be read during export through a custom `dehydrate` method.

The behaviour change from #1861 broke those resources, making them now raise exceptions like: `AttributeError: property 'title' of 'Book' object has no setter`.

I think this change was too drastic for a bug fix, and the release notes don’t really point to this fairly large behaviour change. I am not confident that my tests cover all the cases for such fields.

Perhaps this change could be undone?

In the mean time, I will work around by setting `attribute` for those fields, but modifying `import_row` to drop them from incoming data.

**To Reproduce**
see above

**Versions (please complete the following information):**
 - Django Import Export: 4.0.7+
 - Python 3.11
 - Django 4.2

**Expected behavior**
see above

**Screenshots**
n/a

**Additional context**
n/a

**Comment by matthewhegarty** [comment]
Thanks for raising.  I'm understanding that you have declared your resources similar to [this example](https://github.com/django-import-export/django-import-export/issues/1846#issue-2306290283) where you have declared fields, but with no attribute so that they are not set on the model during import, but you can still export those fields.  Is that correct?

**Comment by adamchainz** [comment]
Yes.

**Comment by matthewhegarty** [comment]
ok thanks, I'll take a look.

**Comment by matthewhegarty** [comment]
I've reverted the change from #1861 in #1874.  If you could check this over and confirm it would solve the issue for you I would appreciate it.

**Comment by adamchainz** [comment]
Thank you for the swift action. I just tested the new version on my project, and the issue is fixed.
