### ISSUE TITLE
delete field and skip_field = False do not seem to work together

### ISSUE THREAD

**Issue by FerranPalmaC** [django-import-export/django-import-export#1875]
I have a Django model that I want to import from the admin panel. 

Everything works fine without the delete field. Here is my resource code:

```
class DeviceResource(resources.ModelResource):
    def before_import(self, dataset, **kwargs):
        # Some logic to raise errors

    class Meta:
        model = Device
        name = _("Create devices by importing a CSV")
        exclude = (
            "id",
            "created",
            "modified",
            "created_icinga",
        )
        import_id_fields = ("hostname",)

```

In the `DeviceAdmin` class, I specify the resource:

```
@admin.register(Device)
class DeviceAdmin(ImportMixin, admin.ModelAdmin):
    # Some other fields
    resource_classes = [DeviceResource]

    def get_readonly_fields(self, request, obj=None):
        return ["hostname"] if obj else []

    class Meta:
        model = Device
```

Up to this point, everything works as expected. The problem comes when I add the delete field. Following the documentation, I add this lines to the `DeviceResource`:

```
    delete = fields.Field(widget=widgets.BooleanWidget())

    def for_delete(self, row, instance):
        return self.fields["delete"].clean(row)

```

And I include the delete header in the CSV. This setup allows me to delete devices, but issues occur when creating new devices. If the delete field is set to 0 in the CSV (or 1, which doesn't solve the problem), I get this error for each new device:

    - Line number: N - Device object can't be deleted because its id attribute is set to None.

Obviously, if I'm creating the device it's id attribute is None, moreover, I'm not trying to delete the device, the delete field in the CSV is set to 0, so I shouldn't get this error in any case.

If I set `skip_diff = True` in the `DeviceResource` Meta class the error goes away and everything works again, but I want to see the differences so I do not want to set `skip_diff` to True.

I think I can understand why the problem is happening, and actually the [documentation](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#create-or-update-model-instances) states something about this. 

However, I do not think this applies to my case because `hostname` uniquely identifies a Device instance.

Do I have to decide between having the delete option or using `skip_diff`? It makes no sense to me.

I don't have any idea of how to solve this problem, so any help is appreciated.

**Comment by matthewhegarty** [comment]
If I understand your issue, you want to have a column in the import CSV called "delete" which if set to '1' will delete the row.  The underlying row may or may not be in the database.

The code which handles the delete is [here][1].  We can see that we have to override `for_delete()` to return a boolean to say whether the delete should occur.  The documentation gives us an [example][2] of how to do this:

```python
        def for_delete(self, row, instance):
            return self.fields['delete'].clean(row)
```

However, I think this example is not clear.  This says that if there is a declared field called 'delete', and it has a non null value, then perform the delete.

Perhaps the best way for your issue would be to declare as follows:

```python
    def for_delete(self, row, instance):
        return row.get("delete") == "1"
```

Obviously this is simpler and should work for your use case.

btw you can ignore `skip_diff` this field is only for performance improvements when importing programatically and you don't want the Admin UI checks to run.

[1]: https://github.com/django-import-export/django-import-export/blob/37a73a1dd65387a7d0ab2cb4a3dd32562fd8769a/import_export/resources.py#L732

[2]: https://django-import-export.readthedocs.io/en/latest/getting_started.html#deleting-data

**Comment by FerranPalmaC** [comment]
It seems to work like a charm with your solution and not using the delete field.

Thank you very much. I close the issue.
