### ISSUE TITLE
multi column foreign key

### ISSUE THREAD

**Issue by eskhool** [django-import-export/django-import-export#188]
It should be pretty straightforward to have multiple column based Foreign Key lookup. I can easily make the change and submit a pull request. Any particular way we should take the multiple columns in the Foreign Key Widget in the Field in the Resource definition?

**Comment by manelclos** [comment]
Hi @eskhool, what do you want to accomplish by having multiple fields in the Foreign Key? In Django itself this is not supported. How is this different to issue #189?

**Comment by eskhool** [comment]
Idea is to lookup a FK using more than one field for example if I am loading data in Model A with a foreign key to Model B and I want to identify model B using multiple fields B.fielda and B.fieldb. Am I missing how to do this?

**Comment by manelclos** [comment]
It looks to me this is something very specialised, you can always do it with a custom format.

**Comment by suriya** [comment]
I have a similar requirement as well. Until recently, I have been using my own CSV import code. However, I want to move to a library that is better supported and used by others. I came across django-import-export and I see that it does not support looking up ForeignKey objects with multiple lookup fields.

A classic example would be looking up a person by `first_name` and `last_name` fields. @manelclos suggestion of using a custom format works. We could have a `name` field and split its values and do a lookup. It is obvious that this could break based if the `last_name` has a space in it.

**Comment by int-ua** [comment]
It could have been solved relatively easily if there was a way to access other row values from a Widget. Is there a feature request for this? I can't find it.
