### ISSUE TITLE
resource base class to skip rows matching unique_together criteria

### ISSUE THREAD

**Issue by eskhool** [django-import-export/django-import-export#189]
It seems to make sense in many situations to auto skip rows (using the skip_row method) for those instances where the unique_together fields are already present (instead of letting the database throw a unique index exception). This can be a UniqueModelResource class which has the skip_row function introspecting the unique_together field for that model. Would a pull request for this make sense?

**Comment by Wirzi** [comment]
Yes i think so! +1

**Comment by manelclos** [comment]
Hi @eskhool, I think that settings ``import_id_fields`` to the unique_together fields will do just that. Then you are only missing ``skip_unchanged`` set to True. Is that a solution?

https://django-import-export.readthedocs.org/en/latest/getting_started.html#customize-resource-options

**Comment by eskhool** [comment]
It defeats DRY which is a strong Django cornerstone. It would make sense to do this by default or have a resource sub-class which does automatically (to pick up the unique together criteria) and let the override change that no?

**Comment by manelclos** [comment]
Yes, setting ``import_id_fields`` automatically to the unique together criteria would be nice. I agree that is what I would expect, import-export picking all the django model configuration. PR welcome.

**Comment by shouldsee** [comment]
It took me several hours to figure out how to adapt to `unique_together`. The general scenario is the unqiued fields serve as a pseudo-index, therefore we should suppress "id" automatically in these cases. 

#257 #375
