### ISSUE TITLE
Importing AND displaying related models at importing preview

### ISSUE THREAD

**Issue by hector-macias1** [django-import-export/django-import-export#1891]
I have this Course model (also look at the many to many fields):

```
class Course(models.Model):

    class Meta:
        unique_together = ('name', 'year', 'semester')

    name = models.CharField(primary_key=True, max_length=250, null=False, blank=False)
    year = models.IntegerField(null=False)
    semester = models.IntegerField(null=False)
    active = models.BooleanField(default=True)

    _students = models.ManyToManyField(to=User, blank=True)
    _teachers = models.ManyToManyField(to=User, blank=False, related_name='courses_teacher')

    def add_teacher(self, teacher: 'Teacher'):
        self._teachers.add(teacher)

    def add_student(self, user: 'User'):
        self._students.add(user)
```

For extracting the students from an excel sheet (which has a horrific format) I used this custom resource model:

```
class StudentResource(resources.ModelResource):
    username = Field(attribute='username', column_name='STUDENT_ID')
    first_name = Field(attribute='first_name', column_name='NAME')

    class Meta:
        model = User
        skip_unchanged = True
        report_skipped = False
        import_id_fields = ('username',)
        fields = ('STUDENT_ID', 'NAME')

    def import_data(self, dataset, **kwargs):
        """
        clean data from the list, only extract students
        """
        subsection = dataset[23:len(dataset) - 4]

        data = tablib.Dataset()

        # distribute data for students
        data.headers = ['NAME', 'STUDENT_ID']
        for i in subsection:
            data.append([i[1], str(i[8])])

        cleaned_data = data
        return super().import_data(cleaned_data, **kwargs)

    def after_save_instance(self, instance, row, **kwargs):
        print(instance)
        # distribute data for students
        group, _ = Student.create_group()
        group.user_set.add(instance)
```

As you can see, in import_data() I'm only extracting students from the sheet. 

Is there a way to extract and display other data (which would be for other models) from the same excel sheet in the import preview? 

In this case in particular, I would also need to extract other data from the dataset. Something like, let's say `course_name= data[13][3]` or `teacher_name= data[17][3]`. Currently I'm running out of ideas, since the overwritten import_data method returns the super method (which only receives a single dataset as a parameter). 

If there's a way to do this, would it be possible to display multiple models at the preview?

**Comment by matthewhegarty** [comment]
This is a tricky issue since import_export is built around working with a single dataset.  Others have worked around this by using JSON in certain fields as a mechanism for supporting nested data.  

You can read through [this thread](https://github.com/django-import-export/django-import-export/issues/445) for some further background and ideas.

> If there's a way to do this, would it be possible to display multiple models at the preview?

It's not possible with the current framework, but you could try to customize.  I think it will be tricky though.
