### ISSUE TITLE
Widget ManyToManyWidget cannot find m2m connections

### ISSUE THREAD

**Issue by honnisha** [django-import-export/django-import-export#1895]
**Describe the bug**
Widget ManyToManyWidget cannot find and creat3e m2m connections

**To Reproduce**
```
class FactResource(resources.ModelResource):
    tags = fields.Field(attribute='tags', widget=ManyToManyWidget(Tag, field='name', separator=','))

    class Meta:
        model = Fact
```

With default ManyToManyWidget qs filter is: `{'name__in': <filter object at 0x79f0827dba60>}`

With this option, everything works:
```
class CustomManyToManyWidget(ManyToManyWidget):
    def clean(self, value, row=None, **kwargs):
        if not value:
            return self.model.objects.none()
        if isinstance(value, (float, int)):
            ids = [int(value)]
        else:
            ids = value.split(self.separator)
            ids = [i.strip() for i in ids if i is not None]
        return = self.model.objects.filter(**{"%s__in" % self.field: ids})
```

Is this a bug or am I doing something wrong?

**Versions (please complete the following information):**
 - Django Import Export: 3.7.4
 - Python 3.10
 - Django 4.2

**Comment by matthewhegarty** [comment]
Can you provide a failing test case or steps to reproduce with the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?

**Comment by honnisha** [comment]
I double-checked, it must have been something else. It's not reproducing. Thank you!
