### ISSUE TITLE
Ability to add multiple custom exports to ModelAdmin

### ISSUE THREAD

**Issue by kitsunde** [django-import-export/django-import-export#19]
I would like to be able to export different datasets. I currently have this for exporting a model and related data:

```
class GameAdmin(ExportMixin, admin.ModelAdmin):
    resource_class = GameResource
    # ...
```

However Games also have Levels, what I would like is having a mechanism to add multiple custom exports similar to how https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter works:

```
class GameAdmin(ExportMixin, admin.ModelAdmin):
    resource_class = [LevelsResource, GameResource]
    # ...
```

Which would let me export Level data.

**Comment by JyothiVutukuri** [comment]
I think, this issue has to reopen
I am using django import and export in django admin

But we want multiple types of export for the same model
Eg. We have investors model
We want exports like
1.  Investors data for issuing shares
2. Investors data for compliance data with different fields
3. Founders to see investors with invested project.

**Comment by ton77v** [comment]
having an option to use multiple resource classes will be very handy

I have models with various M2M relationships and sometimes can get export data for only some of those without a need 2 touch the rest

it's all doable using export first, etc etc but would be much easier to choose the resource class when you need to update just some (sets) of the data
