### ISSUE TITLE
SyntaxError during installation

### ISSUE THREAD

**Issue by epalm** [django-import-export/django-import-export#190]
See http://stackoverflow.com/questions/27553414/pip-install-django-import-export-raises-syntaxerror

Apparently this has something to do with tablib and Python 2.x vs Python 3.x.

The readme https://github.com/bmihelac/django-import-export/blob/master/README.rst indicates that the requirements are "Python 2.7+ or Python 3.3+".  I would assume that If tablib doesn't support Python 2.7+, and django-import-export required tablib, then django-import-export should also not support Python 2.7.x?

**Comment by bmihelac** [comment]
I'm closing this, please reopen if needed.
