### ISSUE TITLE
Hide resource field when only one resource?

### ISSUE THREAD

**Issue by adamchainz** [django-import-export/django-import-export#1908]
#1671 added support for multiple resource classes and adjusted `ImportExportFormBase` to show the resource field as read-only when there is only one resource class, rather than hiding it by deleting it. But this field field doesn’t make sense to most users when read-only. By default, a resource’s display name is its class name, so the import and export pages just have an extra row with something like “resource: BookResource”.

As part of rolling out the v4 upgrade, my clients requested hiding the field. I’ve found this can be done with a custom form class:

```python
from django import forms
from import_export import forms as ie_forms


class HideResourceField(ie_forms.ImportExportFormBase):
    """
    Form mixin to hide the “resource” field when there’s only one option, as
    it doesn’t make any sense to users.
    """
    def _init_resources(self, resources):
        """
        After super method adjusts the field and widget, replace the widget
        with a HiddenInput.
        """
        super()._init_resources(resources)
        if len(resources) == 1:
            self.fields["resource"].widget = forms.HiddenInput()


class ImportForm(HideResourceField, ie_forms.ImportForm):
    pass


class ExportForm(HideResourceField, ie_forms.ExportForm):
    pass
```

I think this could be making the default behaviour. It will be less confusing for the common case of a single resource (especially without a meaningful display name).

**Comment by matthewhegarty** [comment]
Hi Adam, thanks for submitting this.  I think it is reasonable and I can't see a reason why it cannot be the default behaviour.  I'll consider it for the next milestone release, and include docs as to how to preserve the existing behaviour, should anyone wish to do so.
