### ISSUE TITLE
`test_import.py` module is large and can be broken up into smaller modules

### ISSUE THREAD

**Issue by matthewhegarty** [django-import-export/django-import-export#1909]
`tests/admin_integration/test_import.py` is now over 1k lines and should be broken up into smaller test modules.

Also

- look at adding helpers to remove code duplication
- Refer to URLs using constants in `admin_integration/mixins.py` rather than magic strings

**Comment by dahvo** [comment]
Hello! I am starting on this, it will be my first contribution.
