### ISSUE TITLE
`import_id_fields` as foreign key shows Update instead of New

### ISSUE THREAD

**Issue by Jwiggiff** [django-import-export/django-import-export#1922]
**Describe the bug**
I am using the admin interface to import a bunch of Users/UserProfiles. I am using `UserProfile` as my model, and when I set `import_id_fields` to a field on the `User` model instead, it thinks every row is an update even though it creates a new record instead.

**To Reproduce**
I have a resource defined as so:
```
class UserProfileResource(resources.ModelResource):
    email = fields.Field(
        attribute="user",
        column_name="email",
        widget=ForeignKeyWidget(User, "username"),
    )
    first_name = fields.Field(
        attribute="user",
        column_name="first_name",
        widget=ForeignKeyWidget(User, "first_name"),
    )
    last_name = fields.Field(
        attribute="user",
        column_name="last_name",
        widget=ForeignKeyWidget(User, "last_name"),
    )

    def before_import_row(self, row, **kwargs):
        print(row, flush=True)
        email, first_name, last_name = row["email"], row["first_name"], row["last_name"]
        user, created = User.objects.get_or_create(username=email)
        user.email = email
        user.first_name = first_name
        user.last_name = last_name
        user.save()

    class Meta:
        model = UserProfile
        fields = [
            "email",
            "first_name",
            "last_name",
            "phone_number",
        ]
        import_id_fields = ["email"]
```

Where `UserProfile` has a `OneToOne` relation to `User`. When I import, it shows every row is an Update even though no user exists with the specified email in the row, and when I complete the import a new record is created.

**Versions (please complete the following information):**
 - Django Import Export: 4.1.1
 - Python 3.12.3
 - Django 5.0.6

**Expected behavior**
If no user exists with the specified email, it should show as a New entry.

**Screenshots**
![image](https://github.com/user-attachments/assets/4961bbef-1f3b-44ae-b09e-229e96462a34)

**Comment by matthewhegarty** [comment]
Here is the line which looks up existing rows:

https://github.com/django-import-export/django-import-export/blob/27d2739e9c0784e8211c98ca8f01175df0f97ef4/import_export/instance_loaders.py#L31)

Based on your code snippet, I expect that this would exec:

```python
UserProfile.objects.get(email=row["email'])
```

When you create the `User` object, I wouldn't expect that it would also create a `UserProfile` row.  So is there something else going on?  Have the `UserProfile` rows been created in a previous import?

> when I set `import_id_fields` to a field on the User model instead, it thinks every row is an update even though it creates a new record instead.

Note that you are creating the `User` instance in `before_import_row()` which runs before the instance lookup [logic](https://github.com/django-import-export/django-import-export/blob/27d2739e9c0784e8211c98ca8f01175df0f97ef4/import_export/resources.py#L722).  That means that the `User` object will always be present in the db, when the lookup happens, and it will be an Update not a Create.

If you want to use `User` as the import model, then you can remove `before_import_row()` (but then it will technically be a `UserResource` not a `UserProfileResource`).

So you'll have to pick one model for import, and then create associated data in `after_init_instance()` or similar.
