### ISSUE TITLE
Create m2m relations with existing data in the Database

### ISSUE THREAD

**Issue by hector-macias1** [django-import-export/django-import-export#1934]
So I have this model in Django:

```
class Course(models.Model):
    class Meta:
        unique_together = ('name', 'year', 'semester')

    name = models.CharField(primary_key=True, max_length=250, null=False, blank=False)
    year = models.IntegerField(null=False)
    semester = models.IntegerField(null=False)
    active = models.BooleanField(default=True)

    _articles = models.ManyToManyField(to='Article', blank=True)
    _students = models.ManyToManyField(to=User, blank=True)
    _teachers = models.ManyToManyField(to=User, blank=False, related_name='courses_taught')

    def students(self) -> QuerySet['User']:
        """
        Retrieves the list of students in the course.

        :returns: List of students in the course.
        """
        return self._students.all()

    def teachers(self) -> QuerySet['Teacher']:
        """
        Retrieves the list of teachers associated with the course.

        :returns: List of teachers associated with the course.
        """
        return self._teachers.all()

    def add_teacher(self, teacher: 'Teacher'):
        """
        Adds a teacher to the course.

        :param teacher: The teacher to be added.
        """
        self._teachers.add(teacher)

    def add_student(self, user: 'User'):
        """
        Adds a student to the course.

        :param user: The user to be added as a student.
        """
        self._students.add(user)

    def __str__(self):
        return f"{self.name} ({self.year}-{self.semester})"
```

Teachers and students are default Django users. Since the data for teachers, students and course come from the same .xls file (one file contains a course with it's teachers and students), I've decided to make custom resources for both teachers and students (using tablib to just import these two individually). 

Now that I'm creating the resource for course I'm facing the problem of making the manytomany relations between a course and it's corresponding teachers and students (which were previously imported and already exist in the DB).

I haven't really figured out how the manytomany widget works yet (from what I understand, you use the widget to import related data at the same time). I don't know if it would be possible to gather data from the DB and somehow append it with the dataset I'm building in the class resource.

What would be the correct approach for making the two manytomany relations with course using import-export? Considering I have the methods add_teacher() and add_students()

**Comment by matthewhegarty** [comment]
Best advice would be to download the example app and see how m2m fields are handled by default.  Reading source code and stepping through with breakpoints is the best way to understand how it fits together.

> I haven't really figured out how the manytomany widget works yet (from what I understand, you use the widget to import related data at the same time).

Yes, there are examples in the example app.  The example app uses the "Category" model as an example.  m2m fields can be updated using pipe delimited fields in csv, or in yaml, json etc.

>  I don't know if it would be possible to gather data from the DB and somehow append it with the dataset I'm building in the class resource.

Get a handle on how it's working in the example app already.  There are hooks you can use during the import process if you need to fine tune.
