### ISSUE TITLE
XLS not supported for importing

### ISSUE THREAD

**Issue by hector-macias1** [django-import-export/django-import-export#1945]
**Describe the bug**
I want to import data from an xls (2003) file. For that, I imported xlrd 2.0.1 and openpyxl 3.1.3. 
In the Import view, XLS is not recognized in the list of available formats. A couple of months ago it worked perfectly. I've checked dependencies versions, and as far as I can see in the version control of my project nothing has changed that would indicate me a problem related with dependencies.

Import Export version: 4.1.0
XLRD version: 2.0.1
Openpyxl version: 3.1.3

![import](https://github.com/user-attachments/assets/2ce965aa-cd02-467b-b256-fe0e013da7d2)
Notice there's no option for XLS

**Comment by matthewhegarty** [comment]
Do you have [`IMPORT_EXPORT_FORMATS`](https://django-import-export.readthedocs.io/en/latest/installation.html#import-export-formats) (or `IMPORT_FORMATS`) defined?  
Or have you set `import_formats` (or `formats`) on the Admin class?

Can you reproduce this in the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?
