### ISSUE TITLE
Import preview color

### ISSUE THREAD

**Issue by hector-macias1** [django-import-export/django-import-export#1951]
Every time I'm importing, the data preview gets me a different color every time.
![image](https://github.com/user-attachments/assets/b8fda931-7d07-450c-9a34-1ec12713cd12)

In this case was purple, which is unreadable. 
Is there a component to change the color of the preview table? Or at least get the original light green color it had?

**Comment by matthewhegarty** [comment]
I haven't seen this issue before - please can you tell me which versions you are using and ideally give me some steps to reproduce with the example app?
