### ISSUE TITLE
Exporting directly, without export form, doesn't respect admin filters

### ISSUE THREAD

**Issue by bjedovinfofactory** [django-import-export/django-import-export#1956]
**Describe the bug**
When you perform an export while having `skip_export_form = True` the filters that were applied on the admin aren't respected and **everything** gets exported.

**To Reproduce**
1. Set up `django-import-export` as per documentation
```py
# models.py
class Foo(models.Model):
    bar = models.CharField(...)

# admin.py
class FooResource(ModelResource):
    class Meta:
        model = models.Foo

@admin.register(models.Foo)
class FooAdmin(ExportMixin, admin.ModelAdmin):
    list_filter = ("bar",)
    resource_classes = [FooResource]
    skip_export_form = True
```
2. Go to admin
3. Filter by "bar"
4. Press "Export" button

Now everything gets exported, instead of just the ones filtered by "bar".

**Versions (please complete the following information):**
 - Django Import Export: 4.1.1
 - Python 3.12.1
 - Django 5.1.1

**Expected behavior**
The exported results should match what I see in the Django admin.

**Additional context**
My assumption is that it's caused by the fact that when you go through the export form the request is sent in `POST` while when you press the button it's a simple `GET` url. Didn't dig too deep into the library.

Note: issue persists also when using `ImportExportModelAdmin` instead of `ExportMixin`

**Comment by SergeiMinaev** [comment]
Confirm. Spent a lot of time before I realized what the reason was.

**Comment by matthewhegarty** [comment]
I could reproduce this in v4.1.1 but not in the `main` branch.  Can you try with `main` branch and confirm if the issue persists?

**Comment by bjedovinfofactory** [comment]
@matthewhegarty I apologize for taking this long to reply, I have tested the version on the `main` branch and it is indeed fixed. Thank you very much.
