### ISSUE TITLE
Import fails after confirming the action in Django Admin

### ISSUE THREAD

**Issue by yuriy65** [django-import-export/django-import-export#1957]
I am trying to use django-import-export 4.1.1 via Django Admin (Django 5.1.1) with a custom import form and default confirmation form. I can start importing from .xlsx file and see the expected preview, but after clicking **Confirm Import** button, a mystery error message appears. However, all work just fine if the import confirmation stage is skipped by setting **skip_import_confirm = True**
So far, I don’t know if it has something to do with my code or if there is a bug in the django-import-export app.

Error message
----------------------
![image](https://github.com/user-attachments/assets/b0926003-1e8f-447a-8cdc-5285e856e0a9)

model
--------
```
class AcademicGroupMember(models.Model):
    first_name = models.CharField(max_length=30, blank=False, default='', verbose_name=_('First Name'))
    middle_name = models.CharField(max_length=30, blank=False, default='', verbose_name=_('Middle Name'))
    last_name = models.CharField(max_length=30, blank=False, default='', verbose_name=_('Last Name'))
    sic = models.CharField(max_length=10, validators=[RegexValidator('^[А-Я]{2}\\d{8}$')], unique=True, blank=False,
                           default='', verbose_name=_('Student Identity Card'))
    academic_group = models.ForeignKey('AcademicGroup', on_delete=models.CASCADE, verbose_name=_('Academic Group'))
```
resource
------------
```
class MemberResource(resources.ModelResource):

    def __init__(self, **kwargs):
       super().__init__(**kwargs)

    def after_init_instance(self, instance, new, row, **kwargs):
        if 'academic_group' in kwargs:
            instance.academic_group = kwargs['academic_group']

    class Meta:
        model = AcademicGroupMember
        exclude = ('id',)
        import_id_fields = ('sic',)
        skip_unchanged = True
```       
My admin
--------------
```
@admin.register(AcademicGroupMember)
class MemberAdmin(ImportExportModelAdmin):
     
    resource_classes = [MemberResource]
    import_form_class = MemberImportForm
    import_export_formats = [XLS, XLSX]
    skip_import_confirm = False

  
    def get_import_data_kwargs(self, request, *args, **kwargs):
        form = kwargs.get("form", None)
        if form and hasattr(form, "cleaned_data"):
            kwargs.update({'academic_group': form.cleaned_data.get('academic_group', None)})
        return kwargs
```
Import Form
-----------------
```
class MemberImportForm(ImportForm):
    academic_group = forms.ModelChoiceField(queryset=AcademicGroup.objects.all(), required=True)
```

**Comment by Gunner245** [comment]
from the looks of the exception, this issue and #1958 have the same root cause.

**Comment by yuriy65** [comment]
Thanks

**Comment by urlsangel** [comment]
> This should be fixed in #1944 and is now in the main branch

Hi @matthewhegarty 👋 

Firstly, I've been using `django-import-export` for years - mainly to migrate data into Wagtail sites - so thanks for all your hard work, I couldn't do my job without you!

Re this issue, I've been working on a gnarly import script for a couple of months now - I've just upgraded Django from `4.2` -> `5.1`, and I'm now a bit blocked as it's failing for me with this same error.

It looks like this issue has been fixed and is in the main branch now - do you know if it will be available via `pypi` soon?

Thanks again 🙏

**Comment by matthewhegarty** [comment]
Hi Russell

Thanks for the kind words - always great to hear that the library is being used and helping people with their work.

The 4.2 release of django-import-export is almost ready so looking at a release in the next week hopefully, then it will be available via pypi - obviously you can pin your dependencies to the `main` branch which might unblock you in the short term?

**Comment by urlsangel** [comment]
Hey Matt

No worries, I did exactly that in `poetry` after messaging you this morning, so not blocked anymore! 🙏

**Comment by urlsangel** [comment]
Hi @matthewhegarty 

We released an update to our staging server yesterday, and now we have the dreaded [TemplateDoesNotExist](https://github.com/django-import-export/django-import-export/issues/548) issue, so this project is blocked from previewing unfortunately.

The git rev that we're has been running fine locally, and it appears to have been installed by pip/poetry correctly on the staging server, so I'm not sure what the issue is.

It looks like you're close to releasing 4.2 to pypi, do you have an idea of when that might be?

Thanks in advance!

Russell.

**Comment by matthewhegarty** [comment]
Hi Russell - we just have a couple of things left to go, so I'm going to aim for a full release in the next week 🤞 

However I have just released [`4.2.0-rc.0`](https://pypi.org/project/django-import-export/4.2.0rc0/) so maybe you can use this to try to unblock your issue.

**Comment by urlsangel** [comment]
Cheers @matthewhegarty, giving that a go now 👍 🙏😀

**Comment by urlsangel** [comment]
@matthewhegarty that worked, you are a lifesaver - thank you 🙏 🛟 😅

**Comment by yuriy65** [comment]
Hello @matthewhegarty ,

I have just tried django-import-export 4.2.0-rc.0 via Django Admin (Django 5.1.1)  with my previous source code unchanged. Now I can start importing from .xlsx file and see the expected preview, but after clicking **Confirm Import** button, 
no import results show apart from an OK message. And that doesn't depend on skip_unchanged value. However, all work just fine if the import confirmation stage is skipped by setting skip_import_confirm = True

By the way, format limiting like import_export_formats = [XLS, XLSX, ODS] doesn't work as expected. Instead, a list of all default formats is rendered.

Thank you so much for your attention and participation.
Yurii

**Comment by matthewhegarty** [comment]
@yuriy65 ok - I will take a look - it will save me time if you can confirm this occurs in the example app.

**Comment by yuriy65** [comment]
Hi @matthewhegarty <https://github.com/matthewhegarty>,

Thanks for your quick reply.

Sorry, what do you mean by "confirm this occurs in the example app"? Should
I send you the source code of the example app again (it is in a closed
issue, "Import fails after confirming the action in Django Admin #1957") or
just screenshots related to the current problem?

вс, 20 окт. 2024 г. в 19:24, Matt Hegarty ***@***.***>:

**Comment by matthewhegarty** [comment]
I just tried to reproduce this issue using [this description](https://github.com/django-import-export/django-import-export/issues/1957#issue-2545017341) in the main branch and django 5.1.1 in the example app and it worked fine, so unless I am missing something it could be an issue with your custom code.

Can you give me specific steps to reproduce in the example app?  Meaning that if I follow the steps I get the same issue as you.  I won't have time to try to reverse engineer your code samples, so if you could give me reproducible steps I might be able to help.

> format limiting like import_export_formats = [XLS, XLSX, ODS] doesn't work as expected.

I tested a declaration like this and it worked fine:

```python
IMPORT_EXPORT_FORMATS = [XLS]
```

![image](https://github.com/user-attachments/assets/becd2cdc-f746-4b32-a02c-90b369d8bd2a)

**Comment by yuriy65** [comment]
I will look into this again and get back to you.

As for IMPORT_EXPORT_FORMATS, I used this attribute not in settings.py but
via model admin, like in the last sentence of the screenshot attached.

**Comment by matthewhegarty** [comment]
> I used this attribute not in settings.py but via model admin

Ah - ok I understand.  This is an error in the docs.  It should be `formats` not `import_export_formats`.  I'll get that corrected.

**Comment by yuriy65** [comment]
Ok, thanks for the clarification.

**Comment by yuriy65** [comment]
The attachment provides a simplified example of the app in question. Import
works fine only with skip_import_confirm = True; otherwise, no data is
imported. Maybe I'm missing something.

The login and password to the admin site are the same: *admin*. import.csv
- file to import from.

пн, 21 окт. 2024 г. в 16:03, Yurii Parfonov ***@***.***>:

> Ok, thanks for the clarification.
>

**Comment by matthewhegarty** [comment]
There's no attachment, but I won't have time to look into it unless you can show me that it's a bug in import_export (i.e. give me steps to reproduce in the example app).

The best thing for you to do is to set the debugger, step through export in your code and see what the issue is.  If you're using a custom form then it could be an issue with form validation, but you can see that in debug mode.

**Comment by yuriy65** [comment]
Thank you so much
