### ISSUE TITLE
ExportActionModelAdmin not get the fields from get_fields?

### ISSUE THREAD

**Issue by mamcx** [django-import-export/django-import-export#196]
I have a custom list of fields defined in the admin like this:

``` python
@admin.register(Proyecto)
class ProyectoAdmin(ExportActionModelAdmin):
    resource_class = ProyectoResource
    exclude = ('projectValue',)

    def get_fields(self, request, obj=None):
        if (request.user.is_superuser and  (settings.SITIO_ACTUAL == 'argos')):
            return super(ProyectoAdmin, self).get_fields(request, obj)
        else:
            if settings.SITIO_ACTUAL == 'argos':
                return ['proyecto', 'entidadContratante' ]
            else:
                return ['proyecto', 'tipoEntidad', 'nombrePaquete', 'proceso']
```

But the export show ALL the fields in the model

**Comment by manelclos** [comment]
Hi @mamcx,

If you only want to include some fields, you need to declare them using the "fields" option in the Meta class of the Resource, see here:
https://django-import-export.readthedocs.org/en/latest/getting_started.html#customize-resource-options

You can also override the get_fields or get_export_order function in the resource if you want this to be dynamic.

**Comment by raoulalobo** [comment]
hi , i'm new in django please how can override the get_fields or get_export_order , i want to use request parameter like this def get_export_order(self, request ):
