### ISSUE TITLE
Tablib 3.7.0 support?

### ISSUE THREAD

**Issue by jameslao** [django-import-export/django-import-export#1964]
tablib 3.7.0 has been released a few days ago. Shall we update our dependency to use it?

**Comment by matthewhegarty** [comment]
Yes, now would be a good time to update because release 4.2 will be ready soon.
Thanks

**Comment by jameslao** [comment]
Ah I see that the requirement has already been updated in https://github.com/django-import-export/django-import-export/pull/1923 so no worries.
