### ISSUE TITLE
How can I limit or validate the number of rows in an import file and immediately raise the error?

### ISSUE THREAD

**Issue by timmyomahony** [django-import-export/django-import-export#1967]
I'm trying to add validation to my `ModelResource` so that I can limit the number of rows in an import spreadsheet. I'm able to create a `before_import` method to perform the validation:

```python
def before_import(self, dataset, *args, **kwargs):
        row_count = len(dataset)
        if row_count > 1000:
            raise ValidationError(
                f"Spreadsheet exceeds the row limit. Only spreadsheets with fewer than 1000 rows are accepted. Your file has {row_count} rows."
            )
        return super().before_import(dataset, *args, **kwargs)
```

The issue is that this validation error doesn't cause the processing to stop. Instead it gets added to the list of errors to display to the user once the file has been processed. In large import files this can take minutes, or even crash so I'd like the validation to prevent this from happening by aborting the process when raised.

The reason I'm trying to do this is to stop users from uploading particularly large import files with 1000s of rows (I have a separate performance-specific Resource for these files that users can choose instead).

**Comment by matthewhegarty** [comment]
Hi

There is a [`raise_errors`](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#validation-errors) flag which gets passed to the `import_data()` method.  If this flag is set, then the import should fail at the first error by raising a `ImportError`.  This is in v4 only.

However I think you will only have control over this flag if you are running an import "programmatically".  If you are using the Admin UI for import then it might not be possible to set this flag directly without some subclassing of `import_data()` in the Resource.  I guess it would be a useful enhancement to be able to set this as a config option, which I'll make a note to look into.

**Comment by timmyomahony** [comment]
Thanks, I'll close this question but further context (and might be useful for future users): I'm working on an app on Digital Ocean App Platform which frustratingly has a hard timeout of 100 seconds that can't be changed. This makes more complex imports with 10k+ rows a bit more challenging. Normally, having to wait a few minutes for a large import is fine, but here I need to optimise a bit (your notes [here](https://gist.github.com/matthewhegarty/f8a6fc7d06ae00176b15c885faca6c1f) are useful). 

The ability to have multiple resources-per-admin has really helped here. I now have two resources for importing

- A "standard" resource that you can use to create, update and delete rows in the traditional workflow. This is the resource I'm adding a row limit of 1000 to.
- A second "advanced" resource that is purely for handling large create-only imports. This has no limit. I slightly customise the frontend to make this clear:

![Screenshot 2024-10-15 at 15 19 08@2x](https://github.com/user-attachments/assets/3620d666-96ea-49b3-8913-298fb251bdf2)

**Comment by matthewhegarty** [comment]
Thanks Timmy - I've dropped you a LinkedIn connection request - always happy to talk about potential improvements for bulk imports (I have worked a lot in this area).
