### ISSUE TITLE
How to export data based on data from another model related via ForeignKey?

### ISSUE THREAD

**Issue by mglowinski93** [django-import-export/django-import-export#1969]
There are two models:

```python
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Event(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4
        editable=False,
    )

    promoter = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )


class Reservation(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        verbose_name=_("ID"),
    )

    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name="reservations",
    )
    participant = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
```

How to add export via `event tab` of all reservations assigned to particular event?

**Comment by matthewhegarty** [comment]
Do [these links](https://django-import-export.readthedocs.io/en/latest/faq.html#how-to-customize-export-data) help at all?  If not, please refine your question and I will try to answer.

**Comment by mglowinski93** [comment]
I could not make it work with upper hints.

My intention is like below:
1) Let's say there is an event (e.g. concert)
2) 3 people booked place on that particular event
3) I have an Django Admin panel tabl with events, where I display manage an event.
4) Every event has reservation assigned to it.

My intention is to allow admin export an excel file with list of reservation per particular event.
Ideally would be to allow also export a few events at once, one per tab in excel.

**Comment by matthewhegarty** [comment]
> My intention is to allow admin export an excel file with list of reservation per particular event.

If you can produce the required results using the Django ORM, then they can be exported.  You can use the [`filter_export()`](https://github.com/django-import-export/django-import-export/blob/3d05cd05a76d8332e5e26b525bf2a5bedc51495c/import_export/resources.py#L1021) to modify the base results (e.g. an export from Event table).

> Ideally would be to allow also export a few events at once, one per tab in excel.

To do this you would probably have to override [`get_export_data()`](https://github.com/django-import-export/django-import-export/blob/3d05cd05a76d8332e5e26b525bf2a5bedc51495c/import_export/admin.py#L704) in your Admin class, and use the openpyxl library to create a worksheet in the required format.

**Comment by mglowinski93** [comment]
Thank you.

`filter_export` did the job.
