### ISSUE TITLE
How to add a header row to excel

### ISSUE THREAD

**Issue by mglowinski93** [django-import-export/django-import-export#1970]
Is that possible to add a header column (with e.g. a title) upfront exported data?

We can assume, that we talk about excel file.

**Comment by matthewhegarty** [comment]
You can modify the tablib dataset in the [`after_export()`](https://github.com/django-import-export/django-import-export/blob/3d05cd05a76d8332e5e26b525bf2a5bedc51495c/import_export/resources.py#L1008) method.

More info [here](https://stackoverflow.com/a/62332748/39296).

**Comment by mglowinski93** [comment]
According to my research it's not what I'm looking for.
Upper hint allows to modify a data content.

What I need to do is:
1) Add a row before headers (center it) -> e.g. with constant value "Hello world"
2) Increase column width, but according to [this](https://github.com/jazzband/tablib/pull/516) ticket it's not possible
3) Modify exported file name

Do you see any solution for my needs?

**Comment by matthewhegarty** [comment]
> Add a row before headers (center it) -> e.g. with constant value "Hello world"

You can only do this by modifying the spreadsheet directly using [openpyxl](https://openpyxl.readthedocs.io/en/stable/).  You should be able to override hooks to modify data as described [here](https://github.com/django-import-export/django-import-export/issues/1969#issuecomment-2419885130).

> Increase column width, but according to ticket it's not possible

It would be possible with openpyxl.

> Modify exported file name

You can do this by overriding [`get_export_filename()`](https://github.com/django-import-export/django-import-export/blob/3d05cd05a76d8332e5e26b525bf2a5bedc51495c/import_export/admin.py#L813)

**Comment by mglowinski93** [comment]
Thank you, it's clear now :)
