### ISSUE TITLE
How to automatically test an admin panel export?

### ISSUE THREAD

**Issue by mglowinski93** [django-import-export/django-import-export#1971]
Is there any recommended way to test (e.g. with pytest) an export data via admin panel?

**Comment by matthewhegarty** [comment]
There are lots of examples [here](https://github.com/django-import-export/django-import-export/blob/main/tests/core/tests/admin_integration/test_export.py) of how we are testing exports from Admin UI.

**Comment by mglowinski93** [comment]
I've a testcase like this:

```python
def test_export(
    authenticated_api_client: APIClientData,
):
    client = authenticated_api_client.client

    factories.ReservationFactory.create()

    response = client.post(
        get_url(
            path_name="admin:events_event_export",
        ),
        data={"format": "0"},
        follow=True,
    )

    assert response.status_code == HTTPStatus.OK
```

and configuration like this:

```bash
/admin/events/event/export/	import_export.admin.export_action	admin:events_event_expor
```


Why response is not an generated file, but HTML content of admin panel?

**Comment by matthewhegarty** [comment]
It's possible there is a validation error 🤷‍♂️ 
Set a breakpoint in the export logic and step through to see what is going on.
Also view the returned HTML content to see if there are any error messages in there.

**Comment by mglowinski93** [comment]
Indeed, I was not logged in.
Thank a lot!
