### ISSUE TITLE
How to export in PDF format

### ISSUE THREAD

**Issue by paulocoutinhox** [django-import-export/django-import-export#1981]
Hi,

How to export in PDF format?

Thanks.

**Comment by matthewhegarty** [comment]
Hi

You can't export directly to PDF, but you should be able to override the [export data](https://django-import-export.readthedocs.io/en/latest/api_admin.html#import_export.admin.ExportMixin.get_export_data) and construct a PDF from the exported bytes using another library ([docs](https://docs.djangoproject.com/en/5.1/howto/outputting-pdf/)).

I've never tried this so cannot say if it works.  Please post back if you get something working.
