### ISSUE TITLE
How to export django-import-export fields

### ISSUE THREAD

**Issue by yswtrue** [django-import-export/django-import-export#1986]
now export [django-import-export](https://opencollective.com/django-import-export) field is blank, how to export [django-import-export](https://opencollective.com/django-import-export) fields?

**Comment by matthewhegarty** [comment]
Can you help me understand the issue?

- What version are you using?
- Has this worked before but now is not working?
  - If so, which version did it work in?
- Can you give me any steps to reproduce the issue.

Please follow the guidelines [here](https://django-import-export.readthedocs.io/en/latest/contributing.html#guidelines-for-reporting-an-issue-feature)
