### ISSUE TITLE
export only current page check. 

### ISSUE THREAD

**Issue by Astate** [django-import-export/django-import-export#1988]
Select "Export selected" from action menu only work for current page.
When we go to next page we lost all check from previous page. 

example :
we check four rows from the first page -> 4 of 200 selected
we go to next page it's flip to  0 of 200 selected

How  i can select many row from many page without lost selected from previous page ?

**Versions**
 - django-import-export==3.3.2
 - Python3.11
 - Django==4.2.7

**Comment by matthewhegarty** [comment]
I think this is an issue with Django admin.  I can't see that there is any way that the state of selections is retained when you click through pagination, so this is something we'd have to add.

**Comment by matthewhegarty** [comment]
Same issue [here][1] and further discussion [here][2]

[1]: https://stackoverflow.com/questions/14475333/django-admin-keeping-selected-items-on-different-page-in-changelist-view
[2]: https://groups.google.com/g/django-users/c/MK0vWOP86qE

**Comment by andrewgy8** [comment]
A couple solutions come to mind @Astate : 

- one dirty solution is to increase the pagination limit on a page. 

```
@admin.register(Book)
class BookAdmin(admin.ModelAdmin):
    list_per_page = 400
```

- implement bettering filter on the admin page to get your selection into one page. 

Fundamentally though, I dont see this as a Django Import Export issue as its a feature of Django Admin that limits this.
