### ISSUE TITLE
Problem with DecimalWidget with zero value

### ISSUE THREAD

**Issue by mateuspadua** [django-import-export/django-import-export#199]
An error occurs when importing fields that have zero value in xls file.

<b>Original:</b>

```
class DecimalWidget(NumberWidget):
    """
     Widget for converting decimal fields.
     """
    def clean(self, value):
        if not value:
            return None
        return Decimal(value)
```

<b>My suggestion for fix:</b>

```
class DecimalWidget(NumberWidget):
    def clean(self, value):
        return Decimal(value if value else 0)
```

**Comment by bmihelac** [comment]
@mateuspadua which error does it raise?

**Comment by mateuspadua** [comment]
the error is (1048, "Column 'my_column' cannot be null")

I believe that is because the column can not receive as null value, but in the import file, the value for this column has been set to zero, so I guess that could not give error but to set zero for this column when saving.

Thanks for answer.

**Comment by bmihelac** [comment]
Are you sure that field in excel is not empty? It should be "0" in field

**Comment by mateuspadua** [comment]
Hi, i am sure that field is with "0" value in excel. If you want, i can send you my excel file. Thanks for answer.

**Comment by bmihelac** [comment]
Would it be possible for you to add failing test?

**Comment by mateuspadua** [comment]
Yes, i am going to prepare one and i will send to you. Thanks

**Comment by mateuspadua** [comment]
How i can send this test to you?

**Comment by bmihelac** [comment]
All tests should go to test folder, please see https://github.com/bmihelac/django-import-export/tree/master/tests

**Comment by teshomem** [comment]
Hello guys,

I am not sure if this is related but I have same problem when I import excel column with zero value. This is in my model:
concentration = models.PositiveIntegerField(default=0, blank=False, null=False)
and i get (1048, "Column 'concentration' cannot be null")

The excel cells have zero values. For some reason the values in excel are considered as null. Do you have any idea? 

Thank you for the help
