### ISSUE TITLE
导入和导出的字段一样用应该如何处理

### ISSUE THREAD

**Issue by guoqingshuai** [django-import-export/django-import-export#1990]
您能帮我了解这个问题吗？
我使用的是django-import-export==4.1.1
我有这样一个需求 导入和导出的字段不一致 应该如何处理 
    class Meta:
        # 导入模型
        model = TeachingClass
        # 导入导出的字段
        fields = ('major_id','class_name', 'class_desc',"class_id","parent_id","new_field")
        # fields = ('major_id','class_name', 'class_desc')
        # 指定id
        import_id_fields=('class_name',)
        #导入的顺序
        import_order = ('class_name', 'class_desc',"class_id","parent_id")
        # 导出的顺序
        export_order = ('major_id','class_name', 'class_desc')
如 ：我导入时候导入class_name', 'class_desc',"class_id","parent_id" 这四个字段其中class_id","parent_id 这两个是后端生成的，我在导出的时候不想导出"parent_id","new_field" 这两个字段 应该如何处理

**Comment by andrewgy8** [comment]
Google Translate:

What should I do if the imported and exported fields are used the same way?

Can you help me understand this problem?
I'm using django-import-export==4.1.1
I have such a requirement. The imported and exported fields are inconsistent. How should I deal with it?
```
class Meta:
#Import model
   model = TeachingClass
# Import and export fields
   fields = ('major_id','class_name', 'class_desc',"class_id","parent_id","new_field")
# fields = ('major_id','class_name', 'class_desc')
#Specify id
   import_id_fields=('class_name',)
#Import order
   import_order = ('class_name', 'class_desc',"class_id","parent_id")
# Export order
   export_order = ('major_id','class_name', 'class_desc')
```
For example: when I import, I import the four fields class_name', 'class_desc', "class_id", and "parent_id". Among them, class_id" and "parent_id" are generated by the backend. I don't want to export "parent_id" when exporting. "new_field" How should these two fields be handled?

**Comment by andrewgy8** [comment]
Please see #539

**Comment by guoqingshuai** [comment]
感谢您的回复，已经理解了您说的问题，但是通过export_order 就能指定导出的顺序 为什么不用此做条件呢，这只是我的猜想。

**Comment by andrewgy8** [comment]
GT:
> Thank you for your reply. I understand the problem you mentioned. But the order of export can be specified through export_order. Why not use this as a condition? This is just my guess.


Ah! Are you asking why you can't specify export order and have it respect the fields that you want exported? Sorry if I don't understand. Google Translate may be losing some information along the way 😄

**Comment by guoqingshuai** [comment]
解决了我的问题谢谢您
