### ISSUE TITLE
TypeError: JSONWidget.render() got an unexpected keyword argument 'export_fields'

### ISSUE THREAD

**Issue by ShaheedHaque** [django-import-export/django-import-export#1993]
**Describe the bug**
Exception as per subject line.

**To Reproduce**
1. Exporting a model with a JSONField seems to trigger the issue.

**Versions (please complete the following information):**
 - Django Import Export: 4.2.0 (newly installed)
 - Python 3.12.3
 - Django 5.1.3 (newly installed)

**Expected behavior**
No exception.

**Screenshots**

**Additional context**

**Comment by andrewgy8** [comment]
Hey @ShaheedHaque , could you provide a way to reproduce this behaviour?

**Comment by matthewhegarty** [comment]
Can you reproduce in the [example app][1]?  I just declared a new field in `Book`:

```
config = models.JSONField(default=dict)
```

I ran migrations then tried an export, and the field was exported fine.  Check that 4.2.0 is definitely installed and there isn't an old version hanging around somehow (e.g. `pip freeze | grep -i django`)

Have you added any customizations such as overridden methods?

If this issue persists for you, then steps to reproduce and a stack trace would be very helpful.

[1]: https://django-import-export.readthedocs.io/en/latest/installation.html#example-app

**Comment by ShaheedHaque** [comment]
> Have you added any customizations such as overridden methods? It's possible you have overridden `render()` and not updated your code after installing 4.2.0. Check the [4.2.0 release notes](https://django-import-export.readthedocs.io/en/latest/release_notes.html#breaking-changes).

That was it. A long-forgotten-by-me bit of code looks like this, with a simple repro triggered by the update to 4.2:

```
#
# In models.py
#
class Bug(db_models.Model):
    description = db_models.CharField(max_length=256)
    inputs = db_models.JSONField()
```

plus:

```
#
# In admin.py
#
class JSONWidget(widgets.Widget):
    """
    https://github.com/django-import-export/django-import-export/issues/285
    Convert data into JSON for serialization.
    """
    def clean(self, value, row=None, *args, **kwargs):
        """
        Hide Sphinx incompatibility in super() docstring.
        """
        return json.loads(value)

    def render(self, value, obj=None):     ##### missing **kwargs as per release notes.
        if value is None:
            return ""
        return json.dumps(value)


class JSONResource(ModelResource):
    """
    https://github.com/django-import-export/django-import-export/issues/285
    Override ModelResource to provide JSON field support.
    """
    @classmethod
    def widget_from_django_field(cls, f, default=widgets.Widget):
        if f.get_internal_type() in ('JSONField', ):
            return JSONWidget
        else:
            return super().widget_from_django_field(f)

class BugResource(JSONResource):
    class Meta:
        model = my_models.Bug


class BugAdmin(i_e_admin.ImportExportMixin, admin.ModelAdmin):
    resource_class = BugResource
```

If I create an instance of `Bug(description="whatever",inputs={"x": 1})` using the Django admin, and then export fails because of the missing kwargs.

Many thanks for the quick replies.
