### ISSUE TITLE
XLS export fails on datetime.timedelta.

### ISSUE THREAD

**Issue by kitsunde** [django-import-export/django-import-export#20]
Works fine in CSV, but not XLS.

**Comment by cschaffner** [comment]
I have the same problem. How did you guys solve it?

**Comment by Jufik** [comment]
I found a work around in __excel_date_dt from {packagepath}/xlwt/Row.py, around line 99.
You should get the tzinfo and pass it to the epoch creation when relevant.

Antother solution is to remove tzinfo from your datetime object.
The later is obviously not "exactly" correct, but enough for my current need. 

A contribution would be needed in the xlwt library to fix this properly
