### ISSUE TITLE
Template Inheritance (Skipped to avoid recursion) Error

### ISSUE THREAD

**Issue by iamzoltan** [django-import-export/django-import-export#2019]
**Describe the bug**
I am trying to use the templates inside this library to extend some of my custom templates. I was running `django==3.0` and `django-import-export==2.5.0` with `python3.8` before, and there was no issue with template inheritance. I am now forced to update to `python3.12`, `django==5.1` and decided to give `django-import-export==4.3.3` a go. For context, I am using these templates for custom admin pages.

**To Reproduce**
1. extend a template for a custom django admin page
2. use `{% extends "admin/import_export/change_list.html" %}`
3. Go to the page in django admin
4. See error: `TemplateDoesNotExist` because of `django.template.loaders.app_directories.Loader: /usr/local/lib/python3.12/site-packages/import_export/templates/admin/import_export/change_list.html (Skipped to avoid recursion)`

**Versions (please complete the following information):**
 - Django Import Export: 4.3.3
 - Python 3.12
 - Django 5.1

**Expected behavior**
I expected the inheritance to work as before.

**Additional context**
It is unclear to me what happened. Any guidance would be helpful. I tried downgrading to the old version of `django-import-export`, but that did not work because it errors with the new python version. I am using the `ImportExportModelAdmin` as the inherited class for my admin classes.

Thanks for your help! :)

**Comment by matthewhegarty** [comment]
Hi, sorry to hear you are having upgrade issues.  I suggest to have a look at this [thread](https://github.com/django-import-export/django-import-export/issues/1514#issuecomment-1344200867) first, and see if that works for you.

It might not be relevant to this issue, but if you are upgrading from django-import-export 2.x, then I suggest upgrade to 3.x first, then 4.x because there are a few breaking changes in each major release.

**Comment by iamzoltan** [comment]
@matthewhegarty That helped! Thanks. I didnt have to change the path, only the attribute name:
```
-change_list_template = "admin/reviews/change_list.html"
+import_export_change_list_template = "admin/reviews/change_list.html"
```
That worked for me :)
