### ISSUE TITLE
easier customization of (excel) importing

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#203]
Hi,

I've got to create a customized function for excel import, that is, interpreting the data in the excel and providing a dataset to django-import-export. I'd like to see some hooks in the classes to this is easier/cleaner. I did it like:

```
from import_export.admin import ImportMixin
from import_export.formats.base_formats import XLS

class MyXLS(XLS):
    def create_dataset(self, in_stream):
    ...
    return dataset

class MyAdmin(ImportMixin, admin.ModelAdmin):
    ...
    formats = (MyXLS,)
```

Happy to create a PR if you provide pointers where/how to do it.

**Comment by bmihelac** [comment]
Hi @manelclos! The way you did it looks good to me, you are basically adding new format. What would you like to make easier/cleaner?

**Comment by manelclos** [comment]
Yeah, not that much work, but it took a while to figure out as I found nothing in the documentation regarding it.

Maybe a get_dataset() method I can override in the ImportMixin. But if you think the current method is ok, it is only a matter of adding it to the documentation.

Thanks!

**Comment by bmihelac** [comment]
Adding documentation would be beautiful!

Do you mean hook like this:

    dataset = input_format.create_dataset(data) # old
    dataset = self.create_dataset(input_format, data) # new

**Comment by manelclos** [comment]
Yes, that makes sense. That way I can implement the function right inside the admin class right? (overriding the default built in the ImportMixin)

**Comment by bmihelac** [comment]
this hook allow additional processing from inside admin. However ``Resource`` class has ``before_import`` so manipulating dataset is not admin related maybe you would want to override it in a Resource.

https://github.com/bmihelac/django-import-export/blob/master/import_export/resources.py#L276

**Comment by manelclos** [comment]
I see what you mean. In admin.py:
```
                dataset = input_format.create_dataset(data)
                result = resource.import_data(dataset, dry_run=True,
                                              raise_errors=False)
```

What I need to override is how the dataset is created, not how it is used afterwards. I see your previous suggestion as the best option:
```
dataset = self.create_dataset(input_format, data)

def create_dataset(self, input_format, data):
    return input_format.create_dataset(data)
```

This way I can customize the import the way I like, and have access to both the original import_format and the data.

The most important thing though is documenting the feature :)

**Comment by bmihelac** [comment]
Yes let's do this. 

Regarding documentation - I welcome every improvement :)
