### ISSUE TITLE
ForeignKeyWidget should automatically pick up "to_field"

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#204]
Hi, in the source code you describe a way for a foreign key to point to a field other than the pk:
https://github.com/bmihelac/django-import-export/blob/master/import_export/widgets.py#L175

```
ForeignKeyWidget(Author, 'name'))
```

I think the default behaviour should be to check if to_field has been defined in the model and automatically handle it.

Thanks!

**Comment by bmihelac** [comment]
Looks like you are right (I just did not use to_field enough to have opinion)
