### ISSUE TITLE
Meta exclude field not working

### ISSUE THREAD

**Issue by vyscond** [django-import-export/django-import-export#209]
So i've tried to export my table without the ID column to make a test: if postgresql do not auto-increment only when i try to import a file with ID. The problem is the .CSV is not accepted to be import because it's missing the ID column. This occurs over the admin page and over the django's shell.

Over the admin page i got this for each row
```python
Line number: 1 - 'id'
Traceback (most recent call last):
File "/Users/vyscond/Tartarus/infosae-rest/.venv/lib/python3.4/site-packages/import_export/resources.py", line 323, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "/Users/vyscond/Tartarus/infosae-rest/.venv/lib/python3.4/site-packages/import_export/resources.py", line 154, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
KeyError: 'id'
```

Here is my admin Object's
```python
class PersonResource(resources.ModelResource):
    class Meta:
        model = Person
        exclude = ('id',)
        fields = (
            'name' ,
            'address' ,
            'phone' ,
            )

class PersonAdmin(ImportExportActionModelAdmin):
    resource_class = PersonResource
    ordering = ('phone',)
```

So why the hell the we have the options to exclude if the 
```python
class ModelInstanceLoader(BaseInstanceLoader):
    """
    Instance loader for Django model.

    Lookup for model instance by ``import_id_fields``.
    """

    def get_queryset(self):
        return self.resource._meta.model.objects.all()

    def get_instance(self, row):
        try:
            params = {}
            for key in self.resource.get_import_id_fields():
                field = self.resource.fields[key]
                params[field.attribute] = field.clean(row)
            return self.get_queryset().get(**params)
        except self.resource._meta.model.DoesNotExist:
            return None
```

always try to read the ID? Where is this ID come from if it's possible to exclude it over the exporting process? This, of course, is related to the mysterious about what Django and Postgres do when we pass a not 0 value on an auto-increment field type like the default ID. For SQLite this is not a trouble, it's just accept the value and move on incrementing, but this is not the database we use in production, right?

1 - Whats the matter with the function of import having routines based on ID column (which is possible to be excluded)?
2 - How this library/django behaves about set a non-zero value for an auto-increment column/field on real databases?

**Comment by bmihelac** [comment]
Hey @vyscond please see https://github.com/bmihelac/django-import-export/issues/211, I think it covers your questions

**Comment by manelclos** [comment]
Hi @vyscond, did you tried ``import_id_fields`` option as @bmihelac suggested? Any news on this issue?

**Comment by vyscond** [comment]
i already gave up on use this library. right now i'am using the output of  __dumpdata__ default function to manipulate and generate other formats.

**Comment by srugano** [comment]
Even if I tried that solution from @bmihelac , I end up doing with the same error because in

```
   for key in self.resource.get_import_id_fields():
     field = self.resource.fields[key]
```

`self.resource.fields` is an empty dict, no matter what I change in the configurations. This issue is still there.
