### ISSUE TITLE
IntegerWidget clean() returns None when value is 0

### ISSUE THREAD

**Issue by aklos** [django-import-export/django-import-export#219]
I've been having problems importing data and found this problem. I don't know if it's an issue with django-import-export (0.2.6), Python (2.7.6), or my postgres (9.1.14) schema. I'm using Django 1.7.

I recieve this error when trying to import an object that has an integer field set to 0: "IntegrityError: null value in column "field_name" violates not-null constraint"

During debugging I found the culprit to be the lines "if not value: return None" in the clean method of import-export's IntegerWidget class.

Sorry, this is the first time I've submitted an issue so I probably messed up somehow, but if this issue is valid then someone please let me know what I should do, thanks. :neckbeard:

**Comment by bmihelac** [comment]
This should be fixed in recent versions:
 
https://github.com/bmihelac/django-import-export/commit/26ab583784d70f86655049fe35db417579fdfade

**Comment by aklos** [comment]
Maybe the fix wasn't added into the release version?

One more issue though, the fix doesn't work for XLS documents which might feed integers as decimals but still use the integer widget. The check should probably force the value with "int(value) is not 0".

**Comment by dif001** [comment]
there is some problem to make value from list
it include float value, so the value was treated as float, 
so if  u wanna avoid error, u must cast by int type explicitly
```python
class IntegerWidget(NumberWidget):
    def clean(self, value):
        if not value and value is not 0:
            print value is float
            return None
        return int(value)
```
```python
class IntegerWidget(NumberWidget):
    def clean(self, value):
        value = int(value)
        if not value and value is not 0:
            print value is float
            return None
        return int(value)
```

**Comment by gauravdott** [comment]
I am facing the same issue, 0 is interpreted as None in all widgets when importing from xls. Can anybody tell me how to solve this problem?

**Comment by aklos** [comment]
You need to override the widget clean methods and properly parse the values like how dif001 did.

**Comment by gauravdott** [comment]
Where do I override the widget's clean method and how to use it?

**Comment by bmihelac** [comment]
Can you check if https://github.com/django-import-export/django-import-export/pull/282 works for you?

**Comment by bmihelac** [comment]
Closed with https://github.com/django-import-export/django-import-export/pull/282
