### ISSUE TITLE
End up with duplicates when overriding import_obj

### ISSUE THREAD

**Issue by Zowie** [django-import-export/django-import-export#220]
Hi, first of all thanks for the great Django app! 

Now my problem: I'm running into an issue where I override `import_obj` and create FK related objects before the imported object is saved, and the FK related objects end up duplicated in my database.. 
I'm adding the `save()`d objects to the `data` argument in `import_obj()` like this:

```
createdThingData = data["thing"].partition("::") // User has to enter one string value with a delimiter
createdThing = new CreatedThing()
createdThing.value, createdThing.value2 = createdThingData[0], createdThingData[2]

createdThingData2 = data["thing2"].partition("::") // User has to enter one string value with a delimiter
createdThing2 = new CreatedThing()
createdThing2.value1, createdThing2.value2 = createdThingData2[0], createdThingData2[2]

createdThing.save(), createdThing2.save()

data = {
    "thing": createdThing.id,
    "thing2": createdThing2.id,
}

return super(NewThingResource, self).import_obj(obj, data, dry_run)
```

So the end result here is that i have a single NewThing in my database, that has a FK to `createdThing` and `createdThing2`, but both `createdThing` and `createdThing2` are duplicated! The problem is of course that my FK objects needs an `id` before i can add them to `data`. The import Preview screen also shows correct results: the `id` of each of the related objects. 

I noticed that if i click on 'Import' after i selected the file to import from and go to the Preview screen, the related objects are being added, and when i 'Confirm import' they're being created again..

I hope someone can clarify what happens here, i can't find it in the docs.

**Comment by manelclos** [comment]
Hi @Zowie, are you writing those values to the database in the preview step?

**Comment by stripathi669** [comment]
+1 on the issue. The entries are getting duplicated for me too. In my case, no FKs are involved. Any idea why @manelclos ?

**Comment by bmihelac** [comment]
Do you use transactions?  Settings is `IMPORT_EXPORT_USE_TRANSACTIONS` and relevant info is here:

http://django-import-export.readthedocs.io/en/latest/import_workflow.html#transaction-support

**Comment by manelclos** [comment]
@Zowie @stripathi669 if you look at import_obj, the object is not supposed to be saved, only the fields need to be imported. can you check that removing the call to save() in import_obj fixes the issue?

https://github.com/django-import-export/django-import-export/blob/fc6ef3e6150a442366966498c43259453d9f1c09/import_export/resources.py#L331
