### ISSUE TITLE
Customize the import preview template with fields which aren't in the model ?

### ISSUE THREAD

**Issue by HydrUra** [django-import-export/django-import-export#221]
How to customize the import preview template ?
I can't find the rendering of the preview in import workflow. 
I am decalring a fields that don’t exist in the target model, i'm using it to find the id that matches (before_import) but I cannot displaying it to the user... I don't understand how to do so and where... 
Picture of my excel and what the module displays me
![import_genus](https://cloud.githubusercontent.com/assets/11501885/6666005/7b7de94e-cbf9-11e4-8478-081245f4543f.jpg)

**Comment by manelclos** [comment]
Hi @HydrUra, you can accomplish it using a custom format. See explanation in issue #277. I'll try to put an example in the documentation.
