### ISSUE TITLE
Change column names

### ISSUE THREAD

**Issue by moglars** [django-import-export/django-import-export#230]
In the documentation it is stated:
It is possible to override a resource field to change some of its options
See: https://django-import-export.readthedocs.org/en/latest/getting_started.html#declaring-fields
If I do this, it appears a new column with the specified column name, but there are no values.

How can export a model with different column names?

**Comment by manelclos** [comment]
Hi @moglars,

See the ''dehydrate_full_title" function in the same page. Write a dehydrate_+field_name function.

**Comment by manelclos** [comment]
Hi @moglars, any news on this issue?

**Comment by ulyssesv** [comment]
I had a similar issue. The default behaviour for column names is to use the field name but I needed the field's `verbose_name` instead.

To do this I just replaced the `field_from_django_field` method changing the section in bold below:

```
class ContentResource(resources.ModelResource):
    @classmethod
    def field_from_django_field(self, field_name, django_field, readonly):
        """
        Returns a Resource Field instance for the given Django model field.
        """

        FieldWidget = self.widget_from_django_field(django_field)
        widget_kwargs = self.widget_kwargs_for_field(field_name)
        field = fields.Field(attribute=field_name, **column_name=django_field.verbose_name**,
                widget=FieldWidget(**widget_kwargs), readonly=readonly)
        return field
```

**Comment by source3** [comment]
Bump.  Having the same issue.

**Comment by kalekseev** [comment]
> In the documentation it is stated:
> It is possible to override a resource field to change some of its options  

Docs should say that you need to include `attribute=<model.field_name>` argument together with `column_name` argument otherwise code returns `dehydrate_<field_name>` method result or None.

**Comment by zdomcia** [comment]
@kalekseev could you please show some example with using ```attribute=<model.field_name>```? When I add it I still have empty field

**Comment by TrungKien1230** [comment]
@ulyssesv : I tried like this but I got error:

@admin.register(Recipient)
class RecipientAdmin(ImportExportModelAdmin, ModelResource):
    list_display=('decision','name','description',)

    def field_from_django_field(cls, field_name, django_field, readonly):
        """
                    #     Returns a Resource Field instance for the given Django model field.
                    #     """
        FieldWidget = cls.widget_from_django_field(django_field)
        widget_kwargs = cls.widget_kwargs_for_field(field_name)
        field = cls.DEFAULT_RESOURCE_FIELD(
            attribute=field_name,
            column_name=django_field.verbose_name,
            widget=FieldWidget(**widget_kwargs),
            readonly=readonly,
            default=django_field.default,
        )
        return field

Error:

 File "C:\Users\nguy\PycharmProjects\Learning\django_SonNguyen_add_moreFunction_for_page_admin\demoform\news\admin.py", line 33, in <module>
    class SafetyReortTriageAdmin(ImportExportModelAdmin, resources.ModelResource):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by jordanmkoncz** [comment]
Here's a mixin based on the code from @ulyssesv, which you can easily add to your `ModelResource` class:

```
from import_export import fields as import_export_fields


class ColumnNameAsFieldVerboseNameMixin:
    @classmethod
    def field_from_django_field(self, field_name, django_field, readonly):
        """
        Returns a Resource Field instance for the given Django model field.

        Customised to set the `column_name` to the `verbose_name` of the Django model field, rather than the field name.

        See https://github.com/django-import-export/django-import-export/issues/230#issuecomment-115014836.
        """
        FieldWidget = self.widget_from_django_field(django_field)

        widget_kwargs = self.widget_kwargs_for_field(field_name)

        field = import_export_fields.Field(
            attribute=field_name,
            column_name=django_field.verbose_name,
            widget=FieldWidget(**widget_kwargs),
            readonly=readonly,
            default=django_field.default,
        )

        return field

class ExampleModelResource(ColumnNameAsFieldVerboseNameMixin, ModelResource):
    ...
```

Note that another approach you could use to set the column names to whatever you want is to override `get_export_headers`, for example:

```
class ExampleModelResource(ModelResource):
    def get_export_headers(self):
        headers = super().get_export_headers()

        for index, header in enumerate(headers):
            if header == 'model_field_name':
                headers[index] = "My Custom Arbitrary Header for model_field_name"

        return headers
```

Source: https://stackoverflow.com/a/61913307/1374827
