### ISSUE TITLE
Maximum recursion depth exceeded while trying to import some dataset

### ISSUE THREAD

**Issue by TalitaSoares** [django-import-export/django-import-export#250]
I've got this error message when I was trying to import some dataset through django admin.

    Line number: 1 - Line number: 1 - maximum recursion depth exceeded while calling a Python object
    Traceback (most recent call last):
    File "/home/talita/Documentos/projetos/ambientes/ambientesEmoda/lib/python2.7/site-packages/import_export/resources.py", line 345, in import_data
    real_dry_run)
    File "/home/talita/Documentos/projetos/ambientes/ambientesEmoda/lib/python2.7/site-packages/import_export/resources.py", line 256, in get_diff
    v1 = self.export_field(field, original) if original else ""
    RuntimeError: maximum recursion depth exceeded while calling a Python object while calling a Python object
    Traceback (most recent call last):
    File "/home/talita/Documentos/projetos/ambientes/ambientesEmoda/lib/python2.7/site-packages/import_export/resources.py", line 345, in import_data
    real_dry_run)
    File "/home/talita/Documentos/projetos/ambientes/ambientesEmoda/lib/python2.7/site-packages/import_export/resources.py", line 256, in get_diff
    v1 = self.export_field(field, original) if original else ""
    RuntimeError: maximum recursion depth exceeded while calling a Python object

Model

    class ProductRestriction(GeneralModel):
        restriction = BooleanField(
            verbose_name=u'Restrição', default=True
        )
        brand = ForeignKey(
            Brand, verbose_name=u'Marca', null=True, blank=True
        )
        collection = ForeignKey(
            Collection, verbose_name=u'Coleção', null=True, blank=True
        )
        product = ForeignKey(
            Product, verbose_name=u'Produto', null=True, blank=True
        )
        state = ForeignKey(
            State, verbose_name=u'Estado', null=True, blank=True,
            )
        city = ManyToManyField(
            City, verbose_name=u'Cidade', null=True, blank=True,
        )

        class Meta:
            verbose_name = u'Restrição'
            verbose_name_plural = u'Restrições'
            app_label = 'showroom'

Model Resource

    class ProductRestrictionResource(ModelResource):
        class Meta:
            model = ProductRestriction
            fields = ('id', 'restriction', 'brand', 'collection', 'product', 'state', 'city')

Admin

    class ProductRestrictionAdmin(ImportExportModelAdmin):
        resource_class = ProductRestrictionResource
        form = ProductRestrictionAdminForm
        exclude = ('is_active',)
        filter_horizontal = ['city']
        search_fields = ['brand', 'collection', 'product', 'city', 'state']
        list_filter = (
            BrandRestrictionListFilter,
            CollectionRestrictionListFilter,
            ProductRestrictionListFilter,
        )
        list_display = ['__unicode__', 'restriction', ]

        class Meta:
            model = ProductRestriction

$ python --version
Python 2.7.5

Django==1.6.5
django-import-export==0.2.3
tablib==0.10.0

**Comment by bmihelac** [comment]
It looks like your ``__unicode__`` method calls itself.

**Comment by manelclos** [comment]
Hi @TalitaSoares, any news on this issue?

**Comment by bmihelac** [comment]
I'm closing this, please reopen if needed.
