### ISSUE TITLE
problem with few django instances

### ISSUE THREAD

**Issue by AyumuKasuga** [django-import-export/django-import-export#251]
Hello! I have two django instances on two different servers (under one balancer but without sticky sessions) and sometimes I get error: 
IOError: [Errno 2] No such file or directory: u'/tmp/tmph40kuA'

It's happens cause first time client gets response from first server (when executes import_action method https://github.com/bmihelac/django-import-export/blob/master/import_export/admin.py#L171) and tmpfile creates in filesystem of first server. Then client gets response from second server, executes process_import method (https://github.com/bmihelac/django-import-export/blob/master/import_export/admin.py#L115), but tmp file (from form import_file_name field) does not exists on second server tmp dir...

Maybe it's possible to add option for store tmpfile in custom location or redis/memcache or database?

**Comment by bmihelac** [comment]
Please see:

https://github.com/bmihelac/django-import-export/pull/133
