### ISSUE TITLE
unique_together doesn't work

### ISSUE THREAD

**Issue by cfarfan** [django-import-export/django-import-export#257]
Hello!
I have the following code:

models.py

```
class Fulfillment(models.Model):
    percentage  = models.FloatField()
    month       = models.ForeignKey(Month)
    year        = models.ForeignKey(Year)
    company             = models.ForeignKey(Company)
    country             = models.ForeignKey(Country)
    class Meta:
        verbose_name        = 'Budget Fulfillment'
        verbose_name_plural = 'Budget Fulfillments'
        get_latest_by       = 'year'
        unique_together     = (('company','country','year', 'month'),)
```

admin.py

```
class FulfillmentResource(resources.ModelResource):
    company = fields.Field(column_name='company', attribute='company',widget=widgets.ForeignKeyWidget(Company,'name') )
    country = fields.Field(column_name='country', attribute='country',widget=widgets.ForeignKeyWidget(Country,'name') )
    class Meta:
        model = Fulfillment
        fields = ('id','company','country','year','month','percentage')
        export_order = ('id','company','country','year','month','percentage')
```

so, when I import a xls with the duplicate data, unique_together does not work (the duplicate data is added to database).
can you help me with this?

**Comment by bmihelac** [comment]
did you add ``unique_together`` after creating table? It should be enforced at the database level

https://docs.djangoproject.com/en/1.8/ref/models/options/#unique-together

**Comment by manelclos** [comment]
Hi @cfarfan, @bmihelac is right, you should be getting a database error. Anyway, try setting the ``import_id_fields`` option in the resource to your unique_together fields, and see if it helps. See here: https://django-import-export.readthedocs.org/en/latest/getting_started.html#customize-resource-options

**Comment by shouldsee** [comment]
in case anyone is looking into using the `unique_together` fields as the primary key implicitly while keeping a numeric primary key, one needs to set `unique_together` at the database level as well as `exclude=('id', )` to disengage the actual primary key from the identification process.

Basically, the import workflow identifies the candidate hit in the database through `import_id_fields`, cache the candidate as `original`, then overwrite the specified fields using values from xls and save as a new object. So if the 'id' attribute is included, it gets overwritten and causes an `IntegrityError` when the new object is saved for violating the `unique_together` field. But if 'id' field has been excluded, then the new object is saved with the old 'id' un-touched.

Therefore it is necessary to exclude ('id',) here, by modifying the `Resource` as

```
class FulfillmentResource(resources.ModelResource):
    company = fields.Field(column_name='company', attribute='company',widget=widgets.ForeignKeyWidget(Company,'name') )
    country = fields.Field(column_name='country', attribute='country',widget=widgets.ForeignKeyWidget(Country,'name') )
    class Meta:
        model = Fulfillment
        exclude = ('id',)
        import_id_fields = ('company','country','year', 'month')
        #fields = ('company','country','year','month','percentage')
        #export_order = ('company','country','year','month','percentage')
```
