### ISSUE TITLE
Checkbox to exclude row on import

### ISSUE THREAD

**Issue by alaw005** [django-import-export/django-import-export#258]
I am just wondering how hard it would be to add a checkbox on the import preview page to enable the user to select records to exclude from the import. 

This would be useful where there is more than one record matching the import_id_fields as would allow user to select which record they want to include. 

I am very new to python/django so a little beyond me, although I have just worked out how to override the "skip_row" function which I imagine is where we would test if recorded has been marked to exclude. I suppose the form and template would need to be updated and somehow passed to "skip_row" where decision on included/excluding would be made.

**Comment by rhunwicks** [comment]
In #237 we allowed `**kwargs` to be passed to `import_data` so presumably we could add the checkbox to the form and use it to build an array of rows that should be skipped, and then check for them in `skip_row`.

I'm not sure that such an extension belongs in the core though. It would be difficult to know how to pass the array to skip rows:

* if the PK is a single field and is in the import file, then it works great, but that situation won't be common
* if the import_id_fields are in the row then we could build a tuple of them, but that doesn't help when there are multiple rows with identical import_id_fields but different other fields (the use case @alaw005   describes)
* we could build a tuple of all fields, but that seems a bit of a hack
* we could use the row_id, but that might not work if the user is doing any dataset manipulation in ` before_import` - I often need to un-crosstab data, or delete extra rows before the main header, etc. In theory, the datasets should be the same, but you could have problems if any of the dataset manipulation depends on the value of `dry_run`.

**Comment by bmihelac** [comment]
I had idea to move handling of uploaded data to some form  to make handling confirming and importing data pluggable with ``ConfirmImportForm`` (https://github.com/django-import-export/django-import-export/pull/133#issuecomment-69537699). I am not sure if this would work and there is already PR https://github.com/django-import-export/django-import-export/pull/264 that solves original problem of horizontal scaling.

On the other side I am not sure if this should go in core as overriding import_action should not be problem, there are less than 50 lines of code there:
https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L171-L229

**Comment by rhunwicks** [comment]
I agree about it not going in core.

I think we should add extension points to enable these sorts of
customizations as we find them. The pluggable temporary storage is a good
example.

For example, we could:

   - change the call to input_format.create_dataset to go via a new
   self.create_dataset which would allow people to customize the dataset
   creation on a per admin basis.
   - separate the the import_template_name into confirm_import_tempate_name
   and process_import_template_name so that people can customize the
   confirm page separately if they want

​

**Comment by bmihelac** [comment]
agree,. good points
