### ISSUE TITLE
IntegrityError: Key (id)=(10) already exists

### ISSUE THREAD

**Issue by shackra** [django-import-export/django-import-export#268]
Seems like Django cannot use the last available id after importing data into the database, this cause problems when trying to add individual values into the database from the Django admin panel

**Comment by manelclos** [comment]
Hi @shackra, how did you import the data? Was all the data new values?

**Comment by shackra** [comment]
I imported the data through the admin panel, using the "import" link. The database was empty and the values inserted were new! this how my `admin.py` file looks like:

```
from django.contrib import admin
from import_export import resources
from import_export.admin import ImportExportMixin

from .models import FrenchWord
from .models import ItalianWord

# import_export resources
class FrenchWordResource(resources.ModelResource):
    class Meta:
        model = FrenchWord

class ItalianWordResource(resources.ModelResource):
    class Meta:
        model = ItalianWord

# Integration with admin panel
class FrenchWordAdmin(ImportExportMixin, admin.ModelAdmin):
    resource_class = FrenchWordResource
    pass

class ItalianWordAdmin(ImportExportMixin, admin.ModelAdmin):
    resource_class = ItalianWordResource
    pass

admin.site.register(FrenchWord, FrenchWordAdmin)
admin.site.register(ItalianWord, ItalianWordAdmin)
```

**Comment by rhunwicks** [comment]
Please can you post the models.py too

**Comment by shackra** [comment]
Sure!

--8<---------------cut here---------------start------------->8---
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError


def NotEqualTo0(value):
    if value == 0:
        raise ValidationError('Word cannot be scored with 0 '
                              '(to avoid exceptions when exporting'
                              ' and importing the list into the database)')


class FrenchWord(models.Model):

    def __str__(self):
        return u"word: {} - score: {}".format(self.word, self.score)

    word = models.CharField(
        verbose_name="French word", unique=True, max_length=50)
    score = models.IntegerField(verbose_name="Score",
                                validators=[MaxValueValidator(2, "Score value greater than 2"),
                                            MinValueValidator(-2,
                                                              "Score value less than -2"),
                                            NotEqualTo0])


class ItalianWord(models.Model):

    def __str__(self):
        return u"word: {} - score: {}".format(self.word, self.score)

    word = models.CharField(
        verbose_name="Italian word", unique=True, max_length=50)
    score = models.IntegerField(verbose_name="Score",
                                validators=[MaxValueValidator(2, "Score value greater than 2"),
                                            MinValueValidator(-2,
                                                              "Score value less than -2"),
                                            NotEqualTo0])
--8<---------------cut here---------------end--------------->8---

rhunwicks writes:

> Please can you post the models.py too
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/django-import-export/django-import-export/issues/268#issuecomment-103964188

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by rhunwicks** [comment]
And does the file you are importing from have columns for just name and score, or does it also include an id column?

Incidentally, is there are a reason for separate models for FrenchWord and ItalianWord rather than a single ScoredWord with columns for word, score and language (with choices of French or Italian).

Extending that model to support additional languages would be trivial, whereas the approach using separate models per language means duplicating the model and the resource and the admin for each new language - although you could reduce that by subclassing

**Comment by shackra** [comment]
The file included the id field too, because django-import-export was complaining it wasn't included in the file.

I did the separation as requested by my client; my first approach was having everything in a single table...

**Comment by rhunwicks** [comment]
I think you need to remove the `id` column from the file and 

```
import_id_fields = ('word',)
```

to each Resource `Meta` class.

Without talking to your client to understand their reasoning, I can't know if there is a valid reason for separating the data into separate tables, but I doubt it.

If they insist I would still be aiming for a single Word class/table with proxy subclasses for ItalianWord and FrenchWord, and a subclassed Manager, e.g.

```
class ItalianWordManager(models.Manager):
    def get_queryset(self):
        return super(ItalianWordManager, self).get_queryset().filter(language='it')
```

**Comment by shackra** [comment]
Thank you very much, @rhunwicks your advice solved my issue successfully!

**Comment by serrrgggeee** [comment]
hello I'm trying clean two fields to  model, like hear
`class PlaceWidget(widgets.ForeignKeyWidget):
	def clean(self, value):
		print 'value', value
		return self.model.objects.get_or_create(name = value,continent = value )[0]`
but in this case it's the one name 'value', I get this like here
`country = fields.Field(column_name='country', attribute='country', widget=PlaceWidget(Country, 'name'))`
and this for name, and I wana get for continent two and to insert it to one string in database if I do this case
`country = fields.Field(column_name='country', attribute='country', widget=PlaceWidget(Country, 'name'))
	continent = fields.Field(column_name='continent', attribute='continent', widget=PlaceWidget(Country, 'continent'))`
I have two read in database, How can I do it. Thanks so much, and sory for my english.
