### ISSUE TITLE
Import unique - duplicate key value violates unique constraint

### ISSUE THREAD

**Issue by maltitco** [django-import-export/django-import-export#273]
Why does not ignore the unique value fields that already exist?

duplicate key value violates unique constraint "expenses_expensestype_expenses_type_key"
DETAIL:  Key (expenses_type)=(Sprzedaz) already exists.

```
class ExpensesTypeResource(resources.ModelResource):
    class Meta:
        model = ExpensesType
        skip_unchanged = True
        report_skipped = True

```

![zrzut ekranu 2015-05-23 o 13 09 42](https://cloud.githubusercontent.com/assets/1561204/7783750/549a7b06-014d-11e5-96fe-0101267a292a.png)

**Comment by manelclos** [comment]
Hi @maltitco, as there is no value in the "id" column, the rows are supposed to be new values. Maybe if you know "expenses_type" is unique you can use it as the row identification?

**Comment by maltitco** [comment]
Hi, expenses_type is unique:

```
expenses_type = models.CharField(max_length=255, unique=True)
```
if I set "expenses_type" as import_id_fields = ('expenses_type',)  I still have the error: already exists

**Comment by maltitco** [comment]
I found the correct configurations

```
class ExpensesTypeResource(resources.ModelResource):
    class Meta:
        model = ExpensesType
        skip_unchanged = True
        report_skipped = True
        import_id_fields = ('expenses_type',)
        fields = ('expenses_type',)
```
