### ISSUE TITLE
0 is interpreted as None in all widgets when importing from xls.

### ISSUE THREAD

**Issue by gauravdott** [django-import-export/django-import-export#274]
Can anybody tell me how to solve this problem?

**Comment by manelclos** [comment]
Hi @gauravdott, I haven't still played with widgets. For XLS I usually subclass XLS Format class and then override the create_dataset function. It is quite easy and gives you full control. See create_dataset function: https://github.com/django-import-export/django-import-export/blob/master/import_export/formats/base_formats.py#L173

**Comment by manelclos** [comment]
Hi @gauravdott, can you test latest import_export code in git to see if it solves this issue?
