### ISSUE TITLE
How to apply it on the frontend side?

### ISSUE THREAD

**Issue by maltitco** [django-import-export/django-import-export#275]
Is there an example of how to use on user side?

**Comment by manelclos** [comment]
Hi @maltitco can you please add more information to your question? I don't understand what you are trying to do.

**Comment by maltitco** [comment]
I would allow the import from applications - not from admin panel.

**Comment by manelclos** [comment]
You probably mean this: https://django-import-export.readthedocs.org/en/latest/getting_started.html#importing-data

See if it helps.

**Comment by maltitco** [comment]
Thanks I'll try it.

**Comment by manelclos** [comment]
Perfect! reopen if needed!

**Comment by maltitco** [comment]
I have a new problem (on frontend).
Data are loaded but after approval refreshes the page and I have information: "This field is required" over the File field.

link to code: http://wklej.org/hash/30ac274b704/

![zrzut ekranu 2015-05-27 o 15 16 10](https://cloud.githubusercontent.com/assets/1561204/7853806/5d9910cc-0513-11e5-84c3-73ccb069632f.png)
![zrzut ekranu 2015-05-27 o 15 15 52](https://cloud.githubusercontent.com/assets/1561204/7853807/5d9d96ce-0513-11e5-95cb-706ab6e6217a.png)
