### ISSUE TITLE
django-import-export skipping the values of ManyToManyField

### ISSUE THREAD

**Issue by gauravdott** [django-import-export/django-import-export#276]
I am trying to import a model via the admin interface but for some reason it skips the values of Many to Many field

PFA screenshot of excel file and admin interface. Any help is appreciated.
![screen shot 2015-05-25 at 9 42 41 pm 2](https://cloud.githubusercontent.com/assets/869769/7799711/261b1980-0327-11e5-8dee-8f304423c8e0.png)
![screen shot 2015-05-25 at 9 43 07 pm 2](https://cloud.githubusercontent.com/assets/869769/7799714/2f8b4576-0327-11e5-9eb0-f9f009c17bed.png)

**Comment by manelclos** [comment]
Hi @gauravdott, how does your resource class look like?

**Comment by gauravdott** [comment]
Never mind, the thread is quite old so I wrote a custom parser to import the data as I needed it for testing only.

Thanks anyway.

**Comment by alexavenger** [comment]
I have exactly the same problem and I have it also in your test APP. 
I've opened the Books-sample and split it in columns and saved it as in .xlsx
Then I import it and categories is Blank as you can see. 

![image](https://user-images.githubusercontent.com/47525730/88810137-44b1a500-d1b5-11ea-89fb-3b62367f9c58.png)
