### ISSUE TITLE
Way to allow export in pdf

### ISSUE THREAD

**Issue by Gustavosdo** [django-import-export/django-import-export#277]
Is there any possibility of including the export option for a .pdf format?

I'm using the django-import-export in my projects, and I've been thinking about the option of exporting files in PDF format.
But I do not want to leave this option on another button, functioning differently.
I want to focus all options on the same page of django export-import-export.
![Example of Export](https://dl.dropboxusercontent.com/u/80415688/export_django.png)

Is it feasible I customize to make it work?
What is the simplest way to do it?

Ps: I know that is not the purpose of the project, but I think it would be a great choice for the end user.

**Comment by manelclos** [comment]
Hi @Gustavosdo you can subclass Format (https://github.com/django-import-export/django-import-export/blob/master/import_export/formats/base_formats.py#L30) and add it to the available formats option in the admin class (https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L72).

We need to properly document this way of importing/exporting data.

**Comment by Gustavosdo** [comment]
Got it, thanks @manelclos !

**Comment by SalahAdDin** [comment]
Can you put a full example here?

**Comment by emfrigo** [comment]
I have the same issue, there's a way or an example to add a custom pdf format?

**Comment by TrungKien1230** [comment]
@gustavo-sdo did you have solution for it ? Do you know how to export in .pdf the data in admin interface ?

**Comment by gustavo-sdo** [comment]
@TrungKien1230 we ended up not using the resources of django-import-export. We did it on the outside using [django-easy-pdf](https://github.com/nigma/django-easy-pdf) to generate reports within the admin.

**Comment by TrungKien1230** [comment]
@gustavo-sdo  nice, could you please give me an example with django-easy-pdf ?. I'm trying to print report in .pdf with admin too. Thanks in advance

**Comment by gustavo-sdo** [comment]
Install the _django-easy-pdf==0.2.0.dev1_

Considering that you have an application called "**pdf**", follow the example below...

_pdf/urls.py_
```python
from django.conf.urls import url
from pdf.views import PDFDetailView

urlpatterns = [
    url(r'^pdfview/$', PDFDetailView.as_view(), name='pdf_view'),
]
```

_pdf/views.py_
```python
from django.apps import apps
from easy_pdf.views import PDFTemplateView

class PDFDetailView(PDFTemplateView):
    template_name = 'pdf/base.html'
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        
        # get the parameters values
        app_name = request.GET.get('app_name')
        model_name = request.GET.get('model_name')
        
        # get your model class
        class_name = apps.get_model(app_label=app_name, model_name=model_name)
        # make a query if you want to send objects to the template context
        objects = class_name.objects.all()
        
        context.update({
            'objects': objects,
            'text': 'printing some text...',
            'title': 'Example pdf page',
        })
        return self.render_to_response(context)
```

_templates/pdf/base.html_
```html
{% extends "easy_pdf/base.html" %}

{% block content %}
    <div id="content">
        <div class="main">
            <p>{{ text }}</p>
        </div>
    </div>
{% endblock %}
```

So, in your browser:
http://localhost:8000/pdf/pdfview/?app_name=your_appname&model_name=your_modelname

Change _your_appname_ and _your_modelname_ according to the model you have.
In this way, you can handle several parameters in the views.py, according to the report you want to generate.

**Comment by TrungKien1230** [comment]
@gustavo-sdo, I have always this error, do you know how to solve it ? 


 File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by gustavo-sdo** [comment]
> @gustavo-sdo, I have always this error, do you know how to solve it ?

The command below will probably solve this problem: 
`>>> sudo apt-get install libpango1.0-0` 

If you are using windows, I recommend that you stop what you are doing and prepare a Linux environment for development. Believe in the voice of experience, working with linux will save you precious time. Installing certain libs on Windows is an unnecessary headache.
In addition, you do not need to leave the windows platform to have a working environment with linux. Learn more about Windows WSL... It's native.

**Comment by TrungKien1230** [comment]
@gustavo-sdo thank you very much, I'm tarting thinking about your advice. ^^

**Comment by DeepikaSharma5** [comment]
Can anyone tell me how to export django models (data) as pdf in django admin.
Just like exporting as CSV file
