### ISSUE TITLE
Cannot import django-osm-field empty latitude and longitude fields after exporting

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#284]
Django 1.7.7, django-import-export 0.2.7, importing file that I've just exported, I'm getting

> Line number: 1 - [u"\u0417\u043d\u0430\u0447\u0435\u043d\u043d\u044f '' \u043f\u043e\u0432\u0438\u043d\u043d\u0435 \u0431\u0443\u0442\u0438 \u0447\u0438\u0441\u043b\u043e\u043c \u0437 \u043f\u043b\u0430\u0432\u0430\u044e\u0447\u043e\u044e \u043a\u0440\u0430\u043f\u043a\u043e\u044e."]

> Traceback (most recent call last):
> File "/var/www/chesno2/venv/local/lib/python2.7/site-packages/import_export/resources.py", line 360, in import_data
> self.import_obj(instance, row, real_dry_run)
> File "/var/www/chesno2/venv/local/lib/python2.7/site-packages/import_export/resources.py", line 226, in import_obj
> self.import_field(field, obj, data)
> ValidationError: [u"\u0417\u043d\u0430\u0447\u0435\u043d\u043d\u044f '' \u043f\u043e\u0432\u0438\u043d\u043d\u0435 \u0431\u0443\u0442\u0438 \u0447\u0438\u0441\u043b\u043e\u043c \u0437 \u043f\u043b\u0430\u0432\u0430\u044e\u0447\u043e\u044e \u043a\u0440\u0430\u043f\u043a\u043e\u044e."]

The encoded line is

    Значення '' повинне бути числом з плаваючою крапкою.

which translates to

    Value '' must be a float

**Comment by int-ua** [comment]
It worked after adding
```
location_lat = fields.Field(widget=DecimalWidget)
location_lon = fields.Field(widget=DecimalWidget)
```
to the resource.

**Comment by int-ua** [comment]
No, not really worked, now all the values are just empty. Looks like we need a FloatWidget.

**Comment by int-ua** [comment]
It worked only after creating FloatWidget and explicitly defining attributes for the fields:

```
class FloatWidget(Widget):
    def clean(self, value):
        if value != "":
            return float(str(value).replace(',', '.'))
        return None


class SomeResource(resources.ModelResource):
    location_lat = fields.Field(attribute='location_lat', widget=FloatWidget())
    location_lon = fields.Field(attribute='location_lon', widget=FloatWidget())
...
```

**Comment by SalahAdDin** [comment]
There will be some mistake with django-smart-selects field?

**Comment by int-ua** [comment]
What mistakes exactly? Haven't used `django-smart-selects` yet.
