### ISSUE TITLE
django-jsonfield imported as string

### ISSUE THREAD

**Issue by wasabigeek** [django-import-export/django-import-export#285]
I'm currently using [django-jsonfield](https://github.com/bradjasper/django-jsonfield/) and wanted to import the JSON object through django-import-export. Unfortunately (?) it escapes and saves the JSON as a string.

Hope I'm not asking too much!

**Comment by manelclos** [comment]
Hi @wasabigeek can you provide a one-row data sample? Also, which format are you using to import? What does the jsonfield expect as input, a unicode string?

**Comment by manelclos** [comment]
Hi @wasabigeek, I've taken a look at django-jsonfield and as expected, it serializes the JSON data to a string. If your input data is already serialized to a string, it should work. If your input data is in json format, then you need to json.dumps it and use the value in a tablib dataset.

**Comment by rudyryk** [comment]
Here's my model sample:

```python
class Tag(models.Model):
    slug = models.SlugField("slug", max_length=100, unique=True)
    name = JSONField("name", default=dict, blank=True)
```

Here's exported data sample:

```json
[
  {
    "id": 1,
    "slug": "creative",
    "name": "{'en': 'creative', 'ru': '\u0442\u0432\u043e\u0440\u0447\u0435\u0441\u0442\u0432\u043e'}"
  }
]
```

Expected:

```json
[
  {
    "id": 1,
    "slug": "creative",
    "name": {"en": "creative", "ru": "\u0442\u0432\u043e\u0440\u0447\u0435\u0441\u0442\u0432\u043e"}
  }
]
```

**Comment by rudyryk** [comment]
I'm using standard `django.contrib.postgres.fields.JSONField` in the sample above.

**Comment by narwhaljames** [comment]
I was able to add JSONField support in my resources by doing this:

```
import json
from import_export import widgets

class JSONWidget(widgets.Widget):
    """ Convert data into JSON for serialization.
    """
    def clean(self, value, row=None, *args, **kwargs):
        return json.loads(value)

    def render(self, value, obj=None):
        if value is None:
            return ""
        return json.dumps(value)


class JSONResourceMixin(object):
    """ Override ModelResource to provide JSON field support.
    """
    @classmethod
    def widget_from_django_field(cls, f, default=widgets.Widget):

        if f.get_internal_type() in ('JSONField', ):
            return JSONWidget
        else:
            return super().widget_from_django_field(f)

```

And then when defining a resource that has a JSONField:

```
class MyResource(JSONResourceMixin, resources.ModelResource):
    ...
```

**Comment by ShaheedHaque** [comment]
Now that Django 2.0 has JSONField packaged in, any chance the JSONField support from @narwhaljames could be integrated. I just managed to recover from a rather nasty corruption due to me not noticing that JSONField was not supported?

**Comment by joshua-s** [comment]
This needs to be fixed

**Comment by joshua-s** [comment]
Could we revisit this? It is also corrupting my imports/exports.

**Comment by andrewgy8** [comment]
Hi @joshua-s! Im working on a branch which will address this issue. I hope to have it in soon!

**Comment by andrewgy8** [comment]
This should be solved in the next release

**Comment by ton77v** [comment]
@narwhaljames thanks! it works, although I can't figure out how the JSON should be formatted, i.e. what delimiter should I use between the properties? I'm using CSV

`,{"key": `"value"},

works OK

But if I need
`,{"key1": `"value1", "key2":"value2"},

I'm getting exception "InvalidDimensions encountered while trying to read file: ..."

Tried spaces and tabs, got error "Expecting ',' delimiter: line 1 column 13 (char 12)"
