### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by cubiczx** [django-import-export/django-import-export#286]
How I have to configure Django to django-import-export use the locale ES?

**Comment by manelclos** [comment]
Hi @cubiczx , it should be enough to change this in your settings.py:

    LANGUAGE_CODE = 'es'

**Comment by cubiczx** [comment]
My setings:
# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'es'

gettext = lambda s: s
LANGUAGES = (
    ('es', gettext('Spanish')),
)

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.
USE_L10N = True

TEMPLATE_CONTEXT_PROCESSORS = TCP + (
...
    "django.core.context_processors.i18n",
...
)

MIDDLEWARE_CLASSES = (
...
    'django.middleware.locale.LocaleMiddleware',
)

**Comment by manelclos** [comment]
@cubiczx strange, I tested on a local installation before answering you. Are you using latest import-export version? which Django version?

**Comment by cubiczx** [comment]
Django==1.6.2
django-import-export==0.2.3

**Comment by manelclos** [comment]
Good, there were no spanish translation in 0.2.3 (https://github.com/django-import-export/django-import-export/tree/0.2.3/import_export/locale). You need to update to 0.2.7 to get spanish translation.

**Comment by cubiczx** [comment]
How do I download the latest version for my Django?

**Comment by manelclos** [comment]
Django version 1.6 is still supported, just try

    pip install django-import-export --upgrade

**Comment by SalahAdDin** [comment]
Is there a transifex project for django-impor-export project?

**Comment by manelclos** [comment]
@SalahAdDin I don't know, @bmihelac ?

**Comment by cubiczx** [comment]
I unistall and install and get new version
