### ISSUE TITLE
Leading zero stripped from phone number

### ISSUE THREAD

**Issue by sebastien-christy-neomades** [django-import-export/django-import-export#289]
I have a 'phone' column declared as this:
phone = models.CharField(max_length=10, null=True, blank=True)

In the data some phone numbers starts with a zero.
When this data is exported, the leading zero is removed from the value.

**Comment by manelclos** [comment]
Hi @sebastien-christy-neomades, which format are you exporting to? happens with other formats as well?

**Comment by sebastien-christy-neomades** [comment]
I'm exporting to XLSX. I haven't tried other formats, I will do some tests now.

**Comment by sebastien-christy-neomades** [comment]
I don't have the problem when exporting to CSV (I've tested also XLS and JSON but the export fails).
May be the problem is not in the exported data but in the way the column is interpreted: the values seems to be interpreted as numbers instead of text.

**Comment by bmihelac** [comment]
Here is quick test using tablib:

    import tablib
    data = tablib.Dataset(*[('004', 'Reitz', 23), ('Bessie', 'Monke', 22)],headers=['First Name', 'Last Name', 'Age'])
    data.json # ok 004 interpreted as text
    open('test.xlsx', 'wb').write(data.xlsx) # not ok 004 interpreted as number
    open('test.xls', 'wb').write(data.xls) # ok 004 interpreted as string

This should be reported and fixed (if it is not already) in tablib.

**Comment by sebastien-christy-neomades** [comment]
OK, thank you. I found this issue: https://github.com/kennethreitz/tablib/issues/39,
I will leave a comment.
