### ISSUE TITLE
django.utils.deprecation.RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9

### ISSUE THREAD

**Issue by synotna** [django-import-export/django-import-export#290]
File "/home/tech/.pyenv/versions/partner-backend-2015-06-16/lib/python3.4/site-packages/import_export/formats/base_formats.py", line 22, in <module>
    from django.utils.importlib import import_module
  File "/home/tech/.pyenv/versions/partner-backend-2015-06-16/lib/python3.4/site-packages/django/utils/importlib.py", line 9, in <module>
    RemovedInDjango19Warning, stacklevel=2)
django.utils.deprecation.RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

**Comment by manelclos** [comment]
Hi @synotna, this is already fixed (https://github.com/django-import-export/django-import-export/commit/fe0d9477699ce8467d62edc23240dcc71a64b743).

You can use the github version if it is not an inconvenience to you.

Maybe it is time for a new release including new fixes. @bmihelac ?

**Comment by bmihelac** [comment]
@manelclos agree, would make new release, contact me if you think anything is needed before publishing 0.2.8

**Comment by synotna** [comment]
I must have been doing something very stupid or was completely blind yesterday: I swear I did check before opening an issue, and I do clearly see the issues now :)

Apologies, closing!
