### ISSUE TITLE
Import csv, crashes when id is left empty

### ISSUE THREAD

**Issue by kgoudak** [django-import-export/django-import-export#291]
Hi and congrats for the great work you've done.

I would like to ask for an issue that some other guys asked previously, but I can't seem to get this to work after reading the other threads.

I'm trying to import a csv, for a very simple model, which has no explicit id.

Here is my model:

class Constants(models.Model):
    multiplier_one = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    multiplier_two = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)

The error that I'm getting is the following:

Traceback (most recent call last):
  File "/home/vagrant/pyenv/versions/cca/lib/python3.4/site-packages/import_export/resources.py", line 348, in import_data
    row_result.object_repr = force_text(instance)
  File "/home/vagrant/pyenv/versions/myapp/lib/python3.4/site-packages/django/utils/encoding.py", line 83, in force_text
    s = six.text_type(s)
TypeError: %d format: a number is required, not NoneType

At the CSV that I'm importing, I have named the first column as "id" and left it empty

Can you please help me find out what I'm possibly doing wrong?

Thank you

**Comment by manelclos** [comment]
Hi @kgoudak, which import_export version are you using? could you check latest github version? It would help to have the resource class too. We should be able to catch this type of errors and give some useful feedback...

**Comment by kgoudak** [comment]
Hi @manelclos,

thank you for your quick reply.

I'm using v0.2.6 and here is the resource class I have:

class ConstantsResource(resources.ModelResource):
    
    class Meta:
        model = Constants

**Comment by manelclos** [comment]
Hi @kgoudak, I can't reproduce with latest version in github and also with latest release 0.2.7. Can you please check any of those versions? my CSV looks like this:

    id,multiplier_one,multiplier_two
    ,1.50,2.50

**Comment by kgoudak** [comment]
Hi @manelclos, 

I just tried with version 0.2.7 and it produces the same error.

here is my CSV:
id,multiplier_debt_sales,multiplier_current_ratio
,9.5,8.5

and this is my Admin class (I don't know if it helps)

class ConstantsAdmin(ImportExportModelAdmin):

    resource_class = ConstantsResource
    pass

**Comment by kgoudak** [comment]
ok. I don't know exactly what the problem was, but now it works.

What I did was that I migrated to version 0.2.7 and I have dropped the database, and then:
makemigations
migrate

and when I ran it, it worked  :|

Anyway, thank you for your time and help

**Comment by manelclos** [comment]
@kgoudak at first I thought it was the field names being different, but I tested and makes no diference when trying to reproduce the problem. Glad it worked. Always use latest version ;) continuos fixing going on! :)

**Comment by Braintelligence** [comment]
I had the exact same problem. I worked with this package for HOURS until I found the "sweet spot" (which in hindsight I had found many times before but something was blocking the succesful import...). Only after dropping the whole table and all migrations and migrating from scratch this here worked.

Maybe this shouldn't be closed but rather very well investigated!
