### ISSUE TITLE
Override get_export_order

### ISSUE THREAD

**Issue by raoulalobo** [django-import-export/django-import-export#292]
hi , i'm new in django please how can override the get_fields or get_export_order , i want to use request parameter like this def get_export_order(self, request ):

**Comment by manelclos** [comment]
Hi @raoulalobo, the get_export_order function in the Resource class does not provide the request parameter. I'd go for setting the export_order option from your view, which will have access to the request, everytime you need and before making use of the resource. Does this makes sense to you?

**Comment by raoulalobo** [comment]
@manelclos ,i untersdand a little , but i work with admin integration , which view must i modificate ?

**Comment by manelclos** [comment]
@raoulalobo, are you changing export order everytime?

**Comment by raoulalobo** [comment]
i want to have custom export order depends on the user group

**Comment by raoulalobo** [comment]
@manelclos Sorry for my englhis

**Comment by manelclos** [comment]
Not sure if this works, but the I'd go this way:

Override get_export_data: https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L305

Something like this (untested):

        resource_class = self.get_export_resource_class()
        rc = resource_class()
        rc.export_order = ('id', 'name')  # modify according to your needs
        data = rc.export(queryset)
        export_data = file_format.export_data(data)
        return export_data

Not sure if you can access self.request on that function.

Hope it helps!

**Comment by raoulalobo** [comment]
@manelclos thanks, i try

**Comment by raoulalobo** [comment]
@manelclos  I cannot access sefl.request on that function
