### ISSUE TITLE
Trouble with OneToOne relationships

### ISSUE THREAD

**Issue by jtiki** [django-import-export/django-import-export#293]
I have the following model to extend the built in django user model

    from django.db import models
    from django.contrib.auth.models import User

    class AARCUserInfromation(models.Model):
        STATES = (
            ('Alabama', 'AL'),
             ...
         )
    
    user = models.OneToOneField(User, related_name="additional_info")
    aarc_number = models.CharField(max_length=255, help_text="""AARC Memeber
                                   Number provided by the AARC""",
                                   verbose_name="AARC Member Number",
                                   blank=True, null=True)
    state = models.CharField(max_length=2, choices=STATES, default="MD",
                             blank=True, null=True)

  from django.contrib.auth.models import User

  from import_export import resources
  from import_export import fields

So I made the following resource to try and import from an Excel sheet.

    class UserResource(resources.ModelResource):
        aarc_member_number = fields.Field(attribute="additional_info__aarc_number",
                                                                   column_name="AARC Member Number")
        first_name = fields.Field(attribute='first_name', column_name="First Name")
        last_name = fields.Field(attribute='last_name', column_name="Last Name")
        email = fields.Field(attribute='email', column_name="Email")
        
        def before_save_instance(self, instance, dry_run):
            instance.username = "{}{}".format(instance.first_name,
                                                                   instance.last_name)
            instance.set_password(instance.email)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'id',
                    'aarc_member_number')

Everything imports and is setup correctly (user.username is set to first_name + last_name and the password is set to user.email after being hashed) except that the aarc_member_number isn't being honored correctly. Every time I try to import it is just ignored and left blank. Below is an example of the Excel sheet I'm uploading as well as the django admin output before processing.

![image](https://cloud.githubusercontent.com/assets/1173792/8335302/de597a46-1a6a-11e5-84e8-f5b33c0cda93.png)

Any help would be appreciated!

![screen shot 2015-06-24 at 12 17 34 pm](https://cloud.githubusercontent.com/assets/1173792/8335337/07e011a4-1a6b-11e5-9b38-4150ae7c7c05.png)

**Comment by manelclos** [comment]
Hi @jtiki, can you try without defining ``aarc_member_number`` and include ``additional_info__aarc_number`` in fields instead?

**Comment by jtiki** [comment]
@manelclos 

No luck:

    from django.contrib.auth.models import User

    from import_export import resources
    from import_export import fields


    class UserResource(resources.ModelResource):
        """
        aarc_member_number = fields.Field(attribute="additional_info__aarc_number",
                                          column_name="AARC Member Number")
        """
        first_name = fields.Field(attribute='first_name', column_name="First Name")
        last_name = fields.Field(attribute='last_name', column_name="Last Name")
        email = fields.Field(attribute='email', column_name="Email")

        def before_save_instance(self, instance, dry_run):
            instance.username = "{}{}".format(instance.first_name,
                                              instance.last_name)
            instance.set_password(instance.email)

        class Meta:
            model = User
            fields = ('first_name', 'last_name', 'email', 'id',
                      'additional_info__aarc_number')


![image](https://cloud.githubusercontent.com/assets/1173792/8335885/760cfa5e-1a6e-11e5-84d2-9516a0572761.png)

![screen shot 2015-06-24 at 12 41 27 pm](https://cloud.githubusercontent.com/assets/1173792/8335891/7be7aa50-1a6e-11e5-9100-d4dd68ff65c6.png)

**Comment by andilabs** [comment]
It is definetly not working for IMPORT. It work pretty fine for export only. The library claims to support OneToOneField.....:(

**Comment by bmihelac** [comment]
I confirm that this would not work (at least not out of a box).

django-import-export can set relation fields but would not change this instances.

This is expected behaviour and follows what Django does. For example, this would work in Django (from docs page):

    Blog.objects.values('name', 'entry__headline')

but this would not:

    Blog.objects.filter(pkl=1).update('entry__headline')

If there is need to change related instances it is would be possible to override ``import_obj`` and ``save_instance`` and track needed change in some private instance attribute.

Please reopen if needed.

**Comment by jtiki** [comment]
@bmihelac That is actually what I ended up doing, I just forgot I had this issue open.

For anyone interested this was the final result in the resources file:

    def after_save_instance(self, instance, dry_run):
        if not dry_run:
            more = AARCUserInformation(
                user=instance,
                aarc_number=instance.aarcinformation__aarc_number,
                state="")
            more.save()
            instance.aarcinformation = more
            instance.aarcinformation.save()
            instance.save()

**Comment by aidanlister** [comment]
I've done it this way:

```
    address = OneToOneField(
        attribute='address__freeform',
        parent_prop='address',
        child_prop='freeform',
        column_name='address',
    )
```

And then the OneToOne Field looks like:

```
class OneToOneField(fields.Field):
    parent_prop = ''
    child_prop = ''

    def __init__(self, parent_prop, child_prop, *args, **kwargs):
        self.parent_prop = parent_prop
        self.child_prop = child_prop
        super().__init__(*args, **kwargs)

    def save(self, obj, data):
        if not self.readonly:
            child_obj = getattr(obj, self.parent_prop, None)
            if not child_obj:
                raise ValueError('Unable to find %s on %s' % (self.parent_prop, obj))
            setattr(child_obj, self.child_prop, self.clean(data))
            child_obj.save()
```

**Comment by sassanh** [comment]
@jtiki it raises:
```
*** AttributeError: 'User' object has no attribute 'aarcinformation__aarc_number'
```

**Comment by sassanh** [comment]
@aidanlister I doubt if it works for importing new rows. You're raising an `ValueError` exception when `child_obj` does not exist and when you're importing new rows `child_obj` does not exist so it always raises an error. I guess you're using your code only for modifying already existing data. Am I missing something here?

**Comment by lwm** [comment]
Thanks @aidanlister! I've tested this and it surely works.

@bmihelac, would you be accepting PRs for this to make it into the core package?
