### ISSUE TITLE
auto fill id?

### ISSUE THREAD

**Issue by karlosss** [django-import-export/django-import-export#295]
I cannot find a way (neither in the documentation nor in the code) to import a CSV file without any id columns with id being automatically filled. I get Key Error:"id" instead when omitting the id column in my CSV. Any way to do this? If not, I would appreciate to include this feature as soon as possible. Thanks.

**Comment by bmihelac** [comment]
override ``get_instance(self, instance_loader, row)`` in your resource and return ``False``, this would shortcut trying to load existing instance.

See:

https://django-import-export.readthedocs.org/en/latest/import_workflow.html

**Comment by bmihelac** [comment]
I'm closing this, please reopen if needed.

**Comment by int-ua** [comment]
I've ended up writing this: https://github.com/django-import-export/django-import-export/issues/299#issuecomment-121084758
