### ISSUE TITLE
How to import CSV file without ID column?

### ISSUE THREAD

**Issue by 1st** [django-import-export/django-import-export#299]
Hello.

I need to import CSV file without ID column. I need to create new objects with auto-id field. Those what fails to insert (for example, if we have duplicated value for unique field) - we ignore and insert those what can be inserted without duplication error.

How to do this?

**Comment by int-ua** [comment]
I've just written a Resource for a similar task (id column is still present, but it can be completely empty), here it is, changed slightly:

```
class ModelNameResource(resources.ModelResource):
...
    def before_import(self, dataset, dry_run, **kwargs):
        id_index = dataset.headers.index('id')
        field_index = dataset.headers.index('field')

        try:
            for row_number in range(len(dataset.dict)):
                row = list(dataset.lpop())

                try:
                    row[id_index] = ModelName.objects.filter(
                        field=row[field_index])[0].pk
                except IndexError:
                    pass

                dataset.append(tuple(row))
        except Exception as e:
            info = sys.exc_info()
            ex_type, ex, tb = info
            traceback.print_tb(tb)
            print(type(ex_type), e)
```

The Exception part will not be needed once #259 code is released.

**Comment by 1st** [comment]
How to use this with current released version of django-import-export?

**Comment by sylvainblot** [comment]
@1st I use: (in my case I never import existing data)

```
    def before_import(self, dataset, dry_run, **kwargs):
        dataset.insert_col(0, col=["",]*dataset.height, header="id")

    def get_instance(self, instance_loader, row):
        return False
```

**Comment by jeffcjohnson** [comment]
I was able to import a CSV with auto-ids by defining the unique fields using import_id_fields.

In the code below, I have a table with id, regex, and a few more optional fields.  I loaded a single column CSV file with only regex in it.

```
class EmailFilterResource(ModelResource):
    class Meta:
        model = models.EmailFilter
        import_id_fields = ('regex',)
```

**Comment by unifiedsaad** [comment]
i have figure out the solution to import without ID column 
Here is code , Take a Look

        if request.method == 'POST':
        queryset = Client.objects.filter(company=company)
        company = Company.objects.get(id=company)
        person_resource = ClientResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']
        imported_data = dataset.load(new_persons.read().decode('utf-8'), format='csv')
        try:
            for row in dataset:
                client = Client()
                client.company = company
                client.title = row[0]
                client.first_name = row[1]
                client.last_name = row[2]
                client.email = row[3]
                client.position = row[4]
                client.company_name = row[5]
                client.vat_number = row[6]
                client.website = row[7]
                client.address = row[8]
                client.city = row[9]
                client.state = row[10]
                client.zip = row[11]
                client.country = row[12]
                client.phone = row[13]
                client.fax = row[14]
                client.notes = row[15]
                client.save()

        except Client.DoesNotExist:
            raise Http404("There is a Problem with The CSV")

    return render(request, 'import.html')

And my Resource Looks Like this

    class ClientResource(resources.ModelResource):
    company = fields.Field(
        column_name='company',
        attribute='company',
        widget=ForeignKeyWidget(Company, 'name'))

    class Meta:
        model = Client
        skip_unchanged = True
        report_skipped = True
        exclude = ('id', 'company', 'status', 'modified', 'created')
        import_id_fields = ['email']
