### ISSUE TITLE
How do you deal with server timeouts?

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#301]
Are there any way to mitigate timeouts while still using django-import-export?
Can you please elaborate on your methods more than in #206 ?
Update: Can I run import from CLI?

**Comment by bmihelac** [comment]
@int-ua you can configure web server so it does not time out, gunicorn has ``--timeout`` option, if you use it with nginx, there is ``proxy_connect_timeout`` setting.

See this gist for django management command that imports resource (it is working for me but I did not have a time to iron it for inclusion in project)

https://gist.github.com/bmihelac/8271651bfde107d163ad

**Comment by bmihelac** [comment]
please reopen if needed

**Comment by andybak** [comment]
@bmihelac - that gist is a 404. It would be really handy to have something in the docs about command line usage.

**Comment by diogosimao** [comment]
If running Django with Apache it might log: `Timeout when reading response headers from daemon process`
