### ISSUE TITLE
BigIntegerField doesn't get recongnized as IntegerWidget

### ISSUE THREAD

**Issue by luto** [django-import-export/django-import-export#302]
[`ModelResource.widget_from_django_field`](https://github.com/django-import-export/django-import-export/blob/95722b924741dd7b2bfc4a461066cd662d3b209a/import_export/resources.py#L548-L550) only reconizes `IntegerField`, `PositiveIntegerField`, `PositiveSmallIntegerField`, `SmallIntegerField` and `AutoField` as integers.
This means that djangos [`BigIntegerField`](https://docs.djangoproject.com/en/1.8/ref/models/fields/#bigintegerfield) doesn't the `IntegerWidget` automatically, so it has to be manually.

Is there anything wrong with just adding `BigIntegerField` to the list?

**Comment by bmihelac** [comment]
Hi @luto, I don't see any reason why this should not be added. Do you want to open a pull request?
