### ISSUE TITLE
django.utils.importlib will be removed in Django 1.9.   return f(*args, **kwds)

### ISSUE THREAD

**Issue by mathijshoogland** [django-import-export/django-import-export#305]
Hi guys,

Great project! But when I use django-import-export with python 3.4, Django 1.8, I get the following warning:
django.utils.importlib will be removed in Django 1.9.
  return f(_args, *_kwds)

Do you guys know how to solve this?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by bmihelac** [comment]
Hi @MathijsHoogland. Thanks for report. I think we can safely use Pyhton 2.7 importlib instead of deprecated ``django.utils.importlib``.

    import django.utils.importlib

would became:

    import importlib

We already stopped supporting Python 2.6 so there is no need for any note regarding this.

Do you wan tto make a pull request?
