### ISSUE TITLE
Many to Many over multiple rows

### ISSUE THREAD

**Issue by billdozr** [django-import-export/django-import-export#308]
I was wondering if there is a way to represent the many-to-many relations over multiple rows?

For instance, if I have a Worker model with many-to-many field for OperatingArea model, how would I have that represented in tabular form like this:

ID, NAME, ZIP-CODE
1, Joe, 4050
1, Joe, 3192 
1, Joe, 4053
4, Adam, 2099
4, Adam, 3004
23, Phil, 7077

So Joe, with worker ID 1 has 3 operating areas (4050, 3192, 4053).

As of this writing, the default is that the model will represent the many-to-many as a single field, comma delimited, value.

**Comment by billdozr** [comment]
Seems that by overriding the Resource export method, I could change the way the data is appended. Would this be the recommended way to go in this sort of a case?

**Comment by bmihelac** [comment]
I am not sure about recommended way, but maybe exporting OperatingArea  and including all Worker fields is sensible solution for your case.
