### ISSUE TITLE
Times change from pm to am on import

### ISSUE THREAD

**Issue by jtiki** [django-import-export/django-import-export#310]
So I am importing a large number of records from an xls sheet that looks like the following:

<img width="1385" alt="screen shot 2015-08-23 at 3 52 31 pm" src="https://cloud.githubusercontent.com/assets/1173792/9429926/03b8a01e-49af-11e5-8f81-529c2d4a7abd.png">

But then when I actually confirm the import some of the values are changed from pm to am:

<img width="1247" alt="screen shot 2015-08-23 at 3 53 54 pm" src="https://cloud.githubusercontent.com/assets/1173792/9429928/345088ae-49af-11e5-9e27-306906ef51bd.png">

Notice it does not happen with all of the records, it seems to only happen with records listed between 1pm - 5pm.

I will also attach a clip from the excel sheet:

<img width="1013" alt="screen shot 2015-08-23 at 3 55 04 pm" src="https://cloud.githubusercontent.com/assets/1173792/9429933/60d6994a-49af-11e5-906b-9e867d8da2f6.png">

And my resource model for reference:

<img width="671" alt="screen shot 2015-08-23 at 3 55 46 pm" src="https://cloud.githubusercontent.com/assets/1173792/9429934/746073c8-49af-11e5-9d15-775bf53f2f51.png">

**Comment by bmihelac** [comment]
@jtiki it looks that all time fields are imported as AM time, is that right?

**Comment by jtiki** [comment]
@bmihelac Yes, it appears times from 1pm - 5pm are changed by 12 hours (e.g. 1pm becomes 1am).

**Comment by bmihelac** [comment]
As I see, `time_start` field is defined as string in both excel and resource and as time field in your model. django-import-export would interpret it as a string and db backend would probably strip the part that it does not understand (`pm` part).

You could make your own widget that would parse time from string and use that. 

Even better, you could use proper time field in excel and write widget that would parse excel time field similar to what  `ExcelDateWidget`  does.
