### ISSUE TITLE
How to override methods from extended UserAdmin model?

### ISSUE THREAD

**Issue by p3k** [django-import-export/django-import-export#314]
I am currently using the method described in the [Django 1.4 docs](https://docs.djangoproject.com/en/1.4/topics/auth/#adding-userprofile-fields-to-the-admin) for extending the user admin with extra properties and methods in a Django 1.8 setup, and I am not able to make use of advanced features of django-import-export.

(This documentation is not available in newer versions. Is this not the preferred way to extend the user model, anymore?)

E.g. any attempt to override a method (e.g. `before_import()`) simply fails. Here is an excerpt of my code:

```python
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin

from import_export import resources
from import_export.admin import ImportExportMixin

class UserProfileResource(resources.ModelResource):
  def before_import(self, dataset, dry_run):
    print 123

  class Meta:
    model = UserProfile

class UserProfileAdmin(ImportExportMixin, UserAdmin):
  …

admin.site.unregister(User)
admin.site.register(User, UserProfileAdmin)
```

(Please let me know if you think details of `UserProfileAdmin` might be important to solve the issue.)

I’d expect to see `123` in the log output whenever I import user data but this is not the case.

Digging a little bit deeper in the django-import-export code I found that the actual resource class seems to be not the one I desire.

This is the output when I log its value and the corresponding model from within the method `get_resource_class()` in [line 117 of admin.py](https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L117) 

```python
def get_resource_class(self):
  print self.model
  print modelresource_factory(self.model)
  …

<class 'django.contrib.auth.models.User'
<class 'import_export.resources.UserResource'>
```

IMHO it should be `UserProfile` and `UserProfileResource` instead.

Of course, I simply tried to rename my resource class to `UserResource` but it did not help.

Is there a work-around for this issue? I am aware that this could be unrelated to django-import-export and rather lie in the nature of Django mixins but I would be glad about any help, anyway.

Cheers,
tobi

**Comment by p3k** [comment]
Could it be that overriding the resource methods is generally broken? I just file another issue, #315.

**Comment by bmihelac** [comment]
It seems you forgot to set ``resource_class = UserProfileResource`` in your admin class.

Please reopen if problems persists.

**Comment by p3k** [comment]
Thanks, adding `resource_class` to admin class solved the issue.
