### ISSUE TITLE
Override of resource methods broken?

### ISSUE THREAD

**Issue by p3k** [django-import-export/django-import-export#315]
If I try to override the `before_import()` method in the BookAdmin class of the test app (current Git clone) I do not get the desired output `123` in the log:

```python
class BookAdmin(ImportExportMixin, admin.ModelAdmin):
    list_filter = ['categories', 'author']

    def before_import(self, dataset, dry_run):
      print 123
```

Am I missing something?

**Comment by bmihelac** [comment]
``before_import`` is called in ``Resource`` class, so you should inherit from ``ModelResource`` and override ``before_import`` there.

**Comment by p3k** [comment]
Oops, my bad, sorry. Thanks for your help.
