### ISSUE TITLE
Import foreign keys that do not exist (creating new values in Foreign key)

### ISSUE THREAD

**Issue by yarnball** [django-import-export/django-import-export#318]
I am trying to import values which do not already exist my foreign key. I would like import/export to add these new values to the ForeignKey model.

I've tried adding "null/blank" to the models, but it still will not create (import) new values in the foreign key. The error I get is "DoesNotExist: x matching query does not exist."

Here is a sample of my Admin.py (which only imports to a foreign key if the values being imported already exist).

    store_name = fields.Field(column_name='store_name', attribute='Store', widget=widgets.ForeignKeyWidget(Store, 'store_name'))
    def clean(self, value):
            val = super(ForeignKeyWidget, self).clean(value)
            object, created = Store.objects.get_or_create(store_name='')
    class Meta:
        model = Product
        fields = ('id', 'second_name', 'product_name', store',)
        export_order = ('id', 'second_name', 'product_name')
        skip_unchanged = False
        report_skipped = False
        widgets = {
                'published': {'format': '%d.%m.%Y'},
                }

Can anyone advise please?

Thanks

**Comment by yarnball** [comment]
I've just updated- it- I'm trying to use get_or_create. It did not work. I added:object, created = Store.objects.get_or_create(store_name=row[4])

Please direct me if you can.

**Comment by bmihelac** [comment]
@yarnball yes, you can use widget. 

If you subclass ``ForeignKeyWidget`` and override it's ``clean`` method to create object if it does not exists this should work.

https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L173-L207

**Comment by bmihelac** [comment]
Please reopen if needed.

**Comment by yarnball** [comment]
Thanks Bojan. I have made several attempts but still I have not been able to get it working. Could you please clarify with an example?

`class ProductResource(resources.ModelResource):

    store_name = fields.Field(column_name='store_name', attribute='Store', widget=widgets.ForeignKeyWidget(Store, 'store_name'))
    def clean(self, value):
            val = super(ForeignKeyWidget, self).clean(value)
            return self.model.objects.get(**{self.field: val}) if val else None
    class Meta:
        model = Store
        fields = ['store_name']
    class Meta:
        model = Product
        fields = ('id', 'second_name', 'product_name', 'store_name',)
        export_order = ('id', 'second_name', 'product_name')
        skip_unchanged = False
        report_skipped = False
        widgets = {
                'published': {'format': '%d.%m.%Y'},
                }`

**Comment by bmihelac** [comment]
Not tested, but something like this:

    from import_export import widgets


    class MyWidget(widgets.ForeignKeyWidget):

        def clean(self, value):
            if value:
                return self.model.objects.get_or_create(
                    name=val
                )

    # in resource
    store_name = fields.Field(column_name='store_name', attribute='Store',                     widget=widgets.MyWidget(Store))

**Comment by int-ua** [comment]
I've written it this way:

    class ForeignKeyWidgetWithCreation(ForeignKeyWidget):
        def __init__(
                self,
                model,
                field='pk',
                create=False,
                *args, **kwargs):
            self.model = model
            self.field = field
            self.create = create
            # super(ForeignKeyWidgetWithCreation, self).__init__(*args, **kwargs)

        def clean(self, value):
            val = super(ForeignKeyWidgetWithCreation, self).clean(value)
            if self.create:
                instance, new = self.model.objects.get_or_create(**{
                    self.field: val
                })
                val = getattr(instance, self.field)
            return self.model.objects.get(**{self.field: val}) if val else None

# Usage example
    class PersonInvolvementResource(Resource):
        field1 = fields.Field(
            attribute='field1',
            widget=ForeignKeyWidgetWithCreation(
                OtherModel,
                field='name',
                create=True))

**Comment by yarnball** [comment]
Thanks Bojan, 

Your method is neat and it 'almost' works.

`
class ProductResource(resources.ModelResource):

    store_name = fields.Field(column_name='store_name', attribute='Store', widget=widgets.ForeignKeyWidget(Store))
    def clean(self, value):
        if value:
            return self.model.objects.get_or_create(
                name=val
            )
`
It seems to look for the right value- but it says: ValueError: Column 'store_name': invalid literal for int() with base 10: 'My_new_value_to_import'

Any tips?

**Comment by bmihelac** [comment]
Yes, use debugger, insert this in line before one where exception is raised and then inspect variables:

    import pdb; pdb.set_trace()

**Comment by yarnball** [comment]
Ok so this works:

`class StoreWidget(widgets.ForeignKeyWidget):
    def clean(self, value):
    	return self.model.objects.get_or_create(store_name = value)[0]`

`class ProductResource(resources.ModelResource):

    store_name = fields.Field(column_name='store_name', attribute='Store', widget=StoreWidget(Store, 'store_name'))`

It's a really handy tool. Two issues still exist with it:

1. It imported the normalized values (ie values to foreign key) BEFORE the confirm import button is pushed. Can we this be over-ridden?

2. Can we make it non-case sensitive?

Thanks

**Comment by Braintelligence** [comment]
I second that. Is there an easy way to make this only execute on real import?

**Comment by patently-offensive** [comment]
Does anyone have this working in a many to many context, in particular a model with an m2m relationship with itself?

For example, I have a Product model, with an m2m relationship to itself to represent products that are competitive with each other. Example data:

> product_name  |  competes_with
> Product A         | Product C
> Product B         |
> Product C         | Product B, Product D

I need Product C to be created while importing row 1 and related to Product A and Product D to be created with importing row 3 and linked to Product C.

The below will create new values, but will only create an M2M relationship if the foreign key value already exists. In the above example: 
- C will be created, but not related to A
- B will be related to C on importing C
- D will be created, but not related to C

`class M2MCreateWithForeignKey(widgets.ManyToManyWidget):
	def __init__(self, model, separator=', ', field='pk', defaults=None, create=False):
		self.model = model
		self.separator = separator
		self.field = field
		self.defaults = defaults
		self.create = create

	def clean(self, value):
		values = filter(None, value.split(self.separator))

		if self.create:
			for v in values:
				self.model.objects.get_or_create(defaults=self.defaults, **{self.field:v})
			return super(M2MCreateWithForeignKey, self).clean(value)
		else:
			try:
				val = super(M2MCreateWithForeignKey, self).clean(value)
			except ObjectDoesNotExist:
				model_name = self.model.__name__
				error = "Imported data includes non-existant %s(s) (%s) "\
					"\nThis model does not support creating a new %s when importing data."\
					% (model_name, value, model_name)
				logger.error(error)
				return None
			else:
				return val`

**Comment by taime** [comment]
Got an error:
**clean() got an unexpected keyword argument 'row'**

`
class AuthorWidget(widgets.ForeignKeyWidget):
    def clean(self, value):
        return self.model.objects.get_or_create(author = value)[0]
`

`

class ProductResource(resources.ModelResource):
    author = fields.Field(column_name='author', attribute='author', widget=AuthorWidget(Author, 'title'))

    class Meta:
        model = Song
        fields = ( 'id', 'title', 'author' )
`

**Comment by int-ua** [comment]
https://github.com/django-import-export/django-import-export/commit/8e81b409aae501d1f882f4a4fd458112c2eccac1#diff-948ac927a7e0c8c8d0bb8026e9a49d62L288

**Comment by ToddMinear** [comment]
In case it helps someone else... I found the solution above failed when importing NULL values. Using a bit of Serhiy's code (from earlier in the thread) solved it:
`
```
class AuthorWidget(widgets.ForeignKeyWidget):
    def clean(self, value, row=None, *args, **kwargs):
        return self.model.objects.get_or_create(author = value)[0] if value else None


class ProductResource(resources.ModelResource):
    author = fields.Field(column_name='author', attribute='author', widget=AuthorWidget(Author, 'title'))

    class Meta:
        model = Song
        fields = ( 'id', 'title', 'author' )
```

`

**Comment by himay123** [comment]
from import_export import resources, fields,widgets
from inventory.models import Orders,Shipment,Item
import datetime
from import_export.widgets import ForeignKeyWidget,DateWidget,DateTimeWidget,CharWidget,DecimalWidget
from django.forms.widgets import TextInput
from decimal import Decimal
import json


class CustomDecimalWidget(widgets.DecimalWidget):
    DECIMAL_MAX_DIGITS = 8
    DECIMAL_MAX_PLACES = 2
    def clean(self, value, row=None, *args, **kwargs):
        if self.is_empty(value):
            return None
        elif 'NA' in value:
            return 0
        else:
            return value
        return utils.format_number(value, self.DECIMAL_MAX_DIGITS, self.DECIMAL_MAX_PLACES)
class ForeignKeyWidgetWithCreation(ForeignKeyWidget):
    def __init__(
            self,
            model,
            field='pk',
            create=False,
            *args, **kwargs):
        self.model = model
        self.field = field
        self.create = create
        # super(ForeignKeyWidgetWithCreation, self).__init__(*args, **kwargs)

    def clean(self, value):
        val = super(ForeignKeyWidgetWithCreation, self).clean(value)
        if self.create:
            instance, new = self.model.objects.get_or_create(**{
                self.field: val
            })
            val = getattr(instance, self.field)
        return self.model.objects.get(**{self.field: val}) if val else None
class StoreWidget(widgets.ForeignKeyWidget):
    def clean(self, value):
        return self.model.objects.get_or_create(Shipment = value)[0]
'''class convertnatovalue(TextInput):
    def _format_value(self, value):
        if 'NA' in value:
             return 0
        else:
            return value
    def render(self,value, attrs=None):
        value = self._format_value(value)
        return super(TextInput, self).render(value, attrs)'''
class OrderResource(resources.ModelResource):		
    order_id = fields.Field(column_name='Order Id', attribute="order_id")
    OrderedOn = fields.Field(column_name='Ordered On', attribute="OrderedOn",widget=DateWidget('%b %d, %Y'))
    Shipment = fields.Field(column_name='Shipment ID', attribute="Shipment" ,widget=StoreWidget(Shipment,'id'))
    order_item_id = fields.Field(column_name='ORDER ITEM ID', attribute="Item",widget=ForeignKeyWidget(Item, 'id'))
    hsn_code = fields.Field(column_name='HSN CODE', attribute="hsn_code")
    order_state = fields.Field(column_name='Order State', attribute="order_state")
    fsn = fields.Field(column_name='FSN', attribute="fsn")
    sku = fields.Field(column_name='SKU', attribute="sku")
    product = fields.Field(column_name='Product', attribute="product")
    invoice_no = fields.Field(column_name='Invoice No.', attribute="invoice_no")
    cgst = fields.Field(column_name='CGST', attribute="cgst",widget=CustomDecimalWidget())
    igst = fields.Field(column_name='IGST', attribute="igst",widget=CustomDecimalWidget())
    sgst = fields.Field(column_name='SGST', attribute="sgst",widget=CustomDecimalWidget())
    invoice_date = fields.Field(column_name='Invoice Date (mm/dd/yy)', attribute="invoice_date",widget=DateWidget('%x'))
    invoice_amount = fields.Field(column_name='Invoice Amount', attribute="invoice_amount")
    selling_price_per_item = fields.Field(column_name='Selling Price Per Item', attribute="selling_price_per_item")
    shipping_charge_per_item = fields.Field(column_name='Shipping Charge per item', attribute="shipping_charge_per_item")
    quantity = fields.Field(column_name='Quantity', attribute="quantity")
    price_contribution_subsidy = fields.Field(column_name='Price inc. FKMP Contribution & Subsidy', attribute="price_contribution_subsidy")
    buyer_name = fields.Field(column_name='Buyer name', attribute="buyer_name")
    ship_to_name = fields.Field(column_name='Ship to name', attribute="ship_to_name")
    address_line_1 = fields.Field(column_name='Address Line 1', attribute="address_line_1")
    address_line_2 = fields.Field(column_name='Address Line 2', attribute="address_line_2")
    city = fields.Field(column_name='City', attribute="city")
    state = fields.Field(column_name='State', attribute="state")
    pincode = fields.Field(column_name='PIN Code', attribute="pincode")
    dispatch_after_date = fields.Field(column_name='Dispatch After date', attribute="dispatch_after_date",widget=DateTimeWidget('%b %d, %Y %X'))
    dispatch_by_date = fields.Field(column_name='Dispatch by date', attribute="dispatch_by_date",widget=DateTimeWidget('%b %d, %Y %X'))
    form_requirment = fields.Field(column_name='Form requirement', attribute="form_requirment")
    tracking_id = fields.Field(column_name='Tracking ID', attribute="tracking_id")
    package_length_cm = fields.Field(column_name='Package Length (cm)', attribute="package_length_cm")
    package_breadth_cm = fields.Field(column_name='Package Breadth (cm)', attribute="package_breadth_cm")
    package_height_cm = fields.Field(column_name='Package Height (cm)', attribute="package_height_cm")
    package_weight_kg = fields.Field(column_name='Package Weight (kg)', attribute="package_weight_kg")
    ready_to_make = fields.Field(column_name='Ready to Make', attribute="ready_to_make")
  
    class Meta:
        model = Orders
        import_id_fields = ('order_id',)
        skip_unchanged = False
        report_skipped = False
        fields = ('order_id', 'OrderedOn', 'ShipmentID', 'order_item_id','hsn_code', 'order_state', 'fsn', 'sku', 'product', 'invoice_no', 'cgst', 'igst', 'sgst', 'invoice_date', 'invoice_amount', 'selling_price_per_item', 'shipping_charge_per_item', 'quantity', 'price_contribution_subsidy', 'buyer_name', 'ship_to_name', 'address_line_1', 'address_line_2', 'city', 'state', 'pincode', 'dispatch_after_date', 'dispatch_by_date', 'form_requirment', 'tracking_id', 'package_length_cm', 'package_breadth_cm', 'package_height_cm', 'package_weight_kg', 'ready_to_make',)
        widgets = {
            'published': {'format': '%d.%m.%Y'},
            }

**Comment by jongracecox** [comment]
@int-ua, I used [your post](https://github.com/django-import-export/django-import-export/issues/318#issuecomment-139989178) as a basis to implement my Many-to-many widget with creation. @patently-offensive, [your answer](https://github.com/django-import-export/django-import-export/issues/318#issuecomment-179551994) was helpful too.

## Many-to-Many Widget with object creation

```
from import_export.widgets import ManyToManyWidget
from django.db.models import QuerySet

class ManyToManyWidgetWithCreation(ManyToManyWidget):
    """A many-to-many widget that creates any objects that don't already exist."""

    def __init__(self, model, field="pk", create=False, **kwargs):
        self.model = model
        self.field = field
        self.create = create
        super(ManyToManyWidgetWithCreation, self).__init__(model, field=field, **kwargs)

        def clean(self, value, **kwargs):

        # If no value was passed then we don't have anything to clean.

        if not value:
            return self.model.objects.none()

        # Call the super method. This will return a QuerySet containing any pre-existing objects.
        # Any missing objects will be

        cleaned_value: QuerySet = super(ManyToManyWidgetWithCreation, self).clean(value, **kwargs)

        # Value will be a string that is separated by `self.separator`.
        # Each entry in the list will be a reference to an object. If the object exists it will
        # appear in the cleaned_value results. If the number of objects in the cleaned_value
        # results matches the number of objects in the delimited list then all objects already
        # exist and we can just return those results.

        object_list = value.split(self.separator)

        if len(cleaned_value.all()) == len(object_list):
            return cleaned_value

        # If we are creating new objects then loop over each object in the list and
        # use get_or_create to, um, get or create the object.

        if self.create:
            for object_value in object_list:
                _instance, _new = self.model.objects.get_or_create(**{self.field: object_value})

        # Use `filter` to re-locate all the objects in the list.

        model_objects = self.model.objects.filter(
            **{f"{self.field}__in": object_list}
        )

        return model_objects
```

##Usage

```
    categories = fields.Field(
        column_name="categories",
        attribute="categories",
        widget=ManyToManyWidgetWithCreation(
            model=models.Category,
            field="name",
            separator="|",
            create=True,
        ),
        default="",
    )
```

This approach should:
* Handle delimited lists of objects
* Create any missing objects when `create=True`
* Error in the same way as a normal ManyToManyWidget when `create=False`
* Handle lists of objects where some are missing and some are pre-existing

There are some cases where this might not work, for example, if a list of ID's are passed or if field values are non-string-based.

**Comment by manickam1999** [comment]
For for foreign key we can create a custom foreign key widget 

### ForeignKeyWidgetWithCreation

```
def clean(self, value, row=None, *args, **kwargs):
        try:
            return super(ForeignKeyWidgetWithCreation, self).clean(value, row, *args, **kwargs)
        except:
            return self.model.objects.create(**{self.field: value})
```

**Comment by Emmanuel-Aggrey** [comment]
This works for me 

from django.db import models
from import_export import fields
from import_export import resources

class ForeignKeyWidgetWithCreation(ForeignKeyWidget, models.Model):
    def clean(self, value, row=None, *args, **kwargs):
        try:
            return super(ForeignKeyWidgetWithCreation, self).clean(value, row, *args, **kwargs)
        except self.model.DoesNotExist:
            print(f"Object does not exist for {self.model.__name__} with {self.field}={value}. Creating...")
            obj, created = self.model.objects.get_or_create(**{self.field: value})
            if created:
                print(f"Object created successfully for {self.model.__name__} with {self.field}={value}")
            else:
                print(f"Object retrieved successfully for {self.model.__name__} with {self.field}={value}")
            return obj
        except Exception as e:
            print(f"Error creating/getting object for {self.model.__name__}: {e}")
            return e.args


class FactorResources(resources.ModelResource):

    country = fields.Field(
        column_name="country",
        attribute="country",
        widget=ForeignKeyWidgetWithCreation(Country, field="name"),
    )

    accuracy = fields.Field(
        column_name="accuracy",
        attribute="accuracy",
        widget=ForeignKeyWidgetWithCreation(AccuracyLevel, field="name"),
    )

    unit_of_measure = fields.Field(
        column_name="unit_of_measure",
        attribute="unit_of_measure",
        widget=ForeignKeyWidgetWithCreation(Unit, field="name"),
    )

    class Meta:
        model = FactorResource
        fields = [
            "id",
            "is_active",
            "unit_of_measure",
            "ghg_unit",
            "kg_CO2e",
            "kg_CO2e_of_CH4",
            "kg_CO2e_of_CO2",
            "kg_CO2e_of_N2O",
            "biogenic_kg_CO2e",
            "accuracy",
            "data_source",
            "period_start",
            "period_end",
            "country",
        ]

**Comment by Emmanuel-Aggrey** [comment]
c
