### ISSUE TITLE
Excel NA() values are imported as 42

### ISSUE THREAD

**Issue by rhunwicks** [django-import-export/django-import-export#323]
If you import an xls or xlsx file into a dataset using `XLS.create_dataset()` and one of the cells contains a `NA()` error value then the value of the imported cell in the dataset is 42.

That's probably not what you want in any circumstance.

See http://stackoverflow.com/questions/4928629/xlrd-excel-script-converting-n-a-to-42, for example.

I have filed a bug upstream at https://github.com/kennethreitz/tablib/issues/202

I'm not sure why we have overridden `create_dataset` in our XLS format, because the upstream one seems to do exactly the same thing as ours.

**Comment by bmihelac** [comment]
thanks @rhunwicks 

Regarding ``create_dataset`` it exists in our code because it was added to tablib after v0.9.11 which was for long time only released version.

**Comment by rhunwicks** [comment]
Should we drop it now then, and make `tablib>=0.9.11` explicit in
`requirements/base.txt`?

**Comment by bmihelac** [comment]
makes sense.
