### ISSUE TITLE
BooleanCastWidget: interpret arbitrary words as True/False for BooleanField

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#325]
I've just rewritten BooleanWidget to support adding possible True/False values as arguments.
Maybe it'll be useful for someone else too. AFAIU you can [safely] replace BooleanWidget with this code, backward compatibility included. Moving `["1", 1]` to the default value will also allow reverting 0/1 meaning.

```
class BooleanCastWidget(Widget):
    def __init__(
            self,
            true_values=[],
            false_value="0",
            case_sensitive=False,
            *args, **kwargs):
        if not case_sensitive:
            true_values = list(map(str.lower, true_values))
        self.true_values = true_values + ["1", 1]
        self.false_value = false_value
        self.case_sensitive = case_sensitive

    def render(self, value):
        if value is None:
            return ""
        return self.true_values[0] if value else self.false_value

    def clean(self, value):
        if value == "":
            return None
        if not self.case_sensitive:
            value = value.lower()
        return True if value in self.true_values else False
```

**Comment by bmihelac** [comment]
@int-ua please note that default arguments are evaluated at definition time in Python (see http://stackoverflow.com/questions/1651154/why-are-default-arguments-evaluated-at-definition-time-in-python).

maybe something like these would work better:

    class BooleanCastWidget(Widget):
        TRUE_VALUES = ["1", 1]
        FALSE_VALUE = "0"

        def __init__(
                self,
                true_values=None,
                false_value=None,
                case_sensitive=False,
                *args, **kwargs):
            if not true_values:
                true_values = self.TRUE_VALUES
            if not false_value:
                false_value = self.FALSE_VALUE
            if not case_sensitive:
                true_values = list(map(str.lower, true_values))
            self.true_values = true_values
            self.false_value = false_value
            self.case_sensitive = case_sensitive

**Comment by int-ua** [comment]
Yes, thanks a lot. Feel free to close this.
