### ISSUE TITLE
Model Admin is not showing Import export widgets

### ISSUE THREAD

**Issue by auvipy** [django-import-export/django-import-export#328]
Following are the codes in my admin.py, the code should  change the admin with import export options bt my admin remain the same as django default. what could be the problem?

from django.contrib import admin
from import_export import resources
from import_export.admin import ImportExportModelAdmin

from .models import HourlyData, TransectionData

# Register models here.

class HourlyDataResource(resources.ModelResource):

    class Meta:
        model = HourlyData
        fields = ('day1_total_hour', 'day2_total_hour')

class TransectionDataResource(resources.ModelResource):

    class Meta:
        model = TransectionData
        fields = ('date', 'cash_in', 'cash_out', 'send_money', )

class HourlyDataAdmin(ImportExportModelAdmin):
    resource_class = HourlyDataResource
    pass

class TransectionDataAdmin(ImportExportModelAdmin):
    resource_class = TransectionDataResource
    pass

admin.site.register(HourlyData)
admin.site.register(TransectionData)

**Comment by bmihelac** [comment]
@auvipy you are not registering your admin class - it should be:

   admin.site.register(HourlyDataAdmin , HourlyData)
   ....
