### ISSUE TITLE
Import occurs before clicking 'confirm' (normalization)

### ISSUE THREAD

**Issue by yarnball** [django-import-export/django-import-export#330]
I've created this trick to import foreign keys across models (normalization). It is really handy.

However, the data imports before I click confirm. It only applies the foreign key values (and not the primary key ones).

This is a big issue. Can anyone suggest a work around?

Here's an example of my code in admin.py.

`
class StoreWidget(widgets.ForeignKeyWidget):
    def clean(self, value):
        return self.model.objects.get_or_create(store_name = value)[0]
`

`
class ProductResource(resources.ModelResource):

    store_name = fields.Field(column_name='store_name', attribute='Store', widget=StoreWidget(Store, 'store_name'))
`

**Comment by int-ua** [comment]
I guess you can start by trying to enable transaction support:

https://django-import-export.readthedocs.org/en/latest/import_workflow.html#transaction-support
https://django-import-export.readthedocs.org/en/latest/api_resources.html#import_export.resources.Resource.import_data

AFAIU you can also add a cancel action to the confirmation page that will rollback the transaction.

**Comment by bmihelac** [comment]
As @int-ua says, transactions are easiest if you can use them. Please reopen if needed
