### ISSUE TITLE
Exporting model with UUID pk fails

### ISSUE THREAD

**Issue by adrienemery** [django-import-export/django-import-export#333]
Im using UUIDs for primary keys and when I choose the `json` format for exporting it fails with:

`UUID('09959a86-7791-11e5-8bcf-feff819cdc9f') is not JSON serializable`

which is coming from tablib when its called here:

``` python
    def export_data(self, dataset):
        return self.get_format().export_set(dataset) 
```

It would be great to be able to export models with UUID base pk's. 
Thanks

**Comment by bmihelac** [comment]
Do you use Django or some 3rd party library for uuid field?

**Comment by adrienemery** [comment]
I use Django.

**Comment by JCapriotti** [comment]
I hit this too. I found that if I follow the relationship and explicitly list the ID in the field list (i.e. `relationship__id`) the export works fine. However, upon import the `relationship` field on the parent table is imported as null.

Looking into alternate solutions.

**Comment by JCapriotti** [comment]
Also FWIW, this works for exporting. Does not work for importing, but it might be as simple as overriding the `clean` method similar to how the `ForeignKeyWidget` works.

```
class UUIDWidget(Widget):

    def __init__(self, field='pk', *args, **kwargs):
        self.field = field

    def render(self, value, obj=None):
        return str(getattr(value, self.field))
```

And in the resource class:

    relationship_field = fields.Field(column_name='relationship_field', 
                                      attribute='relationship_field',
                                      widget=UUIDWidget('id'))
