### ISSUE TITLE
XLS import doesn't update existing records

### ISSUE THREAD

**Issue by davemerwin** [django-import-export/django-import-export#336]
Any guesses as to why django-import-export is not even seeing the fields that have been changed? I can export the doc, make the change, save it and reimport it and it doesn't see the changed field. Is something missing?

**Comment by bmihelac** [comment]
Can you give more info, ie. what is field type, initial and changed value, etc

**Comment by davemerwin** [comment]
The value is an integer. It needs to update. Also, a VARCHAR. In both cases when I upload the file with the new data nothing happens.

So, one value was 0. And the new value is 5. The file has the right value, but the record isn't updated.

**Comment by bmihelac** [comment]
can you give ModelResource and Model definition

**Comment by davemerwin** [comment]
Here's my resource:

    class RootstockResource(resources.ModelResource):
        class Meta:
		model = Rootstock
		fields = ('id', 'name', 'stock_quantity',
			'one_eighth_price_50_99', 'one_eighth_price_100_999', 'one_eighth_price_1000_9999', 'one_eighth_price_10000_49999', 'one_eighth_price_50000_199999', 'one_eighth_price_200000_499999', 'one_eighth_price_500000_up',
			'three_sixteenths_price_50_99', 'three_sixteenths_price_100_999', 'three_sixteenths_price_1000_9999', 'three_sixteenths_price_10000_49999', 'three_sixteenths_price_50000_199999', 'three_sixteenths_price_200000_499999', 'one_eighth_price_500000_up',
			'one_quarter_price_50_99', 'one_quarter_price_100_999', 'one_quarter_price_1000_9999', 'one_quarter_price_10000_49999', 'one_quarter_price_50000_199999', 'one_quarter_price_200000_499999', 'one_quarter_price_500000_up',
			'three_eights_price_50_99', 'three_eights_price_100_999', 'three_eights_price_1000_9999', 'three_eights_price_10000_49999', 'three_eights_price_50000_199999', 'three_eights_price_200000_499999', 'three_eights_price_500000_up',
			'one_eighth_inv', 'one_eighth_regrade_inv', 'three_sixteenths_inv', 'three_sixteenths_regrade_inv', 'one_quarter_inv', 'one_quarter_regrade_inv', 'three_eights_inv', 'three_eights_regrade_inv', 'one_half_inv', 'one_half_regrade_inv')

Here's my model:

    class Rootstock(models.Model):
	# Size choices
	QUESTION = '?'
	VERY_DWARF = '1'
	DWARF = '2'
	SEMI_DWARF = '3'
	SEMI_VIGOROUS = '4'
	STANDARD = '5'
	SIZE_CHOICES = (
		(QUESTION, '?'),
		(VERY_DWARF, 'Very Dwarf'),
		(DWARF, 'Dwarf'),
		(SEMI_DWARF, 'Semi Dwarf'),
		(SEMI_VIGOROUS, 'Semi Vigorous'),
		(STANDARD, 'Standard'),
	)

	# Usage Choices
	QUESTION = '?'
	COMMERCIAL = '6'
	LIMITED = '7'
	EXPERIMENTAL = '8'
	USAGE_CHOICES = (
		(QUESTION, '?'),
		(COMMERCIAL, 'Commercial'),
		(LIMITED, 'Limited'),
		(EXPERIMENTAL, 'Experimental'),
	)

	# Availability Choices
	QUESTION = '?'
	AVAILABLE = '10'
	OTHER_SOURCES = '11'
	LIMITED = '12'
	NOT = '13'
	AVAILABILITY_CHOICES = (
		(QUESTION, '?'),
		(AVAILABLE, 'Available'),
		(OTHER_SOURCES, 'Available from other sources'),
		(LIMITED, 'Limited Supply'),
		(NOT, 'Not Available'),
	)

	name = models.CharField(max_length=100)
	grouping = models.CharField(max_length=2)
	slug = models.CharField(max_length=100)
	display_order = models.IntegerField(default=0)
	content = models.TextField()
	bundle_image_1x = models.FileField(upload_to="rootstock-images", null=True, blank=True)
	bundle_image_2x = models.FileField(upload_to="rootstock-images", null=True, blank=True)
	sapling_image_1x = models.FileField(upload_to="rootstock-images", null=True, blank=True)
	sapling_image_2x = models.FileField(upload_to="rootstock-images", null=True, blank=True)
	stock_quantity = models.IntegerField(null=True, blank=True)
	relative_size = models.IntegerField(null=True, blank=True)
	plant_size = models.CharField(null=True, blank=True, max_length=100)
	size = models.CharField(null=True, blank=True, max_length=2, choices=SIZE_CHOICES)
	usage = models.CharField(null=True, blank=True, max_length=2, choices=USAGE_CHOICES)
	availability = models.CharField(null=True, blank=True, max_length=2, choices=AVAILABILITY_CHOICES)
	one_eighth_price_50_99 = models.DecimalField(verbose_name="1/8 Price 50 - 99", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_price_100_999 = models.DecimalField(verbose_name="1/8 Price 100 - 999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_price_1000_9999 = models.DecimalField(verbose_name="1/8 Price 1,000 - 9,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_price_10000_49999 = models.DecimalField(verbose_name="1/8 Price 10,000 - 49,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_price_50000_199999 = models.DecimalField(verbose_name="1/8 Price 50,000 - 199,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_price_200000_499999 = models.DecimalField(verbose_name="1/8 Price 200,000 - 499,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_price_500000_up = models.DecimalField(verbose_name="1/8 Price 500,000 +", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_50_99 = models.DecimalField(verbose_name="3/16 Price 50 - 99", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_100_999 = models.DecimalField(verbose_name="3/16 Price 100 - 999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_1000_9999 = models.DecimalField(verbose_name="3/16 Price 1,000 - 9,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_10000_49999 = models.DecimalField(verbose_name="3/16 Price 10,000 - 49,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_50000_199999 = models.DecimalField(verbose_name="3/16 Price 50,000 - 199,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_200000_499999 = models.DecimalField(verbose_name="3/16 Price 200,000 - 499,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_sixteenths_price_500000_up = models.DecimalField(verbose_name="3/16 Price 500,000 +", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_50_99 = models.DecimalField(verbose_name="1/4 Price 50 - 99", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_100_999 = models.DecimalField(verbose_name="1/4 Price 100 - 999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_1000_9999 = models.DecimalField(verbose_name="1/4 Price 1,000 - 9,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_10000_49999 = models.DecimalField(verbose_name="1/4 Price 10,000 - 49,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_50000_199999 = models.DecimalField(verbose_name="1/4 Price 50,000 - 199,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_200000_499999 = models.DecimalField(verbose_name="1/4 Price 200,000 - 499,999", null=True, blank=True, max_digits=4, decimal_places=3)
	one_quarter_price_500000_up = models.DecimalField(verbose_name="1/4 Price 500,000 +", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eights_price_50_99 = models.DecimalField(verbose_name="3/8 Price 50 - 99", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eights_price_100_999 = models.DecimalField(verbose_name="3/8 Price 100 - 999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eights_price_1000_9999 = models.DecimalField(verbose_name="3/8 Price 1,000 - 9,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eights_price_10000_49999 = models.DecimalField(verbose_name="3/8 Price 10,000 - 49,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eigths_price_50000_199999 = models.DecimalField(verbose_name="3/8 Price 50,000 - 199,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eigths_price_200000_499999 = models.DecimalField(verbose_name="3/8 Price 200,000 - 499,999", null=True, blank=True, max_digits=4, decimal_places=3)
	three_eigths_price_500000_up = models.DecimalField(verbose_name="3/8 Price 500,000 +", null=True, blank=True, max_digits=4, decimal_places=3)
	one_eighth_inv = models.IntegerField(verbose_name="1/8 Inventory", null=True, blank=True)
	one_eighth_regrade_inv = models.IntegerField(verbose_name="1/8 Inventory", null=True, blank=True)
	three_sixteenths_inv = models.IntegerField(verbose_name="3/16 Inventory", null=True, blank=True)
	three_sixteenths_regrade_inv = models.IntegerField(verbose_name="3/16 Inventory", null=True, blank=True)
	one_quarter_inv = models.IntegerField(verbose_name="1/4 Inventory", null=True, blank=True)
	one_quarter_regrade_inv = models.IntegerField(verbose_name="1/4 Inventory", null=True, blank=True)
	three_eights_inv = models.IntegerField(verbose_name="3/8 Inventory", null=True, blank=True)
	three_eights_regrade_inv = models.IntegerField(verbose_name="3/8 Inventory", null=True, blank=True)
	one_half_inv = models.IntegerField(verbose_name="1/2 Inventory", null=True, blank=True)
	one_half_regrade_inv = models.IntegerField(verbose_name="1/2 Inventory", null=True, blank=True)
	pear = models.BooleanField(default=False)

	class Meta:
		verbose_name = 'Rootstock'
		verbose_name_plural = 'Rootstocks'
		ordering = ('display_order',)

	def __unicode__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('rootstock_detail', args=[str(self.slug)])

**Comment by bmihelac** [comment]
@davemerwin so exporting files, changing all fields and importing it again does not change anything? Or only some fields? Which format you export to and import from? Does importing work if you do not use custom resource class (than you would be able to export / import all fields)
