### ISSUE TITLE
Ignore missing fields on import if they are optional (have default, can be null)

### ISSUE THREAD

**Issue by mlncn** [django-import-export/django-import-export#338]
Would it be possible to have a configuration option to accept an import row as valid if it had all required fields, but did not have fields that the model has as allowing null or has a default for?

**Comment by mlncn** [comment]
Should note, willing to work on adding this feature if there's interest.

**Comment by int-ua** [comment]
:+1:

**Comment by bmihelac** [comment]
@mlncn can you give an example? it should be possible to specify which fields to import...

**Comment by mlncn** [comment]
Yes!  So i'm able to do the following:

fields = ('username', 'first_name', 'last_name', 'email',)
import_id_fields = ['username']

And that's pretty great.

One way to do what i want is to have, say:

optional_fields = ('is_staff', 'is_superuser',)

Then, if someone were to have a spreadsheet that has is_staff, it would work, but they wouldn't *have* to have that column.

**Comment by bmihelac** [comment]
I see. What is current output if you include optional fields? Looking at [source code](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L228-L230) it looks like importing field should be skipped if it is not in data, but it could be that somewhere else exception is raised.

**Comment by domenkozar** [comment]
We now obey Django model defaults: https://github.com/django-import-export/django-import-export/pull/345
