### ISSUE TITLE
JSON is opened as binary?

### ISSUE THREAD

**Issue by Braintelligence** [django-import-export/django-import-export#339]
Hello everyone,

it seems to me as if JSON files that are imported and exported via admin always behave like binary files.

See, if I export objects with CharFields that contain special characters like "äüöÄÖÜß" and the like it gives me an utf-8 encoded json file with "\u00df" instead of "ß" for example.
I tried playing around with from_encoding and to_encoding but to no avail.

What could I do to get the behaviour I want which is input and output as text utf-8 file?

If I need to import files I always have to search and replace every occurence of special characters; this is rather bothersome and also the exported format is not human-readable.

**Comment by bmihelac** [comment]
Json format should be treated as text format and it should be by default utf-8 encoding:

https://github.com/django-import-export/django-import-export/blob/master/import_export/formats/base_formats.py#L119

If it is not please add minimal test case or more info.

**Comment by Braintelligence** [comment]
Did you try exporting any CharField-containing model as JSON? Try looking in the resulting file for "\u00" strings by providing special characters in the CharField-data. This is true for me and I didn't modify the export output in any way.
They should be real encoded symbols instead, shouldn't they?

**Comment by Braintelligence** [comment]
Maybe this is the intended behavior and I am thinking backwards? When exporting from phpmyadmin the special characters are also textually encoded that way.

**Comment by bmihelac** [comment]
Example copied from tablib docs:

    >>>  data = tablib.Dataset(*[('Kenneth€', 'Reitz', 23), ('Bessie', 'Monke', 22)],
                              headers=['First Name', 'Last Name', 'Age'])
    >>> data.json
    '[{"First Name": "Kenneth\\u20ac", "Last Name": "Reitz", "Age": 23}, {"First Name": "Bessie", "Last Name": "Monke", "Age": 22}]'

Here it is visible that indeed special characters are encoded so I guess this works as intended.

**Comment by Braintelligence** [comment]
I see.
Bummer... JSON is my preferred format for importing/exporting for now due to many reasons.

For example: I can't cope with comma as delimiter in CSV, because it is used for decimal values in German scope.

Well... I'll use my trusty Notepad++ replacement workflow then for importing the old MySQL data into the Django ORM.

Thanks, you can close this then I guess.

**Comment by bmihelac** [comment]
Maybe you can make it so JSON does not encode, I guess you could see json format implementation in tablib and update it accordingly.

Regarding CSV - there is also TSV, also fields can be quoted

**Comment by Braintelligence** [comment]
I needed something to export to from phpmyadmin. I believe TSV was no option but since phpmyadmin exports its JSON files this way as well I guess it is working as intended.

Maybe this is how JSON has to look like, I frankly didn't work enough with JSON to know this.
