### ISSUE TITLE
VersionAdmin integration.

### ISSUE THREAD

**Issue by kierun** [django-import-export/django-import-export#340]
My admin classes all inherit from [VersionAdmin](http://django-reversion.readthedocs.org/en/latest/admin.html?highlight=versionadmin) from [django=-revision](https://github.com/etianen/django-reversion). However, when I try to add `ImportExportActionModelAdmin` as another parent class, depending on the order (first or last), I get the functionality of only the first one but not the last one.

The export as an admin action works fine.  The `import` functionality is the one that is missing if `ImportExportActionModelAdmin` is not in first place in the parent list.

Can I combine the two?

**Comment by bmihelac** [comment]
yes, use ``ImportExportMixin``

**Comment by kierun** [comment]
I am afraid that did not work.  

Here is what I did:

    class InvoiceResource(resources.ModelResource):
      class Meta:
          model = Invoice

    class InvoiceAdmin(VersionAdmin, ImportExportMixin):
        resource_class = InvoiceResource
        ...

This shows the `VersionAdmin` buttons but none of the import/export ones.

    class InvoiceAdmin(ImportExportMixin, VersionAdmin):
        resource_class = InvoiceResource
        ...

This shows the import and export buttons but not the version control ones.

**Comment by bmihelac** [comment]
Of course, you would need to override admin template in this case. This
should be easy.

**Comment by kierun** [comment]
I shall give that a try. Not used Django much at all, so this is all new.

**Comment by kierun** [comment]
Got it to work!  Thank you.
