### ISSUE TITLE
Decimal raises RepresenterError on YAML/JSON

### ISSUE THREAD

**Issue by kierun** [django-import-export/django-import-export#341]
While exporting a model containing a `models.DecimalField` field to either YAML or JSON, I get this error:
 
    Traceback:
    File "/home/***/Envs/intranet/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
      132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    [...]
    File "/home/***/Envs/intranet/lib/python2.7/site-packages/yaml/representer.py" in represent_data
      67.                     node = self.yaml_representers[None](self, data)
    File "/home/***/Envs/intranet/lib/python2.7/site-packages/yaml/representer.py" in represent_undefined
      247.         raise RepresenterError("cannot represent an object: %s" % data)

    Exception Type: RepresenterError at /admin/order_process_tracker/order/
    Exception Value: cannot represent an object: -1.00

I get the same error either from the admin page or from the shell. However, if I use CSV, that works fine.

Any idea what I am doing wrong?

**Comment by bmihelac** [comment]
this is related to JSON encoder, plase see:

http://stackoverflow.com/questions/1960516/python-json-serialize-a-decimal-object

Extending json format to serialize `Decimal` types is one of options (and as I think same applies to Date/Time fields as well). Other options are manually dehydrating fields or using other formats

please reopen if needed
