### ISSUE TITLE
Something wrong with admin-import overview before confirming? | Bad approach to #103

### ISSUE THREAD

**Issue by Braintelligence** [django-import-export/django-import-export#342]
So I try to import a resource which looks like this:

```python
class AlternativeCityNameResource(resources.ModelResource):

    class Meta:
        model = AlternativeCityName
        import_id_fields = ['id']
        fields = ('cityname', 'id', 'alternative_cityname')

    def before_import(self, dataset, dry_run, *args, **kwargs):
        city_ids = []

        for data in dataset.dict:
            city_id = data['cityname']

            # If no OldPlace known
            if city_id is None:
                city_ids.append('')
            # else try to find corresponding OldPlace
            else:
                try:
                    city_id = OldPlace.objects.get(city=city_id).id
                # If not possible, add it to LOST ALTERNATIVES
                except OldPlace.DoesNotExist:
                    lostoldplace_object,lostoldplace_created = OldPlace.objects.get_or_create(city="LOST ALTERNATIVES")
                    city_id = lostoldplace_object.id
                except OldPlace.MultipleObjectsReturned:
                    print("MULTIPLEOBJECTS:")
                    print(city_id)

            city_ids.append(city_id)

        dataset.append_col(city_ids, 'city')
        return super(AlternativeCityNameResource, self).before_import(dataset, dry_run, *args, **kwargs)

    export_cityname = fields.Field(column_name='cityname')

    def dehydrate_id(self, altcityname):
        return ""

    def dehydrate_export_cityname(self, altcityname):
        return "%s" % altcityname.city
```

My JSON looks like this:

[{"cityname": "Neisse", "id": "", "alternative_cityname": "Neisse"}, ...]

But the overview after uploading the JSON looks like this:
![image](https://cloud.githubusercontent.com/assets/6761196/11038677/76bd3eb6-8704-11e5-8969-3fc05e2b0399.png)

Why is there no cityname column?

**Comment by Braintelligence** [comment]
Wow, as always it hits me after I write the issue down -_-...

My model doesn't know a field with this name by itself; so I guess I have to add it with fields.Field(). Trying this out now.

**Comment by Braintelligence** [comment]
So if I add it like this:
```python
cityname = fields.Field(column_name='cityname')
```

The column appears but there is no data in it:
![image](https://cloud.githubusercontent.com/assets/6761196/11038858/551bced4-8705-11e5-8e24-07d664c738eb.png)

How can I get it to display this column out of the json file?

**Comment by bmihelac** [comment]
attribute? 

https://django-import-export.readthedocs.org/en/latest/api_fields.html

**Comment by Braintelligence** [comment]
Well, instead I found out, that if I do it like this:
```python
city = fields.Field(attribute='city')
```

I get the name of the city instead of the ForeignKey of the city, which is what I wanted!

I can work around the original issue now but I need to know how to manipulate tablib datasets. I don't know how to do this.
```python
data['city'] = OldPlace.objects.get(city=city_name).id
```
doesn't seem to work?

**Comment by Braintelligence** [comment]
Changing the dict value itself doesn't seem to change the dataset itself. I can't find a command to set or manipulate values.
It seems I need to delete the whole row and then add it again. This is really bothersome.

**Comment by Braintelligence** [comment]
Now I saw #103 and #143 and am feeling stupid. ^^
Trying to go this route now, then.

**Comment by Braintelligence** [comment]
Using the ForeignKeyWidget worked!
I can ditch my old working route now for this more beautiful approach. Sorry for bothering you!

**Comment by bmihelac** [comment]
Glad it works for you @Braintelligence ! If you feel that documentation could be improved, please add it :)
