### ISSUE TITLE
Better result reporting

### ISSUE THREAD

**Issue by rhunwicks** [django-import-export/django-import-export#346]
At the moment `import_data()` is a monolithic function with no easy customization points. In order to provide better feedback to users, I would like to extend it to report the total number of rows in each result type (NEW, UPDATE, SKIP, DELETE), including the total number of skipped rows even when `report_skipped == False`

There is no easy way to do this without copying the whole `import_data()` function into the subclass because there is no way to override Result class used, or the handling of individual rows.

I could achieve my requirements by making a slight change to import_data() to count the total number of each result type.

If it is desirable, I could also:

* replace the `result = Result()` with `result = self.get_result_class()()` to allow people to customize the Result if necessary
* move the inner part of the `for row in dataset.dict:` to a new `import_row()` method that would allow people to customize what happens before and after the row import is attempted
* add a `report_error()` and a `report_row_result()` to hold the code that appends the results to the result, once again providing an additional extension point for people that need additional reporting

**Comment by bmihelac** [comment]
@rhunwicks that looks sensible to me,  it wouldn't break anything and it would be easier to customise importing process
