### ISSUE TITLE
How to save user ID to model when importing data?

### ISSUE THREAD

**Issue by daniel1943** [django-import-export/django-import-export#349]
Full question here: http://stackoverflow.com/questions/33847382/django-import-export-how-to-add-current-admin-user-to-model

save_model work with normal admin but not with import/export.

**Comment by daniel1943** [comment]
I managed to make it work with:

    class KWResource(resources.ModelResource):
    ....
    ....
       def before_import(self, dataset, dry_run, *args, **kwargs):
           li = []
           li.append(kwargs.pop('user', 1))
           dataset.insert_col(0, li, 'user')
           return super(KWResource, self).before_import(dataset, dry_run, *args, **kwargs)

But it only works as long as my author model is ForeignKey to user. If I change it to ManyToManyField it gives this error:

`Traceback (most recent call last):
  File "/home/django/myproject/myprojectenv/lib/python2.7/site-packages/import_export/resources.py", line 373, in import_data
    self.import_obj(instance, row, real_dry_run)
  File "/home/django/myproject/myprojectenv/lib/python2.7/site-packages/import_export/resources.py", line 238, in import_obj
    self.import_field(field, obj, data)
TypeError: 'User' object does not support indexing`

**Comment by bmihelac** [comment]
See documentation on [Import data workflow](https://django-import-export.readthedocs.org/en/latest/import_workflow.html). ``import_data``  would receive ``user`` instance - you can save it as an instance variable. Then assign it to an instance in ``before_save_instance``.

**Comment by daniel1943** [comment]
Any examples of similar things? I tried pretty much everything and can't seem to make it work.

    author = fields.Field(column_name='user', attribute='author', widget=ManyToManyWidget(User, field='id'))
    def after_save_instance(self, instance, dry_run, **kwargs):

        instance.user = User.objects.get(id=kwargs.pop('user', 1))
        instance.user.save()
        instance.save()

Shouldn't this work?

**Comment by bmihelac** [comment]
If you look at admin [source code](https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L156-L159), your resource class can override `import_data`:

    def import_data(*args, **kwargs):
        self._user = kwargs.get('user', None)
        return super(import_data(*args, **kwargs))

and then use self._user in after_save_instance

code is from head, I hope it'll help.

**Comment by daniel1943** [comment]
Thank you, this did it. If in future anyone needs, here is full code: Model included, so code is complete :)

    author = models.ManyToManyField(User, blank=True, editable=False)

    def import_data(self, *args, **kwargs):
        self._user = kwargs.get('user', None)
        return super(KWResource, self).import_data(*args, **kwargs)

    def after_save_instance(self, instance, dry_run, **kwargs):

        instance.save()
        instance.author.add(self._user)
