### ISSUE TITLE
ExportActionModelAdmin does not work with Grappelli

### ISSUE THREAD

**Issue by timkofu** [django-import-export/django-import-export#351]
Hello,

This the functionality I'm referring to:
![](http://django-import-export.readthedocs.org/en/latest/_images/django-import-export-action.png)
Grappelli immediately runs the action on click, without giving you a chance to select the "Format".
Is there a way to set one export format as the default for an ExportActionModelAdmin thus eliminating the need to chose one?

**Comment by bmihelac** [comment]
@timkofu I'd say that it would be better to fix it (probably in grapelli js, not familar)

**Comment by bmihelac** [comment]
please reopen if anything can be done in django-import-export that is not workaround (that can be done if needed in admin)

**Comment by rm--** [comment]
[Related grapelli issue](https://github.com/sehmaschine/django-grappelli/issues/546).
