### ISSUE TITLE
skip some rows from import file

### ISSUE THREAD

**Issue by Alwerdani** [django-import-export/django-import-export#355]
Hello,
I've an Excel files where the first n of rows contain meta data (Information about the data in the next rows)
I there a way where I can only import cells starting from row number A to row number B or to the end ?

**Comment by bmihelac** [comment]
I guess you could override resource `import_data` to strip this rows from dataset. IE: in your resource class:

    def import_data(self, dataset, *args, **kwargs):
        # do something with dataset
        super(MyResource, self).import_data(dataset, *args, **kwargs)

**Comment by int-ua** [comment]
Can you please add "by number" or something similar to the title? Current state is slightly misleading when you know there is a skip_row method http://django-import-export.readthedocs.io/en/stable/api_resources.html#import_export.resources.Resource.skip_row
