### ISSUE TITLE
Improve performance using select_related

### ISSUE THREAD

**Issue by joshkel** [django-import-export/django-import-export#358]
I set up a ModelResource to export a number of fields off of ForeignKey relationships and noticed that performance was quite a bit worse than it could be (over 3x worse, in my case), since each relationship had to be fetched separately.

It seems to me that `get_queryset` could be updated to use [`select_related`](https://docs.djangoproject.com/en/1.9/ref/models/querysets/#select-related). One approach would be to add `select_related` as an attribute to ResourceOptions, but since it already has the list of column names, it should be able to automatically determine which related fields are needed. Something like this:

``` python
# Get column names of related fields
needed_relations = [f.column_name for f in self.get_fields() if '__' in f.column_name]

# Strip the foreign key field name; we want just the tables
needed_relations = [f.rpartition('__')[0] for f in needed_relations]

queryset = queryset.select_related(*needed_relations)
```

Does this approach seem reasonable? (I'm still relatively new to Django and this project, so please let me know if I'm missing something.) If the general idea is sound, then I can submit a proper PR.

**Comment by bmihelac** [comment]
Hi @joshkel,

There is option to override `get_queryset` of `ModelResource`, or use `queryset` argument of `export` to include select_related. I guess that should be enough for most.

If you still think there is a need for `select_related` then, I would like it to behave like similar method in ModelAdmin:

https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_select_related

What do you think?

**Comment by joshkel** [comment]
Sorry, I may not have been clear.

I saw `get_queryset` (although, since it doesn't appear to documented on Read the Docs, I wasn't sure if overriding it was supported), and I saw the `queryset` argument to `export`. Modifying `queryset` within `export` is what I'm doing for now.

However, it seems to me that the base `ModelResource.get_queryset` method could be updated to call `select_related` automatically. It has access to the list of database column names (via `get_fields()`), it can determine which of those follow foreign key relationships (by searching for `__`), and it knows that the foreign key relationships will always be needed (so I don't think there's any reason to _not_ use `select_related`). The code snippet I gave would implement this.

Updating `ModalResource.get_queryset` to do this can improve the export operation's performance (over 3x faster for my particular case), automatically, without requiring that the developer using the library take extra action. This seems like a good thing. However, like I said, I'm still relatively new to Django and this project, so I might be missing something, and I didn't want to submit a PR without first asking.

**Comment by bmihelac** [comment]
I admit that I do not have concrete example where it should be better not to automatically call `select_related` for included fields. 
Even if there are some reasons against optimizing  `get_queryset` method is easy to override.

**Comment by diogosimao** [comment]
Without any doubt and with all my money I would bet that `list_select_related ` feature use would solve #206 #301 #437. I would work on it at any time and I will. Also see [issue](https://stackoverflow.com/questions/28383358/streaming-a-response-with-django-import-export) on StackOverFlow

**Comment by merwok** [comment]
This is still relevant :/

**Comment by minholi** [comment]
If you have multiple ForeignKey fields just create a ModelResource and override get_queryset() like this:

```python
    def get_queryset(self):
        qs = MyModel.objects.select_related('myforeignkey1', 'myforeignkey2').prefetch_related('mym2mfield1', 'mym2mfield2').all()

        return qs
```

**Comment by vanschelven** [comment]
>  just create a ModelResource and override get_queryset()  

See #790 as to why this doesn't work
