### ISSUE TITLE
Raise errors on Admin interface

### ISSUE THREAD

**Issue by mstrcnvs** [django-import-export/django-import-export#359]
Hi there,

I'm trying to apply custom logic and raise a custom error on the Admin interface using `ImportExportModelAdmin` and `Resource` classes. 

While reading `django-import-export` source code I've noticed that if you raise an exception while the dry_run is running (before actual import) it will show on the admin interface, but it seems this is not true, here's my code.

``` python
import time

from django.contrib import admin

from import_export import resources
from import_export.admin import ImportExportModelAdmin

from places.models import BikeFriendlyPlace


class BikeFriendlyPlaceResource(resources.ModelResource):
    class Meta:
        model = BikeFriendlyPlace

    def save_instance(self, instance, dry_run):
        if dry_run:
            if not custom_logic:
                raise Exception('Custom error to be shown on interface')
        else:
            instance.save()
            time.sleep(0.05)



class BikeFriendlyPlaceModelAdmin(ImportExportModelAdmin):
    resource_class = BikeFriendlyPlaceResource


admin.site.register(BikeFriendlyPlace, BikeFriendlyPlaceModelAdmin)
```

Thank you!

**Comment by bmihelac** [comment]
It should, can you put pdb.set_trace before raising exception, and assert that exception is raised:

    import pdb; pdb.set_trace()
    raise Exception('Custom error to be shown on interface')

**Comment by mstrcnvs** [comment]
It's indeed being raised.

```sh
> /home/rafael/devel/web/usebike/places/admin.py(18)save_instance()
-> raise Exception('Custom error to be shown on interface')
(Pdb) n
Exception: Custom error to be shown on interface
> /home/rafael/devel/web/usebike/places/admin.py(18)save_instance()
-> raise Exception('Custom error to be shown on interface')
(Pdb) __exception__
(<class 'Exception'>, Exception('Custom error to be shown on interface',))
(Pdb) n
```

**Comment by mstrcnvs** [comment]
Tested right now doing the same thing on `before_import` and worked perfect.

**Comment by bmihelac** [comment]
Not sure what can be the issue and without idea except to find if result contains errors in

https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L228
