### ISSUE TITLE
import error, 'get() keywords must be strings'

### ISSUE THREAD

**Issue by cometsong** [django-import-export/django-import-export#365]
I'm having trouble getting a form to accept data on import.  Currently testing `csv` format file; get same errors with `xls` file.  

sample from import.csv:
```csv
jid,project_code,collab_id,sample_code,sequencing_type
JMQN3H,AAST,42567,ST,1
JO2FT1,AAST,43267,ST,1
```

The error coming out is `get() keywords must be strings`.  

django error log:
```
Line number: 1 - get() keywords must be strings
OrderedDict([('jid', 'JMQN3H'), ('project_code', 'AAST'), ('collab_id', '42567'), ('sample_code', 'ST'), ('sequencing_type', '1')])
Traceback (most recent call last):
File "/var/www/django/jid_generator/lib/python3.4/site-packages/import_export/resources.py", line 356, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "/var/www/django/jid_generator/lib/python3.4/site-packages/import_export/resources.py", line 186, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
TypeError: get() keywords must be strings
```

I tried putting the values in csv file inside quotes. 
I tried modifying the `admin`, `form` and the `Resource` widgets.  

admin.py:
```python
"""ImportExport Resource"""
class DetailResource(resources.ModelResource):
    jid = fields.Field(
        default=generate_Jid(prefix='J'),
        readonly=True,
        widget=widgets.CharWidget(),
        )
    project_code = fields.Field(column_name='project_code', attribute='project_code',
        widget=widgets.ForeignKeyWidget(ProjectCode, 'code'),
        )
    sample_type = fields.Field(
        widget=widgets.ForeignKeyWidget(SampleType, 'code'),
        )
    sequencing_type = fields.Field(
        widget=widgets.ForeignKeyWidget(SequencingType, 'code'),
        )
    collab_id = fields.Field(
        widget=widgets.CharWidget(),
        )

    class Meta:
        model = JIdDetail
        all_fields = ( 'jid', 'project_code', 'collab_id',
                'sample_type', 'sequencing_type', )
        import_id_fields = ( 'jid', )
        fields = all_fields
        export_order = all_fields

@admin.register(JIdDetail)
# class JIdDetailAdmin(admin.ModelAdmin):
class JIdDetailAdmin(ImportExportModelAdmin):
    resource_class = DetailResource

    # has_add_permission removes the individual 'add' admin action
    # def has_add_permission(self, request):
        # return False

    form = JIdDetailForm
    actions_on_top = False
    actions = None
    all_fields = ( 'jid', 'project_code', 'collab_id',
            'sample_type', 'sequencing_type', )
    fields = ( all_fields, )
    list_display = all_fields
    search_fields = all_fields
    readonly_fields = ( 'jid' ),
    list_filter = ( 'sample_type', 'sequencing_type', 'project_code' )
    ordering = ['creation_date', 'project_code', 'sequencing_type']
```

forms.py:
```python
class JIdDetailForm(forms.ModelForm):
    class Meta:
        model = JIdDetail
        fields = ( 'jid', 'project_code', 'collab_id',
                'sample_type', 'sequencing_type', )
        readonly_fields = ( 'jid' ),

        # widgets = {
            # 'jid': forms.TextInput(attrs={'size':'6'}),
            # 'collab_id': forms.TextInput(attrs={'size':'40'}),
            # }
```

models.py
```python
class JIdDetail(models.Model):
    verbose_name = 'J Id Detail'
    jid = models.CharField('J ID',
            max_length=6, blank=False,
            help_text="A unique ID string for every sample.",
            unique=True,
            )
    project_code = models.ForeignKey(ProjectCode, to_field='code')
    collab_id = models.TextField('Collaborator ID', blank=False,
            help_text="Collaborator sample ID."
            )
    sample_type = models.ForeignKey(SampleType, to_field='code')
    sequencing_type = models.ForeignKey(SequencingType, to_field='code')
    creation_date = models.DateTimeField(auto_now_add=True)
```

Any tips on how to troubleshoot this?

Thanks!
-Benjamin-

**Comment by bmihelac** [comment]
Importer by default expect column named `id` to known to create or update existing instance

see [import_id_fields](https://django-import-export.readthedocs.org/en/latest/api_resources.html#modelresource) in documentation to change this fields

**Comment by bmihelac** [comment]
Please reopen if needed

**Comment by cometsong** [comment]
None of the fields I am using are named `id`, they're named `jid` or `collab_id`. 

I know the Field name `id` is reserved by Django as well.

**Comment by cometsong** [comment]
(How do I **reopen** an issue i'm not the *owner* of?)  :)

**Comment by bmihelac** [comment]
Oh I didn't see you are already using `import_id_fields`

Can you put `import pdb; pdb.set_trace()` in resources.py before exception is raised (thats 185)

File "/var/www/django/jid_generator/lib/python3.4/site-packages/import_export/resources.py", line 186, in get_or_init_instance

and write here results of: instance_loader, row, self.get_import_id_fields()

**Comment by bmihelac** [comment]
Hm, maybe this is unicode/bytestring issue, can you try to use:

import_id_fields = ( b'jid', )

**Comment by cometsong** [comment]
I tried to pip your repo as 'editable' but could get it to be accepted in the INSTALLED_APPS, as the module name was no longer the same.

Doing a `manage.py check` it gave me the following pdb trace interaction.  it was looong.

pdb trace results:
```pdb
def get_or_init_instance(self, instance_loader, row):
> /var/www/django/jaxid_generator/src/import-export/import_export/resources.py(193)Resource()
def save_instance(self, instance, dry_run=False):
/var/www/django/jaxid_generator/src/import-export/import_export/resources.py(199)Resource()
...same with: ...
before_save_instance
after_save_instance
delete_instance
....etc through ....
def modelresource_factory(model, resource_class=ModelResource):
--Return--
<frozen importlib._bootstrap>(321)_call_with_frames_removed()->None
--Return--
<frozen importlib._bootstrap>(1471)exec_module()->None
...and many more frozen importlib statements....
```

**Comment by cometsong** [comment]
btw when I do `pip list` it shows:
```
/var/www/django/jaxid_generator/lib/python3.4/site-packages/pip/vcs/__init__.py:314: ResourceWarning: unclosed file <_io.BufferedReader name=4>
(3 lines of same)
django-import-export (0.4.2.dev0, /var/www/django/jaxid_generator/src/import-export)
```

**Comment by bmihelac** [comment]
I am almost sure adding b before string would fix this. Please try:

    import_id_fields = ( b'jid', )

**Comment by cometsong** [comment]
I switched back to the release version (0.4.2) and uninstalled the --editable one. 
Modified line to add in the `b`:  `import_id_fields = ( b'jid', )` inside the `DetailResource` class.

got error `KeyError: b'jaxid'

**Comment by bmihelac** [comment]
You have defined `jid` field in your resource, and data, but dict contains `jaxid`:

    OrderedDict([('jaxid', 'JMQN3H'), ('project_code', 'AAST'), ('collab_id', '42567'), ('sample_code', 'ST'), ('sequencing_type', '1')])

**Comment by cometsong** [comment]
doh! i previously removed the 'ax' from the other things i posted, for some strange chance of string recognition.  Didn't removed it from the ordered dict.  all the `jid`s are in fact `jaxid`s.  Sorry for confusion!

**Comment by bmihelac** [comment]
@cometsong you are missing attribute in jid field:

jid = fields.Field(
       attribute='jid'
        default=generate_Jid(prefix='J'),
        readonly=True,
        widget=widgets.CharWidget(),
        )

**Comment by cometsong** [comment]
Yay! 
That gets it through the stringy step!
Now it gets to the 'Preview' step and only one of the fields is present.  :|
All fields are intended to be text.
Do i need `attribute` on all the others as well? Matching their column names?

![import_preview](https://cloud.githubusercontent.com/assets/307777/11900130/c3fc38e0-a571-11e5-8845-88bee707e133.png)

**Comment by bmihelac** [comment]
yes, if redefining field. If just adding existing model field to fields,  you do not have to specify attribute/column_name

**Comment by bmihelac** [comment]
Glad it works for you, please open new issue if needed.

**Comment by cometsong** [comment]
Works very well!
Thanks for your assistance!
It's all in the `attribute`'s.  Need to search docs for them and figure out what they're used for now.  :)
