### ISSUE TITLE
can modify import_formats list?

### ISSUE THREAD

**Issue by cometsong** [django-import-export/django-import-export#368]
The `import_formats` is loaded from `get_import_formats` (admin.py#L130), which in turn uses `DEFAULT_FORMATS`, which is based on `base_formats` method `can_import`

I'd like to modify the `fields['input_format'].choices` that are displayed in the `ImportForm`.  Meaning, I'd like to remove some of the formats and change the order of the remaining ones.

Can this be done?
I've not found it as a setting, or as a variable in the `Meta` section of the `Resource`.  
Am I missing something?

Thanks!

**Comment by bmihelac** [comment]
`get_export_formats` and `get_import_formats` can be used, see

https://django-import-export.readthedocs.org/en/latest/api_admin.html

Autogenerated docs for admin module was not available on readthedocs.

**Comment by cometsong** [comment]
@bmihelac Thanks for the info, plus thanks for the new Admin docs.  :)
