### ISSUE TITLE
automatic mimetype detection for import files

### ISSUE THREAD

**Issue by shalakhin** [django-import-export/django-import-export#370]
Hi guys!

I think we can remove dropdown of types for import as we can detect filetype based on the extension. This way you just choose import file and press "Import".

I can work on such PR if people agree it makes sense.

**Comment by bmihelac** [comment]
This would be great.

There is some code in Import management command for django-import-export that could be of use:
https://gist.github.com/bmihelac/434fceb6ba8e752f08d3

**Comment by shalakhin** [comment]
Thank you! I will make PR in the nearest few weeks as soon as I have time to finish it.

**Comment by jheld** [comment]
@shalakhin Any update on this?

**Comment by shalakhin** [comment]
Hi guys!

I was loaded by work. In the nearest 14 days I will send you PR.

**Comment by bmihelac** [comment]
@shalakhin that would be awesome :)
