### ISSUE TITLE
import-export writes to the database even if you do not confirm your import.

### ISSUE THREAD

**Issue by agersoncgps** [django-import-export/django-import-export#371]
after_save_instance() appears to fire after the "preview" step loads and before clicking the "confirm import" button. If you do not click "confirm import" and just exit the page your import data is written to the database already.

**Comment by bmihelac** [comment]
There is a `dry_run` parameter that can be used to know if data should be written or not.

**Comment by agersoncgps** [comment]
Sure, but in either case shouldn't it only load after clicking "confirm import"?

**Comment by bmihelac** [comment]
`after_save_instance` is a hook that you can use for custom logic. It does not do anything by default.
It receives `dry_run` parameter so you know if data should be saved to database or not:

https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L204-L208

See also  `IMPORT_EXPORT_USE_TRANSACTIONS` setting  that allows to rollback after preview.

**Comment by agersoncgps** [comment]
Sure, I get that, lets forget about after_save_instance for a moment. dry_run defaults to false so it tells the import system to save data to the database. What I getting at is that the save to database occurs when clicking "submit" after selecting the file and before clicking the "confirm import" button. This means the "confirm import" button has no effect and is in fact misleading. Shouldn't it write the database after clicking that button?  If you upload a file, click submit, get no errors, see the preview of data and do not click "confirm import" and just exit the page your import data has already been written to the database.

**Comment by bmihelac** [comment]
It should not be saved with `dry_run=False`. If it does please give more info or create failing test case

**Comment by K900** [comment]
Sorry for bumping an old bug, but are you using Oracle by any chance?

**Comment by K900** [comment]
Seems like I've figured it out. The issue is with multiple databases, and with django-import-export creating all transactions on the default database and not the database the model actually belongs to. I haven't looked into it in detail yet, but it seems like `Resource.import_data_inner` needs to be updated to support multiple databases.

**Comment by minedbp** [comment]
In my case, I used non-default database or an external database and It works for using the after_save_instance, here is my code snippets inside my resources.py class and I override few of the functions below MyClassResource(resources.ModelResource):

def get_or_init_instance(self, instance_loader, row):
        """
        Either fetches an already existing instance or initializes a new one.
        """
        with in_database(settings.APP_LABEL_DB, write=True):
            instance = self.get_instance(instance_loader, row)
            if instance:
                return (instance, False)
            else:
                return (self.init_instance(row), True)

    def save_instance(self, instance, using_transactions=True, dry_run=True):
        """
        Takes care of saving the object to the database.
        Keep in mind that this is done by calling ``instance.save()``, so
        objects are not created in bulk!
        """
        with in_database(settings.APP_LABEL_DB, write=True):
            self.before_save_instance(instance, using_transactions, dry_run)
            if not using_transactions and dry_run:
                # we don't have transactions and we want to do a dry_run
                pass

            self.after_save_instance(instance, using_transactions, dry_run)

    def after_save_instance(self, instance, using_transactions, dry_run):
        """
        Override to add additional logic. Does nothing by default.
        """
        if not dry_run:
            instance.save()

**Comment by tech4solitude** [comment]
@minedbp  thanks for the code snippet. 
Can anyone help us out in the latest version of Django? We have the multi-database architecture in our project and we're facing a similar issue. It will be really helpful if someone can help us out.

**Comment by franhace** [comment]
Anyone had any luck solving this issue?

**Comment by K900** [comment]
I am not 100% sure about this, since its been a very long time, but I believe my original merge request fixed this at least in a multi-db environment. It's way behind master though...

**Comment by franhace** [comment]
Thanks for the quick answer!
I read the issue you're referring but it does not match the issue I have.
I've been wanting to upload rows from a file, and it imports them once I browse the file and select submit, instead of afterwards when we confirmed the action. 
If I click on "confirm" it uploads them again, therefore having a lot of duplicates.

Later I'll try using the IMPORT_EXPORT_USE_TRANSACTIONS.

**Comment by shakyasaijal** [comment]
If transaction support is not enabled(may work if enable, I have not tested for that). Use 

`def after_save_instance(self, instance, using_transactions, dry_run, *args):
        try:
            if not dry_run:
                // Code here
        except (Exception, User.DoesNotExist) as e:
            print(e, "gengen")
            pass
`
When we import and press "Submit", dry_run is True. When we press "Confirm Import" dry_run is False. May not be the best idea but got nothing except this.

**Comment by shakyasaijal** [comment]
If transaction support is not enabled(may work if enable, I have not tested for that).

Use:

`
   after_save_instance(self, instance, using_transactions, dry_run, *args)
`

When we import and press "Submit", dry_run is True. When we press "Confirm Import" dry_run is False. May not be the best idea but got nothing except this.
