### ISSUE TITLE
Alter a value on import based on some logic

### ISSUE THREAD

**Issue by Braintelligence** [django-import-export/django-import-export#373]
Hello everyone.

What would be the easiest way to alter or add values of attributes on import through admin interface based on some logic?

Should I use before_import?

Example: The number of pages is not contained within the import file. If the object is a book I want the number to be 500, if the object is a magazine I want the number to be 100.
I'd need an if-clause somewhere that checks this and then injects the correct value for the attribute.

**Comment by bmihelac** [comment]
@Braintelligence 

overriding `import_obj` is quite useful for adding per object logic, see:

https://django-import-export.readthedocs.org/en/latest/import_workflow.html

**Comment by Braintelligence** [comment]
I helped myself with a workaround using the clean function of widgets and forms. :)
