### ISSUE TITLE
Pass row values to every Widget

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#375]
AFAIU it will help create widgets with autocreation of related ForeignKey instances that require two fields already present in the row. For example:

* FK to `Person` with `first_name`, `last_name`
* FK to `Quote` that requires a `Book` (let's suppose it's identifiable just by name) and that book is already in the import fields
* FK to `POI` that is identifiable with two (or even three) coordinates

**Comment by int-ua** [comment]
Related: #188

**Comment by Eccleshall** [comment]
I too have come across the same issue!

Related Issue #378

**Comment by bmihelac** [comment]
I am thinking about adding optional **kwargs to widgets methods. Beside row value, current format could be added.

**Comment by int-ua** [comment]
#420

**Comment by Tib7** [comment]
can u give some example code of how to use it? i still get some errors.

**Comment by int-ua** [comment]
Let's start with the errors you get, please post them and we'll try to fix them.

**Comment by Tib7** [comment]
It looks like it can't find gamesite_account_id using provided rows:

error: Line number: 1 - NOT NULL constraint failed: scores_score.gamesite_account_id



models.py (Score):
```
class Score(models.Model):
    gamesite_account = models.ForeignKey('players.GamesiteAccount', null=False, blank=False, on_delete=models.CASCADE)
    date            = models.DateField(default=date.today, null=False, blank=False)
    score_usd       = models.DecimalField(max_digits=6, decimal_places=2)


    class Meta:
        unique_together = (gamesite_account', 'date')

    def __str__(self):
        return '%s // %s // %s' % (self.gamesite_account, self.date, self.score_usd)
```

models.py (GamesiteAccount):
```
class GamesiteAccount(models.Model):
    active     = models.BooleanField(default=True, null=None, blank=None)
    created    = models.DateTimeField(default=timezone.now, null=True, blank=True)
    player     = models.ForeignKey(Player, null=False, blank=False, on_delete=models.CASCADE)
    gamesite   = models.ForeignKey('gamesites.Gamesite', null=True, blank=True, on_delete=models.CASCADE)
    login      = models.CharField(max_length=20, unique=False)
    password   = models.CharField(max_length=20, unique=False)
    score_nick = models.CharField(max_length=60, unique=False)

    
    class Meta:
        unique_together = (
        	('gamesite', 'login'),
        	('gamesite', 'score_nick'),
        )  
   
    def __str__(self):
        return '%s // %s' % (self.player, self.gamesite)
```


admin.py (scores):
```
class MyForeignKeyWidget(ForeignKeyWidget):
    def get_queryset(self, value, row):
        return self.model.objects.filter(
            gamesite__name__iexact=row["gamesite"],
            score_nick__iexact=row["score_nick"]
        )


class ScoreResource(resources.ModelResource):
    gamesite_account = fields.Field(widget=MyForeignKeyWidget(GamesiteAccount,)) 
    date             = fields.Field(column_name='date', attribute='date')
    score_usd        = fields.Field(column_name='score_usd', attribute='score_usd')



    class Meta:
        model = Score


class ScoreAdmin(ImportExportModelAdmin):
    resource_class = ScoreResource
```

**Comment by int-ua** [comment]
Skimmed through, looks like the error is in the `MyForeignKeyWidget`: you need to rewrite the `clean` method instead of `get_queryset`.

**Comment by Tib7** [comment]
any examples how to use clean method for a case like this?

**Comment by int-ua** [comment]
Try something like this:

    def clean(self, value, row):
        return self.model.objects.get(
            gamesite__name__iexact=row["gamesite"],
            score_nick__iexact=row["score_nick"])

**Comment by Tib7** [comment]
Unfortunatelly, still can't get gamesite_account_id:

Line number: 1 - NOT NULL constraint failed: scores_score.gamesite_account_id

```
class MyForeignKeyWidget(ForeignKeyWidget):
    def clean(self, value, row):
        return self.model.objects.get(
            gamesite__name__iexact=row["gamesite"],
            score_nick__iexact=row["score_nick"]
        )
```

Any other ideas?

**Comment by int-ua** [comment]
Maybe try explicitly setting attribute for the gamesite_account Resource field? Like in two others.

**Comment by Tib7** [comment]
I don't know if this is what you meant, but still the same error with this: 

```
class ScoreResource(resources.ModelResource):
    gamesite_account = fields.Field(attribute='gamesite_account', widget=MyForeignKeyWidget(GamesiteAccount, 'gamesite_account')) 
    date            = fields.Field(column_name='date', attribute='date')
    score_usd       = fields.Field(column_name='score_usd', attribute='score_usd')
```

and this:
```
class ScoreResource(resources.ModelResource):
    gamesite_account = fields.Field(attribute='gamesite_account', widget=MyForeignKeyWidget(GamesiteAccount,)) 
    date            = fields.Field(column_name='date', attribute='date')
    score_usd       = fields.Field(column_name='score_usd', attribute='score_usd')
```

Of course, I can probably create some kind of slug field for GamesiteAccount and take the id through this way, but reading the manual and this thread i thought i can get the id by importing data of 2 other (already existing) fields of GamesiteAccount model.. 

Any ideas about other solutions?

**Comment by int-ua** [comment]
Oh, you don't have the id field in the file being imported, do you?
Try adding this to ScoreResource.Meta:

    exclude = ('id',)
        import_id_fields = (
            'gamesite_account',
            'date',
        )

Not sure if `score_usd` and `date` are unique or being updated. Maybe just adding empty `id` column to the file will suffice?

**Comment by Tib7** [comment]
I have the id column, but it's rows are empty to make 'autogenerate' new [id]s possible (as shown in my second post).

score_usd is not unique
date is not unique
score_usd and date are not unique together

It's all like in my second post.

In a result of this:
```
exclude = ('id',)
import_id_fields = (
    'gamesite_account',
    'date',
)
```
I got the following error:

Line number: 1 - "Column 'gamesite_account' not found in dataset. Available columns are: ['id', 'gamesite', 'score_nick', 'date', 'score_usd']"

**Comment by marcodaurelio** [comment]
Hello, I have a similar problem.
I want to import-export the daily occupation of an employee (how many hours an employee works per day). The employee is identified by its number and its user `first_name` and `last_name`, so I export them in the DailyOccupation file. How to write a `Resource` to properly import the file?

models.py 
```
class Employee(models.Model):
    number = models.IntegerField()
    user = models.OneToOneField(User, unique=True)
    ... # other not important fields

class DailyOccupation(models.Model):
    ALLOWED_HOURS = ((8, 8), (6, 6), (4, 4), (2, 2), (0, 0))
    mon = models.IntegerField(choices=ALLOWED_HOURS, default=8)
    tue = models.IntegerField(choices=ALLOWED_HOURS, default=8)
    wed = models.IntegerField(choices=ALLOWED_HOURS, default=8)
    thu = models.IntegerField(choices=ALLOWED_HOURS, default=8)
    fri = models.IntegerField(choices=ALLOWED_HOURS, default=8)
    sat = models.IntegerField(choices=ALLOWED_HOURS, default=0)
    sun = models.IntegerField(choices=ALLOWED_HOURS, default=0)
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE)
```
resources.py:
```
class DailyOccupationResource(resources.ModelResource):

    class Meta:
        model = DailyOccupation
        fields = (
            'employee__number',
            'employee__user__first_name',
            'employee__user__last_name',
            'mon',
            'tue',
            'wed',
            'thu',
            'fri',
            'sat',
            'sun',
        )
        export_order = fields
        import_id_fields = (
            'employee__number',
            'employee__user__first_name',
            'employee__user__last_name',
        )
```
This code currently is not able to import: I have error 
`NOT NULL constraint failed: gestione_rapportini_dailyoccupation.employee_id`
How to modify this code to allow import of a csv like this, without the `id` field?
```
employee__number,employee__user__first_name,employee__user__last_name,mon,tue,wed,thu,fri,sat,sun,
1,PINCO,PALLINO,8,8,8,8,8,8,0,
2,ANTONIO,BANDERAS,8,8,8,8,8,0,0,
3,JOHNNY,ENGLISH,8,8,8,8,8,0,0,
```

**Comment by Nihaalmodi** [comment]
@marcodaurelio  
In DailyOccupationResource using Custom Foregin Key Widget along with overriding its clean method will do the work
```
class MyForeignKeyWidget(ForeignKeyWidget):
    def clean(self, value, row):
        return self.model.objects.get(
            number__iexact=row["number"],
            user__first_name__iexact=row["first_name"]
            user__last_name__iexact=row["last_name"]
        )
```
and in modify the resource as follows:
```
class DailyOccupationResource(resources.ModelResource):
    _employee_number = fields.Field(widget=MyForeignKeyWidget(Employee,"number"))
    _employee_user_first_name = fields.Field(widget=MyForeignKeyWidget(Employee,"user__first_name"))
    _employee_user_last_name = fields.Field(widget=MyForeignKeyWidget(Employee,"user__last_name"))
    class Meta:
        model = DailyOccupation
        fields = (
            '_employee_number',
            '_employee_user_first_name',
            '_employee_user_last_name',
            'mon',
            'tue',
            'wed',
            'thu',
            'fri',
            'sat',
            'sun',
        )
```
