### ISSUE TITLE
RemovedInDjango110Warning issue

### ISSUE THREAD

**Issue by Jicehef** [django-import-export/django-import-export#380]
virtualenvs/django19/lib/python3.4/site-packages/import_export/resources.py:492: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'

**Comment by fabian** [comment]
Duplicate of #369

**Comment by bmihelac** [comment]
Fixed with 48b866e
