### ISSUE TITLE
skip_row does not detect the difference when m2m objects are being updated

### ISSUE THREAD

**Issue by javiercf** [django-import-export/django-import-export#385]
`skip_row` method does not the difference between ManyToMany objects in `instance` or `original` because the `instance` related objects remain unchanged.

When using `skip_row` all models where m2m changed are detected as unchanged thus the whole transaction is skipped

**Comment by ses4j** [comment]
To workaround this, I overrode skip_row and added a clause like this:

```
            if field.attribute == 'tags':
                tags = split_tags(self._row.get('Tags'), self._all_tags, separator=',')
                orig_tags = set(field.get_value(original).all().values_list('name', flat=True))
                if tags != orig_tags:
                    return False
```

Which is a lousy hack, but does the job.

**Comment by mxreppy** [comment]
Am I missing something or did you cache the file row data in `_row` somewhere else (looking at the 0.7.0 & 1.0.0 releases

**Comment by irsalmashhor** [comment]
This is my workaound attempt at fixing this issue. For M2M, I sent in the row parameter and use that to detect whether the value of the export is different than the value in the row. Note that this only works if the export value is unique. You'll have to modify the skip_row function to include the new row parameter.

    def skip_row_fix(self, instance, original, row):
        if not self._meta.skip_unchanged:
            return False
        for field in self.get_import_fields():
            if isinstance(field.widget, ManyToManyWidget):
                if self.export_field(field, original) != row[field.attribute]:
                    return False
            else:
                try:
                    if list(field.get_value(instance).all()) != list(field.get_value(original).all()):
                        return False
                except AttributeError:
                    if field.get_value(instance) != field.get_value(original):
                        return False
        return True

**Comment by raphodn** [comment]
I also struggled to update a M2M field which was defined like this:
```
tags = fields.Field(column_name="tags", attribute="tags", widget=ManyToManyWidget(Tag, field="name"))
```
What I ended up doing was to write custom code in the `import_obj()` method, where I manually compare the instance.tags with the row.tags, and do a instance.tags.set() with the corresponding ids (having transformed the tag names into ids beforehand). More importantly, and similarly to a comment above, I add `self._m2m_updated = True` (False if no changes) before calling super, so that I'm able to set `skip_row()` to False for these rows.

Please let me know if there is something easier to do 🤔 🙏 

Full code below, hope it helps :)
```
class QuestionResource(resources.ModelResource):
    category = fields.Field(
        column_name="category",
        attribute="category",
        widget=ForeignKeyWidget(Category, field="name"),
    )
    tags = fields.Field(
        column_name="tags", attribute="tags", widget=ManyToManyWidget(Tag, field="name")
    )

    def import_obj(self, instance, row, dry_run):
        """
        Manually manage M2M column
        - tags: get the row's comma-seperated tags, get their ids, check if they are
        different than the instance, and finally set them to the instance
        """
        tags = row.get("tags")
        tag_ids = []
        if tags != "":
            tags_split = tags.split(",")
            for tag_string in tags_split:
                tag = Tag.objects.get(name=tag_string)
                tag_ids.append(tag.id)
            tag_ids.sort()
        if list(instance.tags.values_list("id", flat=True)) != tag_ids:
            instance.tags.set(tag_ids)
            self._m2m_updated = True
        else:
            self._m2m_updated = False
        super(QuestionResource, self).import_obj(instance, row, dry_run)

    def skip_row(self, instance, original):
        """
        Highlight row if M2M column was updated
        """
        if self._m2m_updated:
            return False
        return super(QuestionResource, self).skip_row(instance, original)

    class Meta:
        model = Question
        skip_unchanged = True
        report_skipped = True
```
