### ISSUE TITLE
How can I change the export import links to actions in django admin

### ISSUE THREAD

**Issue by gitiup** [django-import-export/django-import-export#388]
The import export links lay over top of the add button in django admin.

How can I change these links to show as actions in the django admin so that the link don't overlay on the other admin buttons?

![link over button](https://cloud.githubusercontent.com/assets/502898/12487999/842fc7d2-c037-11e5-8e87-056319da609d.png)

**Comment by bmihelac** [comment]
Override `admin/import_export/change_list.html` template.

**Comment by bmihelac** [comment]
Please reopen if needed

**Comment by gitiup** [comment]
Not sure how to do that and what to change exactly :).
