### ISSUE TITLE
Howto import csv with custom formats

### ISSUE THREAD

**Issue by kellerkind** [django-import-export/django-import-export#391]
I have csv files that have colon seperated values wrapped by quotes. It is really easy importing these formats using the custom csv package that comes with python as it has a well defined set of attributes for handle different csv formats. The tablib support for csv on the other side seems very limited. Is there a way to use the use csv.DictReader as an alternative import approach for importing data? What feature of the tablib.Dataset class are used within the import workflow of import-xport that csv.DictReader lacks?

```
X":"COMMENT":"CORES":"EDITIONKEY":"FARM":"FQDN-LOGIN":"HOSTNAME":"HT-CORES":"HW-FREQUENCY":"HWARCH":"KERNELARCH":"LASTUPDATE":"LICENSEKEY":"MEMORY":"MODEL":"NAME":"PARENT":"SERIAL":"SHORTNAME":"SOCKETS":"SOURCE":"UUID":"VCENTER":"VCENTERPATH":"VIRTUALHUMAN":"VLT-CODE":"POWERSTATE":"CONSOLE"
"C":"":"4":"":"":"machine03p141b.home.sec.local":"machine03p141":"4":"":"":"x86_64":"2016-01-04":"":"":"":"":"564df441-1e6a-b0ca-88fb-f9ece7fa3907":"":"machine03p141":"":"SSH":"613081d7b9f56b42f414be51edbf1ca61fc229a6":"":"":"OS Instance":"6":"":"appl95p01b.home.sec.local"
"C":"":"4":"":"04":"":"":"4":"":"":"":"2016-01-04":"":"12288":"":"machine04p600":"7fe6c80ccc87e8081bf06940d2f404cfaaa4afab":"":"machine04p600":"1":"API":"421b66a1-bb86-c5e1-97e1-d029ab3f1f00":"":"Datacenters/home_virt_dc/host/ESXi/dc-APPZ-2_14_2680/machine04s62.home.sec.local/machine04p600":"Virtual Machine":"5":"poweredOn":"appl95p01b.home.sec.local"
"C":"ED-Medienarchiv App 1.1 Q":"4":"":"":"machine01p74.home.local":"machine01p74":"4":"":"":"x86_64":"2016-01-04":"":"":"":"":"564d933f-592a-ae54-8fa5-6fd9f4cffbaa":"":"machine01p74":"":"SSH":"c4f53878e6ac55041a2db176c13e2bc5a4108e3d":"":"":"OS Instance":"6":"":"appl90p01.home.sec.local"
```

**Comment by jnns** [comment]
The `**kwargs` of tablib's `import_set()` are directly passed on to Python's `csv.reader()`. Unfortunately, django-import-export's `Format.create_dataset()` does not pass any additional arguments to `import_set()` which leaves you with the option of subclassing your own `Format` and adding the dialect there.

**Comment by kellerkind** [comment]
Thanks for your finding. Can you explain why not add the **kwargs to the base_formats? I'd create a pull request for this.

**Comment by avillapalos** [comment]
If you want a custom delimiter, you can do the following:

Create a new Format class and overwrite the `create_database` method:
`class SemicolonCSV(base_formats.CSV):

    def get_title(self):
        return "semicolon_csv"

    def create_dataset(self, in_stream, **kwargs):
        return tablib.import_set(in_stream, format='csv', delimiter=';')`

But you must also create a class based on ImportMixin to overwrite `get_import_formats` method, adding the new format:
`class CustomImportMixin(ImportMixin):
    
    def get_import_formats(self):
        """
        Returns available import formats.
        """
        self.formats += [SemicolonCSV]
        return [f for f in self.formats if f().can_import()]`
