### ISSUE TITLE
Working with django-import-export and django-taggit

### ISSUE THREAD

**Issue by Braintelligence** [django-import-export/django-import-export#392]
Hello everyone.

So I'm trying to export a model that utilizes django-taggit tags.

It looks like this:

``` python
# We do this to get specific ForeignKeys instead of ManyToMany-stuff
class TaggedArticles(TaggedItemBase):
   content_object = models.ForeignKey('Article')


class Article(models.Model):
   title = models.CharField(max_length=300)
   tags = TaggableManager(through=TaggedArticles)


class ArticleResource(resources.ModelResource):

    class Meta:
        model = Article
        import_id_fields = ['id']
        fields = ('id', 'title', 'tags')

    tags = fields.Field(attribute='tags', widget=ForeignKeyWidget(TaggedArticles, 'instance'))
```

My problem is the last line. Where it says instance I deliver the Article object this way but I don't know how to instead reference the tag strings. I think it's something totally stupid but I just can't wrap my head around this.

I would really appreciate any help with this =(.

The relevant .py of taggit can be found here:
https://github.com/alex/django-taggit/blob/master/taggit/models.py

What I'm fetching by referencing 'instance' is the instance attribute of "_TaggableManager".

**Comment by bmihelac** [comment]
@Braintelligence shouldn't there be `ManyToManyWidget` instead of `ForeignKeyWidget`?

**Comment by Braintelligence** [comment]
@bmihelac By using an intermediate class "TaggedArticles" I have a single ForeignKey to one Article per Tag as stated in the docs of django-taggit:

https://django-taggit.readthedocs.org/en/latest/custom_tagging.html

**Comment by Braintelligence** [comment]
Maybe I should use the custom tag route instead. This way I would have direct access to the corresponding TagBase =/.
But from a learning perspective I'd really want to know if I could do it this way somehow.

**Comment by bmihelac** [comment]
Maybe easiest is to provide `dehydrate_tags` method
see:
https://django-import-export.readthedocs.org/en/latest/getting_started.html#advanced-data-manipulation

I am not sure what is article.tags in your case.

**Comment by Braintelligence** [comment]
Does this work both ways? For import and export?

**Comment by bmihelac** [comment]
no, dehydrate_ is only for export.

**Comment by Braintelligence** [comment]
I need it to work both ways.
Is there a hydrate method then?

Maybe I'll try the CustomTag-Route then. ^^

**Comment by Braintelligence** [comment]
Well I don't seem to find a solution.
The problem is, that the field you use in the actual model just references a _TaggableManager instance which then can let you ask for and save tags using methods.
So the ForeignKey doesn't point to a model whose fields I can use to find the correct corresponding instance.

So either I need to ditch this convenient tagging package or I need to write a custom import/export behaviour where the tags column is treated differently from everything else.

I'm kinda looking at a dead end here.

**Comment by bmihelac** [comment]
See ManyToMany widget - it should be a good start. 

https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L243

you just need to write clean and render methods

**Comment by Braintelligence** [comment]
I'm not sure a ManyToMany widget would cut it, though. I don't see the exact route I would have to "follow" to end up at the correct Tag name related to my tagged model.
I have a long ways to go to fully comprehend all things Python and Django related to this case.

I will refrain from using django-import-export for this particular app then and instead use dbbackup. If you are ok with it I'd like to leave the issue open, so maybe sometime someone creates a django-taggit widget for this :).

Thanks for reading.

**Comment by GabLeRoux** [comment]
As @Braintelligence said, `dehydrate_tags` is for export only, but at least it's handy, I managed to export comma separated tags instead of ids using something like this very minimal example:

model:
```python
class Book(models.Model):
    tags = TaggableManager()
```

```python
class BookResource(resources.ModelResource):
    tags = fields.Field()

    class Meta:
        model = Book

    def dehydrate_tags(self, book):
        return ','.join([tag.name for tag in book.tags.all()])
```

I'll give widgets a try and update here if I find something
* [import_export/widgets.py#L239](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L239)
* [customize-widgets](https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-widgets)

**Comment by int-ua** [comment]
I'm going to try writing this widget for taggit tags. How do you all think, is there a better parent than plain `Widget`?

**Comment by beruic** [comment]
I think `Widget` is a fine parrent, but I'd at least take a look at [`SimpleArrayWidget`](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L262) and [`ManyToManyWidget`](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L352) for inspiration.

**Comment by int-ua** [comment]
Export was really simple, for now I'm using this:
```
class TaggitTagsExportWidget(Widget):
    def __init__(self, separator=',', *args, **kwargs):
        self.separator = separator

    def render(self, value, obj=None):
        return self.separator.join([tag.name for tag in value.all()])

    def clean(self, value, row=None):
        raise NotImplementedError('Use readonly=True on the tags field.')
```

But import for import I cannot find a place where instance is already created and available. `after_save_instance` doesn't have `row` values, in `Widget`s' `clean` method instance is not created yet. I'll try to use `after_import_row` but I'll have to hit DB yet another time because the instance itself isn't available, only ID. Did I miss something?

**Comment by int-ua** [comment]
```
    def after_import_row(self, row, row_result, **kwargs):
        instance = self._meta.model.objects.get(pk=row_result.object_id)
        instance.tags.set(*row['tags'].split(','))
```
worked for now but it's a hackish workaround rather than a solution. At least it must not contain 'tags' and separator hardcoded.
