### ISSUE TITLE
Import ascii characters not valid.

### ISSUE THREAD

**Issue by JostCrow** [django-import-export/django-import-export#396]
Hello,

I try to upload a csv file with the name of a user (Ævar). but I get this error. 

```
UnicodeEncodeError encountred while trying to read file: 'ascii' codec can't encode character u'\xc6' in position 241: ordinal not in range(128)
```

I have debugged a part of the code to find out where it goes wrong. Everything goes well except extracting the data from tablib.

If I create a print statement at 'formats/base_formats.py' at line 108 (before return data) It will crash.

Python interpreter = 2.7
Django = 1.9
tablib version = 0.10.0 also tried the dev version.
django-import-export = 0.4.2

**Comment by int-ua** [comment]
#390

**Comment by int-ua** [comment]
Are you having in a development environment? I have it on the production server, but can't reproduce it on my machine even with the seemingly identical configuration.

**Comment by creimers** [comment]
@int-ua I'm facing the production server phenomenon (Elastic Beanstalk, AWS). In development, everything's just fine... Any ideas?

**Comment by int-ua** [comment]
We didn't have this problem for a long time now. Are you able to get a traceback?

**Comment by creimers** [comment]
No traceback... There is a `try, except` in the [source](https://github.com/django-import-export/django-import-export/blob/e6d9be730babc2a54d535b8a95862e5f5606ca26/import_export/admin.py#L267).

If I remove all funny characters (ä, ö, ß, ...) from the csv, it works in production as well. I was looking into the possibility of it being an Apache character settings error, but so far no luck...

**Comment by creimers** [comment]
I'm using python 3.4.3 (both in dev and in prod), django 1.11.9 and django-import-export 1.0.0. 

I have no clue what kind of Apache version is in use, as I don't manage it manually (AWS elastic beanstalk).

**Comment by int-ua** [comment]
Can you execute `locale.getpreferredencoding(False)`? https://stackoverflow.com/a/23917799

**Comment by creimers** [comment]
Was it something that you eventually fixed on the server (nginx) level?

**Comment by creimers** [comment]
```
>>> import locale
>>> locale.getpreferredencoding(False)
'UTF-8'
```

**Comment by creimers** [comment]
There is something about Apache, file uploads and encoding in the django [docs](https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/modwsgi/)... I'll see if that will lead me anywhere.

**Comment by creimers** [comment]
@bmihelac Do you maybe have a clue what the problem could be here?

**Comment by creimers** [comment]
I find it difficult to believe, but it seems to be a missing env var, as indicated in [this SO post](https://stackoverflow.com/questions/3715865/unicodeencodeerror-ascii-codec-cant-encode-character/10986010#10986010) and also in the [django docs](https://docs.djangoproject.com/en/2.0/howto/deployment/wsgi/modwsgi/).

Thank you @int-ua for helping out!
