### ISSUE TITLE
Problems importing data with self-referencing many-to-many fields when foreign keys do not already exist

### ISSUE THREAD

**Issue by patently-offensive** [django-import-export/django-import-export#397]
Thanks to [this discussion](https://github.com/django-import-export/django-import-export/issues/318) I was able to get importing foreign keys that do not exist to work for one to many relationships. I'm now trying to do the same with many to many relationships.

For example, I have a Product model, with an m2m relationship to itself to represent products that are competitive with each other. Example data:

> product_name | competes_with
> Product A | Product C
> Product B |
> Product C | Product B, Product D

I need Product C to be created while importing row 1 and related to Product A and Product D to be created with importing row 3 and linked to Product C.

The below will _create_ new values, but won't create a corresponding M2M relationship unless the foreign key value already existed. So, in the above example:

- C will be created, but not related to A
- B will be related to C on importing C
- D will be created, but not related to C

The below also works perfectly fine if the foreign keys are in a different model. It's not clear to me why the behavior is different when importing data with _self-referencing_ many-to-many fields.

```
class M2MCreateWithForeignKey(widgets.ManyToManyWidget):
    def __init__(self, model, separator=', ', field='pk', defaults=None, create=False):
        self.model = model
        self.separator = separator
        self.field = field
        self.defaults = defaults
        self.create = create

    def clean(self, value):
        values = filter(None, value.split(self.separator))

        if self.create:
            for v in values:
                self.model.objects.get_or_create(defaults=self.defaults, **{self.field:v})
            return super(M2MCreateWithForeignKey, self).clean(value)
        else:
            try:
                val = super(M2MCreateWithForeignKey, self).clean(value)
            except ObjectDoesNotExist:
                model_name = self.model.__name__
                error = "Imported data includes non-existant %s(s) (%s) "\
                    "\nThis model does not support creating a new %s when importing data."\
                    % (model_name, value, model_name)
                logger.error(error)
                return None
            else:
                return val
```

**Comment by patently-offensive** [comment]
I should also note that importing the data a second time does not create the missing relationships, even though it seems like it should. It seems like there may be some deeper issue with self-referencing many-to-many fields that I'm not understanding.

**Comment by patently-offensive** [comment]
I realized what was going on and this behavior is proper. As each row was being imported, the self-referential m2m relationship defined in that row (or, importantly, the absence of such a relationship) was simply overwriting whatever previous relationship(s) had already been imported. I was misinterpreting this as a failure to create new relationships. 

I need special behavior to handle my datasets, where I want a new self-referential relationship defined in row 1 to be created, but not removed if it is absent in row 2. For example

Item 1 | Item 2
A         | B
B         | C

I need this to result in A<->B and B<->C, whereas currently this would result in only B<->C (the original A<->B relationship is removed when row 2 is imported because that row indicates that B is only related to C).

I'll post my code when I get this working in case anyone else needs this behavior.

**Comment by patently-offensive** [comment]
Here's the hackish, but functional, solution I came up with. Hackish because it relies on the inspect module to get info about the row being imported from the caller frame so that existing M2M relationships can be maintained:
```
class M2MAdditiveCreateWithForeignKey(widgets.ManyToManyWidget):
	def __init__(self, model, m2mfield, separator=', ', field='pk', defaults=None, create=False, *args, **kwargs):
		self.model = model
		self.m2mfield = m2mfield
		self.separator = separator
		self.field = field
		self.defaults = defaults
		self.create = create
		super().__init__(self.model, separator=self.separator, field=self.field, *args, **kwargs)

	def clean(self, value):
		values = filter(None, value.split(self.separator))

		if self.create:
			results = [self.model.objects.get_or_create(defaults=self.defaults, **{self.field:v})[0] for v in values]
			# pdb.set_trace()
			caller_frame = inspect.stack()[1].frame
			caller_args = inspect.getargvalues(caller_frame)
			data = caller_args.locals['data']
			this_row = data[self.field]
			existing_obj = self.model.objects.get(**{self.field:this_row})
			existing_related = getattr(existing_obj, self.m2mfield).all()
			existing_related_objs = [self.model.objects.get(**{self.field:r}) for r in existing_related]
			combined_results = results + list(set(existing_related_objs) - set(results))
			pdb.set_trace()
			return combined_results
		else:
			try:
				val = super().clean(value)
			except ObjectDoesNotExist:
				model_name = self.model.__name__
				error = "Imported data includes nonexistant %s(s) (%s) "\
					"\nThis model does not support creating a new %s when importing data."\
					% (model_name, value, model_name)
				logger.error(error)
				return None
			else:
				return val
```

**Comment by JonesKenzie** [comment]
Sorry, I couldn't figure out how to implement this. Can you give the full example?

**Comment by ndthmdg98** [comment]
I solved this Problem using the [_after_import(self, dataset, result, using_transactions, dry_run, **kwargs):_](https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.resources.Resource.after_import) method inside my Resource class through iterating over the rows and add manually the m2m ids to the object.  

```
def after_import(self, dataset, result, using_transactions, dry_run, **kwargs):
      entries = dataset.dict
      for object in entries:
          object_id = object['id']
          object = M2MSelfReferencedModel.objects.get(id=object_id)
          if object['object_m2m']:
              object_m2m_ids = object['object_m2m'].split(',')
              for object_m2m_id in object_m2m_ids:
                  object_m2m_to_add = M2MSelfReferencedModel.objects.get(id=object_m2m_id)
                  object.object_m2m.add(object_m2m_to_add)
```

Don't be worried about the empty columns in the import preview. After the import the m2m relations has been set.
