### ISSUE TITLE
Add feature to export change list columns

### ISSUE THREAD

**Issue by treyhunner** [django-import-export/django-import-export#40]
It looks like only model fields are exported currently.  I'm looking for an app that will also allow exporting the change list columns (sometimes they are aggregates or deep relations).

I can understand if this feature isn't desired since the resulting exported data couldn't be re-imported necessarily.

Adding a "related projects" section to the README and/or documentation with links to other similar projects (some with different goals probably) would be useful.  One of the other admn export libraries probably provides this functionality.

**Comment by manelclos** [comment]
Closing as resolved. Please reopen if necessary.
