### ISSUE TITLE
Can't override methods of ModelResource

### ISSUE THREAD

**Issue by noam-fairfly** [django-import-export/django-import-export#402]
Hi,

I need to override the code for the `save_instance` method but for it seems it can't be overridden when using the modelresource_factory.

Here my resource definition:
```
class MyResource(resources.ModelResource):

    class Meta:
        model = MyModel

    def before_save_instance(self, instance, dry_run):
        print "check override before_save_instance"

    def save_instance(self, instance, dry_run=False):
        print "check override save_instance"
```
And when running this code:
```
resource = resources.modelresource_factory(model=MyModel)()
resource.before_save_instance(instance, False)
```
**Nothing is printed (the original method is called).**

**Comment by bmihelac** [comment]
you want to use ``resource = MyResource() `` instead of ``resources.modelresource_factory``.

**Comment by noam-fairfly** [comment]
Absolutely!
So simple... thank you!
