### ISSUE TITLE
Why not import in bulk?

### ISSUE THREAD

**Issue by ketanbhatt** [django-import-export/django-import-export#403]
Why haven't `bulk_create` been implemented? Importing large sheets is very inefficient at the moment.
(Sorry if it is already implemented)

**Comment by manelclos** [comment]
Hi Ketanbhatt,

As per the official django documentation: https://docs.djangoproject.com/es/1.9/ref/models/querysets/#bulk-create

This has a number of caveats though:

> The model’s save() method will not be called, and the pre_save and post_save signals will not be sent.
> It does not work with child models in a multi-table inheritance scenario.
> If the model’s primary key is an AutoField it does not retrieve and set the primary key attribute, as save() does.
> It does not work with many-to-many relationships.

That said, you can probably override import_data in the Resource and do what you need.

**Comment by ketanbhatt** [comment]
Yes, was planning to do that, but `django-import-export` is an excellent library, and this would have been a good addition. 
What about you allow for `bulk_create` if the user asks you to? A lot of the times our models might not have any relationships, and I don't want to use their `pk`s so its fine if `bulk_create` doesn't return that. 

I can take a swing at it if you think this is something you would want to be included

**Comment by manelclos** [comment]
I think this should be left up to the programmer, no user interaction. So yes, if the programmer knows this can be done safely, django-import-export should make it easy. I don't know though which changes are needed to cleanly implement this.

**Comment by nishanthvijayan** [comment]
Any updates on this?
