### ISSUE TITLE
Import isnt saved

### ISSUE THREAD

**Issue by lilaLeon** [django-import-export/django-import-export#408]
Hello,
I have a problem with the import from a different model. The Previewpage shows the change but it isn't saved into the database

my model.py goes
`class Adress(models.Model):`
`    street = models.CharField(verbose_name="Street", max_length = 100, blank=True)`
`    number = models.CharField(verbose_name="Number", max_length = 10, blank=True)`
`    def __str__(self):`
`        return "{}  {}".format(self.street, self.number)>`

`class Person(models.Model):`

`    adress = models.ForeignKey(Adress, verbose_name="Adress", blank=True, null=True,)`
`    id = models.IntegerField(verbose_name="Person", primary_key=True,)`
In My admin.py I tried

`class PersonResource(resources.ModelResource):`
`    adress__street = fields.Field(attribute='adress__street, column_name='Street_Person')`
`    adress__number = fields.Field(attribute='adress__number, column_name='Number_House_Person')`
`    id = fields.Field(attribute="id", column_name="PersonID")`
    `class Meta:
`        model = Person
`        exlude = ('adress',)`
`class PersonAdmin (ImportExportActionModelAdmin):`
`    resource_class = PersonResource`

Now everythings seems to be working fine. Export works and when I import the excel, the preview shows all changes I made. But after I confirm the Import the database stays the same.
Any idea why this could be?

Kind regards

**Comment by bmihelac** [comment]
django-import-export would not save related models.

See [import workflow](https://django-import-export.readthedocs.org/en/latest/import_workflow.html) for more details and hooks that you can use to save related model. `after_save_instance`  seems good choice.

**Comment by bmihelac** [comment]
Please reopen if needed
