### ISSUE TITLE
MediaStorage does not respect the read_mode parameter

### ISSUE THREAD

**Issue by jbradberry** [django-import-export/django-import-export#416]
Which is a problem if one needs to deal with files by using universal newlines mode, for example.

**Comment by bmihelac** [comment]
Thanks for reporting. Would you like to submit a PR?

**Comment by jbradberry** [comment]
I started on one, but found that the obvious change broke tests elsewhere.

**Comment by bmihelac** [comment]
That is really frustrating :( If you open PR with broken tests I would be glad to take a look and fix tests in the next days.

**Comment by jbradberry** [comment]
It appears that I misremembered, the broken test I was seeing (`core.tests.base_formats_tests.CSVTest.test_import_unicode`) happens on my system regardless of whether I've made changes or not.

**Comment by bmihelac** [comment]
Merged, thanks a lot! Would you be kind to open an issue with stacktrace for broken tests with python and tablib versions.
