### ISSUE TITLE
csv import seems to expect ANSI

### ISSUE THREAD

**Issue by Braintelligence** [django-import-export/django-import-export#423]
Hi there,

when importing a CSV file with comma as delimiter and enclosed within double quotes it seems that tablib? expects ANSI instead of UTF-8 which is kinda contraintuitive.

This is not anything major, since there is an abundance of textcodec conversion tools, but I find this rather strange.

**Comment by jnns** [comment]
Works for me; using a UTF-8 encoded CSV file with comma delimiter and every cell enclosed within double quotes. Besides, there's no ANSI codec - ANSI is only an institute. Looking at [tablib's source](https://github.com/kennethreitz/tablib/blob/master/tablib/formats/_csv.py#L33) I see that UTF-8 is the default encoding.

My suggestion is to file the bug against tablib itself once it's reproducible.

**Comment by int-ua** [comment]
How do you know it does, @Braintelligence ? Is it related to #390 ?

**Comment by Braintelligence** [comment]
ANSI codec is a generic term for a standard codec on a system, so I thought anyone would recognize what I mean. I mean it is even used as a standalone codec term in Notepad++...

In my case it should be Windows-1252.

I don't know why but importing strings with special characters like öüäÖÜÄß resulted in weird symbols when using an UTF-8-encoded CSV, whereas everything was fine, when converting it to Windows-1252 beforehand.
I imported the CSV locally via the manage.py runserver served admin site.

**Comment by jnns** [comment]
@Braintelligence You could step through the `clean()` methods of `Field` and `Widget` with a debugger like `pdb`, and inspect the value's type. Maybe this will shed some light into this.

**Comment by Braintelligence** [comment]
@jnns I'm sorry, I don't have the experience and the time to do this in the next weeks :(. Since I found a rather easy workaround for my case I really just wanted to leave this here, so people can look it up if it happens to them as well.
It could be that this is related to the way Python and Django interacts/works with the Windows OS while importing and thus only few developers will stumble upon this.

If you can't reproduce this on a Windows computer with special characters, then maybe we should close this issue or tag it with low priority.
