### ISSUE TITLE
No static/ when installed via pip

### ISSUE THREAD

**Issue by gpip** [django-import-export/django-import-export#427]
After running `pip install -U django-import-export==0.4.3` you will notice that the `import_export` directory does not include the `static/` directory, causing 404 errors on the js file.

**Comment by int-ua** [comment]
Did you run the `collectstatic` command?

**Comment by gpip** [comment]
Yes, the `static/` simply doesn't exist on the pypi package, so there's nothing to collect from it. If I install from the latest commit in this repo, it works just fine.

**Comment by int-ua** [comment]
Confirming.

**Comment by bmihelac** [comment]
Thanks for reporting, this should be fixed with new release.
