### ISSUE TITLE
error on delete from admin

### ISSUE THREAD

**Issue by simpuc** [django-import-export/django-import-export#432]
Hello,

I am using 0.4.4 version and I got the error

```
Exception Value: 'RowResult' object has no attribute 'object_id'
Exception Location:     /usr/local/lib/python2.7/site-packages/import_export/admin.py in process_import, line 178
```

while I am trying to delete some record using your import function.

I think it is because your code try to log a delete action of an object just deleted. At the row 178 there is

```
object_id=row.object
```

I have resolved it adding at the row 174

```
and row.import_type != row.IMPORT_TYPE_DELETE:
```

I know it do not log the delete action in the admin panel, but never mind.

Thank you for your work and best regards

Simone

**Comment by bmihelac** [comment]
Thanks  for reporting. This should be fixed - please reopen if you still experience difficulties

**Comment by simpuc** [comment]
That's all right!
Thank you
Simone

**Comment by msart** [comment]
Hello, 

I'm using the 1.2 version and found the same problem. To correct this we added back:
```
row_result.object_id = instance.pk
row_result.object_repr = force_text(instance)
```

in the line 512, 513

**Comment by msart** [comment]
I made a PR ([#1101](https://github.com/django-import-export/django-import-export/pull/1101)) with a fix for this problem, that can log the deleted instance correctly, for version 2.0.2

**Comment by jrzerr** [comment]
I can confirm that @msart fix works, had the exact same problem in 2.6.1.

**Comment by matthewhegarty** [comment]
I can reproduce as follows

1. start example app
2. import books1.csv
3. import books2.csv (this marks the book for delete)

[books1.csv](https://github.com/django-import-export/django-import-export/files/7532733/books1.csv)
[books2.csv](https://github.com/django-import-export/django-import-export/files/7532734/books2.csv)

**Comment by matthewhegarty** [comment]
A fix for this issue is now in main branch and will go into release 2.7.0
