### ISSUE TITLE
Failure on not-that-large exports?

### ISSUE THREAD

**Issue by mallyvai** [django-import-export/django-import-export#437]
I'm getting timeouts trying to export our datasets. For now I'm getting around this by cloning the production DB locally and then running the django app locally to export. Here's the error I'm getting;

> SystemExit: 1
> (17 additional frame(s) were not displayed)
> ...
>   File "import_export/resources.py", line 424, in export
>     data.append(self.export_resource(obj))
>   File "import_export/resources.py", line 402, in export_resource
>     return [self.export_field(field, obj) for field in self.get_fields()]
>   File "import_export/resources.py", line 399, in export_field
>     return field.export(obj)
>   File "import_export/fields.py", line 101, in export
>     value = self.get_value(obj)
>   File "import_export/fields.py", line 75, in get_value
>     value = getattr(value, attr)

Some quick notes on our dataset:
- 17 columns 
- 10 of them involve a foreign-key lookup
- The deepest foreign key lookup is 2 hops deep
- The fields are a mix of text and integers, the longest text field is maybe 200 chars.

There are about 1400 records that are being exported. Overall this isn't a lot, so it's a bit concerning. I see older / closed issue reports of timeouts, but they're happening at the level of 300,000 records, and this is much, much smaller. This dataset is < 200KB when the export worked using my 'local' hack.

Any thoughts?

**Comment by bmihelac** [comment]
What is exception thrown? Can you post full stack trace?

**Comment by mallyvai** [comment]
Would be happy to email the error along, the ST contains some semi-private info about my dev setup. Where should I send it?

**Comment by bmihelac** [comment]
@mallyvai bmihelac at mihelac.org
