### ISSUE TITLE
make_password  on diff

### ISSUE THREAD

**Issue by molavy** [django-import-export/django-import-export#438]
i try to implement user bulk import
def get_diff(self, original, current, dry_run=False):
        current.password=make_password(current.password)
        print current.password
        print original.password
        return super(UserResource, self).get_diff(original, current, dry_run)

it return something like this
[u'<del style="background:#ffe6e6;">pbkdf2_sha256$24000$AedsasdfNsddDfAsdcu$7qw323j+ASDFuAasfrPyguAsdfVtmUasdJsdfO6asdf=</del><ins style="background:#e6ffe6;">pbkdf2_sha256$24000$emSnNv2PHoCu$7qsr11j+ZPuxDpvrPyguADuVtmUxAefJgTT/nO6H1rA=</ins>', u'<span>a</span>', u'<span>m</span>']

but on preview don't show any diff row

**Comment by ay1man4** [comment]
Hi,

Have you found a way to import user with password (using make_password)?
