### ISSUE TITLE
Internal Error when exporting in xls format.

### ISSUE THREAD

**Issue by zoonoo** [django-import-export/django-import-export#442]
I've been exporting in xls format using django-import-export for a while, but after adding dehydrate method, I get error while exporting in xls format. It works fine when I export in csv, tsv or html. The server iterates the dehydrate method for all the DB rows, but it returns 500 error in the end.
```
>>> django.VERSION
(1, 8, 0, 'final', 0)
```

```

class ApplicationResource(resources.ModelResource):
    univ_name = fields.Field()

    def dehydrate_univ_name(self, Application):
        userp = get_user_profile(Application)
        univ_code = userp.university
        return univ_code

    class Meta:
        model = Application
        fields = ('user__first_name', 'user__last_name',
                  'user__userprofile__gender',
                  'univ_name')
```

**Comment by zoonoo** [comment]
I was using django-import-export-0.2.7, and have upgraded to django-import-export-0.4.5. The xlsx export works.

**Comment by bmihelac** [comment]
Hi @zoonoo. thanks for contributing. If this is still an issue, please add traceback if possible minimal test case.
