### ISSUE TITLE
 list_filter and search_fields not displaying 

### ISSUE THREAD

**Issue by abadger1406** [django-import-export/django-import-export#443]
In admin.py, change the class defenining to use importExportModelAdmin, as commented out below, and the import / export feature is seen, but I no longer see the search and filter in the admin 

```
#class BlackListAdmin(ImportExportModelAdmin): # this does not allow filter or search to work
class BlackListAdmin(admin.ModelAdmin):
    list_display = ('modified', 'registration','name','comment','carpark')
    list_filter = ('carpark',)
    date_hierarchy = ('modified')
    search_fields = ('registration', 'name')
    resource_class = BlackListResource
```

Just upgraded to latest version
```
Downloading django-import-export-0.4.5.zip (79kB)
```

Still have same issue:-

![screenshot from 2016-05-01 07-52-38](https://cloud.githubusercontent.com/assets/634924/14940534/cecd5776-0f71-11e6-94f5-b3d670c8f981.png)

Then change to use importExportModelAdmin, and display changes:-
![screenshot from 2016-05-01 07-53-06](https://cloud.githubusercontent.com/assets/634924/14940538/e1a1ea2e-0f71-11e6-8937-96b625fd1027.png)

**Comment by bmihelac** [comment]
@abadger1406 you do not use standard django admin, right?

It should be easy enough to override django-import-export admin templates, so they include everything your custom admin requires, please see:

https://github.com/django-import-export/django-import-export/tree/6c7c4eef1fc05485d27b3d9e9223727726f07e0f/import_export/templates/admin/import_export

Please reopen if needed.

**Comment by mayait** [comment]
@abadger1406, did you managed to make it work? 
I'm also using django_admin_bootstrapped and having the same issue

**Comment by mostaszewski** [comment]
@abadger1406 @bmihelac @mayait 
If you have django-admin-bootstrapped installed, the latest working version of django-import-export is 0.42.
After upgrade to 0.43 list_filters don't work.
Here is my solution (i don't know if it will work in your case):
Change this file: **_import_export/templates/admin/import_export/change_list.html_**
```
import_export/templates/admin/import_export/change_list.html 

{% extends "admin/change_list.html" %}

{# Original template renders object-tools only when has_add_permission is True. #}
{# This hack allows sub templates to add to object-tools #}
{% block object-tools %}
  <ul class="object-tools">
    {% block object-tools-items %}
      {% if has_add_permission %}
        {{ block.super }}
      {% endif %}
    {% endblock %}
  </ul>
{% endblock %}
```
to
```
{% extends "admin/change_list.html" %}

{# Original template renders object-tools only when has_add_permission is True. #}
{# This hack allows sub templates to add to object-tools #}
{% block object-tools %}{{ block.super }}{% endblock %}
```
It works for me with the latest (0.6.0) version.
