### ISSUE TITLE
User made available for import but not export?

### ISSUE THREAD

**Issue by shaggyfrog** [django-import-export/django-import-export#446]
I've noticed that a `user` kwarg is populated (from the Django `request`) when `import_data()` gets called, but this is not done for exports. Is there any particular reason why? I am doing an export and need the user details so I can trim some fields out, and I'm happy to add this functionality, but I wanted to check first that there wasn't a reason. Thanks!

**Comment by bmihelac** [comment]
No, there is no particular reason. I would like to have this functionality.
