### ISSUE TITLE
Any way to hide import and export button if not superuser?

### ISSUE THREAD

**Issue by sunjoomoon** [django-import-export/django-import-export#454]
Any tip about hiding import/ export buttons for non superusers?

**Comment by jheld** [comment]
One way to accomplish this is to subclass the admin template for the _change.html that import/export rides on. When the template loads, you can add:
`{% if request.user.is_superuser %} buttons html code {% endif %}`

**Comment by bmihelac** [comment]
Agree with @jheld. Template can be easily changed. Please reopen if needed
