### ISSUE TITLE
Modify file before loading into tablib.Dataset

### ISSUE THREAD

**Issue by JarnoRFB** [django-import-export/django-import-export#456]
I have a situation were a user needs to upload a file in a format that is outputted by another program. However, the format of the file is no valid CSV or anything else, but could be easily brought into that format using some RegEx operations. 
So I would need to know were I could implement such logic, since I could not find a hook for doing file manipulation **before** passing the file to the resource, i.e. before turning it into a `tablib.Dataset`. I believe providing such a hook would be useful.

**Comment by bmihelac** [comment]
@JarnoRFB one option would be to provide your own format, ie: subclass Format and implement ``create_dataset`` method.

https://github.com/django-import-export/django-import-export/blob/master/import_export/formats/base_formats.py#L50

**Comment by bmihelac** [comment]
Please reopen if needed
