### ISSUE TITLE
Need help. Float value instead of decimal.

### ISSUE THREAD

**Issue by tarokinoe** [django-import-export/django-import-export#464]
Hi! Can you help me.
I import this excel file with decimal value of some attributes ("area" for example)
![excel](https://cloud.githubusercontent.com/assets/7135742/15476604/87173900-2142-11e6-9d78-2f53bb660eff.png)
but in import preview the value is float:
![import_preview](https://cloud.githubusercontent.com/assets/7135742/15476699/3a229d00-2143-11e6-9cc2-ee48abcb6a80.png)
Is it possible decimal value in import preview.

**Comment by unbeliever1** [comment]
Hi @tarokinoe
How did you solve that problem with decimal values in xls import?
I will be very grateful for answer

**Comment by tarokinoe** [comment]
Hi @unbeliever1  
I create custom decimal field, where override clean method
```python
class CustomDecimalWidget(widgets.DecimalWidget):
    """
    Widget for converting decimal fields.
    """

    def clean(self, value):
        if self.is_empty(value):
            return None
        return Decimal(str(value))
```

**Comment by unbeliever1** [comment]
It works like a charm. 
Thanks for the solution.
