### ISSUE TITLE
use verbose_name for identifying import Columns Name

### ISSUE THREAD

**Issue by kellerkind** [django-import-export/django-import-export#468]
Set verbose_name flag in resource class. If True verbose_name is used from Django model's field definition. If no verbose_name field is explicitly defined in the model Django' set this value to the default field_name.

	class JiraResource(resources.ModelResource):

		class Meta:
			model = JiraRequest
			import_id_fields = ('key',)
			exclude = ('id',)
			skip_unchanged = True
			report_skipped = False
			verbose_name = True

Patch:
	--- a/import_export/resources.py
	+++ b/import_export/resources.py
	@@ -124,6 +124,12 @@ class ResourceOptions(object):
		 Controls if the result reports skipped rows Default value is True
		 """

	+    verbose_name = False
	+    """
	+    Controls if column name used from Django's model verbose_name attribute. Default value is False
	+    """
	+
	+

	 class DeclarativeMetaclass(type):

	@@ -742,11 +748,15 @@ class ModelResource(six.with_metaclass(ModelDeclarativeMetaclass, Resource)):
			 Returns a Resource Field instance for the given Django model field.
			 """

	+        column_name = field_name
	+        if self._meta.verbose_name:
	+            column_name = django_field.verbose_name
	+
			 FieldWidget = self.widget_from_django_field(django_field)
			 widget_kwargs = self.widget_kwargs_for_field(field_name)
			 field = Field(
				 attribute=field_name,
	-            column_name=field_name,
	+            column_name=column_name,
				 widget=FieldWidget(**widget_kwargs),
				 readonly=readonly,
				 default=django_field.default,

**Comment by bmihelac** [comment]
Closed as per comment:

https://github.com/django-import-export/django-import-export/issues/52#issuecomment-27970222
