### ISSUE TITLE
ImportMixin.process_import does not handle exceptions and can return None

### ISSUE THREAD

**Issue by pajod** [django-import-export/django-import-export#474]
Most easily reproduced by not using POST method when the whole point of that view is POSTing data.

This is obviously not the solution, but to prevent regular Exceptions, a quick workaround in import_export/admin.py is possible:

    +from django.views.decorators.http import require_POST
    
    @@ -110,7 +111,7 @@ def get_urls(self):
             my_urls = [
                 url(r'^process_import/$',
    -                self.admin_site.admin_view(self.process_import),
    +                require_POST(self.admin_site.admin_view(self.process_import)),
                     name='%s_%s_process_import' % info),

**Comment by bmihelac** [comment]
Nice catch, would you like to write a PR for require_POST?

I guess not handling exception in  `process_import` is ok, as exception would be logged/mailed to admin.

**Comment by pajod** [comment]
PR includes a different one-liner: decorators = DRY = better style.

Note: i attached a py3 compatibility fix. Might come in handy reviewing other PRs because more unit tests succeed on travis.
