### ISSUE TITLE
import export not showing up in admin

### ISSUE THREAD

**Issue by CAtoDC** [django-import-export/django-import-export#475]
The django-import-export installed correctly, via pip (I can use it in the Interacive Console); but the buttons don't display in Admin. Django doesn't seem to be recognizing import_export.
![myapp_admin](https://cloud.githubusercontent.com/assets/8337820/15991696/9b5c739e-3088-11e6-96ec-481e5ad5a8a3.png)

**Comment by SalahAdDin** [comment]
Use `ImportExportMixin`.

**Comment by karlhugle** [comment]
same issue....

**Comment by SalahAdDin** [comment]
Put your traceback please.

**Comment by karlhugle** [comment]
works now...
from import_export.admin import ImportExportMixin, ImportMixin, ExportActionModelAdmin

**Comment by bmihelac** [comment]
Guess this is resolved, I am closing it

**Comment by vlordier** [comment]
@bmihelac the from import_export.admin import ImportExportMixin, ImportMixin, ExportActionModelAdmin is not explicitly mentioned in the docs

**Comment by bmihelac** [comment]
@vlordier thanks for noticing, it is available in [api docs](https://django-import-export.readthedocs.io/en/latest/api_admin.html#import_export.admin.ExportActionModelAdmin). If you would like to add more documentation, we'll gladly accept PR.
