### ISSUE TITLE
Import from .xls - ManyToManyWidget AttributeError

### ISSUE THREAD

**Issue by kylemartin87** [django-import-export/django-import-export#48]
An AttributeError error occurs when importing from a .xls file that has a single integer entry in a field representing a ManyToMany relationship.

The issue seems to be that the single integer entry is read in as a float. Then when
ids = value.split(",")
is called on line 153 of import_export/widgets.py the error occurs.

A possible solution could be to add the following two lines above line 153:
if isinstance(value, float):
            value = str(int(value))

**Comment by nattster** [comment]
I ran into this issue with django-import-export 0.5.1.

ManyToManyWidget in master branch has already check for both float & int type:
https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L375

So the master branch should fixed it. Looking forward for upcoming release soon.
