### ISSUE TITLE
import-export not work with mptt

### ISSUE THREAD

**Issue by leotop** [django-import-export/django-import-export#483]
If i use import-export for mptt model, export fine, import error

http://stackoverflow.com/questions/38120853/how-use-django-import-export-and-mptt

Django-Import-Export not imported file if I use django-mptt

Model

class Page(MPTTModel):
    name = models.CharField(max_length=250)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    content = models.TextField(blank=True, null=True)

class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name

Admin

class PageResource(resources.ModelResource):

    class Meta:
        model = Page
        fields = ('id', 'title', 'name', 'content',)
        exclude = ('parent', )

@admin.register(Page)
class PageAdmin(ImportExportModelAdmin):
    empty_value_display = '-empty-'

If I exclude parent error Line number: 1 - 'module' object has no attribute 'izip'

If parent blank or value=name or id, error Line number: 1 - Cannot assign "''": "Page.parent" must be a "Page" instance.

Exclude not work in class Meta.

How import data?

**Comment by thauk-copperleaf** [comment]
Are you using a numbered release? Are you using Python 3? I have corrected a similar error (was a problem with my PR) and have the fix waiting in #477.

We are successfully using mptt, so if you are working off master, I suspect your first issue is fixed by 5f2a3bf (using `zip` instead of `itertools.izip`).

**Comment by leotop** [comment]
Thanks. Fix work for me.

**Comment by leotop** [comment]
Page.parent" must be a "Page" instance. How add parent to child?
Use name or id for parent column not add child. If export data, column parent = name parent.

**Comment by ricjuanflores** [comment]
@leotop How did you solve it?
