### ISSUE TITLE
Import/Export admin buttons not showing up if another mixin is loaded first

### ISSUE THREAD

**Issue by hermanocabral** [django-import-export/django-import-export#486]
Howdy,

I'm facing an issue where the import/export buttons don't show up in the admin page (Django 1.9) if I have another mixin loaded first.

The mixin being loaded first is from django-advanced-filters: https://github.com/modlinltd/django-advanced-filters/blob/develop/advanced_filters/admin.py#L57

eg. 
```
class WhateverAdmin(AdminAdvancedFiltersMixin, ImportExportMixin, admin.ModelAdmin):
    pass
```

Anyone ever experienced that?

Thanks.

**Comment by hermanocabral** [comment]
No longer an issue, thanks.

**Comment by taut-and-yare** [comment]
@hermanocabral I am having the same issue, how did you resolve it?

**Comment by matthewhegarty** [comment]
@taut-and-yare Please can you try with the [3.0.0 release beta version](https://pypi.org/project/django-import-export/3.0.0b3/) and if it is still an issue, can you provide steps to reproduce?

**Comment by taut-and-yare** [comment]
@matthewhegarty to reproduce: I am trying to use a django-advanced-filters  mixin together with `ImportExportActionModelAdmin` like so:
```
@admin.register(Contact)
class ContactAdmin(AdminAdvancedFiltersMixin, ImportExportActionModelAdmin):
    # other stuff
```
The template used is: [admin/advanced_filters.html](https://github.com/modlinltd/django-advanced-filters/blob/develop/advanced_filters/templates/admin/advanced_filters.html)

**Comment by taut-and-yare** [comment]
@matthewhegarty FYI, the problem persists with 3.0.0
I managed to get it to work by adding one include tag in the template mentioned above:
[admin/advanced_filters.html](https://github.com/modlinltd/django-advanced-filters/blob/develop/advanced_filters/templates/admin/advanced_filters.html):
```
{% block object-tools-items %}
  {% include "admin/import_export/change_list_import_item.html" %}
  {{ block.super }}
  {# Add a link to the end of the tool items #}
  {% if advanced_filters %}
	<li><div class="afilters">
		<a class="ajax-popup-link icons-object-tools-add-link" href="#advanced_filters" >{% trans "Advanced Filter" %}</a>{% if '_afilter' in request.GET %}<a class="edit-link" href="{% url 'admin:advanced_filters_advancedfilter_change' current_afilter %}" >{% trans "Edit" %}</a>{% endif %}
</div></li>
  {% endif %}
{% endblock object-tools-items %}
```

**Comment by hermanocabral** [comment]
@taut-and-yare It was so long ago that I barely remember what I did, but as far as I recall there was something missing in the template and I just had to add it there to work.
