### ISSUE TITLE
Dry run not working with transactions is slow

### ISSUE THREAD

**Issue by arj03** [django-import-export/django-import-export#488]
It appears that when running with transactions enabled, the semantics of dry_run changes. This means that in preview mode it will potentially start doing all kinds of crazy database stuff, only to rollback the transaction in case the user doesn't confirm the changes. For our app with a rather complicated save, this makes preview 10 times slower than it should be.

The following patch reverts so that dry_run can be used with transactions as well:

https://github.com/arj03/django-import-export/commit/528ca8fbfc3ad342b4365804a1e9e6a487b84c61

I don't see why we can't both have transactions and dry_run, they should be orthogonal.

**Comment by thauk-copperleaf** [comment]
I have PR #480 already open to fix up transactionality with import_data that you might want to look at.

**Comment by bmihelac** [comment]
Is this still an issue?

**Comment by arj03** [comment]
Should be fixed with #480
