### ISSUE TITLE
Many to many fields and admin upload

### ISSUE THREAD

**Issue by lfarrell** [django-import-export/django-import-export#49]
Do many to many fields work via admin imports?  I keep getting something like this:
ValueError('"<Accession: >" needs to have a value for field "accession" before this many-to-many relationship can be used.',) 

It doesn't seem like it can if it's displaying the data to import before importing, as there's no way to get the primary key for the row since it doesn't have one yet?

Thanks,

Dean

**Comment by PetrDlouhy** [comment]
For anyone reading this. The problem has much simpler solution, than adding separate import and export resources. It is enough to write dehydrate method like this:
```
    def dehydrate_str_choices(self, obj):
        if obj.id:
            return obj.str_choices()
```

**Comment by djangoma** [comment]
In Models.py
class Faculty(models.Model):
	empid = models.CharField(primary_key=True, verbose_name="Employee ID",max_length=20)
	deptname=models.ForeignKey('Department', verbose_name="Department Name", on_delete=models.CASCADE, )
	facultyname=models.CharField(verbose_name="Faculty Name",max_length=100)
		
	def __str__(self):
		return self.facultyname

class Student(models.Model):
	sregno = models.CharField(primary_key=True,verbose_name="Registration Number", max_length=20)
	sname = models.CharField(verbose_name="Student Name", max_length=100)''
def __str__(self):
sbranch = models.CharField(verbose_name="Branch", max_length=50)
	deptname = models.ForeignKey('Department', verbose_name="Department Name",on_delete=models.CASCADE,)
		return self.sname
class ResearchScholar(models.Model):
	rsname = models.CharField(verbose_name="Student Name", max_length=100)
	rsregno = models.CharField(primary_key=True,verbose_name="Registration Number", max_length=20)
	rssupervisor = models.ForeignKey('Faculty',verbose_name="Supervisor's Name", on_delete=models.CASCADE,)
	deptname = models.ForeignKey('Department', verbose_name="Department Name", on_delete=models.CASCADE,)
	def __str__(self):
		return self.rsname

class BookSeries(models.Model):
	refformat=models.TextField(verbose_name="Citation Format",max_length=500,blank=False)
	facultyauthor = models.ManyToManyField('Faculty',verbose_name="Faculty Author")
	studentauthor = models.ManyToManyField('Student',verbose_name="Student Author",blank=True)
	rsauthor = models.ManyToManyField('ResearchScholar',verbose_name="Research Scholar Author",blank=True)
	booktitle = models.CharField(verbose_name="Paper Title",max_length=200,blank=False,default='')

def __str__(self):
		return self.refformat
		
	def display_fauthor(self):
		return ', '.join([facultyauthor.facultyname for facultyauthor in self.facultyauthor.all()[:3]])
	
	display_fauthor.short_description = 'Faculty Name'
	
	def display_sauthor(self):
		return ', '.join([studentauthor.sname for studentauthor in self.studentauthor.all()[:3]])
	
	display_sauthor.short_description = 'Student Name'
	
	def display_rsauthor(self):
		return ', '.join([rsauthor.rsname for rsauthor in self.rsauthor.all()[:3]])
	
	display_rsauthor.short_description = 'RS Name'

----------------------------------------------------------
In Admin.py

class BookSeriesResource(resources.ModelResource):
	facultyauthor = fields.Field(column_name='facultyauthor', widget=ManyToManyWidget(Faculty,'facultyname'))
	studentauthor = fields.Field(column_name='studentauthor', widget=ManyToManyWidget(Student,'sname'))
	rsauthor = fields.Field(column_name='rsauthor',widget=ManyToManyWidget(ResearchScholar, 'rsname'))
	#def dehydrate_facultyauthor(self, book):
	#	return ', '.join(map(str, book.facultyauthor.all()))
	
	#def dehydrate_studentauthor(self, book):
	#	return ', '.join(map(str,book.studentauthor.all()))
	
	#def dehydrate_rsauthor(self, book):
	#	return ', '.join(map(str,book.rsauthor.all()))
	
#return ', '.join(map(str,book.facultyauthor.all().values('facultyname')))

	class Meta:
		model = BookSeries
		fields = ('id','refformat', 'facultyauthor', 'studentauthor','rsauthor','booktitle', 'bookname', 'pubfromconf', 'bsjr', 'bsnip', 'bisbn', 'created_at', 'updated_at', 'created_by', 'updated_by')
		import_id_fields = ['id']
		
	

#return ', '.join([facultyauthor.facultyname for facultyauthor in self.facultyauthor.all()[:3]])


class BookSeriesAdmin(ImportExportModelAdmin, admin.ModelAdmin):
	list_display = ('display_fauthor','booktitle', 'bookname')
	resource_class = BookSeriesResource
	list_filter = ('pubfromconf','bpublishedon',)

------------------
During Export, with dehydrate method in BookSeriesResource, it works fine, displaying the name of the faculty authors. 
Whereas, with dehydrate method, it gives the same error as mentioned in this thread above. 
So i commented dehydrate method while import option and it works fine but without the list of names for facultyauthor.

Could you help me solve this issue?
