### ISSUE TITLE
Ignore import_id_fields in class Meta

### ISSUE THREAD

**Issue by leotop** [django-import-export/django-import-export#490]
Errors
    Line number: 1 - "Column 'id' not found in dataset. Available columns are: ['name', 'model','content']

```
class PageResource(resources.ModelResource):
    class Meta:
        model = Page
        import_id_fields = ('name',)
```

system: python 3.4.3, django 1.9

**Comment by haidaraM** [comment]
I think you have to exclude 'id'. I had a similar a problem.

```python
class PageResource(resources.ModelResource):
    class Meta:
        model = Page
        exclude = ('id',)
        import_id_fields = ('name',)
```

**Comment by LoisWong** [comment]
I have the same problem, too. I tried using "exclude" sentence, but it still not works. I have to change column name to "id" in my database. Then it read id column, while other columns' content doesn't appear. I am still looking for a solution.

**Comment by gbozee** [comment]
I think @haidaraM explanation solves this issue, the `exclude = ('id',)` must be used and a new field which you know would be required should be replaced as the new "id". so if the fields where `name, firstname, lastname, email`, since say `email` is unique it could be what would be used in the `import_id_fields`

**Comment by jwzh222** [comment]
hi @gbozee @haidaraM ,thanks to comments but it doesn't solve the problem. it seems like the meta class option `import_id_fields`  doesn't work when you give it a new value. it still using the default one 'id'.

**Comment by franz-see** [comment]
`import_id_fields` does NOT work for me either

Python Python 2.7.10
Django 1.11.20
django-import-export 1.2.0

**Comment by senabIsShort** [comment]
I'm on the same boat
In my case I have 2 resources built very similarly (identical Meta class), the first one imports properly while using `import_id_fields` but the second one does not.

Has anybody been able to identify the issue ?
I have tried to redefine `get_import_id_fields` but either I did it wrong or django-import-export still used its original definition.

Below are the resources (spared some field definitions) :
``` Python
# The imported files are Excel tables with a column per field (NO ID HEADER)
class PaiementResource(resources.ModelResource):
# This one imports without any problems
    class Meta:
        model = Paiement
        import_id_fields = ('adherent', 'motif',)
        fields = ('adherent', 'motif', 'methode', 'date_paiement', 'montant',)

class ChequeResource(resources.ModelResource):
# This one raises a KeyError 'id' on import
    class Meta:
        model = Cheque
        import_id_fields = ('nom_emetteur_cheque',)
        fields = ('nom_emetteur_cheque', 'banque_emetteur', 'remise__date_remise', 'remise__num_remise')
```

Python 3.7
Django 2.2
django-import-export 1.2

**Comment by cgajagon** [comment]
Hello,
import_id_fields does NOT work for me either
And adding exclude = ('id',) did not work either.

Im using Python 3 and Django 2
