### ISSUE TITLE
can not follow ManyToMany relationship

### ISSUE THREAD

**Issue by GuihaiHU** [django-import-export/django-import-export#491]
It's nice to follow the foreignKey relationship which can print the values and cannot to modify them.
However, it cannot follow ManyToMany relationship.For example

id,proposer,approver,receiver__username
4,1,2,

It does't raise any error.

**Comment by thauk-copperleaf** [comment]
It might be easier to understand the problem if you have a unit test, which specifies what behaviour you are expecting, and the incorrect behaviour you get instead.

**Comment by bmihelac** [comment]
agree with @thauk-copperleaf, please add a failing test case.
