### ISSUE TITLE
Not excluding fields I don't want

### ISSUE THREAD

**Issue by garycurran1** [django-import-export/django-import-export#494]
So I'm trying to integrate this with the admin side and have it so that it will export the table, however when I put something into exclude then try to export nothing happens

In my admin file I have:

```
class ItemResource(resources.ModelResource):

    class Meta:
        model = Item
        exclude = ('authenticate', )
```

and 

```
class ItemAdmin(ImportExportModelAdmin):
    list_display = ['id',  'name', 'category', 'type', 'agent', 'authenticate', ]
    search_fields = ('name', 'category', 'id', 'authenticate', )
    list_filter = ["authenticate"]
    actions = [approve, reject]
```

Everytime I click the button to export it displays all my fields and doesn't exclude authenticate like asked

**Comment by leotop** [comment]
python 3?

**Comment by SergioDzul** [comment]
if you try to exclude some fields try with this:

`class QuestionResource(resources.ModelResource):

    class Meta:
        model = Question
        exclude = ('created_at, updated_at',)

    def get_fields(self):
        fields = super(QuestionResource, self).get_fields()
        new_fields = [field for field in fields if field.attribute not in ['created_at', 'updated_at']]
        return new_fields

class QuestionAdmin(ImportExportModelAdmin):
    """
    Question admin
    """
    list_display = ('content', 'created_at', 'answer')
    exclude = ('created_at', 'updated_at')
    search_fields = ('content',)

    def get_resource_class(self):
        return QuestionResource`

**Comment by bmihelac** [comment]
As @SergioDzul noticed, you forgot to specify `resource_class`

please reopen if needed
