### ISSUE TITLE
Disabling a specific file type in imports/exports

### ISSUE THREAD

**Issue by sassanh** [django-import-export/django-import-export#498]
Thanks for this great django extension, it's been really useful for me.

Is it possible to disable specific file types like json or tsv in import/export forms?

**Comment by thauk-copperleaf** [comment]
Quickly looking at the code, you could subclass `ImportMixin` and `ExportMixin` and override `formats`, which gets its default value from  `DEFAULT_FORMATS`. Or you could override `get_import_formats()` and `get_export_formats()`.

**Comment by sassanh** [comment]
Yeah I found that, forgot to update this github issue. Thanks anyways.
