### ISSUE TITLE
skip_unchanged and report_skipped problem

### ISSUE THREAD

**Issue by misazr** [django-import-export/django-import-export#499]
I have tried examples from document, but I can't not export only selected (checked) objects in my case books from django admin, I always getting all records (books). Could some body give me explanation or example how to get only checked objects?

What I tried:

```
class BookResource(resources.ModelResource):

    class Meta:
        model = Book
        skip_unchanged = True
        report_skipped = False
        fields = ('id', 'name', 'price',)

class BookAdmin(ImportExportMixin, admin.ModelAdmin):
    resource_class = BookResource

admin.site.register(Book, BookAdmin)

```

I found this:
https://github.com/django-import-export/django-import-export/issues/124

but didn't help me.

**Comment by lilaLeon** [comment]
I think you are using the wrong Adminmixin. Try:

`from import_export.admin import ImportExportActionModelAdmin

class BookAdmin(admin.ModelAdmin, ImportExportActionModelAdmin):`

Then you can select the records you like and choose "Export Selected Books" from the dropdown.

Hope it Helps

**Comment by bmihelac** [comment]
@lilaLeon is right, `ImportExportMixin` is used for importing data.
Please reopen if needed.
