### ISSUE TITLE
How to change cell width for exported Excel data? 

### ISSUE THREAD

**Issue by ntorek** [django-import-export/django-import-export#500]
I am trying to figure out how I would change the column cell width in my exported Excel data. Is there a way to set the cell width to auto-size or stretch to the size of the data,  so that if I export a long piece of information, it doesn't get split up into multiple narrow columns, but shown as one wide column with the full text displayed?

**Comment by shaggyfrog** [comment]
That depends on if the tablib library can do it, since that's what we use to read and write Excel files. I'm on my iPhone so it's hard to check that at the moment.

**Comment by bmihelac** [comment]
@ntorek if tablib can do it, we can do it too.

I am interested in adding a feature that would allow some basic styling.

If you want to give it a try, here is tablib code, that should manipulate styles in xlsx format (did not try it).

https://github.com/kennethreitz/tablib/blob/master/tablib/formats/_xlsx.py
