### ISSUE TITLE
Does not set {{ title }} context variable

### ISSUE THREAD

**Issue by brianmay** [django-import-export/django-import-export#504]
The default ``django/contrib/admin/templates/admin/base_site.html``, is used by the page that allows you to select the page format - looks like this is ``export.html``. It has:

```
{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}
```

Unfortunately, this project does not supply a value of title to this template, resulting in incorrect output or (in my case) fatal errors as I have configured Django to generate a fatal error if a template variable is not defined.

**Comment by bmihelac** [comment]
Hi @brianmay! Thanks for noticing. Would you like to add a PR for this?

**Comment by brianmay** [comment]
My time is restricted, however I should be able to do something. First, just to confirm, what branch should I be working from? Master?

**Comment by brianmay** [comment]
Ok, done. https://github.com/django-import-export/django-import-export/pull/519 - hopefully I got the right branch :-)
