### ISSUE TITLE
NoneType exception on importing from admin site

### ISSUE THREAD

**Issue by roshanr95** [django-import-export/django-import-export#508]
I'm getting a `NoneType` exception when the `__str__` method in my model references a `self.*` field. The issue crops up in version 0.4.5 only(0.4.4 works fine)

The offending line is https://github.com/django-import-export/django-import-export/blob/0.4.5/import_export/resources.py#L414 which calls `__str__` on the model instance.

Perhaps `self.*` fields aren't set until the model is saved [here](https://github.com/django-import-export/django-import-export/blob/0.4.5/import_export/resources.py#L430-L432)(atleast for new rows)?

**Comment by bmihelac** [comment]
Hi @roshanr95, is it possible to add failing test for this?

**Comment by int-ua** [comment]
Looks like #439 duplicate

**Comment by int-ua** [comment]
Fixed in `0.6.0` with #505
