### ISSUE TITLE
Feature request: use verbose_name instead of field name for column names

### ISSUE THREAD

**Issue by tijs** [django-import-export/django-import-export#52]
When your exporting data from your database as xls or csv it's usually for human reading so it would be nice if the column names would be the verbose_name of the model fields. i.e. "Company name" instead of company_name for a field: `company_name = models.CharField(_('Company name'))`

As far as i can tell this is not currently possible, even just passing a display_name value to a (custom) field for a resource would be a nice fix...

**Comment by gnuhpc** [comment]
a ugly but work solution:

class XXXXXResource(resources.ModelResource):
    def get_export_headers(self):
        headers = []
        for field in self.get_fields():
            for col in self.Meta.model._meta.__dict__['_field_name_cache']:
                if (col.__dict__['name']==field.column_name):
                    headers.append(col.__dict__['verbose_name'])
        import logging
        logging.debug(headers)
        return headers

    class Meta:
        model = XXXXX
        exclude = ('slug', 'updatedate',)

**Comment by gnuhpc** [comment]
And if you want to export column using corresponding choices value, pls override method as below:

    def export_field(self, field, obj):
        field_name = self.get_field_name(field)
        method = getattr(self, 'dehydrate_%s' % field_name, None)
        logging.debug(field_name)
        if method is not None:
            return method(obj)
        else:
            display = getattr(obj, 'get_%s_display' % field_name,None)
            if display:
                return display()
        return field.export(obj)

**Comment by DurandA** [comment]
@gnuhpc here is an updated solution working with Django>=1.9:
```
def get_export_headers(self):
    headers = []
    for field in self.get_fields():
        model_fields = self.Meta.model._meta.get_fields()
        header = next((x.verbose_name for x in model_fields if x.name == field.column_name), field.column_name)
        headers.append(header)
    return headers
```

**Comment by kellerkind** [comment]
IMO this is simpler implementation and gives control in Resource #468

**Comment by Eluzive** [comment]
How does one also use the verbose names of related objects?

Ex) Trying to get the export the pets name but instead of the column name pet__name showing, we should use the verbose name "Pet Name".

```
class HumanModelResource(resources.ModelResource):
    def get_export_headers(self):
        headers = []
        for field in self.get_fields():
            model_fields = self.Meta.model._meta.get_fields()
            header = next((x.verbose_name for x in model_fields if x.name == field.column_name), field.column_name)
            headers.append(header)
        return headers

    class Meta:
        model = Human
        fields = ("name", "pet__name")

class HumanAdmin(ExportMixin, admin.ModelAdmin):
    resource_class = HumanModelResource
    list_display = ("name", "pet")

class Human(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name")
    pet = models.ForeignKey(Pet)

class Pet(models.Model):
    name = models.CharField(max_length=255, verbose_name="Pet Name")
```

**Comment by nicodelara** [comment]
This work for me.

```
    class Meta:
        model = YourModelHere
        exclude = ('id',)

    def get_export_headers(self):
        headers = []
        for field in self.get_export_fields():
            headers.append(self.Meta.model._meta.get_field(field.column_name).verbose_name)
        return headers
```

**Comment by daimon99** [comment]
I think there is a better implementation now. Both import and export now use verbose name instead of name in the header.

```
class MyBaseResource(resources.ModelResource):
    """
    自定义的导入/导出资源基类。特点：

    #. 导出/导入 excel header 为 verbose_name
    """

    # def get_export_headers(self):
    #     excludes = self._meta.exclude
    #     all_export_fields = filter(lambda x: x.name not in excludes, self._meta.model._meta.fields)
    #     verbose_name_of_all_export_fields = map(lambda x: x.verbose_name, all_export_fields)
    #     return verbose_name_of_all_export_fields

    @classmethod
    def field_from_django_field(cls, field_name, django_field, readonly):
        FieldWidget = cls.widget_from_django_field(django_field)
        widget_kwargs = cls.widget_kwargs_for_field(field_name)
        field = cls.DEFAULT_RESOURCE_FIELD(
            attribute=field_name,
            column_name=django_field.verbose_name,
            widget=FieldWidget(**widget_kwargs),
            readonly=readonly,
            default=django_field.default,
        )
        return field
```

**Comment by waketzheng** [comment]
If your resource class have custom field, code can be as follows:
```py
from import_export import resources
from import_export.fields import Field

class VerboseExportMixin:
    """Export with verbose name"""

    def get_export_headers(self):
        vnames = {i.name: i.verbose_name for i in self.Meta.model._meta.fields}
        return [vnames.get(i.split("__")[0], i) for i in super().get_export_headers()]


class MyModelResource(VerboseExportMixin, resources.Resource):
    url = Field(column_name="Activation URL")
   
    class Meta:
        model = MyModel
```

**Comment by paulzhn** [comment]
With the latest version (2.6.1), you should override both `get_export_fields` and `get_user_visible_fields`

**Comment by furkandemireleng** [comment]
> With the latest version (2.6.1), you should override both `get_export_fields` and `get_user_visible_fields` to make the visible field name be the verbose_name if using the django admin

Hello I am a newbie can you wirte some basics. I wan to export excel file with my list_display only. Can you help me please ? Thanks
