### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one

### ISSUE THREAD

**Issue by facconi** [django-import-export/django-import-export#521]
I am trying to import a very simple excel file, with two columns and two rows.
The columns are "id" and "name".
The first row contains "id" and "name", the second one an integer value (the ID) and the name of the item.
The "id" is the standard primary key.
When I try to import it, I receive the following error:

```
Traceback (most recent call last):
  File "~/env/lib/python2.7/site-packages/import_export/resources.py", line 434, in import_row
    instance, new = self.get_or_init_instance(instance_loader, row)
  File "~/env/lib/python2.7/site-packages/import_export/resources.py", line 258, in get_or_init_instance
    instance = self.get_instance(instance_loader, row)
  File "~/env/lib/python2.7/site-packages/import_export/resources.py", line 252, in get_instance
    return instance_loader.get_instance(row)
  File "~/env/lib/python2.7/site-packages/import_export/instance_loaders.py", line 33, in get_instance
    return self.get_queryset().get(**params)
  File "~/env/lib/python2.7/site-packages/django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Product -- it returned 16!
```

Why is this happening? How can I debug it?

Using:
- Django==1.9.9
- django-import-export==0.5.0

Thank you.

**Comment by thauk-copperleaf** [comment]
What does your Model look like? Your Resource?

What are the exact contents of the file you are importing? (Perhaps in CSV format)

What are your DB contents (for the table associated with the model) before you perform the import? (In other words, are you getting 16 Products back from an empty table?)

What is the value of `params` on line 33 of `instance_loaders.py`? (In other words, what does the query getting Products look like?)

**Comment by facconi** [comment]
Hi.

models.py:

```
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(
            Q(publishing_start_date__lte=date.today()) | Q(publishing_start_date=None),
            Q(publishing_end_date__gte=date.today()) | Q(publishing_end_date=None),
            published=True
        )

class Product(models.Model):
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('last updated'), auto_now=True)
    name = models.CharField(_('name'), max_length=100)
    slug = AutoSlugField(_('slug'), unique=True, populate_from='name', always_update=False)
    published = models.BooleanField(_('published'), default=True)
    publishing_start_date = models.DateField(_('publishing start date'), blank=True, null=True)
    publishing_end_date = models.DateField(_('publishing end date'), blank=True, null=True)

    # more fields for properties

    all_objects = models.Manager()
    objects = ProductManager()

    def get_absolute_url(self):
        return reverse('product', kwargs={'product_slug': self.slug})

    class Meta:
        ordering = ('name',)
        verbose_name = _('product')
        verbose_name_plural = _('products')
```

admin.py

```
class ProductResource(resources.ModelResource):
    class Meta:
        model = Product
        exclude = (
            'created',
            'updated',
            "slug",
            "published",
            "publishing_start_date",
            "publishing_end_date",
            # all other fields except id and name
        )
        import_id_fields = [
            "id",
        ]
        report_skipped = True
        skip_unchanged = True

class ProductAdmin(ImportExportModelAdmin):
    resource_class = ProductResource
```

I have attached the sample .csv file compressed as .zip file. It just have two columns, id and name, and two rows (the first with columns name and the second with id and the new name).
I have exported the file from the admin, edited,  and reimported.

[Product-2016-09-14.csv.zip](https://github.com/django-import-export/django-import-export/files/471766/Product-2016-09-14.csv.zip)

On the DB, ids are unique. There are a lot of products (> 200) and only one with id=114.

I have found that if I run a query using the default manager, everything works find.

Product.all_objects.all().count()

When using the custom manager the error happens.

Using the `_default_manager` for the queries solves the issue:

`Product._default_manager.all().count()`

https://docs.djangoproject.com/en/1.10/topics/db/managers/#django.db.models.Model._default_manager

I think I have to fix my manager, but it should be a wise choice to change all the queries you are doing from objects to _default_manager.

**Comment by yongxinxu** [comment]
Hi, I just solved the same problem by myself. Just check admin.py and make sure **import_id_fields** in ProductResource don't refer to multiple objects.
