### ISSUE TITLE
French locale not in pypi

### ISSUE THREAD

**Issue by frague59** [django-import-export/django-import-export#524]
Hi, 

django-import-export is a great app !

I'm using django-import-export (0.5.0), fr (french) po / mo files are in the git repository , but not in the 0.5.0 distribution package package.

Can you upgrade the package with those files ?

Thanks !

**Comment by bmihelac** [comment]
Hi @frague59 and thanks :)

I am not sure why this happened, it should be fixed in 0.5.1
