### ISSUE TITLE
How can i get the name of the models choices field while exporting?

### ISSUE THREAD

**Issue by skolomiiets** [django-import-export/django-import-export#525]
I have a model with choices list (models.py):

    class Product(models.Model):
        ...
        UNITS_L = 1
        UNITS_SL = 2
        UNITS_XL = 3
        PRODUCT_SIZE_CHOICES = (
        (UNITS_L, _('L')),
        (UNITS_SL, _('SL')),
        (UNITS_XL), _('XL'),
        )
        product_size = models.IntegerField(choices=PRODUCT_SIZE_CHOICES)
        ...

Also I added a new class for exporting needed fields(admin.py):

    from import_export import resources, fields
    ...
    Class ProductReport(resources.ModelResource):
        product_size = fields.Field()

        class Meta:
            model = Product

        #I want to do a proper function to render a PRODUCT_SIZE_CHOICES(product_size)

        def dehydrate_size_units(self, product):
            return '%s' % (product.PRODUCT_SIZE_CHOICES[product_size]) 

        fields = ('product_name', 'product_size')

    Class ProductAdmin(ExportMixin, admin.ModelAdmin):
        resource_class = ProductReport

But this is not working. How can I get a named value of PRODUCT_SIZE_CHOICES in export by Django import-export ?

**Comment by int-ua** [comment]
You'll need a Widget for this, here is mine, for example:
```
class ChoicesWidget(Widget):
    """
    Widget to substitute localized choices.
    N.B.: before_import is executed before Widget.clean
    """
    def __init__(self, choices, *args, **kwargs):
        activate(settings.LANGUAGE_CODE)
        self.choices = {str(value): str(key) for (key, value) in choices}

    def clean(self, value, row=None):
        # виконується після before_import
        return self.choices.get(value, value) if value else None

    def render(self, value):
        if value is None:
            return ""
        return value
```

**Comment by johnfraney** [comment]
For anyone else who stumbled across this looking for an easy way to import/export your choice display values, I made a couple tweaks to @int-ua's code above and it's working well for me:

```
from import_export.widgets import Widget


class ChoicesWidget(Widget):
    """
    Widget that uses choice display values in place of database values
    """
    def __init__(self, choices, *args, **kwargs):
        """
        Creates a self.choices dict with a key, display value, and value,
        db value, e.g. {'Chocolate': 'CHOC'}
        """
        self.choices = {str(value): str(key) for (key, value) in choices}

    def clean(self, value, row=None):
        """Returns the db value given the display value"""
        return self.choices.get(value, value) if value else None

    def render(self, value):
        """Returns the display value given the db value"""
        for display_val, db_val in self.choices.items():
            if db_val == value:
                return display_val
        return ''
```

To use the widget, be sure to pass in the choices from your model:
```
from import_export import resources, fields


class MyModelResource(resources.ModelResource):
    my_choice_field = fields.Field(
        widget=ChoicesWidget(MyModel.MY_CHOICE_FIELD_CHOICES),
        column_name='my_choice_field',
        attribute='my_choice_field',
    )
    class Meta:
        ...
```

**Comment by mpyrev** [comment]
Updated snippet to support latest version and made it O(1) in render method instead of O(n).
```python
from import_export.widgets import Widget


class ChoicesWidget(Widget):
    """
    Widget that uses choice display values in place of database values
    """
    def __init__(self, choices, *args, **kwargs):
        """
        Creates a self.choices dict with a key, display value, and value,
        db value, e.g. {'Chocolate': 'CHOC'}
        """
        self.choices = dict(choices)
        self.revert_choices = dict((v, k) for k, v in self.choices.items())

    def clean(self, value, row=None, *args, **kwargs):
        """Returns the db value given the display value"""
        return self.revert_choices.get(value, value) if value else None

    def render(self, value, obj=None):
        """Returns the display value given the db value"""
        return self.choices.get(value, '')
```

**Comment by twz915** [comment]
https://stackoverflow.com/a/49186282/2714931

**Comment by twz915** [comment]
https://stackoverflow.com/a/49186282/2714931
