### ISSUE TITLE
resource.py self.save_instance error when importing data

### ISSUE THREAD

**Issue by carlosp420** [django-import-export/django-import-export#528]
I am trying to import data in an XLS file and I get this error:

```python
Traceback (most recent call last):
  File "/home/voseq/.virtualenvs/voseq/lib/python3.4/site-packages/import_export/resources.py", line 459, in import_row
    self.save_instance(instance, using_transactions, dry_run)
TypeError: save_instance() takes from 2 to 3 positional arguments but 4 were given
```

I have been able to do a fix by replacing the line with:
```python
    self.save_instance(instance, dry_run)
```

But I guess this is not a good fix.

**Comment by shaggyfrog** [comment]
Yes, the [`Resource.save_instance()`](https://github.com/django-import-export/django-import-export/blob/cee40b80b9f310d4555249c59cb0ca199d4376ac/import_export/resources.py#L264) method was given an extra parameter called `using_transactions` in 0.5.0. But every call to it, that I can see, has been updated to use the extra parameter. So I'm not sure what's wrong.

Have you overridden that method in your resource class somewhere?

If you're certain this is an error in the library (as you suggested in the issue you referenced), can you provide a test case that will reproduce the error?

**Comment by carlosp420** [comment]
sorry for the false alarm @shaggyfrog I just checked my code and I have a method that overrides the `save_instance` method using the old way (without the `using_transactions` parameter). That triggered the error message.
I was confused about this error because the traceback pointed to `4/site-packages/import_export/resources.py` and not to my method.

I will close this issue.
