### ISSUE TITLE
Change limit of file dimensions

### ISSUE THREAD

**Issue by gbrennon** [django-import-export/django-import-export#531]
Hey!

Is there a way to change file limit?

I'm trying to import a .csv that is returning me "invalid dimensions", but if I import a smaller version of this .csv(less rows) django-import-export works

**Comment by bmihelac** [comment]
invalid dimensions is not related with file limit, but exception that tablib raises when headers and data does not fit:

http://docs.python-tablib.org/en/latest/api/#tablib.InvalidDimensions

**Comment by annapaola** [comment]
It would be great if the app mentioned in the error, the source of the problem.
