### ISSUE TITLE
How to update fk object's field?

### ISSUE THREAD

**Issue by mmospanenko** [django-import-export/django-import-export#532]
Hello! I did'n find this case in documentation/code and asking here. 
If Author from example has another field 'country'. How can I change this field by importing Books?
For example I want to change author's another field looking up by 'name'. 

I'm trying to reload widget.clean method for this (hardcoded lookup field) but where should I set new values (for diff and saving after)? I think that widget is not good place for create/lookup/edit objects (fk fields). Give me advice please how to it in right way.

I think this case very popular, add please in docs example.

Thank you

**Comment by shaggyfrog** [comment]
If you want to update a different model than the one you're importing, you can do that by overriding one of several different methods in your Resource class (like `Resource.after_import_row`), to look up the Author (`author = Author.objects.get(...)`) and then change it however you want.

**Comment by mmospanenko** [comment]
But how can I create new objects if TransactionManagementError raises with save() inside 'atomic' block?

I want to update related objects (with lookup) with current row.

**Comment by mmospanenko** [comment]
Everything ok. I've found that its bug [#399]. 
Thank you
