### ISSUE TITLE
Why would you ever setattr on None (in the case of relationship / ForeignKey)

### ISSUE THREAD

**Issue by iankpconcentricsky** [django-import-export/django-import-export#535]
Field.save() has the logic

```
    def save(self, obj, data):
        """
        If this field is not declared readonly, the object's attribute will
        be set to the value returned by :meth:`~import_export.fields.Field.clean`.
        """
        if not self.readonly:
            attrs = self.attribute.split('__')
            for attr in attrs[:-1]:
                obj = getattr(obj, attr, None)
            setattr(obj, attrs[-1], self.clean(data))

```

while init_instance() on ModelResource does

```
    def init_instance(self, row=None):
        """
        Initializes a new Django model.
        """
        return self._meta.model()
```

Which, if the model instance has a relation (FK), will not create the relation instance (RelatedObjectDoesNotExist).

The getattr in Field.save() above will return None (as it is declared to), and the setattr below it will attempt to set a value on None, not the relation instance (which obviously explodes).

In other words, given a field

```
class SomeModelResource(resources.ModelResource):
    relation_field = fields.Field(attribute='relation_model__property')
```

The logic will behave:

```
bad_instance = self._meta.model()  # i.e. SomeModel()
relation = getattr(bad_instance, 'relation_model', None)  # Returning None 💁
setattr(relation, 'property', 'value')
```

**Comment by bmihelac** [comment]
Good catch @iankpconcentricsky.

I am not sure if it would be better to silently skip setting obj attribute if it obj is None or to just assert that obj is not None and raise an error.

What do you think?

cc @thauk-copperleaf

**Comment by iankpconcentricsky** [comment]
@bmihelac I don't think silently skipping would be a good experience for developers. My initial reaction is that the code in Field.save() looks bad; too clever (not explicit enough in its intention) and inherently flawed (in the sense that it gets literally nothing done for the creation of an instance who has foreign keys even though it appears as though it intends to)

**Comment by bmihelac** [comment]
I agree that silently skipping is not ok and it is different that what is done currently.
Not sure that any handling of non existing instances should be in a Field class. This is meant just to handle simple cases.

**Comment by iankpconcentricsky** [comment]
@bmihelac Well the intention is to map an import value (the rows column) to a related property of the ModelResource's model.  I'd say... if it's going to suggest it does that, it should do that. Field.save() looks currently incapable of doing what it suggests it will.
