### ISSUE TITLE
display list error message convert to Table style

### ISSUE THREAD

**Issue by ibnbay99** [django-import-export/django-import-export#537]
I want ask and share my way to display list error message to be table syle and make more readable.
![desctop screenshot](https://cloud.githubusercontent.com/assets/21232045/19624081/8c100234-9910-11e6-8e57-5c1e44dc995e.png)
![desctop screenshot2](https://cloud.githubusercontent.com/assets/21232045/19624082/8c1358e4-9910-11e6-96dc-5db0ace3b19e.png)

On second image (browser), on column Reason.
I just want to display Second message: from (example) "DETAIL: Key (email)=(andi11@gmail.com) already exists."

Or other u already apply something like me? Or have another idea to make error message be more readable... 

Thanks before...

**Comment by anupy** [comment]
Is this feature implemented?
