### ISSUE TITLE
can I use django-import-export import fields different with the export fields?

### ISSUE THREAD

**Issue by lx1054331851** [django-import-export/django-import-export#539]
I found with django-import-export, the import fields and export fields is the same, but I want to set different fields when importing and exporting, I don't know whether django-import-export support that?

**Comment by bmihelac** [comment]
Off course, use 2 resources.

**Comment by lx1054331851** [comment]
hi @bmihelac , can I ask a simple example 😊 , I am not actually understand the documentation. 😢

**Comment by bmihelac** [comment]
This would use BookResource for import and ExportBookResouce for export.

```
class BookAdmin(ImportExportModelAdmin):
    resource_class = BookResource

    def get_export_resource_class(self):
        """
        Returns ResourceClass to use for export.
        """
        return ExportBookResource
```

**Comment by thauk-copperleaf** [comment]
Have you tried overriding `Resource.get_export_fields()`? https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L597

We use that to change both what fields are visible on the import screen, as well as what fields get exported.
