### ISSUE TITLE
Widget rendering Issue (0.5.1)

### ISSUE THREAD

**Issue by lilaLeon** [django-import-export/django-import-export#547]
After updating to the newest version ive got issues with exporting models that use the importexportmixin and have no resource of their own.
The errormessage is:
    render() takes 2 positional arguments but 3 were given
Any Ideas on how to fix this?

Thanks in advance!

**Comment by bmihelac** [comment]
Hi @lilaLeon 

please post full stack trace

**Comment by lilaLeon** [comment]
Hey bmihelac,
here is the traceback:
Traceback:

File ".../python3/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File ".../python3/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File ".../python3/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File ".../python3/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File ".../python3/lib/python3.5/site-packages/django/contrib/admin/sites.py" in inner
  244.             return view(request, *args, **kwargs)

File ".../python3/lib/python3.5/site-packages/import_export/admin.py" in export_action
  377.             export_data = self.get_export_data(file_format, queryset, request=request)

File ".../python3/lib/python3.5/site-packages/import_export/admin.py" in get_export_data
  364.         data = resource_class(**self.get_export_resource_kwargs(request)).export(queryset, *args, **kwargs)

File ".../python3/lib/python3.5/site-packages/import_export/resources.py" in export
  630.             data.append(self.export_resource(obj))

File ".../python3/lib/python3.5/site-packages/import_export/resources.py" in export_resource
  601.         return [self.export_field(field, obj) for field in self.get_export_fields()]

File ".../python3/lib/python3.5/site-packages/import_export/resources.py" in <listcomp>
  601.         return [self.export_field(field, obj) for field in self.get_export_fields()]

File ".../python3/lib/python3.5/site-packages/import_export/resources.py" in export_field
  595.         return field.export(obj)

File ".../python3/lib/python3.5/site-packages/import_export/fields.py" in export
  122.         return self.widget.render(value, obj)

Exception Type: TypeError at /admin/db/thismodel/export/
Exception Value: render() takes 2 positional arguments but 3 were given

**Comment by bmihelac** [comment]
ok, do you use some custom widget?

**Comment by shaggyfrog** [comment]
The signature of the widget render() method was changed at https://github.com/django-import-export/django-import-export/commit/91845fc988875b13efb4b30eaa38ca6010d903c8

Like @bmihelac says, if you've subclassed widget and overrode the render() method, but you didn't update its parameter list to match the change, then you'll get this exception.

**Comment by lilaLeon** [comment]
Hey thanks for your help!
I do use some custom widgets, but they all look like this(after the update):
class MyBoolWidget(Widget):
    TRUE_VALUES = ["True", "ja", "Ja", "x", "1", 1]
    FALSE_VALUE = ["False","nein","Nein", "0", ""]

    def render(value, obj):
        if value is None:
            return ""
        if value == False:
            return "nein"
        else:
            return "ja"

    def clean(self, value, row):
        cleaned = value.strip().split()
        if not cleaned:
            return None
        elif cleaned[0] in self.TRUE_VALUES:
            return True
        else:
            return False


Is that incorrect?

**Comment by lilaLeon** [comment]
class MyBoolWidget(Widget):
    TRUE_VALUES = ["True", "ja", "Ja", "x", "1", 1]
    FALSE_VALUE = ["False","nein","Nein", "0", ""]

    def render(self, value, obj):
        if value is None:
            return ""
        if value == False:
            return "nein"
        else:
            return "ja"

    def clean(self, value, row):
        cleaned = value.strip().split()
        if not cleaned:
            return None
        elif cleaned[0] in self.TRUE_VALUES:
            return True
        else:
            return False

**Comment by shaggyfrog** [comment]
So then what is the value of self.widget at the bottom of that stack trace?

Your first revision to your comment had

def render(value, obj)

But now it's

def render(self, value, obj)

Which would have caused the exception

**Comment by lilaLeon** [comment]
Hey @shaggyfrog , thanks again but I'm afraid thats still not the issue. 
Like I said in the original post the problem occurs when I have no Resourceclass and  model_resourcefactory is used (I think).
I dug a little deeper and it seems the error always occurs when Datefields are involved.
For example this would throw an error:
 in models.py:
class Book(models.Model):
    versand = models.DateField(blank=False, null=True, verbose_name='Versanddatum')
    id = models.AutoField(primary_key=True, verbose_name="Nummer")
and in admin.py:
class BookAdmin(ImportExportMixin):
    list_display = ['id', 'versand']

**Comment by lilaLeon** [comment]
I found the error.. I overlooked a file in my branch and now its fixed.
Sorry for wasting your time!
