### ISSUE TITLE
TemplateDoesNotExist error due to django.template.loaders.eggs.Loader being deprecated

### ISSUE THREAD

**Issue by machakux** [django-import-export/django-import-export#548]
Since Django 1.9 the [`django.template.loaders.eggs.Loader`](https://docs.djangoproject.com/en/1.10/ref/templates/api/#django.template.loaders.eggs.Loader) has been deprecated and it looks like it is not among the default template loaders in Django 1.10.

When installing `django-import-export` as a dependancy of another package (example; using `python setup.py develop` on a dependant package) `django-import-export` gets installed as a zipped egg file which results into a `TemplateDoesNotExist` unless `django.template.loaders.eggs.Loader` is added to settings manually.

Will it be useful adding [`zip_safe = False`](http://setuptools.readthedocs.io/en/latest/setuptools.html#id26) in setup.py (or something similar) in order to discourage installation of django-import-export as a zipped egg?

**Comment by rooterkyberian** [comment]
Adding a example of exception message to make this little easier to google:
```
TemplateDoesNotExist: admin/import_export/change_list_import.html
```

**Comment by mp3il** [comment]
any fix?

**Comment by timthelion** [comment]
You need to include 'import_export' in your 'INSTALLED_APPS' in `settings.py`

**Comment by CJohnDesign** [comment]
I'm having the same problem. Working locally but broken in production. 

Django==1.11.29
django-import-export==1.2.0
