### ISSUE TITLE
Preview template outside admin

### ISSUE THREAD

**Issue by ibnbay99** [django-import-export/django-import-export#554]
Anyone can provide example project with upload preview template like in admin (tests folder)?
And give error message if failed...

Thanks...

**Comment by smalldale** [comment]
I have found the answer [here](https://stackoverflow.com/a/57875725).
I also created an [example](https://github.com/smalldale/Django-Import-Outside-Admin-Example) of it.


![preview](https://user-images.githubusercontent.com/49019693/100786937-75e10100-3445-11eb-8659-44b04962dc34.png)
