### ISSUE TITLE
export Hebrew or Russian text from Django admin to CSV file

### ISSUE THREAD

**Issue by AlexandrKO** [django-import-export/django-import-export#555]
Hi all, 

I use  "django-import-export/django-import-export" in my project and when I try to export Hebrew or Russian text from Django admin to CSV file I receive unknown text (For example: 
"יום העצמאות" from Django will be represented in CSV as "׳™׳•׳ ׳”׳¢׳¦׳ž׳ ׳•׳×"). Import work well. I checked to_encoding and from_encoding it is 'utf-8' format. Phython 3.5.2, Djando 1.10.1.

Thank you, 
Alexander

**Comment by 4iGAN** [comment]
@AlexandrKO I use the same configuration and I have no problem with it. I use openoffice for edit csv-file.
