### ISSUE TITLE
Having problem importing "image" within Csv

### ISSUE THREAD

**Issue by 10featj** [django-import-export/django-import-export#562]
I understand I won’t be able to upload an image but is there anything I can put in its places a holder whilst I upload other data. 

When I upload a data set the same to the one I exported (except unique id's) I get an error 
“ Cannot assign "u''": "Component.data_sheet" must be a "File" instance.”

I understand the 'U' has something to do with Unicode, but is there anything I can put in this field that will bypass this error and uplaod the rest of the data?

Any help or pointers will be appreciated, I am kind of new to Django though.

Thank you for reading,

**Comment by bmihelac** [comment]
Hi @10featj,

you can customize resource with using `exclude` option, see documentation:

https://django-import-export.readthedocs.io/en/latest/getting_started.html#customize-resource-options

This kind of question would be more appropriate to ask on stackoverflow.
