### ISSUE TITLE
Any way to import/export to multiple tables from one csv?

### ISSUE THREAD

**Issue by SudShekhar** [django-import-export/django-import-export#563]
Hi,

Thanks for making this!

I am trying to create an import/export flow that spans multiple tables.
For example, let's say this is my csv file

`id | question_text | answer_1 | answer_2| answer_3| correct_answer`

And I have two tables: `Questions` and `Answers` , such that answer points to question and stores the answer text plus whether its correct or not, while question just has the text and id.

I was wondering if its possible to create such a flow with the current library (couldn't find anything in the documentation) and if anyone else has tackled a similar issue?

Thanks.

**Comment by shaggyfrog** [comment]
There's no one exact way to do this. One way is to use a single Resource class that creates associated objects in `import_field()`.

**Comment by kellerkind** [comment]
Why not use a third table like "Exam", where you save the csv row. Then use ForeignKeys to Question and Answers.
