### ISSUE TITLE
inserting rows.

### ISSUE THREAD

**Issue by Aameer** [django-import-export/django-import-export#566]
Hey guys I used django-import-export to create an excel report now I wanted to add some details to the top (above the headers without overriding any data) but I wasn't able to figure it out. Is there a way that I can pre-pend some rows on top of dataset and then fill it up with some documentation notes? . I even tried to use lpush(http://docs.python-tablib.org/en/latest/_modules/tablib/core/#Dataset.lpush) of tablib which I guessed might work as the type of dataset was showing as tablib , but it didn't work. Any suggestions how I might be able to achieve this?.Thanks

**Comment by bmihelac** [comment]
Hello, @Aameer.

are you able to do this with tablib directly?

**Comment by Aameer** [comment]
@bmihelac , no unfortunately it didn't work as I have already mentioned in the above comment. Since I was short on time so I dropped it. It would awesome to enable such changes on the dataset and highly add to the usability of django-import-export. Moreover I would be more than happy to help in whichever form I can to move this forward.
