### ISSUE TITLE
cannot exclude id field during import : KeyError: u'id'

### ISSUE THREAD

**Issue by ydaniels** [django-import-export/django-import-export#570]
am trying to import in admin and already excluded the id field but i get

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/import_export/resources.py", line 434, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "/usr/local/lib/python2.7/dist-packages/import_export/resources.py", line 258, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "/usr/local/lib/python2.7/dist-packages/import_export/resources.py", line 252, in get_instance
return instance_loader.get_instance(row)
File "/usr/local/lib/python2.7/dist-packages/import_export/instance_loaders.py", line 31, in get_instance
field = self.resource.fields[key]
KeyError: u'id'
```

why is it compulsory to include id field i thought it should be autogenerated

**Comment by jwzh222** [comment]
i'm having the same issue, it seems like the meta class option import_id_fields doesn't work when you give it a new value. it still using the default one 'id'. 

`class SponsorBlockResource(resources.ModelResource):
    class Meta:
        model = SponsorBlock
        exclude = ('id', )
        import_id_fields = ('name',)
        skip_unchanged = True
        fields = ['name','block_time',]`

**Comment by ydaniels** [comment]
yes that's what i did to fix the problem but i think its not necessary to include id field when importing new data, a fix for this would be nice.

**Comment by SubraGomz** [comment]
@jwzh222  Where did you add this SponsorBlockResource class in Django admin.py or views.py or someother file?
Please specify

**Comment by ababic** [comment]
@jmgamboa That's my understanding too. The `id` column must be present in the uploaded file, but the values can be blank for new items. I've added a PR (#996) to make things work even when `id` (or whatever columns are specified in `Meta. import_id_fields`) are not present in the uploaded file.
