### ISSUE TITLE
How to import related objects and their relationships.

### ISSUE THREAD

**Issue by dg1980** [django-import-export/django-import-export#571]
When I import models like following:

```
class Category(models.Model):
   name = models.CharField(max_length=100, db_index=True)

class Subcategory(models.Model):
   name = models.CharField(max_length=100, db_index=True)
   slug = models.SlugField(max_length=200, db_index=True)
   category = models.ForeignKey(Category, blank=True)

class Product(models.Model):
   name = models.CharField(max_length=100) 
   category = models.ForeignKey(Category, blank=True, null=True)
   subcategory = models.ForeignKey(Subcategory, blank=True, null=True)
```

Everything is imported thanks to ForeignKeyWidget, but how can I import relations when my csv file looks something like that:

id | product_name | category | subcategory
-- | T-Shirt A  | His | summer
-- | T-Shirt B  | Her | summer

?

As you see 'summer' subcategory name isn't unique and I need to set the proper relationship like:

'His' < 'summer' < 'T-Shirt A'
'Her' < 'summer' < 'T-Shirt A'

during import.

How can I achieve it?

I will be grateful for your help.

**Comment by bmihelac** [comment]
Hi @dg1980 

check [import workflow](https://django-import-export.readthedocs.io/en/latest/import_workflow.html)

One quick option could be to subclass `import_obj()` and set subcategory based on row value and instance category.

**Comment by dg1980** [comment]
Dear @bmihelac 

Thank you kindly for your help. I'll try to solve it based on your suggestion.

**Comment by dg1980** [comment]
Could you give an example of code? (how to sublass Import_obj())

I am doing something wrong..

**Comment by dg1980** [comment]
Dear @bmihelac,

I have tried to subclass import_obj() and I have following experiences with it:

if I try to do something like:

```
def import_obj(self, instance, row, dry_run):
        super(ProductResource, self).import_obj(instance, row, dry_run)
        instance.name = 'some_value' 
```

product instance name is being overridden.

If I try to override instance.subcategory it returns an following exception:

Cannot assign "'some_value'": "Product.subcategory" must be a "Subcategory" instance. 

So how to invoke "Subcategory" instance set subcategory.category to "some_value".

I will be grateful for your support.

**Comment by bmihelac** [comment]
@dg1980 in last line, you have both new instance and row with all passed values. Finding and assigning subcategory instance to product.subcategory should be easy from there.

**Comment by gthieleb** [comment]
I have solved this in my current project (for importing ManyToMany Values) with subclassing `import_field` and calling a `clean_FOO` method (adapted the code from `dehydrate_FOO`). Within the clean method (example here are ManyToMany fields `disks` and `filesystems`) you can get the correct subcategory or create the instance with Django's `get_or_create` method (Careful about the return values here). 

	class SpecResource(resources.ModelResource):

	    disks = fields.Field(column_name='Disks')
	    filesystems = fields.Field(column_name='Filesystems')

	    class Meta:
		model = Spec
		exclude = []

	    def import_field(self, field, obj, data):

		field_name = self.get_field_name(field)
		method = getattr(self, 'clean_%s' % field_name, None)
		if method is not None:
		    obj = method(field, obj, data)

            super(SpecResource, self).import_field(field, obj, data)


	    def clean_disks(self, field, obj, data):

		disks = []
		cell = data[field.column_name]
		for e in cell.split(','):
		    e = e.strip().split('-')
		    if len(e) < 3:
		        continue
		    size, disk_type, quality = e
		    qualityi, created = StorageQuality.objects.get_or_create(quality=quality)
		    diski, created = Disk.objects.get_or_create(size=size, disk_type=disk_type, quality=qualityi)
		    disks.append(diski)
		obj.disks = disks
		return obj

	    def clean_filesystems(self, field, obj, data):

		filesystems = []
		cell = data[field.column_name]
		for e in cell.split(','):
		    e = e.strip().split('-')
		    if len(e) < 3:
		        continue
		    mount, size, quality = e
		    qualityi, created = StorageQuality.objects.get_or_create(quality=quality)
		    filesystemi, created = Filesystem.objects.get_or_create(mount=mount, size=size, quality=qualityi)
		    filesystems.append(filesystemi)
		obj.filesystems = filesystems
		return obj

**Comment by dg1980** [comment]
Dear @gthieleb,

thank you very much.
