### ISSUE TITLE
Mixins for Class Based Views

### ISSUE THREAD

**Issue by jangeador** [django-import-export/django-import-export#573]
Does anyone have example code for a mixin that would work outside the admin app. The mixins in this project are very tightly coupled to the admin app.

**Comment by ziima** [comment]
Looks like #692 is going in that direction.

**Comment by jangeador** [comment]
@ZuluPro the ExportView looks really good. If there is an import view that goes with it. I would love to see it.

**Comment by ZuluPro** [comment]
Haha, I do it step by step, and ImportView is the next step. ;)

**Comment by jangeador** [comment]
@ZuluPro did you ever get around to the ImportView?

**Comment by ZuluPro** [comment]
@jangeador I just begin to need it,
So I think I will implement it and make a PR soon.

**Comment by jangeador** [comment]
@ZuluPro I would be happy to help if there is anything I can do. Let me know.

**Comment by leonardodepaula** [comment]
Did someone ever implement ImportView?

**Comment by ZuluPro** [comment]
@leonardodepaula Yup, I did,
Just need commit that here.

**Comment by leonardodepaula** [comment]
If anyone else is looking for a solution, this one worked for me:

https://gist.github.com/nimasmi/12b3200c3e1399123da6
