### ISSUE TITLE
Provide a way to set the initial 'file format'

### ISSUE THREAD

**Issue by elbenfreund** [django-import-export/django-import-export#576]
As far as I understand there is no obvious way to set an initial value for the "file format" drop down.
It would be nice to have a way to provide one.

**Comment by bmihelac** [comment]
If there is only one choice it is selected. It would not be too hard to add method that would return initial data: 

https://github.com/django-import-export/django-import-export/blob/master/import_export/admin.py#L240

**Comment by elbenfreund** [comment]
Are you interest in a PR that would allow to set the initial data?

**Comment by bmihelac** [comment]
Yes, this seems nice to have

**Comment by shaggyfrog** [comment]
It's on our feature list at work, to pre-select the correct file format value based on the extension of the file uploaded. How did you solve it?
