### ISSUE TITLE
Line number: 1 - Cannot assign "(<Author: Mariam>, True)": "Book.author" must be a "Author" instance.

### ISSUE THREAD

**Issue by shaludhaka** [django-import-export/django-import-export#577]
Hi ,

I am constant getting below error:
Line number: 1 - Cannot assign "(<Author: Mariam>, True)": "Book.author" must be a "Author" instance.

**My admin.py**

from django.contrib import admin

# Register your models here.

from import_export import resources,fields
from import_export.admin import ImportExportModelAdmin
from import_export.widgets import ForeignKeyWidget,ManyToManyWidget
from import_export import resources
from .models import Book,Author

class AuthorWidget(ForeignKeyWidget):

    def __init__(self,model,field='pk',*args, **kwargs):
        self.model = model
        self.field = field

        # super(ForeignKeyWidgetWithCreation, self).__init__(*args, **kwargs)

    def clean(self, value,row=None,*args, **kwargs):
        val = super(ForeignKeyWidget, self).clean(value)
        if val:
            return self.model.objects.get_or_create(name=val)

class BookResource(resources.ModelResource):
    author = fields.Field(column_name='author', attribute='author', widget=AuthorWidget(Author, 'name'))
    # categories = fields.Field(column_name='categories', attribute='categories', widget=ManyToManyWidget(Category, 'name'))

    class Meta:
        model = Book

class BookAdmin(ImportExportModelAdmin):
    resource_class = BookResource

admin.site.register(Book, BookAdmin)
admin.site.register(Author)
# admin.site.register(Category)

**csv content**
id	name	author	author_email	imported	published	price
	rohan	Mariam	rohan@gmail.com	yes	02/09/16	123

Please suggest:

**Comment by gthieleb** [comment]
Should look like:

	def clean(self, value,row=None,*args, **kwargs):
	    val = super(ForeignKeyWidget, self).clean(value)
	 
	    """ Instead of get_or_create / get if you are sure that author already exists.
		Name is ambigous book name? author name? Suggest to change 'name' to 'author' """
	    author = Author.objects.get_or_create(name=val)
	    if val:
		return self.model.objects.get_or_create(name=author)
