### ISSUE TITLE
GenericForeignKey import/export

### ISSUE THREAD

**Issue by LouisAmon** [django-import-export/django-import-export#580]
How do you manage [Generic Relations](https://docs.djangoproject.com/en/1.10/ref/contrib/contenttypes/#generic-relations) using `django-import-export` ?

A GenericForeignKey combines two informations to generate a relation: a `content_type` and an `object_id`.

Since each `field` has his own logic in `django-import-export`, I was thinking of using `before_import_row` or `before_save_instance` to define the combination of the above two fields.

Has anyone tried building a `GenericForeignKeyWidget` ?

**Comment by igerko** [comment]
+1

**Comment by johnfraney** [comment]
I was able to import/export a generic foreign key using the [built-in ForeignKey widget](http://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.ForeignKeyWidget)

**Comment by johnfraney** [comment]
@msmaromi For a generic foreign key field called `address` on my model `Dude`, I just have this field in my `ModelResource`:

```
class DudeResource(resources.ModelResource):
    address = fields.Field(
        column_name='address',
        attribute='address',
        widget=widgets.ForeignKeyWidget(Address, 'name'))  # use a unique field

    class Meta:
        model = Dude
        fields = ['address']
```

So in the CSV file (or whatever format you're using), import/export will use whatever you specify in the `address` column like:

```
Address.objects.get(name=name)
```

**Comment by msmaromi** [comment]
If the specified address not found, can it creates new one?

**Comment by johnfraney** [comment]
@msmaromi It might be good to open a separate issue for that since it's different from the original question.

**Comment by francisjeanneau** [comment]
> @msmaromi For a generic foreign key field called `address` on my model `Dude`, I just have this field in my `ModelResource`:
> 
> ```
> class DudeResource(resources.ModelResource):
>     address = fields.Field(
>         column_name='address',
>         attribute='address',
>         widget=widgets.ForeignKeyWidget(Address, 'name'))  # use a unique field
> 
>     class Meta:
>         model = Dude
>         fields = ['address']
> ```
> So in the CSV file (or whatever format you're using), import/export will use whatever you specify in the `address` column like:
> 
> ```
> Address.objects.get(name=name)
> ```

This pretty much looks ike a direct relation to the `Address` model. How would you go about a field named `general` that can hold either an `Address` or a `Organization`?

**Comment by francisjeanneau** [comment]
Here is a clean and simple solution to resolve GenericForeignKey fields:

```python
class OrderLineResource(resources.ModelResource):
    item = fields.Field()
    def dehydrate_item(self, orderline):
            model = apps.get_model('store', orderline.content_type.model)
            return model.objects.get(id=orderline.object_id).name
    class Meta:
        model = OrderLine
```

Note:
- the `Orderline` model is the one that holds a GenericForeignKey field.
- `orderline.content_type.model` returns the model name.
- the `'store'` attribute in `apps.get_model('store', orderline.content_type.model)` is the name of the Django app in which the unknown model resides.
- `model = apps.get_model('store', orderline.content_type.model)` will assign the correct model to the `model` local variable, just as if you'd have done `from app.models import "unknown_model" as model`
- `return model.objects.get(id=orderline.object_id).name` returns the `name` attribute of the object refered to by the GenericForeignKey field.

**Comment by francisjeanneau** [comment]
Finally since I needed to find models from any app, I built a little function:

```python
def get_model_from_name(model_name):
    """
    Used to get a model instance when you only have its name.
    """
    app_labels = [a.label for a in apps.app_configs.values()]
    app_number = len(app_labels)
    for idx, app in enumerate(app_labels):
        try:
            model = apps.get_model(app, model_name)
            return model
        except LookupError as err:
            if idx == (app_number - 1):
                raise err
            continue
```
Hope this helps someone!

**Comment by wreeecks** [comment]
> @msmaromi For a generic foreign key field called `address` on my model `Dude`, I just have this field in my `ModelResource`:
> 
> ```
> class DudeResource(resources.ModelResource):
>     address = fields.Field(
>         column_name='address',
>         attribute='address',
>         widget=widgets.ForeignKeyWidget(Address, 'name'))  # use a unique field
> 
>     class Meta:
>         model = Dude
>         fields = ['address']
> ```
> So in the CSV file (or whatever format you're using), import/export will use whatever you specify in the `address` column like:
> 
> ```
> Address.objects.get(name=name)
> ```

Using `ForeignKeyWidget` to get the `GenericRelation` didn't work.

**Comment by W1773ND** [comment]
> Finally since I needed to find models from any app, I built a little function:
> 
> ```python
> def get_model_from_name(model_name):
>     """
>     Used to get a model instance when you only have its name.
>     """
>     app_labels = [a.label for a in apps.app_configs.values()]
>     app_number = len(app_labels)
>     for idx, app in enumerate(app_labels):
>         try:
>             model = apps.get_model(app, model_name)
>             return model
>         except LookupError as err:
>             if idx == (app_number - 1):
>                 raise err
>             continue
> ```
> 
> Hope this helps someone!

Django provide a convenient way to achieve this. Simple type:

```python
from django.contrib.contenttypes.models import ContentType

wanted_model = ContentType.objects.get(model=input.get('name_of_model').lower()).model_class()
```
Then  wanted_model is an instance of desired object!

Enjoy!
