### ISSUE TITLE
from_encoding does not work

### ISSUE THREAD

**Issue by jschneier** [django-import-export/django-import-export#586]
If I have a `latin-1` encoded file and set `latin-1` as `from_encoding` then `tmp_storage.read(input_format.get_read_mode())` fails for me because read mode is set to `rU` and auto-detects `utf-8` as the encoding.

Switching text format's read mode to be `rb` (i.e. eliminating the difference between them entirely) fixes this issue. It makes sense to me, then we can just let the `force_text` proceed on all non-binary inputs.

**Comment by bmihelac** [comment]
Hello @jschneier, can you add a failing test for this?
