### ISSUE TITLE
MediaStorage setting now using the correct class

### ISSUE THREAD

**Issue by marksweb** [django-import-export/django-import-export#589]
I've defined the following in my settings;

`IMPORT_EXPORT_TMP_STORAGE_CLASS = 'import_export.tmp_storages.MediaStorage'`

But noticed that there were no files being saved to my S3 bucket. To test it I've added breakpoints to the save & read methods on the class but neither were hit during an import.

Am I doing something stupid here? The docs suggest that is the correct setting name, and the usage of the setting requires an import path & a classname in the value.

Versions;
Python 2.6
Django==1.10.5
django-import-export==0.4.5
tablib==0.11.2

**Comment by martiuripariu** [comment]
Hi Marksweb, I'm having the same problem. Were you able to find a solution? Thank you, Good Luck!
