### ISSUE TITLE
Exporting via admin action fails if actions_on_top and actions_on_bottom available

### ISSUE THREAD

**Issue by chrisill** [django-import-export/django-import-export#591]
If both actions_on_top and actions_on_bottom are available to users on the admin page, selecting the export action and file-format on the upper side ends in an error message "You must select an export format."
This does not happen if using the action on the bottom of the page.

POST is passing both results (the selected file_format from the upper action and the blank onefrom the lower action in the same key to the request. Looks like the last one (lower select with empty value) is considered only.

**Comment by psychok7** [comment]
I can confirm this BUG using `Django 1.10`. Any ideas on how to solve this?

**Comment by chrisill** [comment]
Most easy fix: Just set "actions_on_top" and "actions_on_buttom" one to True and the other to False.

**Comment by I-NOZex** [comment]
still unsolved...

**Comment by Mustafa-Abu-Ghazy** [comment]
I can confirm this BUG still unsolved... using  `Django==3.2.7` and  `django-import-export==2.7.1`
I have fixed it to allow use of both of `actions_on_top=True` and `actions_on_bottom=True` at the same time. 
by overwriting the import_export/action_formats.js to be
```js
(function ($) {
    $(document).ready(function () {
        var $actionsSelect, $formatsElement;
        $actionsSelect = $('.actions select[name="action"]');
        $formatsElement = $('.actions select[name="file_format"]');
        if ($('body').hasClass('grp-change-list')) {
            // using grappelli
            $ShowElementToShow = $formatsElement;
        } else {
            // using default admin
            $formatsElementToShow = $formatsElement.parent();
        }
        for (let i = 0; i < $actionsSelect.length; i++) {
            $actionsSelect.eq(i).change(function () {
                if ($(this).val() === 'export_admin_action') {
                    $formatsElementToShow.eq(i).show();
                } else {
                    $formatsElementToShow.eq(i).hide();
                }
            });
            $actionsSelect.eq(i).change();

            $formatsElement.eq(i).change(function () {
                for (let j = 0; j < $formatsElement.length; j++) {
                    if ($formatsElement.eq(j).val() != $(this).val()) {
                        $formatsElement.eq(j).val($(this).val());
                    }
                }
            });
        }
    });
})(django.jQuery);
```

**Comment by matthewhegarty** [comment]
To reproduce in example app:

1.  Add     `actions_on_top = True`,    `actions_on_bottom = True` to `CategoryAdmin`
2.  Click on 'Categories'
3. Select a category to export
4. Click export on top menu, and select format.
5. Click Go

![2022-02-27_20-25](https://user-images.githubusercontent.com/6249838/155898612-877d2712-8160-497d-b050-84686a23a2d7.png)
