### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by beruic** [django-import-export/django-import-export#592]
When is the next release going to happen?
I am eagerly awaiting the new duration field, and i can't really see what is holding it back.

**Comment by beruic** [comment]
Is the changelog automatically generated, or should I write it in order to speed things up?

**Comment by beruic** [comment]
Changelog updated in PR #593

**Comment by beruic** [comment]
I can see now that I also need the clean fix for m2m widgets.

**Comment by SalahAdDin** [comment]
:+1:
