### ISSUE TITLE
before_import... modify dataset to be used in import_row ??

### ISSUE THREAD

**Issue by cometsong** [django-import-export/django-import-export#597]
I've successfully overridden the `before_import` method to change the dataset by generating values for a specific field in the added logic.  (Successful because I see in my debug/print statements that the fields have values in the `Dataset.Row` `OrderedDict` instances.)

However, the modified rows of that `dataset` are *not* passed to the `before_import_row` method, and thus do *not* show up in the Result that is shown to the user in the *Confirm* screen.

*Background:*  I've searched through the list of issues and found a few pointers in different directions...
- I've tried using with and without a `return super()` at the end of the override, as I saw one of the issue comments using ([#319](319#issuecomment-138723810)).
- the `import_obj`, the `get_instance` have also been recommended, but those are more field-specific. e.g. [#373](373)
- several `before_import` examples [#174](174), [#299](299) that make it seem `before_import` *does* modify the dataset successfully.
- ....

I chose that overall `before_import` because the row values need to generated in session batches, based on the complete number of rows being imported.

Should I do the modifying the dataset in another way? another method?  Ideas?

*Installed versions:*  
- Python 3.6.1
- Django 1.11.1
- django-import-export 0.5.2.dev0
- tablib 0.11.4

My before_import code (FYI the field being modified is named jaxid"):
```python
    def before_import(self, dataset, using_transactions=True, dry_run=False, **kwargs):
        """ Overridden to generate new JAXid values for each row to be imported. """
        num_rows = dataset.height
        print('num_rows in dataset: {}'.format(num_rows))

        #TODO: implement kwargs.prefix for other types
        id_prefix = kwargs.get('prefix', 'J')
        jid = JAXidGenerate(prefix=id_prefix)
        new_jaxids = jid.generate_new_ids(num_rows)

        jaxid_col_num = dataset.headers.index('jaxid')
        dataset_jaxids = set([row[jaxid_col_num]
                              for row in dataset
                              if row[jaxid_col_num] != ''])
        print("current_ids used by incoming dataset: {}".format(dataset_jaxids)) # shows all values previously defined to be used in import

        for row in dataset.dict:
            # print('dataset first: {}'.format(row)) #shows the present value or lack thereof
            if row['jaxid'] == '':
                row['jaxid'] = self.assign_new_id(new_jaxids, dataset_jaxids)
            print('dataset final: {}'.format(row)) #shows the resulting value assigned to the field

        # tried with this present and commented out:
        return super(self.__class__, self).before_import(dataset, using_transactions, dry_run, **kwargs)
```

**Comment by pszklanko** [comment]
Things you want to modify (touples (header, value) in dataset) are immutable. Returning value won't help, because it is not then assigned to anything.

Generally to manipulate dataset I would recommend using methods from [tablib API ref](http://docs.python-tablib.org/en/latest/api/#dataset-object).  At least it works for me. You can append column with: `append_col(col, header=None)`

**Comment by cometsong** [comment]
Thanks @pszklanko.
The column already exists, so there's no need to `append` it unless I were to remove it first.  As that would remove it from all rows where a value exists, it's not in the user's best interest. :/

I'm looking through for a way to modify each row's value using that API... do you place those method calls within the `before_import` hook?  or somewhere else?

**Comment by pszklanko** [comment]
How about replacing rows you modify? You could change the data in a single row, delete the old one with `del dataset[index]` and then `append` or `insert` modified one.

Yes, I did it all in `before_import`.

**Comment by cometsong** [comment]
Ok, i got it working on my third try...

For reference (if anyone else finds this...) creating an new dataset with the modified and wholly replacing the existing dataset (`dataset = new_dataset`) does **not** work.

Deleting the row being modified and then `dataset.append`ing it as a new row to the end skips over some rows in the intitial dataset (possibly in my looping technique, but have not tested enough others to see if they'd work).

Using `del[index]` and `dataset.insert(index, new_row)` _**does**_ work!

Thankls @pszklanko for your help!


functioning code below...
using:

    def replace_row(row_index, row_dict):
       """'pop' for specific index number within dataset, followed by insertion of new 'row' values"""
       del dataset[row_index]
       dataset.insert(row_index, row_dict.values())
then later:

    for row_index, row_values in enumerate(dataset):
        row = dict(zip(dataset.headers, row_values))
        if not row['jaxid']:
            row['jaxid'] = new_jaxids.next()
        replace_row(row_index, row)

**Comment by CSChen0905** [comment]
installed version 
- Django==4.2
- django-import-export==4.3.7

I got the same problem.
First, I modified dataset in `before_import,` and dataset modified in the before_import function. But it does not affect the original dataset. Also try the @cometsong method, but not working.
I finally  did it in `import_data.`  I created a new dataset and return the new dataset.
```python
def import_data(
        self,
        dataset,
        dry_run=False,
        raise_errors=False,
        use_transactions=None,
        collect_failed_rows=False,
        **kwargs,
    ): 

#create a new_dataset and add data to it
new_dataset = tablib.Dataset()


#return new_dataset
return super().import_data(
                new_dataset,
                dry_run,
                raise_errors,
                use_transactions,
                collect_failed_rows,
                **kwargs,
            )
```
