### ISSUE TITLE
Is it possible to import/export various related models all at once?

### ISSUE THREAD

**Issue by jordiecometrica** [django-import-export/django-import-export#599]
I can't get a straight answer on this from reading the documentation and source code. Suppose I want to export a publisher, along with all books that they have published, and all of the authors of those books. I also want to do the reverse and import all of these, all at once. Naturally it's a m2m between books and authors, but let's say it's just a foreign key from book to publisher.

Is this something that can be done? If I specify related fields on the publisher, they become read-only. I also can't see how a format like CSV could handle multiple types of rows or "denormalised" data for the m2m case.

I'd like to add: this isn't a request to do work for me. Github issues are weird. You seem to be using this as a forum rather than as a way to track bugs, so that's what I'm doing too with this "issue". If what I want to do can't be done, that's fine, I'll figure it out on my own and maybe offer a PR later.

**Comment by chgad** [comment]
I ran into the same issue ant thinks it's very important to be able to import related tables. I don't think CSV is capable of representing the relations correctly - but Jason and YAML (etc.) can do it so it might be nice to include such a feature.

So a mighty up for this issue !

**Comment by int-ua** [comment]
You'll have to write to own Widgets. It's not trivial, but doable. Check included widgets for some examples and note that you can use `row['column name']` along with `value` in the widget column. I even got to third level of relations now by using widgets inside widgets (initiating subwidgets in main widgets' init)

**Comment by mykljohn** [comment]
@int-ua Can you post a sample of that?  I'm doing the same thing...the main data is student info, but the related is class registration.

**Comment by int-ua** [comment]
class SomeWidget(ForeignKeyWidget):
        def __init__(
                self,
                field='id',
                *args, **kwargs):
            self.field = field
            self.other_widget = OtherWidget()

        def clean(self, value, row):
            something = self.other_widget.clean(
                    row['column name'], row)
            ...

**Comment by HqShiblu** [comment]
`asdasda` SADFCSDV### ADF

**Comment by rez0n** [comment]
@int-ua  @mykljohn Hey!
Can you please share your experience with importing two Excell sheets with autoincrementing id and relating it using a special column in the sheets with internal id?

I am not sure what OtherWidget needs to do.

```
class SomeWidget(ForeignKeyWidget):
    def __init__(
            self,
            field='id',
            *args, **kwargs):
        self.field = field
        self.other_widget = OtherWidget()

    def clean(self, value, row):
        something = self.other_widget.clean(
                row['column name'], row)
                ```

**Comment by int-ua** [comment]
I don't remember exactly without looking at the code but I think the `OtherWidget.clean` should return the instance that id is referencing.
