### ISSUE TITLE
Fields without blank=True that are blank should error

### ISSUE THREAD

**Issue by jschneier** [django-import-export/django-import-export#601]
If I have a Char or Text field that _does not_ have `blank=True` (i.e. I have the default case) then currently this package will just silently do the import which can break everything. Since Django encourages not using `null=True` in `CharField` and `TextField` this seems like an _extremely_ common situation to be in.

Not sure how this issue has never been raised before.

**Comment by jschneier** [comment]
It seems that we largely rely on the database integrity checks to handle errors for us (aside from the `DateWidget`?). We should be using Django's builtin in validation logic instead of barfing out database integrity stack traces that end users won't be able to understand.

**Comment by cometsong** [comment]
I ran across this same type of event, and added in a clean call to the `save` override I made on many models in my apps.

```
def save(self, **otherstuff):
    self.full_clean()
    super().save(**otherstuff)
```
(replacing "otherstuff" with the actual args involved in this).
ref:  https://docs.djangoproject.com/en/1.11/ref/models/instances/#saving-objects


The full_clean method does all the model field definition's checks, as the db itself does nothing at all besides table relationships.
ref: https://docs.djangoproject.com/en/1.11/ref/models/instances/#django.db.models.Model.full_clean

HTH

**Comment by jschneier** [comment]
This library should likely do that instead of having to override your models
