### ISSUE TITLE
django jet incompatibility

### ISSUE THREAD

**Issue by benjaminderei** [django-import-export/django-import-export#618]
When on import or export view of django-import-export and using Django Jet admin the select input have a buggy behaviour (on click the console say: `TypeError: django.jQuery is not a function`)

**Comment by luk156** [comment]
any news?

**Comment by vrbarros** [comment]
Hello, I'm having the same problem. Any solution found?

**Comment by eugeniol** [comment]
Hey guys, anyone has a workaround to solve this?

**Comment by eugeniol** [comment]
Quick workaround found 
Create a template in yourt project with 2 libs missing


_templates/admin/import_export/base.html_
```
{% extends "admin/import_export/base.html" %}
{% load static %}

{% block extrahead %}{{ block.super }}
    <script type="text/javascript" src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
{% endblock %}

 ```

**Comment by manelclos** [comment]
django.jQuery is expected to be there, as suggested, import jquery manually then:

```
django.jQuery = jQuery;
```

**Comment by yadavbraham** [comment]
> Quick workaround found
> Create a template in yourt project with 2 libs missing
> 
> _templates/admin/import_export/base.html_
> 
> ```
> {% extends "admin/import_export/base.html" %}
> {% load static %}
> 
> {% block extrahead %}{{ block.super }}
>     <script type="text/javascript" src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script>
>     <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
> {% endblock %}
> ```

Worked for me

**Comment by fergyfresh** [comment]
What directory did you guys put this in? Or did you have to patch the code in a fork?

**Comment by omarsalazar** [comment]
This worked for me
https://github.com/geex-arts/django-jet/issues/284

**Comment by AlBartash** [comment]
> Quick workaround found
> Create a template in yourt project with 2 libs missing
> 
> _templates/admin/import_export/base.html_
> 
> ```
> {% extends "admin/import_export/base.html" %}
> {% load static %}
> 
> {% block extrahead %}{{ block.super }}
>     <script type="text/javascript" src="{% static "admin/js/vendor/jquery/jquery.js" %}"></script>
>     <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
> {% endblock %}
> ```

This one fixed 'django.jQuery' bug for django-jet on my side. Thanks.
