### ISSUE TITLE
The value of DateTimeField which enables 'auto_now' option can't be set from imported data

### ISSUE THREAD

**Issue by userlocalhost** [django-import-export/django-import-export#642]
Thank you for providing this great software!
I found a problem about import processing, so I report it.

## Abstract
After import data, the current time is always set to the DateTimeField which is enabled 'auto_now'. On the other hands, DataTimeField which is disabled 'auto_now' could be set the time which is specified in the imported data, as following.

### Definition of Model
```python
class Hoge(models.Model):
    datetime1 = models.DateTimeField(auto_now=False)
    datetime2 = models.DateTimeField(auto_now=True)
```
### Definition of ModelResource
```python
class HogeResource(ModelResource):
    class Meta:
        model = Hoge
        fields = ('id', 'datetime1', 'datetime2')
```
### Result of reproduction
```
$ python manage.py shell
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import tablib
>>> from import_export import resources
>>> from hoge.admin import HogeResource
>>> from hoge.models import Hoge
>>> 
>>> raw_data = {'id': 1, 'datetime1': '2017-01-01 00:00:00', 'datetime2': '2017-01-01 00:00:00'}
>>> headers = ['id', 'datetime1', 'datetime2']
>>> 
>>> # clear data before testing
>>> Hoge.objects.all().delete()
(1, {u'hoge.Hoge': 1})
>>> 
>>> resource = HogeResource()
>>> dataset = tablib.Dataset([raw_data[x] for x in headers], headers=headers)
>>> result = resource.import_data(dataset)
>>> 
>>> obj = Hoge.objects.get(id=1)
>>> obj.datetime1
datetime.datetime(2017, 1, 1, 0, 0, tzinfo=<UTC>)
>>> obj.datetime2
datetime.datetime(2017, 8, 1, 2, 51, 53, 964519, tzinfo=<UTC>)
>>>
```
## Environment
I checked this problem was occur in the following environments.

|Relevant software|Version|
|:------------------|:-------:|
|django-import-export|0.5.2.dev0|
|django|1.11.3|
|tablib|0.11.5|
|Python|2.7.12, 3.5.2|

**Comment by rapkyt** [comment]
Hi

**auto_now** attribute in DateTimeField (which default value is False) enables Django to populate that field with the datetime at the moment of save the instance in the database.

See [this](https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.DateField.auto_now)
> Note that the current date is always used; it’s not just a default value that you can override.
> As currently implemented, setting auto_now or auto_now_add to True will cause the field to have editable=False
