### ISSUE TITLE
Join to jazzband

### ISSUE THREAD

**Issue by ad-m** [django-import-export/django-import-export#649]
Hello,

I suggest move repository to [jazzband](https://jazzband.co/) organization.  This repository looks slightly deserted. It has proposals for changes that are simple, have votes of support, but have not been considered.

>  Jazzband is a cooperative experiment to reduce the stress of maintaining Open Source software alone.
> The goal of the Jazzband is to offer relief by sharing responsibility for open source work with other like-minded people. It offers maintainers and contributors the ability to play in the same band instead of being forced into “artist” and “audience” roles by the tools GitHub provides

CC: @jezdez

**Comment by shaggyfrog** [comment]
As maintainers sometimes our lives are busy (including work), and we don't have the time to go through PRs. Yes, we are behind right now.

I just went through about 10 that change source code, and only 3 of them had matching tests. So most of them aren't ready for merging anyway.

Still, if anyone would like to join as a maintainer, and help us with this backlog, please let @bmihelac know.

Otherwise, as always, you are free to fork this library here on GitHub, and then you will be able to reference your fork as a dependency in your project, e.g. your requirements.txt file.

**Comment by bmihelac** [comment]
@ad-m thanks for taking time to write this suggestion. It is worth to think over this idea and to see what should be done before joining Jazzband if they would want us in their band :)

Regardless few thing that should be done with django-import-export in near future:

* there are lot of issues that are indeed support requests and probably it would be better to direct them to stackoverflow in issue template
* lot of pull requests have not tests at all, bringing danger of breaking things - we should make it clear in issue template what is needed for PR to be considered
* we should add code of conduct

As @shaggyfrog said we would love to welcome new maintainers that would help us, so if anyone would love to help, ping us :)

**Comment by mgrdcm** [comment]
@bmihelac I'd certainly like to help you and @shaggyfrog out with maintaining `django-import-export`.  It's very useful, implemented very well, and I believe very valuable to the Django community.

**Comment by bmihelac** [comment]
@mgrdcm thanks:) I send you an email.

**Comment by wasabigeek** [comment]
@bmihelac and other maintainers - thank you! Very useful package.

Are there any plans for updating the Pypi version? Or should we keep using the development version going forward?

**Comment by bmihelac** [comment]
@wasabigeek, published:

 https://pypi.python.org/pypi/django-import-export/0.6.0

**Comment by jezdez** [comment]
Hi all, what's the latest on this?

**Comment by bmihelac** [comment]
Hi @jezdez and thanks for continuing this conversation. Since this issue was opened team got new strengths and I would like to hear their thoughts on this matter. Jazzband is for sure a great community and concept.

**Comment by jezdez** [comment]
@bmihelac Understood, no worries, I'm glad things are better for the project!
