### ISSUE TITLE
Differentiate between display fields and fields to import

### ISSUE THREAD

**Issue by jeffreybrowning** [django-import-export/django-import-export#651]
In a resource can we get a display_fields that controls what fields to show to users, and a fields, which is used by the code. 

**Explanation:**
I have a number of non-engineers using the import page in django admin that get confused by the text "This importer will import the following fields". I have included some extra fields to take care of creating other models in my resources, which are then processed and become "real" model fields. 

Imagine a user's avatar image. In the User model this is a fk to a File model. It's better for my non-engineer brethren to put a url in for the `avatar` field in the import csv, and then have that intuited into a File. So I'd like to name the field for that avatar value `avatar_url`, not `avatar`. I can do that: 

```    
    avatar_url = fields.Field()
    class Meta:
        model = User
        fields = ['avatar_url']
```

However, the import doesn't accept a value in the row for `avatar` after the url is processed if `avatar` is not present in the fields. This means I need to add `avatar` to the fields. But then my admins see `avatar` as an option for a field and get confused.

**Comment by lilaLeon** [comment]
If you change 
`avatar_url = fields.Field()`
to
`avatar = fields.Field(attribute="avatar", column_name="avatar_url")`

your users should be shown the column_name as displayvalue. You would have to change the header in your csv aswell obviously.

Hope it helps!
