### ISSUE TITLE
hi i have a problem import xlsx to a model with ForeignKey could you help me?

### ISSUE THREAD

**Issue by juliocebrito** [django-import-export/django-import-export#654]
models.py

class Estacion(models.Model):
    nombre = models.CharField(max_length=255, unique=True)
    regional = models.CharField(max_length=255, choices=choices.REGIONAL_CHOICES)
    ciudad = models.CharField(max_length=255, choices=choices.CIUDAD_CHOICES)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('creado',)
        verbose_name = "estacion"
        verbose_name_plural = "estaciones"

    def __str__(self):
        return self.nombre

class Actividad(models.Model):
    wp = models.CharField(max_length=255, unique=True)
    id_notificacion_noc = models.CharField(max_length=255, unique=True)
    estacion = models.ForeignKey(Estacion, blank=True, null=True, related_name='actividades')
    banda = models.CharField(max_length=255)
    tecnologia = models.CharField(max_length=255)
    valor_wp_eur = models.CharField(max_length=255)
    proyecto = models.CharField(max_length=255)
    escenario = models.CharField(max_length=255)
    tipo_trabajo = models.CharField(max_length=255)
    fecha_ingreso_onair = models.DateField()
    regional = models.CharField(max_length=255)
    ciudad = models.CharField(max_length=255)
    realtifinish = models.DateField()
    fecha_integracion = models.DateField()
    tipo_gap = models.CharField(max_length=255)
    tx_df_confirmado = models.CharField(max_length=255)
    notificaciones = models.CharField(max_length=255)
    estado_noc = models.CharField(max_length=255)
    subestado_noc = models.CharField(max_length=255)
    degradacion = models.CharField(max_length=255)
    fecha_asignacion_npo = models.DateField()
    fecha_primera_respuesta_npo = models.DateField()
    fecha_ultima_respuesta_npo = models.DateField()
    fecha_concepto_npo = models.DateField()
    concepto_npo = models.TextField(blank=True, null=True)
    responsable_npo = models.CharField(max_length=255)
    celular_npo = models.CharField(max_length=255)
    responsable_actual =models.CharField(max_length=255)
    impacto_degradacion = models.CharField(max_length=255)
    requiere_visita = models.CharField(max_length=255)
    fecha_fc_visita = models.DateField()
    id_siteaccess = models.CharField(max_length=255, unique=True)
    precheck = models.CharField(max_length=255)
    visita_supervisor = models.CharField(max_length=255)
    celular_supervisor = models.CharField(max_length=255)
    integrador = models.CharField(max_length=255)
    celular_integrador = models.CharField(max_length=255)
    concepto_ni = models.TextField(blank=True, null=True)
    fecha_concepto_ni = models.DateField()
    tipo_intervencion = models.CharField(max_length=255)
    requiere_hw = models.CharField(max_length=255)
    cantidad_hw = models.CharField(max_length=255)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-creado',)
        verbose_name = "actividad"
        verbose_name_plural = "actividades"

    def __str__(self):
        return self.wp

admin.py

class ActividadResource(resources.ModelResource):

    class Meta:
        model = Actividad
        exclude = ( 'creado', 'actualizado', )

@admin.register(Actividad)
class ActividadAdmin(ImportExportModelAdmin):
    resource_class = ActividadResource

error is --->Line number: 1 - Column 'estacion': invalid literal for int() with base 10:

Errors

Line number: 1 - Column 'estacion': invalid literal for int() with base 10: 'ANT.Alambra'
None, 12709851, None, ANT.Alambra, 850Mhz, None, 828.931518503, EXP_3G, CE, Channel Element, None, Nor Occidente, Antioquia, 2017-08-16 00:00:00, 2017-08-16 00:00:00, GAP On Air, Viable Integracion, NOTIFICADO NOC, Escalado a Implementacion, Degradacion KPI, Para los KPIS Average number of simultaneous HSDPA users (RNC_645c), Max simult HSUPA users (RNC_1687ª), Average number of simultaneous HSUPA users (RNC_1036b) sectores Y y Z continua disminución de usuarios después de la actividad los demás KPIS van retomando comportamiento., 2017-09-02 00:00:00, 2017-09-04 00:00:00, 2017-09-05 00:00:00, 2017-09-04 00:00:00, Enviar el sitio a seguimiento porque el comportamiento de los kPIs mencionados, desde el 4 de septiembre, vuelven a los valores cercanos a los  históricos. , Jairo Polo, None, NI, Leve, NO, 2017-09-05 00:00:00, None, None, None, None, Juan Gabriel , 3124991628, Cambio de parámetros, None, Local, None, None
Traceback (most recent call last):
File "/Users/juliocebrito/Virtualenv/trouble-shooting/lib/python2.7/site-packages/import_export/resources.py", line 452, in import_row
self.import_obj(instance, row, dry_run)
File "/Users/juliocebrito/Virtualenv/trouble-shooting/lib/python2.7/site-packages/import_export/resources.py", line 331, in import_obj
self.import_field(field, obj, data)
File "/Users/juliocebrito/Virtualenv/trouble-shooting/lib/python2.7/site-packages/import_export/resources.py", line 321, in import_field
field.save(obj, data)
File "/Users/juliocebrito/Virtualenv/trouble-shooting/lib/python2.7/site-packages/import_export/fields.py", line 112, in save
setattr(obj, attrs[-1], self.clean(data))
File "/Users/juliocebrito/Virtualenv/trouble-shooting/lib/python2.7/site-packages/import_export/fields.py", line 68, in clean
raise ValueError("Column '%s': %s" % (self.column_name, e))
ValueError: Column 'estacion': invalid literal for int() with base 10: 'ANT.Alambra'

**Comment by lilaLeon** [comment]
the field estacion expects an id to set the foreignkey not the name of the estacion. You could try changing
`nombre = models.CharField(max_length=255, unique=True)`
to 
`nombre = models.CharField(max_length=255, unique=True, pk=True)`

**Comment by gthieleb** [comment]
Please read the [doc for pasting code in github first!](https://guides.github.com/features/mastering-markdown/)

For solving your issue use a ForeignKey Widget as described [here](https://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.ForeignKeyWidget) and add 2nd param `nombre`.
