### ISSUE TITLE
Problem import excel to my app on google appengine

### ISSUE THREAD

**Issue by juliocebrito** [django-import-export/django-import-export#658]
error when i use TempFolderStorage:

Exception Value: | Only tempfile.TemporaryFile is available for use

/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/tempfile.py in PlaceHolder, line 45

error when i use CacheStorage, local works but in appengine:
when file is 100k works,
when file is 500k appengine deadline is 60 seconds so error:
Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.

**Comment by shaggyfrog** [comment]
There's not enough information here to understand what the problem is.

**Comment by interpegasus** [comment]
Likely the issue is related with the fact that file uploads in Google Cloud should be handled according to:
https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
