### ISSUE TITLE
Support for Django2

### ISSUE THREAD

**Issue by elcolie** [django-import-export/django-import-export#664]
```bash
  File "/Users/el/.pyenv/versions/soken3.7/lib/python3.7/site-packages/import_export/admin.py", line 16, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```
That module has been renamed to `django.urls`

**Reference:**
https://stackoverflow.com/questions/43139081/importerror-no-module-named-django-core-urlresolvers

**Comment by ppsammartino** [comment]
Is this project being maintained at the moment? Haven't seen any official support for Django 2.0 since it's been launched.

**Comment by ouahibelhanchi** [comment]
As a workaround, we can use the following:

```python
try:
    from django.core.urlresolvers import reverse
except ImportError:
    from django.urls import reverse
```

**Comment by manelclos** [comment]
Will update for Django 2.0 in short: https://github.com/django-import-export/django-import-export/pulls?q=is%3Apr+is%3Aopen+label%3Adjango-2.0

**Comment by elcolie** [comment]
@manelclos Good to know. Thanks. Looking forward to see `django-import-export` in action.

**Comment by manelclos** [comment]
Django 2 support PRs are now merged, please open a new issue if more problems are found.

**Comment by elcolie** [comment]
Okay
