### ISSUE TITLE
How to display file name on import confirm screen?

### ISSUE THREAD

**Issue by sixsixtrample** [django-import-export/django-import-export#671]
I need to display the name of the file being imported on the confirmation screen. I can't see how to do this with result or existing variables. Do I need to override something?

Thank you for your help.

**Comment by cometsong** [comment]
There is a `request.POST` variable `'original_file_name'` which stores the name of the uploaded file.  Hope that helps.

**Comment by sixsixtrample** [comment]
This was exactly what I needed.

Should have been closed 12/2017!
