### ISSUE TITLE
Import Qualified and Delimited by - Values Structure

### ISSUE THREAD

**Issue by steveo-ct** [django-import-export/django-import-export#673]
Hello - When trying to import a csv with the following value set, the import displays and ultimately inserts blank / null values to the database:
id, person, email
, john, john@example.com
, sue, sue@example.com

This would display on the import validation screen as:
id, person, email
1, , 
2, , 

removing the space after the comma's fixes the issue:
id,person,email
,john,john@example.com
,sue,sue@example.com

Import validation screen displays correctly.

question(s):
1. Can this functionality be fixed? so the delimiter is a comma regardless if there's a space next to it?
2. Can a custom text qualifier be assigned? ex: <|john|>. qualifier would be <||>
3. can a custom delimiter be assigned? ex. johnþsueþemail delimiter would be þ or thorn. value could be assigned by hex value or ascii code or the value itself.

Django 1.11.6
Import-export 0.5.1
python 3.6.2

**Comment by nazmulhasan85** [comment]
@steveo-ct  do you have any customization in resource class? or you can share your code can understand easily.

**Comment by manelclos** [comment]
Hi @steveo-ct, the input data should be correct, otherwise you can create your own format subclassing an existing one, CSV in your case, and do the data cleaning there.
