### ISSUE TITLE
Drop support for all versions of Django prior to 1.11

### ISSUE THREAD

**Issue by bmihelac** [django-import-export/django-import-export#681]
As stated on [Django 2.0 release notes](https://docs.djangoproject.com/en/dev/releases/2.0/#third-party-library-support-for-older-version-of-django) I propose this change in next major/breaking version.

> Following the release of Django 2.0, we suggest that third-party app authors drop support for all versions of Django prior to 1.11. At that time, you should be able to run your package’s tests using python -Wd so that deprecation warnings do appear. After making the deprecation warning fixes, your app should be compatible with Django 2.0.

**Comment by mgrdcm** [comment]
How about doing it gradually by dropping support for <1.8 first (which is an LTS release) as the next breaking change and then dropping <1.11 in the next one?

**Comment by shaggyfrog** [comment]
That would mean two major releases in quick succession (if we are moving to semver), which is unusual, and so I think it makes more sense to drop support as Bojan (and the Django team) suggest.

Users of Django <=1.10 can always grab an older version of our lib.

T

**Comment by mgrdcm** [comment]
For some reason I thought 2.0 wasn't going to be released until July.  I see now that luckily I'm wrong (it's scheduled for December 2017 if anyone else is wondering :).

I think it's weird for Django to recommend to (and for apps to) drop support for the 1.8 LTS since it'll be supported by Django until April 2018.

**Comment by mgrdcm** [comment]
Also a little looking at the `django-import-export` code, I see around a dozen places where conditionals and workarounds could go away by not supporting `<1.8` but other than #680 I haven't seen anything that would be saved by only supporting `>=1.11`.

**Comment by bmihelac** [comment]
make sense to support 1.8 LTS until it is officialy supported (at least april, 2018 according to django docs)

**Comment by mgrdcm** [comment]
I created https://github.com/django-import-export/django-import-export/pull/685 as a start to removing support for `Django<1.8`.
