### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by mgrdcm** [django-import-export/django-import-export#687]
This'll be the adoption of Semantic Versioning and a major/breaking release.  Let's use this ticket to determine which breaking changes we want to wrap into `1.0.0` and coordinate on how to release it.

Known tickets requiring a major/breaking semver release:
- [x] #685:  Require `Django>=1.8`

**Comment by mgrdcm** [comment]
I think we should also drop support for Python 3.3 in `1.0.0`, since it has reached EOL: https://docs.python.org/devguide/index.html#index-6

The Django versions we support that support Python 3.3 also support newer versions of Python that aren't EOL'd.

**Comment by bmihelac** [comment]
> I think we should also drop support for Python 3.3 in 1.0.0, since it has reached EOL: https://docs.python.org/devguide/index.html#index-6

agreed

**Comment by mgrdcm** [comment]
Now that https://github.com/django-import-export/django-import-export/tree/0.6.1 has been tagged and released, should we go ahead with the plan to make `1.0.0` the next release?  I just branched and created https://github.com/django-import-export/django-import-export/tree/0.6.x we can use if there are any big bug fixes we need to do before `1.0.0` is released.  So I think we can go ahead with #685 and such, how does that sound @bmihelac?

**Comment by bmihelac** [comment]
I would really like to merge this before moving forward:

https://github.com/django-import-export/django-import-export/pull/690/commits/77323e744c50cb2aa0210d853b8f6b5d323ad674

This patch looks fine by me, but would extra eyes :)

**Comment by mgrdcm** [comment]
Ahh, OK!  I just removed the `0.6.x` branch, and we can redo that after #690 gets merged in and `0.6.2` gets released.

**Comment by manelclos** [comment]
Hi! What about moving all settings to dictionary?
```
IMPORT_EXPORT_SETTINGS = {
    IMPORT_EXPORT_USE_TRANSACTIONS: True
    ...
}
```

Best doing this before 1.0.0 :)

**Comment by bmihelac** [comment]
@manelclos we have only 3 settings right (https://django-import-export.readthedocs.io/en/latest/installation.html#settings)? Personally I would prefer not to complicate about that....

**Comment by manelclos** [comment]
Ok, it was just a suggestion, as some people in PRs want to add options here and there. It would also mean maintaining both for some time...

**Comment by bmihelac** [comment]
Hey all! Is there anything that should be done before 1.0.0 release?

**Comment by manelclos** [comment]
I use this project on several production systems. It is actively maintained. Supports latest Django versions. Has a good test coverage. Time to have a 1.0 release :)

**Comment by manelclos** [comment]
What are the priorities from now on?

**Comment by bmihelac** [comment]
There are lot of pull requests that could be incorporated (I think) and I waited until 1.0 release. 

Currently I use zest.releaser to release new versions - it work great, but I would like to autmate updating changelog.  Creating release description if possible would be awesome. Something like [this](https://github.com/jazzband/django-push-notifications/releases).

Also what are best practices to allow team to upload new releases to pypi?
