### ISSUE TITLE
Import : how to add a select form for a foreignkey

### ISSUE THREAD

**Issue by mwolff44** [django-import-export/django-import-export#69]
Hello,

I would like to import a model where i ahem a foreign key. All imported rows will be linked to one entry of this foreign key. 
I can add a column with the same number for each row, but i prefer to add a select box in the import form.
How can i do that ?

Thx

**Comment by jleclanche** [comment]
@bmihelac I'm going to be working on this over the next couple of days. Do you have suggestions/specific ideas as to how the configuration should look like?

**Comment by jleclanche** [comment]
@bmihelac What do you think of https://github.com/jleclanche/django-import-export/commit/124b75dd6a9164a9542fd2ea94068aed88549429?

**Comment by bmihelac** [comment]
@jleclanche thanks for contribution, I will take a look soon.

**Comment by jleclanche** [comment]
@bmihelac I filed a PR for this. I'm sure it'll need some improvements, let me know :)

**Comment by JarnoRFB** [comment]
Hello,

I'm right now working on a project that requires exactly the same feature, so I would like to ask if there has been progress on this topic.

If not, overriding the default behaviour of the ImportExportMixin would be a valid option for me too, though I'm somewhat stuck on how to do it. I have posted a question on [Stackoverflow](http://stackoverflow.com/q/36918074/4873972), so if anybody has figured this out I would be grateful for any suggestions.
