### ISSUE TITLE
The best way to override skip_row

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#699]
Is this the best way?

    class YourResource(ModelResource):
        def skip_row(self, instance, original):
            # additional checks
            return super(YourResource, self).skip_row(instance, original)

I'll try adding it to the docs after confirmation or improvement.

**Comment by bmihelac** [comment]
It is documented in 5. of http://django-import-export.readthedocs.io/en/stable/import_workflow.html#import-data-workflow

and http://django-import-export.readthedocs.io/en/stable/api_resources.html#import_export.resources.Resource.skip_row

but maybe it can be more clear :)
