### ISSUE TITLE
Ability to hide full tracebacks

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#700]
I usually include the data that is wrong into the error output of my Widgets and currently we don't need any tracebacks. For now I'm using this JS code:

    var jq = document.createElement('script');
    jq.src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js";
    document.getElementsByTagName('head')[0].appendChild(jq);
    jQuery.noConflict();
    jQuery('.traceback').hide();

**Comment by bmihelac** [comment]
I guess that could be done in css as well, ie `.traceback {display: none}`?

I think it is easy enough to achieve and no need for another counfiguration.

**Comment by virtualdvid** [comment]
Hi @bmihelac,

I'd like to hide the tracebacks after a fail import for users. `DEBUG = False` in settings and `.traceback {display: none}` are not working. Do you know how can I acomplish this?
