### ISSUE TITLE
ExportActionModelAdmin is a bit heavyweight

### ISSUE THREAD

**Issue by andybak** [django-import-export/django-import-export#701]
It stomps over any existing templates overrides and actions. Ideally there should be a more lightweight way that doesn't require a mixin or different base class.

I came up with the following for my own purposes. Maybe it's worth adding to the docs?

https://github.com/DjangoAdminHackers/ixxy-admin-utils/commit/d999e68c82b35a4530aa10d71a1862198f74a50b

**Comment by manelclos** [comment]
Hi @andybak,

Isn't that ExportActionModelAdmin?

http://django-import-export.readthedocs.io/en/stable/api_admin.html#import_export.admin.ExportActionModelAdmin

**Comment by andybak** [comment]
@manelclos 

> Isn't that ExportActionModelAdmin?

I'm not sure what the referent of "that" is in your sentence. Can you clarify your question?

**Comment by manelclos** [comment]
@andybak sorry, I mean that ExportActionModelAdmin seems to be the lightweight version you are asking for. In your code you are creating an option for exporting, this is why I suggested ExportActionModelAdmin.

**Comment by andybak** [comment]
Hmmmm. Looking again at ExportActionModelAdmin - these are the problems I see:

1. It sets change_list_template = None (I might be using custom templates for other purposes
2. It sets a custom action_form (see above)
3. It overwrites the actions class property (I can juggle the order of subclasses to avoid problems but it's still a source of potential problems)

It just seems to be doing an awful lot of work for a fairly simple thing. If the existing export_admin_action was refactored then you could support both the convenient but opinionated current method (with the drawbacks documented) - and a more lightweight action which would be similar to my linked commit but with less code duplication with the current export_admin_action

**Comment by manelclos** [comment]
Agreed, we should have simpler classes and build the views and the admin on top of them. Please see https://github.com/django-import-export/django-import-export/pull/692 for related work. Would be great to come up with a proposal before doing any work.

Thanks!!
