### ISSUE TITLE
Meta.fields shadows import_export.fields

### ISSUE THREAD

**Issue by krishraghuram** [django-import-export/django-import-export#703]
from import_export import resources, fields
	from .models import Profile

	class ProfileResource(resources.ModelResource):
		class Meta:
			model = Profile
		        fields = ('rollno', 'name', 'resident_hostel', 'subscribed_hostel')
	        rollno = fields.Field(readonly = True)

I get an error `'tuple' object has no attribute 'Field'`  in the last line.

I assume this is because import_export.fields is being shadowed by the fields tuple that specify white listed fields.

The easy fix is : `from import_export.fields import Field` instead of `from import_export import fields`
But I think this problem should be mentioned in the **Getting Started** section of docs, so that new users don't get confused.

**Comment by bmihelac** [comment]
Hello @krishraghuram,

thanks for raising this, I see how it can add confusion. Would you like to make PR which would update docs to use `from import_export.fields import Field` instead of `from import_export import fields`?
