### ISSUE TITLE
ImportExportActionModelAdmin bug

### ISSUE THREAD

**Issue by nyssance** [django-import-export/django-import-export#715]
ImportExportActionModelAdmin can not choose export type

**Comment by bmihelac** [comment]
Hi @nypisces, I do not understand - can you add more info?

**Comment by josephyin** [comment]
I watch the source code.
`class ExportActionMixin(ExportMixin):
    """
    Mixin with export functionality implemented as an admin action.
    """

    # Don't use custom change list template.
    change_list_template = None

    def __init__(self, *args, **kwargs):
        """
        Adds a custom action form initialized with the available export
        formats.
        """
        choices = []
        formats = self.get_export_formats()
        if formats:
            choices.append(('', '---'))
            for i, f in enumerate(formats):
                choices.append((str(i), f().get_title()))

        self.action_form = export_action_form_factory(choices)
        super(ExportActionMixin, self).__init__(*args, **kwargs)

    def export_admin_action(self, request, queryset):
        """
        Exports the selected rows using file_format.
        """
        export_format = request.POST.get('file_format')

        if not export_format:
            messages.warning(request, _('You must select an export format.'))
        else:
            formats = self.get_export_formats()
            file_format = formats[int(export_format)]()

            export_data = self.get_export_data(file_format, queryset, request=request)
            content_type = file_format.get_content_type()
            response = HttpResponse(export_data, content_type=content_type)
            response['Content-Disposition'] = 'attachment; filename=%s' % (
                self.get_export_filename(file_format),
            )
            return response
    export_admin_action.short_description = _(
        'Export selected %(verbose_name_plural)s')

    actions = [export_admin_action]

    class Media:
        js = ['import_export/action_formats.js']`
when I click the export action, 'file_format' is None, so I get a warning message say 'You must select an export format.'

**Comment by andrewgy8** [comment]
@josephyin Do you mind posting a snippet of your own code? And if I understand correctly, there are no file formats available to be selected in the drop down?

**Comment by YPCrumble** [comment]
I think I know what's going on here. People are using something like `ExportActionMixin`. If you use this mixin, it needs to be _first_, not last.

So this would cause this issue:

class MyModelAdmin(admin.ModelAdmin, ExportActionMixin)

...and this would solve the issue:

class MyModelAdmin(ExportActionMixin, admin.ModelAdmin)

My initial thought was to update the documentation, but a more elegant solution might be to add a more helpful error message, adding something like "Perhaps you forgot to declare the import_export mixin admin.ModelAdmin in your admin.py file?"

What do you think @andrewgy8 ?

**Comment by andrewgy8** [comment]
I think that sounds great @YPCrumble ! If this is indeed the issue, documentation could always be beneficial in this instance. Submit a PR if you have some time for it!

**Comment by josephyin** [comment]
@YPCrumble that's great. Maybe you solved my problem.
