### ISSUE TITLE
broken design in ul.object-tools (Import not accessible)

### ISSUE THREAD

**Issue by zvolsky** [django-import-export/django-import-export#716]
The hack in
import_export/templates/admin/import_export/change_list.html
rewrites the ul.object-tools element.

However some admin template packages, especially bootstrap packages (I have tested django-admin-bootstrap and django-admin-bootstrapped) generate the same, but with additional classes like .pull-right.

In such case django-import-export will break their design
and in result the ul.object-tools can be completly hidden by other objects (and both Import and Add will be not accessible).

I know that this is completly ugly and the problem is somewhere between django standard admin, django admin template package and your project,
however I think you shoul remove your template completly and
a) let it so, because I don't feel that user without Add permissions should Import,
b) or, think about some other less conflicting solution - which will be difficult.

My meaning: a)

**Comment by bmihelac** [comment]
Hi @zvolsky,

It should work with standard django admin templates - if not it should be fixed.

For other admin templates, it is easy enough to  override django-import-export templates. It would be better if it would just work, but last time that I checked, this was not possible without adding complexity.

It is possible that recent Django versions changed template structure that would allow apps to play nicely with other admin templates. In this case, I look forward to update this.

**Comment by paulbaker3** [comment]
I've looked around to see how to "override django-import-export templates". Is there example code of how to do this? Did I miss something in the docs? I'm on Django 1.11 and django-import-export 2.1.0 with `bootstrap-admin==0.3.6` and `django-admin-bootstrapped==2.5.0` onboard. Currently if `django_admin_bootstrapped` is installed, the action menu drop down is hidden entirely on page load. Any thoughts?
