### ISSUE TITLE
Just import button and not the export?

### ISSUE THREAD

**Issue by GuidoBrasil** [django-import-export/django-import-export#718]
Hi There, 

I guess my installation is working fine. However it is curious that I just see the import button, and not the export one?? 

This I how I build my admin interface.. 

```
class EmpresaResource(resources.ModelResource):
    class Meta:
        model = Empresa
```

```
@admin.register(Empresa)
class EmpresaAdmin(ImportExportActionModelAdmin):
    resource_class = EmpresaResource
    list_display = ['empresa']
    ordering = ['empresa']
    search_fields = ['empresa']
    list_filter = ['empresa']
```

![screen shot 2017-12-26 at 21 10 51](https://user-images.githubusercontent.com/2990873/34366330-57105214-ea81-11e7-893d-88592d37b7c8.png)

**Comment by manelclos** [comment]
Try with ImportExportModelAdmin
