### ISSUE TITLE
before_export method

### ISSUE THREAD

**Issue by matisse00** [django-import-export/django-import-export#721]
Is before_export method were created for change queryset?
If answer is yes, it doesn't working, queryset is immutable.
We had to use something like this:

```
def export(self, queryset=None, *args, **kwargs):
        queryset = queryset.exclude(name__isnull=True)
        return super().export(queryset, *args, **kwargs)
```

**Comment by bmihelac** [comment]
No it is not, see `get_queryset`:

https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.resources.ModelResource.get_queryset
