### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by minedbp** [django-import-export/django-import-export#722]
Hi there

I have this issue when I'm importing excel data or any other formats, it's all the same, export no problem but only when I import the data.

Can anybody help me on this? thanks

Thanks
PoL

**Comment by manelclos** [comment]
Hi @minedbp, you need to provide more info and the error you are getting.

**Comment by minedbp** [comment]
Hi manelclose

I've got this error message when importing from .xlsx file format.
![image](https://user-images.githubusercontent.com/31558920/35505658-bc11af4a-0521-11e8-865a-489ccc0ea914.png)

Resource.py
class HouseTypeStandardResource(resources.ModelResource):
    class Meta:
        model = HouseTypeStandard
        skip_unchanged = True
        fields = ('id', 'house_type', 'house_type_desc',
                  'is_active')

Admin.py
class HouseTypeStandardAdmin(ImportExportModelAdmin):
    # A handy constant for the name of the alternate database.
    using = settings.APP_LABEL_PIG_FARM_SYSTEM

    list_display = ('id', 'house_type', 'house_type_desc',
                    'is_active', )
    search_fields = ['id', 'house_type', 'house_type_desc',
                     'is_active', ]
    fieldsets = (
        (None, {
            'fields': ('house_type', 'house_type_desc',
                       'is_active',)
        }),
    )

    def save_model(self, request, obj, form, change):
        # Tell Django to save objects to the 'other' database.
        obj.save(using=self.using)

    def delete_model(self, request, obj):
        # Tell Django to delete objects from the 'other' database
        obj.delete(using=self.using)

    def get_queryset(self, request):
        # Tell Django to look for objects on the 'other' database.
        return super(HouseTypeStandardAdmin, self).get_queryset(request).using(self.using)

    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        # Tell Django to populate ForeignKey widgets using a query
        # on the 'other' database.
        return super(HouseTypeStandardAdmin, self).formfield_for_foreignkey(db_field, request, using=self.using, **kwargs)

    def formfield_for_manytomany(self, db_field, request, **kwargs):
        # Tell Django to populate ManyToMany widgets using a query
        # on the 'other' database.
        return super(HouseTypeStandardAdmin, self).formfield_for_manytomany(db_field, request, using=self.using, **kwargs)

    resource_class = HouseTypeStandardResource


admin.site.register(HouseTypeStandard, HouseTypeStandardAdmin)

These are all my scripts, last time it works but i don't know why suddenly doesn't, hope you can guide me on this.

Thanks
minedbp

**Comment by manelclos** [comment]
Hi, unless you can provide more info or the complete stack trace, the error seem to be a problem using django.
