### ISSUE TITLE
DBF import export feature

### ISSUE THREAD

**Issue by Arlington1985** [django-import-export/django-import-export#726]
I cannot see in dropdown list dbf file option, but written that it supports everything what tablib does and tablib support dbf files as well. How can I use DBF file option?

**Comment by manelclos** [comment]
Hi @Arlington1985, create a new format, see examples here: https://github.com/django-import-export/django-import-export/blob/master/import_export/formats/base_formats.py

**Comment by Arlington1985** [comment]
This is another option. So it it means it doesn't support DBF yet

**Comment by andrewgy8** [comment]
Hi @Arlington1985 ! Thanks for bringing this up. Although we don't have a defined `Format` for this, it is certainly still possible to import this file type. 

Would you be able to submit a PR to add this `Format` class?
