### ISSUE TITLE
How to customize import to do two models

### ISSUE THREAD

**Issue by gregpinero** [django-import-export/django-import-export#728]
I'm trying to import new users, and also have a model with a foreign key to users be created at the same time.

Data to import might look like this:
username, email, phone, company_name, company_address
...

So I'd want the import to create the user (ignoring the company fields) and then also create the company if it doesn't yet exist.

Is this possible?  How might you approach it?

**Comment by manelclos** [comment]
Hi @gregpinero,

I usually create a custom format and override create_dataset for that use case. But I abuse it saving FK values no matter if dry_run is set or not. Anyway it may be of use to you:

```
class CustomFormat(XLS):
    def __init__(self):
        super().__init__()
        self.headers = ['define headers here']

    def create_dataset(self, in_stream):
        xls_book = xlrd.open_workbook(file_contents=in_stream)
        dataset = tablib.Dataset()
        sheet = xls_book.sheets()[0]

        dataset.headers = self.headers
        for i in moves.range(1, sheet.nrows):
            values = sheet.row_values(i)
            ... recover data, process values, 
            dataset.append(values)
        return dataset

```
