### ISSUE TITLE
Help with speed improvements?

### ISSUE THREAD

**Issue by jonathan-s** [django-import-export/django-import-export#730]
@bmihelac When using django-import-export it's fairly slow if you're uploading many thousands of entries. Would you be interested in someone doing some work to speed this up?

I would load the import into a data frame and put the queryset in a dataframe as well. From that you can make a diff to present to the user. 

When inserting into the database you can copy the csv directly into the database (at least for postgres). Which is also a lot faster than updating the objects individually which I think is happening now.

**Comment by bmihelac** [comment]
Helllo @jonathan-s,

By *dataframe* you means pandas.DataFrame?
I do not have experience with pandas but speed optimisations for large datasets would definitely be useful for many users. Do you think it could be possible to utilize pandas for current import process. If you are not familiar with Import workflow and work that is done here is overview:
http://django-import-export.readthedocs.io/en/latest/import_workflow.html

**Comment by jonathan-s** [comment]
Yes, with dataframe I mean a pandas.DataFrame. 

The current implementation collects all errors it's possible to do that because it goes through row by row, however if we want to make a bulk insert to save time it will only ever get one error, which is when the import fails and we won't precisely be able to tell where this error occurs (at what row). Is that tradeoff acceptable?

**Comment by chgad** [comment]
Hi,

@jonathan-s  nice idea but I'd like to see both versions. In my usecases I'm allomst allways uploading DataSets with around 200 entries, so it's not that bad. But I see your Problem (faced it one time though) and I would suggest when implementing the usage of pandas.DataFrame, also leave a "fall back option" like `collect_errors = True` when someone wants to use the slower yet more verbose version

**Comment by yozlet** [comment]
Having spent the last month digging through the code, I can see several ways of speeding it up, _but_:
	1. Some of the optimisations are totally dependent on the schema definition; in other words, it's possible that a big chunk of the work is due to how you've defined your `ModelResource`, especially with things like `ForeignKeyWidget`. Even so, there are a few things we could do here that make it faster for everyone.
	2. Another user-specific issue is caching & memory usage. _If_ the slowest operations are DB queries, and optimisation happens by reducing them, then _almost any_ caching you do will help _somewhat_. On my project we've had bad luck with caching causing more problems than it solves, so I'm wary of adding new things; however, some very unscientific testing with `django-cachalot` shows significant improvements, even if you just give it a `locmem` cache and forcibly wipe it at the start of every request. There are enough repeated `SELECT`s to make a difference. The point is: **there are speed improvements you can make without changing django-import-export at all**.
	3. Most importantly: **Before making major code changes, _know_ where the problem areas are.** I've only done a little profiling so far, but from what I've seen, there's a strangely huge number of queries being made in unexpected areas. (Given how little time I had to spare for profiling, that's as concrete as I'm willing to say.) So:
		1. Have easily-repeatable performance tests that cover the uses you/we need
		2. Those tests should measure a bunch of different things (wall clock time and total query count being the two main ones, but cache hit/miss metrics would be valuable too)
		3. Have a profiling setup that's good enough to be refined as investigation/work progresses
