### ISSUE TITLE
Unable to import model with BinaryField

### ISSUE THREAD

**Issue by roshanr95** [django-import-export/django-import-export#736]
I'm trying to import data for a model which has nullable `BinaryField`. The data doesn't contain the field and I want it to be imported with a null value in the field. If the field already exists in the database for a given `id`, it should keep the value as it is.

I removed the field from the `fields` whitelist in the corresponding `Resource` object and added it to the `exclude` blacklist. However, I'm getting this error while importing - `can't pickle memoryview objects`.

Traceback:

    Traceback (most recent call last):
    File "/lib/python3.5/site-packages/import_export/resources.py", line 451, in import_row
    original = deepcopy(instance)
    File "/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
    File "/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
    File "/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
    File "/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
    File "/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
    TypeError: can't pickle memoryview objects

Package versions - django==1.11, django-import-export==0.6

Reduced version of the code as an example:

    class ABC(models.Model):
        name = models.CharField('Name', max_length=128, blank=False, null=False)
        binary_field = models.BinaryField('Some name', null=True, blank=True)

    class ABCResource(resources.ModelResource):
        class Meta:
            model = ABC
            fields = (
                'id',
                'name',
            )
            import_id_fields = ('id',)
            exclude = ('binary_field',)

    class ABCAdmin(ImportExportModelAdmin):
        form = ABCModelForm
        list_display = (
            'id',
            'name',
        )
        exclude = ('binary_field',)
        resource_class = ABCResource

**Comment by axiom24** [comment]
@bmihelac can you take a look at this?

**Comment by skyl** [comment]
```
File "py/env/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 2290, in get_db_prep_value
return connection.Database.Binary(value)
TypeError: memoryview: a bytes-like object is required, not 'str'
```
