### ISSUE TITLE
REST Exports

### ISSUE THREAD

**Issue by chgad** [django-import-export/django-import-export#739]
Hey all,

i stumbled upon this PR #692 in the process of creating REST-Api endpoints for one of my projects. Unfortunately this aproach didn't fit my purposes so I wrote an "export REST view" myself (looking forward to also write an import REST view). So my question now: Is it in the sense of this project to also provide "non-admin" views, REST-like views, utilizing resources etc. ?

If so I would refactor my code, enhance it further and open a PR.

Thanks in advance.

**Comment by chgad** [comment]
Any Thoughts about this ?

**Comment by ZuluPro** [comment]
@chgad 
Could you say why the `ExportView` doesn't fit with your requirerments ?
