### ISSUE TITLE
Import Export is not getting all the values from the columns

### ISSUE THREAD

**Issue by Umartahir93** [django-import-export/django-import-export#741]
I am importing data from excel file. Import-export stores first two columns in the database. But it is not able 
to copy other columns. Attach is preview of my django import export
![capture](https://user-images.githubusercontent.com/31737085/36430595-57ce3e92-1677-11e8-88af-b1ba2c0aba86.JPG)

**Comment by GregKaleka** [comment]
Can you share what your import file looks like and what format it's in?

**Comment by manelclos** [comment]
and also the resource configuration you are using
