### ISSUE TITLE
Import using NON-DEFAULT Database

### ISSUE THREAD

**Issue by minedbp** [django-import-export/django-import-export#748]
Hi Guys

Is there a way that I could use non-default database to import the data? Cause right now I have other external / or non-default databases inside my django admin site.

Thanks

**Comment by manelclos** [comment]
I'd usually write a Django Database Router when using multiple databases: https://docs.djangoproject.com/en/2.0/topics/db/multi-db/#using-routers

**Comment by minedbp** [comment]
Hi manelclos

I'm also using routers but some cases when I'm integrating the django admin interface, I can be able to display the data from external database and can export data as well, but when I tried to import back the .csv file then this is the issue that can't find the external database. 

**Admin.py**
class ContactUsAdmin(ImportExportModelAdmin):
    using = 'other_db_name'

    list_display = ('id', 'full_name', 'email',
                    'subject', 'submitted')
    search_fields = ['id', 'full_name', 'email', 'subject', 'message']
    list_filter = ('submitted', )
    fieldsets = (
        (None, {
            'fields': ('full_name', 'email',
                       'subject', 'message')
        }),
    )

    def save_model(self, request, obj, form, change):
        # Tell Django to save objects to the 'other' database.
        obj.save(using=self.using)

    def delete_model(self, request, obj):
        # Tell Django to delete objects from the 'other' database
        obj.delete(using=self.using)

    def get_queryset(self, request):
        # Tell Django to look for objects on the 'other' database.
        return super().get_queryset(request).using(self.using)

    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        # Tell Django to populate ForeignKey widgets using a query
        # on the 'other' database.
        return super().formfield_for_foreignkey(db_field, request, using=self.using, **kwargs)

    def formfield_for_manytomany(self, db_field, request, **kwargs):
        # Tell Django to populate ManyToMany widgets using a query
        # on the 'other' database.
        return super().formfield_for_manytomany(db_field, request, using=self.using, **kwargs)

    resource_class = ContactUsResource


admin.site.register(ContactUs, ContactUsAdmin)

**Resources.py**
class ContactUsResource(resources.ModelResource):

    using =  'other_db_name'

    def save_model(self, request, obj, form, change):
        # Tell Django to save objects to the 'other' database.
        obj.save(using=self.using)

    def delete_model(self, request, obj):
        # Tell Django to delete objects from the 'other' database
        obj.delete(using=self.using)

    def get_queryset(self, request):
        # Tell Django to look for objects on the 'other' database.
        return super().get_queryset(request).using(self.using)

    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        # Tell Django to populate ForeignKey widgets using a query
        # on the 'other' database.
        return super().formfield_for_foreignkey(db_field, request, using=self.using, **kwargs)

    def formfield_for_manytomany(self, db_field, request, **kwargs):
        # Tell Django to populate ManyToMany widgets using a query
        # on the 'other' database.
        return super().formfield_for_manytomany(db_field, request, using=self.using, **kwargs)

    class Meta:
        model = ContactUs
        skip_unchanged = True

What could be the possible reason for this, any help really appreciated.

Thanks a lot

**Comment by sv8083** [comment]
@minedbp  Did your issue get resolved?
