### ISSUE TITLE
Can only import one ManyToMany field

### ISSUE THREAD

**Issue by KrystalPhuar** [django-import-export/django-import-export#750]
Hi, 
I have a model with 2 Many To Many fields. Exporting files is completely fine but I can't import files such as Excel files to my database from the admin. My codes are below: 

![screen shot 2018-02-28 at 12 39 49 am](https://user-images.githubusercontent.com/25235451/36763451-ea8453f4-1c1f-11e8-8342-94de52b99f8a.png)
![screen shot 2018-02-28 at 12 39 40 am](https://user-images.githubusercontent.com/25235451/36763454-ec9dd2f0-1c1f-11e8-9b39-4e1baabefea9.png)

The error I'm getting:
![screen shot 2018-02-28 at 12 36 53 am](https://user-images.githubusercontent.com/25235451/36763354-7f1280e6-1c1f-11e8-9669-aa93f160aa3e.png)

Approach and Specialty are the 2 M2M fields and I can only import either one field at a time. For example, if in my excel sheet the Approach column is filled while the Specialty column is empty, I can import it. But not when both is filled. Would appreciate any help that you all provide. Thanks!

**Comment by rms-sth** [comment]
I have similar problem while importing the exported files m2m relationship
