### ISSUE TITLE
Add field value from import form

### ISSUE THREAD

**Issue by justkrevedko** [django-import-export/django-import-export#758]
Hi!

Need advice about how to add field value which is not in import file. Created custom _InputForm_, but stucked with getting value from my select in _before_import_ function

<img width="316" alt="my_select" src="https://user-images.githubusercontent.com/175383/36974805-0d6c30ea-2089-11e8-8d78-cb4d2f195aae.png">

**Comment by justkrevedko** [comment]
Just invented solution. I added hidden field in my import forms, then added these values in dataset in  process_import and import_action methods in my ImportExportActionModelAdmin class.

There might be a simpler solution, but my also works!

**Comment by mgrdcm** [comment]
@justkrevedko I like that!  Would you be willing to throw together a little more information about how you did that?  I think that's a common problem (I have a similar need but haven't worked out a complete solution yet) so would love to have some documentation on ways to solve it.

**Comment by justkrevedko** [comment]
Hello, @mgrdcm 
First I created custom forms.py in my project to add new fields:

> forms.py

```
from django import forms
from import_export.forms import ImportForm, ConfirmImportForm
from .models import Contract

class CustomImportForm(ImportForm):
    ...
    #this is my custom field
    input_contract = forms.ChoiceField(label = "Contract", choices=())

    def __init__(self, import_formats, *args, **kwargs):
        super(CustomImportForm, self).__init__(import_formats, *args, **kwargs)
        ...
        #get values for select
        choices = []
        contracts = Contract.objects.all()
        for c in contracts:
            choices.append((str(c.pk), c.name))
        choices.insert(0, ('', '---'))
        self.fields['input_contract'].choices = choices

class CustomConfirmImportForm(ConfirmImportForm):
    #need to set custom field value to save after import preview
    input_contract = forms.CharField(widget=forms.HiddenInput())
```

Then I overrode methods in my ImportExportActionModelAdmin class

> admin.py

```
from .forms import CustomImportForm, CustomConfirmImportForm
...
class CameraAdmin(ImportExportActionModelAdmin):
    resource_class = CameraResource
    #not needed all formats
    formats = (base_formats.XLS, base_formats.CSV)
    ...
    # return my custom import form here
    def get_import_form(self):
        return CustomImportForm

    def import_action(self, request, *args, **kwargs):
        ...
        if request.POST and form.is_valid():
            input_format = import_formats[
                int(form.cleaned_data['input_format'])
            ]()
            import_file = form.cleaned_data['import_file']
            #here saving select value
            input_contract = form.cleaned_data['input_contract']
            ...
 
           #modify dataset to see value on import preview
            contract_field = [int(input_contract)] * dataset.height
            dataset.append_col(contract_field, header='contract')
            ...
            
            if not result.has_errors():
                context['confirm_form'] = CustomConfirmImportForm(initial={
                    'import_file_name': tmp_storage.name,
                    'original_file_name': import_file.name,
                    'input_format': form.cleaned_data['input_format'],
                    # set hidden value in confirm form
                    'input_contract': form.cleaned_data['input_contract']
                })
     ...

    @method_decorator(require_POST)
    def process_import(self, request, *args, **kwargs):

        confirm_form = CustomConfirmImportForm(request.POST)
        if confirm_form.is_valid():
            import_formats = self.get_import_formats()
            input_format = import_formats[
                int(confirm_form.cleaned_data['input_format'])
            ]()
            # get value here
            input_contract = confirm_form.cleaned_data['input_contract']
            ...        
            # modify dataset berore save
            contract_field = [int(input_contract)] * dataset.height
            dataset.append_col(contract_field, header='contract')
            ...
```

**Comment by cpoetter** [comment]
I am having a bit trouble implementing this. I see the custom field on the import form, but the value does not get set in the actual import. Did anybody else make this work?

**Comment by yozlet** [comment]
I found a simpler way of doing this: If you override `ImportExportModelAdmin.get_resource_kwargs()`, you can store the `request` object in your Resource class, then use it in `before_import_row()`.

Most of the magic happens in the resource:

```python
class CameraResource(ModelResource):
	... your resource definition...

	# Override the constructor to store the request
    def __init__(self, request=None):
        super()
        self.request = request

    # Insert the contract into each row
    def before_import_row(self, row, **kwargs):
        row['import_contract'] = self.request.POST.get('import_contract', None)
```

In order to get the `request` to the resource constructor:

```python
class CameraAdmin(ImportExportActionModelAdmin):
    resource_class = CameraResource
	
    def get_import_form(self):
        return CameraImportForm

    # add the request to the resource constructor call kwargs
    def get_resource_kwargs(self, request, *args, **kwargs):
        rk = super().get_resource_kwargs(request, *args, **kwargs)
        rk['request'] = request
        return rk
```

Also, if your custom form is just querying a model's instances for a ForeignKey reference, you don't need a special form constructor. Just use a `ModelChoiceField` with the `queryset` argument:

```python
class CameraImportForm(ImportForm):
    input_contract = forms.ModelChoiceField(label = "Contract", queryset=Contract.objects.all())
```

The only difference I can see is that this way doesn't allow for a custom ConfirmImportForm. Currently there's no `ImportExportActionModelAdmin.get_confirm_import_form()`, which is a shame. The good news is that the use of `before_import_row()` means you don't need it anyway.

**Comment by Wolverine7** [comment]
@yozlet what are you refering here as 'import_contract'  
contract = self.request.POST.get('import_contract', None)?

**Comment by yozlet** [comment]
@Wolverine7 Thanks for catching that typo! I meant `input_contract` (from @justkrevedko's original code).

I've also taken the opportunity to move the logic around a little, as I talked about in #899. This is the code you were asking for; sorry for not replying sooner!

**Comment by Wolverine7** [comment]
@yozlet thank you for your prompt response! really appreciate your help!

**Comment by jishnu-ramachandran** [comment]
10

**Comment by Milstein** [comment]
is there any new solution using : `get_form_kwargs` instead of `get_resource_kwargs`?

**Comment by mgrdcm** [comment]
Yes there should be @Milstein!  That's what I'm using it for.  Apologies I don't have a full example to share right now.
