### ISSUE TITLE
Import export getting only first two columns of imported excel file

### ISSUE THREAD

**Issue by navid-rida** [django-import-export/django-import-export#760]
I'm trying to import an excel file from admin panel import utility. however, import export is getting only first two columns of the file. here's how my excel file looks like:
![djangi-import-export-3](https://user-images.githubusercontent.com/5724258/37285898-a9d93026-262a-11e8-9870-99f15fdd7470.jpg)

here's my admin panel after the file has been imported. Please note that the value mentioned in the opening_date column is the default value provided in the model class.
![django-import-export-2](https://user-images.githubusercontent.com/5724258/37286012-ed1afffe-262a-11e8-99b5-dd29d11843f9.jpg)

I've gone through other related issues such as #741 but no working solution is provided

**Comment by wangzhaohe** [comment]
Same question with you! Did it solved?
