### ISSUE TITLE
How to only import new rows and disable update while importing

### ISSUE THREAD

**Issue by sameerkumar18** [django-import-export/django-import-export#761]
Consider the follwoing as CSV uploaded while importing - 
May 2018,7697,0,5870,0,0,0,0,0,0,0,0,600,0,30,200,6700
May 2018,7735,0,5870,0,0,0,0,0,0,0,0,600,0,30,200,6700

The django-import-export considers the first record as a new record and the second record as an update to the first record. 
So I was wondering if there was a way to disable the update and only consider input rows as new rows while importing.

I would greatly appreciate if someone could help me out with this!
Thanks :)

**Comment by carlmalouf** [comment]
Just wondering why this was closed? I have the same issue. I have deliberate duplicate records that aren't being imported.
