### ISSUE TITLE
Skipping erroneous rows during importing? 

### ISSUE THREAD

**Issue by vincentwhales** [django-import-export/django-import-export#763]
I am importing a large file containing rows from a crawler. 

Right now if one row has an invalid data my entire import is halted. 

Is there anyway to tell django-import-export to skip erroneous rows during import?

**Comment by manelclos** [comment]
Hi @vincentwhales, no specific option right now. But you can easily use a different Result class in Resource, see get_result_class (https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L196).

Then you can have result.has_errors() return False, and if you are still interested in errors a has_errors_real() to check in your code.

https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L580

Let us know if you give it a try.

**Comment by rvyav** [comment]
You literally saved my life!! @Bubbassauro

**Comment by tawanda** [comment]
@Bubbassauro you also saved me some pain of going into the packages innards, thanks

**Comment by dwasyl** [comment]
@Bubbassauro When I override `import_row`, I keep getting errors from `increment_row_result_total` reporting that `'NoneType' object has no attribute 'import_type'` this is based on `row_result` being `None`.

Any ideas what's going on? Even if I just override `import_row` and run `super()` I get the same error.

**Comment by Rubyj** [comment]
It would be nice if we had the `skip_rows()` function occur before calling import_row

**Comment by sarendsen** [comment]
The snippet does not show the preview table correctly when the import file is missing columns.
Snippet below takes this into account.

```python
class ModelResource(resources.ModelResource):
    def get_field_names(self):
        names = []
        for field in self.get_fields():
            names.append(self.get_field_name(field))
        return names

    def import_row(self, row, instance_loader, **kwargs):
        # overriding import_row to ignore errors and skip rows that fail to import
        # without failing the entire import
        import_result = super(ModelResource, self).import_row(
            row, instance_loader, **kwargs
        )

        if import_result.import_type == RowResult.IMPORT_TYPE_ERROR:
            import_result.diff = [
                row.get(name, '') for name in self.get_field_names()
            ]

            # Add a column with the error message
            import_result.diff.append(
                "Errors: {}".format(
                    [err.error for err in import_result.errors]
                )
            )
            # clear errors and mark the record to skip
            import_result.errors = []
            import_result.import_type = RowResult.IMPORT_TYPE_SKIP

        return import_result
```

**Comment by longlep** [comment]
In case anyone is interested, I had the same problem as @dwasyl  and it was caused by naming confusion with pylint_django.  Uninstalling pylint_django fixed the problem.

**Comment by m-ketan** [comment]
@Bubbassauro @sarendsen How can i return the errors list to my view and use it from there?

**Comment by Bbillyben** [comment]
Thanks all for the code all! you saved a great amount of time looking for the right method to dig into!

I would add a little modification, in case the field column name do not match the field name:


```
class SkipErrorRessource(resources.ModelResource):
    
    report_error_column=False  # a parameter to report table column not defined in the resource class
    
    def get_field_column_names(self):
        names = []
        for field in self.get_fields():
            names.append(field.column_name)  # >> get the field name 'used' name
        return names

    def import_row(self, row, instance_loader, **kwargs):
        import_result = super(SkipErrorRessource, self).import_row(
            row, instance_loader, **kwargs
        )

        if import_result.import_type == results.RowResult.IMPORT_TYPE_ERROR:
            import_result.diff=[]
            for field in self.get_fields():    # >> loop throught the field directly and gather from the field column name instead of field name
                import_result.diff.append(row.get(field.column_name, ''))
            
            if self.report_error_column:  # >> to report eventual columnds not in the resources definition, to help spotting the issue.
                for row_name in row:
                    if not row_name in self.get_field_column_names():
                        import_result.diff.append(row.get(row_name, ''))

            # Add a column with the error message
            import_result.diff.append(
                "Errors: {}".format(
                    [err.error for err in import_result.errors]
                )
            )
            # clear errors and mark the record to skip
            import_result.errors = []
            import_result.import_type = results.RowResult.IMPORT_TYPE_SKIP

        return import_result

    class Meta:
        abstract = True

```

**Comment by matthewhegarty** [comment]
I took another look at this issue based on the v3.3.4 codebase.

If running the import as a [script][1], then you have the [`raise_errors`][2] param which you pass to [`import_data()`][3].  If `True`, the script will exit as soon as an error is encounted, if `False` (default) then errors will be stored internally in the [`Result`][4] object.

If running via the Admin UI, then by default any errors during import will be reported to the user, and the import will fail:

![Screenshot 2023-12-18 at 16 40 23](https://github.com/django-import-export/django-import-export/assets/6249838/252f9b94-7c7e-4b4f-ba1d-bd34923ac8d6)

However, you can override this behaviour in your Resource, so that rows with validation errors are skipped:

```python
  def skip_row(self, instance, original, row, import_validation_errors=None):
      if import_validation_errors:
          return True
      return super().skip_row(instance, original, row, import_validation_errors)
```

[1]: https://django-import-export.readthedocs.io/en/latest/getting_started.html#importing-data
[2]: https://github.com/django-import-export/django-import-export/blob/bf18044f3d9102371400316570800b0181412f2e/import_export/resources.py#L859
[3]: https://github.com/django-import-export/django-import-export/blob/bf18044f3d9102371400316570800b0181412f2e/import_export/resources.py#L843
[4]: https://github.com/django-import-export/django-import-export/blob/bf18044f3d9102371400316570800b0181412f2e/import_export/results.py#L113

**Comment by polow** [comment]
I am having trouble using skip_row, even though i override it to skip rows with noj existing relation in one of the fields but it keeps raising error.
Will update my comment with an example.

**Comment by Bbillyben** [comment]
I'm not sure if could be of help, I use the class below for my resources:

```
class SkipErrorRessource(ModelResource):
    
    report_error_column=False
    
    def get_field_column_names(self):
        names = []
        for field in self.get_fields():
            names.append(field.column_name)
        return names

    def import_row(self, row, instance_loader, **kwargs):
        import_result = super(SkipErrorRessource, self).import_row(
            row, instance_loader, **kwargs
        )

        if import_result.import_type == results.RowResult.IMPORT_TYPE_ERROR:
            import_result.diff=[]
            for field in self.get_fields():
                import_result.diff.append(row.get(field.column_name, ''))
            
            if self.report_error_column:
                for row_name in row:
                    if not row_name in self.get_field_column_names():
                        import_result.diff.append(row.get(row_name, ''))

            # Add a column with the error message
            import_result.diff.append(
                "Errors: {}".format(
                    [err.error for err in import_result.errors]
                )
            )
            # clear errors and mark the record to skip
            import_result.errors = []
            import_result.import_type = results.RowResult.IMPORT_TYPE_SKIP

        return import_result
    
    class Meta:
        abstract = True
```
that print error, but skip the rows in errors
