### ISSUE TITLE
Wishlist: Multiple resource classes for one model

### ISSUE THREAD

**Issue by int-ua** [django-import-export/django-import-export#765]
Use case: different sources of information with different fields that require different resource classes.

**Comment by andrewgy8** [comment]
I too would like to know what this would look like.  I'm imaging something like DRF's nested serializer concept. Is that kind of the concept?

**Comment by llombard** [comment]
use case:
I have to export data for multiple needs that do not require the same columns.
I could define several resources and use 
`dataset_need1 = BookResource_1().export()
`dataset_need2 = BookResource_2().export()
in the command line but how to chose the resource in the admin section?
Thanks :)
