### ISSUE TITLE
Option to drop faulty rows during import 

### ISSUE THREAD

**Issue by vincentwhales** [django-import-export/django-import-export#773]
I am importing a lot of rows from my crawler and it's very inconvenient that one single faulty row causes my entire import to be halted. 

Is there anyway to specify django-import-export to just skip a row if it contains any error? 

(Perhaps I can override something at `for_delete`?)

**Comment by formatcom** [comment]
Hi, @vincentwhales can solve this by using **try** and *except* in the method for_delete or as in my case in after_import_row.
![screenshot_2018-05-07_10-08-50](https://user-images.githubusercontent.com/8493573/39709150-b230cede-51de-11e8-8ad3-9378b16d73e7.png)
