### ISSUE TITLE
Export `iterator` optimizations bypass `prefetch_related` optimizations

### ISSUE THREAD

**Issue by jrobichaud** [django-import-export/django-import-export#774]
When using `.iterator()` `prefetch_related` is not taken in consideration (this is a django side effect of `iterator()`).

This is a sample of `export` method of `Resource` class:
```python
        if isinstance(queryset, QuerySet):
            # Iterate without the queryset cache, to avoid wasting memory when
            # exporting large datasets.
            iterable = queryset.iterator()
        else:
            iterable = queryset
        for obj in iterable:
            data.append(self.export_resource(obj))
```

When `queryset` is an instance of `QuerySet` `prefetch_related` defined in `get_queryset()` override will be ignored.

Example ([source of the code example](https://github.com/django-import-export/django-import-export/issues/392#issuecomment-294657764)):

```python
class Book(models.Model):
    tags = TaggableManager()

class BookResource(resources.ModelResource):
    tags = fields.Field()

    class Meta:
        model = Book

    def dehydrate_tags(self, book):
        return ','.join([tag.name for tag in book.tags.all()])

    def get_queryset(self, queryset=None):
        if queryset is None:
            queryset = Book.objects.all()
        return queryset.prefetch_related('tags')
```

Since it is a `QuerySet` and the code of `export` will use `iterator()` it will result with 1 SQL query to fetch the books and 1 SQL query per row to fetch the tags.

The workaround I found was to list the queryset which will bypass the `export` `iterator()` logic:
```python
    def export(self, queryset=None):
        queryset = self.get_queryset(queryset)
        fetched_queryset = list(queryset)
        return super().export(fetched_queryset)
```

With this fix I have now 2 SQL queries only

It works but it is not a clean solution.

Suggested fix:
- In `export` validate if the queryset instance has `prefetch_related` and not use iterator in this situation
- Or add some sort of configuration and documentation to avoid this kind of pointless and complicated override logic.

**Comment by bdauvergne** [comment]
We have the same problem here, I think that django-import-export should use a batched iterator (i.e. take chunk of [n*i:n*(i+1)] of the initial queryset until it returns an empty list, it would allow some prefetching but prevent loading all the table in memory).

**Comment by kingbuzzman** [comment]
Same boat over here..

**Comment by jrobichaud** [comment]
@kingbuzzman, this as by design fact is indeed why I have not filled a bug report to django but to `django-import-export`.

**Comment by kingbuzzman** [comment]
@jrobichaud i have a working solution:

```
from django.core.paginator import Paginator

def page_queryset(queryset, per_page=2000):
    """
    While in a perfect world you would use queryset.iterator(), but there is an issue that it fails to 
    load any prefetch_related() fields specified. Using Paginator() we can mimic the same functionality
    """
    if queryset._prefetch_related_lookups:
        paginator = Paginator(queryset, per_page)
        for index in range(paginator.num_pages):
            yield from paginator.get_page(index + 1)
    else:
        yield from queryset.iterator()
```

**Comment by jrobichaud** [comment]
It makes sense.

Makes sure to add tests using `select_related()` as well.

**Comment by kingbuzzman** [comment]
@jrobichaud will you close this?

**Comment by jrobichaud** [comment]
@kingbuzzman nope, it appears there is a bot closing stuff.

**Comment by Blejwi** [comment]
Same issue here, it would be nice to have this option configurable, because in some cases exporting breaks sensible timeouts for HTTP requests.

**Comment by jrobichaud** [comment]
Still an issue I believe. 🤔

**Comment by jrobichaud** [comment]
Please reopen.

**Comment by kingbuzzman** [comment]
It's a django bug, nothing to do with this lib.

**Comment by andrewgy8** [comment]
@kingbuzzman Is there a link to the django bug?
