### ISSUE TITLE
Remove test database from repository

### ISSUE THREAD

**Issue by bmihelac** [django-import-export/django-import-export#780]
followup from

https://github.com/django-import-export/django-import-export/pull/625

**Comment by manelclos** [comment]
Hi @bmihelac, the idea is to provide some fixtures as example data?

**Comment by bmihelac** [comment]
Yes, if possible fixtures, would be better, than distributing database.

**Comment by ZuluPro** [comment]
@bmihelac @manelclos Factories (from factory-boy) are better.
