### ISSUE TITLE
Question about diff-match-patch requirement

### ISSUE THREAD

**Issue by nikolas** [django-import-export/django-import-export#785]
Hi,
What version of diff-match-patch is django-import-export designed to work with? The version in google's repo isn't published on pypi: https://github.com/google/diff-match-patch/tree/master/python3

I tried this version but the API is slightly different: https://pypi.org/project/diff_match_patch_python/

I'm mainly asking because the version of diff-match-patch here on pypi is pretty old, and untested or maintained on the latest versions of python: https://pypi.org/project/diff-match-patch/

**Comment by bmihelac** [comment]
Hi @nikolas 

as it looks like, we do use pypi version:
https://github.com/django-import-export/django-import-export/blob/master/setup.py#L28

**Comment by nikolas** [comment]
thanks - that version is working fine for me - i was just worried since i'm on like python 3.6 and that package is so old. It's all fine though, guess that means it's good code :p
