### ISSUE TITLE
get_queryset not working with admin

### ISSUE THREAD

**Issue by mcjlnrtwcz** [django-import-export/django-import-export#790]
Hi,
I've defined custom `get_queryset` method for my resource class. I'v set the resource class for my admin class, but when I export data via Django admin the results are not filtered as I want.
It seems like my `get_queryset` method is not evaluated (checked that with print).
Everything works fine when I go to Django shell and export the resource manually.

**Comment by fmirdita** [comment]
I just submitted another issue #797 that might be related to this! I included all the details on my issue.

**Comment by manelclos** [comment]
Hi @mcjlnrtwcz,

The admin export action will use the queryset from the admin, respecting applied filters and searches.

If you want to change the root queryset, the one that is used as a starting point for applying the filters, you have to override get_queryset on the ModelAdmin, and that would also affect your admin changelist, which I think is good.

If you need a queryset that has nothing to do with the changelist, you can create a ExportMixin subclass and override get_export_queryset as @fmirdita suggested in the issue he submitted.

Hope this helps!

**Comment by Mark90** [comment]
Hi @manelclos ,

Thanks, that cleared things up.

Based on the [docs](https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.resources.ModelResource.get_queryset) I tried overriding `get_queryset()` on my `ModelResource` subclass, but it didn't do anything.
Is there any use to overriding that value? Or did I misinterpret the docs?

**Comment by YPCrumble** [comment]
I had the same confusion on this issue. Reading [the docs](https://django-import-export.readthedocs.io/en/latest/api_resources.html#import_export.resources.ModelResource.get_queryset) made me believe that overriding the `get_queryset` method on my `ModelResource` would override the queryset for `ExportMixin`.

Currently `get_queryset` on the `ModelResource` class only gets called if the [queryset passed to `export` is None](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L637). For that reason `ExportMixin` will never call `get_queryset` on the `ModelResource` class. Is there a reason that `get_queryset` on the `ModelResource` shouldn't be able to update a queryset from `ExportMixin`, for instance?

I'd be happy to submit a PR that would call `get_queryset` from the `ModelResource` if maintainers would welcome it? I would suggest adding `self.queryset` as a class property like how `queryset` and `get_queryset` work in Django's `ListView`.

**Comment by edmenendez** [comment]
I also got the impression reading the docs that I could just override `get_queryset` to change the query. Then I found this useful issue :-) The easiest fix may be to just make the docs more clear.

**Comment by bmihelac** [comment]
Thanks, you are right. Updating docs so that *default* queryset is used if no specific queryset is given would be more clear. Would anyone like to make a PR for this?

**Comment by mh-firouzjah** [comment]
Hello there! 👋🏻 
If anyone is still facing issues with this and finds the documentation confusing, the recommended approach to modify the queryset is by utilizing the `filter_export` method. Overriding this method within the ModelResource grants control over the exported data.
