### ISSUE TITLE
is it possible to show a progress bar when importing a file?

### ISSUE THREAD

**Issue by yongxinxu** [django-import-export/django-import-export#793]
When importing a larger file, it usually takes a while to import. For users, it would be great to know how the file is progressing and how long it will take. Is this possible?

**Comment by manelclos** [comment]
Hi @yongxinxu this is not implemented, @bmihelac is this something you would like to see in core import-export?

**Comment by bmihelac** [comment]
No, sorry. I do not see this feature would be available anytime soon.

**Comment by MahamdiAmine** [comment]
@yongxinxu you can get the total rows number using before_import(..) then use the row_number in the function before_import_row() and print something like this ("{}/{}".format(row_number, total))
