### ISSUE TITLE
InvalidDimensions encountered while trying to read file:

### ISSUE THREAD

**Issue by davemerwin** [django-import-export/django-import-export#796]
Django==2.0.6
django-import-export==1.0.1
openpyxl==2.4.9

I've looked a bunch and can't see what is causing the issue. I download an Excel document, add some records, and then upload that same document. Here's the resource in question:

    from import_export.admin import ImportExportModelAdmin
    from import_export import resources

    class MasterCategoryResource(resources.ModelResource):
        class Meta:
            model = MasterCategory

    class MasterCategoryAdmin(ImportExportModelAdmin):
        resource_class = MasterCategoryResource

    admin.site.register(MasterCategory, MasterCategoryAdmin)

Any suggestions?

**Comment by davemerwin** [comment]
By the way, I've double check that there were not empty rows or extra columns.

**Comment by davemerwin** [comment]
I found the issue! Stupid Apple Numbers. If you open an Excel doc and then export it to Excel it adds a bunch of notices to the file and messes up the schema. Really lame.

**Comment by Bhupesh-V** [comment]
this is not actually a solution.
I am having the same issues

> I found the issue! Stupid Apple Numbers. If you open an Excel doc and then export it to Excel it adds a bunch of notices to the file and messes up the schema. Really lame.

**Comment by srugano** [comment]
Having the same problem.

**Comment by andrewgy8** [comment]
Hi @srugano , this issue is a bit old, can you open another one with more detail about your problem? It seems that the OP fixed his issue. Yours probably will be different.
