### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by Dynnammo** [django-import-export/django-import-export#799]
Hello guys.
I installed the package easily and now i can export export whatever i want, however the import tool isn't working at all, throwing me a TypeError each time I submit a file. It precises : 'NoneType' object is not callable

**Here is my model:**
```
class Mission(models.Model):
    name = models.CharField(max_length=100,
                            default="", unique=True,
                            primary_key=True)
    content = models.CharField(max_length=500, default="", blank=True)
```

**with the admin.py code:**
```
import tablib
from django.contrib import admin
from import_export import resources
from import_export.admin import ImportExportModelAdmin
from myProject.app.models import Mission

class MissionResource(resources.ModelResource):

    class Meta:
        model = Mission
        import_id_fields = ('name',)
        fields = ('name', 'content')
        export_order = fields
        exclude = ('id',)

class MissionAdmin(ImportExportModelAdmin):
    resource_class = MissionResource

admin.site.register(Mission,MissionAdmin)

```

**Here is the stack traces:**
```
Traceback:

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/home/myName/.local/share/virtualenvs/myProject/lib/python3.6/site-packages/import_export/admin.py" in import_action
  258.             tmp_storage = self.get_tmp_storage_class()()

Exception Type: TypeError at /admin/app/mission/import/
Exception Value: 'NoneType' object is not callable
```
As far as I searched:

- This errors occurs whatever the file is : csv, json etc. I even tested on random jpg files, so I think it isn't related to the file nature.

- I completely deleted my model in order to put the one in the django-import-export test project, so I think it isn't related to the model

Thanks in advance!

**Comment by Dynnammo** [comment]
I reinstalled maybe more properly the package and the database, and change admin.py, and now it works: RTFM X)

**Comment by OlegEgoism** [comment]
> Я переустановил, может быть, более правильно пакет и базу данных, и изменил admin.py, и теперь он работает: RTFM X)

I have a problem too! can't solve it!
Tell me more about what you did to make it work right?

**Comment by OlegEgoism** [comment]
model.py

class Product(models.Model):
    unique_name = models.CharField(max_length=200, null=True, blank=True, unique=True)
    name = models.CharField(verbose_name='Название товара', max_length=150, blank=False, null=False)  # unique=True?
    description = RichTextField(verbose_name='Описание товара', null=True, blank=True)
    features = RichTextField(verbose_name='Ключевые особенности', null=True, blank=True)
    composition = RichTextField(verbose_name='Состав', null=True, blank=True)
    additives = RichTextField(verbose_name='Пищевые добавки', null=True, blank=True)
    analysis = RichTextField(verbose_name='Гарантированный анализ', null=True, blank=True)
    image = RichTextUploadingField(verbose_name='Изображение товара', blank=True, config_name='custom')
    date_added = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True)
    is_active = models.BooleanField(verbose_name='Активен', default=True)
    animal = models.ManyToManyField('Animal', related_name='products', verbose_name='Тип животного')
    brand = models.ForeignKey('Brand', related_name='products', verbose_name='Бренд', on_delete=models.PROTECT)
    category = models.ForeignKey('Category', related_name='products', verbose_name='Категория',
                                 on_delete=models.PROTECT)

resources.py
class ProductAdminResource(resources.ModelResource):
    animal = fields.Field(column_name='animal', attribute='animal', widget=ManyToManyWidget(Animal, field='name'))
    category = fields.Field(column_name='category', attribute='category', widget=ForeignKeyWidget(Category, field='name'))
    brand = fields.Field(column_name='brand', attribute='brand', widget=ForeignKeyWidget(model=Brand, field='name'))

    class Meta:
        model = Product
        fields = 'id', 'name', 'animal', 'category', 'brand'
        export_order = 'id', 'name', 'animal', 'category', 'brand'  

admin.py
@admin.register(Product)
class ProductAdmin(ImportExportModelAdmin):
    list_display = 'name', 'brand', 'body_description', 'date_added', 'is_active', 'product_options',
    list_editable = 'is_active',
    list_filter = 'date_added', 'animal', 'brand', 'is_active',
    list_per_page = 20
    exclude = ('unique_name',)
    resource_class = ProductAdminResource
