### ISSUE TITLE
ArrayField with different delimiter

### ISSUE THREAD

**Issue by BojanKogoj** [django-import-export/django-import-export#802]
I'm using ArrayField that contains some text, which can have a comma in it. Import/export is a problem, because it splits a field if it contains a comma. Can we add an option for custom delimiters?

**Comment by mgrdcm** [comment]
One way to do this now is to subclass the CSV class and overwrite the delimiter, for instance to use `;` instead of `,`:

```python
from import_export.formats import base_formats


class SCSV(base_formats.CSV):
    """ CSV with Semicolons instead of Commas. """

    def get_title(self):
        return "scsv"

    def create_dataset(self, in_stream, **kwargs):

        kwargs['delimiter'] = ';'

        return super().create_dataset(in_stream, **kwargs)
```

**Comment by mgrdcm** [comment]
Oh!  By "ArrayList" do you mean the Django model field type `ArrayField`?

And are you exporting to JSON again, is that it?

**Comment by BojanKogoj** [comment]
Sorry, yes. I export to JSON and import from JSON on another server.

**Comment by daffdev** [comment]
mgrdcm, can you explain where put the override method or make a example to how use it please?

**Comment by afuetterer** [comment]
Hi, I also would like to import a list to a field from a JSON file to a postgres ArrayField.
For example when importing 
```json
[
  {
    "keywords": ["keyword1", "keyword2"]
  }
]
```
I get 
`Error in line: 1, 'list' object has no attribute 'split'`

If I store the keywords as a comma seperated string `"keywords": "keyword1,keyword2"` they get imported correctly. Is this not possible I already have the list?

**Comment by andrewgy8** [comment]
Is this an import JSON file specific issue? Or can this be generalized to csv, xls, etc.?
