### ISSUE TITLE
FileNotFoundError after importing thousand rows(13k)

### ISSUE THREAD

**Issue by RomartM** [django-import-export/django-import-export#807]
[FileNotFoundError at _admin_users_cuser_process_import_.pdf](https://github.com/django-import-export/django-import-export/files/2194970/FileNotFoundError.at._admin_users_cuser_process_import_.pdf)

**Comment by bmihelac** [comment]
Thanks for taking time  to fill this issue @RomartM. Does this happens every time and only for big files? Also does it happens when importing is confirmed?

**Comment by khaledeladl** [comment]
this happen to me too multiple times with small file 5K rows, other larger files didn't failed

**Comment by koedal** [comment]
This is happening for me too when I select the Confirm button. Doesn't happen every time. I've not noticed it on a file with 5k rows around 330kb in size and on a file with 18k rows around 3MB in size. I have two other files it hasn't happened for ever that are around 2k rows and 1.2 MB in size.

**Comment by zees-dev** [comment]
A suggested fix is to use CacheStorage - as stated in this solution: https://stackoverflow.com/a/42452966/10813908

As for me, i use django-import-export in admin panel, you can add the same attribute to the Meta class of a Resource:
```python
from import_export import resources
from import_export.tmp_storages import CacheStorage

class BookResource(resources.ModelResource):
    class Meta:
        model = Book
        tmp_storage_class = CacheStorage
```

**Comment by AdrianGolda** [comment]
Using cache storage casues me BadZipFile error. It works locally but not on AWS S3 bucket. So both not setting tmp_storage_class and setting it to CacheStorage give me errors :(

**Comment by matthewhegarty** [comment]
Is it possible you can create a new issue with enough detail so that we can look into it?
thanks

**Comment by matthewhegarty** [comment]
It shouldn't be an issue anymore if you use the latest version and consider how your store your files (more documentation [here](https://django-import-export.readthedocs.io/en/latest/faq.html#filenotfounderror-during-admin-import-confirm-step)).  If it's still an issue for you please raise a new issue (following the guidance [here](https://django-import-export.readthedocs.io/en/latest/contributing.html#guidelines-for-reporting-an-issue-feature)).

**Comment by matthewhegarty** [comment]
Correct doc link: [here](https://django-import-export.readthedocs.io/en/latest/admin_integration.html#customizable-storage)

**Comment by Natgho** [comment]
thanks for the explanation :)
