### ISSUE TITLE
Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead

### ISSUE THREAD

**Issue by tiholic** [django-import-export/django-import-export#829]
I'm facing this error on xlsx export

\venv\lib\site-packages\openpyxl\worksheet\worksheet.py:303: UserWarning: Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead
  warn("Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead")

Django 2.1
Py 3.6.1
django-import-export "dev"

**Comment by tarek-aec** [comment]
I solved this temporarily by downgrade to old versions:
```
tablib==0.10.0
openpyxl==2.4.0
django-import-export==1.0.0
```
by the way until new update fixing in [tablib](https://github.com/kennethreitz/tablib/tree/v0.12.1) deprecate version 0.12.1.

**Comment by bmihelac** [comment]
Is this still an issue with latest tablib?

**Comment by tiholic** [comment]
Issue was observed on 1.1.0 but not seen when using `-e git+https://github.com/django-import-export/django-import-export.git#egg=django-import-export`

Sorry for greatly delayed response

**Comment by tiholic** [comment]
@bmihelac Seems like issue is sorted out, not reproduced on 1.1.0 anymore with tablib 0.12.1

**Comment by tiholic** [comment]
```
....../venv/lib/python3.7/site-packages/openpyxl/worksheet/worksheet.py:303: UserWarning: Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead
  warn("Using a coordinate with ws.cell is deprecated. Use ws[coordinate] instead")
```

Noticed the issue again today with 1.1.0
