### ISSUE TITLE
Transactions are used for dry runs, even though they have been disabled

### ISSUE THREAD

**Issue by beruic** [django-import-export/django-import-export#830]
In the `Resource` class I fount the following line in the `import_data` method:

    using_transactions = (use_transactions or dry_run) and supports_transactions

Now why does it use transactions for dry runs whenever transactions are supported, even though I have opted to disable transactions completely?

I have some pretty big imports (200k+ objects) that take a really long time with transactions. Is there a deeper reason why the line does not just read the following?:

    using_transactions = use_transactions and supports_transactions

**Comment by bmihelac** [comment]
Hi @beruic and thanks for filling this issue.

If I remember the reason for using transactions in dry_run are foreign (and maybe m2m) relationships. Without transaction it would not be possible to assign foreign field to some model if this model missing pk.

**Comment by beruic** [comment]
@bmihelac But wouldn't import fail as well then?

**Comment by bmihelac** [comment]
Dry run and no transactions combo makes `save_m2m` no-op:

https://github.com/django-import-export/django-import-export/blob/54232db4a511cc5f0b085c6bb192c3619f27e452/import_export/resources.py#L345-L359

Surely as you noticed [this](https://github.com/django-import-export/django-import-export/blob/54232db4a511cc5f0b085c6bb192c3619f27e452/import_export/resources.py#L352-L354) currently never happens as dry_run is always wrapped in transaction.

I am thinking about refactoring `using_transactions = ...` line so it retain current behaviour but can be changed to not use transactions in dry run as well.

```python
using_transactions = supports_transactions and (
    use_transactions or
    (dry_run and self.use_transactions_in_dry_run())
)
```

Thoughts?

**Comment by beruic** [comment]
LGTM, but I guess it would be better if there was a non-transaction way to check constraints of the m2m.

**Comment by bmihelac** [comment]
@beruic would you like to write PR for this?

**Comment by beruic** [comment]
Would, if I could see time for it. Stuff is burning here, and unfortunately this is not a company priority issue anytime soon. Anyway, the solution you proposed aboev is your solution nevertheless. If that is what goes into the code, the PR is yours :)

**Comment by beruic** [comment]
@bmihelac I was too slow getting to this one. Didn't your fix above work fine? So shouldn't it just be merged?

**Comment by clint74** [comment]
It worked for me.
The whole process was about 40 minutes before change, now 5 minutes.
https://gist.github.com/clint74/bd74025e799bf7101a5471b08ecd1567

> Dry run and no transactions combo makes `save_m2m` no-op:
> 
> https://github.com/django-import-export/django-import-export/blob/54232db4a511cc5f0b085c6bb192c3619f27e452/import_export/resources.py#L345-L359
> 
> Surely as you noticed [this](https://github.com/django-import-export/django-import-export/blob/54232db4a511cc5f0b085c6bb192c3619f27e452/import_export/resources.py#L352-L354) currently never happens as dry_run is always wrapped in transaction.
> 
> I am thinking about refactoring `using_transactions = ...` line so it retain current behaviour but can be changed to not use transactions in dry run as well.
> 
> ```python
> using_transactions = supports_transactions and (
>     use_transactions or
>     (dry_run and self.use_transactions_in_dry_run())
> )
> ```
> 
> Thoughts?

**Comment by beruic** [comment]
@bmihelac can you reopen this one?

**Comment by matthewhegarty** [comment]
I would like to have a dry run, and also disable transactions.  Effectively I would like a mode where it doesn't touch the database at all, and just runs validation of the rows.  I don't think this is possible at present as described above.

Is it possible we can have the [PR](https://github.com/django-import-export/django-import-export/issues/830#issuecomment-419438950) which prevents transactions in dry run?
