### ISSUE TITLE
Not work in heroku  python-3.6.6 

### ISSUE THREAD

**Issue by jrujano** [django-import-export/django-import-export#831]
Mounting my app django in heroku I generate this error, it should be noted that in my virtualenv works perfectly

File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module

app [web.1]: return _bootstrap._gcd_import (name [level:], package, level)

  app [web.1]: ModuleNotFoundError: No module named 'import_export'

There is a user who presents the same error
https://stackoverflow.com/questions/46072246/modulenotfounderror-no-module-named-import-export
i have tried with
$ pip install django-import-export
pip install -e git+https://github.com/django-import-export/django-import-export.git#egg=django-import-export

**Comment by andrewgy8** [comment]
Hi @jrujano! Sorry no one has gotten back to you about this.  

Has this been resolved? 

If not, can you tell me what the out put of `pip list` is? And what version of django you are running?
