### ISSUE TITLE
Help block for import.html template

### ISSUE THREAD

**Issue by pacahon** [django-import-export/django-import-export#838]
I have some fields in my import workflow which should be converted into db representation first. For example:
```python
COURSES = (
    (1, 'bachelor 1'),
    (2, 'bachelor 2'),
    (3, 'master degree 1'),
    ...
)
course = models.PositiveSmallIntegerField(
    _("Course"),
    choices=COURSES)
```

It's really not easy to keep in mind all of these `bachelor 1`, etc. And I want to show some kind of help block on admin import form. 
```
This importer will import the following fields: ...
Note:
`course` column should be one of ['bachelor 1', ... ]
```

Right now I can do it with customization `import_template_name` path in model admin. But it needs to copy the whole template and add text in appropriate place. Next time I update `django-import-export`, I should remember that my templates could be broken and have to check/fix all of them.
How about to add empty block `import_action_help_block`? In this case it would be really easy to add help info and not to worry about compatibility:

```
# import.html
...
    <p>
      {% trans "This importer will import the following fields: " %}
      <code>{{ fields|join:", " }}</code>
    </p>
    
    {% block import_action_help_block %}{% endblock import_action_help_block %}

    <fieldset class="module aligned">
...


# import_users.html
{% extends "admin/import_export/import.html" %}

{% block import_action_help_block %}
Note:
`course` column should be one of ['bachelor 1', ... ]
{% endblock import_action_help_block %}
```

**Comment by DmytroLitvinov** [comment]
Just had the same case as described in the ticket where I need to specify encoding of the import.
Any chance that the issue can be reopened?

**Comment by matthewhegarty** [comment]
hi
What version of django-import-export are you using?  Please ensure using latest stable version (3.3.7) and consider upgrading to [v4 rc1](https://pypi.org/project/django-import-export/4.0.0rc1/).

**Comment by DmytroLitvinov** [comment]
Yes, we are using [v3.3.7](https://pypi.org/project/django-import-export/3.3.7/) (latest stable one from PyPI).

**Comment by matthewhegarty** [comment]
Thanks - I've opened the issue.  If you felt like submitting a PR it would be most welcome.

**Comment by DmytroLitvinov** [comment]
Sure, @matthewhegarty .

Will that work for us? 
<img width="917" alt="image" src="https://github.com/django-import-export/django-import-export/assets/16066485/32ac0c06-52f4-4d0f-86de-febf3aab434f">

**Comment by matthewhegarty** [comment]
Can you test it with the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?

**Comment by DmytroLitvinov** [comment]
Working on preparing PR.

**Comment by matthewhegarty** [comment]
Thanks - might be an idea to run the example app and check that you can override the block successfully

**Comment by DmytroLitvinov** [comment]
@matthewhegarty , opened PR to fix that issue  - https://github.com/django-import-export/django-import-export/pull/1776

**Comment by matthewhegarty** [comment]
Please can you demonstrate how to override the new block using the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?  I have tried but have not been successful.

**Comment by DmytroLitvinov** [comment]
Hi @matthewhegarty ,
I see you merged the MR.
Sorry for the late response, everything was fine?

**Comment by matthewhegarty** [comment]
Hi
Yes - happy to merge it.  I tried to test by overriding the template in the example app, however I couldn't do it and gave up!

**Comment by matthewhegarty** [comment]
Release in [3.3.8](https://pypi.org/project/django-import-export/3.3.8/).
