### ISSUE TITLE
Wasting Primary Key ID's

### ISSUE THREAD

**Issue by aashishgahlawat** [django-import-export/django-import-export#846]
In case if you try to import a CSV file using `ImportExportModelAdmin `

say I have a Django modes named `PRODUCTS `as:
```
product_id (pk)     name (char)         size (char)   etc...
1                           milk                     500ml
2                           bread                  Large
```

`admin.py` looks like:

```
class ProductAdmin(ImportExportModelAdmin):
    resource_class = ProductResource

admin.site.register(Product, ProductAdmin)
```

`resource.py`  that holds `ProductResouces `class look like:

```
class ProductResource(resources.ModelResource):
    class Meta:
        model = Product
        import_id_fields = ['product_id']
        skip_unchanged = True
        report_skipped = True
        use_transactions = True
```

and the issue is with uploading CSV file without `product_id`:

the CSV file looks like:

```
product_id (pk)     name (char)         size (char)   etc...
                            fresh milk              500ml
```

**Note:** Here I haven't passed the `product_id`.
So when I do import from my Django admin, it shows data as:

```
product_id (pk)     name (char)         size (char)   etc...
3                           fresh milk             500ml
```

Probably it get this primary key returned from database **(MYSQL)** and then shows confirm import button on chick of which the record I have is:
`4                           fresh milk             500ml`

**the id imported is 4 rather than 3.**

I have 
`IMPORT_EXPORT_USE_TRANSACTIONS = True in settings.py`
also have tried to make `use_transactiosn = False` in both `settings.py` and in `resources.py` and alternative combinations, still it wastes `1` `primary key id` in database whenever I don't pass a primary key in my csv file

**Comment by aashishgahlawat** [comment]
Am using `Django 2.0.2` and  `Python 3.6`

**Comment by zmaximo1990** [comment]
I'm using `Django 2.1.5` and got the same error.

When i confirm the import, the inserted rows's id are increased one more than the confirm screen shows me.

Any suggestions?
<img width="1212" alt="1" src="https://user-images.githubusercontent.com/7076329/52688395-1266a600-2f35-11e9-96f6-49d591ba5671.png">
<img width="1079" alt="2" src="https://user-images.githubusercontent.com/7076329/52688398-1266a600-2f35-11e9-90e9-05988579e759.png">

**Comment by bmihelac** [comment]
Please see https://github.com/django-import-export/django-import-export/issues/560#issuecomment-270673979

**Comment by andrewgy8** [comment]
Relevant bit of text here from #560 :

> These only ever increase, and they're exempt from the usual transaction rollback rules to permit multiple transactions to grab new IDs at the same time. This means that if a transaction rolls back, those IDs are "thrown away"; there's no list of "free" IDs kept, just the current ID counter. Sequences are also usually incremented if the database shuts down uncleanly.
