### ISSUE TITLE
Automatically pick correct widget for ModelResource fields

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#868]
Hi,

You have a Resource class that is based on ModelResource.
You specify a field with the attribute and column_name mappings, but NO widget.

The result is that even when the django field is a (let's say) DecimalField, you will end up with a plain Widget and not the DecimalWidget. This is decided here:
https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L673

We would need some variable to track that we are using Widget because widget parameter was not specified, here: https://github.com/django-import-export/django-import-export/blob/master/import_export/fields.py#L41

Then we could use field_from_django_field for those declared fields which do not specify a widget.

That would make Resources easier to specify, and more natural for beginners. It is currently failing for me because DecimalField would not accept '' as a valid number. Setting DecimalWidget manually in the field fixes the problem, but it is too verbose.

@bmihelac would you accept a PR for this improvement?

**Comment by bmihelac** [comment]
Hi @manelclos,

just to check that we talk about same things, would this be proper example:

```python
class BookResource(resources.ModelResource):
    price = fields.Field(column_name='product_price', attribute='price')

    class Meta:
        model = Book
```

for Book model as is specified here:
https://github.com/django-import-export/django-import-export/blob/master/tests/core/models.py#L30-L42

**Comment by manelclos** [comment]
Yes, exactly.
