### ISSUE TITLE
Export as xlsx returns 500 error

### ISSUE THREAD

**Issue by Eliottiosdevs** [django-import-export/django-import-export#872]
Hello, 

Very nice project, only having one problem. 
`cell() missing 1 required positional argument: 'column'`

I don't think the problem is on my end, seems related to #817 
Any updates on this?

**Comment by felocru** [comment]
The latest release does not have the update yet :/

**Comment by fmatray** [comment]
I also have the problem :'(

**Comment by andrewgy8** [comment]
FYI #801 Addresses this

**Comment by bmihelac** [comment]
thanks for reporting, this should be fixed in 928ec9f

**Comment by Eliottiosdevs** [comment]
Thanks!
