### ISSUE TITLE
How to make class heritage with ModelResource

### ISSUE THREAD

**Issue by ZuluPro** [django-import-export/django-import-export#877]
Hello,

How to make class heritage with ModelResource ?

A basic heritage with redefinition of Meta will include all fields from the parent resource.
Even if I put `Meta.fields` & `Meta.export_order`. It will just put them at the end.

**Comment by andrewgy8** [comment]
Hi @ZuluPro! I'm not sure I follow. Could you provide a code snippet that could help define the issue?

**Comment by ZuluPro** [comment]
Hello @andrew-bro 
Yes sorry, no problem.

```
class Parent(resources.ModelResource):
    class Meta:
        fields = export_order = ['username', 'last_name', '']

class Child(Parent):
    class Meta:
        fields = export_order = ['username', 'first_name']
```

The Child resource will produce a table with `'last_name`' as last column. Even if it's define to just show `['username', 'first_name']`.

**Comment by andrewgy8** [comment]
I see. And Im sorry to say, I'm not sure why that happens 😞 

But a way that I have been able to solve it in other situations (models, admin,, serializers, etc.) is to use a common constant defining the fields that you would like to have in each resource, and then concatenating the lists together with the specific fields for each resource.

**Comment by ZuluPro** [comment]
Hi @andrewgy8 

I think I experienced the same thing with `django.forms.ModelForm` and maybe `django_tables2.tables.Table`.

They all have in common to use meta-classes...

**Comment by andrewgy8** [comment]
I'm going to close this unless someone can show this is django-import-export specific issue.

**Comment by ZuluPro** [comment]
I think it's mandatorily related to django-import-export. Even the other objects have the same behavior doesn't mean import-export shouldn't improve it.

**Comment by andrewgy8** [comment]
Are you suggesting we solve a feature/bug in the way Python handles Meta class attribute inheritance? 

I'm of the opinion that its out of the scope of Django Import Export.
