### ISSUE TITLE
ConfirmImportForm should include custom form fields sent by ImportForm

### ISSUE THREAD

**Issue by yozlet** [django-import-export/django-import-export#879]
_**Caveat:** I'm new to Django Import/Export, so please correct me if I have the wrong ideas about the best ways of doing this._

My first use of DI/E required importing a file that was (deliberately) missing a column, with the intention of providing the extra column value in the import form. Eventually I worked out (what I _think_ is) a good way of doing this, as [I explained to someone else having the same problem](https://github.com/django-import-export/django-import-export/issues/758#issuecomment-443918300) - and then [someone else](https://stackoverflow.com/questions/52335510/extend-django-import-exports-import-form-to-specify-fixed-value-for-each-import/53607729#53607729), and [someone else](https://stackoverflow.com/questions/36918074/extending-the-admin-import-form-for-django-import-export/53642164#53642164). In other words, it's a pretty common problem.

But the use of sessions is messy, and may lead to weird bugs. It'd be better if `ConfirmImportForm` carried across _all_ form fields by default, including custom ones. Alternatively, if there was a way to specify which extra form fields to include. Another alternative is #880, which would require more work from implementers but would allow much more flexibility.

**Comment by mgrdcm** [comment]
Hey there!  So I'm doing a similar thing with no modifications to DIE and without using sessions, but it's a bit hacky.  I'll post what I'm doing later.

Here's what I'm hoping to do long-term, let me know how this sounds to you - a new `import_export.fields.Field` subclass that is basically a prompt with a Django Form widget and pulls the value from that prompt instead of an actual column.  Basically a synthetic column.  Then to add this all you'd have to do is add like
```python
prompted_column = import_export.fields.PromptField(column_name="Yes or No or Maybe", form_widget=django.forms.widgets.NullBooleanSelect())
```
and then that would show up as like "Yes or No or Maybe: ..." on the import form.

**Comment by yozlet** [comment]
@mgrdcm I like it! Looks like a neat, easy way to add form fields (as optional columns) to the process. If it's not in your design already, I recommend adding a parameter that defines whether the field is only used for import, or export, or both.

And yes, I'm definitely interested in hearing your slightly hacky alternative to using sessions. I'm sending my code to production, so any alternatives that are less likely to produce horrible bugs would be very useful.

**Comment by mgrdcm** [comment]
Hey!  Sorry about that.  I'm having to dedicate all my time to getting a project ready first. Should be able to work on this over the weekend though!

**Comment by Wolverine7** [comment]
@mgrdcm Hi. Any progress? I am also very interested to see this feature

**Comment by yozlet** [comment]
@mgrdcm What @Wolverine7 said. Instead of a full implementation, how about a 1 minute description of the hack, and we can work out the specifics from there? (I'm putting my money on something to do with `kwargs` being passed through the view.)
