### ISSUE TITLE
Importing Many2Many Widget with its own foreing key to another table

### ISSUE THREAD

**Issue by chadquilter** [django-import-export/django-import-export#881]
python3.6, Django2

I am having issues getting the import to work with a many2many field that is in turn using its own foreign key for a dropdown of a common names table shared by a few other tables (which are also having this problem). 

My model structure is thus:
* Master Collection <-- master record using names from sub tables
    ^     |   ^    |    ^         <--- sub tables (m2m) using name from name table
*table1 | *table2 | *table3
                V <---sub-sub table (foreign key) all using name table 
           *Names Table 

Here is an example of one of my widgets in the resource class:
    collection_creator = fields.Field(
        column_name='collection_creator',
        attribute='collection_creator',
        widget=ManyToManyWidget(Creator, ';', 'creator_name'))

The model Creator has a column called creator_name and that is a foreign key to a master name list.
It works great on export, and all m2m lists are delimited just fine. However on import I get an error:

"...invalid literal for int() with base 10..."

This works fine on a normal m2m with no foreign key lookup, so I'm guessing it has trouble doing a deeper reverse lookup when a foreign key is involved stopping at the relationship table? Is there any work around or hack I can perform on the m2m widget or do I need to modify it to look deeper? 

Thanks for making this tool, its very handy!

**Comment by chadquilter** [comment]
Just replying for anyone wanting to find out how to get a m2m with a foreign key to work on imports. I over-rode the init and clean methods for the manytomanywidget and statically set the return for the object filter with the next depth table I needed to add the connection with. 

I need to modify this to take an additional argument but here is the idea in practice for anyone that just wants to plug and play this. Put this in your admin model:

class M2MForeignKeyWidget(ManyToManyWidget):
(self, model, separator=None, field=None, *args, **kwargs):
        if separator is None:
            separator = ','

        if field is None:
            field = 'pk'

        self.model = model
        self.separator = separator
        self.field = field
        super(ManyToManyWidget, self).__init__(*args, **kwargs)

    def clean(self, value, row=None, *args, **kwargs):
        if not value:
            return self.model.objects.none()

        if isinstance(value, (float, int)):
            ids = [int(value)]
        else:
            ids = value.split(self.separator)
            ids = filter(None, [i.strip() for i in ids])
       ### This is what needs to be changed to add additional table relations __ForeignTableColumn__
      ### in a real implementation you would add the ability to add this as an argument and pass it
        return self.model.objects.filter(**{
            '%s__ForeignTableColumn__in' % self.field: ids
        })

Make sure and update the __ForeignnTableColumn__ to whatever is column you're trying to map to, 
then in you're resource class where you would normally use the fields.field( widget use the M2MForeignKeyWIdget instead of the ManyToManyWidget.

Anyway, just thought I would pass along....

**Comment by tjaegerpca** [comment]
Thank you for posting the fix!
I am having an issue, and can't quite understand why I'm having trouble... 
I replaced the string 'ForeignTableColumn' with 'users' as so:           
```
return self.model.objects.filter(**{
                '%s__users__in' % self.field: ids
            })
```
```
class myResource(resources.ModelResource):
    assigned_manager = Field(
        column_name='Assigned Manager',
        attribute='assigned_manager',
        widget=M2MForeignKeyWidget(User, 'username')
    )
   class Meta:
      model = myModel
      
```

And am getting the error:
Unsupported lookup 'users' for AutoField or join on the field not permitted.

Could you help me understand what I am missing?

**Comment by andrewgy8** [comment]
Thanks @chadquilter for the update! Im sure it will help someone in the future.  

I will close this issue since it seems to be resolved.
