### ISSUE TITLE
Why does BooleanWidget not behave like other widgets?

### ISSUE THREAD

**Issue by yozlet** [django-import-export/django-import-export#883]
The pattern for other Widgets and their role in Fields:

1. `clean()` raises `ValueError` if the `value` is an invalid type or string format
2. Users set a column's default value in the Field

Both of the above are great design choices, as they make it easy for the user to differentiate between valid values, invalid values and nulls. If the user wants to treat an invalid value as a null, they can subclass the widget without reimplementing all its functionality:

```python
class MyDateWidget(DateWidget):
	def clean(self, value, row=None):
		try:
			return super().clean(value)
		except ValueError:
			return None
```

However, with BooleanWidget:

1. `clean()` treats all unknown types and string formats as `False` unless they're recognised as `null`
2. Users can't change this `False` default (though they can change how `null` is interpreted)

And this takes away the user's ability to differentiate valid from invalid values, and in turn, their choice of how invalid values are treated. Worse, this aspect of BooleanWidget's behaviour isn't discussed in the documentation.

I realise that BooleanWidget's behaviour has been in place long enough that many users now depend on it, so it can't be changed easily. But maybe it could be deprecated in favour of a differently-named Widget (`BoolWidget`? `StrictBooleanWidget`?) which also has more options (like those mentioned in #325).

**Comment by andrewgy8** [comment]
Hey @yozlet ! Thanks for bringing this up.

What do you propose the "new" widget's API would look like? Would it be more relaxed about false values? More configurable? 

Or do you think that a documentation change would suffice? Describing its current behavior and how one could implement their own widget for their own needs?
