### ISSUE TITLE
Resize very large files for confirm view

### ISSUE THREAD

**Issue by jab3z** [django-import-export/django-import-export#89]
Hi!

As I will upload very large files, for confirm view I would like resize it, and read just the first 20-30 entries which will be displayed in the Preview. I know I have to monkey patch import_action, but which would be the approach from cutting the file and still have support for all provided formats? I don't want to write a case for each one separately.

After the user confirmation I will assign the processes to a worker.

Regards,
Dacian

**Comment by alaw005** [comment]
I have a 2.8MB file with 53,000 rows and 28 columns of data but while waiting to import kills the django development service (version 1.4). I can import 2,000 rows ok. Is there a way that import-export can upload the file and then process it with a separate worker?

**Comment by mightygraf** [comment]
same problem here
