### ISSUE TITLE
Add an extra dropdown option on the admin page?

### ISSUE THREAD

**Issue by Wolverine7** [django-import-export/django-import-export#899]
Hi,

First of all, thank you very much for the package; it works great. 

I was wondering if we can modify an admin page to add an extra drop down option field? Please find attached picture that shows what I am talking about.

That would automatically populate the import field with the month picked

<img width="1175" alt="djangoimportexport" src="https://user-images.githubusercontent.com/8800283/51628223-0f663000-1f0a-11e9-894b-419b26f08847.png">

**Comment by andrewgy8** [comment]
Hey there @Wolverine7! If I understand this correctly, it would be like dynamic default field? Is that right?

**Comment by Wolverine7** [comment]
Yes. I have a month choice field inside of my model.py (please find attached screenshot). Which I have to include in my import csv document. I was wondering if instead, I could have a dynamic field with months listed and upon the choice, it would fill the column based on the value from dropdown field during the import.

<img width="809" alt="screen shot 2019-01-30 at 3 26 27 pm" src="https://user-images.githubusercontent.com/8800283/52013912-deef3a80-24a3-11e9-94e1-a28c9d8597f6.png">

<img width="300" alt="screen shot 2019-01-30 at 3 34 17 pm" src="https://user-images.githubusercontent.com/8800283/52014213-96844c80-24a4-11e9-8252-03d657d37484.png">

**Comment by andrewgy8** [comment]
Something like what is discussed [here](https://github.com/django-import-export/django-import-export/issues/879)?

**Comment by Wolverine7** [comment]
@andrewgy8 Yes. But I am not sure if they had any luck with that

**Comment by Wolverine7** [comment]
@yozlet  Thank you for your response. Could you share your code for the second approach?

**Comment by yozlet** [comment]
@Wolverine7 I've updated [that comment](https://github.com/django-import-export/django-import-export/issues/758#issuecomment-443918300) with the improved code, and also fixed a recurring typo. Thanks for that!

**Comment by Wolverine7** [comment]
@yozlet your code worked great! However, the export fails after that with the following error 

![screen shot 2019-02-09 at 7 43 16 pm](https://user-images.githubusercontent.com/8800283/52528376-fea41100-2ca2-11e9-8346-4dac11867bbd.png)

**Comment by yozlet** [comment]
@Wolverine7 Not enough info in that screenshot for me to help you, alas. Could you post a gist with some of the code you wrote for this? Especially:
 * `get_resource_kwargs()`
 * the `ImportForm` subclass
 * if possible, your `Author` model
