### ISSUE TITLE
Provide meaningful string representation for results.Error

### ISSUE THREAD

**Issue by elbenfreund** [django-import-export/django-import-export#900]
**Is your feature request related to a problem? Please describe.**
When dealing with error, I feel that a ``str(error_instance)`` should give me some idea about the nature of the error, aka show ``Error.error``.

**Describe the solution you'd like**
Provide ``Error.__str__`` that returns ``Error.error``. One could think about including row information but I do not have a strong opinion on that one tbh.

**Describe alternatives you've considered**
Obviously it is possible to be verbose and call ``error_instance.error``.
However, besides being verbose this requires the caller to know the attribute name where the actual error is stored.

**Comment by alexmndzdev** [comment]
I did this to show the errors, maybe is useful:
```
if result.has_errors() == False:
    response = []
    index_row = 0
    for row in result.rows:
        index_row = index_row + 1
        for error in row.errors:
            messages = []
            for array_error in error.error:
                if (isinstance(array_error, str)):
                    messages.append(array_error)
                else:
                    messages.append(array_error[0].upper()+': '+array_error[1][0])
            response.append({'index': index_row, 'message' : messages})
response.append({'total': result.totals}) #This contains the result of records addeds and updateds
return HttpResponse(json.dumps(response), status = 400, content_type = 'application/json')
```

**Comment by andrewgy8** [comment]
Thanks you two for bringing this to our attention! 

I too agree that the error handling can be improved. Do either of you feel up to the challenge to submit a PR to improve this?

**Comment by elbenfreund** [comment]
@andrewgy8 I would be willing to submit a PR if noone else is eager to do this. I would not be able to commit to a dedicated timeline though, which given the low impact nature of this issue is probably fine :)

**Comment by andrewgy8** [comment]
@elbenfreund No worries! Anything you contribute will be more than welcome.
