### ISSUE TITLE
change_list.html is overriding too much

### ISSUE THREAD

**Issue by alexandernst** [django-import-export/django-import-export#901]
Currently the `change_list.html` template is overriding too much of the HTML. It shouldn't be enforcing classes because that collides with look&feel apps like grappeli.

I suggest changing the code to something like:

```
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
  {% if has_add_permission %}
    {% include "admin/import_export/change_list_import_item.html" %}
    {% include "admin/import_export/change_list_export_item.html" %}
  {% endif %}
  {{ block.super }}
{% endblock %}
```

**Comment by bmihelac** [comment]
@alexandernst thanks, would you like to make a pull request?

**Comment by jdramirezr** [comment]
@alexandernst this is good solution when you use change_list_template, thanks!

**Comment by matthewhegarty** [comment]
`change_list.html` was [modified in release 3.0.0](https://github.com/django-import-export/django-import-export/blob/2086267a5872afcd28a13c90ed158157ea6b1949/import_export/templates/admin/import_export/change_list.html#L1)
