### ISSUE TITLE
'enter a valid date' error

### ISSUE THREAD

**Issue by skystone011** [django-import-export/django-import-export#910]
When import the date column like '20190212', it failed, the error is "ValueError: Column 'cr_date': Enter a valid date.".
Can we handle this type of date? or should i always convert the date to '2019-02-12' to import?
thank you for response.

**Comment by bmihelac** [comment]
Did you check docs for DateWidget?

https://django-import-export.readthedocs.io/en/latest/api_widgets.html#import_export.widgets.DateWidget

**Comment by skystone011** [comment]
Thanks, i'll check it !
