### ISSUE TITLE
How do I access the row values when importing a file with Django Import-Export ?

### ISSUE THREAD

**Issue by GiannisIordanou** [django-import-export/django-import-export#911]
I am importing a file with django import-export and I want to take the values of each row.

Specifically, a user chooses a file to upload through a form and a ajax call, then I read it and load it to a tablib dataset and then I use a resource to import its content in my database.

I get the validation errors if they exist but I can't get the values of each row.

My aim is to to present the data and any errors might occur in a table on the front end for the user to preview.

For example:

    import_file = request.data['importedFile']
    import_resource = ImportResource()
    dataset = Dataset()
    imported_data = dataset.load(import_file.read().decode('utf-8'))
    result = import_resource.import_data(dataset, dry_run=True)

I iterate through the rows of the Result with result.rows and each row seems to have a raw_values property but it returns empty.

**Comment by andrewgy8** [comment]
Hi @GiannisIordanou !

According to the [Tablib docs](http://docs.python-tablib.org/en/master/tutorial/#importing-data), you need to open the file before reading and loading the data. Have you tried that? 

`imported_data = dataset.load(open(import_file).read().decode('utf-8'))`

**Comment by GiannisIordanou** [comment]
The thing is I purposely use a file with errors, so I can see how it all works. The validation errors for each row if exist they get returned correctly.

I will try opening the file before loading, and I will see if it gets fixed.

**Comment by GiannisIordanou** [comment]
Hello @andrewgy8 ,

I have updated my issue with a bit more details. I have tried what mentioned earlier and I get the following error: 

`TypeError: expected str, bytes or os.PathLike object, not InMemoryUploadedFile`

**Comment by andrewgy8** [comment]
Its hard to say without knowing what your dataset looks like. Could you share a couple of lines?
