### ISSUE TITLE
How to edit tablib.Dataset before InvalidDimensions error?

### ISSUE THREAD

**Issue by juju4Life** [django-import-export/django-import-export#917]
I'm receiving the following error when trying to upload a csv file:

> InvalidDimensions encountered while trying to read file

I know that this is a tablib error, and due to the fact that I have empty lines between each row in my csv, as well as blank lines at the end of file. I want to gain access to the dataset before the import to format it properly. I've tried overriding the import_obj, before_import and before_import_row methods, but that doesn't seem to work. None of the other methods seems to work either.

admin.py

    class UpdateResource(resources.ModelResource):
        def before_import_row(self, row, **kwargs):
            print(row)
I've just been trying to find the correct method to use before the error. I've had no luck gaining access to the tablib.Dataset resource before the error.

I've tried sub-classing the `ImportExportMixin` class, but I have no idea if this is even the way to go, or to how go about gaining access to the Dataset before the format of the csv is checked.

admin.py

    class UploadAdmin(ImportExportMixin, TablibFormat, admin.ModelAdmin):
            def import_action(self, request, *args, **kwargs):
                # Do something to gain access to the tablid.Dataset, or csv before it is read
                return super(UploadAdmin, self).import_action(request, *args, **kwargs)

How can I gain access to, and change the tablib.Dataset, or the csv file's format

**Comment by andrewgy8** [comment]
Hey @juju4Life ! Did you have a chance to figure this out? 
I was thinking about this, and figured there might be a way to check the existence of data in the row in the `before_import_row` function of the Resource class. 

The pseudocode would look something like this:
```
class UpdateResource(resources.ModelResource):
    def before_import_row(self, row, **kwargs):
        if row is empty:
             raise Exception
```
and you would have to make sure that [`raise_errors` is `False` which it is by default](https://django-import-export.readthedocs.io/en/latest/import_workflow.html#import_data).

This should allow you to "skip" the rows that are blank. 

The other way would be to override the behavior of `import_row`  on the resource class and `pass` when the row is empty.  This way may be more graceful.
