### ISSUE TITLE
update record with request user info before import row

### ISSUE THREAD

**Issue by daysleeper1980** [django-import-export/django-import-export#919]
How can we update a column with request user info at before_import_row stage?

I try to use   def get_import_resource_kwargs(self, user, *args, **kwargs):
    return self.get_resource_kwargs(user, *args, **kwargs) in order to use at before_import_row but i cant get any user info at there

**Comment by andrewgy8** [comment]
Hey @daysleeper1980 !

By "request user info", you mean the admin user info? 

What I think you can do, although untested, is pass the request into `import_data(dataset, dry_run, raise_errors, use_transactions, collect_failed_rows, request=request)`.  Then it should be accessible in `before_import_row` as `request.user`. 

Let me know how that goes.  And if you can, could you paste all the relevant code here.

**Comment by daysleeper1980** [comment]
hey andrew,

infact i already solved it like the way you said,just it needs to be request.user not request itself

thanks  a lot for your response

**Comment by samirhinojosa** [comment]
@daysleeper1980 Hi!

could you pass how you solved it?

**Comment by daysleeper1980** [comment]
Hi,

As i said you can set dataset with the value you want to update like
`import_data(dataset, dry_run=False,raise_errors=True)`

and after that at:
`def before_import_row(self, row,**kwargs):` 
you can just use kwargs to update

**Comment by templargin** [comment]
@daysleeper1980 @samirhinojosa 

Guys, I am having the same issue.
I was able to retrieve user from ```kwargs```

But then I struggle with the next step.
I've tried something like this: ```row.fields['created_by'] = user```. It does not work.

Can you point out the way of updating the field of the row?

Thank you!

**Comment by daysleeper1980** [comment]
Hİ @templargin ,

let's say you want to update a password of a customer and also change the status,you can use the syntax below 

```
        obj = CustomUser()
        obj.set_password("1234")
        row['password'] = obj.password
        row['is_active'] = True
```

**Comment by templargin** [comment]
@daysleeper1980 Thank you for actually getting back on this! Are you sure this is the way you implemented it?

I am getting the ```'ContactResource' object does not support item assignment``` error.

View:
```
def imported_contacts(request):
    if request.method == 'POST':
        contact_resource = ContactResource()
        dataset = Dataset()
        new_contacts = request.FILES['imported_contacts']

        imported_data = dataset.load(new_contacts.read().decode('utf-8'),format='csv')

        result = contact_resource.import_data(dataset, user=request.user, dry_run=True, raise_errors=True)

        if not result.has_errors():
            print(imported_data, file=sys.stderr) # this actually prints, which means no errors
            contact_resource.import_data(dataset, user=request.user, dry_run=False)

    return HttpResponseRedirect(reverse('contacts:contact_list'))
```

Here is my ```resource``` class:
```
class ContactResource(resources.ModelResource):

    created_by = fields.Field(
        column_name='created_by',
        attribute='created_by',
        widget=ForeignKeyWidget(User, 'email'))

    class Meta:
        model = Contact
        skip_unchanged = True
        report_skipped = True
        exclude =('is_active')

    def before_import_row(row, *args, **kwargs):
        user = kwargs.pop('user', None)
        print(user.email, file=sys.stderr) # this is to confirm kwargs pull the right value, which it does

        row['created_by'] = user.email
```

And this is an example of .csv file:
```
first_name,last_name,id
Bob,Dylan,
```

For example, if I remove ```before_import_row``` part from my resource and add ```created_by``` field to .csv file:
```
first_name,last_name,created_by,id
Bob,Dylan,example@gmail.com(e-mail of current user)
```
everything works, and current user then sees the contacts.

I've also tried using ```setattr(row, 'created_by', user.email)``` instead of ```row['created_by'] = user.email```, that did not work either.

Any help would be appreciated, thank you!
