### ISSUE TITLE
when import csv file ,KeyError: u'id' occured

### ISSUE THREAD

**Issue by zhijiasun** [django-import-export/django-import-export#92]
i try to import some data form csv file, but errors occurred as follows:

Errors
    Line number: 1 - u'id'
    Traceback (most recent call last):
    File "/home/zhijiasun/.virtualenvs/tutorial/local/lib/python2.7/site-packages/import_export/resources.py", line 317, in import_data
    instance, new = self.get_or_init_instance(instance_loader, row)
    File "/home/zhijiasun/.virtualenvs/tutorial/local/lib/python2.7/site-packages/import_export/resources.py", line 149, in get_or_init_instance
    instance = self.get_instance(instance_loader, row)
    KeyError: u'id'

I just modify the data of the csv file which exported by the app and then try to import it. But error happed.

**Comment by Hiieu** [comment]
It doesn't works for me

```python

class SignUpResource(resources.ModelResource):
    class Meta:
        model = SignUp
        exclude = ('id','gender','timestamp', )
        import_id_fields = ['id','gender','timestamp',]
```

I still have same error.

**Comment by fiterbek** [comment]
You are excluding the 'id' field as well as telling django to use it for importing objects. That can't work imho. 
I think you need to at least remove the id field from exclude, and put only the id field in import_id_fields. But if id is the primary key for your object, you shouldn't have to do anything custom. It's hard to tell without more code (of your model, specifically).

**Comment by jcsimonin** [comment]
Hey, check the separator in your import file. Should be a comma!
In my case the error was the csv file.
The file was also an export that i tried to import directly (for test).
My exported csv file had a semicolon as separator and not the expected comma...

**Comment by harshit0agrawal** [comment]
I figured it out that if you don't have an 'id' field in your model one can assign
`import_id_fields=['some_other_field']` in class Meta of ModelResource and upload a file without the id field. It worked quite smoothly for me.

**Comment by sha12** [comment]
I am still facing key error even though I updated "import_id_fields"
error:
```
Line number: 1 - 'NoneType' object has no attribute 'DoesNotExist'
1236, sdkfk, Rack3, FSMF, FXEB+FRGT+FXDB, 4567, plain, Working, No issues, None pending, Checking import , ,
Traceback (most recent call last):
File "D:\Python35\lib\site-packages\import_export\instance_loaders.py", line 31, in get_instance
field = self.resource.fields[key]
KeyError: 'SBTS_ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\Python35\lib\site-packages\import_export\resources.py", line 434, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "D:\Python35\lib\site-packages\import_export\resources.py", line 258, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "D:\Python35\lib\site-packages\import_export\resources.py", line 252, in get_instance
return instance_loader.get_instance(row)
File "D:\Python35\lib\site-packages\import_export\instance_loaders.py", line 34, in get_instance
except self.resource._meta.model.DoesNotExist:
AttributeError: 'NoneType' object has no attribute 'DoesNotExist'
```
Model
```
class Testlines(models.Model):
     SBTS_ID=models.CharField(max_length=20,primary_key=True)
     Owner=models.CharField(max_length=50)
     Rack = models.CharField(max_length=50)
     Hw_config= models.CharField(max_length=200)
     Radio_modules = models.CharField(max_length=200, default="FXEB+FRGT+FXDB")
     SBTS_Build= models.CharField(max_length=200)
     Setup_config = models.CharField(max_length=200)
     Calls = models.CharField(max_length=200)
     Issues = models.CharField(max_length=200)
     Investigations = models.CharField(max_length=200)
     Status_Comments = models.TextField()
     lastmodifiedon = models.DateTimeField(default=None,null=True)
     lastmodifiedby = models.CharField(max_length=100,null=True,blank=True,default=None)
```

Resources
```
class TestlinesResource(resources.ModelResource):
    class Meta:
        Model = Testlines
        import_id_fields=['SBTS_ID']
```
my csv file
**SBTS_ID  	Owner	Rack	Hw_config	Radio_modules	SBTS_Build	Setup_config	Calls	Issues	     Investigations	         Status_Comments	lastmodifiedon	lastmodifiedby**
1236  	sdkfk	Rack3	FSMF	                 FXEB+FRGT+FXDB	   4567	                     plain	                Working	 No issues	None pending	Checking import 		

please help

**Comment by shaggyfrog** [comment]
> `Model = Testlines`

That should be `model`

**Comment by sha12** [comment]
my bad.   thanks for your time shaggyfrog !

**Comment by DaveJ61** [comment]
I have read just about everything about this problem and I have been trying to eliminate this for nearly 2 days.
I have tried all sorts of combinations to try and get this running but have failed.

`from django.contrib import admin`
`from import_export import resources`
`from import_export.widgets import ForeignKeyWidget`
`from import_export.admin import ImportExportModelAdmin`
`from models import Item`

`class ItemResource(resources.ModelResource):`
    `class Meta:`
        `model = Item`
        `import_id_fields = ['item_id', 'partcode', 'manufacturer', 'description', 'quantity', 'reorderquantity', 'minquantity', 'maxquantity', 'cost', 'rrp', 'category',]`
        `fields = ('barcode', 'partcode', 'manufacturer', 'description', 'quantity', 'reorderquantity', 'minquantity', 'maxquantity', 'cost', 'rrp', 'category',)`
        `#exclude = ('id',)`


KeyError: 'item_id'
ERROR:root:'item_id'
Traceback (most recent call last):
  File "/home/david/projects/trc/venv/local/lib/python2.7/site-packages/import_export/resources.py", line 440, in import_row
    instance, new = self.get_or_init_instance(instance_loader, row)
  File "/home/david/projects/trc/venv/local/lib/python2.7/site-packages/import_export/resources.py", line 262, in get_or_init_instance
    instance = self.get_instance(instance_loader, row)
  File "/home/david/projects/trc/venv/local/lib/python2.7/site-packages/import_export/resources.py", line 256, in get_instance
    return instance_loader.get_instance(row)
  File "/home/david/projects/trc/venv/local/lib/python2.7/site-packages/import_export/instance_loaders.py", line 31, in get_instance
    field = self.resource.fields[key]

I have tried with or without an id column in both csv and xlsx files. I have tried using import_id_fields. I even created an item_id field in my database even though I shouldn't need one as another filed is the primary key. I am finding the documentation difficult to follow and the example is incomplete. It also seems there are quite a few others having this issue.
Can someone please help?

**Comment by manelclos** [comment]
Hi @DaveJ61, can we see the first line in the csv file you are trying to import?

**Comment by DaveJ61** [comment]
Hi, thanks for the reply. The first line is as follows:-

"id","barcode","partcode","manufacturer","description","quantity","reorderquantity","minquantity","maxquantity","cost","rrp","category"

**Comment by fiterbek** [comment]
@DaveJ61 : re-reading http://django-import-export.readthedocs.io/en/stable/getting_started.html#importing-data , it seems to me that with the first csv line as you stated:

"id","barcode","partcode","manufacturer","description","quantity","reorderquantity","minquantity","maxquantity","cost","rrp","category" 

and the fields in your Meta resource class as they are, you shouldn't have to declare `import_id_fields = ['item_id']` as your csv file already uses the default `id` field. 
Only if you would use `item_id` as column name in your csv you would have to do this. 
Futhermore, I think you don't need any of the declared fields in `import_id_fields`.

The error means import-export is looking for an item_id column in your csv file but can't find it. And sure enough, it isn't present afaics.

**Comment by DaveJ61** [comment]
Hi, thanks for the reply. I have tried every alternative and I believe I have already tried what you have suggested. However, I will try again and let you know.

**Comment by macolo** [comment]
If you override `get_instance` in your `ModelResource` like this it works (even without the 'id' column trick in the CSV):

```
    def get_instance(self, instance_loader, row):
        try:
            params = {}
            for key in instance_loader.resource.get_import_id_fields():
                field = instance_loader.resource.fields[key]
                params[field.attribute] = field.clean(row)
            return self.get_queryset().get(**params)
        except Exception:
            return None
```
I havent had time to look into the why though.

**Comment by 1099094077** [comment]
Thanks,solution to my problem perfectly

**Comment by mohsinmdl** [comment]
Just **create an empty column** namely `id` and then import the same file via Django import_export.

**Comment by kliyes** [comment]
> Just **create an empty column** namely `id` and then import the same file via Django import_export.

thanks, this makes import records with auto-increment id

**Comment by Georege** [comment]
i use 
import_export.__version__ '2.0.2' 
django.__version__ '3.0.4' 
import .xlsx excel data have the same problem!
-----------------------------------------------------
错误
行号: 1 - 'id'
vpc-erymihwm, subnet-naku2y0n, CCDC-测试环境-子网, 10.0.0.0/24, False, False, ap-beijing-3, rtb-mhj5kobp, 2017-12-11 13:08:14, 212, None, None, False, 253, []
Traceback (most recent call last):
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 500, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 277, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 266, in get_instance
self.fields[f] for f in self.get_import_id_fields()
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 266, in <listcomp>
self.fields[f] for f in self.get_import_id_fields()
KeyError: 'id'

行号: 2 - 'id'
vpc-erymihwm, subnet-c4diznbt, CCDC-通用环境-网关子网, 10.0.1.0/24, False, False, ap-beijing-3, rtb-a4j9hs2v, 2017-12-15 19:31:05, 252, None, None, False, 253, []
Traceback (most recent call last):
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 500, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 277, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 266, in get_instance
self.fields[f] for f in self.get_import_id_fields()
File "D:\Anaconda3\lib\site-packages\import_export\resources.py", line 266, in <listcomp>
self.fields[f] for f in self.get_import_id_fields()
KeyError: 'id'

-----------------------------------------------------------------
models.py
from django.db import models
# Create your models here.
class Subnets(models.Model):
    VpcId = models.CharField(max_length=200,  null=True, blank=True)
    SubnetId = models.CharField(
        max_length=20, primary_key=True, null=False)
    SubnetName = models.CharField(max_length=200,  null=True, blank=True)
    CidrBlock = models.CharField(max_length=20, unique=True, null=False)
    IsDefault = models.CharField(max_length=200,  null=True, blank=True)
    EnableBroadcast = models.CharField(max_length=200,  null=True, blank=True)
    Zone = models.CharField(max_length=200,  null=True, blank=True)
    RouteTableId = models.CharField(max_length=200,  null=True, blank=True)
    CreatedTime = models.CharField(max_length=200,  null=True, blank=True)
    AvailableIpAddressCount = models.IntegerField(null=True, blank=True)
    Ipv6CidrBlock = models.CharField(max_length=200,  null=True, blank=True)
    NetworkAclId = models.CharField(max_length=200,  null=True, blank=True)
    IsRemoteVpcSnat = models.CharField(max_length=200,  null=True, blank=True)
    TotalIpAddressCount = models.IntegerField(null=True, blank=True)
    TagSet = models.CharField(max_length=200,  null=True, blank=True)

    def __self__(self):
        return self.CidrBlock

admin.py
from django.contrib import admin
from backend.models import Subnets
from import_export import resources
from import_export.admin import ImportExportModelAdmin

# Register your models here.
class SubnetsResource(resources.ModelResource):

    class Meta:
        model = Subnets
        fields = ('VpcId', 'SubnetId', 'SubnetName', 'CidrBlock', 'IsDefault', 'EnableBroadcast', 'Zone', 'RouteTableId', 'CreatedTime',
                  'AvailableIpAddressCount', 'Ipv6CidrBlock', 'NetworkAclId', 'IsRemoteVpcSnat', 'TotalIpAddressCount', 'TagSet',)
        import_id_fields = ('SubnetId',)

class SubnetsAdmin(ImportExportModelAdmin):
    reosurce_class = SubnetsResource

admin.site.register(Subnets, SubnetsAdmin)
-------------------------------------------------------
i set  import_id_fields = ('SubnetId',) but it doesn't effect！
i try models.py delete SubnetId primary_key and add " id = models.AutoField(primary_key=True)" ! the import success! but, i don't want models structure like this!
any one can help me?

**Comment by chiahul4** [comment]
Similar problem... Need Some help with it
I got KeyError: 'u' instead of 'id'

**Line number: 1 - 'u'
Traceback (most recent call last):
File "C:\Users\poke6\Desktop\Web\env\lib\site-packages\import_export\resources.py", line 639, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Users\poke6\Desktop\Web\env\lib\site-packages\import_export\resources.py", line 334, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "C:\Users\poke6\Desktop\Web\env\lib\site-packages\import_export\resources.py", line 321, in get_instance
import_id_fields = [
File "C:\Users\poke6\Desktop\Web\env\lib\site-packages\import_export\resources.py", line 322, in <listcomp>
self.fields[f] for f in self.get_import_id_fields()
KeyError: 'u'**

##

class Publication(models.Model):
	pub_id = models.AutoField(primary_key=True)
	publication_number = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)
	reference_name = models.CharField(max_length=40, blank=True)
	first_author = models.CharField(max_length=40, blank=True)
        year = models.IntegerField(blank=True, null=True)
	endnote = models.CharField(max_length=255, blank=True)
	title = models.CharField(max_length=255, blank=True)
	publication_type = models.CharField(max_length=40, blank=True)
	irrelevance_reason = models.TextField(blank=True)
	disease_treated = models.CharField(max_length=40, blank=True)
	total_patients = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)
	patients_using_device = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)
	event_description = models.TextField(blank=True)
	country = models.CharField(max_length=40, blank=True)
	objective = models.TextField(blank=True)
	endpoint = models.TextField(blank=True)
	conclusion = models.TextField(blank=True)
	treatment_details = models.TextField(blank=True)
	follow_up = models.TextField(blank=True)
	technical_success = models.CharField(max_length=9, blank=True)
	technical_failure = models.CharField(max_length=9, blank=True)
	technical_statement = models.TextField(blank=True)
	procedural_success = models.CharField(max_length=9, blank=True)
	procedural_failure = models.CharField(max_length=9, blank=True)
	procedural_statement = models.TextField(blank=True)
	morbidity_rate = models.CharField(max_length=9, blank=True)
	morbidity_statement = models.TextField(blank=True)
	recommendation = models.TextField(blank=True)
	evidence = models.CharField(max_length=9, blank=True)
	d = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)
	a = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)
	p = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)
	r = models.DecimalField(max_digits=11, decimal_places=0, null=True, blank=True)

	def __str__(self):
	
	return f'{self.publication_number}, {self.title}, {self.first_author}, {self.year}'

##

class PublicationResource(resources.ModelResource):
	class Meta:
		model = Publication
		import_id_fields = ('pub_id')
		fields = ('pub_id','publication_number', 'reference_name', 'first_author', 'year', 
		'endnote', 'title', 'publication_type','irrelevance_reason', 'disease_treated', 'total_patients',
		'patients_using_device', 'event_description', 'country','objective', 'endpoint', 'conclusion',
		'treatment_details', 'follow_up', 'technical_success','technical_failure', 'technical_statement', 'procedural_success',
		'procedural_failure', 'procedural_statement', 'morbidity_rate','morbidity_statement', 'recommendation', 'evidence', 
		'd','a','p','r',)

class PublicationAdmin(ImportExportModelAdmin):
	list_display = ['pub_id', 'publication_number', 'first_author', 'year', 
		'endnote', 'title', 'publication_type', 'disease_treated', 'total_patients',
		'patients_using_device']
	# form = PublicationForm
	list_filter = ['year', ]
	search_fields = ['first_author','year',]
	resource_class = PublicationResource

admin.site.register(Publication, PublicationAdmin)

**Comment by shaggyfrog** [comment]
`import_id_fields = ('pub_id')`

Did you forget the trailing comma? `('pub_id',)`

**Comment by chiahul4** [comment]
@shaggyfrog OMG Yes!!! Thank you!

**Comment by huxaiphaer** [comment]
> pub_id',)

What was the version number of your package ?

**Comment by 1099094077** [comment]
来信已收到，谢谢！

**Comment by huxaiphaer** [comment]
@shaggyfrog , whats the version number of your package

**Comment by matthewhegarty** [comment]
2.3.0 is an older version - there have been lots of fixes and additions since then.  Can you upgrade to the latest version (2.7.1) and see if you still get the same issue.

**Comment by huxaiphaer** [comment]
Hi @matthewhegarty , I actually did that but same error

**Comment by huxaiphaer** [comment]
I actually upgraded it `2.7.1` but still the same error, I also removed `pub_id` form `exclude` but still the same error

**Comment by matthewhegarty** [comment]
What happens if you try this:

```
fields = ('pub_id',)
import_id_fields = ('pub_id',)
```

If that still doesn't work, step through with a debugger and see where the issue is.

**Comment by huxaiphaer** [comment]
If I do this, it doesn't work reason in my excel file I only have one column names `email` , so this is the error I get :

```
Line number: 1 - __str__ returned non-string (type NoneType)
1.0, huxaiphaeridris@gmail.com
Traceback (most recent call last):
File "/home/idris/Documents/guiomentor/guio-dashboard-backend/venv/lib/python3.8/site-packages/import_export/resources.py", line 703, in import_row
row_result.add_instance_info(instance)
File "/home/idris/Documents/guiomentor/guio-dashboard-backend/venv/lib/python3.8/site-packages/import_export/results.py", line 43, in add_instance_info
self.object_repr = force_str(instance)
File "/home/idris/Documents/guiomentor/guio-dashboard-backend/venv/lib/python3.8/site-packages/django/utils/encoding.py", line 64, in force_str
s = str(s)
TypeError: __str__ returned non-string (type NoneType)
```

**Comment by huxaiphaer** [comment]
Finally it works, I added the fields like this :

```
class CommonResourcesClass(resources.ModelResource):
    class Meta:
        model = models.Applicants
        fields = ('pub_id', 'email',)
        import_id_fields = ('pub_id',)
```
