### ISSUE TITLE
Django ForeignKey Widget to lookup two related objects

### ISSUE THREAD

**Issue by Wolverine7** [django-import-export/django-import-export#924]
Hey all,

I checked the documentation and it describes how the Foreign Key Widget Works. Is there a way I can lookup related objects based on two fields. For example, Book.name, Book.year instead of Book.pk

**Comment by andrewgy8** [comment]
Hey @Wolverine7 ! Looking through the code, it seems like the `ForeignKeyWidget` only supports one field at the moment with a simple [`get`](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L356).  

That's not to say you couldn't implement your own `ForeignKeysWidget`. It looks like the only change you'd have to make is to be able to accept multiple fields and then implement the `clean` method with the `get` querying multiple fields.  

`return self.get_queryset(value, row, *args, **kwargs).get(**{self.field_1: val, self.field_2: val2})`

**Comment by yadalik** [comment]
Is it considered as alternative to combination  `use_natural_foreign_keys=True ` and `use_natural_primary_keys=True` from [https://docs.djangoproject.com/en/2.1/topics/serialization/#serialization-of-natural-keys](https://docs.djangoproject.com/en/2.1/topics/serialization/#serialization-of-natural-keys) for now?

There is no any some sort of "automatic" NaturalPrimaryForeignKeyWidget method for this yet? Something like django-import-export discovers automatically all keys from foreignkeys from models and used all values from model on import (or created if it does not exist), so we don't need to use pk and establish those fields manually for every model?

**Comment by Wolverine7** [comment]
@andrewgy8 
how to use [this](https://github.com/django-import-export/django-import-export/blob/fe491d8af6220e29cf98b84c4d76a0d10e4ce693/import_export/widgets.py#L350)
to limit the foreign key query. 

For example, I am using Author.number instead of the Author.pk as my foreign key  inside of my dataset. For the particular year the Author.number is unique. However, for the next year I might have the same Author.number and I have a year as a foreign key inside of the Author table. 
So I am trying to limit the query return as Author.objects.filter(year=year)

How would I implement this with ForeignKey widget? Thank you in advance

**Comment by hanyce** [comment]
i hava the same problem , how  can i solve it?
