### ISSUE TITLE
How do I add the file used to import data ?

### ISSUE THREAD

**Issue by GiannisIordanou** [django-import-export/django-import-export#925]
I am using `django-import-export` to allow my app's users to import their own data to the database. I have created the appropriate resource with the fields that are needed. It works as it should.

What I am trying to do next is add the used file alongside the users imported data, so I can show the users their imported files and their info.

I am not saving the files to my server, just processing them.

Firstly, I have created a new model called `FileImported` to hold the info for the file used for the import:

 

    class FileImported(models.Model):
         filename = models.CharField()
         name = models.CharField()
         size = models.DecimalField()
         extension = models.CharField()
         date = models.DateField(auto_now_add=True)
         time = models.TimeField(auto_now_add=True)
         timestamp = models.DateTimeField(auto_now_add=True)
         user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    
         def __str__(self):
             return self.filename

Then I had to pass the file info:

    result = imported_resource.import_data(dataset, dry_run=True, raise_errors=False,
                                                                           file_name=import_file_name,
    									   user=self.request.user,
    									   file_size=import_file_size,
    									   file_extension=import_file_extension)

After that, I create a new `FileImported` model object before importing:

    class ImportedResource(resources.ModelResource):
    
       .........

        def before_import(self, dataset, using_transactions, dry_run, **kwargs):
            file_name = kwargs.get('file_name', 'unknown')
            name = os.path.splitext(file_name)[0]
            file_size = kwargs.get('file_size', 'unknown')
            file_extension = kwargs.get('file_extension', 'unknown')
            user = kwargs.get('user', 'unknown')

            file_name_model_object = FileImported .objects.get_or_create(filename=file_name,
    														name=name,
    														size=file_size,
    														extension=file_extension,
    														user=user)
        
I have added the following fields to my model:

    imported = models.BooleanField(default=False)
    imported_file = models.ForeignKey(FileImported, on_delete=models.CASCADE,blank = True,null=True)

The most obvious way is to add the `imported_file` field to the fields in the resource. That way, the user will have to fill that themselves or leave it blank or hidden, I suppose, and then I would fill it later.

I am not sure how to add the newly created `FileImported` model object to each row of my data, if it's not one of the fields.

I am thinking of using `before_save_instance` and do something like:

    def before_save_instance(self, instance, using_transactions, dry_run):
        instance.imported = True
        instance.imported_file = ?

The issue is passing the imported_file info(?).

**Comment by yozlet** [comment]
How about these two steps:

1. Change the last line of `ImportedResource.before_import()` to set an attribute on the resource instance:
```
self.file_imported = FileImported.objects.get_or_create( ...
```

2. Define `ImportedResource.before_import_row()`:
```python
def before_import_row(self, row, **kwargs):
	row['imported_file'] = self.imported_file
```

I use a very similar technique for linking imported rows with other objects that aren't mentioned in the file.
