### ISSUE TITLE
cant be installed by pip

### ISSUE THREAD

**Issue by karinakozarova** [django-import-export/django-import-export#930]
I try to install this package by uisng:
```
bash-4.4# pip3 install django-import-export
Collecting django-import-export
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f179063ef98>: Failed to establish a new connection: [Errno -3] Try again')': /simple/django-import-export/
```
but it's not working. Is there any other way to install `django-import-export`

**Comment by andrewgy8** [comment]
This looks like a network issue. Are you still seeing this behavior? 

I just tried to install `django-import-export` it from pip, and it worked flawlessly.

**Comment by andrewgy8** [comment]
It looks like yesterday around 1:00, PyPi [had an uptick in the number of errors.](https://status.python.org/) 

Im going to close this unless we discover a `django-import-export` specific issue.
