### ISSUE TITLE
Trace error during import

### ISSUE THREAD

**Issue by josircg** [django-import-export/django-import-export#931]
How can I get the error report ? 
I tried the above code but I got no error description.

        resource = resources.modelresource_factory(model=Premiacao)()
        dataset = Dataset()
        arquivo = open(filename, encoding='iso-8859-1')
        dataset.load(arquivo.read(), format='csv')
        result = resource.import_data(dataset, dry_run=True)
        if result.has_errors():
            print('error')
            for row in result.invalid_rows:
                print(row)

**Comment by andrewgy8** [comment]
Hi @josircg ! What do you mean by error report? You mean the error page right before import?

**Comment by josircg** [comment]
Hi @andrewgy8 ! I'm trying to import the file via console but the import_data informs that there are erros but don't specify which errors. I tried with code:

    if result.has_errors():
        print('error')
        for row in result.invalid_rows:
            print(row)

But invalid_rows is empty. I'm asking what is the correct to way to get the error list.

**Comment by yozlet** [comment]
The errors you want are in `result.base_errors()` (problems with the whole import) and `result.row_errors()` (errors with specific rows). These will both return lists of error objects. For an example of how to inspect and print them, [take a look at this chunk of a PR](https://github.com/django-import-export/django-import-export/blob/2dbf8a3423bb7bd7919168e76cd45b143cdaedd2/import_export/management/commands/import_file.py#L74-L84) (still in progress).
