### ISSUE TITLE
Performance : Prevent DOM reflow on import preview

### ISSUE THREAD

**Issue by franz-see** [django-import-export/django-import-export#932]
Currently, when the import preview is huge (i.e. thousands of rows), it forces the browser to do substantial DOM reflow. This greatly slows down the browser as it tries to resize the preview table (and the whole page) over and over again as it prints new DOM elements. 

To improve performance, you can set `table.import-preview`'s `display` to `none` first, and then set it to `table` later on after the whole table has been loaded. 

That is, add this before the table is loaded

```
<style>
  table.import-preview {
    display:none;
  }
</style>
```

(or add this in `import.css`), and then add at the end of `import_export/import.html`

```
  <script type="text/javascript">
    (function() {
      var import_previews = document.querySelectorAll('table.import-preview')
      for (var i = 0; i < import_previews.length; i++) {
        import_previews[i].style.display = 'table'
      }
    })();
  </script>
```

**Comment by andrewgy8** [comment]
You lost me at DOM (🤣 ), but anything to speed up table rendering sounds great! Anybody care to submit a PR for this?

**Comment by andrewgy8** [comment]
Any idea what the downsides to this would be?

**Comment by bmihelac** [comment]
I understand there can be a lot of reflow but not sure about hiding and displaying table.  Could `table-layout: fixed;` help?

**Comment by franz-see** [comment]
@andrewgy8 the down side is if javascript is disabled, then the preview will never show up :)

**Comment by franz-see** [comment]
@bmihelac i'll try that out and will let you know how it goes :) thanks !

**Comment by franz-see** [comment]
@bmihelac i just tried

```
<style>
  table.import-preview {
    table-layout: fixed;
  }
</style>
```

but the whole page was still getting longer and longer as new rows are being flushed by the HTTP response

**Comment by yozlet** [comment]
How about setting `table.import-preview`'s display to `none` using JS, so nothing changes for JS-disabled users, but everyone else gets smoother loading?
