### ISSUE TITLE
URGENT - is there a way I can limit the queryset ?

### ISSUE THREAD

**Issue by SanchitVerma** [django-import-export/django-import-export#935]
I am importing data to Book model and inside of the Book model I have a foreign key to Author, I am using Author.number instead of the Author.pk. Now the problem I am facing is that for the giving year Authors have unique number, while next year they will have different year foreign key but same number. I was wondering is there a way I can limit the queryset and how should i do it? 

Do i use? class FullNameForeignKeyWidget(ForeignKeyWidget):
    def get_queryset(self, value, row):
        return self.model.objects.filter(
            first_name__iexact=row["first_name"],
            last_name__iexact=row["last_name"]
        )

**Comment by yozlet** [comment]
@SanchitVerma Something similar to that, yep. If you have an `author_number` column and an `author_year` column, then you want a custom `ForeignKeyWidget` like:

```python
class AuthorForeignKeyWidget(ForeignKeyWidget):
    def get_queryset(self, value, row, *args, **kwargs):
        return self.model.objects.filter(
            author__number__iexact=row["author_number"],
            author__year__iexact=row["author_year"]
        )
```

And then include it in your custom `ModelResource` subclass like so:

```python
author = fields.Field(
        attribute="author",
        column_name="author_number",
        widget=AuthorForeignKeyWidget(Author, "number")
    )
```

Note, however, that:
1. I haven't tested this, and it will most likely need tweaking
2. These kinds of questions are much better asked on StackOverflow, though... hold on, is [this your question](https://stackoverflow.com/questions/55437638/how-to-import-django-import-using-foreign-key-widget)?

**Comment by andrewgy8** [comment]
Please don't title an issue as "Urgent" and then abandon it. Thanks.

**Comment by SanchitVerma** [comment]
It was an urgent issue back in March and it was answered back then. I should have marked it closed after that. It wasn't "abandoned".
