### ISSUE TITLE
Bug in DateTimeWidget which leads to incorrect timezone import

### ISSUE THREAD

**Issue by lukasewolf** [django-import-export/django-import-export#942]
Hi all,
thanks for this great project!

I'm living in central europe with day light saving (UTC+1 or UTC+2).  My exported DateTimeFields are written to json as UTC (as others have noted, eg. in #813). According to the code this step is not influenced by USE_TZ.
On import with USE_TZ = True, they are converted to aware datetimes with my default timezone, which is  incorrect (because they are UTC times!) and leads to dates jumping 1 or 2 hours back in time. If I repeat import/export cycles this will move them back in time even further...

_Related issues:_
Import does not adjust for timezone #465
Export not timezone sensitive #813

_Possible solution:_
Making the imported datatime timezone-aware but with the timezone correctly set to UTC gives me the expected results and correctly imported DateTimeFields (see diff below).
Sadly I've not enough experience to predict possible side effects of this change which is working for my situation.

```
@@ -182,8 +184,7 @@ class DateTimeWidget(Widget):
                 if settings.USE_TZ:
                     # make datetime timezone aware so we don't compare
                     # naive datetime to an aware one
-                    dt = timezone.make_aware(dt,
-                                             timezone.get_default_timezone())
+                    dt = timezone.make_aware(dt, timezone.utc)
                 return dt
             except (ValueError, TypeError):
                 continue
```

Thanks a lot for all your hard work!
Regards, Lukas Wolf

**Comment by octomaria** [comment]
Hi,

is there a reason to prefer `timezone.get_default_timezone()` over `timezone.get_current_timezone()` here?
https://github.com/django-import-export/django-import-export/blob/3c082f98afe7996e79f936418fced3094f141c26/import_export/widgets.py#L182-L186

With `get_current_timezone()` one could override the default timezone for import/export operations only, if needed. (E.g. wrapping those operations with [timezone.override](https://docs.djangoproject.com/en/stable/ref/utils/#django.utils.timezone.override).) 
And if there is no need to override the default timezone, `get_current_timezone()` will return the default one.
(In the example above, the default timezone would be Central European, with UTC activated when importing data.)

Or maybe it would be possible to add an optional timezone parameter to the DateTimeWidget?
