### ISSUE TITLE
Proposal: make the Export action similar to Delete action

### ISSUE THREAD

**Issue by frnhr** [django-import-export/django-import-export#945]
I made some tweaks to django-import-export locally and I'm wondering if there is interest in a PR. (my code is not quite PR-ready right now, hence my asking).

The tweak is to add a regular "Export" action that does not need an additional dropdown for the formats. Instead, the formats are chosen on a separate view, similar to how the delete action shows a separate view for confirmation.

![Select_contact_to_change___urbandanish_solutions](https://user-images.githubusercontent.com/1173748/56373578-89ecd600-6201-11e9-91cc-b7dd5f7fc59e.jpg)

Then after clicking "Go" we see an intermediate view. The view already exists in django-import-export, it is being reused here with minor changes:

![Export___urbandanish_solutions](https://user-images.githubusercontent.com/1173748/56373675-c15b8280-6201-11e9-85ca-cc6ec89feccb.jpg)

Finally, I'm currently sending a download link via messages, but it might be better to use some JS to trigger the download, not yet sure on this point:

![Select_contact_to_change___urbandanish_solutions](https://user-images.githubusercontent.com/1173748/56373778-02539700-6202-11e9-9cd4-e12242584676.jpg)

So, any interest in having a PR with this? Currently I'm implementing this as an additional mixin, leaving the other action as is.

-----

BTW, my reason for doing this tweak is that I'm using a little JS hack that turns the action dropdown into a bunch of buttons. The extra dropdown wasn't really working well with this:
https://github.com/frnhr/django-admin-action-buttons
Shameless plug: that's my app ☝️ 

But I'm guessing this approach is simple to make compatible with other apps (Grappelli, etc.)

**Comment by andrewgy8** [comment]
Hmm, very interesting @frnhr .  IMHO, I see nothing wrong with this in the import-export project as it falls into its scope as far as I am concerned.  

Personally, I would welcome a PR! You can always submit it and then see what others have to say.
