### ISSUE TITLE
ExportActionModelAdmin not working with Django 2.2

### ISSUE THREAD

**Issue by lorenzomorandini** [django-import-export/django-import-export#947]
As title, ExportActionModelAdmin will stop working in Django 2.2 since admin actions are no longer collected from base ModelAdmin classes.

https://docs.djangoproject.com/en/2.2/releases/2.2/#admin-actions-are-no-longer-collected-from-base-modeladmin-classes

**Comment by lusinh** [comment]
@lorenzomorandini Do you test it? It still working!
ExportActionModelAdmin does not override actions field. So, It still working.
Test code, run it in shell:
```
from import_export.admin import ExportActionModelAdmin
ExportActionModelAdmin.actions
```
and the result is:
```
[<function ExportActionMixin.export_admin_action at 0x7ff1e0f32840>]
```

**Comment by lorenzomorandini** [comment]
To me it seems that actions field gets overrided
https://github.com/django-import-export/django-import-export/blob/52f0a1fc092fec21a0239b37ef99498277e50cb4/import_export/admin.py#L568

**Comment by lusinh** [comment]
@lorenzomorandini I think you must change code, follow the django release 2.2.
Example:
When you need add new action, you need recall action from previous model:
```
class XYZ(ExportActionModelAdmin):
    actions = ExportActionModelAdmin.actions + ['your_action']
```

**Comment by lorenzomorandini** [comment]
That's true. I guess then it's sufficient to update the documentation

**Comment by lorenzomorandini** [comment]
Shouldn't we change ExportActionModelAdmin so it's:

    actions = admin.ModelAdmin.actions + [export_admin_action] ?

Otherwise simply doing:
    
    class MyModelAdmin(ExportActionModelAdmin):
        ...

will not work and MyModelAdmin will not have export_admin_action

**Comment by shanedicks** [comment]
I'm seeing this same issue with the ImportExportActionModelAdmin as well for django 2.2. Export is just not listed in the actions menu on the admin site.
