### ISSUE TITLE
export and import header field using locale language?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [django-import-export/django-import-export#948]
As we know in django-admin, if you specify
```python
list_display = ('classroom', 'course', 'start_time')
```
The displayed text on the model view page depends on the locale the admin user used, not necessary English 'classroom', 'course', ...

However, in django-import-export, the exported header is always English. For example, if you specifiy
```python
fields = ('name')
```
The exported header is always called 'name', regardless you use **custom_name**
```python
name = models.CharField(_('custom_name'), max_length=20)
```
For import, same problem exits.

For non-English secretaries, it is not convenient, in my opinion.

**Comment by andrewgy8** [comment]
Im curious if you are you using `django-model-translations` package?

**Comment by zhaofeng-shu33** [comment]
Maybe `django-model-translations` can do the job.
