### ISSUE TITLE
Mix package and default signals

### ISSUE THREAD

**Issue by jiargei** [django-import-export/django-import-export#949]
I want to use signals from

- django-import-export while importing csv
- django signals while using the admin form

in my signal method i have a api post call which should just be triggered once. So how to make sure i can run the django signal while using the admin form. And regardless of that, when I import a csv the django-import-export signal should be triggered.

It is important that the api call just happens once!

Summarized:

Single Entry via Admin Form -> Normal Signal -> API Call
CSV Import -> Django-Import-Export Signal -> API Call

**Comment by andrewgy8** [comment]
Can you trigger the signal with the `after_import_row` hook? https://django-import-export.readthedocs.io/en/latest/import_workflow.html

**Comment by jiargei** [comment]
Hej! Sorry for that late reply on that issue...
How does this solve the issue?
If i declare a signal for a "normal" input via the admin this will work over the post_save receiver. The import_export will still trigger this becaus it calls the save method even if i want to confirm the import.
