### ISSUE TITLE
Form control export fields for writing to csv

### ISSUE THREAD

**Issue by ccsv** [django-import-export/django-import-export#956]
Is it possible to have a form which the user fills out with booleans that determines which columns get exported? If so are there examples using a view?

**Comment by andrewgy8** [comment]
You mean dynamically selecting the fields in the ResourceClass?

**Comment by ccsv** [comment]
Yes

**Comment by andrewgy8** [comment]
As far as I am aware, at the moment there is no option to do this. It would require a separate view. It could be done though via a multi select and then dynamically setting the `export_order` in the [`get_fields()`](https://github.com/django-import-export/django-import-export/blob/master/import_export/resources.py#L233) function call. 

Let us know how far you get with this!

**Comment by gggfreak2003** [comment]
I dont know if the question is still from interest but I found a workaround which works quiet good for me. First overwrite the `get_export_order` function:

```
class SiteResource(resources.ModelResource):
        ...
        def get_export_order(self):
                order = tuple(k for k in self._meta.export_order if k in self.fields)
                return order + tuple(k for k in self.fields if k not in order)
```

Now you could remove the field from the instance
```
sites_resource = SiteResource()
sites_resource.fields.pop(FIELDNAME, None)
dataset = sites_resource.export(queryset)
```

and you will get only the not remove fields.

Have I overseen some side effects?
