### ISSUE TITLE
Functionality request: Integration with wagtail

### ISSUE THREAD

**Issue by adsk2050** [django-import-export/django-import-export#960]
does django-import-export work well with  wagtail? It works as far as I have used it. But it doesn't have an admin interface for wagtail.

**Comment by andrewgy8** [comment]
Not sure as I have never used wagtail. But PR's are always welcome!

**Comment by jturmel** [comment]
@adsk2050 I am looking to do this myself, if you install and setup an import/export resource and attach it to a Wagtail modeladmin does the action show up in the header?

**Comment by adsk2050** [comment]
> @adsk2050 I am looking to do this myself, if you install and setup an import/export resource and attach it to a Wagtail modeladmin does the action show up in the header?

I didn't understand. could you please elaborate @jturmel

**Comment by SeriForte** [comment]
@adsk2050 If you do not need an integration into wagtail admin, you could use it in the django admin.
I faced a similar problem when I needed a import / export tool for my simple django models, that I include into my wagtail setup.

here is what I ended up with:

1. `pip install django-import-export` 
2. in **settings.py** add `import_export`
3. in **admin.py** add a `resources.ModelResource` class acc. to the [docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#creating-import-export-resource)
4. in **admin.py** add a `ImportExportModelAdmin` class acc. to the [docs](https://django-import-export.readthedocs.io/en/latest/getting_started.html#admin-integration)

Note: if you already have a `ModelAdmin` from Wagtail to access it from there, 
you will now have two "Admin-Classes"

To access the admin pages:
wagtail admin: http://127.0.0.1:8000/admin
django admin: http://127.0.0.1:8000/django-admin/

In the django-admin you could now use the import and export functions.

@jturmel the integration into Wagtails ModelAdmin seems not to work, at least not with my configuration.

**Comment by jturmel** [comment]
@SeriForte yeah it doesn't work, I did more research to better understand Wagtail and figured out that how it's handling it's Admin stuff is completely different so each library (like django-import-export) would need to provide a way to work in Wagtail.

I've resorted to using Wagtail Admin for users who need to manage content, and then still use Django Admin.
