### ISSUE TITLE
Help to import a model data with a ForeignKey to self-model

### ISSUE THREAD

**Issue by eamigo86** [django-import-export/django-import-export#962]
Hello, first of all, thank you for your great work with this package. 

I'm new working with this package and have a problem and no found solution anywhere, I have not seen anything in the documentation. My problem trying to import a previously exported model data (JSON) from admin, when I the model that has a ForeignKey relationship with itself:
Example model:
```python
class ClassA (models.Model):
     name = models.CharField(max_length=200, blank=True)
     field_x = models.ForeignKey ("self", null=True, blank=True, on_delete=models.SET_NULL)
```
Example exported data.json:
```json
[{
    "id": 1,
    "name": "Object1",
    "field_x": 2
},{
    "id": 2,
    "name": "Object2",
    "field_x": ""
}]
```
Get the following output:
```bash
ProjectX.appA.models.DoesNotExist: ClassA matching query does not exist.
```
Any advice? Thanks

**Comment by dstrohl** [comment]
I have this same challenge... is there a way of forcing a multi-stage import process, where it first goes through and imports all of the objects, then goes through and updates the link?
