### ISSUE TITLE
Using Import Export along with Django-reversion in Django Admin site

### ISSUE THREAD

**Issue by sukeshlaghate** [django-import-export/django-import-export#964]
Hi,

I am trying to use Import Export functionality for bulk import of users in Django Admin site. I also want to track version and history of the CustomUser model and hence have inherited CustomUser model from VersionAdmin. 

The issue I am facing is if I multi inherit Custom User model from Version admin and ImportExportModelAdmin then I am not able to see import export buttons. See attached snapshot
![Django_admin_site](https://user-images.githubusercontent.com/25061957/60441509-c2168900-9c34-11e9-942b-4f755a261981.PNG)

 My code looks like following

```
from django.contrib import admin
from django.contrib.auth import get_user_model
from reversion.admin import VersionAdmin

# required for import export option in Admin site for bulk import export

from import_export.admin import ImportExportModelAdmin

from users.forms import CustomUserCreationForm, CustomUserChangeForm
from users.models import (CustomUser, Company)

# Register your models here.


class CustomUserAdmin(VersionAdmin, ImportExportModelAdmin):
    add_form = CustomUserCreationForm
    form = SCustomUserChangeForm
    model = CustomUser
    list_display = ['email', 'username','first_name', 'last_name',]


admin.site.register( CustomUser, CustomUserAdmin )
```

However if I invert the inheritance order that is  CustomUserAdmin(ImportExportModelAdmin, VersionAdmin) then I see import export buttons but "Recover Deleted Users" button disappears as shown in this snapshot
![Django_admin_site2](https://user-images.githubusercontent.com/25061957/60441439-972c3500-9c34-11e9-9ef8-cf7b88c84553.PNG)

Request you to point in right direction as to how to correctly use django-import-export with django-reversion in admin site 

Thanks in advance for helping out.

**Comment by ababic** [comment]
@sukeshlaghate what you're seeing is the result of both classes overriding certain methods/attributes on Django's ModelAdmin class to get the buttons to display. To use the two together, you'll probably have to override those methods/attributes on your `CustomUserAdmin` class to combine the method logic or attribute values of both subclasses. 

Even with this problem solved, you may well face further issues if the left-most class overrides other attributes/methods overridden by the other (e.g templates). 

It would be incredibly difficult to rewrite the `ImportExportModelAdmin` class in a way that would never conflict this way with other classes. It's not something a maintainer of any app can realistically make a promise on.

**Comment by Sinek8** [comment]
I solve this by using proxy models. By using proxy models, one can register same model more than once to the django admin panel. You can register one with reversions and one with this app.
