### ISSUE TITLE
from_encoding does not work

### ISSUE THREAD

**Issue by aerospatiale** [django-import-export/django-import-export#965]
I see there are plenty of other issues on this topic but they don't appear to be answered.

I am having issues with csv files containing the BOM at the start. So for example, with a header of id,location, start_time,end_time,break_duration in my file, I am seeing the following error, even if I set the from_encoding to 'utf-8-sig':

`Line number: 1 - "Column 'id' not found in dataset. Available columns are: ['\\ufeffid', 'location', 'start_time', 'end_time', 'break_duration']"`

```
class ShiftResource(resources.ModelResource):
    class Meta:
        model = Shift
        fields = ('id', 'location', 'start_time', 'end_time', 'break_duration')

class ShiftAdmin(ImportMixin, admin.ModelAdmin):
    from_encoding = 'utf-8-sig'
    resource = ShiftResource
```

**Comment by aerospatiale** [comment]
@andrewgy8 Do you guys need more info? Is this a known issue? Model import/export doesn't appear to work at all.

**Comment by raphodn** [comment]
I have the exact same problem (with a csv exported from Notion.so).
My current hack is to use the `before_import_row()` method:
```
def before_import_row(self, row, **kwargs):
        row["id"] = row["\ufeffid"]
```

**Comment by mgrdcm** [comment]
@raphodn Can you try using a custom format for the import and overwriting the `get_read_mode` method?

```python
class fixencodingCSV(base_formats.CSV):
    def get_read_mode(self):
        return 'rb'
```

**Comment by raphodn** [comment]
Thanks for your help.
I copied your class, commented out my overwriting of `before_import_row`, and overwrote `get_import_formats` with the code below: (is this correct ?)
```
def get_import_formats(self):
        return [fixencodingCSV]
```
Anyway the id column is still not correctly imported
(the rows are seen as new instances when they should be existing instances. and doing a `print(row)` in `before_import_row` shows `OrderedDict([('\ufeffid', '140'), ...`)
