### ISSUE TITLE
Feature Request: Update/New Only

### ISSUE THREAD

**Issue by mattburlage** [django-import-export/django-import-export#972]
This feature would only consider importing rows that either create new entries or update existing ones (or both) depending on the setting selected. There could be a 'Filter' drop-down that lets users say 'Import All,' 'Update Only,' or 'New Only.'

I will try to take a stab at this when I'm able.

**Comment by beruic** [comment]
This would solve so much for me. i frequently clean an import file to avoid making new entries.

**Comment by beruic** [comment]
I vote for reopening this one.
