### ISSUE TITLE
JSONField import

### ISSUE THREAD

**Issue by Sqvall** [django-import-export/django-import-export#973]
What i need do, than import data in FSONField?

I use:
```python
class ProductResource(resources.ModelResource):
    category = fields.Field(attribute='category', column_name='category',
                            widget=ForeignKeyWidget(Category, 'name'))
    brand = fields.Field(attribute='brand', column_name='brand',
                         widget=ForeignKeyWidget(Producer, 'name'))
    properties = fields.Field(attribute='properties', column_name='properties', widget=JSONWidget)

    class Meta:
        model = Product
        fields = ('id', 'name', 'price', 'category', 'brand', 'properties', 'description')
        export_order = ('id', 'name', 'price', 'category', 'brand', 'properties', 'description')

```
And i have Error: 
```Object of type Product is not JSON serializable```
As I understand, need point field name, but JSONWidget not takes arguments.
If i not use JSONWidget. Export works great, but import as string data in JSONField.
May be you can help me, what should i use to fix it, if this is possible?

**Comment by andrewgy8** [comment]
Hey @Sqvall ! Any chance you can post a bit of the data you are trying to import. Its hard to debug this without any relevant data. 😉

**Comment by Sqvall** [comment]
@andrewgy8 
Oh sorry, this example data wich i need import
```json
"properties": {
        "color": "Black",
        "invertor technology": false,
        "service area, m²": 24
    },
```

**Comment by jcmundy** [comment]
I have the same question.  I have one column in a csv that is json being imported to a JSONField.  I set up my resource and widget this way and get the error Object of type 'Annotation' is not JSON serializable  - Annotation is the model name (not the column name).  Thank you for your help.

**Comment by abdulghaphor** [comment]
Guys, I have the same question also.

Any idea how to solve this issue?

**Comment by ton77v** [comment]
This works for me:
https://github.com/django-import-export/django-import-export/issues/285#issuecomment-312020642

Although I had so switch from CSV to TSV because otherwise commas inside JSON raise InvalidDimensions exception during the import
