### ISSUE TITLE
Performance: slow export with ForeignKeys id

### ISSUE THREAD

**Issue by PetrDlouhy** [django-import-export/django-import-export#974]
I tried to investigate slow export on my model. I found out, that if I write `dehydrate` function on `ModelResource` like this:
```python
    def dehydrate_user_profile(self, search_report):
        return search_report.user_profile_id
```

The export rapidly speeds up. I think, that `django-import-export` has bad method of getting the `id` values for ForeignKeys.

The bad performance is similar to this (notice the `.` instead of `_`)
```python
    def dehydrate_user_profile(self, search_report):
        return search_report.user_profile.id
```

**Comment by andrewgy8** [comment]
Hey @PetrDlouhy ! Thanks for the investigation. How much of an increase would you say? Would you like to submit a PR with some of these changes?

**Comment by PetrDlouhy** [comment]
@andrewgy8 In my case the increase was extreme - when I try with just 1300 records it is almost instant vs. 20 seconds.

I investigated a little bit further. The problem is, that on line `90` in `fields.py` in  `get_value()` function the value of foreign key is fetched by:
```
value = getattr(value, attr, None)
```
If the value is not already cached or not fetch by the queryset with `select_related`, it will trigger new DB query for every row of the export.
That value is further processed by `Widget.render()` where the value of certain key is fetched from the related object. This is unnecessary, if the key we want is primary key of the ForeignKey relation.

I am not sure, how to fix this properly.
One method might be to detect, that we want to fetch `pk`/`id` key and bypass the `get_value()->Widget.render()` mechanism.
Downside is that it might change behaviour if one of these function was overridden by user.

Second method is to automatically include `select_related` to the queryset.
Upside is that it can greatly improve performance not only for primary keys, but also for related fields. 
Downside is that it might not work for some user modified querysets properly. Also in some cases it can lead to slowdown, because the `select_related` would increase the query complexity and/or fetch unwanted data (which might be solved by using `only`).

**Comment by unixconky** [comment]
Any ideas how to improve this?

**Comment by jfilter** [comment]
A hotfix for now, overriding [`get_export_queryset`](https://django-import-export.readthedocs.io/en/latest/api_admin.html#import_export.admin.ExportMixin.get_export_queryset):

```python
  def get_export_queryset(self, request):
      return (
          super(YourModelAdmin, self)
          .get_export_queryset(request)
          .select_related()
      )
```

**Comment by mikaraunio** [comment]
@jfilter 's answer works great when you're exporting from the admin. If you'll be exporting from the shell or your views as well, you could override `get_queryset` directly on your `Resource`, which should cover all cases:

```python
def get_queryset(self):
    return super().get_queryset().selected_related('RELATED_MODEL1', 'RELATED_MODEL2', ...)
```

Maybe amending the Getting started section of the docs to suggest users do this if they're doing related lookups could be all that's needed?

Alternatively, an idea could be to mirror ModelAdmin's `list_select_related` in `Resource`, maybe as follows:

```python
class ModelResource(Resource, metaclass=ModelDeclarativeMetaclass):
    ...
    def get_queryset(self):
        """
        Returns a queryset of all objects for this model. Override this if you
        want to limit the returned queryset.
        """
        qs = self._meta.model.objects.all()
        select_related = getattr(self, 'export_select_related`, None)
        if select_related:
            qs = qs.select_related(*select_related)
        return qs

class MyResource(resources.ModelResource):
    export_selected_related = ('RELATED_MODEL1', 'RELATED_MODEL2', ...)
```

Can do a proper PR later if this looks sensible.

**Comment by matthewhegarty** [comment]
@mikaraunio Thanks for this update.  I feel that updating the 'Getting started' docs would be a great way to move this forward.  If you are able to submit a PR for this documentation update that would be appreciated.

**Comment by matthewhegarty** [comment]
See also #1715

**Comment by matthewhegarty** [comment]
@PetrDlouhy Is now a good time to resolve this issue?
