### ISSUE TITLE
Add Meta fields dynamically

### ISSUE THREAD

**Issue by brianmoran** [django-import-export/django-import-export#982]
I have use-case where I need to set the Meta fields dynamically. Since they are a tuple, they are immutable and cannot be changed. Is there a workaround to set fields? 

```
pr = ProductResource()
# meta fields are set to None
pr._meta.fields = ('product_id', 'sites',) 
print(pr.export(pr._meta.model.objects.filter(pk__in=["AN-43859396-000"])))
# all fields are printed out
```

**Comment by RobertAKARobin** [comment]
I'd like to revive this.

**Comment by pokken-magic** [comment]
So from what I can tell the metaclass copies the ResourceOptions fields values wind up getting stored in a dictionary in the 'fields'  based off the __new__ magic method on the DeclarativeMetaclass.

Keeping it very simple I think that you could modify the fields attribute of your resulting resource and remove or add fields as you like; if you did something like stored a copy of the original fields you could then do a dictionary comprehension to reassign them. 

`
pr = ProductResource()
original_fields = pr.fields
desired_fields = ( 'product_id', 'sites', ) 
pr.fields = { 
    field_name : original_fields.get(field_name)
    for field_name in desired_fields
}
`

This seems to work pretty smoothly in limited testing.
