### ISSUE TITLE
Doesn't seem to work with django-object-tool

### ISSUE THREAD

**Issue by alexei** [django-import-export/django-import-export#987]
We're using both [django-import-export/django-import-export](https://github.com/django-import-export/django-import-export) and [Xavier-Lam/django-object-tool](https://github.com/Xavier-Lam/django-object-tool) in our project and it appears we can only enable one or the other.

We have a model admin that inherits from `import_export.admin.ExportActionModelAdmin` and overrides `change_list_template = ExportMixin.change_list_template` (it appears `ExportActionModelAdmin` enables the action but disables the "Export" button). The end result is the object tool doesn't show up, unless we reset `change_list_template` to the original value.

Perhaps django-import-export could use django-object-tool to display the "Export" button?

**Comment by andrewgy8** [comment]
Hey @alexei ! My guess is that it overrides whats in that html tag. There might be a way to have both if you rewrite the template and use specific tags. 

ATM, Im hesitant to put another dependency into this project unless we absolutely need it or it is highly desired by the community.
