### ISSUE TITLE
Django 3 Error

### ISSUE THREAD

**Issue by nyssance** [django-import-export/django-import-export#988]
from django.utils import six
ImportError: cannot import name 'six' from 'django.utils'

**Comment by napsterv** [comment]
It appears that this is a django issue and not django-import-export problem.

**Comment by nyssance** [comment]
@napsterv
https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis

django.utils.six - Remove usage of this vendored library or switch to six.

**Comment by napsterv** [comment]
> @napsterv
> https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis
> 
> django.utils.six - Remove usage of this vendored library or switch to six.

Alright. Got it.

**Comment by andrewgy8** [comment]
In the end, is this a django issue or a django-import-export issue?

**Comment by nyssance** [comment]
@andrewgy8 A django-import-export issue.

**Comment by unchris** [comment]
It looks like it's being fixed in the 2.0 branch.

**Comment by max-block** [comment]
any progress with it?

**Comment by andrewgy8** [comment]
2.0 was released yesterday. Let us know how it goes.
