### ISSUE TITLE
How to use permissions?

### ISSUE THREAD

**Issue by FelipeVelasquez1802** [django-import-export/django-import-export#990]
I do not understand how I should implement the global variable IMPORT_EXPORT_EXPORT_PERMISSION_CODE to avoid the "export" button to groups that do not have permissions. Can you give an example, please?

**Comment by stiko** [comment]
```
class Book(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=60)

    class Meta:
       permissions = (('import', 'Can import'), ('export', 'Can export'))
```
Then run `makemigrations` and `migrate`
This will generate the permissions as per django documentation, but `django-import-export` isn't really working with anything but the default.

**Comment by scream4ik** [comment]
With custom permissions no problem.
When you set for example `view` permission, it means `view_book` permission. If you want to use custom permission, you need set for example `IMPORT_EXPORT_EXPORT_PERMISSION_CODE = 'import' in your settings. And in your `Book` model it will be `import_book` instead of `import` permission

**Comment by hardiksondagar** [comment]
Can someone share working code example?

**Comment by carlosdorneles-mb** [comment]
For the permissions to work you need to do the following:

> ```
> class Book(models.Model):
>     id = models.AutoField(primary_key=True)
>     name = models.CharField(max_length=60)
> 
>     class Meta:
>        permissions = (('import', 'Can import'), ('export', 'Can export'))
> ```
> 
> Then run `makemigrations` and `migrate` This will generate the permissions as per django documentation, but `django-import-export` isn't really working with anything but the default.

After doing this you must go to the project settings and add the following environment variables:

```
IMPORT_EXPORT_IMPORT_PERMISSION_CODE = "import"
IMPORT_EXPORT_EXPORT_PERMISSION_CODE = "export"
```

**Comment by fertek** [comment]
Thanks, Carlos, for the code sample! I would like to add that the **permission codename** is not optional. 

Does not work:

```
class VeryLongModelName(models.Model):
    …

    class Meta:
       permissions = [("import_shortname", "Import …")]
```

Does work:

```
class VeryLongModelName(models.Model):
    …

    class Meta:
       permissions = [("import_verylongmodelname", "Import …")]
```

Explanation:

- https://github.com/django-import-export/django-import-export/blob/e5f5b3cb842b8a2336fc4a6927b2297223fc2a72/import_export/admin.py#L130
- https://github.com/django/django/blob/8edaf07a28a3e3848ab1edbdcd2fdc25e6bd6015/django/contrib/auth/__init__.py#L253
- https://stackoverflow.com/questions/64984409/understanding-model-permissions-in-django-3-1
