### ISSUE TITLE
Usability of ImportMixin

### ISSUE THREAD

**Issue by chrismerck** [django-import-export/django-import-export#993]
Latest docs describe an amazing `ImportMixin` where we can set specific fields for all rows. But it seems that it is not documented and only partially implemented in `v1.2.0`. Specifically, `get_form_kwargs` is never called.

How baked is `ImportMixin`?

**Comment by andrewgy8** [comment]
Hi @chrismerck, can you define "baked"? And what would you like to see? Care to submit a PR with changes you envision?

**Comment by chrismerck** [comment]
Sorry, my post was terribly unclear. I'll take it that the presence of the **Customize admin import forms** section  in the "latest" docs means that it should work on `v1.2.1.dev0`. I was just uncertain as I did not get it to work immediately and thought I may need to wait for a release version.
