### ISSUE TITLE
Default value set to ManyToManyField is not taken

### ISSUE THREAD

**Issue by SebaRossi94** [django-import-export/django-import-export#999]
Hello there i'm having an issue setting a default value to a ManyToMany field when importing from a file. If i leave the field blank it imports it with no value even with the model default value set to "Basico". Only after importing it succesfully when i enter some data i uploaded and try to save it with no value selected it reports an error
`productos = fields.Field(
    column_name = "Productos",
    attribute = "productos",
    widget = ManyToManyWidget(model = Producto, field = "Name"),
    default = (Producto.objects.get(Name = "Basico"))
    )`
I don't know if the problem is the type i'm setting as a default variable or what. Please if anyone could help me i would appriciate that.

**Comment by accordioff** [comment]
Better late than not at all. Please have a look at this example how to use pk-values as defaults:
[LINK](https://www.rdegges.com/2010/populating-default-manytomany-field-values-in-django/)
